### ISSUE TITLE
3.0.4 import fails on 19.0.0 beta5

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1000]
Error log sent to you.  Import fails completely.

**Comment by marcelklehr** [comment]
mmmh, where did you get that backup from?

**Comment by sunjam** [comment]
From myself on a stable hosted provider using the export command.  It was exported before I ever touched any of the version 3 betas on a local device, which I've used for testing.

Unfortunately, my provider updated their Bookmarks app yesterday and now seems to have hosed their bookmarks data for all users completely.

**Comment by marcelklehr** [comment]
The f-droid links in that file are garbled for some reason. Hopefully those are the only ones, then you should be able to fix that by hand.

> Unfortunately, my provider updated their Bookmarks app yesterday and now seems to have hosed their bookmarks data for all users completely.

Oooph. This release really is way more stressful than anticipated... :(

**Comment by sunjam** [comment]
Good news: the rest of my backup worked!  I stopped seeing any output, but kept the tab open and everything has more or less imported. :)
