### ISSUE TITLE
Import into selected folder. (Possibility to import without `Imported Bookmarks` folder.)

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1002]
I'm wondering if it would be possible to import without the creation of an `Imported Bookmarks` folder, because I'm importing into an instance that has no bookmarks at all.  So, although I realize it is there for a reason, I'd appreciate being able to not need that folder... if it is do-able.  Thanks for considering.

If it isn't possible, I'd like to clarify the process to move books out of this new folder as quickly and effectively as possible.  Perhaps someone reading this issue can help clarify it for me! :heart:

**Comment by marcelklehr** [comment]
I'll rephrase this issue as "Import into user-selected folder". This is possible and IMO a good improvement.

**Comment by sunjam** [comment]
My thought was dump into root directory, but perhaps I could do this as user selectable (much like floccus).

**Comment by marcelklehr** [comment]
Yep, being able to select the folder to import into would allow dumping into the root folder while also covering the original use case for the 'imported bookmarks' folder.

**Comment by marcelklehr** [comment]
Fixed.
