### ISSUE TITLE
After closing `Search`, re-directed to root folder

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1003]
On 19.0.0 beta5 with 13.0.5: If I search for a bookmark from FolderA, then close the search window, I'm immediately re-directed to my root bookmark directory.
![Screenshot_20200501_182449](https://user-images.githubusercontent.com/1787238/80851923-68c31180-8bd9-11ea-81d0-6a1c788beea2.png) <- clicking this X will re-direct

I'd like to ideally remain in the current directory (FolderA) after closing the search box.

**Comment by marcelklehr** [comment]
This is not possible, because the search function is a different route. It will search in all folders, not just the one you had selected before, so it has no knowledge of where you were.
