### ISSUE TITLE
GET rest/v2/folder stopped returning parent_folder

### ISSUE THREAD

**Issue by altepizza** [nextcloud/bookmarks#1005]
**Describe the bug**
The [API documentation](https://nextcloud-bookmarks.readthedocs.io/en/latest/folder.html#get-full-hierarchy) currently states that you would receive the following answer when calling ```GET /public/rest/v2/folder```
`{
  "status": "success", "data": [
    {"id": "1", "title": "work", "parent_folder": "-1"}, [...]`

Which worked fine in 2.x but with 3.0.5 you only get 
`{
    "status": "success",
    "data": [
        {
            "id": 2,
            "title": "my folder",
            "userId": "user",
            "children": [
                {
                    "id": 3, [...]`

Is this a bug or a feature?

**To Reproduce**
1. GET (with basic auth) on https://your.nextcloud.instance/index.php/apps/bookmarks/public/rest/v2/folder

**Expected behavior**
As already described: [API documentation of GET /public/rest/v2/folder](https://nextcloud-bookmarks.readthedocs.io/en/latest/folder.html#get-full-hierarchy)

**Server:**
 - OS: Ubuntu 18.04.4 LTS
 - HTTP server: nginx 1.14.0-0ubuntu1.7
 - Database mariadb 10.4.12
 - PHP version: 7.3.17
 - Nextcloud version: 18.0.4
 - Bookmarks app version: 3.0.5

**Comment by marcelklehr** [comment]
That would be a bug.
