### ISSUE TITLE
Moving bunch of bookmarks -> all lost

### ISSUE THREAD

**Issue by kc853** [nextcloud/bookmarks#1006]
Updated to 3.0.5 and selected an bunch of root bookmarks to move them to an existing folder. Bookmarks disappeared from root, but never arrived at the folder. Now all bookmarks are gone.
See error in Nextclouds 18.0.4 log (same entry for each failed bookmark):

```
[index] Error: TypeError: Argument 3 passed to OC\AppFramework\Middleware\MiddlewareDispatcher::beforeOutput() must be of the type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 123 at <<closure>>

0. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 123
   OC\AppFramework\Middleware\MiddlewareDispatcher->beforeOutput(OCA\Bookmarks\Co ... {}, "getBookmarkFavicon", null)
1. /var/www/html/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmarks\Co ... {}, "getBookmarkFavicon")
2. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Bookmarks\ ... r", "getBookmarkFavicon", OC\AppFramework\ ... {}, {id: "2",_route: ... "})
3. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({id: "2",_route: ... "})
4. /var/www/html/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {id: "2",_route: ... "})
5. /var/www/html/lib/base.php line 1008
   OC\Route\Router->match("/apps/bookmarks/bookmark/2/favicon")
6. /var/www/html/index.php line 38
   OC::handleRequest()

GET /apps/bookmarks/bookmark/2/favicon
from x.x.x.x by y at 2020-05-02T13:37:10+00:00
```
Regards

**Comment by marcelklehr** [comment]
Do you still experience this with the latest version? I've fixed an error where if you were not viewing a folder (e.g. viewing all bookmarks with a specific tag), moving bookmarks would lose them.

**Comment by kc853** [comment]
Yes, it's still there. But now I can specify the trigger of the problem. It's multi clicking on the arrow in the target folder selection window. Moving a bunch of bookmarks takes some time, so I was unsure if I hit the arrow and clicked again and again. An error message comes up that moving of some elements failed. In the result all selected bookmarks are gone. Hope this helps.

**Comment by marcelklehr** [comment]
@kc853 Awesome isolating work!
