### ISSUE TITLE
Adding site to a specified folder using "Add to box" shortcut

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/bookmarks#1011]
**Is your feature request related to a problem? Please describe.**
The "add a bookmark" shortcut doesnt allow the user to directly add a site to a specific folder. This presents a problem as the user has to manually move the site in the folder afterwards. With drag-to-move feature missing, it is a lengthy and a bit annoying process IMO.

**Describe the solution you'd like**
In the "add a bookmark" window dialog, add a "folder" option below or above "tags".

**Additional context**

![Screenshot_1](https://user-images.githubusercontent.com/36133540/80925551-f5fc9680-8d90-11ea-948c-e92eb83ab0a8.png)

**Comment by marcelklehr** [comment]
Thanks for the feedback!

Done :)
