### ISSUE TITLE
Folder #-1[undefined] contains an nonexistent bookmark 531

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#1013]
**Describe the bug**
Sync is broken

**To Reproduce**
Try to sync with the latest version

**Expected behavior**
Expect to sync

**Desktop (please complete the following information):**
 - Linux Mint and Windows7
 - Vivaldi latest and Firefox 68.6.0

**Server (please complete the following information):**
 - Ubuntu 18.04
 - Apache
 - MariaDB 10+
 - PHP 7.3
 - Nextcloud version: 18.0.4
 - Bookmarks app version: 3.0.7
 - Activated Nextcloud Apps: Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bookmarks: 3.0.7
  - breezedark: 18.0.14
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - circles: 0.18.5
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - documentserver_community: 0.1.5
  - drawio: 0.9.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_automatedtagging: 1.8.2
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_photospheres: 1.0.8
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.4
  - maps: 0.1.6
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - occweb: 0.0.7
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - passwords: 2020.5.0
  - photos: 1.0.0
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - registration: 0.4.7
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_diaspora: 2.0.0
  - socialsharing_email: 2.0.0
  - socialsharing_facebook: 2.0.0
  - socialsharing_twitter: 2.0.0
  - spreed: 8.0.8
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - talk_simple_poll: 1.1.1
  - tasks: 0.12.2
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - video_converter: 0.1.4
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflow_script: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - user_ldap
 - Nextcloud configuration: 
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "zsemberi.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "https:\/\/zsemberi.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "loglevel": 2,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "theme": "",
        "app_install_overwrite": [
            "social"
        ]
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "notify_email_calendar": "1",
            "notify_email_calendar_event": "1",
            "notify_email_calendar_todo": "1",
            "notify_email_circles_as_member": "0",
            "notify_email_circles_as_moderator": "0",
            "notify_email_circles_as_non_member": "0",
            "notify_email_comments": "0",
            "notify_email_favorite": "0",
            "notify_email_file_changed": "0",
            "notify_email_file_created": "0",
            "notify_email_file_deleted": "0",
            "notify_email_file_restored": "0",
            "notify_email_public_links": "0",
            "notify_email_remote_share": "0",
            "notify_email_shared": "0",
            "notify_email_spreed": "0",
            "notify_email_systemtags": "0",
            "notify_setting_batchtime": "3600",
            "notify_setting_self": "1",
            "notify_setting_selfemail": "0",
            "notify_stream_calendar": "0",
            "notify_stream_calendar_event": "0",
            "notify_stream_calendar_todo": "0",
            "notify_stream_circles_as_member": "1",
            "notify_stream_circles_as_moderator": "1",
            "notify_stream_circles_as_non_member": "1",
            "notify_stream_comments": "1",
            "notify_stream_favorite": "1",
            "notify_stream_file_changed": "1",
            "notify_stream_file_created": "1",
            "notify_stream_file_deleted": "1",
            "notify_stream_file_favorite": "1",
            "notify_stream_file_restored": "1",
            "notify_stream_public_links": "1",
            "notify_stream_remote_share": "1",
            "notify_stream_shared": "1",
            "notify_stream_spreed": "1",
            "notify_stream_systemtags": "1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "44"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "3.0.7",
            "types": ""
        },
        "breezedark": {
            "enabled": "yes",
            "installed_version": "18.0.14",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.0.3",
            "types": ""
        },
        "circles": {
            "allow_federated": "1",
            "allow_linked_groups": "1",
            "enabled": "yes",
            "installed_version": "0.18.5",
            "members_limit": "50",
            "skip_invitation_to_closed_circles": "0",
            "types": "dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1582812289.6861",
            "lastcron": "1588569147",
            "lastupdateResult": "[]",
            "lastupdatedat": "1588569161",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "218001c51aa167d747fe85df53eaab7b",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "sendEventRemindersPush": "yes",
            "types": "filesystem"
        },
        "documentserver_community": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": "filesystem"
        },
        "drawio": {
            "enabled": "yes",
            "installed_version": "0.9.5",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "federation": {
            "autoAddServers": "0",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "240 GB",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "yes",
            "installed_version": "1.8.1",
            "types": "filesystem"
        },
        "files_automatedtagging": {
            "enabled": "yes",
            "installed_version": "1.8.2",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_photospheres": {
            "enabled": "yes",
            "installed_version": "1.0.8",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.2",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "logging"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.3.4",
            "types": ""
        },
        "maps": {
            "enabled": "yes",
            "graphhopperAPIKEY": "",
            "installed_version": "0.1.6",
            "lastAddressLookup": "1587569562",
            "mapboxAPIKEY": "",
            "types": "filesystem"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "occweb": {
            "enabled": "yes",
            "installed_version": "0.0.7",
            "types": ""
        },
        "onlyoffice": {
            "DocumentServerUrl": "https:\/\/zsemberi.de\/index.php\/apps\/documentserver_community\/",
            "defFormats": "{\"docx\":true,\"pptx\":true,\"xlsx\":true,\"odp\":true,\"ods\":true,\"odt\":true,\"doc\":true,\"ppt\":true,\"xls\":true}",
            "editFormats": "{\"csv\":true,\"docx\":true,\"pptx\":true,\"txt\":true,\"xlsx\":true,\"odp\":true,\"ods\":true,\"odt\":true,\"rtf\":true}",
            "enabled": "yes",
            "installed_version": "4.1.4",
            "sameTab": "true",
            "types": "filesystem"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "passwords": {
            "SSEv1ServerKey": "f",
            "enabled": "yes",
            "installed_version": "2020.5.0",
            "legacy_last_used": "1588568927",
            "migration\/customFields": "2020.2.0",
            "passwords\/localdb\/type": "hibp",
            "survey\/server\/notification": "1583420403",
            "types": "",
            "users\/deleted": "[]"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "polls": {
            "enabled": "yes",
            "installed_version": "1.4.3",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "readableLocation": "de",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "types": ""
        },
        "registration": {
            "admin_approval_required": "yes",
            "enabled": "yes",
            "installed_version": "0.4.7",
            "registered_user_group": "User",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "sociallogin": {
            "enabled": "no",
            "installed_version": "2.4.5",
            "types": ""
        },
        "socialsharing_diaspora": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": ""
        },
        "socialsharing_email": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": ""
        },
        "socialsharing_facebook": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": ""
        },
        "socialsharing_twitter": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": ""
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "8.0.8",
            "project_access_invalidated": "1",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "talk_simple_poll": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "prevent_group_restriction"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.12.2",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "dav"
        },
        "theming": {
            "backgroundMime": "image\/png",
            "cachebuster": "11",
            "color": "#747575",
            "enabled": "yes",
            "faviconMime": "image\/png",
            "installed_version": "1.9.0",
            "logoMime": "image\/png",
            "logoheaderMime": "image\/png",
            "name": "Wolke",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "updatenotification": {
            "bookmarks": "3.0.5",
            "breezedark": "18.0.14",
            "calendar": "2.0.3",
            "circles": "0.18.5",
            "contacts": "3.3.0",
            "core": "18.0.2.2",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "mail": "1.3.4",
            "passwords": "2020.5.0",
            "spreed": "8.0.8",
            "talk_simple_poll": "1.1.1",
            "tasks": "0.12.2",
            "types": "",
            "update_check_errors": "0",
            "video_converter": "0.1.4"
        },
        "video_converter": {
            "enabled": "yes",
            "installed_version": "0.1.4",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflow_pdf_converter": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": "filesystem"
        },
        "workflow_script": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": "filesystem"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "filesystem"
        }
    }
}

Server log

200 | GET /index.php/apps/bookmarks/public/rest/v2/folder/-1/childorder?layers=-1 HTTP/2.0
200 | GET /index.php/apps/bookmarks/public/rest/v2/folder HTTP/2.0
200 | GET /index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300 HTTP/2.0

**Comment by marcelklehr** [comment]
Thanks for your feedback. v3.0.8 contains a cleanup step for this problem. Also see https://github.com/marcelklehr/floccus/issues/511

**Comment by copiis** [comment]
v3.0.8 works. Thank you Marcel
