### ISSUE TITLE
Sharing Bookmark Folder with group where the user is a member himself results in duplicate display

### ISSUE THREAD

**Issue by christianalles** [nextcloud/bookmarks#1015]
Hi,
when trying to share a folder with a group where oneself is a member, will result in a duplicate display of the folder. Also entering the folder leads to a duplicate display in the breadcrumbs, like home > shared folder > shared folder

bookmarks version is 3.0.7 nextcloud 18.0.4
steps to reproduce:
have a user group where the user sharing a bookmark folder is member of
share the folder with the group
refresh/reload the browser window
folder will appear two times

expected behavior would be to see only seeing the folder once with the indicator that it is shared

**Comment by marcelklehr** [comment]
Ah, that's a nice catch! Thanks for the feedback :)
