### ISSUE TITLE
Can´t add IP Address bookmarks

### ISSUE THREAD

**Issue by Kernel-Error** [nextcloud/bookmarks#1018]
**Describe the bug**
I can´´t add ip address bookmarks

**To Reproduce**
1. klick on add
2. enter: http://192.168.1.1
3. See error

**Expected behavior**
Well add ip address based bookmarks :)

**Screenshots**
no need

**Desktop (please complete the following information):**
 - OS: all
 - Browser firefox
 - Version 75

**Server (please complete the following information):**
 - OS: FreeBSD 12.1p4
 - HTTP server: nginx 
 - Database MySQL 5.7.29
 - PHP version: 7.3.17
 - Nextcloud version: 18.0.4
 - Bookmarks app version: 3.0.9
 - Activated Nextcloud Apps:
`  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bookmarks: 3.0.9
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - drawio: 0.9.5
  - encryption: 2.6.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.2
  - files_fulltextsearch_tesseract: 1.4.1
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.4
  - news: 14.1.6
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ownpad: 0.6.14
  - password_policy: 1.8.0
  - passwords: 2020.5.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_email: 2.0.0
  - spreed: 8.0.8
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.2
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
`
 - Nextcloud configuration:
`{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "installedat": "1335022929.8563",
        "lastupdatedat": "1340611243.0547",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maxZipInputSize": "838860800",
        "allowZipDownload": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "forcessl": true,
        "trusted_domains": [
            "cloud.kernel-error.com"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwrite.cli.url": "https:\/\/cloud.kernel-error.com",
        "mail_smtpsecure": "ssl",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "calendar",
            "spreed",
            "files_reader",
            "contacts",
            "drawio"
        ],
        "mail_sendmailmode": "smtp",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
`
 - Nextcloud external user backend: ldap

**Additional context**
none

**Web server error log**
```
nothing special
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
{"reqId":"QBd71MhkqZOM6qKA3qDe","level":3,"time":"2020-05-05T14:09:44+00:00","remoteAddr":"2003:f8:5719:ce00:49a6:9fba:7989:9ded","user":"8f93e0b6-9fcb-1039-8367-532028dc98ca","app":"index","method":"POST","url":"/apps/bookmarks/bookmark","message":{"Exception":"Exception","Message":"Call to undefined function gmp_init()","Code":0,"Trace":[{"file":"/usr/local/www/cloud.kernel-error.com/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\InternalBookmarkController"},"newBookmark"]},{"file":"/usr/local/www/cloud.kernel-error.com/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Bookmarks\\Controller\\InternalBookmarkController","newBookmark",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bookmarks.internal_bookmark.new_bookmark"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"bookmarks.internal_bookmark.new_bookmark"}]},{"file":"/usr/local/www/cloud.kernel-error.com/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"bookmarks.internal_bookmark.new_bookmark"}]},{"file":"/usr/local/www/cloud.kernel-error.com/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bookmarks/bookmark"]},{"file":"/usr/local/www/cloud.kernel-error.com/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/www/cloud.kernel-error.com/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"Error","Message":"Call to undefined function gmp_init()","Code":0,"Trace":[{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/vendor/rowbot/url/src/IPv4Address.php","line":94,"function":"parseIPv4Number","class":"Rowbot\\URL\\IPv4Address","type":"::","args":["192",false]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/vendor/rowbot/url/src/Host.php","line":105,"function":"parse","class":"Rowbot\\URL\\IPv4Address","type":"::","args":["192.168.1.1"]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/vendor/rowbot/url/src/BasicURLParser.php","line":895,"function":"parse","class":"Rowbot\\URL\\Host","type":"::","args":["192.168.1.1",false]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/vendor/rowbot/url/src/BasicURLParser.php","line":301,"function":"hostState","class":"Rowbot\\URL\\BasicURLParser","type":"->","args":[""]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/vendor/rowbot/url/src/URL.php","line":73,"function":"parseBasicUrl","class":"Rowbot\\URL\\BasicURLParser","type":"::","args":["http://192.168.1.1",null]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/lib/Service/UrlNormalizer.php","line":25,"function":"__construct","class":"Rowbot\\URL\\URL","type":"->","args":["http://192.168.1.1"]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/lib/Db/BookmarkMapper.php","line":100,"function":"normalize","class":"OCA\\Bookmarks\\Service\\UrlNormalizer","type":"->","args":["http://192.168.1.1"]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/lib/Db/BookmarkMapper.php","line":509,"function":"findByUrl","class":"OCA\\Bookmarks\\Db\\BookmarkMapper","type":"->","args":["8f93e0b6-9fcb-1039-8367-532028dc98ca","http://192.168.1.1"]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/lib/Service/BookmarkService.php","line":161,"function":"insertOrUpdate","class":"OCA\\Bookmarks\\Db\\BookmarkMapper","type":"->","args":[{"id":null,"__class__":"OCA\\Bookmarks\\Db\\Bookmark"}]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/lib/Service/BookmarkService.php","line":132,"function":"_addBookmark","class":"OCA\\Bookmarks\\Service\\BookmarkService","type":"->","args":["http://192.168.1.1","http://192.168.1.1","","8f93e0b6-9fcb-1039-8367-532028dc98ca",[],[9]]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/lib/Controller/BookmarkController.php","line":413,"function":"create","class":"OCA\\Bookmarks\\Service\\BookmarkService","type":"->","args":["8f93e0b6-9fcb-1039-8367-532028dc98ca","http://192.168.1.1","http://192.168.1.1","",[],[9]]},{"file":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/lib/Controller/InternalBookmarkController.php","line":106,"function":"newBookmark","class":"OCA\\Bookmarks\\Controller\\BookmarkController","type":"->","args":["http://192.168.1.1",null,"",[],[9]]},{"file":"/usr/local/www/cloud.kernel-error.com/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"newBookmark","class":"OCA\\Bookmarks\\Controller\\InternalBookmarkController","type":"->","args":["http://192.168.1.1",null,"",[],[9]]},{"file":"/usr/local/www/cloud.kernel-error.com/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\InternalBookmarkController"},"newBookmark"]},{"file":"/usr/local/www/cloud.kernel-error.com/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\InternalBookmarkController"},"newBookmark"]},{"file":"/usr/local/www/cloud.kernel-error.com/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Bookmarks\\Controller\\InternalBookmarkController","newBookmark",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bookmarks.internal_bookmark.new_bookmark"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"bookmarks.internal_bookmark.new_bookmark"}]},{"file":"/usr/local/www/cloud.kernel-error.com/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"bookmarks.internal_bookmark.new_bookmark"}]},{"file":"/usr/local/www/cloud.kernel-error.com/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bookmarks/bookmark"]},{"file":"/usr/local/www/cloud.kernel-error.com/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/local/www/cloud.kernel-error.com/apps/bookmarks/vendor/rowbot/url/src/IPv4Address.php","Line":224},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.4.2"}

```

**Browser log**
```
Nothing special 
```

**Comment by marcelklehr** [comment]
Mmh

cc @TRowbotham Can you make sense of this? I thought URL v3 doesn't require gmp any more?

**Comment by TRowbotham** [comment]
v3.0.1 was the version that removed the gmp dependency. It seems like composer gave the user version 3.0.0 instead. #928 updated composer to use "^3.0", which should normally be sufficient. The only thing that I can think of that would cause them to get 3.0.0 instead of 3.0.1 is if there was a conflict with installing the `brick/math` library.

**Comment by marcelklehr** [comment]
hah, my bad. I hadn't ran composer locally anymore after that pr. Sorry for the noise @TRowbotham

**Comment by marcelklehr** [comment]
Fix in the latest release.
