### ISSUE TITLE
Sharing bookmarks and bookmark folders

### ISSUE THREAD

**Issue by ifuchs** [nextcloud/bookmarks#1019]
I am running Bookmarks v3.0.9. How do I share a bookmark or a folder of bookmarks?

**Comment by marcelklehr** [comment]
You can only share folders. Click on The three-dot-menu of the folder, select details and go to the sharing tab, similar to how you would share a file system folder in nextcloud.

**Comment by ifuchs** [comment]
Thanks. So one can only share folders and only create public links (i.e., not private links to NC authenticated uses or groups)?

**Comment by marcelklehr** [comment]
No, you can share privately with nc users and groups, too.

I have created a visual to aid you in finding the feature on your screen.

![image](https://user-images.githubusercontent.com/986878/81098519-c45b0b00-8f09-11ea-9761-d94ea8a660ae.png)

**Comment by ifuchs** [comment]
oops. I should have seen that.
