### ISSUE TITLE
No Sync after upgrading - similar to #994

### ISSUE THREAD

**Issue by bigtreiber** [nextcloud/bookmarks#1021]
**Describe the bug**
Today I updated bookmarks in my NC installation to 3.0.2 and now on all of my android devices I can't log in into the bookmark App. Error message: "Verbindung fehlgeschlagen".

Log in with a fresh account works. I can't find any way to log into my existing nextloud account.

I already deleted the bookmarks app on my server, without result.

**To Reproduce**
Steps to reproduce the behavior
- Update to Bookmarks 3.0.12
- Sync with [Nextcloud Bookmarks](https://gitlab.com/bisada/OCBookmarks) on Android

**Expected behavior**
Sync should be ok.

**Screenshots**

**Desktop** (please complete the following information)
- Android LineageOS 16
- [Nextcloud Bookmarks](https://gitlab.com/bisada/OCBookmarks)

**Server** (please complete the following information):
- OS: Debian 9
- HTTP server: Apache2
- Database MySQL 5.3
- PHP version: 7.4
- Nextcloud version: 18.0.4
- Bookmarks app version: 3.0.12

**Comment by bigtreiber** [comment]
What I tried without success
- Enabling TOTP
- Deactivating and deleting the Bookmark App on the server
- Changing the PW of my account

It only seems to work with a new account, but that's not an option because there is to many other data in that account.

**Comment by dasbiswajit** [comment]
@bigtreiber Thanks for reporting I am the maintainer of the repository. Can you please open an issue [here](https://gitlab.com/bisada/OCBookmarks/-/issues). We have a stable version now with some known issues.

**Comment by bigtreiber** [comment]
Okay, no need to open an issue. It works with v1.8

**Comment by dasbiswajit** [comment]
ok Cool.
