### ISSUE TITLE
Thumbnails are often not generated 

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/bookmarks#1022]
### Steps to reproduce
Using Screenly in the Bookmarks app, it often happens that thumbnails are not generated (see screen). 

This bug is random. I am simply creating bookmarks (esp., using the bookmarklet). Sometimes it generates a thumbnail, sometimes it doesn't. 

### Expected behaviour
I would expect that there be thumbnails for every site added. 
Nice to have would be a 'refresh thumbnail" button. 

### Actual behaviour
Often, thumbnails are not generated. 

If I go to the screenly website, I can see that they do produce thumbnails for the affected sites. 

## Server configuration detail

**Operating system:** Linux 5.4.0-28-generic #32-Ubuntu SMP Wed Apr 22 17:40:10 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.3.22

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - audioplayer: 2.10.0
 - bookmarks: 3.0.0-beta.1
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - camerarawpreviews: 0.7.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - deck: 1.0.0
 - documentserver_community: 0.1.5
 - drawio: 0.9.5
 - event_update_notification: 1.0.1
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - gpxpod: 4.2.1
 - issuetemplate: 0.6.0
 - keeweb: 0.6.2
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.6
 - metadata: 0.11.1
 - music: 0.14.0
 - news: 14.1.7
 - nextcloud_announcements: 1.7.0
 - notes: 3.3.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - occweb: 0.0.7
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - phonetrack: 0.6.2
 - photos: 1.0.0
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - rainloop: 6.1.0
 - riotchat: 0.3.1
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - socialsharing_email: 2.0.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - suspicious_login: 3.1.0
 - systemtags: 1.8.0
 - tasks: 0.12.2
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - files_external
 - firstrunwizard
 - recommendations
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "aproposnix.dlinkddns.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "http:\/\/localhost\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "app_install_overwrite": [
        "social",
        "dashboard"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "updater.release.channel": "stable",
    "theme": "",
    "loglevel": 2,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0

**Operating system:** Ubuntu 2.04

## Screenshot

http://pix.toile-libre.org/upload/original/1589006970.png

**Comment by marcelklehr** [comment]
In v3 the default behavior is not to interact with any remote servers, even if a Screeenly API is set up. Please verify that you have enabled third-party network access in your admin settings for the bookmarks app.

**Comment by aproposnix** [comment]
@marcelklehr 

I can confirm, assuming your talking about the Privacy section of the settings. 

http://pix.toile-libre.org/upload/original/1589052663.png

**Comment by marcelklehr** [comment]
This is probably an issue with screeenly. I will close this in favor of #741

**Comment by jfqd** [comment]
Dont´t think that this is an issue with screeenly. It was working here, but stopped with an update of 
bookmarks (or nextcloud). Sorry to say which one, but it stopped working. Please reopen the issue.

**Comment by mortee** [comment]
I can confirm this: I just spent 1,5 days getting screeenly running on an armhf system, just to see that even if I configure it in the NC Bokkmarks settings, it's not even called.

**Comment by robinsxv** [comment]
Same for me. My networks tab doesn't even show a request to screeenly.

**Comment by marcelklehr** [comment]
Please open a new issue if this is still a problem for you
