### ISSUE TITLE
Bookmarklet doesn't work on Github pages with Firefox

### ISSUE THREAD

**Issue by anavarre** [nextcloud/bookmarks#103]
I noticed that several times before so here's an issue as I couldn't find any existing one. When you're trying to save a Github page as an ownCloud bookmark with Firefox, nothing happens. Try and save any other page with Firefox and it works. Try and save any Github page, say with Chrome, and it just works.

I checked Firebug's Console tab after pressing on the ownCloud bookmarklet and here's the error that was returned:

```
Content Security Policy: The page's settings blocked the loading of a resource
at self ("script-src https://assets-cdn.github.com https://collector-cdn.github.com").
```

**Comment by Chouchen** [comment]
Well, Github put a CSP in place : https://github.com/blog/1477-content-security-policy

>We've started rolling out a new security feature called "Content Security Policy" or CSP. As a user, it will better protect your account against XSS attacks. But, be aware, it may cause issues with some browser extensions and bookmarklets.

That protection disables any injected script (like almost any bookmarklet does). Nice protection but very intrusive for user :-1: 

We can't do anything against it unfortunately. Maybe there's a plugin which blocks that?

**Comment by vitr** [comment]
while this is very true, you still can overcome the issue by using the firefox pocket add-on
https://addons.mozilla.org/en-US/firefox/addon/read-it-later/
![image 17](https://cloud.githubusercontent.com/assets/2770290/7130926/922869e8-e2bb-11e4-9096-4444fbef3bd5.png)

**Comment by Chouchen** [comment]
Then we need to create a firefox owncloud's bookmark add-on? Is that what you're trying to say?

**Comment by vitr** [comment]
yeah, sorry, didn't intend to promote anything, I've edited my previous comment

**Comment by marcelklehr** [comment]
Closing as wontfix, since an addon is not the scope of this repo (although, it is a good idea ;) )
