### ISSUE TITLE
Missing translation of "Settings" dialog header

### ISSUE THREAD

**Issue by j-ed** [nextcloud/bookmarks#1031]
**Describe the bug**
The name of the settings dialog header isn't translated.

**To Reproduce**
1. Open the Bookmarks app.
2. Check the name of the settings dialog in the lower left corner.

**Expected behavior**
"Settings" should be translated to e.g. "Einstellungen" if the German language has been selected.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2572764/81693101-b48a7c00-945f-11ea-8699-4ca79f80a428.png)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS X]: **Windows 10**
 - Browser [e.g. chrome, safari]: **Firefox 76.0.1**

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7]: **Linux 4.9.218**
 - HTTP server: [e.g. nginx 1.1]: **Apache2 2.4.41**
 - Database [e.g. MySQL 5.3]: **MariaDB 10.2.24**
 - PHP version: [e.g. v7.2]: **7.3.13**
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)]: **18.0.4**
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)]: **3.0.13**
 - Nextcloud external user backend: [e.g. ldap, or none]: **none**

**Comment by marcelklehr** [comment]
Thanks for reporting this (and sorry for the delay). This is an upstream issue of the nextcloud vue components that are being used. I believe this is en route to being fixed, though.

**Comment by philipreimer** [comment]
Looks like this has been fixed. "Settings" is translated in my NC 19.0.2 and NC 18.0.9, at least in German, French and Spanish.
