### ISSUE TITLE
Can we share a Bookmarks with a group?

### ISSUE THREAD

**Issue by Ramdane34** [nextcloud/bookmarks#1035]
Hello, How do we share a Bookmarks to a group?

**Comment by j-ed** [comment]
This is the bug tracker for the developers only and NOT the [**Nextcloud help forum**](https://help.nextcloud.com/). If you would have used the search function of that forum, the following post might have popped-up on your screen which answers your question:

https://help.nextcloud.com/t/bookmarks-v3-0-0-sharing/79858

**Comment by republicus** [comment]
I read the same link and thought sharing wasn't present either. Its not as integrated as other apps: you have to select Details of the folder then set sharing options.

**Comment by Ramdane34** [comment]
Thank you very much You answered my question @radhus
