### ISSUE TITLE
Problems with twofactor_gateway

### ISSUE THREAD

**Issue by republicus** [nextcloud/bookmarks#1036]
Lots of updates lately. Latest update broke sync.
php-gmp is installed

![image](https://user-images.githubusercontent.com/47370709/81994702-6e2b4d80-9616-11ea-8d2b-8ca13438009b.png)

Call to undefined function GuzzleHttp\\_idn_uri_convert()

**nextcloud.log**
`"reqId":"b38yVCfCLLj8No7iD8YL","level":3,"time":"2020-05-14T23:04:13+00:00","remoteAddr":"172.16.1.67","user":"republicus","app":"index","method":"POST","url":"/index.php/apps/bookmarks/public/rest/v2/bookmark","message":{"Exception":"Exception","Message":"Call to undefined function GuzzleHttp\\_idn_uri_convert()","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\BookmarkController"},"newBookmark"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Bookmarks\\Controller\\BookmarkController","newBookmark",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bookmarks.bookmark.new_bookmark"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"bookmarks.bookmark.new_bookmark"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"bookmarks.bookmark.new_bookmark"}]},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bookmarks/public/rest/v2/bookmark"]},{"file":"/var/www/html/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"Error","Message":"Call to undefined function GuzzleHttp\\_idn_uri_convert()","Code":0,"Trace":[{"file":"/var/www/html/apps/twofactor_gateway/vendor/guzzlehttp/guzzle/src/Client.php","line":155,"function":"buildUri","class":"GuzzleHttp\\Client","type":"->","args":[{"__class__":"GuzzleHttp\\Psr7\\Uri"},{"verify":"/mnt/nextcloud/data/files_external/rootcerts.crt","timeout":10,"headers":{"User-Agent":"Nextcloud Server Crawler"},"synchronous":true,"handler":{"__class__":"GuzzleHttp\\HandlerStack"},"allow_redirects":{"max":5,"protocols":["http","https"],"strict":false,"referer":false,"track_redirects":false},"http_errors":true,"decode_content":true,"cookies":false,"idn_conversion":true,"_conditional":{"User-Agent":"GuzzleHttp/6.5.1 curl/7.64.0 PHP/7.3.14-1~deb10u1"}}]},{"file":"/var/www/html/apps/twofactor_gateway/vendor/guzzlehttp/guzzle/src/Client.php","line":183,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["get","https://medium.com/@sammyjohnsonweb/use-riot-not-discord-for-foss-and-privacy-respecting-communities-d25f9ae2cb5",{"verify":"/mnt/nextcloud/data/files_external/rootcerts.crt","timeout":10,"headers":{"User-Agent":"Nextcloud Server Crawler"},"synchronous":true,"handler":{"__class__":"GuzzleHttp\\HandlerStack"},"allow_redirects":{"max":5,"protocols":["http","https"],"strict":false,"referer":false,"track_redirects":false},"http_errors":true,"decode_content":true,"cookies":false,"idn_conversion":true,"_conditional":{"User-Agent":"GuzzleHttp/6.5.1 curl/7.64.0 PHP/7.3.14-1~deb10u1"}}]},{"file":"/var/www/html/lib/private/Http/Client/Client.php","line":149,"function":"request","class":"GuzzleHttp\\Client","type":"->","args":["get","https://medium.com/@sammyjohnsonweb/use-riot-not-discord-for-foss-and-privacy-respecting-communities-d25f9ae2cb5",{"proxy":null,"verify":"/mnt/nextcloud/data/files_external/rootcerts.crt","timeout":10,"headers":{"User-Agent":"Nextcloud Server Crawler"},"synchronous":true}]},{"file":"/var/www/html/apps/bookmarks/lib/Http/Client.php","line":43,"function":"get","class":"OC\\Http\\Client\\Client","type":"->","args":["https://medium.com/@sammyjohnsonweb/use-riot-not-discord-for-foss-and-privacy-respecting-communities-d25f9ae2cb5",{"timeout":10}]},{"file":"/var/www/html/apps/bookmarks/vendor/marcelklehr/link-preview/src/Models/Link.php","line":60,"function":"sendRequest","class":"OCA\\Bookmarks\\Http\\Client","type":"->","args":[{"__class__":"GuzzleHttp\\Psr7\\Request"}]},{"file":"/var/www/html/apps/bookmarks/vendor/marcelklehr/link-preview/src/Models/Link.php","line":69,"function":"fetch","class":"Marcelklehr\\LinkPreview\\Models\\Link","type":"->","args":[]},{"file":"/var/www/html/apps/bookmarks/lib/Service/LinkExplorer.php","line":44,"function":"getPreview","class":"Marcelklehr\\LinkPreview\\Models\\Link","type":"->","args":[]},{"file":"/var/www/html/apps/bookmarks/lib/Service/BookmarkService.php","line":97,"function":"get","class":"OCA\\Bookmarks\\Service\\LinkExplorer","type":"->","args":["https://medium.com/@sammyjohnsonweb/use-riot-not-discord-for-foss-and-privacy-respecting-communities-d25f9ae2cb5"]},{"file":"/var/www/html/apps/bookmarks/lib/Controller/BookmarkController.php","line":414,"function":"create","class":"OCA\\Bookmarks\\Service\\BookmarkService","type":"->","args":["republicus","https://medium.com/@sammyjohnsonweb/use-riot-not-discord-for-foss-and-privacy-respecting-communities-d25f9ae2cb5","Use Riot not Discord for FOSS and Privacy Respecting Communities","",[],[5]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"newBookmark","class":"OCA\\Bookmarks\\Controller\\BookmarkController","type":"->","args":["https://medium.com/@sammyjohnsonweb/use-riot-not-discord-for-foss-and-privacy-respecting-communities-d25f9ae2cb5","Use Riot not Discord for FOSS and Privacy Respecting Communities","",[],[5]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\BookmarkController"},"newBookmark"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\BookmarkController"},"newBookmark"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Bookmarks\\Controller\\BookmarkController","newBookmark",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bookmarks.bookmark.new_bookmark"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"bookmarks.bookmark.new_bookmark"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"bookmarks.bookmark.new_bookmark"}]},{"file":"/var/www/html/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bookmarks/public/rest/v2/bookmark"]},{"file":"/var/www/html/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/apps/twofactor_gateway/vendor/guzzlehttp/guzzle/src/Client.php","Line":220},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36 Edg/81.0.416.64","version":"18.0.4.2"}`

**Comment by simonspa** [comment]
I can confirm the food of errors in the log but sync seems to be fine, at least floccos isn't complaining:

```
[core] Error: TypeError: Argument 1 passed to GuzzleHttp\Psr7\Uri::applyParts() must be of the type array, null given, called in /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/psr7/src/Uri.php on line 73 at <<closure>>

 0. /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/psr7/src/Uri.php line 73
    GuzzleHttp\Psr7\Uri->applyParts(null)
 1. /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/psr7/src/Request.php line 41
    GuzzleHttp\Psr7\Uri->__construct([])
 2. /var/www/nextcloud/apps/bookmarks/lib/Http/RequestFactory.php line 19
    GuzzleHttp\Psr7\Request->__construct("GET", [])
 3. /var/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Models/Link.php line 60
    OCA\Bookmarks\Http\RequestFactory->createRequest("GET", [])
 4. /var/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Models/Link.php line 69
    Marcelklehr\LinkPreview\Models\Link->fetch()
 5. /var/www/nextcloud/apps/bookmarks/lib/Service/LinkExplorer.php line 44
    Marcelklehr\LinkPreview\Models\Link->getPreview()
 6. /var/www/nextcloud/apps/bookmarks/lib/Service/Previewers/DefaultBookmarkPreviewer.php line 103
    OCA\Bookmarks\Service\LinkExplorer->get("https://www.tis ... l")
 7. /var/www/nextcloud/apps/bookmarks/lib/Service/Previewers/DefaultBookmarkPreviewer.php line 87
    OCA\Bookmarks\Service\Previewers\DefaultBookmarkPreviewer->scrapeUrl("https://www.tis ... l")
 8. /var/www/nextcloud/apps/bookmarks/lib/Service/BookmarkPreviewer.php line 74
    OCA\Bookmarks\Service\Previewers\DefaultBookmarkPreviewer->getImage(OCA\Bookmarks\Db\Bookmark {id: 1326})
 9. /var/www/nextcloud/apps/bookmarks/lib/BackgroundJobs/PreviewsJob.php line 35
    OCA\Bookmarks\Service\BookmarkPreviewer->getImage(OCA\Bookmarks\Db\Bookmark {id: 1326})
10. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 61
    OCA\Bookmarks\BackgroundJobs\PreviewsJob->run(null)
11. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
    OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
12. /var/www/nextcloud/cron.php line 125
    OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-05-16T14:45:45+02:00
```
to me it looks like more of an issue triggered by the NC cronjob?

**Comment by marcelklehr** [comment]
@republicus This appears to be an instance of dependency hell.

`OCA\\Bookmarks\\Http\\Client` calls `OC\\Http\\Client\\Client` in nextcloud core which calls `GuzzleHttp\\Client`, but that gets loaded from 
`var/www/html/apps/twofactor_gateway/vendor/guzzlehttp/guzzle/src/Client.php`, which is probably faulty for some reason.

**Comment by marcelklehr** [comment]
@simonspa can you create a new issue for your error?
