### ISSUE TITLE
Some Favicons not loading

### ISSUE THREAD

**Issue by Jolopu** [nextcloud/bookmarks#1037]
**Describe the bug**
In Nextcloud Bookmarks app the favicons of some bookmarks are not loading. For example all of the YouTube-Favicons are missing. Wikipedia favicons are loading but most of other websites the favicons are missing. In the NC server log I can see this:

[index] Error: TypeError: Argument 3 passed to OC\AppFramework\Middleware\MiddlewareDispatcher::beforeOutput() must be of the type string, null given, called in /home/www/cloud.tv/lib/private/AppFramework/Http/Dispatcher.php on line 123 at <<closure>>

0. /home/www/cloud.tv/lib/private/AppFramework/Http/Dispatcher.php line 123
   OC\AppFramework\Middleware\MiddlewareDispatcher->beforeOutput(OCA\Bookmarks\Co ... {}, "getBookmarkFavicon", null)
1. /home/www/cloud.tv/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmarks\Co ... {}, "getBookmarkFavicon")
2. /home/www/cloud.tv/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Bookmarks\ ... r", "getBookmarkFavicon", OC\AppFramework\ ... {}, {id: "90",_route ... "})
3. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({id: "90",_route ... "})
4. /home/www/cloud.tv/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {id: "90",_route ... "})
5. /home/www/cloud.tv/lib/base.php line 1008
   OC\Route\Router->match("/apps/bookmarks/bookmark/90/favicon")
6. /home/www/cloud.tv/index.php line 38
   OC::handleRequest()

GET /index.php/apps/bookmarks/bookmark/90/favicon
from 217.138.199.52 by admin at 2020-05-15T18:24:25+00:00

**To Reproduce**
1. Go to Nextcloud backend
2. Click on Bookmarks
3. Click on Latest Bookmarks

**Expected behavior**
All bookmark favicons should load.

**Screenshots**
![favicons-missing](https://user-images.githubusercontent.com/34797349/82118705-49032000-9779-11ea-86b5-91bd13245b09.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Firefox
 - Version 75

**Server (please complete the following information):**
 - OS: Debian
 - HTTP server: Apache
 - Database MySQL 5.3
 - PHP version: 7.3.13
 - Nextcloud version: 18.0.4
 - Bookmarks app version: 3.0.13

**Comment by marcelklehr** [comment]
This should be fixed in v3.3.2 (at least the error should disappear, the favicons might still be missing, but this is due to a problem in the scraping behavior).
