### ISSUE TITLE
Bookmarklet popup isn't sized properly on Chrome

### ISSUE THREAD

**Issue by anavarre** [nextcloud/bookmarks#104]
Bookmarklet popup works just fine on Firefox. With Chrome, though, it's not sized correctly and. To be able to save the bookmark, you need to resize the popup window manually.

Please see below:

![owncloud_popup](https://cloud.githubusercontent.com/assets/293478/5200023/f8a9088e-7561-11e4-9dfe-a733d320cefe.png)

**Comment by Chouchen** [comment]
Did you try the new version on OC8?
I don't have this on chrome.

**Comment by idef1x** [comment]
I've te same on OC8.2.2 and Chrome v45.x.x.x..is annoying indeed

**Comment by marcelklehr** [comment]
Seems to be fixed for me. Shout if this is still an issue for you.
