### ISSUE TITLE
Adding a bookmark breaks sync

### ISSUE THREAD

**Issue by republicus** [nextcloud/bookmarks#1041]
I did already report this bug in an issue I created, and am curious why it's impossible to find...
*edit* topic was renamed and closed. found it at #1036 
**Describe the bug**
Adding any bookmark breaks sync with latest Bookmarks v 3.0.13

Note: syncing was fine before latest update.

**To Reproduce**
1. **Add bookmark** to your browsers' nextcloud sync folder
2. Click **Sync** (in extension: my eg. Floccus)
3. Observe Sync failure
![image](https://user-images.githubusercontent.com/47370709/82160176-7cb97500-9861-11ea-86a3-5afe6dc86f87.png)

4. **Remove bookmark** from browsers' synced folder
5. Click **Sync**
5. Observe Sync success
![image](https://user-images.githubusercontent.com/47370709/82160183-8a6efa80-9861-11ea-8659-73f1935c1f1b.png)

**Expected behavior**
Syncing when adding bookmarks

Notes: I tried with folders, which made no difference on account sync.
If any one bookmark is present, sync fails.
I had no issues before latest updates (which were nearly daily this past week)

**Desktop**:

OS: Windows 10
Browser: Chrome, Brave, Edge(chromium)

**Server** :

OS: Debian 10
HTTP server: Apache2 2.4.38
Database: 10.3.22-MariaDB
PHP version: 7.3
Nextcloud version: 18.0.4
Bookmarks app version: 3.0.13
Activated Nextcloud Apps:
```
sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - apporder: 0.9.0
  - bookmarks: 3.0.13
  - breezedark: 18.0.16
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - circles: 0.18.5
  - cloud_federation_api: 1.1.0
  - cms_pico: 1.0.6
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 1.0.1
  - dropit: 0.4.0
  - epubreader: 1.4.2
  - event_update_notification: 1.0.1
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.3.0
  - files_automatedtagging: 1.8.2
  - files_external: 1.9.0
  - files_markdown: 2.2.0
  - files_mindmap: 0.0.21
  - files_pdfviewer: 1.7.0
  - files_readmemd: 1.1.4
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_texteditor: 2.11.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.6
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.4
  - maps: 0.1.6
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - passwords: 2020.5.0
  - photos: 1.0.0
  - polls: 1.4.3
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - riotchat: 0.3.3
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.1
  - text: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_gateway: 0.16.0
  - updatenotification: 1.8.0
  - user_ispconfig: 0.4.6
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - announcementcenter
  - encryption
  - federation
  - ojsxc
  - side_menu
  - talk_simple_poll
  - theming
  - unsplash
  - user_ldap
```

**Comment by marcelklehr** [comment]
Hello @republicus 

Is the error message still the same as in #1036? Have you updated `twofactor_gateway` recently? Did you try disabling that app?

As noted in #1036 this error is most likely *not* caused by the bookmarks app. Specifically, the bookmarks app tries to use a nextcloud core API, which calls upon a dependency that is overriden by `twofactor_gateway`.

**Comment by marcelklehr** [comment]
See https://github.com/nextcloud/twofactor_gateway/issues/349
