### ISSUE TITLE
the tags only work

### ISSUE THREAD

**Issue by Ramdane34** [nextcloud/bookmarks#1042]
Hello,

the tags only work as admin, is this normal?

**Comment by marcelklehr** [comment]
Hello @Ramdane34 

I cannot reproduce this from your description of the problem.

Please provide more details. Incidentally, that's what the issue template is for that you deliberately removed ;)

**Comment by Ramdane34** [comment]
I will try to be a little more precise,
when I tag my bookmarks, they appear in the left pane in shortcuts. other users cannot see the tag shortcuts. Was I precise enough?

**Comment by marcelklehr** [comment]
This appears to be the same as https://github.com/nextcloud/bookmarks/issues/993 is that correct?

**Comment by Ramdane34** [comment]
You are right, it seems to me that it is the same thing
Thank you for your quick replies
