### ISSUE TITLE
Bookmarks shared to a group are not seen by new group members

### ISSUE THREAD

**Issue by nursoda** [nextcloud/bookmarks#1043]
**Describe the bug**
If I add a new user to NC and assign it to a group to which a bookmark folder was shared to previously, that new user doesn't see the shared bookmark folder while previously existing group members do see it.

**To Reproduce**
1. work as user u
2. Create some users a1 a2 as group members of group A,
3. Create some bookmarks in one collection/folder X
4. Share X with A
5. Verify that both a1 and a2 see the shared bookmarks
6. Add user a3 as group member of A to NC
7. Login as a3 and open bookmarks app

**Expected behavior**
X should be seen by a3 (but isn't)

**Desktop (please complete the following information):**
Performed the test on Arch Linux (current) with Firefox 76.0.1.

**Server (please complete the following information):**
Arch Linux (current) with NGINX 1.18.0, PHP-FPM 7.4.6, MariaDB 10.4.13, Nextcloud 19.0 RC2, Bookmarks 3.0.13

**Comment by marcelklehr** [comment]
Thank you for the concise bug report :blue_heart: I can confirm this and will provide a fix asap.

**Comment by colpari** [comment]
We currently have the exact same Problem with our LDAP groups on NC 24.0.3 / Bookmarks 11.0.1

1. users added to a group after a bookmark folder has been shared with the group don't get the share
2. users removed from a group which had the share properly before removing still can access the shared bookmarks
3. when the shared bookmark folder is un-shared it stays visible for all users that it was shared with, but it's empty and the UI displays the message 'Unable to count bookmarks'

Most of the times, doing _any_ (re)sharing of _unrelated bookmark folders_ with _unrelated groups or users_ seems to update the underlying data and fix problems 1 and 2 - problem 3  persists in any case.

Shall we open a new issue?
