### ISSUE TITLE
Deleting several equal bookmarks form one folder also delete it from another folder

### ISSUE THREAD

**Issue by Jurik-Phys** [nextcloud/bookmarks#1044]
**Describe the bug**
When two different folders has some numbers of equal bookmarks and when I try to delete one group bookmarks from first folder I get that this group of bookmarks was deleted from second folder also. But deleting one bookmarks from first folder don't delete it from second folder.

**To Reproduce**
I.1. Create folder "First" and "Second"
I.2. Add each two bookmarks. For example "ya.ru" and "google.com"
I.3. Go to in First folder, select one bookmark, for example, "google.com" and delete it from bookmarks menu. Bookmark "google.com" removed from First folder.
I.4. Go to Second folder and all bookmarks (ya.ru and google.com) is exist. [Оk] Bookmarks "google.com" was delete only from first folder.
I.5. Delete First and Second folder for next step.

II. 1. Create folder "First" and "Second"
II.2. Add each two bookmarks. For example "ya.ru" and "google.com"
II.3. Go to in First folder, select bookmarks "google.com" and "ya.ru". Delete it from general menu of selected bookmarks with menu item "Delete selected" (Удалить выбранное).
II.4 Bookmarks "google.com" and "ya.ru" removed from both folder First and Second [bug]

**Expected behavior**
I expect that bookmarks will delete only from  current (First) folder without dependencies of count deleting files.

**Desktop (please complete the following information):**
 - Nextcloud version 18.0.4
 - Bookmarks app version 3.0.13

**Comment by marcelklehr** [comment]
Thank you for the concise bug report! :blue_heart: I will investigate :relaxed:
