### ISSUE TITLE
Bookmark Dupes

### ISSUE THREAD

**Issue by jaro3** [nextcloud/bookmarks#1045]
**Is your feature request related to a problem? Please describe.**
floccus fails when using multiple clients, duplicates same bookmarks, freezes with:
E019: HTTP status 500. Failed POST request. Check your server configuration and log.

**Describe the solution you'd like**
integrate the function to remove Bookmark dupes on the Nextcloud server side app, like this Firefox extension: https://addons.mozilla.org/en-US/firefox/addon/bookmark-dupes/?src=search

**Describe alternatives you've considered**
After removing the dupes by the firefox extensions (also resulting empty folders) and then manually 1by1 on the server the problem is gone but just before another Bookmark client steps in, then it starts all over again...

**Additional context**
The server App should not accept duplicates of existing bookmarks! or at least have a function to manually remove them at once...

**Comment by marcelklehr** [comment]
Mh. Floccus sorts out duplicates bookmarks per folder and duplicates across folders should be supported. Thus, this is a bug. HTTP 500 responses are pretty much always bugs. Could you find the error message in the nextcloud log and post it here?

**Comment by jaro3** [comment]
when it gets stuck it's spewing messages like this:

{"reqId":"roG4nfSwVcBfPY61balI","level":3,"time":"2020-05-28T10:54:11+09:00","remoteAddr":"172.27.7.5","user":"user","app":"index","method":"POST","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark","message":{"Exception":"Exception","Message":"Argument 1 passed to OCA\\Bookmarks\\Service\\Authorizer::getPermissionsForFolder() must be of the type int, null given, called in /usr/share/webapps/nextcloud/apps2/bookmarks/lib/Controller/BookmarkController.php on line 404","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\BookmarkController"},"newBookmark"]},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Bookmarks\\Controller\\BookmarkController","newBookmark",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bookmarks.bookmark.new_bookmark"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"bookmarks.bookmark.new_bookmark"}]},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"bookmarks.bookmark.new_bookmark"}]},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bookmarks/public/rest/v2/bookmark"]},{"file":"/usr/share/webapps/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Bookmarks\\Service\\Authorizer::getPermissionsForFolder() must be of the type int, null given, called in /usr/share/webapps/nextcloud/apps2/bookmarks/lib/Controller/BookmarkController.php on line 404","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/apps2/bookmarks/lib/Controller/BookmarkController.php","line":404,"function":"getPermissionsForFolder","class":"OCA\\Bookmarks\\Service\\Authorizer","type":"->","args":[null,{"__class__":"OC\\AppFramework\\Http\\Request"}]},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"newBookmark","class":"OCA\\Bookmarks\\Controller\\BookmarkController","type":"->","args":["https://www.goldbio.com/articles/article/10-incredibly-useful-protocol-resources-for-life-scientists","10 Incredibly Useful Protocol Resources for Life Scientists | GoldBio","",[],[null]]},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\BookmarkController"},"newBookmark"]},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\BookmarkController"},"newBookmark"]},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Bookmarks\\Controller\\BookmarkController","newBookmark",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bookmarks.bookmark.new_bookmark"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"bookmarks.bookmark.new_bookmark"}]},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"bookmarks.bookmark.new_bookmark"}]},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bookmarks/public/rest/v2/bookmark"]},{"file":"/usr/share/webapps/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/share/webapps/nextcloud/apps2/bookmarks/lib/Service/Authorizer.php","Line":122},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.4.2"}

**Comment by marcelklehr** [comment]
This should be fixed in the latest release. Can you confirm that?
