### ISSUE TITLE
Error trying to search a bookmark if bookmark list is sorted alphabetically

### ISSUE THREAD

**Issue by stlehmann** [nextcloud/bookmarks#1050]
**Describe the bug**
If I sort the bookmark list alphabetically and try to use the search field to find a specific bookmark I will get no results.

**To Reproduce**
1. Go to 'Settings' and choose 'alphabetic' as sort option
2. Click on "Search" button and type in a Bookmark title to search fo
3. Hit Enter
4. The screen will always show message stating that there are no matching bookmarks

**Expected behavior**
There should be a list with the matching bookmarks.

**Desktop (please complete the following information):**
 - OS: Windows 10, Mac OS X Catalina
 - Browser Firefox
 - Version 76.0.1

**Server (please complete the following information):**
 - OS: Debian Jessie
 - HTTP server: nginx 1.6.2
 - Database MySQL 10.4.13
 - PHP version: 7.3.18
 - Nextcloud version: 18.0.4
 - Bookmarks app version: 3.0.13
 - Activated Nextcloud Apps: 
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - apporder: 0.9.0
  - bookmarks: 3.0.13
  - breezedark: 18.0.16
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 1.0.1
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.5
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - notes
  - user_ldap
 - Nextcloud configuration:
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mrl33h.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "http:\/\/cloud.mrl33h.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "app_install_overwrite": [
            "calendar"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
 - Nextcloud external user backend: none

**Additional context**
Using official docker image https://hub.docker.com/_/nextcloud

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
    Doctrine\DBAL\Exception\NonUniqueFieldNameException: An exception occurred while executing 'SELECT `b`.`id`, `b`.`url`, `b`.`title`, `b`.`description`, `b`.`lastmodified`, `b`.`added`, `b`.`clickcount`, `b`.`last_preview`, `b`.`user_id` FROM `oc_bookmarks` `b` LEFT JOIN `oc_bookmarks_tags` `t` ON `t`.`bookmark_id` = `b`.`id` LEFT JOIN `oc_bookmarks_tree` `tr` ON `tr`.`id` = `b`.`id` LEFT JOIN `oc_bookmarks_shares` `s` ON `tr`.`parent_folder` = `s`.`folder_id` LEFT JOIN `oc_bookmarks_shared_folders` `p` ON `s`.`id` = `p`.`share_id` WHERE (`b`.`user_id` = ?) OR (`p`.`user_id` = ?) GROUP BY `b`.`id`, `b`.`url`, `b`.`title`, `b`.`description`, `b`.`lastmodified`, `b`.`added`, `b`.`clickcount`, `b`.`last_preview`, `b`.`user_id` HAVING (GROUP_CONCAT(`t`.`tag`) COLLATE utf8mb4_general_ci LIKE ?) OR (`b`.`url` COLLATE utf8mb4_general_ci LIKE ?) OR (`b`.`title` COLLATE utf8mb4_general_ci LIKE ?) OR (`b`.`description` COLLATE utf8mb4_general_ci LIKE ?) ORDER BY UPPER(`title`) ASC LIMIT 42' with params ["mrl33h", "mrl33h", "%Nextcloud%", "%nextcloud%", "%nextcloud%", "%nextcloud%"]: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'title' in order clause is ambiguous
```

**Browser log**
```
uncaught exception: Object
Error: "Request failed with status code 500"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
actions.js:576:12
TypeError: d.a.t is not a function
actions.js:580:15
```

**Comment by marcelklehr** [comment]
Hello  @stlehmann 
Thank you for your feedback! This is a known issue and a release with the appropriate fix is pending. :)

**Comment by stlehmann** [comment]
@marcelklehr Thanks for the feedback. Looking forward for the fix. Really appriciating your work :)
