### ISSUE TITLE
Update fails: Could not extract app

### ISSUE THREAD

**Issue by gibelium** [nextcloud/bookmarks#1052]
I keep this bug report simple, sorry for that...

**I tried to update Bookmarks App from 3.0.12 to 3.0.13 in Nextcloud 18.0.4. Tried it several times without luck.**

```
[core] Error: Exception: Could not extract app bookmarks at <<closure>>

0. /var/www/vhosts/grojekt.webo.family/httpdocs/nextcloud/lib/private/Installer.php line 197
   OC\Installer->downloadApp("*** sensitive parameter replaced ***")
1. /var/www/vhosts/grojekt.webo.family/httpdocs/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 528
   OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
2. /var/www/vhosts/grojekt.webo.family/httpdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
   OCA\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
3. /var/www/vhosts/grojekt.webo.family/httpdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "updateApp")
4. /var/www/vhosts/grojekt.webo.family/httpdocs/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "updateApp")
5. /var/www/vhosts/grojekt.webo.family/httpdocs/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "updateApp", OC\AppFramework\ ... {}, {appId: "*** sen ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({appId: "*** sen ... "})
7. /var/www/vhosts/grojekt.webo.family/httpdocs/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {appId: "*** sen ... "})
8. /var/www/vhosts/grojekt.webo.family/httpdocs/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/settings/apps/update/bookmarks")
9. /var/www/vhosts/grojekt.webo.family/httpdocs/nextcloud/index.php line 38
   OC::handleRequest()
```

**Comment by marcelklehr** [comment]
mmmh, something is going wrong extracting the files from the archive. I didn't have that problem on my prod instance.

You may be able to update by downloading the release from here https://github.com/nextcloud/bookmarks/releases

**Comment by gibelium** [comment]
> You may be able to update by downloading the release from here

Well, unfortunately I have at least one prod instance where I do not have root access. I will ask the support but it's somehow strange that the extraction fails..

**Comment by marcelklehr** [comment]
Yep, that is strange. Does it happen across multiple instances?

**Comment by marcelklehr** [comment]
Any news?

**Comment by gibelium** [comment]
Well, the support manually updated the Bookmarks App. I close this issue and hope that further updates will work as expected.

**Comment by gibelium** [comment]
Well update to 3.2.1 also failed, so I reopen this issue as I don't like ongoing discussions in closed issues... :-)

What I now tried is to delete Bookmarks App from my NC instance to check if a fresh installation of the app would solve the update problem. Now the instance is in a interesting state regarding the Bookmarks app:
- it is neither listed in the 'Your Apps' nor in the 'Active Apps' list
- it is still shown as available update

<img width="1089" alt="Screenshot 2020-06-19 at 14 29 24" src="https://user-images.githubusercontent.com/728680/85132661-8572e180-b239-11ea-8e99-3865e81b1006.png">

I would like to ask the provider's support team to delete all orphaned aspects of the app to be able to do a clean installation of the app.

What could be the cause of the current state and what would the support team need to delete beside the app folder (e.g. database tables, etc)?

**Comment by gibelium** [comment]
Today I opened a support ticket at my hoster and got the following response.
`Bookmarks app has some issues with installer and you are not the first reporting it. This seems to be more and more common problem.`

Currently installation and updates of the bookmarks app only works on console but not within the web interface.

**Comment by marcelklehr** [comment]
Mmmh, I would have hoped to get a report from them :/ Maybe I have some remnant files in my staging area.. :thinking:

**Comment by gibelium** [comment]
I asked them to share more information and got the following answer:
`The problem is in fact that installer only seems to be broken if it's started via web interface, but if it is installed via occ command, it works well.`

**Comment by marcelklehr** [comment]
That would indicate some kind of execution timeout. I've cleaned the makefile exclude filters now, and hope that that fixes it.

**Comment by gibelium** [comment]
Just tried to update to 3.2.4 -> 3.2.5. Still, the same error and exact same log entry.

If needed, please let me know what kind of information I can request from my hoster.

**Comment by marcelklehr** [comment]
I have stripped out more unnecessary files from the bundle. Hopefully it'll work with the next release. :crossed_fingers:

**Comment by nursoda** [comment]
![shot-of-error](https://user-images.githubusercontent.com/8425483/88854045-0043fa80-d1f1-11ea-9106-e52258144116.gif)
Unfortunately I only have OCCweb access to that server, so I don't know a way to access nextcloud.log … any idea how to debug this?

**Comment by gibelium** [comment]
> That would indicate some kind of execution timeout.

Are there any Nextcloud settings that correspond to the timeout errors and can be adjusted?

**Comment by marcelklehr** [comment]
> Are there any Nextcloud settings that correspond to the timeout errors and can be adjusted?

that would be a PHP setting: `max_execution_time`

v3.3.3 has been released in the meantime, any luck?

**Comment by gibelium** [comment]
> v3.3.3 has been released in the meantime, any luck?

Just tried updating from v3.3.3 to v3.3.4 via web interface without luck. Still getting the _"Could not extract app bookmarks"_ error.

I will ask my hoster if it's possible to increase the `max_execution_time` in my Nextcloud instance.

**Comment by gibelium** [comment]
Answer from my hoster:

> max_execution_time is already set at 3600 (1 hour) which should be more than enough for any PHP operation. Some apps have some strange requirements - some can't be extracted if PHP 7.3 is used, while they do extract with PHP 7.2 and vice versa...

Could it be the PHP version? What other information I could request from my hoster regarding the system configuration so that we can find out the root cause of this problem?

**Comment by nursoda** [comment]
Or could it depend on the number of bookmarks, or bookmark folders? For me, all updates worked this time.

**Comment by gibelium** [comment]
> Or could it depend on the number of bookmarks, or bookmark folders?

In my instance I have <1900 bookmarks within <150 folders. I think that this is not too much, is it?

**Comment by gibelium** [comment]
Answer to my request about the system configuration in my hosted Nextcloud instance:

- OS: CentOS 7
- HTTP server: nginx/1.18.0 (reverse proxy), Apache/2.4.6
- Database Mariadb 5.5.65
- PHP version: v7.3.20
- Nextcloud version: 18.0.7
- Nextcloud external user backend: none
- Nextcloud configuration:
  {
    "system": {
      "passwordsalt": "REMOVED SENSITIVE VALUE ",
      "secret": "REMOVED SENSITIVE VALUE ",
      "trusted_domains": [
      "[URL]"
      ],
      "datadirectory": "REMOVED SENSITIVE VALUE ",
      "dbtype": "mysql",
      "skeletondirectory": "\/var\/www\/vhosts\/[URL]\/.private\/skeleton",
      "version": "18.0.7.1",
      "overwrite.cli.url": "http:\/\/[URL]",
      "dbname": "REMOVED SENSITIVE VALUE ",
      "dbhost": "REMOVED SENSITIVE VALUE ",
      "dbport": "",
      "dbtableprefix": "oc_",
      "mysql.utf8mb4": true,
      "dbuser": "REMOVED SENSITIVE VALUE ",
      "dbpassword": "REMOVED SENSITIVE VALUE ",
      "installed": true,
      "instanceid": "REMOVED SENSITIVE VALUE ",
      "tempdirectory": "\/var\/www\/vhosts\/[URL]\/.private\/tmp",
      "mail_smtpmode": "smtp",
      "mail_from_address": "REMOVED SENSITIVE VALUE ",
      "mail_domain": "REMOVED SENSITIVE VALUE ",
      "mail_smtpauthtype": "LOGIN",
      "mail_smtphost": "REMOVED SENSITIVE VALUE ",
      "mail_smtpport": "26",
      "mail_sendmailmode": "smtp",
      "memcache.local": "\OC\Memcache\APCu",
      "memcache.locking": "\OC\Memcache\Redis",
      "redis": {
      "host": "REMOVED SENSITIVE VALUE ",
      "port": "6379"
      },
      "twofactor_enforced": "false",
      "twofactor_enforced_groups": [],
      "twofactor_enforced_excluded_groups": [],
      "has_rebuilt_cache": true,
      "maintenance": false,
      "theme": "",
      "loglevel": 2,
      "session_keepalive": false,
      "simpleSignUpLink.shown": false,
      "trashbin_retention_obligation": "auto, 30"
    }
  }

**Comment by marcelklehr** [comment]
@gibelium nothing suspicious there, I think :thinking:

**Comment by marcelklehr** [comment]
Apparently, there's nothing I can do: https://github.com/nextcloud/bookmarks/issues/1256#issuecomment-710183017

**Comment by metbril** [comment]
I installed 3.4.3 but was NOT able to update via OCC Web to 3.4.4.
Perhaps the issue should be re-opened?

**Comment by marcelklehr** [comment]
@metbril oh, that's not good. were there any error messages?

**Comment by metbril** [comment]
More or less the same as the issue owner included At the top.

**Comment by marcelklehr** [comment]
@metbril In this case, I think it's likely, https://github.com/nextcloud/bookmarks/issues/1256#issuecomment-710183017 will be relevant for you. I will reopen this, in case more people have issues even with OCC installation.
