### ISSUE TITLE
Framework to create Share to plugins

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1059]
**Is your feature request related to a problem? Please describe.**
Now that sharing exists, I'm wondering if a method could be clarified for users to write and submit their own plugins for expanding bookmarks sharing via the API and github, or possibly via the appstore.

**Describe the solution you'd like**
I've noticed projects will allow users to create and submit their own plugins for extending sharing capability, as opposed to coding through the original dev.  Wondering if this would interest you.

**Additional context**
- Share with Wallabag #524
- Extend sharing to other services such as [archive.org](https://archive.org/web/), Facebook, etc.

**Comment by marcelklehr** [comment]
@sunjam You are reading my mind :relaxed: 
Yes! That's where I think I can provide the most value at the moment. Strictly speaking, I wouldn't call this 'sharing' as that word is tied quite tightly to social sharing in the context of nextcloud, but rather something like "integrations". I would love to implement a way to add integrations with other services, perferably via nextcloud flow. The docs for nextcloud flow are still a little underwhelming, however.

**Comment by sunjam** [comment]
Perhaps it will become possible through this to incorporate social sharing.
![Screenshot_20200531_094038](https://user-images.githubusercontent.com/1787238/83357722-f1d97f80-a322-11ea-908d-38939e0d1357.png)

**Comment by marcelklehr** [comment]
Adding RSS feeds into the sharing dialog is definitely a good idea! I'll do that right now.

Things that would have to use the public link, like the social app and facebook, twitter etc. are probably easy enough to add directly in the app, too. These I would qualify as social sharing (where the receiver of the share is a person).

Things that cannot use the public link (where the receiver of the share is an app), like Archive.org and wallabag, would have to be implemented in a flow op or something similar.

**Comment by marcelklehr** [comment]
see #900 and #1138
