### ISSUE TITLE
count of items wrong & notice-field in details does not clear - after update to Bookmarks app version: 3.1.1

### ISSUE THREAD

**Issue by ramosBerlin** [nextcloud/bookmarks#1067]
a) the count of items with similar tags is wrong. 
in my case it counts 7 if there are 4 items (in 3 different folders) with a specific tag. 
Expected: only "4" is displayed with the tag. 

b) if i put info in the notice-field of 'details', the text is stored (what is fine)... but it stays there in the field even if i open the details of another bookmark. so the same text is displayed (and consequtely stored) in the other bookmark. a ugly bug.  
expected behavior: the field is nulled before reading in the data of the next bookmark.

**Desktop (please complete the following information):**
Win10
Chrome

**Server (please complete the following information):**

 - PHP version: Version: 7.3.18
 - Nextcloud version: 18.0.5
 - Bookmarks app version: 3.1.1

**Comment by acatanyg** [comment]
Server (please complete the following information):
    PHP version: Version: 7.3.17
    Nextcloud version: 18.0.4
    Mysql 10.3.23
    Bookmarks app version: 3.1.1
&
    PHP version: Version: 7.4.6
    Nextcloud version: 19.0.0
    Mysql 10.4.13
    Bookmarks app version: 3.1.1


![NC-Bookm](https://user-images.githubusercontent.com/19175654/84131276-a1f66900-aa44-11ea-91df-b55d013641d1.png)

**Comment by marcelklehr** [comment]
I have tried correcting this in the latest releases. Can you check if this is fixed for you now?

**Comment by acatanyg** [comment]
Yes, I will try asap.

Marcel Klehr <notifications@github.com> schrieb am Sa., 25. Juli 2020,
14:10:

**Comment by ramosBerlin** [comment]
no, it changed but now is giving out stange numbers.
i can not find the logic of the numbers, perhaps you are counting folders and bookmarks and there is no blank between the two numbers?

**Comment by marcelklehr** [comment]
Oof, I had a mind-o in my SQL query. :see_no_evil:

**Comment by marcelklehr** [comment]
Should be fixed in v3.3.2
