### ISSUE TITLE
Microsoft Teams bookmark:  i can't edit / move / rename

### ISSUE THREAD

**Issue by acatanyg** [nextcloud/bookmarks#1071]
Owner can't edit link:

![2020-06-09 12_59_01-Window](https://user-images.githubusercontent.com/19175654/84141521-99f1f580-aa53-11ea-8532-2db1755480db.png)

Shared list:

![2020-06-09 13_09_08-Window](https://user-images.githubusercontent.com/19175654/84141522-9a8a8c00-aa53-11ea-94ed-67ab72bbbb56.png)

Server (please complete the following information):
PHP version: Version: 7.3.17
Nextcloud version: 18.0.4
Mysql 10.3.23
Bookmarks app version: 3.1.1
&
PHP version: Version: 7.4.6
Nextcloud version: 19.0.0
Mysql 10.4.13
Bookmarks app version: 3.1.1

**Comment by marcelklehr** [comment]
I've been able to replicate this now. The issue appears when the same bookmark is in the shared folder but also in a non-shared folder. Will fix, ASAP.

**Comment by acatanyg** [comment]
Thank you very much in advance


Marcel Klehr <notifications@github.com> schrieb am Sa., 20. Juni 2020,
19:12:
