### ISSUE TITLE
Allow to set custom title for an URL

### ISSUE THREAD

**Issue by frlan** [nextcloud/bookmarks#1079]
**Is your feature request related to a problem? Please describe.**
Sometimes webpages are not having a good title-Tag so finding the right bookmark is getting complicated

**Describe the solution you'd like**
I'd like to be able to set a custom title for a URL stored within the app

**Describe alternatives you've considered**
No idea ;)

**Comment by marcelklehr** [comment]
This should already be possible, but is apparently easy to miss.
You can find the `rename` menu entry in the context menu of each bookmark.

Also see #973
