### ISSUE TITLE
Unable to add tag to new bookmark

### ISSUE THREAD

**Issue by jjstuart** [nextcloud/bookmarks#1097]
**Describe the bug**
When trying to add tag to new bookmark get error, resulting in tag not being added.

**To Reproduce**
1. Go to  bookmarks
2. Click '+New Boomark'
3. Enter https://www.theguardian.com/uk link and click --> to add, this opens details dialog to right
4. Enter new (or select existing) tag
5. Error popup will appear

**Expected behavior**
Tag added to bookmark

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.10.97

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - HTTP server: apache 2.4.41
 - Database MySQL 5.3
 - PHP version: v7.4.3
 - Nextcloud version: 18.06
 - Bookmarks app version: 3.2.2
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bookmarks: 3.2.2
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.6
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.4.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.6.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - rainloop: 6.1.4
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_antivirus
  - files_external
  - user_ldap

 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.6.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

 - Nextcloud external user backend: [e.g. ldap, or none] none

**Additional context**
Tried in Firefox 77.0.1 and same result.

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```
{"reqId":"Zu1vGHSsiBxepnifagN2","level":3,"time":"2020-06-29T13:09:37+00:00","remoteAddr":"192.168.1.1","user":"js","app":"index","method":"PUT","url":"/nextcloud/index.php/apps/bookmarks/bookmark/91","message":{"Exception":"Exception","Message":"Argument 1 passed to OCA\\Bookmarks\\Db\\TreeMapper::countChildren() must be of the type int, object given, called in /var/www/html2/nextcloud/apps/bookmarks/lib/Db/TreeMapper.php on line 417","Code":0,"Trace":[{"file":"/var/www/html2/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html2/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/html2/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func"},{"file":"/var/www/html2/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html2/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html2/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\Bookmarks\\Db\\TreeMapper::countChildren() must be of the type int, object given, called in /var/www/html2/nextcloud/apps/bookmarks/lib/Db/TreeMapper.php on line 417","Code":0,"Trace":[{"file":"/var/www/html2/nextcloud/apps/bookmarks/lib/Db/TreeMapper.php","line":417,"function":"countChildren","class":"OCA\\Bookmarks\\Db\\TreeMapper","type":"->"},{"file":"/var/www/html2/nextcloud/apps/bookmarks/lib/Db/TreeMapper.php","line":383,"function":"addToFolders","class":"OCA\\Bookmarks\\Db\\TreeMapper","type":"->"},{"file":"/var/www/html2/nextcloud/apps/bookmarks/lib/Service/BookmarkService.php","line":239,"function":"setToFolders","class":"OCA\\Bookmarks\\Db\\TreeMapper","type":"->"},{"file":"/var/www/html2/nextcloud/apps/bookmarks/lib/Controller/BookmarkController.php","line":477,"function":"update","class":"OCA\\Bookmarks\\Service\\BookmarkService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html2/nextcloud/apps/bookmarks/lib/Controller/InternalBookmarkController.php","line":121,"function":"editBookmark","class":"OCA\\Bookmarks\\Controller\\BookmarkController","type":"->"},{"file":"/var/www/html2/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"editBookmark","class":"OCA\\Bookmarks\\Controller\\InternalBookmarkController","type":"->"},{"file":"/var/www/html2/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html2/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html2/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/var/www/html2/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func"},{"file":"/var/www/html2/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html2/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html2/nextcloud/apps/bookmarks/lib/Db/TreeMapper.php","Line":598},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","version":"18.0.6.0","id":"5ef9e81229041"}
**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
This turns out to be the same bug as #1096
