### ISSUE TITLE
Did not expect more than one result when executing:

### ISSUE THREAD

**Issue by Ramdane34** [nextcloud/bookmarks#1099]
**Describe the bug**
error : 
Did not expect more than one result when executing: query "SELECT `p`.`id`, `p`.`user_id`, `p`.`title`, `p`.`folder_id` FROM `*PREFIX*bookmarks_shared_folders` `p` WHERE (`p`.`folder_id` = ?) AND (`p`.`user_id` = ?)"; 

**To Reproduce**
update Bookmarks 3.2.4

**Desktop (please complete the following information):**
 - OS: MacOS X
 - Browser FireFox

**Server (please complete the following information):**
 - OS: Debian
 - Database MariaDB
 - Nextcloud version: 18.6

**Comment by marcelklehr** [comment]
mmh, does it help to run `occ maintenance:repair`?

**Comment by Ramdane34** [comment]
hello ,


Thank you for your answer. here is the log :
- Repair MySQL collation
     - All tables already have the correct collation -> nothing to do
 - Repair mime types
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 1 tags with no entries have been removed.
 - Repair invalid shares
 - Move .step file of updater to backup location
 - Fix potential broken mount points
     - No mounts updated
 - Add log rotate job
 - Clear frontend caches
     - Image cache cleared
     - SCSS cache cleared
     - JS cache cleared
 - Clear every generated avatar on major updates
 - Add preview background cleanup job
 - Queue a one-time job to cleanup old backups of the updater
 - Cleanup invalid photocache files for carddav
 - Add background job to cleanup login flow v2 tokens
 - Remove potentially over exposing share links
     - No need to remove link shares.
 - Clear access cache of projects
 - Switches from deprecated "production" to "stable" update channel
 - Sets the enterprise logo
     - Repair step already executed
 - Reset generated avatar flag
 - Add read permissions for existing announcements
    0 [>---------------------------]    0 [->--------------------------]
 - Update hook for Appointments app
     - appointments UpdateHook finished
 - Update name of the stored view
 - Fix the share type of guest shares when migrating from ownCloud
 - Cleaning shares database of dead shares
 - Preparing app data of Pico CMS for Nextcloud
     - Checking Pico CMS requirements …
     - Syncing Pico CMS app data folder …
     - Copying Pico CMS config …
     - WARNING: Replacing Pico CMS config file "config.yml.template"
     - Registering Pico CMS templates …
     - WARNING: Replacing Pico CMS system template "empty"
     - WARNING: Replacing Pico CMS system template "sample_pico"
     - Publishing Pico CMS themes …
     - WARNING: Replacing Pico CMS system theme "default"
     - Keeping Pico CMS custom theme "astral"
     - Keeping Pico CMS custom theme "ethereal"
     - Keeping Pico CMS custom theme "freelancer"
     - Keeping Pico CMS custom theme "magazine"
     - Publishing Pico CMS plugins …
     - WARNING: Replacing Pico CMS system plugin "PicoDeprecated"
     - Keeping Pico CMS custom plugin "pico_edit"
 - Fix component of birthday calendars
     - 4 birthday calendars updated.
 - Regenerating birthday calendars to use new icons and fix old birthday events without year
     - Repair step already executed
 - Fix broken values of calendar objects
    0 [--->------------------------]    0 [----->----------------------]
 - Registering building of calendar search index as background job
     - Repair step already executed
 - Registering background jobs to update cache for webcal calendars
     - Added 0 background jobs to update webcal calendars
 - Registering building of calendar reminder index as background job
     - Repair step already executed
 - Clean up orphan event and contact data
     - 0 events without a calendar have been cleaned up
     - 0 properties without an events have been cleaned up
     - 0 changes without a calendar have been cleaned up
     - 0 cached events without a calendar subscription have been cleaned up
     - 0 changes without a calendar subscription have been cleaned up
     - 0 contacts without an addressbook have been cleaned up
     - 0 properties without a contact have been cleaned up
     - 0 changes without an addressbook have been cleaned up
 - Remove activity entries of private events
     - Removed 0 activity entries
 - Delete orphaned ACL rules
 - Rebuild font library
 - Write default encryption module configuration to the database
 - Copy default images to the app data directory
     - Icon %s already exists
     - Icon %s already exists
     - Icon %s already exists
 - Fix the share type of guest shares when migrating from ownCloud
 - Copy the share password into the dedicated column
 - Set existing shares as accepted
 - Purify and migrate collected mail addresses
 0/7 [>---------------------------]   0% 7/7 [============================] 100%
 - Insert background jobs for all accounts
 0/7 [>---------------------------]   0% 7/7 [============================] 100%
 - Make Mail itinerary extractor executable
 - Migrate Mail provisioning config from config.php to the database
     - No old config found
 - Create or update provisioned Mail accounts
     - No Mail provisioning config set
 - Migrate binary status into separate boolean fields
 - Update OAuth token expiration times
 - Migrate legacy conversation reading states
    0 [-------------->-------------]    1 [============================]
 - Repair Passwords Database Objects
     - Checking 0 tag revisions
    0 [------------------>---------]    0 [-------------------->-------]
     - Fixed 0 tag revisions
     - Checking 0 folder revisions
    0 [---------------------->-----]    0 [------------------------>---]
     - Fixed 0 folder revisions
     - Checking 0 password revisions
    0 [-------------------------->-]    0 [>---------------------------]
     - Fixed 0 password revisions
     - Checking 0 tag models
    0 [->--------------------------]    0 [--->------------------------]
     - Fixed 0 tag models
     - Checking 0 folder models
    0 [----->----------------------]    0 [------->--------------------]
     - Fixed 0 folder models
     - Checking 0 password models
    0 [--------->------------------]    0 [----------->----------------]
     - Fixed 0 password models
     - Checking 0 password tag relations
    0 [------------->--------------]    0 [-------------->-------------]
     - Fixed 0 password tag relations
 - Create help command
 - Invalidate access cache for projects conversation provider
     - Invalidation not required
 - Switches from default updater server to the customer one if a valid subscription is available
     - Repair step already executed
 - Add background job to check for backup codes
 - Populating added database structures for workflows

**Comment by marcelklehr** [comment]
Mmmh. The bookmarks repair steps don't appear in there :thinking: Is the app still installed and enabled?

**Comment by Ramdane34** [comment]
This is the problem!
I cannot install and activate Bookmarks
when i install the app i get this error:
`Did not expect more than one result when executing: query "SELECT `p`.`id`, `p`.`user_id`, `p`.`title`, `p`.`folder_id` FROM `*PREFIX*bookmarks_shared_folders` `p` WHERE (`p`.`folder_id` = ?) AND (`p`.`user_id` = ?)"; `

**Comment by marcelklehr** [comment]
Aha!

**Comment by Ramdane34** [comment]
...

**Comment by Ramdane34** [comment]
An idea of the problem ?

**Comment by marcelklehr** [comment]
I've created a repair step that will take care of this problem. I'll try to find out why it occured in the first place.

**Comment by Ramdane34** [comment]
Thank You
