### ISSUE TITLE
Bookmarklet to add Bookmarks does (mostly) not work with Safari (MacOS Catalina)

### ISSUE THREAD

**Issue by guyfromouttaspace** [nextcloud/bookmarks#1111]
I use a default configuration for Nextcloud (19.0) and the Bookmark app. Adding new bookmarks via the default app screen works - but using the bookmarklet "Add to..." seems mostly not to work. I tried it with various websites - but no luck.
A window opens up, first with showing the URL of my Nextcloud instance, than changes to the URL I want to bookmark, then back and forth and so on. After a few seconds then a "Too many redirections" error is shown.

If I remember right, in the past the bookmark app worked without any problems for me. Thank you for your help in advance!

**Comment by marcelklehr** [comment]
mmmh, which version of the bookmarks app is this? Can you post an example URL of where the bookmarklet takes you? This smells like a safari bug, but it's weird that it has worked before.

**Comment by guyfromouttaspace** [comment]
It is Nextcloud 19.0 and bookmark 3.2.4 - MacOS 10.15.6 and the latest Safari.
It causes many redirects while loading and thens stops at the url I wanted to bookark.

URLs: 
welt.de 
heise.de
...and a few more :'(...

**Comment by marcelklehr** [comment]
Could you try with a different browser to isolate whether this is a browser issue?

**Comment by guyfromouttaspace** [comment]
Hi Marcel, it is on MacOS 10.15.6 (occured also on the previous version too) on Safari and Firefox.
I also updated to the latest version 3.2.5 and the error still persists.
welt.de for example - redirects happening and after a few seconds it show the error screen mentioned.

**Comment by marcelklehr** [comment]
It appears that this is a Safari feature (:clap: ): https://support.securly.com/hc/en-us/articles/360000881087-How-to-resolve-the-too-many-redirects-error-on-Safari-

**Comment by guyfromouttaspace** [comment]
> It appears that this is a Safari feature (👏 ): https://support.securly.com/hc/en-us/articles/360000881087-How-to-resolve-the-too-many-redirects-error-on-Safari-

uh oh... ok - but thank you for checking and the research!
