### ISSUE TITLE
42 out of 284 bookmarks visible.

### ISSUE THREAD

**Issue by michael-pellegrini** [nextcloud/bookmarks#1112]
**Is your feature request related to a problem? Please describe.**
Yes, I can only scroll through 42 bookmarks out of 284. 
I'm stuck at the first 42 bookmarks there isn't a way view all bookmarks.
I would like to browse all bookmarks in order to organize, rename, and remove ones no longer needed.

**Describe the solution you'd like**
1.) When you scroll to the bottom additional bookmarks are added to the end,  for example, social sites like Reddit keep adding content as you scroll down. 
2.)  An Arrow key that will cycle through all of your bookmarks, one page at a time.

**Describe alternatives you've considered**
The search feature allows me to find any bookmark by searching for it.

**Additional context**
Screenshot of bookmarks alphabitized. 
![bookmarks-nextcloud-42-visible](https://user-images.githubusercontent.com/47049792/87602823-abb76000-c6c5-11ea-940a-76a2b347b7ce.png)

**Comment by marcelklehr** [comment]
Hello @hm400 
This is actually a regression, but thank you very much for reporting it. I'm fixing this atm.
