### ISSUE TITLE
Update 3.2.4→3.2.5 failed on 1 (out of 3) server(s)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/bookmarks#1120]
I updated the NC instances on my server: no issue; on a dedicated hosted server: no issue. On a shared hosted server: I got some error that updated could not be performed. I deactivated, then uninstalled the app: OK. Upon trying to install there, I get "Could not extract app bookmarks". NC Version is 19.0.1. One I see is that this server doesn't have imagick. Sorry, I have no more info, don't have a login to that server, just OCCweb. Is there anything I should be able to do using OCCweb?

**Comment by marcelklehr** [comment]
This is a known albeit unsolved issue: #1052

**Comment by nursoda** [comment]
This morning, I retried to install – and it worked?!

**Comment by nursoda** [comment]
Same server, Update 3.3.1→3.3.2 fails since it was released yesterday (tried at different times during night an day in case it was load sensitive). All my other (NGINX based) NCs on my own NUC server updated fine, also the dedicated hosted server (running Apache).

**Comment by nursoda** [comment]
Tried again this morning (approx. same time as yesterday) – and it worked – after at least 20 tries during ~36 hours that didn't. This smells like a load/timing issue.
