### ISSUE TITLE
3.3.0 fails; missing an update in appinfo/info.xml

### ISSUE THREAD

**Issue by StackKorora** [nextcloud/bookmarks#1121]
I was unable to update to 3.3.0. Tried a bunch of things, but even a purge/manual install still showed 3.2.5. Went looking and appinfo/info.xml was still pointing to 3.2.5. As soon as I edited that file to 3.3.0 everything worked as expected.

Thanks!

**Comment by marcelklehr** [comment]
Oof, I'm sorry for the inconvenience. v3.3.1 is out now. Let me know if the update works.

**Comment by StackKorora** [comment]
Spot on! Perfect.
Thanks for the quick fix!
