### ISSUE TITLE
Not all of the available space is used to display the list of categories in the left frame

### ISSUE THREAD

**Issue by j-ed** [nextcloud/bookmarks#1126]
**Describe the bug**
To display the list of categories in the left frame only a small part of the available space is used. If I scroll down the list, this is only done within the marked area:

![grafik](https://user-images.githubusercontent.com/2572764/88457170-950ec700-ce84-11ea-9c3d-34edfbe8757b.png)

**To Reproduce**
1. Open the bookmarks app
2. check the list of displayed categories in the left frame
=> only half of the available space is used to display the categories.

**Expected behavior**
All of the available space should be used to display categories.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 78.0.2

**Server (please complete the following information):**
 - OS: Linux
 - HTTP server: Apache2 v2.4.43
 - Database: MariaDB v10.2.24
 - PHP version: 7.2.31
 - Nextcloud version: 18.0.7
 - Bookmarks app version: 3.3.1

**Comment by marcelklehr** [comment]
cc @nextcloud/vuejs aaah, help :scream_cat:

**Comment by raimund-schluessler** [comment]
Probably due to https://github.com/nextcloud/nextcloud-vue/releases/tag/v2.2.0 and especially https://github.com/nextcloud/nextcloud-vue/pull/1160.

**Comment by marcelklehr** [comment]
Fixed with https://github.com/nextcloud/bookmarks/releases/tag/v3.3.2

**Comment by marcelklehr** [comment]
@skjnldsv Was this breaking change by any chance documented somewhere?

**Comment by skjnldsv** [comment]
Yes in the release changelog of the vue components

**Comment by marcelklehr** [comment]
That's where it first says "breaking changes" without (bumping the major version number) and then "revert" again in the next release with a link to a PR https://github.com/nextcloud/nextcloud-vue/pull/1160. And even if I understood what's happening I'm supposed to dig through all changes to see what exactly I'm supposed to adjust while the official docs don't even mention any slots in that component? I'm not a full-time core dev subscribed to all changes happening in any of the repos. I have to rely on documentation. :disappointed:

**Comment by skjnldsv** [comment]
Yeah, sorry about this.
We should have some documentation for AppNavigation :)
I usually check the changelog in the dependabot PRs https://github.com/nextcloud/bookmarks/pull/1109

**Comment by skjnldsv** [comment]
> then "revert" again in the next release

The main slot and list slot were never reverted
https://github.com/nextcloud/nextcloud-vue/pull/1107/files

The footer one was https://github.com/nextcloud/nextcloud-vue/pull/1160

**Comment by marcelklehr** [comment]
So, there's no footer slot anymore?

**Comment by marcelklehr** [comment]
> I usually check the changelog in the dependabot PRs

And I usually rely on semver :D

**Comment by skjnldsv** [comment]
> And I usually rely on semver :D

Yeah, we're not the best for this on the vue components :/
I'm always afraid to end up at `v21.1.4` in 6 months :see_no_evil:

**Comment by skjnldsv** [comment]
> So, there's no footer slot anymore?

There is :p
You can check the docs for the slots https://nextcloud-vue-components.netlify.app/#/Components/App%20containers?id=appnavigation-1
