### ISSUE TITLE
Update NC 19.0.1 Bookmarks 3.3.1: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'where clause'

### ISSUE THREAD

**Issue by Drumsk8** [nextcloud/bookmarks#1127]
Nextcloud Update from 19.0.0.12 -> 19.0.1 was blocked due to an issue with Bookmarks app. 

Disabled the app and resolved Nextcloud update issues and now correctly showing 19.0.1. If I attempt to enable the Bookmarks app (version 3.3.1) I am greeted with the following error:

An exception occurred while executing 'DELETE FROM `oc_bookmarks_shared_folders` WHERE (`id` = ?) AND (`type` = ?)' with params ["18", "share"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'where clause'

Reporting the issue and curious as to what would be the safest procedure to clear this error and be able to re-enable the app?

Thank you.

**Comment by marcelklehr** [comment]
Fixed with https://github.com/nextcloud/bookmarks/releases/tag/v3.3.2
