### ISSUE TITLE
Folder cannot be created. Browser Developer Console shows "412 Precondition Failed" for Javascripts.

### ISSUE THREAD

**Issue by capricorn72** [nextcloud/bookmarks#1144]
In the bookmark app, I can create exactly 1 folder.
When trying to create a 2nd folder, a popup sais "Folder cannot be created".

The initiator
https://cloud.*******/******/apps/bookmarks/js/bookmarks.main.js?v=955c65ad-20
produces #412 precondition failed shown in developer console in chromium.

Headers - General:
Request URL: https://cloud.*********/*********/index.php/apps/bookmarks/folder
Request Method: POST
Status Code: 412 Precondition failed (from ServiceWorker)
Referrer Policy: strict-origin-when-cross-origin

Headers - Response:
Cache-Control: no-cache, no-store, must-revalidate
Connection: Keep-Alive
Content-Length: 31
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self'
Content-Type: application/json; charset=utf-8
Date: Wed, 05 Aug 2020 06:16:20 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Feature-Policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
Keep-Alive: timeout=5, max=98
Pragma: no-cache
Referrer-Policy: strict-origin-when-cross-origin
Server: Apache
Strict-Transport-Security: max-age=15768000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block

A second entry for:
https://cloud.*******/******/apps/bookmarks/service-worker.js
with #412 precondition failed.

In the log file there appears nothing as the javascript seems to be blocked (#412).

What can we do?

Version: stable nextCloud 18.0.7
Bookmarks version: 	3.3.3
OS: Ubuntu Linux 18.04 LTS
Web-Server from Repo: apache2                                2.4.29-1ubuntu4.13
PHP from Repo: php7.2                                 7.2.24-0ubuntu0.18.04.6

**Comment by capricorn72** [comment]
Additional, we found in the protocol via web gui this entry:
Exception: The requested uri(/svg/core/filetypes/folder) cannot be processed by the script '/******/index.php')

**Comment by marcelklehr** [comment]
Mmh, perhaps the service worker is the problem. can you try disabling it as folllows:

1. Press F12
2. Go to the "application" tab and disable the service worker

**Comment by capricorn72** [comment]
There is no "application" tab in the developer tools. Da du auch aus de bist, es ist ein de firefox, aber von Anwendungen, Applikationen finde ich da keinen Tab. Dann weiter in en, damit die Community mitlesen kann...

Console tab says "ServiceWorker not supported", later:
Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: https://cloud.********.***/*********/apps/bookmarks/js/bookmarks.main.js?v=955c65ad-20
Source-Map-Adresse: bookmarks.main.js.map

I found a workaround - it seems the bookmarks app has hard coded / URL in its code.
Our nc runs on a subdirectory of the webserver. When changing DocumentRoot in Apache to the subdir of nc, the bookmark app works fine.
I found this via nc log errors:
"Exception","Message":"The requested uri(/svg/core/filetypes/folder) cannot be processed by the script '/subdir/index.php')"

**Comment by marcelklehr** [comment]
So, does this mean it's not a bookmarks issue? (Cause the URL you posted seems to be correct: `Request URL: https://cloud.*********/*********/index.php/apps/bookmarks/folder`)

**Comment by capricorn72** [comment]
I do not understand why this should _NOT_ be a bookmark issue when this error only appears in the bookmarks app.

**Comment by marcelklehr** [comment]
No need to yell :)

Apparently there's a problem with CSRF checks and subdirectories. I'm not sure how this relates to each other, though.

**Comment by marcelklehr** [comment]
This might be related to a bug fixed in v3.3.4, can you check whether this is fixed in the new release?

**Comment by capricorn72** [comment]
In the new version, the bug seems to be fixed.

**Comment by marcelklehr** [comment]
Yaaay :tada:
