### ISSUE TITLE
Text off-screen

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/bookmarks#1153]
**Describe the bug**
Tooltip text for several items of settings is partially off-screen. Bookmarks app 3.3.3.

![Bug](https://user-images.githubusercontent.com/47887158/89716886-21ef6f80-d9b1-11ea-8d43-1694b8bbd467.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS X]

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7]
 - HTTP server: [e.g. nginx 1.1]
 - Database [e.g. MySQL 5.3]
 - PHP version: [e.g. v7.2]
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)]
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)]
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by radoeka** [comment]
Same for me.  It is valid for multiple tooltips in that part:
- RSS feed
- Remove all information (BTW will there be confirmation question presented to the user, when this button is clicked?)
- Bookmarklet

**Comment by marcelklehr** [comment]
Confirmed.

@nextcloud/vuejs is there anything I can do about this?

**Comment by skjnldsv** [comment]
v-tooltip.auto ?

**Comment by marcelklehr** [comment]
auto is the default, I think. even with right it doesn't work, because the poor tooltip is afraid of overflowing the navigation column apparently :/

**Comment by marcelklehr** [comment]
> BTW will there be confirmation question presented to the user, when this button is clicked?

yes, see #599 for historic interest. :D

**Comment by RomainTT** [comment]
Also true in this situation:

![image](https://user-images.githubusercontent.com/12847715/92241582-bcfb3c80-eebe-11ea-9058-2b9c5cb7318c.png)

(Sorry it is in French) The drop-down menu is cut on its right side.
