### ISSUE TITLE
Easier way to find the tag input search bar/area

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1156]
**Is your feature request related to a problem? Please describe.**
When I want to search for bookmark via a tag or multiple tags, and the tag is nog listed in view on the left side of the window, there is no tag search field shown.  This is what I get presented (Bookmarks 3.3.3):

![image](https://user-images.githubusercontent.com/2937666/90014857-041f5480-dca8-11ea-995a-69be8eb9cac9.png)

**Describe the solution you'd like**
Present a tag search box, or present it when the that part of the window is (double) clicked.

![image](https://user-images.githubusercontent.com/2937666/90015417-df77ac80-dca8-11ea-9c8a-e693104aaa2e.png)

**Describe alternatives you've considered**
Click at the most top bookmark, this opens/creates the tag search field.

Then try to insert the desired tag and continue from there.

However, removing a tag is not easy => will open an issue for that.

**Comment by marcelklehr** [comment]
> and the tag is nog listed in view on the left side of the window

mmh, if the tag is not shown on the left, it doesn't exist, I think. :thinking:

**Comment by radoeka** [comment]
> mmh, if the tag is not shown on the left, it doesn't exist, I think.

The tag exists, but due to the many tags, it is a long list and the tag is not visible (need to scroll down to get the tag in view).

**Comment by marcelklehr** [comment]
Ah, I see. It's a bit of a hidden mode.

This should be better: 

![image](https://user-images.githubusercontent.com/986878/90292703-bc085980-de82-11ea-84b1-9932fc3e2cc1.png)

**Comment by radoeka** [comment]
Thanks.  I've to wait to the new version to experience the improvement.

**Comment by radoeka** [comment]
Just update to bookmarks-3.3.4. I don't see a change :(

![image](https://user-images.githubusercontent.com/2937666/90553769-342d9280-e195-11ea-9d92-74b6b7703903.png)

I don't any reference that there is a tag field within the yellow box.

In case the tag field should be available, can you open this issue, please.

**Comment by marcelklehr** [comment]
Same here, this feature will be in v3.4.0
