### ISSUE TITLE
Make it easier to remove a tag

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1157]
**Is your feature request related to a problem? Please describe.**
Make it easier to remove a tag from tag search bar.

At the moment one need to search for a marked tag (value) in a long drop down menu and once found, that value must be untagged.  It works, but it is not really intuitive.  Can this be easier, please?

**Describe the solution you'd like**
Add a cross to the end of tag, when clicked the tag is removed (is tag possible??)
I've that in another system, and that works very intuitive!

A mockup (the yellow cross could be grey, and results in the tag being removed):
![image](https://user-images.githubusercontent.com/2937666/90016309-11d5d980-dcaa-11ea-97f6-1e089bb42254.png)

Or when possible, just backspace; put the cursor right from the tag <backspace> and the tag is gone :)

**Describe alternatives you've considered**
The current way, but that is cumbersome.

**Comment by marcelklehr** [comment]
see https://github.com/nextcloud/nextcloud-vue/issues/821

**Comment by radoeka** [comment]
Had to change some bookmarks today.  Again I missed the possibility to remove a tag easily, which in my opinion would be clicking on a cross located in the tag (see yellow cross in the screenshot of this request).  The yellow cross should of course not be yellow, but just an small black one.
