### ISSUE TITLE
Make tags clickable (again)

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1158]
**Is your feature request related to a problem? Please describe.**
As far as I remember, tags were clickable in the past.  Very nice, and easy.
At the moment tags can't be clicked :(

![image](https://user-images.githubusercontent.com/2937666/90016936-0fc04a80-dcab-11ea-9c24-bc696ec30ac3.png)

**Describe the solution you'd like**
When the tag is clicked is should be added to tag filter criteria.

**Describe alternatives you've considered**
Use the tag search bar and type the tag, but that is not is conveniënt as just click a tag.

**Comment by marcelklehr** [comment]
Ah, yes. I forgot to reimplement this with the new UI.

**Comment by radoeka** [comment]
Thanks.

**Comment by radoeka** [comment]
Hi, I'm sorry to say: the tag background color changes when I hover over the tag.  However, when I select the tag, by  clicking at the tag nothing happens.
This is in Chrome as well as in Firefox.  Does this functionality need a little more polish?

Can you reopen the issue?

**Comment by marcelklehr** [comment]
v3.3.4 is just a bug fix release, it doesn't have this feature.
