### ISSUE TITLE
Make tags in the tag dropdown menu easy to find

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1159]
**Is your feature request related to a problem? Please describe.**
Make tags in the tag dropdown menu easy to find, for example by listing the tags in alphabetic (sorted) order.

I set my bookmarks to be shown with 'recent added' => nice to quickly check that the bookmark I just added has been added indeed.

![image](https://user-images.githubusercontent.com/2937666/90017555-fff53600-dcab-11ea-8106-98025c506dc1.png)

But the same order seems to be used in the tag drop down list, or at least something that makes it not sorted, and therefor difficult to search.  

Just a simple example:
![image](https://user-images.githubusercontent.com/2937666/90017721-3a5ed300-dcac-11ea-87fe-a5df87dc3025.png)

There are 2 places where the dropdown menu is used:
![image](https://user-images.githubusercontent.com/2937666/90018074-b0fbd080-dcac-11ea-8819-b17cf1f08be0.png)

**Describe the solution you'd like**

Entries in the tag dropdown menu should be ordered alphabetically:

There are two list, see screenshot above.

**Describe alternatives you've considered**
I'm not aware of another solution.  The current one is cumbersome, as it is unclear where a tag is located....

**Comment by marcelklehr** [comment]
Thank you for your feedback!
Tags are currently ordered by usage frequency and you can search the list by typing. This should be good enough, I think.

**Comment by radoeka** [comment]
That's a pity.  Hopefully it will be adjusted someday magically ;)

Thanks.
