### ISSUE TITLE
Auto-tagging

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#1160]
It would be possible to automatically extract tags from web pages' meta data, upon creating a bookmark.
So far, I have discounted that as intrusive, because the user will probably either want no tags at all, or use their own tagging system.

Now, I'm thinking that more tags probably never hurt, even when you primarily use folders for organization.

What do you think?

cc @nextcloud/designers

**Comment by SuperSandro2000** [comment]
If every bookmark of my over 200 would have 2 unique tags it would be quite useless and very cluttered.

What meta data do you want to use? How would they translate to tags?

**Comment by stefan-niedermann** [comment]
`keywords` meta tag sounds reasonable 🤔 ?

**Comment by marcelklehr** [comment]
e.g. youtube auto-populates their keywords metadata with the video tags, but other than that very few sites seem to have that tag anymore.

**Comment by stefan-niedermann** [comment]
Maybe one can try to extract information from `open graph` meta data, like `og:type="article"` -> tag `article`? (though `og:type` will likely be always just `website`...) - just throwing ideas around...

**Comment by marcelklehr** [comment]
The main problem is probably that sites don't have consistent keywords causing wild growth of tags.
