### ISSUE TITLE
Error about missing index 

### ISSUE THREAD

**Issue by frlan** [nextcloud/bookmarks#1164]
**Describe the bug**
When access the activity page of Nextcloud I'm getting an error inside log. This happens after I added a new bookmark -- but this might bbe an coincident

`Aug 15 14:35:48 sergej Nextcloud[19215]: {"reqId":"xVOpEI1iaMpaNMckfJDa","level":3,"time":"2020-08-15T12:35:48+00:00","remoteAddr":"xxxx","user":"xxxn","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0","message":"Undefined index: sharee at /srv/nc/apps/bookmarks/lib/Activity/Provider.php#64","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.7.1"}`

**To Reproduce**
1. Go to activity page 
2. See error

**Expected behavior**
No error inside logs ;)

**Server (please complete the following information):**
 - OS: Debian 10
 - HTTP server: Nginx
 - Database: Postgres 11
 - PHP version: 7.3
 - Nextcloud version: 
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)]
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration:
 php occ config:list
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.chaotenchaos.de",
            "frlan.stratum0.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud2.chaotenchaos.de",
        "dbtype": "pgsql",
        "version": "18.0.7.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "log_type": "syslog",
        "logfile": "",
        "loglevel": "3",
        "updater.release.channel": "stable",
        "data-fingerprint": "eafa99f477d6c0f73d28314b18806445",
        "preview_max_filesize_image": 100,
        "app_install_overwrite": [
            "calendar"
        ],
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        }
    },
    "apps": {
        "accessibility": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.4.0"
        },
        "activity": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "2.11.0"
        },
        "admin_audit": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "admin_notifications": {
            "installed_version": "1.0.2",
            "published-deprecation-notification": "yes",
            "types": "logging",
            "enabled": "no"
        },
        "apporder": {
            "installed_version": "0.10.0",
            "types": "",
            "enabled": "yes"
        },
        "audioplayer": {
            "types": "filesystem",
            "installed_version": "2.7.0",
            "enabled": "no"
        },
        "backgroundjob": {
            "lastjob": "5229"
        },
        "bookmarks": {
            "types": "",
            "installed_version": "3.3.3",
            "enabled": "yes"
        },
        "breezedark": {
            "enabled": "no",
            "installed_version": "17.0.3",
            "types": ""
        },
        "bruteforcesettings": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.6.0"
        },
        "calendar": {
            "types": "",
            "enabled": "yes",
            "installed_version": "2.0.3"
        },
        "camerarawpreviews": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "0.7.8"
        },
        "caniupdate": {
            "types": "",
            "installed_version": "0.2.0",
            "enabled": "no",
            "published-deprecation-notification": "yes"
        },
        "checksum": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "0.4.5"
        },
        "circles": {
            "installed_version": "0.14.1",
            "types": "",
            "enabled": "no"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "types": "filesystem",
            "installed_version": "1.1.0"
        },
        "comments": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "contacts": {
            "types": "",
            "enabled": "yes",
            "installed_version": "3.3.0"
        },
        "cookbook": {
            "types": "",
            "enabled": "yes",
            "installed_version": "0.7.6"
        },
        "core": {
            "installedat": "1528016034.6822",
            "vendor": "nextcloud",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "public_files": "files_sharing\/public.php",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "umgmt_show_last_login": "true",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "shareapi_exclude_groups_list": "[\"\"]",
            "shareapi_exclude_groups": "no",
            "shareapi_only_share_with_group_members": "yes",
            "shareapi_default_expire_date": "yes",
            "shareapi_enforce_expire_date": "no",
            "encryption_enabled": "no",
            "scss.variables": "d41d8cd98f00b204e9800998ecf8427e",
            "lastupdatedat": "1597488490",
            "updater.secret.created": "1594977021",
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "theming.variables": "d41d8cd98f00b204e9800998ecf8427e",
            "lastupdateResult": "[]",
            "oc.integritycheck.checker": "[]",
            "lastcron": "1597494603"
        },
        "dashboard": {
            "installed_version": "5.0.1",
            "types": "",
            "enabled": "no"
        },
        "dav": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "buildCalendarSearchIndex": "yes",
            "buildCalendarReminderIndex": "yes",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "chunks_migrated": "1"
        },
        "drawio": {
            "installed_version": "0.9.0",
            "types": "filesystem",
            "enabled": "no"
        },
        "encryption": {
            "types": "filesystem",
            "recoveryKeyId": "recoveryKey_fbf830a4",
            "publicShareKeyId": "pubShare_fbf830a4",
            "masterKeyId": "master_fbf830a4",
            "enabled": "no",
            "installed_version": "2.6.0"
        },
        "end_to_end_encryption": {
            "installed_version": "1.1.0",
            "types": "filesystem",
            "enabled": "no"
        },
        "event_update_notification": {
            "types": "logging,dav",
            "installed_version": "1.0.2",
            "enabled": "yes"
        },
        "federatedfilesharing": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "federation": {
            "types": "authentication",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "files": {
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500",
            "installed_version": "1.13.1"
        },
        "files_accesscontrol": {
            "types": "filesystem",
            "installed_version": "1.8.1",
            "enabled": "yes"
        },
        "files_automatedtagging": {
            "types": "filesystem",
            "installed_version": "1.8.3",
            "enabled": "no"
        },
        "files_downloadactivity": {
            "installed_version": "1.4.0",
            "types": "filesystem",
            "enabled": "no"
        },
        "files_external": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.9.0",
            "allow_user_mounting": "yes",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,swift,\\OC\\Files\\Storage\\SFTP_Key"
        },
        "files_markdown": {
            "types": "",
            "enabled": "yes",
            "installed_version": "2.3.0"
        },
        "files_mindmap": {
            "enabled": "no",
            "installed_version": "0.0.11",
            "types": ""
        },
        "files_pdfviewer": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.7.0"
        },
        "files_readmemd": {
            "types": "filesystem",
            "fileslist_header": "[\"HEADER\"]",
            "fileslist_footer": "[\"README\"]",
            "installed_version": "1.1.4",
            "show_asciidoc": "false",
            "show_html": "false",
            "show_title": "true",
            "yellow_back": "true",
            "auto_refresh": "false",
            "enabled": "no"
        },
        "files_rightclick": {
            "types": "",
            "enabled": "yes",
            "installed_version": "0.15.2"
        },
        "files_sharing": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.10.1"
        },
        "files_texteditor": {
            "types": "",
            "installed_version": "2.8.0",
            "enabled": "no"
        },
        "files_trackdownloads": {
            "installed_version": "1.4.0",
            "types": "filesystem",
            "enabled": "no"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "types": "filesystem,dav",
            "installed_version": "1.11.0"
        },
        "files_videoplayer": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "no"
        },
        "firstrunwizard": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "2.7.0"
        },
        "gallery": {
            "types": "",
            "enabled": "no",
            "installed_version": "18.4.0"
        },
        "gpxedit": {
            "types": "",
            "enabled": "yes",
            "installed_version": "0.0.13"
        },
        "gpxmotion": {
            "installed_version": "0.0.10",
            "types": "",
            "enabled": "no"
        },
        "gpxpod": {
            "types": "",
            "reset304": "1",
            "enabled": "yes",
            "installed_version": "4.2.2",
            "resetPics404": "1"
        },
        "groupfolders": {
            "types": "filesystem",
            "enabled": "no",
            "installed_version": "3.0.2"
        },
        "initialcheck": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "no"
        },
        "logreader": {
            "types": "",
            "enabled": "yes",
            "installed_version": "2.3.0"
        },
        "lookup_server_connector": {
            "types": "authentication",
            "enabled": "yes",
            "installed_version": "1.6.0"
        },
        "mail": {
            "enabled": "no",
            "types": "",
            "installed_version": "1.4.0"
        },
        "maps": {
            "types": "filesystem",
            "lastAddressLookup": "1596826680",
            "enabled": "yes",
            "installed_version": "0.1.6"
        },
        "metadata": {
            "types": "",
            "enabled": "yes",
            "installed_version": "0.12.0"
        },
        "mindmaps": {
            "installed_version": "0.1.0",
            "types": "",
            "enabled": "no"
        },
        "music": {
            "ocsid": "164319",
            "types": "filesystem",
            "installed_version": "0.16.0",
            "enabled": "yes"
        },
        "nextcloud_announcements": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.7.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200"
        },
        "notes": {
            "types": "",
            "enabled": "yes",
            "installed_version": "3.6.1"
        },
        "notifications": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "2.6.0"
        },
        "oauth2": {
            "types": "authentication",
            "enabled": "yes",
            "installed_version": "1.6.0"
        },
        "ocsms": {
            "enabled": "no",
            "installed_version": "2.1.1",
            "types": ""
        },
        "ojsxc": {
            "apiSecret": "62u9Qq84bqm3J2jxYVgDXxU",
            "installed_version": "3.4.3",
            "types": "prelogin",
            "enabled": "no"
        },
        "password_policy": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "minLength": "8"
        },
        "photos": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes"
        },
        "previewgenerator": {
            "types": "filesystem",
            "installed_version": "2.3.0",
            "enabled": "yes"
        },
        "privacy": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "provisioning_api": {
            "types": "prevent_group_restriction",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "quota_warning": {
            "types": "filesystem",
            "installed_version": "1.7.0",
            "enabled": "yes"
        },
        "recommendations": {
            "types": "",
            "enabled": "yes",
            "installed_version": "0.6.0"
        },
        "serverinfo": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "settings": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "socialsharing_facebook": {
            "types": "",
            "installed_version": "2.1.0",
            "enabled": "yes"
        },
        "socialsharing_twitter": {
            "types": "",
            "enabled": "yes",
            "installed_version": "2.1.0"
        },
        "spreed": {
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction",
            "installed_version": "5.0.2",
            "enabled": "no"
        },
        "support": {
            "enabled": "yes",
            "types": "session",
            "installed_version": "1.1.1",
            "SwitchUpdaterServerHasRun": "yes"
        },
        "survey_client": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.6.0",
            "last_sent": "1595632503",
            "last_report": "{\"id\":\"oc3lv9lrfwyv\",\"items\":[[\"server\",\"version\",\"18.0.7.1\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"memcache.distributed\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"\\\\OC\\\\Memcache\\\\Redis\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.3.19\"],[\"php\",\"memory_limit\",-1],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"pgsql\"],[\"database\",\"version\",\"PostgreSQL 11.7 (Debian 11.7-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit\"],[\"database\",\"size\",852849311],[\"apps\",\"files_videoplayer\",\"disabled\"],[\"apps\",\"mindmaps\",\"disabled\"],[\"apps\",\"apporder\",\"0.10.0\"],[\"apps\",\"initialcheck\",\"disabled\"],[\"apps\",\"encryption\",\"disabled\"],[\"apps\",\"spreed\",\"disabled\"],[\"apps\",\"theming\",\"disabled\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"password_policy\",\"1.8.0\"],[\"apps\",\"provisioning_api\",\"1.8.0\"],[\"apps\",\"serverinfo\",\"1.8.0\"],[\"apps\",\"notes\",\"3.6.0\"],[\"apps\",\"federation\",\"1.8.0\"],[\"apps\",\"lookup_server_connector\",\"1.6.0\"],[\"apps\",\"oauth2\",\"1.6.0\"],[\"apps\",\"files\",\"1.13.1\"],[\"apps\",\"activity\",\"2.11.0\"],[\"apps\",\"dav\",\"1.14.0\"],[\"apps\",\"files_external\",\"1.9.0\"],[\"apps\",\"files_sharing\",\"1.10.1\"],[\"apps\",\"files_trashbin\",\"1.8.0\"],[\"apps\",\"files_versions\",\"1.11.0\"],[\"apps\",\"sharebymail\",\"1.8.0\"],[\"apps\",\"workflowengine\",\"2.0.0\"],[\"apps\",\"admin_audit\",\"1.8.0\"],[\"apps\",\"comments\",\"1.8.0\"],[\"apps\",\"firstrunwizard\",\"2.7.0\"],[\"apps\",\"nextcloud_announcements\",\"1.7.0\"],[\"apps\",\"notifications\",\"2.6.0\"],[\"apps\",\"systemtags\",\"1.8.0\"],[\"apps\",\"support\",\"1.1.1\"],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"survey_client\",\"1.6.0\"],[\"apps\",\"updatenotification\",\"1.8.0\"],[\"apps\",\"logreader\",\"2.3.0\"],[\"apps\",\"circles\",\"disabled\"],[\"apps\",\"dashboard\",\"disabled\"],[\"apps\",\"files_downloadactivity\",\"disabled\"],[\"apps\",\"files_trackdownloads\",\"disabled\"],[\"apps\",\"drawio\",\"disabled\"],[\"apps\",\"admin_notifications\",\"disabled\"],[\"apps\",\"caniupdate\",\"disabled\"],[\"apps\",\"files_mindmap\",\"disabled\"],[\"apps\",\"end_to_end_encryption\",\"disabled\"],[\"apps\",\"groupfolders\",\"disabled\"],[\"apps\",\"ojsxc\",\"disabled\"],[\"apps\",\"audioplayer\",\"disabled\"],[\"apps\",\"ocsms\",\"disabled\"],[\"apps\",\"files_automatedtagging\",\"disabled\"],[\"apps\",\"event_update_notification\",\"1.0.2\"],[\"apps\",\"files_pdfviewer\",\"1.7.0\"],[\"apps\",\"cloud_federation_api\",\"1.1.0\"],[\"apps\",\"files_accesscontrol\",\"1.8.1\"],[\"apps\",\"calendar\",\"2.0.3\"],[\"apps\",\"quota_warning\",\"1.7.0\"],[\"apps\",\"user_usage_report\",\"disabled\"],[\"apps\",\"socialsharing_facebook\",\"2.1.0\"],[\"apps\",\"socialsharing_twitter\",\"2.1.0\"],[\"apps\",\"bookmarks\",\"3.2.5\"],[\"apps\",\"breezedark\",\"disabled\"],[\"apps\",\"music\",\"0.15.1\"],[\"apps\",\"tasks\",\"0.13.2\"],[\"apps\",\"previewgenerator\",\"2.3.0\"],[\"apps\",\"files_markdown\",\"2.3.0\"],[\"apps\",\"checksum\",\"0.4.4\"],[\"apps\",\"contacts\",\"3.3.0\"],[\"apps\",\"bruteforcesettings\",\"1.6.0\"],[\"apps\",\"metadata\",\"0.12.0\"],[\"apps\",\"accessibility\",\"1.4.0\"],[\"apps\",\"camerarawpreviews\",\"0.7.4\"],[\"apps\",\"gpxmotion\",\"disabled\"],[\"apps\",\"files_readmemd\",\"disabled\"],[\"apps\",\"mail\",\"disabled\"],[\"apps\",\"viewer\",\"1.2.0\"],[\"apps\",\"gpxpod\",\"4.2.2\"],[\"apps\",\"gpxedit\",\"0.0.13\"],[\"apps\",\"federatedfilesharing\",\"1.8.0\"],[\"apps\",\"files_rightclick\",\"0.15.2\"],[\"apps\",\"privacy\",\"1.2.0\"],[\"apps\",\"recommendations\",\"0.6.0\"],[\"apps\",\"text\",\"2.0.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.7.0\"],[\"apps\",\"settings\",\"1.0.0\"],[\"apps\",\"photos\",\"1.0.0\"],[\"apps\",\"maps\",\"0.1.6\"],[\"apps\",\"cookbook\",\"0.7.6\"],[\"stats\",\"num_files\",602985],[\"stats\",\"num_users\",12],[\"stats\",\"num_storages\",27],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",17],[\"stats\",\"num_storages_other\",9],[\"stats\",\"num_comments\",3],[\"stats\",\"num_comment_markers\",2],[\"stats\",\"num_systemtags\",89],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",13],[\"files_sharing\",\"num_shares_user\",3],[\"files_sharing\",\"num_shares_groups\",2],[\"files_sharing\",\"num_shares_link\",8],[\"files_sharing\",\"num_shares_link_no_password\",8],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_1\",1],[\"files_sharing\",\"permissions_0_31\",3],[\"files_sharing\",\"permissions_3_17\",4],[\"files_sharing\",\"permissions_3_31\",1],[\"files_sharing\",\"permissions_3_15\",2],[\"files_sharing\",\"permissions_1_31\",2],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"yes\"]]}"
        },
        "systemtags": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "tasks": {
            "types": "",
            "enabled": "yes",
            "installed_version": "0.13.3"
        },
        "text": {
            "enabled": "yes",
            "types": "dav",
            "installed_version": "2.0.0"
        },
        "theming": {
            "types": "logging",
            "installed_version": "1.7.0",
            "enabled": "no",
            "cachebuster": "14"
        },
        "twofactor_backupcodes": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.7.0"
        },
        "updatenotification": {
            "types": "",
            "enabled": "yes",
            "groupfolders": "1.2.2",
            "files_markdown": "2.2.0",
            "bookmarks": "3.3.3",
            "checksum": "0.4.5",
            "installed_version": "1.8.0",
            "spreed": "3.2.4",
            "core": "18.0.7.1",
            "contacts": "3.1.9",
            "maps": "0.1.3",
            "update_check_errors": "0",
            "tasks": "0.11.2",
            "camerarawpreviews": "0.7.8",
            "bruteforcesettings": "1.4.0",
            "music": "0.16.0",
            "mail": "1.0.0",
            "gpxpod": "4.2.1",
            "files_readmemd": "1.1.3",
            "files_rightclick": "0.15.1",
            "notes": "3.6.1",
            "gpxedit": "0.0.12",
            "gpxmotion": "0.0.10",
            "socialsharing_facebook": "1.0.5",
            "socialsharing_twitter": "1.0.5",
            "apporder": "0.10.0",
            "calendar": "2.0.0",
            "cookbook": "0.7.1",
            "metadata": "0.12.0"
        },
        "user_usage_report": {
            "types": "filesystem",
            "enabled": "no",
            "installed_version": "1.2.3"
        },
        "viewer": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "workflowengine": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "2.0.0"
        }
    }
}

 - Nextcloud external user backend: none

**Additional context**

**Comment by marcelklehr** [comment]
Thanks for reporting! This should be fixed in v3.3.4 now
