### ISSUE TITLE
Save button not visible in grid view when renaming bookmark

### ISSUE THREAD

**Issue by reimer-atb** [nextcloud/bookmarks#1168]
**Describe the bug**
I keep my bookmarks in grid view, not as a list. When I try to rename a bookmark from the `...` button of any bookmark, I can edit the URL of the bookmark, but the `Save` button is not visible.

I can hit `Enter` to save or hit `Tab` to move focus to the `Save` button and renaming the bookmark succeeds.

However, this is not immediately clear for new users - it wasn't for me, anyway.
It would be better if the `Save` button would be shown where the `...` button was before.

**To Reproduce**
1. Go to bookmarks app
2. Switch to grid view
3. Click `...` button for any one bookmark
4. Click `Rename`
5. Input field for changing the name appears, but `Save` button is not visible

**Expected behavior**
The `Save` button should appear where the `...` button was.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/5737222/90574462-47eaf000-e1b9-11ea-9950-38f924597b4e.png)

**Desktop (please complete the following information):**
 - OS: MacOS X
 - Browser: Firefox
 - Version: 79.0

**Server (please complete the following information):**
 - OS: not sure, it's a hosted instance
 - HTTP server: Apache
 - Database: MySQL 5.7.30
 - PHP version: v7.3.19
 - Nextcloud version: 18.0.7
 - Bookmarks app version: 3.3.4
 - Activated Nextcloud Apps: 
 - Nextcloud configuration: 
 - Nextcloud external user backend:

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
Fixed.
