### ISSUE TITLE
Add a way to cancel renaming a bookmark

### ISSUE THREAD

**Issue by reimer-atb** [nextcloud/bookmarks#1169]
**Is your feature request related to a problem? Please describe.**
1. Click `...` button for any bookmark
2. Click `Rename`
3. Change bookmark name

If I do that but then change my mind and decide that I do not want to change the name, there is no obvious way to `cancel` the renaming.
There is no explicit `Cancel` button. Hitting `Escape` also has no effect.

I have to switch to another page and back or reload the page to cancel the renaming.

**Describe the solution you'd like**
Provide a `Cancel` button next to the `Save` button, which hides the input field again and displays the original name again. 

An additional button would probably only be feasible in list view, not in grid view.
So pressing the `Escape` key should have the same effect as described above. 

**Describe alternatives you've considered**

**Additional context**

**Comment by marcelklehr** [comment]
Fixed.
