### ISSUE TITLE
"All Bookmarks" menu link should show all bookmarks

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/bookmarks#1171]
**Describe the bug**
Currently in the bookmarks menu (Left blade) there's a link to show "All Bookmarks". However, this will only show bookmarks within the root folder but *not* the bookmarks of folders. 

**To Reproduce**
1. With bookmarks in a sub folder.... Open the bookmark app
2. Click on "All Bookmarks" 
3. Only bookmarks from the root folder are shown. Bookmarks in folders are not shown
 

**Expected behavior**
I would expect that when I select "All Bookmarks", all bookmarks would be shown. Only bookmarks in the root folder are shown. 

As far as I can tell, there is no way to see all of the bookmarks if using the folders. 
This would be very useful in environments where you share certain bookmarks with certain team but you (as the bookmarks owner) need to have an overview of all of the bookmarks on one page. 

It does seem that "Recent Bookmarks" do ignore the folders and will show their content regardless of where they are.

**Comment by marcelklehr** [comment]
Hello @aproposnix 
This is by design. I may not entirely understand your usecase, but if you have folders the assumption is that you want to use the folder structure you have created for finding your bookmarks rather than expecting to be dumped a list of everything you have. If you need that, there's the recent bookmarks view. Am I missing something?

**Comment by aproposnix** [comment]
Your scenario is perfect if someone shared a set of bookmarks with me (that way when I look at "all" bookmarks, I actually see just all of *my* bookmarks.  However, the issue is if you use the folders so that you can *share* different bookmark sets (i.e. a folder) with different teams, then you are no  longer able to see all of your bookmarks on one page. So because I'm sharing, I can no longer see all of my bookmarks in one place. 

Maybe make this a flag? 
☑Include folders in all view

**Comment by marcelklehr** [comment]
mmh. I guess this could be done in unison with #1161 so that there's a filter for shared bookmarks and one for 'my bookmarks'.

**Comment by marcelklehr** [comment]
After discussion with the design team, we decided not to implement this to be as close to the files app as possible.

**Comment by aproposnix** [comment]
@marcelklehr In that case, why not add a "copy to" folder function? This would be useful in the event that the user needs to share with multiple users in different folders. That would be aligned to the files app.

**Comment by marcelklehr** [comment]
@aproposnix That's a good idea! Can you open a new issue for this?
