### ISSUE TITLE
Adding a new bookmark via "New Bookmark" button does not show the new bookmark in the list of bookmarks

### ISSUE THREAD

**Issue by reimer-atb** [nextcloud/bookmarks#1172]
**Describe the bug**

**To Reproduce**
1. Go to Bookmarks
2. Sort bookmarks by 'recently added'
3. Click on 'New Bookmark' button (top left)
4. Enter a URL
5. Click 'Save' button
6. Details panel opens on the right-hand side and shows the just added bookmark's data. But the bookmark itself disappears from the list of bookmarks.

One has to reload the bookmarks page to have the new bookmark appear in the list.

**Expected behavior**
The added bookmark should appear at the top of the bookmarks list.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux, MacOS X
 - Browser Firefox
 - Version 79.0

**Server (please complete the following information):**
 - OS: not sure, it's a hosted instance
 - HTTP server: Apache
 - Database MySQL 5.7.30
 - PHP version: v7.3.19
 - Nextcloud version: 18.0.7
 - Bookmarks app version: 3.3.4
 - Activated Nextcloud Apps: 
 - Nextcloud configuration: 
 - Nextcloud external user backend: 

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by j-ed** [comment]
So I think your headline is wrong, because the new bookmark is definitely been added to the list of bookmarks but the bookmark view (recently added) is not updated accordingly, right?

**Comment by philipreimer** [comment]
@j-ed you are right. Changed the title. Hope it's clearer now.

**Comment by marcelklehr** [comment]
@philipreimer Thank you so much for reporting these issues. Invaluable feedback! :heart:
