### ISSUE TITLE
Current navigation / tag selection is confusing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/bookmarks#118]
Normal ownCloud apps have a sidebar with items to filter the content, and these stay static (Contact groups, Files filters, News folders etc). Bookmarks has the confusing behavior that when you click on a tag, it vanishes from the list.

Now I know this is to have the advanced ability to drill down in the list to see bookmarks with 2 specific tags. But this makes the most basic navigation through the app very difficult. When you only have one tag, there’s not even a way to go back to the normal list when you clicked that one tag.

I propose changing it to the normal sidebar style of all the tags showing _always_. When you click on a tag, only items with that tag are shown, and the tag is marked as active in the sidebar. When you click on another tag – that tag is selected _instead_. Then we can also cut the »Filterable tags« text.

That’s for the basic functionality. In the future we could think of a modifier like pressing `Ctrl` to be able to multiselect tags. But for now we need to focus on the basic experience.

cc @TtuxX @ganomi @wakeup @owncloud/designers

**Comment by jbtbnl** [comment]
I agree with the proposal of @jancborchardt. To address the concerns of @ganomi, I believe it's better for a second clicked tag to be appended to the filter. Clicking a tag for a second time can deselect it. This will avoid `Ctrl + click` stuff that will not work on mobile devices.

**Comment by jancborchardt** [comment]
The thing though is that the majority use case is probably switching to another tag, over drilling down.

And the simplest action, the click on another tag, should perform what the majority expects. Especially since most other ownCloud apps (as mentioned above), drilling down should not be the priority mode of browsing that we design for here.

**Comment by tylkofarci** [comment]
@ganomi 
>but you can easily go back if you click on a selected tag in the "selected tags" area?
what "selected tags area"?

**Comment by shtrom** [comment]
I have the same issue as @jancborchardt: I have no selecting tags area, nor search input. Here what I see after selecting a tag (Linux, in this case); there is no apparent way to unselect that tag.

![bookmarks](https://cloud.githubusercontent.com/assets/160280/8824368/5745d892-30b8-11e5-8b01-35fa380e49e7.png)

**Comment by jancborchardt** [comment]
@blizzz regarding our recent discussion in https://github.com/owncloud/bookmarks/issues/168#issuecomment-121723803 (basically that one is a duplicate of this here)

**Comment by marcelklehr** [comment]
Closing this in favour of #168 unless anyone disagrees :)
