### ISSUE TITLE
Sort by URL/Domain

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#1183]

**Comment by Abhishek-1337** [comment]
Hey @marcelklehr , I have been trying to contribute on some beginner friendly issues ,curious about the whole OS project community.
Is this a project I can help with, I will put 100% of my efforts to contribute to any little issues.

**Comment by marcelklehr** [comment]
Hello @Abhishek-1337 :wave: 
Thank you for commenting. I'm glad you are reaching out! This is definitely a project you can help with. We welcome any and all contributions!
Since this issue involves a bit more work and knowledge after all (probably should be 'good second issue' :P), I'd recommend starting off with #1698, which should be a nice way to get to know the code base.
If you like we can also talk synchronously via gitter, for any questions you may have: https://gitter.im/nextcloud-bookmarks/community

**Comment by Abhishek-1337** [comment]
@marcelklehr 
Thanks for your kind response, I will definitely look into it.
Yes ,I have a lot of questions as I am just beginning my open source journey but I will not cause you any trouble unless it is something that I am not able to understand. I am improving my googling skills too:P.
