### ISSUE TITLE
Details menu must be closed before each bookmark added in webui when adding descriptions.

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1184]
**Describe the bug**
Details must be manually closed after each bookmark is added in the webui, otherwise descriptions will appear on additional bookmarks added.

**To Reproduce**
- *Add Bookmark* in webui.
- Add a description.
- repeat.  Now you'll still see your earlier description applied to the next bookmark.

**Screenshots**
1st Bookmark
![Screenshot_20200827_074444](https://user-images.githubusercontent.com/1787238/91457775-9b081700-e839-11ea-8557-02733072ed42.png)
2nd Bookmark
![Screenshot_20200827_074513](https://user-images.githubusercontent.com/1787238/91457829-ab1ff680-e839-11ea-90e6-6aa255d14e49.png)

**Desktop (please complete the following information):**
 - OS: MacOS, Manjaro ARM
 - Browser Firefox Stable

**Comment by marcelklehr** [comment]
Mmmh, which version is this? I think I fixed this recently.

**Comment by RomainTT** [comment]
> Mmmh, which version is this? I think I fixed this recently.

Hi, I have version 3.3.4 and I have this issue.
