### ISSUE TITLE
The “Add” menu overlaps the input text box.

### ISSUE THREAD

**Issue by RomainTT** [nextcloud/bookmarks#1188]
**Describe the bug**

When adding a new directory or bookmark using the drop-down menu of the head bar, the menu does not disappear and is over the text box. It is an issue as it masks the user input while he is typing.

**To Reproduce**
1. Go to any bookmark directory
2. Select ’List view’ to view bookmarks as a list
3. Click on '· · ·', the menu button on the head bar, next to the directory tree.
4. Click on ’New bookmark’
5. The menu does not disappear while the new bookmark appears.

**Expected behavior**
The menu must disappear as the new bookmark/directory appears.

**Screenshots**
![image](https://user-images.githubusercontent.com/12847715/92242974-efa63480-eec0-11ea-974f-c86a68e165fb.png)

On my screenshot the menu is transparent I don’t know why. But in use it is actually opaque.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 85.0.4183.83

**Server (please complete the following information):**
 - OS: Raspbian Buster
 - HTTP server: Apache
 - Database MySQL 10.3.22
 - PHP version: 7.4.9
 - Nextcloud version: 19.0.1
 - Bookmarks app version: 3.3.4

**Comment by marcelklehr** [comment]
Thanks for your feedback. This is fixed in v3.4.0-beta.1. You can install the beta version by setting your installation release setting from 'stable'/'production' to daily.
