### ISSUE TITLE
v3.4.0-beta.1

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#1189]
see https://help.nextcloud.com/t/bookmarks-v3-4-0-beta-1/90751

**Comment by sunjam** [comment]
Any documentation for testing Flow integration?

Check under Personal / Flow, app settings and Administration / Bookmarks settings.  Unsure of how to test on 20.0.0-beta3.  Thanks.

**Comment by marcelklehr** [comment]
You should be able to set up a new flow in Personal/Flow :thinking:

**Comment by sunjam** [comment]
Bookmarks Flow integration is very clearly available within Flow Settings
as of 19.0.3 and Bookmarks 3.4.1. :)
