### ISSUE TITLE
[Papercut] Delete All Bookmarks

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1199]
Testing #1189 

I click *Settings / Delete all bookmarks*.  The notice that pops up is visible outside the edge of the Firefox 64-bit browser window, even on a massive monitor.  No confirmation box appears.
![image](https://user-images.githubusercontent.com/1787238/92308242-48251280-ef51-11ea-9d81-556026fb920c.png)
I click *Delete all bookmarks* a second time.  Now the confirm box appears.

My suggestion is for this confirmation box to appear the first time the user clicks *Delete all bookmarks*
![image](https://user-images.githubusercontent.com/1787238/92308352-d0a3b300-ef51-11ea-8fc4-1a8f79db7cb6.png)

**Comment by marcelklehr** [comment]
I cannot replicate this. For me the alert comes on the first click.
