### ISSUE TITLE
Microsft Edge

### ISSUE THREAD

**Issue by barnycloud** [nextcloud/bookmarks#1204]
In the documentation I read about installing the floccus app in Chrome and Firefox. What about floccus in the Chromium-based browser Edge? Is there any documentation for it?

**Comment by marcelklehr** [comment]
floccus is also available for Microsoft Edge: https://microsoftedge.microsoft.com/addons/detail/floccus-bookmarks-sync/gjkddcofhiifldbllobcamllmanombji :)

**Comment by barnycloud** [comment]
I've read your guidelines on Chrome and Firefox. In Edge, what is the equivalent of (in German) "Weitere Lesezeichen" and "Lesezeichenleiste" in Chrome?

**Comment by marcelklehr** [comment]
Edge should be similar to Chrome, I think. But I cannot test on Edge. The Guide doesn't really depend on the browser, though. Still, when you find out, feel free to let me know, so I can update the guide.
