### ISSUE TITLE
Context menu does not close after clicking on "Details"

### ISSUE THREAD

**Issue by reimer-atb** [nextcloud/bookmarks#1205]
**Describe the bug**
The context menu does not close after clicking on "Details" and "Details" window has been openend.

**To Reproduce**
1. Go to Bookmarks
2. Click on `...` for any bookmark to open the context menu
3. Click on `Details` to open the "Details" window for the bookmark
4. "Details" window is opened but context menu stays visible

**Expected behavior**
Context menu should be closed after clicking on "Details"

**Screenshots**
![context-menu](https://user-images.githubusercontent.com/5737222/92328416-d76d1b80-f060-11ea-8159-cd5cbcc222c8.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux Gnome Edition
 - Browser: Firefox
 - Version: 79.0

**Server (please complete the following information):**
 - OS: Linux 4.4.0-148-generic x86_64
 - HTTP server: Apache
 - Database: MySQL 5.7.30
 - PHP version: 7.3.19
 - Nextcloud version: 19.0.2
 - Bookmarks app version: 3.3.4
 - Activated Nextcloud Apps: 
 - Nextcloud configuration: 
 - Nextcloud external user backend: none

**Additional context**
Also happens when clicking "Move" ("Verschieben")

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
This has been fixed already (see latest master/beta.1)
