### ISSUE TITLE
Details window hides context menu entries

### ISSUE THREAD

**Issue by reimer-atb** [nextcloud/bookmarks#1206]
**Describe the bug**
When the details window is open it hides part of the context menu.

**To Reproduce**
1. Go to Bookmarks
2. Click on ... for any bookmark to open the context menu
3. Click on `Details` to open the "Details" window for the bookmark
4. Click on `...` for another bookmark to open the context menu again
5. Right part of the context menu is hidden "below" the "Details" window. Context menu entries cannot be read fully.

**Expected behavior**
The context menu should be completely visible and readable

**Screenshots**
![context-menu-hidden](https://user-images.githubusercontent.com/5737222/92328678-c1f8f100-f062-11ea-939d-34f460b89430.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux Gnome Edition
 - Browser: Firefox
 - Version: 79.0

**Server (please complete the following information):**
 - OS: Linux 4.4.0-148-generic x86_64
 - HTTP server: Apache
 - Database: MySQL 5.7.30
 - PHP version: 7.3.19
 - Nextcloud version: 19.0.2
 - Bookmarks app version: 3.3.4
 - Activated Nextcloud Apps: 
 - Nextcloud configuration: 
 - Nextcloud external user backend: none

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
This is fixed in the latest version.
