### ISSUE TITLE
Where are bookmarks stored in Nextcloud?

### ISSUE THREAD

**Issue by nibl** [nextcloud/bookmarks#1219]
Can someone explain where and how bookmark data is stored inside  nextcloud?

I created a bookmarks folder using nextbookmarks, but I can’t see that or anything else that looks like the data I expect.

**Comment by marcelklehr** [comment]
Bookmarks are stored in the bookmarks app.

![image](https://user-images.githubusercontent.com/986878/94042112-7157f680-fdcb-11ea-960b-1c268dcfdb18.png)
