### ISSUE TITLE
Connection failed on smartphone

### ISSUE THREAD

**Issue by brandy000** [nextcloud/bookmarks#1220]
I´m using Bookmarks 2.3.4 on my Nextcloud.
On my smartphone (Fairphone 3 | /e/ based on Linage OS) I want to connect to the server, but the Bookmark app always says, that the connection failed. I use the same account with the Nextccloud app, the Nextcloud Deck app and Nextcloud SMS app. These three are working well, only the Bookmark app doesn´t work.
What´s wrong here?

**Comment by marcelklehr** [comment]
The latest version of the android app seems to be incompatible with nextcloud bookmarks v2.x, but only supports v3.x.
Theoretically it shouldn't be that hard to support v2.x as well, but it's unclear what exactly is the show stopper. Do you see any error logs in the nextcloud logs?

**Comment by brandy000** [comment]
No, I don't see anything in the logs.
When I want to log in manually, I get three possible errors:

- no internet connection
- URL isn't correct
- the selfsigned certificate wasn't imported

I'm connected to the internet, other Nextcloud-apps work and my SSL is up-to-date.

Am 24. September 2020 10:45:20 MESZ schrieb Marcel Klehr <notifications@github.com>:
>The latest version of the android app seems to be incompatible with
>nextcloud bookmarks v2.x, but only supports v3.x.
>Theoretically it shouldn't be that hard to support v2.x as well, but
>it's unclear what exactly is the show stopper. Do you see any error
>logs in the nextcloud logs?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/bookmarks/issues/1220#issuecomment-698207079

-- Gesendte von /e/ Mail.

**Comment by marcelklehr** [comment]
Please get in touch at the repo of the android app over here: https://gitlab.com/bisada/OCBookmarks
