### ISSUE TITLE
PHP Fatal error running occ

### ISSUE THREAD

**Issue by PeterRob** [nextcloud/bookmarks#1223]
Attempt to delete an external storage by cli: sudo -u www-data php /var/www/nextcloud/occ files_external:delete -- 11

PHP Fatal error:  Declaration of Symphony\Component\Console\Input\ArrayInput::hasParameterOption($values, bool $onlyParams = false) must be compatible with Symfony\Component\Console\Input\InputInterface::hasParameterOption($values, $onlyParams = false) in /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Input/ArrayInput.php on line 56

**To Reproduce**
External_storages & Bookmarks apps installed
Run the shell command above

**Expected behavior**
Command completes without error 

**Server (please complete the following information):**
 - Ubuntu 20.04
 - Caddy v2.2
 - Database: Mariadb
 - PHP version: v7.4
 - Nextcloud version: 20.0.0 RC2
 - Bookmarks app version: 3.3.4
 - Activated Nextcloud Apps:
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - admin_audit: 1.10.0
  - appointments: 1.7.6
  - apporder: 0.11.0
  - bookmarks 3.3.4
  - calendar: 2.1.2
  - camerarawpreviews: 0.7.8
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.3.0
  - contactsinteraction: 1.1.0
  - cookbook: 0.7.6
  - dav: 1.16.0
  - end_to_end_encryption: 1.6.2
  - external: 3.7.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - music: 0.16.1-alpha1
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - social: 0.3.1
  - support: 1.3.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_admin: 3.0.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.0.0
  - twofactor_totp: 5.0.0
  - unsplash: 1.1.6
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0

**Comment by marcelklehr** [comment]
This should be fixed in v3.4.0
