### ISSUE TITLE
Error: Undefined class constant 'CACHE_TTL'

### ISSUE THREAD

**Issue by tacruc** [nextcloud/bookmarks#1225]
First of all thanks for your great app. 

**Describe the bug**
I get this error message in the nextcloud log

**To Reproduce**
run cron.php

**Server (please complete the following information):**
 - OS: openSuse
 - Database: MySQL
 - PHP version: v7.2
 - Nextcloud version: 19.0.3
 - Bookmarks app version: 3.4.0

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
[core] Error: Error: Undefined class constant 'CACHE_TTL' at <<closure>>

0. /srv/www/nextcloud/lib/private/BackgroundJob/Job.php line 62
   OCA\Bookmarks\BackgroundJobs\PreviewsJob->run(null)
1. /srv/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 57
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
2. /srv/www/nextcloud/cron.php line 126
   OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-09-30T11:45:01+02:00
```

**Comment by marcelklehr** [comment]
Did you install the app manually? PreviewsJob shouldn't exist anymore.

**Comment by omocinteractive** [comment]
... same here after update: {"reqId":"eUpIYsziPMSC2MjilR9E","level":3,"time":"September 30, 2020 11:45:02","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"Error","Message":"Undefined class constant 'CACHE_TTL'","Code":0,"Trace":[{"file":"/httpdocs/lib/private/BackgroundJob/Job.php","line":62,"function":"run","class":"OCA\\Bookmarks\\BackgroundJobs\\PreviewsJob","type":"->","args":[null]},{"file":"/httpdocs/lib/private/BackgroundJob/TimedJob.php","line":57,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/httpdocs/cron.php","line":126,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/httpdocs/apps/bookmarks/lib/BackgroundJobs/PreviewsJo
 b.php","Line":49,"CustomMessage":"Error while running background job (class: OCA\\Bookmarks\\BackgroundJobs\\PreviewsJob, arguments: )"},"userAgent":"--","version":"19.0.3.1"}

**Comment by marcelklehr** [comment]
Also, v17 is not supported by Bookmarks v3.4.0 (and won't get any more updates starting at the end of this week), so you should probably update to v18.

**Comment by omocinteractive** [comment]
... see above: "19.0.3.1"

**Comment by marcelklehr** [comment]
@omocinteractive How did you install? Remove Bookmarks\BackgroundJobs\PreviewsJob.php to fix this.

**Comment by omocinteractive** [comment]
@marcelklehr: it happend after an update ...
btw. the correct path is /httpdocs/apps/bookmarks/lib/BackgroundJobs/PreviewsJob.php

**Comment by AxorPL** [comment]
I keep getting the same error after updating to 3.4.0 through App Store.

- OS: CentOS 7.8.2003
- Database: MariaDB 10.4.14
- PHP version: 7.4.11
- Nextcloud version: 19.0.3
- Bookmarks app version: 3.4.0

```
Error: Undefined class constant 'CACHE_TTL'

/var/www/natsuki.mst.blue/lib/private/BackgroundJob/Job.php - line 62:
OCA\Bookmarks\BackgroundJobs\PreviewsJob->run()

/var/www/natsuki.mst.blue/lib/private/BackgroundJob/TimedJob.php - line 57:
OC\BackgroundJob\Job->execute()

/var/www/natsuki.mst.blue/cron.php - line 126:
OC\BackgroundJob\TimedJob->execute()
```

**Comment by tacruc** [comment]
> Did you install the app manually? PreviewsJob shouldn't exist anymore. Simply extracting the tar archive over the old installation is not recommended.

No, I updated via the app store.

**Comment by omocinteractive** [comment]
... see the fix above (as with all nextcloud problems, only possible via ssh).

**Comment by tacruc** [comment]
> Also, v17 is not supported by Bookmarks v3.4.0 (and won't get any more updates starting at the end of this week), so you should probably update to v18.

Sorry, typo, running the lasted nextcloud server 19.0.3

**Comment by marcelklehr** [comment]
I think I know what's happening. I'll do a release shortly.

**Comment by marcelklehr** [comment]
Fixed in https://github.com/nextcloud/bookmarks/releases/tag/v3.4.1
