### ISSUE TITLE
Cannot move beyond 7 displayed folders in Icon view

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1234]
Nextcloud 19.0.3 with Bookmarks 3.4.1 stable

![image](https://user-images.githubusercontent.com/1787238/94994589-62044600-054d-11eb-95d8-094389a2ed6b.png)
![image](https://user-images.githubusercontent.com/1787238/94994569-4305b400-054d-11eb-87c7-da3aec77d1ec.png)
There are more folders, but they are not selectable with the scroll wheel or similar in the webui when moving a selection.  Selection can only be moved to one of the seven folders displayed.  Changing to list view adds a scrolling option.

**Comment by marcelklehr** [comment]
Thanks for your diligent bug reports! Keep 'em coming! :heart: 

I'm having trouble reproducing this, though. Scrolling the model with folders to move into works in grid view as well as in list view.

**Comment by sunjam** [comment]
Hmm, I can no longer reproduce this error.  Scrolling folders is working when moving bookmarks in Grid View.
