### ISSUE TITLE
3.4.1 Feedback

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1235]
Nextcloud 19.0.3 with Bookmarks 3.4.1 feedback on Firefox 81.0 (64-bit)

Imported bookmarks via html.  Once successfully added there is no visual feedback until the tab is manually reloaded.
![image](https://user-images.githubusercontent.com/1787238/94996851-dfcf4e00-055b-11eb-947c-2b098f9ada8f.png)
This is what you see before and after import.

All books are imported within a single unnamed folder rather than directly to the root directory. #1238 
![image](https://user-images.githubusercontent.com/1787238/94996860-f5dd0e80-055b-11eb-91ce-9f62f17b8716.png)

Moving selections of bookmarks (1,300 bookmarks takes several minutes and will seize up the Firefox browser), but Nextcloud stays around 20% cpu usage on a simple Odroid device. #1239
![image](https://user-images.githubusercontent.com/1787238/94995136-18b5f580-0551-11eb-8696-44f6afdbe607.png)

Is there any way to see the numbers of bookmarks within a folder?  I'm finding this out by Selecting a bookmark then *Select All*.  This process (and *Cancel Selection*) are very intensive on the browser session and will trigger the wait / stop notice above in Firefox.

Importing a bookmark will add a duplicate of this particular `floccus` tag. #1237
![image](https://user-images.githubusercontent.com/1787238/94995381-cd044b80-0552-11eb-906c-2067d0b770a6.png)

**Comment by marcelklehr** [comment]
> Is there any way to see the numbers of bookmarks within a folder? I'm finding this out by Selecting a bookmark then Select All. This process (and Cancel Selection) are very intensive on the browser session and will trigger the wait / stop notice above in Firefox.

The details sidebar of each folder has a count on how many bookmarks it contains.
