### ISSUE TITLE
Importing a bookmark adds duplicate Floccus directory tags

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1237]
NextcloudPi 19.0.3 with Bookmarks 3.4.1

Importing a bookmark will add a duplicate of this particular `floccus` directory tag #1235.
![image](https://user-images.githubusercontent.com/1787238/94995381-cd044b80-0552-11eb-906c-2067d0b770a6.png)

edit: I'm assuming this is from using import, but perhaps it is something else

**Comment by sunjam** [comment]
Log Warning sent

**Comment by marcelklehr** [comment]
duplicate of #1241
