### ISSUE TITLE
[Feature Request] Select where to import bookmarks and directories

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1238]
Current import of bookmarks 3.4.1 is within an unnamed directory created during import.
![image](https://user-images.githubusercontent.com/1787238/94996860-f5dd0e80-055b-11eb-91ce-9f62f17b8716.png)

**Describe the solution you'd like**
To be able to select where the bookmarks and folders I'm importing will end up.

**Describe alternatives you've considered**
- Import html file.
- Manually move folders and bookmarks to my root directory
- Delete the unnamed folder created during import.

Manual selection process is very browser intensive and takes a long time, as opposed to only a few seconds for the import. #1239

**Comment by marcelklehr** [comment]
>  created during import

This is a wrong assumption. The unnamed folder stems from a bug in the export functionality in v3.3.x. If you you import a file exported in v3.3.x you get an empty folder. If you import from a file exported from e.g. firefox, you don't.

**Comment by sunjam** [comment]
Nice, glad it is fixed.  Since this is as good a location as any to ask:

Is there a best practice for properly migrating over the ol' bookmarks, be it within the webui or a browser or through floccus extension.  Trying to figure how to move over bookmarks I've been keeping for years (folders, tags, descriptions designed in the Bookmarks app) so everything will run peachy keen moving forward.

**Comment by marcelklehr** [comment]
If you have been syncing with floccus, you should have your bookmarks in your browser, too. Since you still seem to be using floccus' legacy sync (using tags), I would recommend the guide over here: https://github.com/marcelklehr/floccus/#switching-from-tag-based-to-folder-based-syncing
