### ISSUE TITLE
Webui becomes non-responsive when "Select All" with over 1,000 bookmarks

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1239]
NextcloudPi 19.0.3 with Bookmarks 3.4.1

**Describe the bug**
1. Select a bookmark.
2. *Select All* 
3. Browser will hang for over a minute on Firefox 81 (64-bit) on an i5 with 8gb of ram.
![image](https://user-images.githubusercontent.com/1787238/94995136-18b5f580-0551-11eb-8696-44f6afdbe607.png)
4. 1,342 bookmarks selected.
![image](https://user-images.githubusercontent.com/1787238/94999311-5c1e5d00-056d-11eb-8dd3-aacf6611445c.png)

**Comment by marcelklehr** [comment]
Moving selections should become faster now. However, selecting a large amount of bookmarks is still slow.

**Comment by sunjam** [comment]
Confirmed, it is faster to select in `3.4.4`  Still got browser timeout when selecting 980 bookmarks, but process was much faster at about 15 seconds to select all from Firefox 81 64-bit with 8gb ram and i5 processor. :+1:

**Comment by radoeka** [comment]
Is there a warning when so many bookmarks are copied.  At a maximum of 500 hundred or so, to prevent issues when copying.
Add an overwrite to warning, so the user can neglect the maximum limit.

**Comment by marcelklehr** [comment]
There is currently no warning. Copying 500 items should work quite well, as it only copies 10 items at max in parallel.

The problem is likely not the network or the backend, but the render process of the browser which currently renders all 980 bookmarks.

Note to self: A virtual list may be the way to go here (https://github.com/Mikescops/vue-virtual-grid seems useful)

**Comment by sunjam** [comment]
Copying 500 items is no issue for me at all.  Also, performance has notably increased in general since this post was originally created.  Just tested in 20.0.8 stable from a low spec Odroid C2:

Selecting 1,600 bookmarks from current Firefox stable took 19 seconds and gave a "stop or wait" warning before completing.  Big improvement!!!

**Comment by marcelklehr** [comment]
I've now implemented virtual scrolling which should finally fix this.
