### ISSUE TITLE
papercut: tooltip has text: "cancel" 

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/bookmarks#1240]
**Describe the bug**
When adding a link, the tooltip has an unexpected text ("cancel")

**To Reproduce**
1. Add a new link
2. Move mouse over the check-mark-icon
3. See text of tooltip

**Expected behavior**
Tooltip should be something like "ok", "save", ,,, 

**Screenshots**
![b1](https://user-images.githubusercontent.com/34692335/95016498-a24dec00-0653-11eb-82d1-32e5f3b15d2d.png)

Perhaps:
https://github.com/nextcloud/bookmarks/blob/72ac14b38bcb8d6d01c90e391974e9b5c4d107f5/src/components/Item.vue#L51

**Comment by marcelklehr** [comment]
Ah, you're right! thanks for the feedback. :)
