### ISSUE TITLE
Search does not include bookmarks any more in NC 20.0

### ISSUE THREAD

**Issue by tgressly** [nextcloud/bookmarks#1243]
**Search does not include bookmarks any more in NC 20.0**

When in the bookmarks tab the search no longer shows results from bookmarks in Nextcloud version 20.0.

**To Reproduce**
1. Go to 'Bookmarks tab'
2. Click on 'Search'
3. Type a search term of any bookmark
4. See results from 'Files' and 'Events', but no longer from 'Bookmarks'

**Expected behavior**
Results from 'Bookmarks' should be shown.

**Desktop**
 - OS: MacOS X
 - Browser: Firefox
 - Version: 81.0.1

**Server**
 - OS: Ubuntu 18.04.5 LTS
 - Docker image: nextcloud:20.0.0
 - Database: mariadb:10.3.11
 - PHP version: [e.g. v7.2]
 - Nextcloud version: 20.0.0
 - Bookmarks app version: 3.4.3
 - Activated Nextcloud Apps: accessibility: 1.6.0, activity: 2.13.1, apporder: 0.11.0, bookmarks: 3.4.3, calendar: 2.1.2, cloud_federation_api: 1.3.0, comments: 1.10.0, contacts: 3.4.0, contactsinteraction: 1.1.0, dashboard: 7.0.0, dav: 1.16.0, deck: 1.1.0, federatedfilesharing: 1.10.1, federation: 1.10.1, files: 1.15.0, files_markdown: 2.3.1, files_pdfviewer: 2.0.1, files_rightclick: 0.17.0, files_sharing: 1.12.0, files_trashbin: 1.10.1, files_versions: 1.13.0, files_videoplayer: 1.9.0, firstrunwizard: 2.9.0, logreader: 2.5.0, lookup_server_connector: 1.8.0, nextcloud_announcements: 1.9.0, notes: 4.0.0, notifications: 2.8.0, oauth2: 1.8.0, password_policy: 1.10.1, photos: 1.2.0, polls: 1.5.4, privacy: 1.4.0, provisioning_api: 1.10.0, qownnotesapi: 20.9.0, recommendations: 0.8.0, richdocuments: 3.7.4, serverinfo: 1.10.0, settings: 1.2.0, sharebymail: 1.10.0, support: 1.3.0, survey_client: 1.8.0, systemtags: 1.10.0, tasks: 0.13.3, text: 3.1.0, theming: 1.11.0, twofactor_admin: 3.0.0, twofactor_backupcodes: 1.9.0, twofactor_nextcloud_notification: 3.0.0, twofactor_totp: 5.0.0, updatenotification: 1.10.0, user_status: 1.0.0, viewer: 1.4.0, weather_status: 1.0.0, workflowengine: 2.2.0
 - Nextcloud configuration:
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.reconnect.gmbh\/",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "20.0.0.9",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "ojsxc",
            "mindmap_app"
        ]
    }
}
```
 - Nextcloud external user backend: none

**Comment by marcelklehr** [comment]
v4.x is released :)
