### ISSUE TITLE
Recent bookmarks are not deleted when deleting all bookmarks

### ISSUE THREAD

**Issue by gibelium** [nextcloud/bookmarks#1251]
**Describe the bug**
After deleting all bookmarks the recent bookmarks are still there. I guess the counter is not zero because of that. In addtion I see the error message 'Failed to load children order'.

This is a follow up to #1107

**To Reproduce**
1. Sync bookmarks via floccus
2. Delete all bookmarks

**Expected behavior**
Deleting all bookmarks should reset the counter and result in no recent bookmarks

**Screenshots**
<img width="1061" alt="1107_message after delete All" src="https://user-images.githubusercontent.com/728680/95656582-a5435380-0b0f-11eb-83f7-1b68314033b2.png">
<img width="1054" alt="1107_recent bookmarks after delete all" src="https://user-images.githubusercontent.com/728680/95656586-a96f7100-0b0f-11eb-844e-149628cee2e2.png">

**Desktop (please complete the following information):**
 - OS: MacOS X
 - Browser: Chrome
 - Version: 85.0.4183.121

**Server (please complete the following information):**
 - Nextcloud version: 19.0.1
 - Bookmarks app version: 3.4.1

**Comment by marcelklehr** [comment]
Can you try updating to 3.4.3?

**Comment by gibelium** [comment]
Yes, I'll do as soon as possible...

**Comment by marcelklehr** [comment]
Ah, updating the app is still not working properly for you? :(
