### ISSUE TITLE
Screeenly website URL is wrong in the admin page of Bookmark app in the Hungarian translation

### ISSUE THREAD

**Issue by pongraczi** [nextcloud/bookmarks#1254]
### Steps to reproduce
* Go to the Admin page as administrator of the Bookmark app
* On the top there is an advice to visit a free screenshot provider, called Screeenly (with triple e)
* The visit url only contains double e, which leads to a digital signage website.

### Expected behaviour
The URL should be: screeenly.com

### Actual behaviour
At this moment the url is: screenly.com **in the Hungarian translation**.  
The English (US) is ok.

## Server configuration detail

**Nextcloud version:** 19.0.3 - 19.0.3.1

**Comment by pongraczi** [comment]
Ok, it seems a translation typo.

**Comment by marcelklehr** [comment]
Thanks for the feedback, do you mind, notifying the translators at https://help.nextcloud.com ?

**Comment by pongraczi** [comment]
Sure, [done.](https://help.nextcloud.com/t/screeenly-website-url-is-wrong-in-the-admin-page-of-bookmark-app-in-the-hungarian-translation/95707)

**Comment by rakekniven** [comment]
Found five occurences of wrong URL and fixed them all.
