### ISSUE TITLE
Failed to create bookmark

### ISSUE THREAD

**Issue by yodatak** [nextcloud/bookmarks#1255]
**Describe the bug**
I can no more create a bookmark for some user

**To Reproduce**
1. Go to 'favorites 
2. Add one  '...' and it say Failed to create bookmark

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Version: Latest

**Server (please complete the following information):**
 - OS: Debian 10
 - HTTP server: nginx/1.14.2
 - Database: PostgreSQL 13.0 (Debian 13.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
 - PHP version:  Version : 7.4.11 
 - Nextcloud version: 20
 - Bookmarks app version: 3.4.3
 - Activated Nextcloud Apps: 
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - bookmarks: 3.4.3
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - deck: 1.1.2
  - drawio: 0.9.7
  - external: 3.7.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.1.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.5.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.5
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.4
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - audioplayer
  - encryption
  - files_external
  - maps
  - spreed
  - support
  - user_ldap

 - Nextcloud configuration:
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
           "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.0.9",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "drawio",
            "calendar",
            "groupfolders",
            "external"
        ],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

 - Nextcloud external user backend: none

I fond no erreor in my log 

**Browser log**
```
Insert your browser log here, this could for example include:
TypeError: this.$refs.actions is undefined
    onClick https://cloud.X.org/apps/bookmarks/js/bookmarks-main.js?v=40b698aa-47:694
    Re https://cloud.X.org/apps/bookmarks/js/bookmarks-main.js?v=40b698aa-47:7
    n https://cloud.X.org/apps/bookmarks/js/bookmarks-main.js?v=40b698aa-47:7
    _wrapper https://cloud.X.org/apps/bookmarks/js/bookmarks-main.js?v=40b698aa-47:7
bookmarks-main.js:7:11622
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 4 globals.js:60:15
Erreur dans les liens source : Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL de la ressource : https://cloud.X.org/apps/bookmarks/js/bookmarks-main.js?v=40b698aa-47
URL du lien source : bookmarks-main.js.map?v=888b491bb94d96732298

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.

**Comment by marcelklehr** [comment]
Can you check the network tab in the browser inspector to find the failed web request?

**Comment by marcelklehr** [comment]
Closing to due lack of response.
