### ISSUE TITLE
Shared bookmarks hidden

### ISSUE THREAD

**Issue by simmstein** [nextcloud/bookmarks#1257]
**Describe the bug**
When a sub folder is shared, the content is not accessible with users.

**To Reproduce**

* user1 creates a folder
* user1 shares the folder with user2
* user1 creates a sub folder
* user1 adds bookmarks in the sub folder
* user2 can not list bookmarks of the sub folder
* user2 adds a bookmark in the sub folder
* user2 can not see his bookmark
* user1 can see the bookmark of user2

**Expected behavior**

user2 must see every bookmarks of the sub folder.

**Screenshots**

![](https://upload.deblan.org/u/2020-10/5f8af537.png)

![](https://upload.deblan.org/u/2020-10/5f8af541.png)

![](https://upload.deblan.org/u/2020-10/5f8af54c.png)

![](https://upload.deblan.org/u/2020-10/5f8af554.png)

![](https://upload.deblan.org/u/2020-10/5f8af55d.png)

**Desktop (please complete the following information):**

 - OS: Debian
 - Browser: Firefox
 - Version:  68 ESR

**Server (please complete the following information):**
 - OS: Debian
 - HTTP server: Apache2 / PHP (dev)
 - Database: MySQL / SQLite
 - PHP version: PHP 7.3 and PHP 7.4
 - Nextcloud version: 19 stable
 - Bookmarks app version: 3.4.3

**Comment by marcelklehr** [comment]
fixed in https://github.com/nextcloud/bookmarks/releases/tag/v3.4.4

**Comment by simmstein** [comment]
Thanks!
