### ISSUE TITLE
Bulk edit tags

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#1259]

**Comment by marcelklehr** [comment]
see https://github.com/nextcloud/nextcloud-vue/pull/1250

**Comment by hashashin1191** [comment]
I tried this nice feature, but the tag disappears before I add it when the pointer is hovered away .

https://user-images.githubusercontent.com/75371007/110214023-9eade200-7edd-11eb-9600-dc40dbe9da51.mp4

**Comment by marcelklehr** [comment]
Thanks for reporting, I've created an issue for this over here: https://github.com/nextcloud/nextcloud-vue/issues/1742

**Comment by marcelklehr** [comment]
I'm closing this as the feature itself has been implemented. The issue raised by @HouraisanNEET will be addressed in nextcloud/nextcloud-vue#1742
