### ISSUE TITLE
Warning for Bookmarks app in owncloud.log

### ISSUE THREAD

**Issue by StopTrain** [nextcloud/bookmarks#126]
"app":"PHP","message":"Undefined index: req_tag at \/srv\/www\/htdocs\/owncloud\/apps\/bookmarks\/templates\/main.php#40","level":3,"time":"2015-02-09T17:40:10+00:00"}

Not a show stopper, just something to be aware of!

**Comment by aristorias** [comment]
I get this error for line 40 and 44 in main.php
Undefined index: req_tag at /usr/share/webapps/owncloud/apps/bookmarks/templates/main.php#44

I even tried it with a clean and fresh mysql databse but i am not able to add any bookmarks :(

**Comment by TtuxX** [comment]
Hello @aristorias, I have  https://github.com/owncloud/bookmarks/pull/114 for your last interrogation ;) I did not had any feedback on it, but would be glad to have yours

**Comment by ratthing** [comment]
Reporting the exact same error.  Just upgraded to 8.02 stable.  
When I go directly to the Bookmark app for the first time after opening a browser, it stalls while loading the left column, and never continues.  
If I go to the "Files" app, then click back to the "Bookmarks" app, then the Bookmarks page load just fine.

**Comment by blizzz** [comment]
Fixed with c522347 in master and stable8.1, can be probably backported to stable8 easily.
