### ISSUE TITLE
Floccus Lock

### ISSUE THREAD

**Issue by Jolopu** [nextcloud/bookmarks#1260]
I keep getting this Nextcloud messages. Very annoying. How to get rid of it? I will downgrade to an older version until this is solved.

Thanks!

<img width="774" alt="floccus-lock" src="https://user-images.githubusercontent.com/34797349/96373546-73fd0000-116d-11eb-806b-27e905feb49f.png">

**Comment by marcelklehr** [comment]
Closing in favor of marcelklehr/floccus#685
