### ISSUE TITLE
I upgraded to Nextcloud 20.0.0 and Bookmarks 3.4.4

### ISSUE THREAD

**Issue by magic-rat** [nextcloud/bookmarks#1270]
... and now the search does not work.

I'm talking about the little search box in the upper right of the header bar ... that expands when you hover over it.

It searches the "Files" app ... but not bookmarks.

Before the upgrade to v 20.0.0 ... it would search bookmarks, too.

**Comment by marcelklehr** [comment]
should be fixed in v4.x
