### ISSUE TITLE
Bookmark title == URL and no picture

### ISSUE THREAD

**Issue by Kariton** [nextcloud/bookmarks#1275]
Hey, since the last release there seems to be some trouble with the bookmark creation. (maybe rel #1255)
i normally dont use the webinterface to create my bookmarks (floccus is already set up on all devices and works really well)

now i noticed the archive feature for pictures and pdfs and wanted to try it.

i created a bookmark to a pdf
the title == url and no more informations are present
a click on the bookmark work as intended

i created a bookmark to a 'normal' website
the title == url and no more informations are present
a click on the bookmark work as intended

only errors occured in firefox / chrome console

unsurprisingly the 'archive is still empty

logs from console:
[console-chrome.log](https://github.com/nextcloud/bookmarks/files/5431972/console-chrome.log)
[console-firefox.log](https://github.com/nextcloud/bookmarks/files/5431973/console-firefox.log)

im running latest NC 19 and latest Bookmarks (today)

i appreciate your work and inprovements on this awsome app. 
thank you

**Comment by lyallp** [comment]
Running NextCloud 20, Bookmarks 4, seem to have lost all preview images of all bookmarks, leaving default 'globe' image as the default. This includes thee Grid as well as the List layout.
Upgraded from Bookmarks previous version using web interface admin->apps.

**Comment by Kariton** [comment]
updated to bookmarks v. 3.4.5 - nothing changed.

**Comment by lyallp** [comment]
Version 4.0.1
Upgraded using admin web UI.
Logged out and in of non admin user.
Also seeing 'Failed to count bookmarks', what appears to be one for each folder.
Tried exporting/clearing and re-importing bookmarks, to no avail.
Still showing default globe.
Tried adding new bookmark, (google.com) and default globe shows.
Additionally, Settings -> Export displays the dashboard, returning to bookmarks and re-clicking export generates the download.
Finally, import seems to trigger the 'Failed to count bookmarks' fairly reliably.
Note that my shared linux hosting environment seems to be a little under load at this time.

Maybe some leftover cache somewhere?

**Comment by lyallp** [comment]
Admittedly, changelog did not address the following issues, regardless, they exist.

Version 4.0.2 plus NextCloud 20 on shared linux cPanel with MySQL.
Upgraded using admin web UI.
Logged out and in of non admin user.
Still seeing 'Failed to count bookmarks', just not as many. I have 73 bookmarks.
However, still showing default globe for all existing bookmarks and new bookmarks (eg. google).
Basically, no change in behavior over previous 2 releases, as per my previous post.

**Comment by lyallp** [comment]
Only just noticed, Bookmarks does not show 'Apps' menu to right of NextCloud Logo IF you go directly from the Dashboard to Bookmarks.
If I go Dashboard -> any other app -> Bookmarks, then the App icons are shown.
Note that if the app icons are not shown, my cursor still changes to a hand where the icons would be.
Clicking on this 'Blank' area seems to select Apps, disregarding the 'App Order' app.

**Comment by marcelklehr** [comment]
> However, still showing default globe for all existing bookmarks and new bookmarks (eg. google).

Sorry for the delay. I cannot reproduce this. Have you enabled network access (under privacy) in the admin settings of the bookmarks app?

**Comment by lyallp** [comment]
Checking the 'Privacy' checkbox under Admin settings of Bookmarks enables the display of bookmark previews. More fiddling required because not all bookmarks appear to generate previews. I will investigate using screeenly, whether self hosted or internet based. 👍 
This does not seem to have fixed the disappearing App icons across the top.
I also saw a failed to count message but seem to be having difficulty reproducing the error.

**Comment by lyallp** [comment]
Updated to NextCloud 20.0.1, same as above.

**Comment by marcelklehr** [comment]
Ok, one down one to go.

I have no influence over the app icons, sadly. Not sure why they disappear. That's likely a nextcloud server issue. If you can reproduce the failed to count issue, feel free to open a new report :heart:
