### ISSUE TITLE
Feature request:t tagging multiple bookmarks.

### ISSUE THREAD

**Issue by brimwats1** [nextcloud/bookmarks#1279]
**Is your feature request related to a problem? Please describe.**
I would really like to be able to tag multiple bookmarks at once

**Describe the solution you'd like**
When selecting multiple bookmarks in the list view there should be a way to select multiple bookmarks to tag at once 

![image](https://user-images.githubusercontent.com/49103046/97088452-cc0c8a00-15e5-11eb-9101-91818149666e.png)

**Describe alternatives you've considered**
Right now I have to import batches of bookmarks into Raindrop.io and then tag them all and then import them into NC Bookmarks.

**Comment by marcelklehr** [comment]
Hello @brimwats 
Thank you for your feedback. This is already planned (see #1259 )
