### ISSUE TITLE
Bookmark has higher php requirements then NC 20 needs

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/bookmarks#1284]
**Describe the bug**
After upgrade from NC v20.0.0 to v20.0.1 the app can no longer be enabled

**To Reproduce**
1. Use NC v.20.0.0 with bookmark v4.0.0
2. Upgrade to NC v20.0.1
3. bookmark app cannot be enabled because of "This app cannot be installed because the following dependencies are not fulfilled: PHP 7.3 or higher is required.

**Expected behavior**
App should work with php 7.2 like the server version 20 does.
Currently that means you cannot run the app on any stable NC version.

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - HTTP server: Apache
 - Database: PostGreSQl 10.13
 - PHP version: v7.2
 - Nextcloud version: 20.0.1
 - Bookmarks app version: 4.0.0

**Comment by marcelklehr** [comment]
I admit I'm being a bit of an early bird, but official support for PHP 7.2 [ends in one month](https://www.php.net/supported-versions.php)

**Comment by rakekniven** [comment]
Hello Marcel,

this broke my installation and so I am asking why I can install an app also if the system requirements do not fit for the app?

**Comment by rakekniven** [comment]
Can I downgrade the app? Will the db scheme work with an downgrade?

**Comment by marcelklehr** [comment]
Sorry for the short reply.

Being able to install despite unmet requirements would be a bug in the server code, but I guess they fixed that in v20.0.1 causing the issue in the first place.
So far, v3.4.x has the same db schema as v4, yes. And I'm also backporting important fixes to v3.x

**Comment by rakekniven** [comment]
Ok, so I will downgrade right now. Thank you for this beautiful app/addon and such quick reply!
