### ISSUE TITLE
Distribution: Composer development dependencies included in file distributed by https://apps.nextcloud.com/apps/bookmarks

### ISSUE THREAD

**Issue by earboxer** [nextcloud/bookmarks#1287]
**Describe the bug**
More files are being distributed than need to be distributed. The uncompressed distribution includes a fairly heavy `vendor` folder.

**To Reproduce**
1. Download one of the archives from https://apps.nextcloud.com/apps/bookmarks
2. Uncompress it
3. Note the presence of vendor/phpunit (and some others)
4. `du -sh vendor` -- notice how large this is (19 - 35 MiBs)
5. `composer install --no-dev` -- notice how it removes a bunch of packages
6. `du -sh vendor` -- this is now *much* smaller  (5.8 - 6.5 MiBs)

**Expected behavior**
I guess the packager should use `--no-dev` when installing the dependencies before creating the archive.

**Comment by marcelklehr** [comment]
Thank you for the heads-up @earboxer! Should be fixed now :heart:
