### ISSUE TITLE
Bookmarks 3.4.6 E020 error with Floccus

### ISSUE THREAD

**Issue by n-greene** [nextcloud/bookmarks#1290]
**Describe the bug**
WIth the update to 3.4.6 all my Floccus syncs are showing
E020: Could not parse server response. Is the bookmarks app installed on your server? Unexpected token < in JSON at position 0 as an error, with no synchronization occurring
Floccus is version 4.3.0 and this was working smoothly before the 3.4.6 update
**To Reproduce**
1. Go to 'Floccus extension in Brave Browswer'
2. Click on 'Sync'
3. Scroll down to '...'

**Expected behavior**
I expected the sync to occur
**Screenshots**

**Desktop (please complete the following information):**
MacOsx Catalina 
10.15.17
PopOs Latest
**Server (please complete the following information):**
 - OS: [TrueNas]
 - HTTP server: apache24
 - Database: mysql 10.4.14
 - PHP version: 7.4.11
 - Nextcloud version: 19.04
 - Bookmarks app version: 3.4.6
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - accessibility: 1.5.0
  - activity: 2.12.1
  - apporder: 0.11.0
  - bookmarks: 3.4.6
  - breezedark: 19.0.6
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - cms_pico: 1.0.10
  - comments: 1.9.0
  - contacts: 3.4.1
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_downloadactivity: 1.8.0
  - files_external: 1.10.0
  - files_fulltextsearch: 1.4.3
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - fulltextsearch: 1.4.2
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - maps: 0.1.6
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - qownnotesapi: 20.9.0
  - ransomware_protection: 1.7.0
  - recommendations: 0.7.0
  - richdocuments: 3.7.5
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - side_menu: 1.19.1
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.5
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.0.0
  - updatenotification: 1.9.0
  - video_converter: 0.1.5
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - mail
  - richdocumentscode
  - richdocumentscode_arm64
  - spreed
  - user_ldap
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]

    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.36",
            "next.nebbles.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "overwrite.cli.url": "http:\/\/next.nebbles.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
 - Nextcloud external user backend: [e.g. ldap, or none]

none

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
Mh, I cannot reproduce this. Have you checked the server log (nextcloud/data/nextcloud.log)?

**Comment by daddydaycare** [comment]
I have this error one on of my pc.  After having all bookmarks deleted and reinstalling and it seeming to work on first pc.  Later all other pc have errors. one has this 20. The other says Nextcloud API error: {"status":"error","data":"invalid children order: A child is missing: folder:75"}

**Comment by ours1** [comment]
Hi, I have something similar (floccus v4.4.6)
 Nextcloud API error: {"status":"error","data":"invalid children order: A child is missing: bookmark:0"}
Here what I did just before syncing : I rename a folder with firefox in the nextcloud bookmark cloud. 
As a result the name in the firefox bookmarks didn't change, and the folder in my nextcloud bookmark cloud came back to his former name.
Hope these clues will help ! Ask me if I can do more...

**Comment by ours1** [comment]
I'v tried something else :
I deleted both of the folder in firefox bookmarks and in my nextcloud bookmark cloud, and after syncing I have this message
"No bookmarks found for the provided GUID." 
but the changes I made remained in both

I tried also this : created a folder in my nextcloud bookmark and after syncing I still have this message
"No bookmarks found for the provided GUID". 
but everything did synchronize well in both

Ah ! I think I have a terrific clue : all I did was with xubuntu, and the last changes synced well on an other pc with windows and no error message !

**Comment by tom-ch1** [comment]
I had this error, too and I found out that the bookmark Title was too long and caused an exception of the db-server:

{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'INSERT INTO \"oc_bookmarks\" (\"title\", \"url\", \"description\", \"user_id\", \"added\", \"lastmodified\", \"last_preview\", \"clickcount\") VALUES(?, ?, ?, ?, ?, ?, ?, ?)' with params [\"very long Bookmark title here\", ...
SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(255)","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver","

I shortened the Bookmark title and this "fixed" the error. You probably want to catch that and convert it into a warning

**Comment by marcelklehr** [comment]
Nice one @tom-ch1 :tada:
