### ISSUE TITLE
fast loading browser start page url?

### ISSUE THREAD

**Issue by poVoq** [nextcloud/bookmarks#1291]
**Is your feature request related to a problem? Please describe**
I would really like to quick access my NC bookmarks from a new browser tab without going through some browser extension or opening the slow to load NC webinterface.

As all browsers support setting a custom homepage url, maybe it would be easiest to have a custom url for NC bookmarks that is quick to load (and responsive for mobile browsers) that can be used as a browser start page?

Ideally also with some quick way to add new bookmarks and maybe also some highlighted favorite bookmarks or most often used bookmarks etc? Maybe that could be somewhat user customizable?

Thanks for considering.

**Comment by marcelklehr** [comment]
Mmh, so there's two issues that I see here.

A) Apparently the current web interface is slow for you? That could be explored to make the experience faster. In v4.x the performance has already been improved.

B) A request for a page that could be used as a "new tab" page. Nextcloud already has the new Dashboard in v20, which could fill this function, but I can see that that might not be exactly what you have in mind. There's requests for favorite bookmarks already, and the app counts the clicks for every bookmark, so there's definitely material for building something like this.

**Comment by poVoq** [comment]
Assuming that one would load that page every time one opens a new tab the regular Nextcloud web interface really is way to heavy. I was actually thinking about utilizing the RSS feeds in a similar fashion, but a simple html only page would probably be more flexible.

**Comment by marcelklehr** [comment]
floccus.org tries to sync your browser bookmarks with nextcloud, so taking into account that most browsers already provide such a page for local bookmarks, floccus may be an option.

**Comment by poVoq** [comment]
Yeah, but there are many browsers that are not supported by Floccus and Floccus also doesn't offer a similar "new tab" experience like Firefox sync for example does.

**Comment by marcelklehr** [comment]
I'm closing this as I think what you describe best fits what I intend the bookmarks main page to be. Obviously, we are not there yet, feature and performance-wise, but I'd rather focus on that than introducing a dedicated "new tab" page which duplicates the functionality of the main page. There are lots of performance improvements that can be made, I just have a lot of things on my plate already, so anyone is free to step up and invest time for this, otherwise I'll tackle this when I get to it :v:  :relaxed:

**Comment by marcelklehr** [comment]
v4.0.7 was just published with lots of performance improvements.
