### ISSUE TITLE
Darstellung des Schlagwort-Arrayas und Update  Issue 

### ISSUE THREAD

**Issue by ramosBerlin** [nextcloud/bookmarks#1292]
Problem 1: the array of bookmark-schlagworte is not displayed correct when showing the 'details'-page of the bookmark
Problem 2: (perhaps consecutive of 1): editing the URL of an existing bookmark will not be stored
Problem 3 (minor): count of link-failures sounts something... but does display a strange numer (19 for one faulty bookmark)

![2020-10-30 16_51_00-Bugreport Bookmark](https://user-images.githubusercontent.com/66569555/97728010-531f9d80-1ad1-11eb-95b2-67b945946c5f.png)

**Comment by marcelklehr** [comment]
I cannot replicate this. Which versions (are) this? (The issue template is there for a reason ;) )

**Comment by ramosBerlin** [comment]
using google chrome on win10
Nextcloud  V 19.0.4.2
on a ngix/1.16.1
Version of bookmark 3.4.6

**Comment by ramosBerlin** [comment]
and the list of active apps:
Flow Upload	1.0.0		 
Accessibility	1.5.0	Offiziell	
Activities for shared file downloads	1.8.0		
Activity	2.12.1	Offiziell	
AppOrder	0.11.0		
Auto Groups	1.2.0		
Automated PDF conversion	1.4.0		
Bookmarks	3.4.6		
Brute-force settings	2.0.1	Offiziell	
Calendar	2.0.4	Offiziell	
Camera RAW Previews	0.7.9		
Circles	0.19.7	Offiziell	
Collaborative tags	1.9.0	Offiziell	
Comments	1.9.0	Offiziell	
Community Document Server	0.1.8		
Contacts	3.4.1	Offiziell	
Contacts Interaction	1.0.0	Offiziell	
Cookbook	0.7.6		
Cospend	1.0.5		
Dashboard	6.0.0		
Deck	1.1.2	Offiziell	
Deleted files	1.9.0	Offiziell	
Draw.io	0.9.7		
End-to-End Encryption	1.5.2	Offiziell	
External sites	3.6.0	Offiziell	
Extract	1.2.5		
Federation	1.9.0	Offiziell	
File access control	1.9.1	Offiziell	
File sharing	1.11.0	Offiziell	
Full text search	1.4.2		
GeoBlocker	0.4.0		
Group folders	7.1.0	Offiziell	
Impersonate	1.6.1	Offiziell	
JavaScript XMPP Chat	4.1.1		
Link editor	1.1.2		
Log Reader	2.4.0	Offiziell	
Mind Map	0.0.23		
Monitoring	1.9.0	Offiziell	
NextBackup	20.9.0		
Nextcloud announcements	1.8.0	Offiziell	
Notifications	2.7.0	Offiziell	
Notifications for calendar event updates	1.0.2		
ONLYOFFICE	6.1.0	Offiziell	
Password policy	1.9.1	Offiziell	
PDF viewer	1.8.0	Offiziell	
Photo Sphere Viewer	1.19.1		
Photos	1.1.0	Offiziell	
Polls	1.5.7		
Privacy	1.3.0	Offiziell	
Quota warning	1.8.0		
Recommendations	0.7.0	Offiziell	
Share by mail	1.9.0	Offiziell	
Support	1.2.1	Offiziell	
Talk	9.0.5	Offiziell	
Tasks	0.13.5	Offiziell	
Text	3.0.1	Offiziell	
Theming	1.10.0	Offiziell	
Update notification	1.9.0	Offiziell	
Versions	1.12.0	Offiziell	
Video player	1.8.0	Offiziell	
W2G2	3.0.3

**Comment by marcelklehr** [comment]
Mmh, ok, nothing unusual there. I think I've found the culprit in the code, though.
