### ISSUE TITLE
Cannot install app

### ISSUE THREAD

**Issue by ddt3** [nextcloud/bookmarks#1306]
**Describe the bug**
When I try to install Bookmarks on a clean Nextcloud 20.0.1 an error is given:
`Client error: `GET https://github.com/nextcloud/bookmarks/releases/download/v4.0.4/bookmarks-4.0.4.tar.gz` resulted in a `404 Not Found` response: Not Found.`

**To Reproduce**
1. Go to Apps'
2. Search Bookmarks
3. Click "Download and Enable"
4. Error: 404

(The irony of version 4.0.4 causing a 404 ;-) )
**Expected behavior**
Bookmarks to be installed

**Additional context**

Looking at github, it does make sense:
https://github.com/nextcloud/bookmarks/releases/download/v4.0.4/bookmarks-4.0.4.tar.gz
Indeed does not exist, 
while e.g.:
https://github.com/nextcloud/bookmarks/releases/download/v4.0.4/bookmarks-4.0.3.tar.gz
does exist

**Comment by jurgenhaas** [comment]
Same issue here, looks like the real GitHub link is now https://github.com/nextcloud/bookmarks/archive/v4.0.4.tar.gz

**Comment by trvrcr** [comment]
I confirm.

**Comment by JSoko** [comment]
> looks like the real GitHub link is now https://github.com/nextcloud/bookmarks/archive/v4.0.4.tar.gz

No, that's the sourcecode...

**Comment by nursoda** [comment]
On NC19, the error message for 3.4.6→3.4.7 is "An error occured during the request. Unable to proceed. Couldn't update app." which is a less helpful message but seems to be the same issue.

**Comment by joergmschulz** [comment]
same for NC18. We have 2 error messages / one as quoted above (404), one: `Error: Undefined offset: 3 at /www/nextcloud/lib/private/legacy/OC_Helper.php#548`

**Comment by marcelklehr** [comment]
The release rollout was stopped, because of https://github.com/nextcloud/bookmarks/issues/1305

**Comment by soerpoers** [comment]
Is it possible to update the link in the appstore to get the old version vor NC19 (3.4.6)?

**Comment by marcelklehr** [comment]
v3.4.9 and v4.0.5 are out now.

**Comment by marcelklehr** [comment]
Reopening for affected people to find this.

**Comment by joergmschulz** [comment]
confirming - 3.4.8 works now for NC18
