### ISSUE TITLE
Adding primary keys for Galera compatibilty

### ISSUE THREAD

**Issue by dr-hildi** [nextcloud/bookmarks#1317]
**Is your feature request related to a problem? Please describe.**
We are running into the described limitations (especially unsupported `DELETE` operations) on MariaDB Galera as described here: <https://mariadb.com/kb/en/mariadb-galera-cluster-known-limitations/>

**Describe the solution you'd like**
Every table should have a primary key.

**Describe alternatives you've considered**
If this isn't possible please remark in documentation that this app isn't compatible to installations on Galera clusters.

**Additional context**
There are other good reasons to have these primary keys: <https://vettabase.com/blog/why-tables-need-a-primary-key-in-mariadb-and-mysql/>

<http://moiseevigor.github.io/programming/2015/02/17/find-all-tables-without-primary-key-in-mysql/> results in e.g.:

```
...
| oc_bookmarks_folders_bookmarks |
| oc_bookmarks_tags              |
...
```

**Comment by brtptrs** [comment]
Does this mean the bookmarks module can not be used when NC is running on a galera cluster? To be on the safe side we've disabled bookmarks, since I don't know how to test this.
