### ISSUE TITLE
Automatic export of bookmarks to file system

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#1318]
****Is** your feature request related to a problem? Please describe.**
I'd like to request a copy of bookmarks be exported as html via cron to the attachments folder, or some other user selectable location.  Recent update #1305 removed bookmarks so the most recent backup is my last manual database export to html.

**Describe the solution you'd like**
Automatic html export of bookmarks to a directory on the filesystem.  I'd love for a backup once a day or once a week.

**Describe alternatives you've considered**
I keep manual exports, but they are saved to my client devices and the process is not automated [as described here](https://github.com/nextcloud/bookmarks/issues/446#issuecomment-396367059).

Thanks for considering!

**Comment by marcelklehr** [comment]
I understand the intention, but I'm not in favor of adding this to the app, mainly because there's an easy way to do this already, albeit without a UI:


```bash
$ curl -k -u "username:password https://nextcloud.local/index.php/apps/bookmarks/public/rest/v2/bookmark/export
```

**Comment by radoeka** [comment]
> I understand the intention, but I'm not in favor of adding this to the app, 

Why not?  

You provide the following reason:

> mainly because there's an easy way to do this already, albeit without a UI:

But that is not really easy for many people.  Providing the functionality via the GUI, would help those people.

It is a security risk: the account credentials are entered on the command line, this is not always hidden.  And when done incorrectly it is even stored in the command line history.  This is not safe (enough) :(

That it is not easy, can be seen from the example provided.  The closing quotes after password after missing....

**Comment by sunjam** [comment]
Interesting point.  My intention is: allow an unprivileged user to save
their bookmarks to their nextcloud file system so they'll be able to sync
backups to their mobile devices and such.

**Comment by marcelklehr** [comment]
If the intention is to sync bookmarks to mobile devices: This is what the API and mobile apps are for. The state of bookmarks' mobile apps is currently not great, but that's not a good reason to invent workarounds, in my opinion.

If the intention is to backup data in order to prevent data loss: Data loss should already be covered by the sysadmin running the instance, by backing up the database.

If the user wants to be extra safe, they can manually export the bookmarks in regular intervals -- manually or automated with the API as shown above. Soon, there'll also be a trash bin for recovering deleted bookmarks.

Regularly dumping app data into the user's files is unprecedented in the nextcloud ecosystem.

I'm happy to add a button for storing an exported file in nextcloud files, but I'm against adding a regular backup.

**Comment by Mayurifag** [comment]
😢 I'm upset about this issue to be closed. As for me, application becomes nearly unusable.

It blows my mind I can't simply have some kind of txt/yaml/conf/whatever file(s) that are easy to be edited locally and synced onto server -> onto my browsers same moment via nextcloud. Yea, web GUI is cool, but there are many cases, where the strength of text editors becomes obvious.

And as mentioned, boomarks-backup-file(s) are handy on the sight of backup: its already backuped alongside with other nextcloud files. So its very convenient for me as an administrator with self-hosted docker nextcloud instance to manage, move on file system, copy to another instances, etc.

Is there any way this feature can be actually developed? Proposals/donations/discussions?

**Comment by jcm4atx** [comment]
> I understand the intention, but I'm not in favor of adding this to the app, mainly because there's an easy way to do this already, albeit without a UI:
> 
> ```shell
> $ curl -k -u "username:password" https://nextcloud.local/index.php/apps/bookmarks/public/rest/v2/bookmark/export
> ```

Thanks, this is exactly what I was looking for.

**Comment by marcelklehr** [comment]
> I'm against adding a regular backup.

I've revised this decision now, and have implemented a regular backup for

* every day for the past 7 days
* every Monday for the past 5 weeks
* every first Monday for the past 6 months
