### ISSUE TITLE
Allow sharing to Circles in the same way as sharing to Groups.

### ISSUE THREAD

**Issue by Torenga** [nextcloud/bookmarks#1325]
**Is your feature request related to a problem? Please describe.**
I can't share a bookmarks folder through the "Circles" app.

**Describe the solution you'd like**
I want to be able to share bookmarks folders to Circles in the same way I can share to Groups.

**Describe alternatives you've considered**
- Manually watching the relevant circle and add users to the group I've shared the bookmarks folder with.
- Create a shared task list or board where users request access to the bookmarks folder.
- Not use Bookmarks app for bookmark sharing, rather use .URL files and share the files folder.

**Other**
It's currently possible to share a regular file folder to Circles.

**Comment by marcelklehr** [comment]
This is a good idea, sadly Nextcloud does not provide a public API for apps to interact with Circles, so this is currently not possible.

**Comment by marcelklehr** [comment]
Implemented.
