### ISSUE TITLE
It's WAAAY too easy to delete something by accident!

### ISSUE THREAD

**Issue by steeeeev0** [nextcloud/bookmarks#1326]
**Is your feature request related to a problem? Please describe.**
I was moving bookmarks out of a recovery folder. The move and delete buttons are awfully close together. I found out the hard way that there is no confirmation asking to deleting a bookmark before it gets deleted. Accidentally hit delete? it's gonezo! (unless I'm missing something?)

**Describe the solution you'd like**
Ask the user to confirm deleting a bookmark. Same should happen when deleting a folder, especially if the folder has bookmarks in it.

Thanks!

**Comment by marcelklehr** [comment]
> it's gonezo!

:sweat_smile:
