### ISSUE TITLE
Installing Bookmarks on Nextcloud 20.0.1 PHP Version

### ISSUE THREAD

**Issue by jrnovak** [nextcloud/bookmarks#1330]
**Describe the bug**
I just installed NC on Amazon AWS as part of Mailinabox deployment.  I want to install the Bookmarks app however I can't because the PHP version is 7.2 and BookMarks requires version 7.3.  I do not know how to upgrade the version of PHP without breaking Nextcloud.  

**To Reproduce*

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS X]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]

**Server (please complete the following information):**
 - OS: Ubuntu 18
 - HTTP server: NGINX
 - Database: [e.g. MySQL 5.3]
 - PHP version: 7.2
 - Nextcloud version: 20.1
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)]
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by j-ed** [comment]
The problem has already been reported and discussed in the following [issue ticket](https://github.com/nextcloud/bookmarks/issues/1284).

BTW, support for PHP 7.2 will **[officially end in 4 days](https://www.php.net/supported-versions.php).** You should update your installation asap!
