### ISSUE TITLE
405 on PUT + DELETE for /public/rest/v2/tag/<TAG> 

### ISSUE THREAD

**Issue by altepizza** [nextcloud/bookmarks#1334]
**Describe the bug**
Deleting or renaming tags via the public REST API will result in a 405

**To Reproduce**
DISCLAIMER: Add your credentials to these curls

***DELETE***
`curl --location --request DELETE 'https://your.cloud.example/index.php/apps/bookmarks/public/rest/v2/tag/deleteMe'`

***PUT***
`curl --location --request PUT 'https://your.cloud.example/index.php/apps/bookmarks/public/rest/v2/tag/deleteMe' \
--data-raw '{ "name": "somethingElse" }'`

**Expected behavior**
[API Doc](https://nextcloud-bookmarks.readthedocs.io/en/latest/tag.html)

**Desktop:**
 - OS: MacOS X

**Server:**
 - Database: mysql 10.3.27
 - PHP version: 7.4.11
 - Nextcloud version: 19.0.3
 - Bookmarks app version: 3.4.9
 - Nextcloud external user backend: none

**Comment by marcelklehr** [comment]
I'm sorry for the long delay.

I can confirm the problem.

The second line should read

```
curl --location -k -u user:password --request PUT 'https://nextcloud.local/index.php/apps/bookmarks/public/rest/v2/tag/deleteMe' -H "Content-Type: application/json" --data-raw '{ "name": "somethingElseEntirely" }'
```

**Comment by altepizza** [comment]
Thx
