### ISSUE TITLE
Error in Microsoft edge

### ISSUE THREAD

**Issue by barnycloud** [nextcloud/bookmarks#1335]
I would like to get floccus running in Microsoft edge browser based on Chromium. After adding floccus to edge (from Google Web Store), I created  in the floccus add on two accounts. The folder /FavBar points to /Favorites Bar/ in folder mapping, the folder /Bookmarks points to /Next Favorites/ in edge.  Before that you have to disable the synchronization via the Microsoft account. The bookmarks in nextcloud are already created (from Chrome), the favorites and the bookmarks in edge I have deleted (of course backed up before). The synchronization with /FavBar <-> /Favoritenleiste works, when synchronizing /bookmarks<-> /Weitere Favoriten/ the following error message appears:
Trying to insert an already existing item into OrderTracker: folder:1399 Trying to insert an already existing item into OrderTracker: folder:1365 Trying to insert an already existing item into OrderTracker: folder:1773 Trying to insert an already existing item into OrderTracker: folder:1773 Trying to insert an already existing item into OrderTracker: folder:1396

1. Go to 'floccus add on'
2. Click on 'Jetzt synchronisieren'

Expected behavior
Syncronization of the Browser bookmarks /Weitere Favoriten/ with nextcloud bookmars folder /Lesezeichen
**Screenshots**

Desktop:
 - OS: Win 10 Pro 64bit
 - Browser: MS edge
 - Version: 87.0.664.47

Server:
 - Hosted on All-Inclusive.com
 - PHP version: 7.3
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)]
 - Bookmarks app version: 18.0.11
 - Activated Nextcloud Apps: Accessibility 1.5.0, Activity 2.12.1, Appointments 1.7.14, Bookmarks 3.4.9. Calendar 2.0.4, 
    Collaborative tags 1.9.0, Comments 1.9.0, Contacts 3.4.2, Contacts Interaction 1.0.0, Deleted files 1.9.0, Federation 1.9.0, 
    File sharing	1.11.0, First run wizard 2.8.0, Log Reader 2.4.0, Monitoring 1.9.0, Music 0.17.3, Nextcloud announcements	 
    1.8.0, Notifications 2.7.0, Password policy 1.9.1,  PDF viewer 1.8.0, Photos 1.1.0, Privacy 1.3.0, Recommendations	0.7.0	,	
     Right click 0.16.0, Share by mail	1.9.0	, Support	1.2.1	, Tasks 0.13.6, Text 3.0.1, Theming 1.10.0, Update notification 1.9.0,	
     Usage survey 1.7.0, Versions 1.12.0, Video player 1.8.0, Auditing / Logging 1.9.0, Default encryption module 2.7.0,	
     External storage support 1.10.0, 
  - Nextcloud external user backend: LDAP user and group backend

**Nextcloud log: LDAP user and group backend (nextcloud/data/nextcloud.log)**
```
Nextcloud log: [no app in context] Warning: Temporary directory /www/htdocs/w0140bcd/barnert.org/html/nextcloud/tmp/ is not present or writable
GET /index.php/apps/logreader/poll?lastReqId=X8aQEZO31iwQ4pFFnZn7swAAAds
from 93.104.163.222 at 2020-12-01T18:48:49+00:00
```

 In Firefox and Chrome floccus works fine

**Comment by barnycloud** [comment]
I have deleted some folders and bookmarks in nextcloud bookmarks and see, there is no error message anymore using synchronization in the floccus add on. But I also noticed in Chromium and Chrome that there are always error messages about individual folders and bookmarks, e.g. during synchronization that individual bookmarks are tried to be edited which would not exist.
Concerning the MS browser  edge:
First of all you have to unsubscribe the synchronization with Microsoft. In doing so the questen  appears if you want to delete all your favorites in edge. I checked this box. Then I synchronized my folder /FavBar (nextcloud bookmarks) with /Favoritenleiste/ (in German) in edge and synchronized /Lesezeichen (in German) in the nextclod bookmarks with /Weitere Favoriten/ (in German) in edge accordingly.

**Comment by barnycloud** [comment]
Again I got the errror message whhen trying to synchronize in edge the folder /Weitere Favoriten/ with /Lesezeichen in the nextcloud bookmarks app:
Trying to insert an already existing item into OrderTracker: folder:1399 Trying to insert an already existing item into OrderTracker: folder:1365 Trying to insert an already existing item into OrderTracker: folder:1773 Trying to insert an already existing item into OrderTracker: folder:1773 Trying to insert an already existing item into OrderTracker: folder:1396

**Comment by marcelklehr** [comment]
This belongs in the [floccus bug tracker](https://github.com/marcelklehr/floccus/issues). I'm currently working on ironing out lots of bugs, though, so this might soon be fixed.
