### ISSUE TITLE
Formatting for Notes

### ISSUE THREAD

**Issue by digitalap3** [nextcloud/bookmarks#1349]
Thank you for this beautiful and useful addition to NC.  I wonder if some kind of formatting for the Notes section would be possible - even something as simple (in looks I have no idea about execution) as maintaining new lines/ empty lines.

I like to copy/paste relevant parts of a page I have saved sometimes or even just having a clean list of ideas from the page separated by empty lines.

**Comment by sunjam** [comment]
See Markdown / Note discussion in #443 and #447

**Comment by digitalap3** [comment]
> See Markdown / Note discussion in #443 and #447

Thank you.
