### ISSUE TITLE
abysmal sync performance - need help pinpointing it

### ISSUE THREAD

**Issue by rmalchow** [nextcloud/bookmarks#1363]
**Describe the bug**
we've been running NC for ages, and it is rolled out for everyone. now we were looking at floccus again, and we have some bad experiences. 

for one, we see a _lot_ of bookmark related requests in the logs, with way more then the fair share of errors.

examples are:
```
{ ....  
"app":"index",
"method":"GET",
"url":"/index.php/apps/bookmarks/public/rest/v2/bookmark/undefined",
"message": ... "Argument ... must be of the type
}
```

but also complaints about invalid JSON, and, on the client side:
```
Incorrect argument types for bookmarks.move. Incorrect argument types for bookmarks.move. Incorrect argument types for bookmarks.move. Incorrect argument types for bookmarks.move. Incorrect argument types for bookmarks.move. Incorrect argument types for bookmarks.move. Incorrect argument types for bookmarks.move. Incorrect argument types for bookmarks.move. Incorrect argument types for bookmarks.move. Incorrect argument types for bookmarks.move.
```
this is all annoying, but the biggest issue is that even with just three users testing this, (on firefox macOS and fedora), CPU utilization and load on the server go up tenfold. while "normal" nextcloud utilization during the day is ~0.5-1 core, when a single person starts a bookmark sync, it goes up to 4 cores or more. with more clients, it maxes out. 

i do not believe that this is normal, so i am wondering how we can debug this, and what we can do to help eliminate this issue for other people.

**Comment by marcelklehr** [comment]
Hi,

the errors are probably due to a recent refactoring of floccus that introduced a decent amount of bugs.
Bad performance is usually mitigated by using APCu caching. Which version of bookmarks do you have installed?

**Comment by rmalchow** [comment]
hi marcel. thank you for your answer. i cannot give you more information until next week - but we did update an update yesterday, and it is actually looking much better now. what i was wondering - from the debug log, i see many many hashes ... but i also see many, many request indicating hierarchical, recursive requests .... wouldn't it be possible to apply some git-like approach, treat the entire thing as a single state, and move most of the heavy lifting to the client side? or was the fact that the clients seemed to do continous deep recursions through the entire tree also a bug rather than expected behaviour?

**Comment by marcelklehr** [comment]
> many, many request indicating hierarchical, recursive requests

Floccus uses hash trees to find out which parts of the tree have changed and only loads those parts from the server. That means, the more differences there are, the longer things take. At a certain point it may be more efficient to load the whole tree once, instead of traversing it via the network, but I'm not yet sure how to determine that threshold...

**Comment by marcelklehr** [comment]
Sync performance should be much better with recent versions of both floccus and the bookmarks app. Let me know if you still experience issues. I'm closing this for now.
