### ISSUE TITLE
reduce previewimage size

### ISSUE THREAD

**Issue by BigMichi1** [nextcloud/bookmarks#1368]
**Is your feature request related to a problem? Please describe.**
When you have a folder containing some links pointing to some "huge" webpages, like https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/CHANGELOG.md or https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/CHANGELOG.md scrolling is nearly impossible when using pageres as a preview engine. the resulting image that is send to the browser is currently 29mb and 14mb

**Describe the solution you'd like**
maybe resizing can help here as as far as i have seen only the top of the page is shown or when the preview is too large some kind of placeholder should be show

**Describe alternatives you've considered**
choosing a different image format maybe can also help, pageres also supports jpeg

**Additional context**
also the two links above will not show up correctly in the details as there is only one small white bar in the middle of the preview

**Comment by marcelklehr** [comment]
I used the crop argument to get rid of the rest of the page content.
