### ISSUE TITLE
bookmarks cache folder is filled up with 4 byte files

### ISSUE THREAD

**Issue by BigMichi1** [nextcloud/bookmarks#1369]
**Describe the bug**
the ``bookmarks/cache`` folder in the ``appdata`` directory contains hundreds of files with a 4 byte size and when inspecting the content only ```null``` is written there.

**To Reproduce**
1. configure pageres as preview engine
2. clear cache folder by manually removing the entire content
3. reload oropen a bookmarks folder containing some links
4. many 4 byte files are stored

**Expected behavior**
these ``null`` 4 byte files should not be stored as there are eating the inodes and also according to the file name they belong to the not configured preview engines

**Screenshots**
![image](https://user-images.githubusercontent.com/91786/103915219-34f69f00-510b-11eb-94a3-f1a97b2f2f7b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 87.0.664.66

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - HTTP server: nginx
 - Database: PostgreSql 12.4
 - PHP version: 7.4.13
 - Nextcloud version: 20.0.4
 - Bookmarks app version: 4.0.5

**Comment by marcelklehr** [comment]
Fixed by a8cda09
