### ISSUE TITLE
Breaking changes in Nextcloud 21

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/bookmarks#1372]
Hi there,

I found that your app uses some classes of Nextcloud's third party libraries. Since an upgrade of those for php8 compatibility, your app will have to be adjusted as well. See https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#doctrine-dbal for details. Your app uses `Doctrine\DBAL\Types\Type` which lost the old contants: https://github.com/doctrine/dbal/blob/3.0.x/UPGRADE.md#deprecated-type-constants.

Cheers

**Comment by ChristophWurst** [comment]
Please note that we just merged a PR with our own constants for the types, so the app can be fully independent of any 3rdparty libraries: https://github.com/nextcloud/server/pull/25089.

**Comment by marcelklehr** [comment]
> Please note that we just merged a PR with our own constants for the types, so the app can be fully independent of any 3rdparty libraries: nextcloud/server#25089.

Nice. I'm using Doctrine\DBAL\Schema\Table->changeColumn() in one of my migrations, though, and that requires a type instance, obtained with Type::getType():Type

**Comment by marcelklehr** [comment]
So, it works now, but I'm still dependent on DBAL's API

**Comment by ChristophWurst** [comment]
> So, it works now, but I'm still dependent on DBAL's API

Because the app supports a wider range of Nextcloud releases? That is a problem right now. Once the minimum version is 21 you can use the new constants safely.

**Comment by marcelklehr** [comment]
No, because I need to use DBAL\Types::getType() for Doctrine\DBAL\Schema\Table->changeColumn

**Comment by ChristophWurst** [comment]
Right. So the `Schema` and a few other types are still from Doctrine directly. We have to clean that up and replace with our own abstraction. You are totally right that you will need the Doctrine stuff for this right now.
