### ISSUE TITLE
Need Some Help with REST API

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#1391]
**Is your feature request related to a problem? Please describe.**
I lost some entries that are not exported yesterday. Fortunately it's not so many.

**Describe the solution you'd like**
Though we have REST API there, I have difficulty dealing with the password.
We have several methods, but I am not sure what if I put plaintext into crontab or a script.
```sh
curl --u user:password https://www.example.com/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark/export
```

**Describe alternatives you've considered**
- Some examples to keep passwords in crontab or the scripts safe.

**Additional context**

**Comment by tflidd** [comment]
Well, I use the password, but you can easily save the database with a cronjob on a daily bases. This saves you for similar trouble with any app:

```
 mysqldump -u root -pmy_password -a nextcloud | gzip > /ncdata/dbbackup/NC-$(date +'%a').sql.gz
 #restore:
 #mysql -u user -p databse < file.sql
```

and if you prefer an app, use the backup app: https://apps.nextcloud.com/apps/nextbackup
I wouldn't implement backup solutions for each app individually.

**Comment by hashashin1191** [comment]
> Well, I use the password, but you can easily save the database with a cronjob on a daily bases. This saves you for similar trouble with any app:
> 
> ```
>  mysqldump -u root -pmy_password -a nextcloud | gzip > /ncdata/dbbackup/NC-$(date +'%a').sql.gz
>  #restore:
>  #mysql -u user -p databse < file.sql
> ```
> 
> and if you prefer an app, use the backup app: https://apps.nextcloud.com/apps/nextbackup
> I wouldn't implement backup solutions for each app individually.

Thanks a lot. I used
```sh
wget --user=user --password=password https://www.example.com/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark/export
```
Which causes exposure if a user
```sh
ps -a | grep bookmarks
5742 user    0:00 wget --user=user --password=password https://www.example.com/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark/export
```

And mysqldump is safer.
```sh
ps -a | grep mysqldump
7792 user    0:00 mysqldump -u user -px xxxxxxxxxxxxx nextcloud
```

**Comment by hashashin1191** [comment]
> Well, I use the password, but you can easily save the database with a cronjob on a daily bases. This saves you for similar trouble with any app:
> 
> ```
>  mysqldump -u root -pmy_password -a nextcloud | gzip > /ncdata/dbbackup/NC-$(date +'%a').sql.gz
>  #restore:
>  #mysql -u user -p databse < file.sql
> ```
> 
> and if you prefer an app, use the backup app: https://apps.nextcloud.com/apps/nextbackup
> I wouldn't implement backup solutions for each app individually.

Thanks a lot. We have several methods, but I am not sure what if I put plaintext into crontab or a script.
```
curl --u user:password https://www.example.com/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark/export
```
