### ISSUE TITLE
Open bookmark, but stay in the Nextcloud Bookmarks tab

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1415]
**Is your feature request related to a problem? Please describe.**
I would like to be able to control what happens when I click on a bookmark.
At the moment when I click on a bookmark, it opens a new tab, and I'm move to that the new tab.
I've to go back to the tab with NC bookmarks, to open another bookmark, etc until all the bookmarks are opened that I want to be open.

**Describe the solution you'd like**
Add the possibility to use "the other mouse button", and provide the possibility to open in a new tab (perhaps in new window too).

This way it will be easy to open multiple bookmarks easily and quickly.

**Describe alternatives you've considered**
Make the behavior configurable for the user.

**Comment by marcelklehr** [comment]
I think opening a tab in the background is not possible with javascript, but you can open multiple bookmarks at once, by selecting them in the app and then clicking on "Open all" in the selection options.

**Comment by radoeka** [comment]
> I think opening a tab in the background is not possible with javascript, 

That still leaves an small opportunity that it might be possible.  Perhaps you discover how it can be done sometime in the future, or perhaps someone that encounters this request know how to do it.

> you can open multiple bookmarks at once, by selecting them in the app and then clicking on "Open all" in the selection options.

This works rather well, almost as nice as opening a bookmark in the background.  
It's a hidden pearl, I would say.

**Comment by marcelklehr** [comment]
This [link](https://stackoverflow.com/questions/10812628/open-a-new-tab-in-the-background) seems to be an exhaustive resource of approaches to this problem. However, none of them work reliably and across browsers.

Thus I'm sorry to be closing this issue as won't fix.

**Comment by radoeka** [comment]
Okay, thanks for your support.  It seems to work with mouse middle click.  This way the page opens in another tab, but I'm not transferred to the tab.
