### ISSUE TITLE
The bookmarklet is too small, when saving bookmark from browser menu bar

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1417]
**Describe the bug**
The bookmarklet is too small.
With bookmarklet I mean the window that pops up, when a bookmark is saved.

**To Reproduce**
Steps to reproduce the behavior
1. Save a bookmark with the bookmark "javascript:(funtion(){var" in the browser menu bar.
2. A window pops up, to add information about the bookmark
3. Current window:

![image](https://user-images.githubusercontent.com/2937666/107424761-55f14c00-6b1e-11eb-9afe-acf988f14696.png)

The button 'save' (opslaan) at the bottom of the window misses :(
(to be clear: when scrolling down, the button becomes visible.  But the scrolling should not be needed, in case the popup is shown fully)

**Expected behavior**
The popup window should always show itself completely.  
Including the button 'save' (opslaan) at the bottom of the window:

![image](https://user-images.githubusercontent.com/2937666/107424682-3fe38b80-6b1e-11eb-8b42-9d00ad502c58.png)

**Desktop (please complete the following information):**
 - OS: Windows + Linux
 - Browser: Chrome
 - Version: 88

**Server (please complete the following information):**
 - OS: openSUSE 15.2
 - HTTP server: Apache
 - Database: sqlite3
 - PHP version: 7.4
 - Nextcloud version: 20.0.7
 - Bookmarks app version: 4.0.8

**Comment by radoeka** [comment]
This is an easy one to fix.  Just change the height value from height=500px to height=650px in the bookmark url.

**Comment by radoeka** [comment]
I think that the following change may work, please review and and when blessed ok submit it, please:

```
apps/bookmarks/src/components # diff -u /var/tmp/bookmarks_src_components_Settings.vue Settings.vue
--- /var/tmp/bookmarks_src_components_Settings.vue      2021-03-28 10:09:53.069424300 +0200
+++ Settings.vue        2021-03-28 10:10:19.796928379 +0200
@@ -122,7 +122,7 @@
                bookmarklet() {
                        const bookmarkletUrl
                                                = window.location.origin + generateUrl('/apps/bookmarks/bookmarklet')
-                       return `javascript:(function(){var a=window,b=document,c=encodeURIComponent,e=c(document.title),d=a.open('${bookmarkletUrl}?url='+c(b.location)+'&title='+e,'bkmk_popup','left='+((a.screenX||a.screenLeft)+10)+',top='+((a.screenY||a.screenTop)+10)+',height=500px,width=550px,resizable=1,alwaysRaised=1');a.setTimeout(function(){d.focus()},300);})();`
+                       return `javascript:(function(){var a=window,b=document,c=encodeURIComponent,e=c(document.title),d=a.open('${bookmarkletUrl}?url='+c(b.location)+'&title='+e,'bkmk_popup','left='+((a.screenX||a.screenLeft)+10)+',top='+((a.screenY||a.screenTop)+10)+',height=650px,width=550px,resizable=1,alwaysRaised=1');a.setTimeout(function(){d.focus()},300);})();`
                },
                viewMode() {
                        return this.$store.state.settings.viewMode

```

**Comment by marcelklehr** [comment]
Could you open a PR for this? :heart:

**Comment by radoeka** [comment]
I've no idea how (to create a pull request.  I used the code from the app inside nextcloud).  I hoped that you could coy and paste the piece of code above and patch it, with:
`patch diff file`

**Comment by marcelklehr** [comment]
That's fine, I'll make the change myself, then. Thank you for investigating! :heart:
