### ISSUE TITLE
Database runs into deadlock by wrong query

### ISSUE THREAD

**Issue by vatolin** [nextcloud/bookmarks#1430]
My hosting provider has informed me about an issue probably caused bei Bookmarks app. The issue triggers the Postgres database to fill all disk space available. Obviously there is a problematic query by Bookmarks app as follows:

```sql
SELECT "b"."id", "b"."url", "b"."title", "b"."description", "b"."lastmodified", "b"."added", "b"."clickcount", "b"."last_preview", "b"."available", "b"."archived_file", "b"."user_id", array_to_string(array_agg("tree"."parent_folder"), ',') AS "folders", array_to_string(array_agg("t"."tag"), ',') AS "tags"
FROM "oc_bookmarks" "b"
LEFT JOIN "oc_bookmarks_tree" "tree" ON b.id =tree.id AND tree.type = $1
LEFT JOIN "oc_bookmarks_tags" "t" ON "t"."bookmark_id" = "b"."id"
LEFT JOIN "oc_bookmarks_tree" "tr" ON tr.id = b.id AND tr.type = $2
LEFT JOIN "oc_bookmarks_shared_folders" "sf" ON "tr"."parent_folder" = "sf"."folder_id"
LEFT JOIN "oc_bookmarks_tree" "tr2" ON tr2.id = tr.parent_folder AND tr2.type = $3
LEFT JOIN "oc_bookmarks_shared_folders" "sf2" ON "tr2"."parent_folder" = "sf"."folder_id"
WHERE ("b"."user_id" = $4) OR ("sf"."user_id" = $5) OR ("sf2"."user_id" = $6)
GROUP BY "b"."id", "b"."url", "b"."title", "b"."description", "b"."lastmodified", "b"."added", "b"."clickcount", "b"."last_preview", "b"."available", "b"."archived_file", "b"."user_id", "b"."id"
ORDER BY "b"."lastmodified" DESC, "b"."id" ASC LIMIT 300
```

This query probably runs into some deadlock and stops only when the server memory is full. The server space is full because PostgreSQL creates temporary files for the query results, so called tablespaces. In this specific case, in these GB-sized temporary files, as far as can be seen, there is actually only this URL: https://www.gdv.de/resource/blob/21430/d2bc574878122808a0bb6aa1c3f88b69/pdf---text-des-uebertragungsabkommens-inkl--der-antragsformulare-data.pdf

**Server (please complete the following information):**
 - OS: Debian 11.10
 - HTTP server: Apache
 - Database: Postgres 11.10
 - PHP version: 7.4.15
 - Nextcloud version: 20.0.7
 - Bookmarks app version: 4.0.8
 - Activated Nextcloud Apps: 
 
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.4
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - flowupload: 1.1.2
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 1.7.5
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - bookmarks
  - encryption
  - files_external
  - files_fulltextsearch
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - user_ldap

 - Nextcloud configuration:
 
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.glombit.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.7.1",
        "overwrite.cli.url": "https:\/\/www.glombit.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "sendmail",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "mail_smtpauthtype": "LOGIN"
    }
}

 - Nextcloud external user backend: Floccus

**Comment by marcelklehr** [comment]
I have asked other devs for help on this as I cannot replicate it, and it seems to be a known problem without a solution, atm :/
