### ISSUE TITLE
Cannot reload Thumbnail of YouTube Screenshot

### ISSUE THREAD

**Issue by skoelzow** [nextcloud/bookmarks#1433]
**Describe the bug**
Once the DefaultBookmarkPreviewer returns an image, it is not possible to reload that image later. Even delete and create does not help.

**To Reproduce**
1. Assume: no explicit previewer is defined.
2. Create a bookmark linking to your own YouTube clip
3. the DefaultBookmarkPreviewer fetches its Thumbnail. 
4. Change the Thumbnail of this video clip
5. The old Thumbnail does not change. I tried to reload the page, reenter the url, delete browser cache, delete and recreate the whole bookmark.
6. Only when I manually delete the cache folder in nextcloud/data/appdata_xyz/bookmarks/ and reload the page the new thumbnail will be shown.

**Expected behavior**
When the url is reentered the BookmarkPreviewer should overwrite the internal cache

**Screenshots**
Reenter the url:
![grafik](https://user-images.githubusercontent.com/79085487/109137711-cc668e80-7759-11eb-88d3-0e65aa8b5fb9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 86

**Server (please complete the following information):**
 - OS: Debian 10
 - HTTP server: apache 2.4.38
 - Database: MySQL 5.7.32
 - PHP version: 7.4.15
 - Nextcloud version: 20.0.7
 - Bookmarks app version: 4.1.0
 - Activated Nextcloud Apps: [applist.txt](https://github.com/nextcloud/bookmarks/files/6042222/applist.txt)
 - Nextcloud configuration: [systemconfig.txt](https://github.com/nextcloud/bookmarks/files/6042225/systemconfig.txt)
 - Nextcloud external user backend: none

**Additional context**
none
**Web server error log**
no errors generated

**Comment by marcelklehr** [comment]
Hey @skoelzow 

This may be a problem with a video that the user created themselves, but usually images of websites do not change very often. The app's background crawler recaptures images every two months, which should be sufficient, in my opinion.

I'm closing this as won't fix.
