### ISSUE TITLE
"Failed to load children order" error and no bookmarks after upgrade from 4.0.5 to 4.1.0

### ISSUE THREAD

**Issue by lookshe** [nextcloud/bookmarks#1453]
**Describe the bug**
After an upgrade to version 4.1.0 I am not able to list any bookmarks or use the app in webbrowser. Using the rest api through an android app works fine.
I can see an 404 on https://.../apps/bookmarks/folder/1/publictoken and later some unauthorized (401) requests.
Also there is some error in console log.

**To Reproduce**
1. Open the "bookmarks app" in browser.

**Expected behavior**
App listing the existing bookmarks.

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - Browser: Chrome, Vivaldi, Firefox

**Server (please complete the following information):**
 - OS: Debian Wheezy
 - HTTP server: Apache 2.2
 - Database: MariaDB 10.3
 - PHP version: 7.4
 - Nextcloud version: 20.0.8
 - Bookmarks app version: 4.1.0
 - Activated Nextcloud Apps:
```
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - apporder: 0.12.0
  - bookmarks: 4.1.0
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - cookbook: 0.8.3
  - dav: 1.16.2
  - deck: 1.2.5
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_texteditor: 2.14.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - metadata: 0.13.0
  - news: 15.3.2
  - notes: 4.0.4
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.6
  - support: 1.3.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0

```
 - Nextcloud configuration:
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.sl-its.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.sl-its.de",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 1,
        "theme": "",
        "maintenance": false,
        "minimum.supported.desktop.version": "1.3.0",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    }
}
```
 - Nextcloud external user backend: none

**Browser log**
```
bookmarks-main.js?v=f9a6005c-0:7 TypeError: Cannot read property 'focus' of undefined
    at i.mounted (bookmarks-main.js?v=f9a6005c-0:615)
    at Re (bookmarks-main.js?v=f9a6005c-0:7)
    at qt (bookmarks-main.js?v=f9a6005c-0:7)
    at Object.insert (bookmarks-main.js?v=f9a6005c-0:7)
    at w (bookmarks-main.js?v=f9a6005c-0:7)
    at En.__patch__ (bookmarks-main.js?v=f9a6005c-0:7)
    at En.e._update (bookmarks-main.js?v=f9a6005c-0:7)
    at En.s (bookmarks-main.js?v=f9a6005c-0:7)
    at un.get (bookmarks-main.js?v=f9a6005c-0:7)
    at new un (bookmarks-main.js?v=f9a6005c-0:7)
```

**Comment by marcelklehr** [comment]
Hello @lookshe 
I'm sorry for your troubles and sorry for the delay on my part.

What are the URLs of the unauthorized (401) requests? Are there any errors in the nextcloud log?

> TypeError: Cannot read property 'focus' of undefined

This is likely unrelated.

**Comment by lookshe** [comment]
Hello,

the requests are:
```
apps/bookmarks/folder/-1/childorder
apps/bookmarks/bookmark?limit=42&page=0&sortby=lastmodified&folder=-1
apps/bookmarks/settings/viewMode
```

I don't know why, but sometimes it seems to work fine. Of course not, when having debug tools open.

When the error/message occurs and I repeatly click on "Bookmarks", after a few clicks, I get to the login mask of nextcloud. Perhaps this could be an issue due to session problems.
I had similar behaviour with another web application using Acpu to store the user sessions. The server uses fcgi processes to handle requests to PHP and spawns multiple processes depending to the number of requests. Due to not sharing Acpu store throughout processes, not every process had a valid user session.

I will try to change the local caching to redis to validate this behaviour.

**Comment by lookshe** [comment]
Hello,

nothing changed after switching to Redis for local caching.

And there are also no messages in nextcloud log.

**Comment by marcelklehr** [comment]
Mmh, that looks like the 401 responses are not the actual problem, but due to some event, possibly due to a server-side error, you are logged out.

**Comment by marcelklehr** [comment]
Could you not find any errors in the nextcloud log?
