### ISSUE TITLE
Installation of bookmarks app failed on Nextcloud V21

### ISSUE THREAD

**Issue by zahlenhexe** [nextcloud/bookmarks#1455]
**Describe the bug**
It is the same behavior as discribed in #1404 

**To Reproduce**
Installation via frontend and with occ app:install bookmarks failed with error: 

`Error: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_bookmarks_shared_folders' doesn't exist`

It is a fresh install without old userdata/db tables. I updated Nextcloud to v21.0.0 final and tried to install bookmarks  v4.1.0 

**Desktop:**
    - OS: Archlinux
    - Browser: Firefox
    - Version: 86

**Server:**
 - OS: Archlinux
 - HTTP server: nginx/1.18.0
 - PHP 8.0.1 (cli)
 - Database: mysqlnd 8.0.1
 - Nextcloud 21.0.0
 - Bookmarks app version: v4.1.0 Latest

**Comment by marcelklehr** [comment]
Mmmh, have you had the bookmarks app installed before? (and perhaps removed the tables by hand?)

**Comment by zahlenhexe** [comment]
thanks for the reply

I just installed the app as described in #1404 (v4.0.8) and removed it with occ. Is it possible to create the tables by hand? I couldn't find a schema in the code for the tables that I could use as sql statement.

I can also try to copy tables from old install (v16, bookmarks 2.3.4) but in this version folder sharing is not implemented yet. 
I also tried to install the app with the package manager (pacman -S nextcloud-app-bookmarks) after it didn't work via web and occ without  success.

**Comment by marcelklehr** [comment]
You can try getting rid of all traces of the app as follows: https://github.com/nextcloud/bookmarks/wiki/Removing-all-traces-from-DB

**Comment by marcelklehr** [comment]
Let me know if that works :)

**Comment by zahlenhexe** [comment]
&#128077; &#128077;

`delete from oc_migrations where app = 'bookmarks';`

That's the solution. All tables were not available 

`#1051 - Unbekannte Tabelle 'nextcloud.oc_bookmarks'`

Many Thanks you made my day
