### ISSUE TITLE
Reorder selected bookmarks menu

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1465]
**Describe the bug**
The "multiple bookmarks selected" menu could use a different order.
Where more intrusive items are located at the bottom of the menu.

**To Reproduce**
1. Select multiple bookmarks
2. Go to the popping up menu
3. Scroll down over the menu to select some of the entries located at the bottom of the mm
4. Now the tag selection dropdown menu pops up (unwanted, the box is sensitive)

Current menu order.  

![image](https://user-images.githubusercontent.com/2937666/111066194-fb9d2f80-84bd-11eb-9254-75ec80ca4142.png)

When trying to "open all selected' the tag entry is triggered, and covers the other items in the menu :(

![image](https://user-images.githubusercontent.com/2937666/111066098-99dcc580-84bd-11eb-9dd7-0cec4241c37e.png)

**Expected behavior**
Undisturbed possibility to select any of the menu items.

The tags entry disturbs.  The Remove/Delete selection is destructive.
Would be could to locate those who entry near the bottom of the menu.

Preferred order:
Open 

1. All selected (probably the most used)
2. Select all
3. Move selected
4. Cancel selected
5. Remove/Delete selected (at the bottom so, it is very likely not touch when any of the above entries is selected)
6. Edit tags of selection  (the drop down menu does not cover any of the entries now)

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows + Linux
 - Browser: Chrome 
 - Version: Recent: 85 or so

**Server (please complete the following information):**
 - OS: opensuse
 - HTTP server: apache
 - Database: sqlite
 - PHP version: 7.4
 - Nextcloud version: 20.0.8
 - Bookmarks app version: Most recent 4.3

**Comment by marcelklehr** [comment]
Hey @radoeka 

Thanks for all your feedback! I really appreciate your input!

I've talked with the design team about this, an have overhauled the bulk edit menu as part of #1474:

The menu is now located on the left of the tool bar and entries have the following order:

1. Open selected
2. Move selected
3. Edit tags
4. Delete selection
5. --
6. Select all
7. Cancel selection

I agree that the tag picker inside the menu is currently a bit awkward, but I am confident that this component will be improved upon to avoid the hover effect you mentioned. Moving the delete entry to the bottom is a good move, I think. I'd rather leave the selection controls (as opposed to selection actions) separated by a line, at the bottom, to make the semantic difference clear.

**Comment by marcelklehr** [comment]
btw, I'd also love to hear feedback on your experience with floccus, if you'd like to share. (Preferably in a new issue in https://github.com/floccusAddon/floccus then :wink: )

**Comment by radoeka** [comment]
Thanks for you extensive explanation.  Appreciated.

Floccus is doing fine at the moment :)  I've syncing acros 3 different browser, and sofar so good.
