### ISSUE TITLE
Local file reference (with file://) can not be stored as bookmark in web gui

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1468]
**Describe the bug**
Local file reference (with file://) can not be stored as bookmark in web gui

**To Reproduce**
1. Have an html file on your local disk
2. Double click this html file so it opens in your browser
3. Select the link from the browser url bar, the one starting with file://user/<user>/etc/.....html
4. Use this link in the Nextcloud bookmarks web GUI to create a bookmark.
5. Click "+" in the NC bookmark GUI application, fill in the form (save it)
6. The file:// is now prepended with https://file:// and this can not be changed.

**Expected behavior**
The file:// bookmark is saved unchanged so it just works

**Screenshots**
NA.

**Desktop (please complete the following information):**
 - OS: NA
 - Browser: NA
 - Version: NA

**Server (please complete the following information):**
 - OS: openSUSE_15.2 (NA)
 - HTTP server: Apache (NA)
 - Database: sqlite3
 - PHP version: 7.4
 - Nextcloud version: 20.0.8
 - Bookmarks app version: 4.1.0
 - Activated Nextcloud Apps: NA

**Context**
The bookmarks are shared with floccus on the various browser.  The html file of course too, using Nextcloud (same location).  As such it is useful to have this fille:// reference stored as bookmark and shared among various browsers.

**Comment by HouraisanNEET** [comment]
A similar issue happens if trying to save ``chrome://dino/``.
It becomes ``http://chrome://dino/`` with URL of ``http://chrome//dino/``.

**Comment by leeand00** [comment]
I too would like to see this functionality.

**Comment by marcelklehr** [comment]
@leeand00 Please use thumbs-up/down emojis on the original post, rather than adding a comment.

**Comment by marcelklehr** [comment]
Ah, yes. Well spotted :)

**Comment by marcelklehr** [comment]
I think this is a security measure by browsers. Nothing I can do. :/

**Comment by radoeka** [comment]
> I think this is a security measure by browsers. Nothing I can do. :/

Ah, that might be.

However, when I save the file as a bookmark in my browser it works -> it opens the file.
Does it mean it is prevented by php or javascript?

Is it possible to put a note somewhere, telling the user that the bookmark can not be opened and must be copy and pasted into the browser.  Something like that?

**Comment by marcelklehr** [comment]
> However, when I save the file as a bookmark in my browser it works -> it opens the file.

You mean, if you create a file: URL bookmark in your browser you can open it from your browser UI? That's expected. But the browser prohibits opening links to file: URLs that appear inside web pages like nextcloud bookmarks.

> Is it possible to put a note somewhere, telling the user that the bookmark can not be opened and must be copy and pasted into the browser.

Yeah, that may be a good idea
