### ISSUE TITLE
Can not store the java bookmark applet

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1469]
**Describe the bug**
Bookmarks comes with its own java bookmarkapplet.
Bookmarks can be shared with Floccus with various Browsers.
For this reason, it is convenient to have this bookmark applet stored as a bookmark in the bookmark application.

However, the bookmark could be stored locally (for example as a Chrome bookmark), but the bookmark does not end in the Bookmarks app, when shared via Floccus.

It is not possible to add the applet as a bookmark in the bookmark weg GUI app, using the "+" sign.

**To Reproduce**
1. Have Floccus up and running
2. Save the bookmarks java bookmarkapplet as a bookmark within one of the Floccus bookmark folders
3. The bookmarksapplet works locally
4. The bookmark does not become available in the bookmarks web GUI.
5. When creating the bookmark via the web GUI, an error message is shown: "Failed to create bookmark"

**Expected behavior**
I expect that the bookmarkapplet can be saved as a bookmark, so it is automatically shared to other browsers when Floccus is used.

**Server (please complete the following information):**
 - Database: sqlite3
 - PHP version: 7.4
 - Nextcloud version: 20.0.8
 - Bookmarks app version: 4.1.0

**Comment by marcelklehr** [comment]
> Bookmarks can be shared with Floccus with various Browsers.
> For this reason, it is convenient to have this bookmark applet stored as a bookmark in the bookmark application.

I don't quite follow as the bookmarklet and floccus are two alternative ways to add bookmarks as I see it. Why would you need the bookmarklet if you have floccus?

Generally the bookmarks app currently doesn't support javascript bookmarks as reported in #832

**Comment by radoeka** [comment]
When I use floccus, the bookmarks are somehow not correctly synced to the server.  The bookmark saved in floccus, disappears :(
For this reason I used the bookmarklet.   I use it as much as I can, to save bookmarks with tags.  That way I can easily find them in the Nextcloud GUI.  That gives me 2 possibilities to find bookmarks: via folders and tags.

For me floccus doesn't exclude the bookmarklet, or the other way around.  It is nice and convenient at the same time, to have them both around.

#832 reported it already.  It would be convenient to have be able to add bookmarks via the bookmarklet, stored in a folder in floccus as this gives the same bookmark layout in various browser :)

**Comment by marcelklehr** [comment]
>  The bookmark saved in floccus, disappears :(

Oh no. Could you open a ticket over at https://github.com/floccusAddon/floccus so I can have a look?

> #832 reported it already. 

Then let's close this ticket in favor of the older one :)
