### ISSUE TITLE
Verify the OCS ID

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/bookmarks#147]
The current entry of the ocsid is `166042` in all branches:
https://github.com/owncloud/bookmarks/blob/master/appinfo/info.xml#L10
https://github.com/owncloud/bookmarks/blob/stable8/appinfo/info.xml#L10
https://github.com/owncloud/bookmarks/blob/stable7/appinfo/info.xml#L11

However that app is only for oC 7: https://apps.owncloud.com/content/show.php?content=166042
oC 8.0 (and later**?**) should use `168710`: https://apps.owncloud.com/content/show.php?content=168710

This causes problems, when people try to enable the app from the recommended section rather then the disabled section: https://github.com/owncloud/core/issues/16092

Manually changing the ocsid resolves the issue.

**Comment by binarykitchen** [comment]
the problem is still here, i cannot enable the bookmarks app, error `"App directory already exists"` still appears

**Comment by blizzz** [comment]
For 8.1 I will do a new release / app on the appcenter and provide it a dedicated ID.

**Comment by blizzz** [comment]
not relevant anymore
