### ISSUE TITLE
What does the button 'Install on home screen' exactly do?

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1482]
**Describe the bug**
'Install on home screen' possibility is unclear (to me.  Even after peeking at the code)

**To Reproduce**
1. Go to https://<fqdn>/apps/bookmarks/ select Settings in the left bottom corner
2. Find the button: Install on home screen
3. Wonder what will happen....

**Expected behavior**
A clear and concise description of what it will do.
Which home screen?  Nextcloud's home screen, in my the dashboard.  But there is already a bookmark widget, probably not.

The browser's home screen, but I already have a bookmarklet on my browser bookmark toolbar.  What's the use of the web-app in the browser's home screen.

Assuming it will add something like a URL to my browser's home screen, can I remove it easily?

I assume the URL will point to: https://<fqdn>/apps/bookmarks/

It would be nice when the above questions get answered, become immediately clear around the button 'Install at home screen' in the bookmarks setting area ( include a link to a help page that shows what is going to happen and the final result.  that would be nice).

**Screenshots**

![image](https://user-images.githubusercontent.com/2937666/112746809-a24ef900-8fb1-11eb-8e3a-824df6da1325.png)

**Comment by marcelklehr** [comment]
Good point! This is web feature mainly useful for use on mobile. [MDN has more information](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen):

> Add to Home screen (or A2HS for short) is a feature available in modern browsers that allows a user to "install" a web app, ie. add a shortcut to their [operating system] Home screen representing their favorite web app (or site) so they can subsequently access it with a single tap. This guide explains how A2HS is used, and what you need to do as a developer to allow your users to take advantage of it.

Maybe you are able to come up with a useful description that we could put above that button?
