### ISSUE TITLE
Bookmarklet Doesn't Work on Firefox Android

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#1485]
**Describe the bug**
The bookmarklet (or other javascript in URL bar) feature in newer Firefox-based Android browsers have been dropped.
mozilla-mobile/fenix #2871

**To Reproduce**
1. Open Bookmarks and click on "Settings".
2. There is no way to drag the bookmarklet button.
3. Manually copy the button and paste it to the URL bar (Redirected to the search engine).
4. Manually add it to the bookmarks and click it (Blank page).

**Expected behavior**
The bookmarklet pops up in old Firefox Android. Chromium-based browsers work as well.

**Client:**
Firefox Android 87.0.0-rc.1
Fennec F-Droid 86.1.1

**Comment by marcelklehr** [comment]
Thanks for the heads-up. That's sad. I can't do anything about that, however.
