### ISSUE TITLE
Help test RC1 of the new release!

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#1509]
Hello there,

I've been busy since the last release in febuary: getting together with the design team to find rough edges as well as conducting a basic usability study of the bookmarks app to identify UX problems.
The result is the upcoming v4.2.0, which brings the improvements listed below. To help test the release you can download the tarball of the release candidate [here](https://github.com/nextcloud/bookmarks/releases/download/v4.2.0-rc.1/bookmarks-4.2.0-rc.1.tar.gz).

### New 
 - UX: Implement drag and drop for moving items
 - UI: Add visual indicators for sharee privileges
 - UX: Add note for admins if scraping is disabled
 - UX: Allow dragging bookmarks onto tags
 - UX: Allow creating new tags in main menu (optimistically)
 - UX: Optimistically add bookmark to list when creating
 - UI: Move Sort order from settings to Controls
 - Dashboard: Add 'frequent bookmarks' widget
 - Implement full-text archiving of HTML pages

### Fixed
- Updated translations from transifex :hearts:
- Authorizer: Check token first, then check user credentials
- BookmarkService: Keep tags when moving across share boundaries
- Migration: Ensure all tables have primary key
- CrawlJob: Set some time and size limits for archiving content
- Fix: Recover from multiple root folders
- Fix OrphanedTreeItemsRepairStep: Reinsert lost bookmarks instead of deleting them
- UI: Display archived content in full-page overlay
- UI: Change "Archived" to "Files" menu entry (+new icon)
- UX: Refactor and improve folder picker
- UX: Bookmarklet: Adjust window height
- UI: Remove frustrating paddings from Item.vue
- UI: Don't cover bookmark titles when there's many tags
- UX: Don't display spinners for the first 500ms
- UX: Improve speed of moving items
- UX: Make sharing visible in folder menu
- UX: Move BulkEditing to the left
- UI: Fix getPermissionsForFolder

Stay safe in your personal stratosphere :cloud:

**Comment by marcelklehr** [comment]
Also let me know if you've had time to do some testing and haven't found anything :)

**Comment by radoeka** [comment]
I installed this version (4.2.0) as it was released recently.

After this I was no longer able to create bookmarks via the bookmarklet (others reported the same issue, see #1537 and I was not able anymore to create bookmarks via the Nextcloud web GUI.  In others words I could not create bookmarks anymore.

I restored bookmarks 4.1.0 as well as the database from backup!  That gave some issues, but I looks like I'm now able to create bookmarks again...

**Comment by marcelklehr** [comment]
@sunjam you could

0. Make a backup
1. move the duplicate folders into two separate folders, so you have two complete trees.
2. Then create sync accounts for both folders in floccus,
3. sync them down into your browser
4. switch one account to sync with the other folder
5. It will merge the two trees
6. check everything
7. Remove the second folder that is not synced anymore

**Comment by marcelklehr** [comment]
@radoeka Could you open a new issue for this?
