### ISSUE TITLE
"Archived" Bookmarks not working & duplicated entries duo to this?

### ISSUE THREAD

**Issue by EngelPika32** [nextcloud/bookmarks#1510]
**Describe the bug**
Hello, I just added a pdf as a bookmark and hoped for it to be automatically saved (archived), but nothing happened.
I then added the bookmark from the web-UI within the "Archived" label again (I thought, maybe I have to tell it explicitly), this over-wrote the existing bookmark with all the added information. "Archived" is still empty. Additionally, the bookmark exists now twice. Editing one edits both.

**To Reproduce**
1. Create a bookmark to a pdf (using bookmarklet; shouldn't matter)
2. Add a tag and place it into a dir
3. Go (WebUI) to the bookmark app and view "Archived" – (it's empty in my case; clean install; 5 bookmarks in total).
4. Add the bookmark here again (Plus Icon in the top left)
5. View weird behavior/reload (prop. duo to tag-removal) – "Archived" is still empty or empty again
6. View "All bookmarks" again; View your folder.

**Expected behavior**
- Download the pdf into personal space after adding it the first time
- Do not overwrite/re-create already existent bookmarks/links
- Explain better (looking at the empty "Archived screen") when pdfs/images are saved (does it check for new bookmarks every 5 minutes or at creation? Do I have to set specific settings as admin in the app settings to use this feature?)

**Screenshots**
Will add on request/if needed.

**Desktop (please complete the following information):**
*Unrelated in my opinion, will extend on request.*
Chrome – 90

**Server (please complete the following information):**
 - Database: MariaDB / mysql
 - PHP version: 7.4.16 – latest nextcloud-docker-conatiner
 - Nextcloud version: 21.0.1 – latest nextcloud-docker-conatiner
 - Bookmarks app version: 4.1.0

**Additional context**
I'm confused about the "Archived" feature. 
- When does it work/download? Can I limit the downloads or are they even limited by default? (ex.: "pls. don't download a 500MB pdf when I only have 1GB space left" – hypothetically)
- Must I activate the "privacy" settings from admin control to use the "achieved"-feature? [If yes, why isn't there a separate option for pdf/images?]

**Web server error log**
? Installed from nextcloud app-store; if you mean your API.
If you mean the proxy server then I'd have to look at it later (if needed).

**Nextcloud log (nextcloud/data/nextcloud.log)**
Nothing related to this app (no new logs).

**Browser log**
Nothing interesting I guess. A bunch of "caching" logs and even more deprecated warnings because of  `@nextcloud/moment`.
```
bookmarks-main.js?v=52f99417-4:7 
TypeError: Cannot read property 'focus' of undefined
    at i.mounted (bookmarks-main.js?v=52f99417-4:615)

Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/folders/4".
    at we (https://nextcloud.bilua.de/custom_apps/bookmarks/js/bookmarks-main.js?v=52f99417-4:615:16528)
```
The first error occurred multiple times, the latter one just once, and is as far as I can see unrelated.

**Comment by marcelklehr** [comment]
Hi @EngelPika32 

the app checks for new bookmarks every half hour. Bookmarking the same URL in multiple folders will link to the same bookmark in all folders.

**Comment by EngelPika32** [comment]
Hi @marcelklehr ,

I added the bookmark originally hours ago and stopped my work due to a call. I then saw the empty "Archived" label after the call, which went on for over an hour. So, it has to be smth. else, or?

Additionally, it might be good to have a notice about this check somewhere + to be able to edit this duration, I guess.

**Comment by marcelklehr** [comment]
> Nevertheless, there should have been a hint about the existing bookmark as it overwrote all existing things (tags, info, name etc) :/

That's indeed not how it should be. It should use the existing info.

> I then saw the empty "Archived" label after the call, which went on for over an hour

Can you check whether your background task (cron job) finished? This may be a similar problem as #1498

> Additionally, it might be good to have a notice about this check somewhere + to be able to edit this duration, I guess.

Good idea about adding a note how this works. I probably won't add an option for editing the duration, though -- if it's too long we can simply change it for everyone. I don't see why some people would want a different interval than others.

**Comment by EngelPika32** [comment]
> Can you check whether your background task (cron job) finished? This may be a similar problem as #1498

It just ran three minutes ago. So, I don't think this is the cause.

> I probably won't add an option for editing the duration, though -- if it's too long we can simply change it for everyone.

Sounds good. Thought, an extra button to manually start/perform the check might be good (for testing)[admin settings/panel]. I dunno whether the check can be performed only for a single user or not, then it could be available for all users (ex. to be used after you imported many bookmarks).

Some kind of option to archive/check a single bookmark immediately could be useful as well [user-option] (ex. to save some files and sync them for offline use before you are going somewhere).
(Should/May I create a new feature issue for this?)

**Comment by marcelklehr** [comment]
> It just ran three minutes ago. So, I don't think this is the cause.

Then we should find the cause. Is there anything in the nextcloud log? Is the URL you bookmarked reachable by the server that hosts your nextcloud?

> to be used after you imported many bookmarks
> to save some files and sync them for offline use before you are going somewhere

The idea is that any file URLs you bookmark are procedurally downloaded. This is done batch wise to not overload the server. IMHO, there's no need for a trigger if the feature works as intended. It might still be wise to add a note to users that they may have to wait for the background job.

**Comment by EngelPika32** [comment]
Yes, it's reachable, and there aren't logs related to this app besides the already shown above^ – which are from the browser console.

> [...] there's no need for a trigger if the feature works as intended.

IMHO, it's useful to immediately sync something for offline use shortly after adding. But it's understandable if the extra work might not be worth it as it's more of a niche/rare case.

\
To be certain, this doesn't matter, or?
> Must I activate the "privacy" settings from admin control to use the "achieved"-feature? [If yes, why isn't there a separate option for pdf/images?]

(One of the many questions from my initial message^)

**Comment by marcelklehr** [comment]
> Must I activate the "privacy" settings from admin control to use the "achieved"-feature?

Ah, yes, this does matter. Without enabling this, there is no network access for the app.

> If yes, why isn't there a separate option for pdf/images?

This is because it doesn't focus on features but on privacy. And for privacy it doesn't matter if you fetch a pdf from a different server or a normal webpage.

**Comment by EngelPika32** [comment]
> and for privacy 

Firstly, it would reduce the number of requests/accessed sites a lot (factor 100-1000).
Secondly, I may only bookmark pdf/images from some trusted sites? …

[Does the app re-check/fetch sites from time to time, or only when they are added/edited?]

**Comment by marcelklehr** [comment]
> Does the app re-check/fetch sites from time to time, or only when they are added/edited?

Yes, the app checks links once every few months.

> it would reduce the number of requests/accessed sites a lot

Is this a performance concern for you?

> Secondly, I may only bookmark pdf/images from some trusted sites?

That's your choice. Still, this is how the app works for now.

**Comment by EngelPika32** [comment]
> Is this a performance concern for you?

No, we're talking about privacy. And from my perspective, it does make quite a difference whether 10 or 1000 sites are accessed (every few months). 

Additionally, those links wouldn't have to be re-checked every few months, as you already saved them the first time.

Therefore, a separate option for pdfs and one for images would be useful.

**Comment by EngelPika32** [comment]
Thinking about that, I saw the option "when: bookmark created" in the flow integration. I'm not quite sure why you ever need to create a bookmark for a bookmark (as there is no option to, for example automatically change the folder and/or add a tag to the bookmark), but this gives some opportunity to manually handle things. 

Using the flow to check the URL for domain/subdomain (use existing regex functionality, just like for filenames) and then archive/allow archiving. With this, files could be downloaded immediately (or very soon) too as the flow triggers on ex. creation of a bookmark. Alternatively, I could check for tags instead of the URL, etc.
[Using a queue would be okay as well if this is easier to implement.]

**Comment by marcelklehr** [comment]
> a separate option for pdfs and one for images would be useful

I'm sorry, I'm not in favor of this at the moment.

> I'm not quite sure why you ever need to create a bookmark for a bookmark

The flow app doesn't know what makes sense and what doesn't so it offers you all possibilities.

> Using the flow to check the URL for domain/subdomain (use existing regex functionality, just like for filenames) and then archive/allow archiving. With this, files could be downloaded immediately (or very soon) too as the flow triggers on ex. creation of a bookmark.

Yes, this would be a good use of the flow integration. However, you would need an app that does the downloading.
