### ISSUE TITLE
Bookmarks from .URL and .webloc files

### ISSUE THREAD

**Issue by EngelPika32** [nextcloud/bookmarks#1511]
**Is your feature request related to a problem? Please describe.**
I have a bunch of .URL and .webloc files and it would be nice to import them.

**Describe the solution you'd like**
- When selecting these files, I'd like the option "add to bookmarks app" or smth. similar.
Existing tags and names should be taken on. 
Comments could be added as notes/plain-text; shares and project linking aren't supported afaik but should be used too – when the related support is added.
The "add bookmark" UI (like in the bookmarklet) could be shown as well for immediate editing of info/tags/sub-folder etc.
- Separate option for importing all these files within a folder (→selecting the root-dir would import all).
- Lastly, a separate option for automatic re-scanning (optional).

**Describe alternatives you've considered**
Searching for all these files and adding them one-by-one on a looong weekend? :dango: xD

**Comment by marcelklehr** [comment]
I understand the desire to easily migrate from the other bookmarks app, but this is not a priority for me personally. If you have some coding skills, there is an API for automating things like this: https://nextcloud-bookmarks.readthedocs.io

**Comment by marcelklehr** [comment]
Actually, come to think of it you may be able to use the flow integration of the bookmarks app for this. You would create a flow that creates bookmarks from URLs in all matched files, and make sure to match only .URL files.

**Comment by EngelPika32** [comment]
Wouldn't this create a bookmark to the file instead of a bookmark with the link from the file? 
(Besides, the flow would only be activated when I create a new .URL file or edit existing files afaik.)

**Comment by marcelklehr** [comment]
> Wouldn't this create a bookmark to the file instead of a bookmark with the link from the file?

Text files are parsed for links and those links are bookmarked. I'm not sure if URL files are detected as text files, but it's worth a shot, IMHO. Also, if it doesn't work directly, this would give a useful way forward: Adjusting flow integration to work with URL files.

> Besides, the flow would only be activated when I create a new .URL file or edit existing files afaik.

Indeed, but removing and re-adding those files would be easier to do than writing new code from scratch, I imagine.

**Comment by EngelPika32** [comment]
> I'm not sure if URL files are detected as text files, but it's worth a shot, IMHO.

It is and so I tried it, but without any luck. No new bookmarks were created.
Adjusting the flow integration for this would be great and might be pretty easy as these files are actually plain text.

> Indeed, but removing and re-adding those files would be easier to do than writing new code from scratch, I imagine.

I'm not quite sure what you mean by that. But using the flow would help a lot as I could simply add a tag to the files instead of reading them manually.

**Comment by marcelklehr** [comment]
Could you post a sample file here, so I can test this?

**Comment by EngelPika32** [comment]
Well, gitHub doesn't support these files.
But the content for .URL is literally just this:
```
[InternetShortcut]
URL=https://www.youtube.com/
```
And for .webloc it's XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>URL</key>
<string>https://www.youtube.com/</string>
</dict>
</plist>
```

**Comment by marcelklehr** [comment]
It seems the workflow has been broken for some time now, I'm only now getting to this. I've fixed it now and have successully scraped a URL from a URL file to the bookmarks app.
