### ISSUE TITLE
Outdated @nextcloud/webpack-vue-config

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/bookmarks#1520]
Please upgrade @nextcloud/webpack-vue-config to our latests config
Also consider the following configs:
- @nextcloud/babel-config

I also see you're using the latest @nextcloud/browserslist-config. Which is actually not supporting IE11. Official IE drop is scheduled for 22 and your min-version is 20. Just be aware of this :)

**Comment by marcelklehr** [comment]
Gnaaaa.

![image](https://user-images.githubusercontent.com/986878/116129127-09072580-a6ca-11eb-8f11-a20550985208.png)

> I also see you're using the latest @nextcloud/browserslist-config. Which is actually not supporting IE11. Official IE drop is scheduled for 22 and your min-version is 20. Just be aware of this :)

Oh. Is that noted on the respective README? That would be good.


Thanks for letting me know :)

**Comment by skjnldsv** [comment]
> Gnaaaa.
> 
> ![image](https://user-images.githubusercontent.com/986878/116129127-09072580-a6ca-11eb-8f11-a20550985208.png)

It's even easier to set it up now. But you're very very late behind (we're on v4 now :) )
See the readme there :wink: https://github.com/nextcloud/webpack-vue-config
