### ISSUE TITLE
Syncing failed with E018 after update to 4.2.0

### ISSUE THREAD

**Issue by Jolopu** [nextcloud/bookmarks#1536]
Update from 4.1.0 to 4.2.0 leads to:

Syncing failed with E018: Konnte nicht am Server authentifiziert werden.

Using lates Floccus 4.6.4 on Chrome. No settings were changed. Nextcloud is 21.0.1

Downgraded to 4.1.0 and everything is ok again.

**Comment by marcelklehr** [comment]
Thanks for reporting!
I can't reproduce this in my setup, but there was a change to the authentication service. I'll have a look.

**Comment by adhoc-post** [comment]
Same problem here:

Upgrading from 4.1.0 to 4.2.0 leads to failed sync: "E018: Authentifizierung fehlgeschlagen"

Server setup: Debian 10 Buster, Nextcloud 21.0.1, Bookmarks 4.2.0
Client setup 1: Debian 10 Buster, Firefox 78.10.0esr (64-Bit), Floccus 4.2.5
Client setup 2: Windows 10, Firefox 88.0, Floccus 4.6.0

In addition, syncing with Nextbookmark 1.14.0 on iPhone (iOS 14.5.1) fails (app aborts silently).

**Comment by marcelbader** [comment]
Same here after upgrade to Bookmarks 4.2.0 on Nextcloud 20.0.9 (web hosting with Red Hat Enterprise)

1. Client: Ubuntu 20.04 | Firefox 88.01 | Floccus 4.6.4 =  "E018: Konnte nicht am Server authentifiziert werden."
2. Client: Android Lineage 17.1 | Nextcloud Bookmarks (Fdroid: Biswajit Das) = "Verbindung fehlgeschlagen"

Downgrading Bookmarks to 4.1.0 not possible, runs into multiple error logs and auto enables maintenance mode (that's another issue)
