### ISSUE TITLE
Bookmarks 4.2.0 filling log with 404 responses

### ISSUE THREAD

**Issue by simonspa** [nextcloud/bookmarks#1539]
**Describe the bug**
Since the update to Bookmarks 4.2.0 yesterday, my Nextcloud log sees many many entries from the app concerning issues reaching bookmarked pages from users, like:

```
[bookmarks] Warning: Client error: `GET <URL>` resulted in a `404 Not Found` response:
<!DOCTYPE html>
<html lang="id-ID">

<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, in (truncated...)
```

or
 
```
[bookmarks] Warning: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for <URL>
```

I think there are two issues here:

* These errors should mark the links as unavailable (or "dead") as it used to, but should not end up in the server log imho.
* If messages like these are to end up in the log, their content should be redacted - I would not expect me (as administrator) to see bookmarks my users store in their private accounts in the NC log.

**To Reproduce**
1. Update to 4.2.0
2. Add a problematic link
3. Observe log

**Expected behavior**
Dead or unreachable bookmarks should not lead to NC server log entries.

**Server (please complete the following information):**
 - OS: Debian Buster
 - HTTP server: nginx
 - Database: MySQL
 - PHP version: 7.4
 - Nextcloud version: 21.0.1
 - Bookmarks app version: 4.2.0

**Comment by marcelklehr** [comment]
Thank you for your feedback! The reason these show up, is to allow admins to find out why some pages end up in the dead links section. I agree that 404s should probably not be logged, but all other errors should be logged in some way or another, IMHO.

**Comment by simonspa** [comment]
Hi @marcelklehr 

thanks for your swift response! I don't fully understand your answer - what type of error would be relevant to the administrator of an instance rather than the users themselves? Since these errors concern user data - shouldn't this always be only visible to the user rather than the administrator?

**Comment by marcelklehr** [comment]
The reason is that they may not be intelligible to the user and often caused by server configuration. If an admin has misconfigured SSL then page crawls may fail for reasons that the user doesn't know.

**Comment by marcelklehr** [comment]
Should be less noisy with v4.3.0
