### ISSUE TITLE
After installing Bookmarks-4.2.0 no longer possible to create bookmarks

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#1552]
**Describe the bug**
After installing Bookmarks-4.2.0 no longer possible to create bookmarks.

Initially I thought it was only not possible to create bookmarks via the bookmarklet.  Later I discovered that the possible workaround to create bookmarks via the NC web GUI didn't work either.

I solved it by restoring the previous version, including the restore of the database.
It was still possible to do this, but it is not easy...  As e.g. files were updated, and these had to be restored...

**To Reproduce**
1. Install version 4.2.0 from 4.1.0
2. Create a bookmark via the bookmarklet.  This is not working that is reported in another bug reported, and is in the meantime fixed.
3. Create a bookmark via the web GUI.  This is not working.  Initially reported in #1509, on request a new issue has been opened.

**Expected behavior**
After a upgrade, the old functionality should be available and working.

**Screenshots**
NA.

**Desktop (please complete the following information):**
 - OS: openSUSE-15.2
 - Browser: Various
 - Version: 4.2.0

**Server (please complete the following information):**
 - OS: openSUSE-15.2
 - HTTP server: apache2
 - Database: sqlite3
 - PHP version: 7.4
 - Nextcloud version: 20.0.9
 - Bookmarks app version: 4.2.0

* The version is no longer available.
*

**Comment by HouraisanNEET** [comment]
Is this related to #1537 and #1542 ?

**Comment by marcelklehr** [comment]
@HouraisanNEET I think it's not, as @radoeka wrote even the normal web UI for adding bookmarks doesn't work.

I cannot reproduce this off-hand, which likely means there's something specific about your setup.

Can you please provide
 - a browser log after the failed creation attempt
 - an excerpt of the nextcloud log after the failed creation attempt
 - An account of what happens visually in more detail than "no longer possible to create bookmarks"

Thank you :)

**Comment by radoeka** [comment]
I can't reproduce the issue anymore as I'm back at the old version.  I'll wait a couple (minor) versions, before I update again.
I tailed the log when the issue happened, but there is nothing else then 
  GET /index.php/apps/bookmarks/public/rest/v2/bookmark?folder=266&page=-1 
I've no browser log (don't know how to get it, btw)
In the browser there is a popup states that the bookmark is not created.  The exact msg (EN) is: "Failed to create bookmark".

**Comment by radoeka** [comment]
I just updated to 20.0.10, which the bookmarks app as well.  I can create bookmarks via the web GUI, as well as the bookmarklet.  As seems well so far :)  Thanks.
