### ISSUE TITLE
Folder title in breadcumb takes many lines

### ISSUE THREAD

**Issue by philippemilink** [nextcloud/bookmarks#1553]
Hello,

When visualizing the content of a bookmark folder, if the folder title contains spaces, the title is on many lines:
![image](https://user-images.githubusercontent.com/5911232/118409937-34f44600-b68d-11eb-8818-fec500aceedc.png)

The problem can be fixed by removing the CSS property `flex: 0;` of the CSS class `.controls__left`.

 - OS: Debian Sid
 - Browser: Firefox ESR 78.10.0
 - Nextcloud version: 21.0.1
 - Bookmarks app version: 4.2.0

**Comment by HouraisanNEET** [comment]
Similar to #1541?

**Comment by marcelklehr** [comment]
Yep, it's the same bug. Fixed already. Will do a release shortly.
