### ISSUE TITLE
Adding and importing works but exporting does not work.

### ISSUE THREAD

**Issue by gerroon** [nextcloud/bookmarks#156]
{"reqId":"5854d7a34f085c2676468232b36e792b","remoteAddr":"192.x.x.x","app":"PHP","message":"Class 'OCA\Bookmarks\Controller\Rest\OCA\Bookmarks\Controller\Lib\Helper' not found at \/var\/www\/owncloud8\/apps\/bookmarks\/controller\/rest\/bookmarkcontroller.php#242","level":3,"time":"2015-05-24T23:58:39+00:00"}

I also get this error

Too many redirects

It may be temporarily unavailable or moved to a new address. You may wish to verify that your internet connection is working correctly.

thanks

**Comment by thinking-aloud** [comment]
In OC 8.1 I get exactly this error. The Bookmarks Chrome extension uses the export url for some reason and it does not work, so I started looking.
A fix would be highly appreciated.

**Comment by pravussum** [comment]
Confirming that @alberanid fix is working.

**Comment by damko** [comment]
please close this ticket
