### ISSUE TITLE
When turned on, causes around 800 database ops/s per in spikes

### ISSUE THREAD

**Issue by dolohow** [nextcloud/bookmarks#1581]
**Describe the bug**
When bookmarks app is enabled, it causes a lot of requests to mariadb database, increasing binary log size significantly.

**To Reproduce**
1. Turn on app
2. Use app for syncing
3. Observe problem

**Expected behavior**
It shouldn't do so many requests, I don't think it's necessary

**Screenshots**
![image](https://user-images.githubusercontent.com/1408564/122600634-5d96a380-d070-11eb-8ae2-ae90e38a233e.png)

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - HTTP server: Apache
 - Database: Mariadb 10.3.29
 - PHP version: 7.4.3
 - Nextcloud version: 21.0.2
 - Bookmarks app version: 4.2.2
 - Nextcloud external user backend: none

**Web server error log**
There is a lot of those logs around 9 per second for about 10 seconds and its kinda linked to those spikes.  They happen in exactly same moment.
```
IP - User [18/Jun/2021:19:53:48 +0200] "GET /index.php/apps/bookmarks/public/rest/v2/folder/116/hash HTTP/1.1" 200 1782 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Edg/91.0.864.41"
```

**Comment by marcelklehr** [comment]
Do you have APCu enabled? It should cache a lot of these queries.

**Comment by dolohow** [comment]
Yes
```bash
$ grep APCu config/config.php
  'memcache.local' => '\\OC\\Memcache\\APCu'
```

anyway I think it should not make so much updates, hammering database

**Comment by marcelklehr** [comment]
Sorry for the delay. I'm not sure if the syncing causes those UPDATE queries if nothing changes in your bookmarks. It may be the CrawlJob that fetches bookmark metadata from the bookmarked sites. Can you find out what those queries are?

**Comment by dolohow** [comment]
How can I do that? I posted apache logs but that is all I have for now...

**Comment by marcelklehr** [comment]
Are all those queries triggered by the `hash` endpoint? I think that's rather unlikely, as it shouldn't make any UPDATEs. Any other endpoints?

**Comment by dolohow** [comment]
I think they were all `hash` endpoints.  This is why I only put in description one.  Since there was no point.

However, I only keep logs for one month and I turned on yesterday bookmarks app and I can't reproduce it. Perhaps some update changed something...? Hard to say

**Comment by marcelklehr** [comment]
Mh, nice to hear that it seems to be resolved. Do get back to me if this returns!

**Comment by dolohow** [comment]
It returned!

This log is from last 14 hours.

```
grep bookmarks /var/log/apache2/nextcloud_access.log | grep -oE "PUT.*(HTTP)" | sort | uniq -c
```

```
   1608 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/446 HTTP
   1608 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/443 HTTP
   1608 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/440 HTTP
    805 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/429 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/folder/99 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/folder/98 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/folder/97 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/folder/95 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/folder/106 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/folder/104 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/folder/103 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/folder/101 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/7 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/448 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/428 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/427 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/426 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/425 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/424 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/423 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/380 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/379 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/377 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/374 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/373 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/372 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/27 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/170 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/157 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/13 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/115 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/114 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/113 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/104 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/103 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/102 HTTP
    804 PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/1 HTTP
```

Seems like something weird is going on there are too many requests for sure.

Full access log looks like this:
```
[IP] - [User] [20/Sep/2021:13:30:40 +0200] "PUT /index.php/apps/bookmarks/public/rest/v2/bookmark/102 HTTP/1.1" 200 2057 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 Edg/93.0.961.52"
```

**Comment by marcelklehr** [comment]
Do you also control the Edge browser that makes these requests or is that a user of yours? (Presumably a floccus instance?)

**Comment by dolohow** [comment]
User of mine.  What do you mean by _floccus instance_?

**Comment by marcelklehr** [comment]
Floccus is a browser extension that syncs bookmarks with nextcloud bookmarks: https://floccus.org

**Comment by dolohow** [comment]
Yes, I asked, and he in fact uses `floccus`.

**Comment by marcelklehr** [comment]
Which version?

**Comment by dolohow** [comment]
`4.7.0`

**Comment by marcelklehr** [comment]
Perhaps this is an encoding problem, where two different encodings of the same titles are compared on the client and decided to be different, but when trying to update the server, there is no actual difference... Hard to debug :/

**Comment by dolohow** [comment]
On database I have `utf8mb4`

Maybe you can cut out special characters. Or maybe compare by URL. Not sure if applicable, because I never used your software.

Thanks

**Comment by dolohow** [comment]
I tested version `10.0` and your work commited in d50ce54, did not help.

**Comment by marcelklehr** [comment]
Mh. I'd love to see some client-side logs from floccus. Can you arrange that? Since floccus doesn't error debug logs are gonna be harder to come by, but it's doable.

#### Firefox
* Go to `about:debugging`
* click on `debug/inspect` button next to floccus entry
* trigger a sync by clicking on `sync now` for the problematic account
* go back to the inspector window and export/copy the logs after waiting for the sync to finish

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* trigger a sync by clicking on `sync now` for the account of your choice
* go back to the inspector window and copy the logs after waiting for the sync to finish

**Comment by dolohow** [comment]
What about edge?

**Comment by marcelklehr** [comment]
Should be the same as chrome

**Comment by marcelklehr** [comment]
Any news?
