### ISSUE TITLE
Enable Support for Nextcloud 22

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/bookmarks#1590]
Thanks

**Comment by marcelklehr** [comment]
Still waiting for https://github.com/nextcloud/server/issues/26407

**Comment by marcelklehr** [comment]
You can force enable the app for now, to see if it works.

**Comment by jakobroehrl** [comment]
Tested it, it's working fine.

**Comment by dvzrv** [comment]
@marcelklehr as the issue mentioned in https://github.com/nextcloud/bookmarks/issues/1590#issuecomment-867534995 seems completed with https://github.com/nextcloud/documentation/pull/6900, would it be possible to release a new version for this app? It is one of the apps blocking the update to nextcloud 22 on Arch Linux. Thanks! :)

**Comment by marcelklehr** [comment]
Yep, that's been on my todo list. Thanks for the heads up!

**Comment by marcelklehr** [comment]
Done :) https://github.com/nextcloud/bookmarks/releases/tag/v4.3.0
