### ISSUE TITLE
New third-party client "Bookmarks for Nextcloud" for Android

### ISSUE THREAD

**Issue by tomcat-xx** [nextcloud/bookmarks#1597]
Does anyone know this new app "Bookmarks for Nextcloud" (de.emasty.bookmarks)? Tried all others (web app included) but found no comfortable way to use bookmarks on Android so far. This one seems to be. But what's about security? 

I also found no way to share bookmarks with new user and restrict access to just bookmarks for the app.

If using app is ok maybe you can add in README.md

**Comment by marcelklehr** [comment]
I've been in contact with the author.

Perhaps @emasty can say more on this subject.

**Comment by emasty** [comment]
Hello @tomcat-xx 

I am glad to hear, that you like the app!

May I ask what your questions regarding security are? I am happy to answer them the best I can.

I try to answer the questions I understood from your message:
- As far as I know, there is no way in Nextcloud to limit access to just certain apps with the API. If I am wrong, please let me know!
- The App only connects to your selected Nextcloud server only - and only to the Bookmarks API. There is no tracking or ads client or anything else built in. The only additional data would be a mail that you manually have to send me when an error occurs (message is prefilled though).
- The app does not store/read/get your credentials. During setup, the user is forwarded to the nextcloud login page. The app only receives an access token after a successful login. You can revert the login on your nextcloud server. Your password is not available/stored for/in the app at any time.
- The sharing feature of Nextcloud Bookmark is currently not supported. It might be something for a future implementation. Right now you can view shared bookmarks but you can't edit/add shared bookmarks. This would have to be done on the website.
- You can share the bookmark through the Android sharing feature, but that is a kind of different use-case

I still think about releasing the app as open source. This would open the opportunity for others to further develop and extend the app. But there are a few things stopping me as of now which are:
- Code documentation and quality
- Correct license

The app was a "learning" project for me to learn Flutter. Therefore, the code quality is a bit mixed ;)

Marcel already asked me to create a pull request for the README.md. Maybe I can do that this week.

**Comment by tomcat-xx** [comment]
Hello Marcus,

Thanks for your answers. I have a better feeling now and will use the app. But as you mentioned "open source", yes, that's the only way to be sure. You'll never know who is behind an app in Google Play.

Checking the possibility of sharing bookmarks in Nextcloud was only an idea to limit access for a dummy user that I could use in the app. I'm using this for example for home automation were I just need access to (a single) calendar. In general I don't have a need for sharing bookmarks.

**Comment by marcelklehr** [comment]
> I still think about releasing the app as open source. This would open the opportunity for others to further develop and extend the app. But there are a few things stopping me as of now which are:
>
>   * Code documentation and quality

I think quality and docs can always be improved, this app is no exception. Don't be ashamed of your work. I think in the end it's more important that people can use it than how beautiful the code is :) 

>   * Correct license

If in doubt, https://choosealicense.com/ may provide more information, but I'm also happy to help on this.

**Comment by marcelklehr** [comment]
@emasty Also, please don't forget to open issues for the problems you hit with the API :)
