### ISSUE TITLE
favorite url/link and its folders (like in files-app) and/or notification

### ISSUE THREAD

**Issue by Der-K-2000** [nextcloud/bookmarks#1600]
It would be nice, if there is a function to favorite a folder/file like in the normal files-app (but not necessarily connected to that system).

As addition a notification-system would be helpful in bigger teams to manage links in the bookmarks-app (I know: fav>activity could do this job in a quite simple way, even though it's not really differentiated.)

🙏👍🏻

**Comment by marcelklehr** [comment]
Hi @SebastianBerlin 

Thanks for the great suggestions! A favorite function is a good idea! Differentiating bookmarks activity events further is a good idea, too, so people can opt to get a mail e.g. when someone else has done something in their bookmarks.

**Comment by marcelklehr** [comment]
The favorite system has been suggested in #1280 

I took the liberty of creating an exclusive feature request over here: #1603
