### ISSUE TITLE
Syncing with Floccus

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#1604]
Hi,

For a few weeks now, I noticed the browser syncing of my bookmarks kept failing with some error E020 (using the Floccus extension). I went to dig a bit in the nextcloud logs and found this error whenever the sync is triggered: [https://pastebin.com/7cREA4KU](https://pastebin.com/7cREA4KU).

Thank you for any help!

**Comment by marcelklehr** [comment]
Can you check, which indices your MYSQL db has: `SHOW INDEX FROM oc_bookmarks;`

**Comment by DetectiveBrie** [comment]
Yes here is what I have:

![image](https://user-images.githubusercontent.com/1509146/126152706-0ea99254-b79a-405a-920c-9ef75de9baba.png)

**Comment by marcelklehr** [comment]
The cardinality values would indicate that you have no bookmarks whatsoever in your instance, which is suspicious. You can try running

```
ANALYZE TABLE oc_bookmarks;
```

to update the indeces.

**Comment by DetectiveBrie** [comment]
Yes that would be correct, I apologize for not mentioning but before posting an issue here I tried various things such as reinstalling both client and server modules, deleting the bookmarks and trying to synchronize at a blank state first (in case a specific bookmark was the problem), etc...

I don't know if the result of the analysis is useful but here it is:
![image](https://user-images.githubusercontent.com/1509146/126155363-2425bea2-cf1f-436a-a460-c07594777124.png)

I also wanted to mention that since the nextcloud log seem to indicate a sort_buffer memory insufficiency, I went to check and the mysql config does allocate 8M to it which I thought would be ample enough. I am really at a loss at what the issue is.

**Comment by marcelklehr** [comment]
> sort_buffer memory insufficiency

This usually means that the DB is asked to sort by a column that is not indexed and thus has to sort the whole table in memory, which can get out of hand quickly. I asked you for your indexes to make sure you have all relevant indexes for your table.

**Comment by panachoi** [comment]
I'm seeing this too. But I just started "fresh", by deleting all my bookmarks from the WebUI, and then setting up my account in Floccus. The first sync works correctly (well, it first fails because the sync would delete my current bookmarks, which is good behavior) when I force a sync up. If I then add a bookmark to the browser, the next sync fails with exactly this error....the oc_bookmarks table looks like this:
```

SHOW INDEX FROM oc_bookmarks;
+--------------+------------+----------------------+--------------+--------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table        | Non_unique | Key_name             | Seq_in_index | Column_name  | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+--------------+------------+----------------------+--------------+--------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| oc_bookmarks |          0 | PRIMARY              |            1 | id           | A         |         624 |     NULL | NULL   |      | BTREE      |         |               |
| oc_bookmarks |          1 | IDX_3EE1CD04A76ED395 |            1 | user_id      | A         |           4 |     NULL | NULL   |      | BTREE      |         |               |
| oc_bookmarks |          1 | IDX_3EE1CD04DF091378 |            1 | last_preview | A         |           2 |     NULL | NULL   | YES  | BTREE      |         |               |
| oc_bookmarks |          1 | bookmarks_modified   |            1 | lastmodified | A         |          24 |     NULL | NULL   | YES  | BTREE      |         |               |
| oc_bookmarks |          1 | bookmarks_deadbyuser |            1 | user_id      | A         |           4 |     NULL | NULL   |      | BTREE      |         |               |
| oc_bookmarks |          1 | bookmarks_deadbyuser |            2 | available    | A         |           4 |     NULL | NULL   | YES  | BTREE      |         |               |
| oc_bookmarks |          1 | bookmarks_dead       |            1 | available    | A         |           2 |     NULL | NULL   | YES  | BTREE      |         |               |
+--------------+------------+----------------------+--------------+--------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
7 rows in set (0.001 sec)


```

I'm not sure whats going on.

**Comment by marcelklehr** [comment]
Ok, then let's try having mysql explain what it does:

```
EXPLAIN SELECT `b`.`id`, `b`.`url`, `b`.`title`, `b`.`description`, `b`.`lastmodified`, `b`.`added`, `b`.`clickcount`, `b`.`last_preview`, `b`.`available`, `b`.`archived_file`, `b`.`user_id`, GROUP_CONCAT(`tree`.`parent_folder`) AS `folders`, GROUP_CONCAT(`t`.`tag`) AS `tags` FROM `oc_bookmarks` `b` LEFT JOIN `oc_bookmarks_tree` `tree` ON (`b`.`id` = `tree`.`id`) AND (`tree`.`type` = 'bookmark') LEFT JOIN `oc_bookmarks_tags` `t` ON `t`.`bookmark_id` = `b`.`id` LEFT JOIN `oc_bookmarks_tree` `tr` ON (`tr`.`id` = `b`.`id`) AND (`tr`.`type` = 'bookmark') LEFT JOIN `oc_bookmarks_shared_folders` `sf` ON `tr`.`parent_folder` = `sf`.`folder_id` LEFT JOIN `oc_bookmarks_tree` `tr2` ON (`tr2`.`id` = `tr`.`parent_folder`) AND (`tr2`.`type` = 'folder') LEFT JOIN `oc_bookmarks_shared_folders` `sf2` ON `tr2`.`parent_folder` = `sf`.`folder_id` WHERE (`b`.`user_id` = 'USERNAME') OR (`sf`.`user_id` = 'USERNAME') OR (`sf2`.`user_id` = 'USERNAME') GROUP BY `b`.`id`, `b`.`url`, `b`.`title`, `b`.`description`, `b`.`lastmodified`, `b`.`added`, `b`.`clickcount`, `b`.`last_preview`, `b`.`available`, `b`.`archived_file`, `b`.`user_id`, `b`.`id` ORDER BY `b`.`lastmodified` DESC, `b`.`id` ASC LIMIT 300
```

(Replace USERNAME with your username.)

**Comment by marcelklehr** [comment]
( Possibly similar issue: https://github.com/floccusaddon/floccus/issues/792 )

**Comment by panachoi** [comment]
Helpful ?
```

id      select_type     table   type    possible_keys   key     key_len ref     rows    Extra
1       SIMPLE  b       ALL     IDX_3EE1CD04A76ED395,bookmarks_deadbyuser       NULL    NULL    NULL    624     Using temporary; Using filesort
1       SIMPLE  tree    ref     PRIMARY PRIMARY 90      nextcloud.b.id,const    7       Using where; Using index
1       SIMPLE  t       ref     PRIMARY,bookmark_tag    PRIMARY 8       nextcloud.b.id  1       Using index
1       SIMPLE  tr      ref     PRIMARY PRIMARY 90      nextcloud.b.id,const    7       Using where; Using index
1       SIMPLE  sf      ALL     bookmarks_shared_folder NULL    NULL    NULL    1       Using where; Using join buffer (flat, BNL join)
1       SIMPLE  tr2     ref     PRIMARY PRIMARY 90      nextcloud.tr.parent_folder,const        7       Using where; Using index
1       SIMPLE  sf2     index   NULL    bookmarks_shared_user   1022    NULL    1       Using where; Using index; Using join buffer (flat, BNL join)


```

**Comment by marcelklehr** [comment]
Thank you! I've identified the problem (it's indeed the same problem as the linked floccus issue) and am working on a fix.

**Comment by marcelklehr** [comment]
Fixed with https://github.com/nextcloud/bookmarks/releases/tag/v4.4.0

**Comment by marcelklehr** [comment]
@DetectiveBrie Can you confirm this is fixed for you with v4.4.0?

**Comment by Octothorn** [comment]
I seem to still be seeing this issue.

E020 using the Floccus extension (previously functional)

> E020: Could not parse server response. Is the bookmarks app installed on your server? Unexpected token < in JSON at position 0


Nextcloud  21.0.4
Bookmarks 4.4.0
Floccus 4.7.0

Bookmarks in nextcloud is otherwise performing normally.

Tried simplifying my nginx setup for nextcloud. No change.
Checked the information in this thread.

Happy to gather more information and discuss further.

**Comment by marcelklehr** [comment]
@Octothorn Do you also see a mysql error in your nextcloud log? (OP's error is sadly gone now behind that URL). E020 only means you have a server-side error, that doesn't need to be the same error discussed here.

**Comment by Octothorn** [comment]
@marcelklehr 
Thanks for getting back.  I just added a gist for the error I see in the logs. A bit hurried at the moment, so have not had time to analyse yet.

https://gist.github.com/Octothorn/fbe1c2f61fc4bfacd2f7b88bdbc09ac4#file-nextcloud-error-re-floccus

**Comment by Octothorn** [comment]
@marcelklehr 
I see you opened this matter to a bug report.
Just getting back with further information which may help (at least eliminating possibilities)
I expect this is all known at this point, but it is offered nonetheless.

To add: 
The nextcloud and flocus errors described were seen after updating to Bookmarks 4.4.1 (and the floccus error was seen previously on 4.4)

oc_bookmarks table structure:

Column | Type | Comment
-- | -- | --
bigint(20) Auto Increment |  
varchar(4096) [] |  
varchar(4096) [] |  
varchar(64) [] |  
varchar(4096) [] |  
int(10) unsigned NULL [0] |  
int(10) unsigned NULL [0] |  
int(10) unsigned [0] |  
int(10) unsigned NULL [0] |  
tinyint(1) NULL [1] |  
bigint(20) NULL |  
longtext NULL |  
longtext NULL |  

Also, I added a new bookmark and re-ran floccus with "push sync". I got the same error in both floccus and in nextcloud logs, but the bookmark did appear correctly in nextcloud. (with a simple one-line description.)

I am not sure if any of this has value to the bug report you opened (pretty sure it doesn't), so I am reporting it here as experience.
