### ISSUE TITLE
Tags not considered in folder hashing function

### ISSUE THREAD

**Issue by emasty** [nextcloud/bookmarks#1606]
The Nextcloud Bookmark API endpoint to hash a folder does not consider tags of child bookmarks.

**Is your feature request related to a problem? Please describe.**
To identify changed bookmarks or folders, the API provides a entry point to generate a hash value for each folder. (See [https://nextcloud-bookmarks.readthedocs.io/en/latest/folder.html#hash-a-folder)](https://nextcloud-bookmarks.readthedocs.io/en/latest/folder.html#hash-a-folder)

The hash value considers:
* Hash value of child folders (title, bookmarks)
* Hash value of child bookmarks (title, url)

Tags of bookmarks are not considered right now. If a tag was deleted/changed from a bookmark, the hash value of the parent folder does not change. Tags can also not be added to the considered fields array.

**Describe the solution you'd like**
* Add tags to hash function
* Reconsider sync strategy (e.g. timestamp based)

**Comment by marcelklehr** [comment]
Ok, currently the hash endpoint fails for me when adding `fields[]=tags`, I'll fix this

**Comment by emasty** [comment]
Many thanks!
I will try to give it a test. But it may take some time.
