### ISSUE TITLE
Old repository tags make tracking this upstream very hard

### ISSUE THREAD

**Issue by dvzrv** [nextcloud/bookmarks#1607]
**Describe the bug**
The tags pre [v0.9.1](https://github.com/nextcloud/bookmarks/tags?after=v0.10.0) are problematic, as they are (mostly) conflicting (they order higher in semver - e.g. `v9.0.5`) with the the tags post `v0.9.1` and additionally there are several jumps in versions in between pre `v0.9.1` (e.g. [v9.1.0RC4](https://github.com/nextcloud/bookmarks/releases/tag/v9.1.0RC4) followed by [v0.4.3](https://github.com/nextcloud/bookmarks/releases/tag/v0.4.3) or [v0.7.1](https://github.com/nextcloud/bookmarks/releases/tag/v0.7.1) followed by [v8.0.15RC1](https://github.com/nextcloud/bookmarks/releases/tag/v8.0.15RC1)) as well.

For downstreams this is very problematic, as they can not easily figure out which is actually your current version (dozens of old version tags order before the current version `v4.3.0` and would have to be added to a manually selected list of tags to ignore) and even more problematically as soon as you reach `v6.0.0` you will hit a version conflict, as that version exists already.

There are two potential ways out of this situation:

* rename all old tags to order properly (e.g. `v9.0.5` -> `v0.9.0.5` or similar)
* Jump to a version that is outside of the scope of the mess for the next release (e.g. >= `v10.0.0`)

Implementing either of the two would be very much appreciated!

**To Reproduce**
1. `git ls-remote -t "https://github.com/nextcloud/bookmarks"`

**Expected behavior**
The tags listed in (https://github.com/nextcloud/bookmarks/tags order sequentially decreasing according to semver (i.e. older tags < newer tags). There are no jumps in tagging schema.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: n/a
 - Version: n/a

**Server (please complete the following information):**
 - OS: Arch Linux
 - HTTP server: n/a
 - Database: n/a
 - PHP version: n/a
 - Nextcloud version: 22.0.0
 - Bookmarks app version: 4.3.0
 - Activated Nextcloud Apps: n/a
 - Nextcloud configuration: n/a
 - Nextcloud external user backend: n/a

**Additional context**
Downstreams use automated tooling to track upstreams. This is based on e.g. [git ls-remote](https://man.archlinux.org/man/git-ls-remote.1) in the case of git repositories.

**Web server error log**
n/a

**Nextcloud log (nextcloud/data/nextcloud.log)**
n/a

**Browser log**
n/a

**Comment by marcelklehr** [comment]
@ChristophWurst Any pointers on the best way forward here?

**Comment by ChristophWurst** [comment]
I'm not sure I understand. Was the version scheme of this app changed?

**Comment by dvzrv** [comment]
It wasn't changed recently, but apart from the `v${MAJOR}.${MINOR}.${PATCH}` scheme there are also two other schemes used (`${MAJOR}.${MINOR}.${PATCH}` and `bookmarks-v${MAJOR}.${MINOR}.${PATCH}`) (so it definitely has been changed in the past).

The problem I am describing in this ticket is rather, that [semver](https://semver.org) has been violated in this repository and is currently still being violated.
The current version [v4.4.0](https://github.com/nextcloud/bookmarks/releases/tag/v4.4.0) orders *in between* dozens of other versions (that are much older than the current - the highest version tag is [v9.1.0](https://github.com/nextcloud/bookmarks/releases/tag/v9.1.0), which is from over five years ago).

The value of the tag is what defines the version, not the time when the tag has been created.

**Comment by alerque** [comment]
@dvzrv As a temporary hack for dealing with downstream packaging in situations like this I've found ① cloning the source, ② deleting all tags created before a date known to be one of the "latest" series, then finally ③ sorting tags to work. Of course this only works by having a full remote clone, it makes it very hard to check by just downloading a tag list from the GitHub API, etc.

**Comment by marcelklehr** [comment]
I guess the safest approach would be to make the next release v10

**Comment by marcelklehr** [comment]
Closed with https://github.com/nextcloud/bookmarks/releases/tag/v10.0.0
