### ISSUE TITLE
Bookmarks web page appears blank in IOS browsers

### ISSUE THREAD

**Issue by mikec83** [nextcloud/bookmarks#163]
When viewing the bookmarks website (owncloudurl/index.php/apps/bookmarks/) in a browser on iOS (iPad or iPhone), the page is completely blank.  I've tried this in safari and chrome.

**Comment by blizzz** [comment]
@michaelclagett Can you elaborate on the versions you use (bookmark app, ownCloud, iOS things), please? Are there any JavaScript issues (if those browser show them)?

**Comment by marcelklehr** [comment]
Closing due to lack of response. If you can provide more information, I'm happy to reopen this :)
