### ISSUE TITLE
Yunohost: Out of sort memory, consider increasing server sort buffer size

### ISSUE THREAD

**Issue by klundry** [nextcloud/bookmarks#1631]
I'm on Yunohost and just upgraded from NC 20 to NC 21, Bookmarks version 4.4.0 and my bookmarks do not display. The main panel shows "No bookmarks here" but all the tags show on the left with numbers next to them as if the bookmarks still are there. I can also export my bookmarks and they are there.

**Comment by marcelklehr** [comment]
It could be that you have multiple root folders due to a race condition. If you don't have access to your database (I assume for Yunohost), the easiest fix is probably to export, clear data, and reimport.
If you have access to your database you can run `SELECT * from oc_bookmarks_root_folders WHERE user_id = 'YOUR USER ID HERE';` to see if you have multiple root folders.

**Comment by klundry** [comment]
Hmm...I cleared, reimported, same thing. Then I cleared, disabled and uninstalled Bookmarks. Reinstalled bookmarks, reimported, same thing.

**Comment by marcelklehr** [comment]
Then something is wrong. :/

**Comment by marcelklehr** [comment]
Are there any errors in the nextcloud log?

**Comment by klundry** [comment]
There are some entries in the log regarding Bookmarks. They are super long lines and I'm not sure what I'm looking for though. Any keywords I can search to find the relevant parts of the lines?

**Comment by klundry** [comment]
Ah, I think this may be the culprit.

`{"reqId":"qXt1HaggNLXxzmX17jPu","level":3,"time":"2021-08-12T21:34:33+00:00","remoteAddr":"192.168.1.1","user":"kellen","app":"index","method":"GET","url":"/apps/bookmarks/bookmark?limit=42&page=0&sortby=title&folder=-1","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing a query: SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size","Code":1038,"Trace"`

**Comment by marcelklehr** [comment]
Aha!

**Comment by marcelklehr** [comment]
That was supposed to be fixed with v4.4.0 :/ Do you have all your bookmarks in the root folder? How many do you have?

**Comment by klundry** [comment]
Yes. I only have 22 bookmarks though so not very many at all.

**Comment by marcelklehr** [comment]
Can you post the full trace, please?

**Comment by klundry** [comment]
Do you mean the full log where I found that snippet?

**Comment by marcelklehr** [comment]
The full log entry with the paths where the error was thrown, yeah

**Comment by klundry** [comment]
[nclog.txt](https://github.com/nextcloud/bookmarks/files/7002440/nclog.txt)

**Comment by marcelklehr** [comment]
v4.4.1 has been released with a fix for this issue.

**Comment by klundry** [comment]
This is still not fixed for me.

**Comment by klundry** [comment]
Recent and every sorting setting result in the same No bookmarks here. The error in the log appears to be the same.

`{"Exception":"PDOException","Message":"SQLSTATE[HY001]:` Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size","Code":"HY001","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":82,"function":"execute","class":"PDOStatement","type":"->","args":[null]},

**Comment by marcelklehr** [comment]
It seems Yunohost has updated their specs, can you confirm that?
