### ISSUE TITLE
Content of bookmark is alway empty in detail page

### ISSUE THREAD

**Issue by jim3ma** [nextcloud/bookmarks#1656]
**Describe the bug**

Content of bookmark is alway empty in detail page.

```
Content pending
This content is being downloaded for offline use. Please check back later.
```

I have checked the database, `archived_file`, `html_content` and `text_content` is also empty.

**Expected behavior**

Content of bookmark is loaded.

**Screenshots**

<img width="1452" alt="Screen Shot 2021-09-22 at 3 03 14 PM" src="https://user-images.githubusercontent.com/1567113/134297805-db46a2b6-e109-4389-817f-c17a2c82ff32.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser:  Chrome
 - Version:  88

**Server (please complete the following information):**
 - Nextcloud version: 21.0.4
 - Bookmarks app version: 10.0.0

**Comment by marcelklehr** [comment]
Hi!

Is network access enabled in your settings?

**Comment by jim3ma** [comment]
The preview image is taken successfully. I think the network is ok.

<img width="1452" alt="Screen Shot 2021-09-22 at 3 03 14 PM" src="https://user-images.githubusercontent.com/1567113/134297805-db46a2b6-e109-4389-817f-c17a2c82ff32.png">

**Comment by marcelklehr** [comment]
> I have checked the database, archived_file, html_content and text_content is also empty.

Can you check the last_preview field? The content should be archived by the background job every half hour. Make sure that your background job is running?

**Comment by jim3ma** [comment]
@marcelklehr All last_preview is zero. Can you tell me how to add log in bookmarks app ? I have added some log into CrawlService, but not work.

**Comment by marcelklehr** [comment]
See https://github.com/nextcloud/bookmarks/blob/master/lib/Service/CrawlService.php#L100

Is your nextcloud cron job up and running? (You can check in the admin settings overview)

**Comment by jim3ma** [comment]
> See https://github.com/nextcloud/bookmarks/blob/master/lib/Service/CrawlService.php#L100
> 
> Is your nextcloud cron job up and running? (You can check in the admin settings overview)
> 
> > All last_preview is zero.
> 
> That would indicate that there's a problem with the background job.

Yes, it's running.

**Comment by marcelklehr** [comment]
Can you check the nextcloud log for errors?

**Comment by jim3ma** [comment]
Sorry, there is no any log for bookmarks.

**Comment by jim3ma** [comment]
> See https://github.com/nextcloud/bookmarks/blob/master/lib/Service/CrawlService.php#L100
> 
> Is your nextcloud cron job up and running? (You can check in the admin settings overview)
> 
> > All last_preview is zero.
> 
> That would indicate that there's a problem with the background job.

I have added the log, but nothing printed in log file.
My actions:
* edit CrawlService.php
* restart nextcloud

**Comment by jim3ma** [comment]
> See https://github.com/nextcloud/bookmarks/blob/master/lib/Service/CrawlService.php#L100
> 
> Is your nextcloud cron job up and running? (You can check in the admin settings overview)
> 
> > All last_preview is zero.
> 
> That would indicate that there's a problem with the background job.

Yes, fixed.

**Comment by jcm4atx** [comment]
I had the same problem. Turns out I had the `snap` version of `pageres-cli` installed. I saw a message in nextcloud.log stating `Sorry, home directories outside of /home are not currently supported.`
The solution was to install the `npm` version.
Just adding my two cents in case someone else has this problem.
