### ISSUE TITLE
Installation failed due SQL error

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#1671]
**Describe the bug**
Try to install the plugin on my self hosted 21.0.2 nextcloud instance

**To Reproduce**
1. Select Bookmark in application list
2. click Download and install
3. error: 
```An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_bookmarks' doesn't exist ```

**Expected behavior**
Installation without error

**Desktop (please complete the following information):**
 - OS: FreeBSD 13.0-p4
 - Browser: Firefox
 - Version: 93.0

**Server (please complete the following information):**
 - OS:FreebSd 13.0
 - HTTP server:Nginx 1.20
 - Database: mariadb 105
 - PHP version: v8.0
 - Nextcloud version: 21.0.2
 - Bookmarks app version: 10.0.0
 - Activated Nextcloud Apps: 
  Enabled:
>   - accessibility: 1.7.0
>   - activity: 2.14.3
>   - bruteforcesettings: 2.2.0
>   - calendar: 2.3.4
>   - cloud_federation_api: 1.4.0
>   - comments: 1.11.0
>   - contacts: 4.0.3
>   - cookbook: 0.9.4
>   - dav: 1.17.1
>   - federatedfilesharing: 1.11.0
>   - files: 1.16.0
>   - files_pdfviewer: 2.1.0
>   - files_rightclick: 1.0.0
>   - files_sharing: 1.13.1
>   - files_trashbin: 1.11.0
>   - files_versions: 1.14.0
>   - logreader: 2.6.0
>   - lookup_server_connector: 1.9.0
>   - news: 16.1.0
>   - nextbackup: 21.1.0
>   - nextcloud_announcements: 1.10.0
>   - notifications: 2.9.0
>   - oauth2: 1.9.0
>   - photos: 1.3.0
>   - privacy: 1.5.0
>   - provisioning_api: 1.11.0
>   - rainloop: 7.1.2
>   - scanner: 0.2.1
>   - serverinfo: 1.11.0
>   - settings: 1.3.0
>   - sharebymail: 1.11.0
>   - spreed: 11.3.2
>   - survey_client: 1.9.0
>   - systemtags: 1.11.0
>   - text: 3.2.0
>   - theming: 1.12.0
>   - twofactor_backupcodes: 1.10.0
>   - updatenotification: 1.11.0
>   - user_ldap: 1.11.0
>   - viewer: 1.5.0
>   - workflowengine: 2.3.0
 Disabled:
>   - admin_audit
>   - bookmarks
>   - camerarawpreviews
>   - contactsinteraction
>   - dashboard
>   - dropit
>   - encryption
>   - federation
>   - files_external
>   - files_inotify
>   - files_markdown
>   - files_videoplayer
>   - firstrunwizard
>   - keeweb
>   - ldap_write_support
>   - libresign
>   - notes
>   - password_policy
>   - recommendations
>   - richdocuments
>   - support
>   - tasks
>   - user_status
>   - weather_status

 - Nextcloud configuration: 
 ```{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.foucry.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "overwrite.cli.url": "https:\/\/nextcloud.foucry.net",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "ownbackup",
            "nextbackup"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465"
    }
}```

 - Nextcloud external user backend: ldap

**Comment by marcelklehr** [comment]
Have had the app installed once before? You may need to check your `oc_migrations` table for remnant entries of the bookmarks app and delete those.
