### ISSUE TITLE
Help test v10.0.1

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#1674]
Hello there,

with v10.0.1 come two fixes that address issues with authentication and I'd like to be extra careful to make sure to not break compatibility with 3rd party clients. I've confirmed that floccus continues to work as expected, but I'd also like to ask @altepizza, @dasbiswajit and @emasty to test their apps with the new release.

If you are using another third-party app, feel free to also try installing https://github.com/nextcloud/bookmarks/releases/tag/v10.0.1 and give it a go with your app or notify your app's maintainer.

Thank you

**Comment by emasty** [comment]
Hello Marcel,

many thanks for the heads up! I will try to test the app and authentication on the weekend.
Is there something we should specifically look out for?

**Comment by emasty** [comment]
Looks good to me. Everything seems to work.

**Comment by marcelklehr** [comment]
Thanks folks!
