### ISSUE TITLE
Bookmarks of specific site have no Title

### ISSUE THREAD

**Issue by tux93** [nextcloud/bookmarks#1681]
**Describe the bug**
When adding a Bookmark for a specific site the page title for the page is never set for the bookmark, it will only display the URL.
I can see "Nextcloud Server Crawler" hitting the site in its access.log, my current assumption is that the root cause is some header the site sets but I can not find any log from the bookmarks app as to why it fails to generate the info.

**Steps to reproduce the behavior:**
1. Go to Bookmarks in Nextcloud
2. Click on New -> New Bookmark
3. Enter https://nitter.squirrel.rocks/openSUSE/ and confirm
4. The Details page of the new Bookmark opens but the page title is not set, instead it shows the URL

**Expected behavior**
The Bookmark has the Title of the Page

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Browser: Firefox
 - Version: 93

**Server (please complete the following information):**
 - OS: openSUSE Leap 15.3
 - HTTP server: nginx 1.19.8
 - Database: mariadb 10.5.12
 - PHP version: 7.4.6
 - Nextcloud version: 22.2.0
 - Bookmarks app version: 10.0.2
 - Activated Nextcloud Apps: 
 ```
  - accessibility: 1.8.0
  - admin_audit: 1.12.0
  - audioplayer: 3.2.2
  - bookmarks: 10.0.2
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - contacts: 4.0.6
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.0
  - files_retention: 1.11.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.3.0
  - gpxpod: 4.2.8
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - news: 16.2.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.1.2
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.1.0
  - updatenotification: 1.12.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
 ```
 - Nextcloud external user backend: none

**Additional context**
Even if the root cause is not within the Bookmarks App it would be great to have log entries for what prevented the App from setting the title

**Web server error log**
```
[03/Nov/2021:23:20:01 +0000] "GET /openSUSE/ HTTP/1.1" 200 11386 "-" "Nextcloud Server Crawler" 
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
No entries regarding the bookmarks app
```

**Comment by marcelklehr** [comment]
Sorry for the delay. I just tried and cannot reproduce this with the URL you gave.

**Comment by tux93** [comment]
I updated to NC 23 / Bookmarks 10.0.3 in the meantime and still see the same behaviour

![image](https://user-images.githubusercontent.com/1749593/145718767-880a29c4-2954-4fd3-b362-72987f36104a.png)

When using the Bookmarklet instead of adding the Bookmark manually the Title is set correctly:

![image](https://user-images.githubusercontent.com/1749593/145718938-10c7f83b-99f7-43fc-9c1e-43344136ac14.png)

**Comment by marcelklehr** [comment]
Have you enabled network access for the app?

**Comment by tux93** [comment]
I was not aware that setting was added, that appears to have indeed been the issue
