### ISSUE TITLE
not able to turn off notification every time I open bookmarks app

### ISSUE THREAD

**Issue by tessus** [nextcloud/bookmarks#1693]
Sorry to use the issue tracker, but I wasn't sure where to ask questions. Please let me know and I do it there, if it is not appropriate.

Every time I open the app, I get the following message:

```
Network access is disabled by default. Go to administrator settings for the bookmarks app to allow fetching previews and favicons.
```

Yes, I know. And I will not change it. But I can't get rid of this message. It is really annoying, because I have to dismiss it every single time.

Please, is there a flag I can set?

P.S.: Bookmarks 10.0.2 on Nextcloud 21.0.6

**Comment by marcelklehr** [comment]
> It is really annoying, because I have to dismiss it every single time.

Yep, that was a preliminary way to let people know where to enable previews, but of course if you really don't want it, I can understand it's quite annoying.
