### ISSUE TITLE
Please add support for nextcloud 23

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/bookmarks#1694]

**Comment by patrickuhlmann** [comment]
What doesn't work?

**Comment by nursoda** [comment]
It probably does work, however it would be nice if one would not need to "allow untested app".

**Comment by LeDucDuBleuet** [comment]
It simply says there is no compatible version of this app with NC 23 in the updater.

**Comment by jurgenhaas** [comment]
The app store at https://apps.nextcloud.com/apps/bookmarks doesn't show support for NC 23 yet, would be great to update the metadata.

**Comment by rakekniven** [comment]
Please vote at the first comment of this issue.

**Comment by marcelklehr** [comment]
Hey everyone!
I'm sorry for the delay. Fixing this unfortunately is not as easy as slapping on a 23-compatible label on my part.
For QA-reasons I need to do a full set of accessibility tests for each release, which is why I haven't found time, so far -- until today :)

**Comment by marcelklehr** [comment]
https://github.com/nextcloud/bookmarks/releases/tag/10.0.3 :rocket:

**Comment by rakekniven** [comment]
Danke schön 🤩

**Comment by jakobroehrl** [comment]
Thanks a lot for your hard work, love the bookmarks app
