### ISSUE TITLE
replace archived marcelklehr/readability.php with fivefilters/readability.php

### ISSUE THREAD

**Issue by patrickuhlmann** [nextcloud/bookmarks#1696]
You are using https://github.com/andreskrey/readability.php which is archived. The maintenance is taken over by https://github.com/fivefilters/readability.php. Can you migrate to that one?

The original reason I ask is because my webhoster is running malware scans and the file vendor/marcelklehr/readability.php/test/test-
pages/yahoo-4/source.html is reported as Generic:HTML/Seospam.B

I created a request for improvement in the library here: https://forum.fivefilters.org/t/malware-warning-readability-php/1286

**Comment by marcelklehr** [comment]
Thanks for the heads up! They don't seem to have rolled out a new release as of yet, though: https://github.com/fivefilters/readability.php/issues/2

**Comment by sommer-gei** [comment]
@patrickuhlmann FYI: the malware aspect was already _discussed_ here
* `andreskrey/readability.php/issues/101` = https://github.com/andreskrey/readability.php/issues/101#issuecomment-830580956
* `nextcloud/news/issues/1321` = https://github.com/nextcloud/news/issues/1321#issuecomment-829223795
* `nextcloud/news/issues/1434` = https://github.com/nextcloud/news/issues/1434#issuecomment-875768840

And I will also mention that there is **no new** current/working (stable) package available in the new repo by `fivefilters`: https://github.com/fivefilters/readability.php/issues/2#issuecomment-1048257746

KR

**Comment by sommer-gei** [comment]
> Thanks for the heads up! They don't seem to have rolled out a new release as of yet, though: [fivefilters/readability.php#2](https://github.com/fivefilters/readability.php/issues/2)

FYI, they now have added tags for new versions :blush:, see the Releases page: https://github.com/fivefilters/readability.php/tags

Best regards
