### ISSUE TITLE
Shared 3rd level folder empty / hidden bookmarks

### ISSUE THREAD

**Issue by pvrhartmann** [nextcloud/bookmarks#1706]
**Describe the bug**
A shared 3rd level folder appears to be empty - the bookmarks are hidden.

Seems to be related to ( https://github.com/nextcloud/bookmarks/issues/1257)

**To Reproduce**
1. Create a folder 1
2. Create a folder 2 within folder 1
3. Create a folder 3 within folder 2
4. Create a bookmark within folder 3
5. Share folder 1 by link and open it
6. Access folder 3 which should appear empty

You may also:
3. Create a folder 3 within folder 1
4. Create a bookmark within folder 3
5. Share folder 1 by link and open it
6. Access folder 3 and see the bookmarks
7. Move folder 3 into folder 2
8. Access folder 3 which should appear empty

**Expected behavior**
Access folder 3 and see the bookmarks in a 3rd level folder

**Screenshots**
![1stlevel_foldertoshare](https://user-images.githubusercontent.com/95620079/144836003-89aefd35-40ef-453f-b85f-af768c931597.jpg)

![1stlevel](https://user-images.githubusercontent.com/95620079/144836072-ed0cb47b-26fa-4ad3-860c-df4b6f74478f.jpg)
![2ndlevel](https://user-images.githubusercontent.com/95620079/144836076-d0f24e6a-aa38-4c8e-bca1-e5c3ba0fbc18.jpg)
![3rdlevel](https://user-images.githubusercontent.com/95620079/144836083-73d1a589-83e1-4910-9d7e-9f2ca54d320f.jpg)

![shared1stlevel](https://user-images.githubusercontent.com/95620079/144836093-2c164515-3ad2-47b0-b972-30c3a212f70e.jpg)
![shared2ndlevel](https://user-images.githubusercontent.com/95620079/144836119-f03eda08-784b-4e08-9b6b-df4a72fa75bc.jpg)
![shared3rdlevel](https://user-images.githubusercontent.com/95620079/144836124-ffa2f508-df35-4d14-bff7-879d142cbc93.jpg)

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser: Firefox 78.15.0esr (64-Bit) / Chromium 90.0.4430.212

**Server (please complete the following information):**
 - OS: Debian 10
 - HTTP server: nginx 1.2
 - Database: MariaDB 10.3
 - PHP version: 8.0
 - Nextcloud version: 21.0.7
 - Bookmarks app version: 10.0.2
 - Nextcloud external user backend: none

- Activated Nextcloud Apps:

enabled:

accessibility: 1.7.0
activity: 2.14.3
appointments: 1.11.2
apporder: 0.13.0
bookmarks: 10.0.2
calendar: 2.3.4
cloud_federation_api: 1.4.0
comments: 1.11.0
contactsinteraction: 1.2.0
dashboard: 7.1.0
dav: 1.17.1
federatedfilesharing: 1.11.0
federation: 1.11.0
files: 1.16.0
files_pdfviewer: 2.1.1
files_rightclick: 1.0.0
files_sharing: 1.13.1
files_trashbin: 1.11.0
files_versions: 1.14.0
files_videoplayer: 1.10.0
firstrunwizard: 2.10.0
groupfolders: 9.0.3
logreader: 2.6.0
lookup_server_connector: 1.9.0
nextcloud_announcements: 1.10.0
notifications: 2.9.0
oauth2: 1.9.0
password_policy: 1.11.0
photos: 1.3.0
privacy: 1.5.0
provisioning_api: 1.11.0
recommendations: 1.0.0
richdocuments: 4.2.3
serverinfo: 1.11.0
settings: 1.3.0
sharebymail: 1.11.0
support: 1.4.0
survey_client: 1.9.0
systemtags: 1.11.0       
text: 3.2.0
theming: 1.12.0
twofactor_backupcodes: 1.10.0
twofactor_totp: 6.1.0
updatenotification: 1.11.0
user_status: 1.1.1
viewer: 1.5.0
weather_status: 1.1.0
workflowengine: 2.3.1

disabled:

contacts: 4.0.6
cookbook: 0.9.6
deck: 1.4.5
documentserver_community: 0.1.11
end_to_end_encryption: 1.7.2
forms: 2.3.0
keeweb: 0.6.6
mail: 1.10.5
notes: 4.1.1
onlyoffice: 7.1.2
polls: 3.3.0
spreed: 11.3.3
tasks: 0.14.2

 - Nextcloud configuration:

"system": {
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "port": 0
        },
        "trusted_domains": [
            "localhost"
        ],
        "dbtype": "mysql",
        "version": "21.0.7.0",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "installed": true,
        "allow_user_to_change_display_name": false,
        "appstoreenabled": false,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "logfile": "\/home\/webkw6fpz\/logs\/nextcloud.log",
        "twofactor_enforced": "false",
        "maintenance": false,
        "simpleSignUpLink.shown": false,
        "default_locale": "de_DE",
        "loglevel": 2,
        "enable_previews": "false",
        "trashbin_retention_obligation": "7, 30",
        "blacklisted_files": [],
        "localstorage.allowsymlinks": true

**Comment by marcelklehr** [comment]
Can you try the latest version? (Although I don't expect this to fix the bug, just to be sure)

**Comment by marcelklehr** [comment]
Ah, I overlooked that your issue is about sharing a folder *publicly*, I can confirm the bug in this case.
