### ISSUE TITLE
There is no table with name 'nextcloud.oc_bookmarks' in the schema

### ISSUE THREAD

**Issue by feutl** [nextcloud/bookmarks#1719]
**Describe the bug**
I am trying to install the bookmark app and when installing it via NC I do get the following error in the "App" section of NC
`There is no table with name 'nextcloud.oc_bookmarks' in the schema.`

**To Reproduce**
1. Go to 'https://cloud.feutl.com/settings/apps/installed/bookmarks'
2. Click on 'Activate'

**Expected behavior**
The app should create the necessary and missing table and get activated.

**Screenshots**
![image](https://user-images.githubusercontent.com/8522012/148208196-8055786e-e055-4171-a15a-99034686ca9a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 95

**Server (please complete the following information):**
 - OS: Debian 11
 - HTTP server: Apache
 - Database: MySQL 10.3.31
 - PHP version: 7.3.31
 - Nextcloud version: NC 22.2
 - Bookmarks app version: 10.0.3
 - Nextcloud external user backend: none

**Comment by marcelklehr** [comment]
This may happen if you have installed the app before and it wasn't removed properly. You can try to 1) remove the app and 2) follow [this guide](https://github.com/nextcloud/bookmarks/wiki/Removing-all-traces-from-DB) to remove all traces of the app before attempting to install again.

**Comment by feutl** [comment]
@marcelklehr 
You were right, I had the "old" one installed previously, actually ages ago. But there were not tables, so the removing of the app worked - concerning the most obvious the tables. Anyhow I had entries in `oc_migrations`.
Now I ask myself, why is the app installation not capable of handling this on its own?

But thanks anyhow :) would not have looked into `oc_migrations` without you mentioning it 👍

**Comment by marcelklehr** [comment]
>  so the removing of the app worked

Removing the app does not remove the associated tables.

> why is the app installation not capable of handling this on its own?

Thus the tables were removed by other means, which the app has now way to detect.


But thanks anyhow :)

Cheers :)
