### ISSUE TITLE
exclude local IP ranges

### ISSUE THREAD

**Issue by mokkin** [nextcloud/bookmarks#1734]
**Is your feature request related to a problem? Please describe.**
We have some local bookmarks (IP-Phones, Printers). Those are also queried, but of course it fails as the server is not within the local network. 

**Describe the solution you'd like**
Exclude local IPs (10.x.x.x, 192.168.x.x) from querying or make it optional.

**Comment by marcelklehr** [comment]
Why is it not satisfactory to just let the crawler crawl into nothingness and report an unavailable link?

**Comment by marcelklehr** [comment]
Ah, I can adjust the log level of these errors. I think currently, they're on WARN, right?

**Comment by mokkin** [comment]
That might be the easiest solution.
Yes, they are on "WARN".
