### ISSUE TITLE
Authorization window

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/bookmarks#1745]
**Describe the bug**
The reauthorization window pops up 5 times with the "No" and "Yes" buttons. After closing 5 windows, the correct authorization window appears with the "Confirm" button.

**To Reproduce**
1. Select "Settings" from the menu.
2. Select "Bookmarks".
3. Wait until you need to reauthorize to Nextcloud.
4. Select "Privacy".

**Expected behavior**
Only one window for reauthorization appears.

**Screenshots**

_Multiple duplicate windows:_

![obraz](https://user-images.githubusercontent.com/47037905/154729217-51f16963-13ca-4f8d-91a3-805f8d439dc8.png)

_Window after closing duplicate windows:_

![obraz](https://user-images.githubusercontent.com/47037905/154728571-1a3cc214-0196-46d0-8e9a-b16fe4bfc487.png)

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version: 97.0

**Server (please complete the following information):**
 - PHP version: 7.3
 - Nextcloud version: 23.0.1
 - Bookmarks app version: 10.0.3

**Comment by marcelklehr** [comment]
Note to self: Should be fixable with initial state
