### ISSUE TITLE
Re-Create Bookmarks Database Tables

### ISSUE THREAD

**Issue by Xtropy74** [nextcloud/bookmarks#1761]
With all the issues I've had with Bookmarks freezing my server with all cores maxed, I just wanted to reset everything back to default so I can start over with Floccus. Continuing to have issues with this process, I logged onto the server and dropped all tables related to occ_bookmarks and now the bookmarks app won't work. How do I get those tables re-created? I assumed they would re-create themselves when I installed the Bookmarks app in Nextcloud but it doesn't.

Thanks,

**Comment by Xtropy74** [comment]
Nevermind, ran this command and it worked: https://github.com/nextcloud/bookmarks/wiki/Removing-all-traces-from-DB

**Comment by marcelklehr** [comment]
Let me know how it goes!
