### ISSUE TITLE
SQLSTATE error

### ISSUE THREAD

**Issue by mobamoba** [nextcloud/bookmarks#1776]
**Describe the bug**
Floccus no longer connects and I'm getting this error in my logs after the 10.21 update:

{"reqId":"xxx","level":3,"time":"2022-03-27T15:20:29-04:00","remoteAddr":"xxx","user":"xxx","app":"bookmarks","method":"POST","url":"/index.php/apps/bookmarks/public/rest/v2/lock","message":"An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'locked' in 'field list'","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"23.0.3.2","id":"6240b901e3598"}

**Server (please complete the following information):**
 - Database: [e.g. MySQL 5.3] MariaDB 10.3.4
 - PHP version: [e.g. v7.2] 7.4
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)] 23.03
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)] 10.21

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
A stack trace gives the location of the error in the code at various moments during execution. It's basically a list of <file path>#<line number> the nextcloud log might contain that along with the error.

**Comment by mobamoba** [comment]
What I posted is the only info in the Nextcloud log. The error shows up it looks like every 30 seconds if that helps at all.

**Comment by marcelklehr** [comment]
The error seems to indicates that you are not running the latest code, as the latest code is not referencing the locked column anymore.

**Comment by marcelklehr** [comment]
What is the latest migration for the bookmarks app? Can you run `SELECT * from oc_migrations where app = 'bookmarks';`

**Comment by mobamoba** [comment]
010002000Date20220319124721

**Comment by marcelklehr** [comment]
huh, that's the latest, that's good.

**Comment by marcelklehr** [comment]
Can you try uninstalling and reinstalling the app? This shouldn't delete any data.

**Comment by mobamoba** [comment]
Same error.

**Comment by marcelklehr** [comment]
I'm sorry, I would need to know where in the code the error originated from. Can you go to the bookmarks app directory and run `grep -rni 'locked' ./`

**Comment by mobamoba** [comment]
That grep outputs a huge amount because it includes things like "blocked" however, perhaps these last few lines will help?

./vendor/guzzlehttp/psr7/src/Response.php:60:        423 => 'Locked',
./lib/Controller/BookmarkController.php:816:                            return new JSONResponse(['status' => 'error', 'data' => 'Resource is already locked'], Http::STATUS_LOCKED);
./lib/Service/CrawlService.php:29:use OCP\Lock\LockedException;
./lib/Service/CrawlService.php:151:                     } catch (NotPermittedException | NoUserException | GenericFileException | LockedException | UrlParseError | InvalidPathException | NotFoundException $e) {
./lib/Service/LockManager.php:34:        * @param bool $locked
./lib/Service/LockManager.php:36:       public function setLock(string $userId, bool $locked): void {
./lib/Service/LockManager.php:38:               $value = $locked ? new DateTime() : new DateTime('@0'); // now or begin of UNIX time
./lib/Service/LockManager.php:41:                       ->set('locked_time', $qb->createNamedParameter($value, Types::DATETIME))
./lib/Service/LockManager.php:53:               $lockedAt = $qb->select('locked_time')
./lib/Service/LockManager.php:58:               if ($lockedAt === null) {
./lib/Service/LockManager.php:62:                       $dateTime = new DateTime($lockedAt);
./lib/Migration/Version004005000Date20210918124721.php:45:                      $table->addColumn('locked', Types::BOOLEAN, ['notnull' => false]);
./lib/Migration/Version010002000Date20220319124721.php:42:              $this->rootFolders = $qb->select('user_id', 'locked')->from('bookmarks_root_folders')->execute()->fetchAll();
./lib/Migration/Version010002000Date20220319124721.php:59:                      $table->dropColumn('locked');
./lib/Migration/Version010002000Date20220319124721.php:60:                      $table->addColumn('locked_time', Types::DATETIME, ['notnull' => false]);
./lib/Migration/Version010002000Date20220319124721.php:75:                      if ($rootFolder['locked'] != true) {
./lib/Migration/Version010002000Date20220319124721.php:80:                              ->set('locked_time', $qb->createPositionalParameter(new DateTime(), Types::DATETIME))

**Comment by marcelklehr** [comment]
mh. None of these results indicate where a 'locked' column is used in the actual code (Files in `Migrations` don't count as you've reported you've already ran all migrations)

**Comment by tetzlav** [comment]
I have a similar problem.

After update the app from v4.x to newer versions my bookmarks were lost because of changes in database scheme. After [recovering](https://github.com/nextcloud/bookmarks/wiki/Recovering-from-DB-Backup) the data by adding some new columns the app works fine again.

Today i tried to update to latest v10.2.1 an i got the same error:
```
Database error when running migration latest for app bookmarks
```
In the log i found:
```
Column not found: 1054 Unknown column 'locked' in 'field list'
```
Maybe i caused the problem with my manual migration last update:
```
MariaDB [owncloud]> DESCRIBE oc_bookmarks;
+---------------+------------------+------+-----+---------+----------------+
| Field         | Type             | Null | Key | Default | Extra          |
+---------------+------------------+------+-----+---------+----------------+
| id            | int(11)          | NO   | PRI | NULL    | auto_increment |
| url           | varchar(4096)    | NO   |     |         |                |
| title         | varchar(4096)    | NO   |     |         |                |
| user_id       | varchar(64)      | NO   | MUL |         |                |
| description   | varchar(4096)    | NO   |     |         |                |
| added         | int(10) unsigned | YES  |     | 0       |                |
| lastmodified  | int(10) unsigned | YES  | MUL | 0       |                |
| clickcount    | int(10) unsigned | NO   |     | 0       |                |
| last_preview  | int(10) unsigned | YES  | MUL | 0       |                |
| available     | tinyint(1)       | NO   | MUL | 1       |                |
| archived_file | bigint(20)       | YES  |     | NULL    |                |
| html_content  | longtext         | YES  |     | NULL    |                |
| text_content  | longtext         | YES  |     | NULL    |                |
+---------------+------------------+------+-----+---------+----------------+
MariaDB [owncloud]> SELECT * from oc_migrations where app = 'bookmarks';
+-----------+-----------------------------+
| app       | version                     |
+-----------+-----------------------------+
| bookmarks | 000014000Date20181002094721 |
| bookmarks | 000014000Date20181029094721 |
| bookmarks | 000016005Date20190402094721 |
| bookmarks | 001000007Date20190721094721 |
| bookmarks | 003000000Date20191123094721 |
| bookmarks | 003000000Date20191129094721 |
| bookmarks | 003000009Date20200505094721 |
| bookmarks | 003001000Date20200526094721 |
| bookmarks | 003001000Date20200526124721 |
| bookmarks | 003004000Date20200807124721 |
| bookmarks | 003004000Date20200817124721 |
| bookmarks | 004002000Date20210208124721 |
| bookmarks | 004003000Date20210718124721 |
| bookmarks | 004003001Date20210723124721 |
| bookmarks | 004005000Date20210918124721 |
+-----------+-----------------------------+
```
Should i delete the rows by do this?
```
DELETE from oc_migrations WHERE app = 'bookmarks';
```

**Comment by marcelklehr** [comment]
> After update the app from v4.x to newer versions my bookmarks were lost because of changes in database scheme.

Which newer versions exactly? Why did you not report this?

> Should i delete the rows by doing this?

No.

If `004005000Date20210918124721` has indeed been run, you should have a boolean column 'locked' in oc_bookmarks_root_folders, which is not the case apparently. So your migration state is inconsistent.

**Comment by mobamoba** [comment]
./lib/Controller/BookmarkController.php:816:                            return new JSONResponse(['status' => 'error', 'data' => 'Resource is already locked'], Http::STATUS_LOCKED);
./lib/Service/LockManager.php:36:       public function setLock(string $userId, bool $locked): void {
./lib/Service/LockManager.php:38:               $value = $locked ? new DateTime() : new DateTime('@0'); // now or begin of UNIX time
./lib/Migration/Version004005000Date20210918124721.php:45:                      $table->addColumn('locked', Types::BOOLEAN, ['notnull' => false]);
./lib/Migration/Version010002000Date20220319124721.php:42:              $this->rootFolders = $qb->select('user_id', 'locked')->from('bookmarks_root_folders')->execute()->fetchAll();
./lib/Migration/Version010002000Date20220319124721.php:59:                      $table->dropColumn('locked');
./lib/Migration/Version010002000Date20220319124721.php:75:                      if ($rootFolder['locked'] != true) {

**Comment by tetzlav** [comment]
> > After update the app from v4.x to newer versions my bookmarks were lost because of changes in database scheme.
> 
> Which newer versions exactly? Why did you not report this?

I just noticed, that somewhen 2 new collums were added:
```
	`html_content` longtext COLLATE utf8mb4_bin DEFAULT NULL,
	`text_content` longtext COLLATE utf8mb4_bin DEFAULT NULL,
```
so i added this in my database backup and the newer version shows all my bookmarks again. I cant remember the versions, but when the 2 collums were added?

> If `004005000Date20210918124721` has indeed been run, you should have a boolean column 'locked' in oc_bookmarks_root_folders, which is not the case apparently. So your migration state is inconsistent.

Sorry for crashing this issue, but what are my possibilities now?

**Comment by marcelklehr** [comment]
@tetzlav You can try adding the boolean column to make your db consistent with the migration state again, so that the update run through.

**Comment by tetzlav** [comment]
Ahh, thank you very much!
```
MariaDB [owncloud]> ALTER TABLE oc_bookmarks_root_folders ADD locked TINYINT(1) DEFAULT NULL;
Query OK, 0 rows affected (0.055 sec)
Records: 0  Duplicates: 0  Warnings: 0

MariaDB [owncloud]> select * from oc_bookmarks_root_folders;
+---------------+-----------+--------+
| user_id       | folder_id | locked |
+---------------+-----------+--------+
| xxxxxxxxxxxx  |         3 |   NULL |
| yyyyyyyyy     |         1 |   NULL |
| zzzzzzzzzzzzz |         2 |   NULL |
+---------------+-----------+--------+
3 rows in set (0.001 sec)

MariaDB [owncloud]> SELECT * from oc_migrations where app = 'bookmarks';
+-----------+-----------------------------+
| app       | version                     |
+-----------+-----------------------------+
| bookmarks | 000014000Date20181002094721 |
| bookmarks | 000014000Date20181029094721 |
| bookmarks | 000016005Date20190402094721 |
| bookmarks | 001000007Date20190721094721 |
| bookmarks | 003000000Date20191123094721 |
| bookmarks | 003000000Date20191129094721 |
| bookmarks | 003000009Date20200505094721 |
| bookmarks | 003001000Date20200526094721 |
| bookmarks | 003001000Date20200526124721 |
| bookmarks | 003004000Date20200807124721 |
| bookmarks | 003004000Date20200817124721 |
| bookmarks | 004002000Date20210208124721 |
| bookmarks | 004003000Date20210718124721 |
| bookmarks | 004003001Date20210723124721 |
| bookmarks | 004005000Date20210918124721 |
| bookmarks | 010002000Date20220319124721 |
+-----------+-----------------------------+
16 rows in set (0.000 sec)
```

**Comment by marcelklehr** [comment]
Feel free to join me on gitter/matrix again for a debugging session if you like :)

**Comment by mobamoba** [comment]
That's the only version I have. I there something I can manually to reforce the migration again or whatever might solve this?

**Comment by marcelklehr** [comment]
@mobamoba Mh, very strange. Then you had the same problem as @tetzlav
