### ISSUE TITLE
Option to disable automatic bookmarks backup to files

### ISSUE THREAD

**Issue by ottsimon** [nextcloud/bookmarks#1779]
Is there an option to disable the new automatic bookmarks backup to files?
I didn't find one.

If not, is it possible to add an option for that?

**Comment by marcelklehr** [comment]
Hey @DerFranke 
There is not, currently. Why do you want to disable it?

**Comment by DerFranke** [comment]
Hi @marcelklehr,

I use the app only to get access to my desktop bookmarks on the go (via Floccus one way sync).
They are already backed up by my browser.
So, this feature just creates files, I have no use for.

**Comment by marcelklehr** [comment]
I see. IMHO, when syncing with floccus it's good practice to keep backups, as sync is not a backup. If you already have a backup the files are perhaps superfluous, but it will only keep 15 backup files at max, so shouldn't be too much of a strain on your disk. I'll gauge demand for an opt-out button, over the next weeks.

**Comment by SeanDS** [comment]
+1 for this. I have an existing backup solution and don't need this feature. Even if it stays, perhaps they can be stored in a hidden folder instead of `Bookmark Backups` on the top level alongside `Bookmarks` which is kinda ugly to me. Perhaps the hidden folder should even be inside the `Bookmarks` directory.

**Comment by derritter88** [comment]
+1 from me as well.

**Comment by Andandaran** [comment]
+1

**Comment by TheMatzy** [comment]
+1 nice to have :)

**Comment by zevlee** [comment]
I wish to indicate desire to disable backup as well. It has been confirmed that this feature does not currently exist.

### Discussed in https://github.com/nextcloud/bookmarks/discussions/1778

<div type='discussions-op-text'>

<sup>Originally posted by **zevlee** March 29, 2022</sup>
Is there a way to disable Bookmarks Backups to Files? I do not find an option to do so.

I use Nextcloud Bookmarks with Floccus, so my bookmarks are saved already in my browser.</div>

**Comment by liquidat** [comment]
Reasons to deactivate the backup function are:
* It clutters my well designed directory layout. I don't want random folders to pop up there. Don't mess with my files. At least let me configure the directory!
* I use the app differently. For me it is a long term database of stuff I might need again in the future. The bookmarks are backuped together with the rest of the Nextcloud database.

**Comment by marcelklehr** [comment]
https://github.com/nextcloud/bookmarks/releases/tag/v10.3.0 is now published allowing to turn off backups.

**Comment by derritter88** [comment]
@marcelklehr : Just as a side note/question: I am not sure if this is a feature or a bug but I recognised that I always got two folders: "Bookmarks Backups" & "Lesezeichen-Backups"

**Comment by SeanDS** [comment]
> https://github.com/nextcloud/bookmarks/releases/tag/v10.3.0 is now published allowing to turn off backups.

Thanks for the quick fix - and great work on this app in general - much appreciated :-)

**Comment by mepreston** [comment]
1) this need to be a global admin option to disable it for everyone. i don't want anyone on my system creating backups.
2) the box "enable bookmarks backup" is not checked
3) it is still generating backups
4) deinstalling this from my nextcloud env, i'm done with it

**Comment by marcelklehr** [comment]
fyi v10.4.0 defaults to backups off for everyone.
