### ISSUE TITLE
Add "Copy URL" to the right-click menu options

### ISSUE THREAD

**Issue by clarkhenry** [nextcloud/bookmarks#1780]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to **copy** a bookmark URL from the bookmarks app. It takes too many clicks.

**Describe the solution you'd like**
Add "copy URL" to the right-click menu in the bookmark web app.

**Describe alternatives you've considered**
The current quickest work-around is to check the checkbox in app for the bookmark I'm interested in. Then, right-click will allow me to copy link (via my browser's default right-click menu options).

**Additional context**
Right-clicking used to pop-up the default browser right-click menu options. Now, right-clicking pops up a custom Bookmarks App menu, but from there, it takes several more clicks to view and copy the URL, if I want to do so natively in the Bookmarks App. My current, most convenient, work-around is a hack which combines using the Bookmark App feature (a new right-click menu) with my browser feature (its native right-click menu).

Before a recent update to the Bookmarks App, this used to take 2 clicks: right-click (opens browser's default right-click menu) -> click on "copy link address".

Now it's 3 clicks, a hack, and not very obvious for users that the work-around (provided above) is possible.

**Comment by marcelklehr** [comment]
Hey @clarkhenry 

Great point! I'll add this :)
