### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by chemicalsam** [nextcloud/bookmarks#1782]
The nextbookmark iOS app is no longer available from the App Store, it never worked really anyways. 

Can we get support in the next cloud or something for iOS users?

**Comment by marcelklehr** [comment]
If there is enough demand I can look into releasing a floccus version for iOS. Adding a thumbs up on the original post for your support of this suffices.

**Comment by cmalvi** [comment]
Please this would be very appreciate.

**Comment by marcelklehr** [comment]
Btw, any reason for this @altepizza ?

**Comment by altepizza** [comment]
In the current crazy times I'm unfortunately lacking time and resources to keep the app in the app store. You can still sideload it (if you own a mac) and I plan to re-publish it once I'm fully on track again but I cannot promise any date (yet).

**Comment by marcelklehr** [comment]
@altepizza I see. I wish you all the best and thanks for all your efforts so far :)

**Comment by radiochild577** [comment]
@altepizza would you be willing to post an IPA that we could sideload? Unfortunately I don't have a Mac so can't build the ipa myself.

**Comment by cmalvi** [comment]
You can sideload it with AltStore

**Comment by altepizza** [comment]
@radiochild577 @S0ulf3re I added the `.ipa` as a release in my [repo](https://github.com/altepizza/nextBookmark/releases/tag/v1.11.2). At least when I'm dropping it via Finder on my phone, it installs and actually runs :P. I would be curious how it works for you.

**Comment by S0ulf3re** [comment]
It does not seem to run
<img width="399" alt="Screen Shot 2022-05-18 at 11 46 56" src="https://user-images.githubusercontent.com/50301900/169085916-5de2d8b9-7c21-4734-9d64-bdcf1677dd37.png">

**Comment by getwet** [comment]
Don't forget to add a donation button! ;-)

**Comment by marcelklehr** [comment]
floccus for iOS is now available in the Apple App Store: https://apps.apple.com/us/app/floccus/id1626998357

**Comment by cmalvi** [comment]
Thanks! For me stuck loading after entering the nextcloud url

**Comment by marcelklehr** [comment]
Please open issues on the relevant repository: github.com/floccusaddon/floccus

**Comment by S0ulf3re** [comment]
That’s great to hear! 👍
