### ISSUE TITLE
Warning in log if guest account is active

### ISSUE THREAD

**Issue by mattsches** [nextcloud/bookmarks#1789]
**Describe the bug**
The following warnings appear in the NC log when a guest account is in place:
```
sudo -u www-data php ./occ log:watch
  Warning  bookmarks          Could not create folder                                                                                              2022-04-08T09:15:01+00:00 

  Warning  bookmarks          Extracting notes from user guest.account@example.org errored                                                          2022-04-08T09:15:01+00:00
```

**To Reproduce**
Enable both the guest accounts app and the bookmarks app, invite a guest user.

**Expected behavior**
No warnings in log

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - HTTP server: apache2
 - Database: MySQL 10.3.34
 - PHP version: 8.0.17
 - Nextcloud version: 23.0.3
 - Bookmarks app version: 10.2.1
 - Activated Nextcloud Apps:
   - accessibility: 1.9.0
   - activity: 2.15.0
   - appointments: 1.12.2
   - bookmarks: 10.2.1
   - bruteforcesettings: 2.3.0
   - calendar: 3.2.2
   - circles: 23.1.0
   - cloud_federation_api: 1.6.0
   - cms_pico: 1.0.18
   - collectives: 0.22.22
   - comments: 1.13.0
   - contacts: 4.1.0
   - contactsinteraction: 1.4.0
   - cookbook: 0.9.11
   - dashboard: 7.3.0
   - dav: 1.21.0
   - deck: 1.6.1
   - eidlogin: 1.0.7
   - federatedfilesharing: 1.13.0
   - federation: 1.13.0
   - files: 1.18.0
   - files_markdown: 2.3.5
   - files_pdfviewer: 2.4.0
   - files_rightclick: 1.2.0
   - files_sharing: 1.15.0
   - files_texteditor: 2.14.0
   - files_trashbin: 1.13.0
   - files_versions: 1.16.0
   - files_videoplayer: 1.12.0
   - firstrunwizard: 2.12.0
   - forms: 2.4.0
   - gpoddersync: 3.2.0
   - gpxpod: 4.3.0
   - groupfolders: 11.1.2
   - guests: 2.1.0
   - logreader: 2.8.0
   - lookup_server_connector: 1.11.0
   - maps: 0.1.10
   - nextcloud_announcements: 1.12.0
   - notes: 4.3.1
   - notifications: 2.11.1
   - oauth2: 1.11.0
   - password_policy: 1.13.0
   - passwords: 2022.4.20
   - phonetrack: 0.7.0
   - photos: 1.5.0
   - privacy: 1.7.0
   - provisioning_api: 1.13.0
   - qownnotesapi: 21.12.0
   - recommendations: 1.2.0
   - richdocuments: 5.0.3
   - serverinfo: 1.13.0
   - settings: 1.5.0
   - sharebymail: 1.13.0
   - spreed: 13.0.4
   - support: 1.6.0
   - survey_client: 1.11.0
   - systemtags: 1.13.0
   - tasks: 0.14.4
   - text: 3.4.1
   - theming: 1.14.0
   - twofactor_backupcodes: 1.12.0
   - unsplash: 1.2.4
   - updatenotification: 1.13.0
   - viewer: 1.7.0
   - weather_status: 1.3.0
   - workflowengine: 2.5.0

**Comment by c0r3dump3d** [comment]
Hi, I have the same problem but in my case is for every user:

```
Warning  bookmarks          Could not create folder                                                                                                                                                                                                
Warning  bookmarks          Extracting notes from user test errored 
```

- OS: CentOS Linux release 7.9.2009
- HTTP Server: Server version: Apache/2.4.6 (CentOS)
- Database: PostgreSQL 12.8
- PHP version: 7.4.28
- Nextcloud: 22.2.3
- Bookmarks app version: 10.3.1
- Activated Nextcloud Apps:
- accessibility: 1.8.0
```
  - activity: 2.15.0
  - apporder: 0.15.0
  - bookmarks: 10.3.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.2.2
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.1.0
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - deck: 1.5.6
  - drawio: 1.0.2
  - external: 3.9.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_antivirus: 3.2.2
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.5.0
  - impersonate: 1.9.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.3.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.3.2
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.6.1
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.14.0
  - recommendations: 1.1.0
  - riotchat: 0.11.3
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.5
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.4
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_email: 2.3.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.12.0
  - user_ldap: 1.12.1
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
```
