### ISSUE TITLE
Class OCA\Bookmarks\Service\FileCache missing method

### ISSUE THREAD

**Issue by smartbyte** [nextcloud/bookmarks#1791]
After upgrading to NC 24 beta 3 the bookmarks app does not work anymore.

Error message:
Class OCA\Bookmarks\Service\FileCache contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (OCP\ICache::isAvailable) at *NC PATH*/apps/bookmarks/lib/Service/FileCache.php#17

OCP/ICache has implements a new static method isAvailable.

To fix this issue, please add the following line to NC/apps/bookmarks/lib/Service/FileCache.php

public static function isAvailable(): bool { return true; }

**Comment by marcelklehr** [comment]
Thank you @smartbyte :)
