### ISSUE TITLE
Description/notes not imported from Delicious export

### ISSUE THREAD

**Issue by shtrom** [nextcloud/bookmarks#181]
When importing bookmarks from a Delicious export, the description is ignored, while I would have expected to see it in the notes. The rest is correctly imported.

The HTML is a bit dodgy (party like it's 1995!), but at least is regular, here's an example.

```
<DL><p>
<DT><A HREF="http://tylervigen.com/spurious-correlations" ADD_DATE="1434252232" PRIVATE="0" TAGS="science,correlation,fallacy,TylerVigen">15 Insane Things That Correlate With Each Other</A>
<DD>Spurious Correlations was a project I put together as a fun way to look at correlations and to think about data. Empirical research is interesting, and I love to wonder about how variables work together. The charts on this site aren't meant to imply causation nor are they meant to create a distrust for research or even correlative data. Rather, I hope this project fosters interest in statistics and numerical research.
```

**Comment by shtrom** [comment]
Ah, the date (from `ADD_DATE`) doesn't seem to be imported either: all bookmarks are created with the date/time of import.

**Comment by blizzz** [comment]
@shtrom Could you check whether this PR fixes it? It needs reviewers and testers :) https://github.com/owncloud/bookmarks/pull/120

**Comment by shtrom** [comment]
@blizzz: #120 doesn't quite do it, but could still be useful.

**Comment by shtrom** [comment]
There (:

I just tested this by re-importing all my bookmarks, and got the expected result.

There is something weird but, I think, unrelated, for the title and URL of some internal sites which the app, somehow, tried to connect to, (I guess) got redirected to the public site, and used the title and URL of that, instead of the one in the export file, but doesn't seem to come from addBookmark()...
