### ISSUE TITLE
More bookmark information in flow output.

### ISSUE THREAD

**Issue by landowark** [nextcloud/bookmarks#1814]
Currently there isn't a lot of useful information that comes out of the flow event for bookmark creation, only eventType and eventName.

Would it be possible to get some information on the bookmark that triggers the event such as ID or title?

**Comment by marcelklehr** [comment]
Wow, I'm intrigued what you'll build with it :)

Regarding your question: You should be able to get the "EntitySubject" out of the RuleMatcher object passed to onEvent. That should be a [Bookmark](https://github.com/nextcloud/bookmarks/blob/master/lib/Db/Bookmark.php) object then with all the good stuff. (I know the flow APIs are horrible..).

**Comment by landowark** [comment]
Hmm. Okay. I'm sending the data with a webhook and all the information I'm getting is the eventType and eventName.

**Comment by marcelklehr** [comment]
So, are you creating a bookmark via flow or listening for created bookmarks via flow?

**Comment by landowark** [comment]
I'm listening for created bookmarks and performing scraping of the url.

**Comment by marcelklehr** [comment]
But you're using the webhook app. That's who you'll have to talk to to get more data out, then.

**Comment by jrb0001** [comment]
> Regarding your question: You should be able to get the "EntitySubject" out of the RuleMatcher object passed to onEvent. That should be a [Bookmark](https://github.com/nextcloud/bookmarks/blob/master/lib/Db/Bookmark.php) object then with all the good stuff. (I know the flow APIs are horrible..).

I tried implementing this into the webhook app myself but there doesn't seem to be any way to get the subject out of the `IRuleMatcher`. It is only passed to `IEntityCheck` while evaluating all the checks. I mean, I could extract it through reflection and/or `IEntityCheck`+global variable, but I would be really surprised if such a PR would be accepted by them.

Everything based on `GenericEvent` seem to carry the subject inside the event. Is there a reason why the bookmarks app doesn't do something like this too?

**Comment by marcelklehr** [comment]
How about IRuleMatcher#getEntity() ?
