### ISSUE TITLE
Bookmarks backup won't start

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/bookmarks#1829]
Hi,

since version 10.4.0 bookmark backup won't start.

I reactivated it in settings, checked folder (same as version before) and waited some days.
Nothing happends. Last backup is created in version 10.3.1.

I'm running nc 22.2.8.

Thanks for hints for checking or fixing it.

**Comment by marcelklehr** [comment]
Confirmed. I had disabled it by default but made a mistake apparently. Next release will have backups working again. :hearts:
