### ISSUE TITLE
Dragging a tag - bug or incomplete feature?

### ISSUE THREAD

**Issue by africanforest** [nextcloud/bookmarks#183]
It looks like a tag could be applied to bookmarks by drag&drop - because the mouse cursor changes to "hand" as soon as a tag is dragged, and it even follows the cursor while being dragged - but nothing happens when that tag is dropped to a bookmark.

So i wonder why the cursor actually shows the hand and why the tag can be dragged at all, if there is no function behind it?

(OC 8.1, Firefox 39, MacBookPro)

**Comment by blizzz** [comment]
not aware we had this feature
