### ISSUE TITLE
Get many errors at first bookmark app opening

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/bookmarks#1830]
Hi,

if I open the bookmark app with many links (around 100) I get many errors at first loading the bookmarks.
After these errors, the bookmark list is empty.

Then I had to go back to dashboard and tried it a second one.
After the second try, bookmark will be loaded.

Is there any fix or workaround?

These are the errors, only in german. But will help, i think.

![grafik](https://user-images.githubusercontent.com/4992106/174129179-abf7828c-b330-4445-b65f-83e979d31d38.png)

**Comment by MartinOstrava** [comment]
I am experiencing the very same issue. In the app around 300 bookmarks, folders are visible, but empty. Tried to re-install app, tried to delete all folders and import from backup (html file), The same behavior, folders empty.

**Comment by marcelklehr** [comment]
Can you check the nextcloud log for errors?

**Comment by Kilohotelbravo** [comment]
I don't know, if it is the same issue here, but it is very probable. The folders in my nextcloud-installation are visible but empty. Yesterday I had a lot of bookmarks.   

The nextcloud log shows this error: (May it helps ...) 

OC\DB\Exceptions\DbalException: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE folder_tree(item_id, parent_folder, type, idx) AS ( SELECT cast(9 as U' at line 1
    /...de/lib/private/DB/ConnectionAdapter.php - line 69:
    OC\DB\Exceptions\DbalException::wrap(Doctrine\DBA ... {})
    /...de/apps/bookmarks/lib/Db/BookmarkMapper.php - line 246:
    OC\DB\ConnectionAdapter->executeQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Db/BookmarkMapper.php - line 239:
    OCA\Bookmarks\Db\BookmarkMapper->findEntitiesWithRawQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Controller/BookmarkController.php - line 379:
    OCA\Bookmarks\Db\BookmarkMapper->findAll("Linkowner", OCA\Bookmark ... {})
    /...de/lib/private/AppFramework/Http/Dispatcher.php - line 225:
    OCA\Bookmarks\Controller\BookmarkController->getBookmarks(-1, null, "or", "", [], 10, false, 60, null, null, null, null)
    /...de/lib/private/AppFramework/Http/Dispatcher.php - line 133:
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... {}, "getBookmarks")
    /...de/lib/private/AppFramework/App.php - line 172:
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... {}, "getBookmarks")
    /...de/lib/private/Route/Router.php - line 298:
    OC\AppFramework\App::main("OCA\\Bookma ... r", "getBookmarks", OC\AppFramew ... {}, [ "bookmarks ... "])
    /...de/lib/base.php - line 1023:
    OC\Route\Router->match("/apps/bookm ... k")
    /...de/index.php - line 36:
    OC::handleRequest()
Verursacht durch Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE folder_tree(item_id, parent_folder, type, idx) AS ( SELECT cast(9 as U' at line 1
    /...de/3rdparty/doctrine/dbal/src/Connection.php - line 1780:
    Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Doctrine\DBA ... {}, Doctrine\DBAL\Query {})
    /...de/3rdparty/doctrine/dbal/src/Connection.php - line 1719:
    Doctrine\DBAL\Connection->handleDriverException(Doctrine\DBA ... {}, Doctrine\DBAL\Query {})
    /...de/3rdparty/doctrine/dbal/src/Connection.php - line 1067:
    Doctrine\DBAL\Connection->convertExceptionDuringQuery(Doctrine\DBA ... {}, "WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/lib/private/DB/Connection.php - line 261:
    Doctrine\DBAL\Connection->executeQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "], null)
    /...de/lib/private/DB/ConnectionAdapter.php - line 66:
    OC\DB\Connection->executeQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Db/BookmarkMapper.php - line 246:
    OC\DB\ConnectionAdapter->executeQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Db/BookmarkMapper.php - line 239:
    OCA\Bookmarks\Db\BookmarkMapper->findEntitiesWithRawQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Controller/BookmarkController.php - line 379:
    OCA\Bookmarks\Db\BookmarkMapper->findAll("Linkowner", OCA\Bookmark ... {})
    /...de/lib/private/AppFramework/Http/Dispatcher.php - line 225:
    OCA\Bookmarks\Controller\BookmarkController->getBookmarks(-1, null, "or", "", [], 10, false, 60, null, null, null, null)
    /...de/lib/private/AppFramework/Http/Dispatcher.php - line 133:
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... {}, "getBookmarks")
    /...de/lib/private/AppFramework/App.php - line 172:
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... {}, "getBookmarks")
    /...de/lib/private/Route/Router.php - line 298:
    OC\AppFramework\App::main("OCA\\Bookma ... r", "getBookmarks", OC\AppFramew ... {}, [ "bookmarks ... "])
    /...de/lib/base.php - line 1023:
    OC\Route\Router->match("/apps/bookm ... k")
    /...de/index.php - line 36:
    OC::handleRequest()
Verursacht durch Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE folder_tree(item_id, parent_folder, type, idx) AS ( SELECT cast(9 as U' at line 1
    /...de/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php - line 94:
    Doctrine\DBAL\Driver\PDO\Exception::new(PDOException ... ]})
    /...de/3rdparty/doctrine/dbal/src/Connection.php - line 1057:
    Doctrine\DBAL\Driver\PDO\Statement->execute()
   /...de/lib/private/DB/Connection.php - line 261:
    Doctrine\DBAL\Connection->executeQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "], null)
    /...de/lib/private/DB/ConnectionAdapter.php - line 66:
    OC\DB\Connection->executeQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Db/BookmarkMapper.php - line 246:
    OC\DB\ConnectionAdapter->executeQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Db/BookmarkMapper.php - line 239:
    OCA\Bookmarks\Db\BookmarkMapper->findEntitiesWithRawQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Controller/BookmarkController.php - line 379:
    OCA\Bookmarks\Db\BookmarkMapper->findAll("Linkowner", OCA\Bookmark ... {})
    /...de/lib/private/AppFramework/Http/Dispatcher.php - line 225:
    OCA\Bookmarks\Controller\BookmarkController->getBookmarks(-1, null, "or", "", [], 10, false, 60, null, null, null, null)
    /...de/lib/private/AppFramework/Http/Dispatcher.php - line 133:
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... {}, "getBookmarks")
    /...de/lib/private/AppFramework/App.php - line 172:
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... {}, "getBookmarks")
    /...de/lib/private/Route/Router.php - line 298:
    OC\AppFramework\App::main("OCA\\Bookma ... r", "getBookmarks", OC\AppFramew ... {}, [ "bookmarks ... "])
    /...de/lib/base.php - line 1023:
    OC\Route\Router->match("/apps/bookm ... k")
    /...de/index.php - line 36:
    OC::handleRequest()
Verursacht durch PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE folder_tree(item_id, parent_folder, type, idx) AS ( SELECT cast(9 as U' at line 1
    /...de/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php - line 92:
    PDOStatement->execute(null)
    /...de/3rdparty/doctrine/dbal/src/Connection.php - line 1057:
    Doctrine\DBAL\Driver\PDO\Statement->execute()
    /...de/lib/private/DB/Connection.php - line 261:
    Doctrine\DBAL\Connection->executeQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "], null)
    /...de/lib/private/DB/ConnectionAdapter.php - line 66:
    OC\DB\Connection->executeQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Db/BookmarkMapper.php - line 246:
    OC\DB\ConnectionAdapter->executeQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Db/BookmarkMapper.php - line 239:
    OCA\Bookmarks\Db\BookmarkMapper->findEntitiesWithRawQuery("WITH RECURS ... C", [ 9,"folder" ... "], [ 1,2,2,2,2, ... "])
    /...de/apps/bookmarks/lib/Controller/BookmarkController.php - line 379:
    OCA\Bookmarks\Db\BookmarkMapper->findAll("Linkowner", OCA\Bookmark ... {})
    /...de/lib/private/AppFramework/Http/Dispatcher.php - line 225:
    OCA\Bookmarks\Controller\BookmarkController->getBookmarks(-1, null, "or", "", [], 10, false, 60, null, null, null, null)
    /...de/lib/private/AppFramework/Http/Dispatcher.php - line 133:
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... {}, "getBookmarks")
    /...de/lib/private/AppFramework/App.php - line 172:
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... {}, "getBookmarks")
    /...de/lib/private/Route/Router.php - line 298:
    OC\AppFramework\App::main("OCA\\Bookma ... r", "getBookmarks", OC\AppFramew ... {}, [ "bookmarks ... "])
    /...de/lib/base.php - line 1023:
    OC\Route\Router->match("/apps/bookm ... k")
    /...de/index.php - line 36:
    OC::handleRequest()

**Comment by marcelklehr** [comment]
Which database and version do you folks use?

**Comment by marcelklehr** [comment]
Yep, MySQL 8 is required for this feature. I'll rollback the commit that introduced this and will do a major version bump.

**Comment by Kilohotelbravo** [comment]
Thanks a lot 😀

**Comment by Kilohotelbravo** [comment]
From my position the version 10.5.1 is doing fine. The bookmarks reappear in the app. Perfect job!
