### ISSUE TITLE
Fractional bookmark number

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/bookmarks#1832]
**Describe the bug**
As far as I remember when I last tested this app a year or so ago, this number next to the bookmarks used to be a counter of bookmarks.
![image](https://user-images.githubusercontent.com/47887158/174444220-222662d2-9208-4ea8-b8c0-71849786b492.png)

Why is it showing a fractional bookmark number?

**To Reproduce**
1. Go to 'Bookmarks'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8.1 Update
 - Browser: Chrome
 -  - Version: 102.0.5005.115

**Server (please complete the following information):**
 - OS: Linux
 - HTTP server: [e.g. nginx 1.1]
 - Database: [e.g. MySQL 5.3]
 - PHP version: [e.g. v7.2]
 - Nextcloud version: 24.0.1
 - Bookmarks app version: 10.4.0
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
mh, there should be a "K" to the right of the fraction, indicating thousand. I'll investigate.

**Comment by InfamousUser** [comment]
Ooooh, okay, that cleared a few things up.
