### ISSUE TITLE
[Question] "remote user" changed XXX, and XXX was created in a public folder 

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/bookmarks#1839]
Yesterday, I updated nextcloud to latest 24.02 and enabled option
![obraz](https://user-images.githubusercontent.com/3769853/176995849-e58bb93c-b90c-4e0b-ac5a-41ec6362525c.png)

Today in notifications, I saw few strange items like
- "remote user" changed XXX,
- XXX was created in a public folder 
Items are connected with txt and pdf files which are in Bookmarks folder in Files app.

Is it connected with this function?
Who is "remote user"?
Is it accessible by other people from Internet (public folder)

Is there any documentation for this feature?

**Comment by marcelklehr** [comment]
This doesn't seem to have anything to do with enabling network access in the bookmarks app. The bookmarks app does store bookmarked files in the Bookmarks folder in files, but it does not create a public folder for you. You should be able to check access rights on the respective files by going into file details in the files app and going to sharing.

Perhaps this wording appears, because no user is logged in at the time of creating the files (in the cron job).

**Comment by pawlosck** [comment]
Ok, I know, why these files were appear in nextcloud. This is probably connected with this feature. I saw this description in my bookmark app, but still I don't know, why it was named as remote user and public folder. 

`Bookmarks to files on the web like photos or PDFs will automatically be saved to your Nextcloud files, so you can still find them even when the link goes offline. `

**Comment by gellenburg** [comment]
> Ok, I know, why these files were appear in nextcloud. This is probably connected with this feature. I saw this description in my bookmark app, but still I don't know, why it was named as remote user and public folder.
> 
> `Bookmarks to files on the web like photos or PDFs will automatically be saved to your Nextcloud files, so you can still find them even when the link goes offline. `

Same thing is happening to me. It's also filling up my storage and consuming all the quota I have. (I use External Storage for most of my storage.)

It would be nice if you could specify the location where these files are downloaded to rather than just assuming the best location to store them.

**Comment by marcelklehr** [comment]
> It would be nice if you could specify the location where these files are downloaded to rather than just assuming the best location to store them.

You can specify the location in the settings in the app

**Comment by SimJoSt** [comment]
Would it be at least possible to change the user to "Bookmaks app"? "remote user" could be anything. Nextcloud, another user, a user without an account with a share link with editing permissions, etc.
And it would be great to disable the notification.
