### ISSUE TITLE
Subfolders are shown as siblings instead of children

### ISSUE THREAD

**Issue by godfuture** [nextcloud/bookmarks#1858]
**Describe the bug**
I have many bookmarks. When I browse the folder structure, I noticed that from 6. subfolder on the children were not spaced to the right as they usually do. These child subfolder appeared as sibiling of the currently opened folder. But as said, this happens only from the 6. folder level in deep folder structures. Folders above are correctly spaced as subfolder.

**To Reproduce**
1. Create at least 7 subfolders
2. Navigate to the lowest level
3. Check, if the children are spaced in comparison to their parent folder

**Expected behavior**
No matter how deep the structure is, all subfolders should be spaced to the right compared to their parent.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4669278/183066066-9849e660-7cfa-4bdc-939a-94be20b3b95a.png)

**Desktop (please complete the following information):**
 - OS: Win x64
 - Browser: Firefox
 - Version: 103.01

**Server (please complete the following information):**
 - OS: Debian 10
 - HTTP server: nginx
 - Database: mariadb 6
 - PHP version: 8.0
 - Nextcloud version: 23.0.5
 - Bookmarks app version: 11.0.1
 - Activated Nextcloud Apps:
 - Nextcloud configuration: 
 - Nextcloud external user backend: -

**Additional context**

**Web server error log**
```
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
```

**Browser log**
```
```

**Comment by marcelklehr** [comment]
Hello @godfuture

Thank you for your feedback. 7 layers is a lot :D That being said, I'll have another look at how this is implemented, I believe I did this for a reason, though. Maybe because the sidebar has a fixed width, i don't remember exactly.

**Comment by godfuture** [comment]
I think modern displays have a lot space to show even deeper structures. Probably this can be optimised for mobile view. But if there is plenty of space, why not letting it to unfold till eternity :D

**Comment by marcelklehr** [comment]
> why not letting it to unfold till eternity

The problem is that I have to add code for each layer.
