### ISSUE TITLE
List only ever shows 42 bookmarks

### ISSUE THREAD

**Issue by JomerDev** [nextcloud/bookmarks#1876]
**Describe the bug**
The UI only ever shows 42 links per folder. It doesn't load more/the next page even if I scroll all the way down. There is no button to switch to the next page in the list either. If I change the sort order I get a new set of links shown, meaning there are more than 42 in the folder. But only 42 are shown
I'm also getting `Unable to count bookmarks` error notifications now and then

**To Reproduce**
Have more than 42 links in a folder. Open the folder in the UI. See that only 42 links are shown

**Expected behavior**
A way to see more than 42 links

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 104

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - HTTP server: Docker image
 - Database: Postgres
 - PHP version: Don't know
 - Nextcloud version: 24.0.4
 - Bookmarks app version: 11.0.1

**Additional context**
There is no error in either the nextcloud or the browser log

**Comment by takagiwa** [comment]
Hello. I have same problem.

Desktop (please complete the following information):

- OS: Windows 10 and 11
- Browser: Chrome
- Version: 104

Server (please complete the following information):

- OS: FreeBSD 13.1-RELEASE-p1
- HTTP server: nginx/1.22.0
- Database: MySQL 8.0.29
- PHP version: PHP 7.4.30
- Nextcloud version: 24.0.4
- Bookmarks app version: 11.0.1

**Comment by JomerDev** [comment]
Looking into this a bit more, it seems like the problem is in the VirtualScroll component [here](https://github.com/nextcloud/bookmarks/blob/f88683d06c593eea3351b28d55ce53ad871bb150/src/components/VirtualScroll.vue#L81)

One, as you can see in the screenshot there are four empty entries in there. I don't know where they come from, they are not rendered, but they make it impossible for the check 
`if (!this.reachedEnd && upperPaddingItems + renderedItems > (this.$slots.default ? this.$slots.default.length : 0))`
to ever be true.
![image](https://user-images.githubusercontent.com/5282863/186115193-37c3ec22-5960-4a19-8843-d7ab7d7db7db.png)

The second issue I found is that even without those four empty entries the check would still fail. In my tests `upperPaddingItems + renderedItems` never added to more than 42 when scrolled all the way down, making the greater than check against the default.length which is also 42 always fail

In both cases `load-more` is never emitted

**Comment by LxGuru** [comment]
Hello. I have same problem.

Desktop (please complete the following information):

    OS: OpenSuSE Leap 15.4 (x86_64)
    Browser: Firefox
    Version: 91.13.0esr (64-bit)

Server (please complete the following information):

    OS: OpenSuSE Leap 15.4 (aarch64 @ Pi4)
    HTTP server: Apache/2.4.51 (Linux/SUSE)
    Database: mysql  Ver 15.1 Distrib 10.6.9-MariaDB,
    PHP version: PHP Version 7.4.25
    Nextcloud version: 24.0.4
    Bookmarks app version: 11.0.1

**Comment by sequent5** [comment]
same problems with latest bookmark.

**Comment by marcelklehr** [comment]
Confirmed. Sorry for the wait! I'll look into this now
