### ISSUE TITLE
Bookmarks Don't Show

### ISSUE THREAD

**Issue by stevepeo** [nextcloud/bookmarks#1897]
Hi

I’m looking for help please. When I add a bookmark, it initially shows as I would expect, however when I go back I an see it in the ‘numbers’ - The Broken link showing is a deliberate test.

- I’ve tried with several user accounts,
- Both Bookmarks and Nextcloud are fully upto date, notably prior to last update of Bookmarks I used to get a message 'No Bookmarks Here' but since the update I just see as per the attached screenshot.
- I've tried this with Chrome, Firefox, Edge and also using an Android phone both via browser and the Bookmarks App

Thanks

![BMerror](https://user-images.githubusercontent.com/113470675/191751831-856698f6-066b-49a9-9077-a1927b812e4f.JPG)

**Comment by marcelklehr** [comment]
Hi,

Which bookmarks version are you running? Which mysql variant and version? Are there any errors at the end of data/nextcloud.log?

**Comment by stevepeo** [comment]
Hi

Tahnks for your reply

Nextcloud 24.0.5
Bookmarks 11.0.2
MySql is Linux 5.7.39 (I'm unable to control this but believe its v8 will be available "shortly")

I've look at the log and see pages upon pages, much of which seems to be repeated;

o/v2/remote.php"],"function":"require_once"}],"File":"/var/www/vhosts/xxxx.xx/cloud.xxxx.xx/apps/dav/lib/Connector/Sabre/Directory.php","Line":242,"message":"File with name /.Contacts-Backup/2022-09-05_20-20-13.vcf could not be located","exception":{},"CustomMessage":"File with name /.Contacts-Backup/2022-09-05_20-20-13.vcf could not be located"}}
{"reqId":"YxZSsbveYz2RJynHHxMC5gAAAAg","level":3,"time":"2022-09-05T19:49:06+00:00","remoteAddr":"212.159.60.103","user":"xxxxxxxxxx","app":"index","method":"GET","url":"/index.php/apps/bookmarks/public/rest/v2/bookmark?folder=-1&page=-1","message":"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE folder_tree(item_id, parent_folder, type, idx) AS ( SELECT cast(1 as U' at line 1","userAgent":"Bookmarks for Nextcloud","version":"24.0.4.1","exception":{"Exception":"OC\\DB\\Exceptions\\DbalException","Message":"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'RECURSIVE folder_tree(item_id, parent_folder, type, idx) AS ( SELECT cast(1 as U' at line

**Comment by marcelklehr** [comment]
As noted in https://github.com/nextcloud/bookmarks/releases/tag/v11.0.0 mysql v8 is required starting with version 11

**Comment by stevepeo** [comment]
ah, ok.  Thanks.

Is there a way of installing a legacy version?  If I try bookmarks seems to (naturally) update to the latest version.

**Comment by marcelklehr** [comment]
You can grab the latest v10 release from [releases](https://github.com/nextcloud/bookmarks/releases) and extract it into your apps/ directory on the server. Downgrading is on your own risk, though, but in this case I don't see why it shouldn't work, so I think you're good to go.
