### ISSUE TITLE
Unable to DELETE all Bookmarks AGAIN!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by tchap2** [nextcloud/bookmarks#1899]
**How many times was function requested to delete all bookmarks at once???? NUMEROUS over 4 previous years.**

I woke up today, finding out that all of my bookmarks were being duplicated (a cummulative 30,000 bookmarks, over 100 folders). My client "Floccus" simply could not finish syncing. I wanted to delete all bookmarks and start fresh, but couldn't do so.

WHY isnt it possible to delete ALL bookmarks at once? This feature used to be available before upgrade to 11.0.3. 
Now, one has to click on irritting "three dots" of EVERY SINGLE folder to delete it. Settings (lower left) don't show that option. Menu bar on left doesn't show any delete options.

Also, previously, it was very easy to have different folders, one for each member of family. Now, there is only one and all bookmarksa re lumped into it.

I can see you added new fatures, but why do you ALWAYS have to break something along the way????

I've been stuck for the past 3 hours figuring out how to delete all bookmarks at once.

**Describe the bug**

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS X]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7]
 - HTTP server: [e.g. nginx 1.1]
 - Database: [e.g. MySQL 5.3]
 - PHP version: [e.g. v7.2]
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)]
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)]
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
Hello @tchap2, let's take a deep breath, shall we?

> finding out that all of my bookmarks were being duplicated (a cummulative 30,000 bookmarks, over 100 folders). 

that is unfortunate :/

> Now, one has to click on irritting "three dots" of EVERY SINGLE folder to delete it. 

You can "select all" in the toolbar after selecting a single item.

> Also, previously, it was very easy to have different folders, one for each member of family. Now, there is only one and all bookmarksa re lumped into it.

I don't see why you shouldn't be able to have multiple folders in the latest version. The functionality certainly wasn't removed.

While I can understand frustration please keep communication civil.
