### ISSUE TITLE
Feature request: Multiple User accounts

### ISSUE THREAD

**Issue by smartsourcefreak** [nextcloud/bookmarks#1900]
It would be great to have the possibility to manage the bookmarks of multiple users. Therefor having implemented a small useraccount manager would be necessary.

**Describe the solution you'd like**
Clicking the settings menu (three dots) would give me the option "Change user"/"Account manager". A menu ("Account manager") would appear, offering the account names of all known users who have logged in from the current device yet. Choosing one of them would request me to confirm to logout the current user and log in the chosen one. "Abort" would stop the process and close the request windows. While "Confirm" would log off the current user, log in the chosen one and load the bookmarks (main) menu of the chosen account.

The account manager menu (look above) would on top let me

1) create a "New user account" [with server, user and password input fields] and 
2) do a few other things with a given account by clicking the three dots next to a user name. "Change to account", "Delete account", "Change account's credentials"... 
3) Exit the account manager and go back to the current user's bookmarks. While being in the "Account manager" menu, the currently logged in user would be shown, as in "Logged in as xyz".

**Describe alternatives you've considered**
Manually having to logout and login (username, passw, server) everytime you want to manage another user's bookmarks. Not nice.

For further question feel free to msg me. Thx.

**Comment by marcelklehr** [comment]
I don't think this is within the scope of this app. the general idea is to have one account per person, I think.

**Comment by smartsourcefreak** [comment]
The official main Nextcloud app supports multiple users, the official Nextcloud notes app supports multiple users. The official Talk app supports multiple users, and so forth. And you don't think that's within the scope of this app?? Lol.

**Comment by marcelklehr** [comment]
This app also supports multiple users:

> Manually having to logout and login (username, passw, server) everytime you want to manage another user's bookmarks.

To my knowledge there's nothing different here to how notes or talk works. If you want a user manager, you need to file an issue with nextcloud/server I'm afraid.

**Comment by smartsourcefreak** [comment]
You should definitely take a look into the apps I mentioned. You can add multiple users and afterwards switch between them. So this bookmarks app lacks this feature. I myself use different Nextcloud accounts for different scenarios / use cases. So quickly switching between accounts makes a lot of sense imo.

**Comment by AndyScherzinger** [comment]
@smartsourcefreak I think you are in the wrong repo... this is the server-side/webUI app repository, what you are referring to sounds to me like the mobile apps which is different people, different repo, etc. So I would guess you are looking for: https://gitlab.com/bisada/OCBookmarks no?

**Comment by smartsourcefreak** [comment]
Oh. You might be right, that I could be in the wrong repository. Actually I am talking about [this](https://play.google.com/store/apps/details?id=de.emasty.bookmarks) which brought me here after following one or two links. I might actually be wrong. Sorry therefor.

**Comment by AndyScherzinger** [comment]
Ah, yes.  That is then the job of the mobile app to implement support for it, from the server-side app this is of course working just fine 👍
