### ISSUE TITLE
Bookmark page is empty

### ISSUE THREAD

**Issue by cyberic99** [nextcloud/bookmarks#1914]
**Describe the bug**
The bookmark window is completely empty, see the screenshot

**To Reproduce**
Go to the bookmarks app

**Expected behavior**
The bookmarks show up

**Screenshots**
![image](https://user-images.githubusercontent.com/193917/196540618-f8bd959d-be04-4d92-92f3-9a050a297df8.png)

**Desktop (please complete the following information):**
 - OS:Archlinux
 - Browser: Chromium Version 105.0.5195.125 (Official Build) Arch Linux (64-bit)
                   Firefox v 105.0

**Server (please complete the following information):**
 - OS: Archlinux
 - HTTP server: Nginx 1.22
 - Database: mariadb 10.9.2-1
 - PHP version: php 8.1.10-1
 - Nextcloud version: 24.0.5
 - Bookmarks app version: : [e.g. 1.1.0 (see Nextcloud apps page)]
 - Nextcloud external user backend: nine

**Additional context**

'recent bookmarks' and 'frequent bookmarks' show up correctly in the dashboard

**Browser log**

This error show up in the console:
```
TypeError: o[t] is undefined
    https://<redacted>/apps/bookmarks/js/bookmarks-main.js?v=a6343934-9:2
```

**Comment by marcelklehr** [comment]
Mh. I cannot reproduce this with Firefox 105, Nextcloud 24.0.6 and Bookmarks 11.0.4

**Comment by cyberic99** [comment]
thanks for trying to reproduce.
I suspect this is related to the content of the database
What could I do to test this ?

**Comment by paddel10** [comment]
Same behaviour ("The bookmark window is completely empty, see the screenshot"). Console output on my computer for Chrome Version 107.0.5304.110:
```
Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src 'nonce-css1uhuwr .... kkxtcs3s0floxrayz0='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by cyberic99** [comment]
I have tested with another user on the same nextcloud instance, same beheavior. hiw could we help to debug ? this is annoying, the bookmarks app is unusable for me

**Comment by marcelklehr** [comment]
> hiw could we help to debug ?

Which version of the app do you have installed?

**Comment by marcelklehr** [comment]
You can try installing the app from source and building the javascript in development mode so you get proper stack traces.

**Comment by cyberic99** [comment]
> Which version of the app do you have installed?
-  nextcloud 24.0.5
- bookmarks: 11.0.4

> You can try installing the app from source and building the javascript in development mode so you get proper stack traces.
I'm sorry but I can't install composer, node, npm on a production server

Is it possible to build a debug build on another machine ?
or can I generate the sourcemaps on another server ?

Thank you

**Comment by marcelklehr** [comment]
Here's a zip file containing a development build of the js files: [js.zip](https://github.com/nextcloud/bookmarks/files/10148928/js.zip)


Recommended exemplary implementation steps:

```
cd /var/www/nextcloud/apps/bookmarks
wget https://github.com/nextcloud/bookmarks/files/10148928/js.zip
rm -rf js
unzip js.zip
```

**Comment by cyberic99** [comment]
Hello again, and sorry for the late reply

Here is what I get in the console when using the provided js files:
![image](https://user-images.githubusercontent.com/193917/210662045-7a4af3f8-ba87-4d91-933e-75796ee8c286.png)

thank you

**Comment by marcelklehr** [comment]
Mh, something went wrong there :/

**Comment by marcelklehr** [comment]
Can you try again with this one? [js.zip](https://github.com/nextcloud/bookmarks/files/10716499/js.zip)

**Comment by marcelklehr** [comment]
I'm just now seeing the URL of the chunk that fails to load starts with `/wapps/`? Where comes the w from?

**Comment by cyberic99** [comment]
Hello @marcelklehr I just tried again with the new zip file, I get the same behavior:
```
ChunkLoadError: Loading chunk vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-7bd8f8 failed.
```
And you're totally right about the 'w' ... it should not be there.
If I try to reach a failing URL after removing the w, I can reach it

In fact I solved the issue

I am on archlinux

My config looks like this:
 ```
 array (
    0 => 'xxx',
  ),
  'datadirectory' => '/var/lib/nextcloud/data',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/share/webapps/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/lib/nextcloud/apps',
      'url' => '/wapps',
      'writable' => true,
    ),
  ),
 ```
I did notice that I had 'nextcloud-bookmarks' installed from my package manager, 
but it seems I had also another version installed from the app store.

After uninstalling the version with 'pacman', the issue disappeared.

I'm sorry about that, the issue was on my end, thank you for your time,
and thank you for nextcloud bookmarks !

**Comment by cyberic99** [comment]
Also see section "12.3 Weird behavior of one or more apps" here:
https://wiki.archlinux.org/title/Nextcloud

**Comment by marcelklehr** [comment]
Oof. Installing nextcloud apps via system package manager should be outlawed... :sweat_smile:

**Comment by cyberic99** [comment]
yes I removed every app that was installed via my package manager, and I'll let nextcloud handle them ;-)
