### ISSUE TITLE
White flash of loading bars on the content of each folder click, when using dark themes.

### ISSUE THREAD

**Issue by marcusquinn** [nextcloud/bookmarks#1923]
**Describe the bug**
White flash of loading bars on the content of each folder click, when using dark themes.

**To Reproduce**
1. Choose a dark theme
2. Click folders to see their content

**Expected behavior**
No white flashes in dark mode, it's jarring.

**Desktop (please complete the following information):**
 - All OSes & browser tried

**Server (please complete the following information):**
 - Nextcloud version: 25.01
 - Bookmarks app version: 11.0.4

**Additional context**
Just surprised there's not already an issue logged for this?

**Comment by marcelklehr** [comment]
Confirmed.
