### ISSUE TITLE
App "bookmarks" cannot be installed because appinfo file cannot be read

### ISSUE THREAD

**Issue by YoannPa** [nextcloud/bookmarks#1925]
**Describe the bug**
It all started today when I tried to recharge my dashboard user account page: the bookmarks panel was loading in loop and nothing was displayed. Then I realize that the bookmarks app had disappeared from the app menu.
On the admin side: same issue. And after entering the applications menu, the Bookmarks app was showing the version number **0**.
I decided to deactivate the app. Then when I tried to reactivate it I got is orange display message : **App "bookmarks" cannot be installed because appinfo file cannot be read.**
For the records: All apps are up to date.
After reloading the application menu, now Bookmarks still can't be activated, but it is showing the version number **11.0.4** (so not **0** anymore).
  
**To Reproduce**
I have no idea Bookmarks disappeared all of sudden from the installed apps. To reproduce the error message display you need to deactivate and then reactivate the app in the applications menu.

**Expected behavior**
Bookmarks was installed 2 years ago, and always smoothly through all updates. It was activated, so expected behavior is to be working, to be displayed in the app bar, to have a panel displayed on the dashboard with my shortcuts, and to be able to activate it after deactivating it.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Chromium Version 90.0.4430.72 and Firefox Version 90.0.4430.72

**Server (please complete the following information):**
 - OS: Ubuntu 16.04
 - HTTP server: nginx/1.10.3 (Ubuntu)
 - Database: mysql  Ver 15.1 Distrib 10.0.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
 - PHP version: PHP 7.0.33-0ubuntu0.16.04.16+esm4 (cli) ( NTS )
 - Nextcloud version: 24.0.6
 - Bookmarks app version: 11.0.4 (I guess ?)
 - Activated Nextcloud Apps: I am using the Snap version of Nextcloud.
 - Nextcloud configuration: I am using the Snap version of Nextcloud.
 - Nextcloud external user backend: I have no clue.

I don't know where to look for logs with Nextcloud Snap application.

**Comment by cyberic99** [comment]
I had the same error, and was able to install the app using this command line:
```
occ app:install bookmarks
```

**Comment by YoannPa** [comment]
@cyberic99 As far as I am concerned, the problem got solved after a Nextcloud update. I forgot to close this issue, I don't have anymore problem with the Bookmarks app since.
So let's close that, I think there is enough information for someone to find it in case it happens again, to reopen it.
