### ISSUE TITLE
Importing Google Bookmarks cuts off Labels/Tags

### ISSUE THREAD

**Issue by inoculator** [nextcloud/bookmarks#193]
Hi all,
that's my first post on GitHub, so please be patient with me ;-)
I got the master version from 2015-09-08 running on my OC 8.1 running.
The general import from Google Bookmarks is working, but it cuts off all Tags.
I tried to work around by exporting from OC and editing the html file replacing 'TAGS=""' with 'TAGS="ALL"' for a first attempt.
After reimporting the file, all URLs are gone. Only "http://" or "https://" is contained in the lists.
The same happens, if I do not manipulate the html export file, but just reimport it.
In addition, it would be good to have a Button to reset the TAG Filter on the Webfrontend. At the moment I workaround by "F5"/reload.
br
Carsten

**Comment by inoculator** [comment]
Hi all again,
it looks like this is still not ongoing to be solved. and even gets worst
I just checked the current version on a fresh install.
Ubuntu 12.04 LTS
PHP5.6
Apache2.4
ownCloud 8.2.0 (stable) 
Bookmarks pulled by git clone today.
...............
Steps to reproduce:
export google bookmarks to a file
Import them into bookmarks
-> all bookmarks imported, but no TAGs.
export bookmarks to a file
Edit the file using gedit or similar
change 'TAG=""' to 'TAG="ALL"' or similar
cleanup database table 'oc_bookmarks' and 'oc_bookmarks_tags'
Import edited file
-> all bookmarks are visible with TAG "ALL" but URL is only "http:///".

**Comment by marcelklehr** [comment]
Diagnosis from the future. Two years too late: If the bookmarks file reads literally `TAG=""`, then Google didn't export the tags for you. :)
