### ISSUE TITLE
Do not save www.example.com and example.com (no www) as separate bookmarks

### ISSUE THREAD

**Issue by vbresan** [nextcloud/bookmarks#1936]
Currently when bookmarking, www and non-www domain names are bookmarked as separate sites.
It would be perfect if that case is detected and bookmarklet showed standard 'already bookmarked' message.

**Comment by marcelklehr** [comment]
The bookmarks app is already employing a URL normalization. www and non-www is not guaranteed to resolve to the same server, sadly, so there would be false positives.
