### ISSUE TITLE
Can't add RSS feed to FreshRSS

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [nextcloud/bookmarks#1939]
Hi,
I tried adding the RSS Feed to FreshRSS with nextcloud credentials but I keep getting this error in FreshRSS - 

cURL error 92: HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1) [https://nextcloud.domain.tld:444/index.php/apps/bookmarks/public/rest/v2/bookmark?folder=8&amp;format=rss&amp;page=-1] 

How can I sort this out? Is this a bug?

**Comment by marcelklehr** [comment]
You can also try page=1 instead of -1 in case you have ALOT of bookmarks (as people posting issues in this repo tend to do...)

**Comment by Gandalf-the-Blue** [comment]
Hi @marcelklehr I'm getting this error in the curl command - 
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
Same as that in FreshRSS.

**Comment by marcelklehr** [comment]
Does it work if you use --http1.1 ?
Does it work if you use page=1 ?

**Comment by Gandalf-the-Blue** [comment]
Same error with both --http1.1 and page=1

**Comment by marcelklehr** [comment]
Any errors in the webserver log or in the Nextcloud log? Does the bookmarks app web UI still work?

**Comment by Gandalf-the-Blue** [comment]
I do see this error in my Nextcloud Log - is this relevant?

[PHP] Error: Error: Undefined variable $folder at /data/nextcloud/apps/notes/lib/Service/NoteUtil.php#154 at <<closure>>

0. /data/nextcloud/apps/notes/lib/Service/NoteUtil.php line 154
   OC\Log\ErrorHandler::onError()
1. /data/nextcloud/apps/notes/lib/Service/NotesService.php line 153
   OCA\Notes\Service\NoteUtil->getOrCreateFolder()
2. /data/nextcloud/apps/notes/lib/Service/NotesService.php line 30
   OCA\Notes\Service\NotesService->getNotesFolder()
3. /data/nextcloud/apps/bookmarks/lib/Service/NotesService.php line 92
   OCA\Notes\Service\NotesService->getAll()
4. /data/nextcloud/apps/bookmarks/lib/Service/NotesService.php line 52
   OCA\Bookmarks\Service\NotesService->getNotes()
5. /data/nextcloud/apps/bookmarks/lib/BackgroundJobs/ExtractFromNotesJob.php line 63
   OCA\Bookmarks\Service\NotesService->extractBookmarksFromNotes()
6. /data/nextcloud/lib/public/BackgroundJob/Job.php line 79
   OCA\Bookmarks\BackgroundJobs\ExtractFromNotesJob->run()
7. /data/nextcloud/lib/public/BackgroundJob/TimedJob.php line 95
   OCP\BackgroundJob\Job->execute()
8. /data/nextcloud/cron.php line 151
   OCP\BackgroundJob\TimedJob->execute()

**Comment by marcelklehr** [comment]
Mh, that error is related to the bookmarks app, but not related to this issue..

Wait a second. Curl'ing the above URL with the option --http1.1 gives you an error that says HTTP/2 stream 0 was not closed cleanly? That's odd. It shouldn't be using HTTP 2 in the first place.

**Comment by Gandalf-the-Blue** [comment]
Yup, not sure why that happens

**Comment by Gandalf-the-Blue** [comment]
I am running NextCloudPi behind nginx reverse proxy. How do I circumvent it?
I tried replacing nextcloud.domain.tld:444 with the IP of my RaspberryPi 4 with the port of the nextcloud container(which is technically not exposed). I get the following error - 

curl: (60) SSL certificate problem: self-signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by marcelklehr** [comment]
You may need to use http only (without ssl)

**Comment by marcelklehr** [comment]
ok then https it is. You can use curl -k to ignore the certificate

**Comment by Gandalf-the-Blue** [comment]
With that, I get this response - 

<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1"><meta http-equiv="X-UA-Compatible" content="ie=edge"><meta http-equiv="Content-Language" content="en"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="mobile-web-app-capable" content="yes"><meta name="HandheldFriendly" content="True"><meta name="MobileOptimized" content="320"><title>Nginx Proxy Manager</title><link rel="apple-touch-icon" sizes="180x180" href="/images/favicons/apple-touch-icon.png"><link rel="icon" type="image/png" sizes="32x32" href="/images/favicons/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/images/favicons/favicon-16x16.png"><link rel="manifest" href="/images/favicons/site.webmanifest"><link rel="mask-icon" href="/images/favicons/safari-pinned-tab.svg" color="#5bbad5"><link rel="sho* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* Connection #0 to host 192.168.1.165 left intact
rtcut icon" href="/images/favicons/favicon.ico"><meta name="msapplication-TileColor" content="#333333"><meta name="msapplication-config" content="/images/favicons/browserconfig.xml"><meta name="theme-color" content="#ffffff"><link href="/css/main.css?v=2.9.19" rel="stylesheet"></head><body><noscript><div class="container no-js-warning"><div class="alert alert-warning text-center"><strong>Warning!</strong> This application requires Javascript and your browser doesn't support it.</div></div></noscript><div id="app" class="page"><span class="loader"></span></div><script src="/js/main.bundle.js?v=2.9.19"></script></body></html>[1]-  Done                    curl -k -u "ncp:rTzaX76uXwHitS9u" -v https://<RPi IP>:444/index.php/apps/bookmarks/public/rest/v2/bookmark?folder=8

How do I test this in browser?

**Comment by marcelklehr** [comment]
Ah, so there is still an nginx inside. foo.

**Comment by marcelklehr** [comment]
Do you get the error also with RSS feds for other folders or other users?

**Comment by Gandalf-the-Blue** [comment]
No other users. I have folders inside the main folder of bookmarks though.

When I tried this command (with the new rss feed link for the folder inside) - curl -k -u "<>:<>" -v https://<>:8500/index.php/apps/bookmarks/public/rest/v2/bookmark?folder=8&format=rss&page=1 --http1.1
I do get all the data back!
How do I add this to freshrss now?

**Comment by Gandalf-the-Blue** [comment]
Okay, so putting this url in with SSL security verification disabled in FreshRSS worked, somewhat. For some reason only two of the most recent bookmarks were imported. Any ideas?

**Comment by marcelklehr** [comment]
> curl -k -u "<>:<>" -v https://<>:8500/index.php/apps/bookmarks/public/rest/v2/bookmark?folder=8&format=rss&page=1 --http1.1

the folder id is the same though :thinking:

**Comment by marcelklehr** [comment]
> Any ideas?

No idea, if all the items are in there when using curl, it's up to FreshRSS to import them, maybe FreshRSS only imports items from the last X days to avoid flooding your database?

**Comment by Gandalf-the-Blue** [comment]
Alright, I'll take a look into the FreshRSS settings.
Closing this issue
Thanks for the help!!
