### ISSUE TITLE
URL for RSS-Feed not available

### ISSUE THREAD

**Issue by PeterBenzin** [nextcloud/bookmarks#1962]
**Describe the bug**
When I use the function to copy the RSS-Feed I do not get the XML-feed's address.

**To Reproduce**

1. Go to "Bookmarks" App.
2. Open a folder that contains some bookmarks already.
3. Click the sharing icon.
4. Create Public link.
5. Click on the three dots
6. Click "Copy RRS-Feed" - I see notification "RSS feed copied"
7. Open that URL in private session browser window.
8. A nicely formatted list of booksmarks is shown in nextcloud template design with no rss link at all.

**Expected behavior**
I expected to get the URL for the RSS XML feed, say something like:
https://mydomain.com/index.php/apps/bookmarks/public/lZ8h5QM.xml
instead of
https://mydomain.com/index.php/apps/bookmarks/public/lZ8h5QM

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 109.0

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - HTTP server: Apache
 - Database: MariaDB 10.3.37
 - PHP version: 8.0
 - Nextcloud version: 25.0.3
 - Bookmarks app version: 12.0.0
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Enabled:
  - activity: 2.17.0
  - bookmarks: 12.0.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - collectives: 2.2.1
  - comments: 1.15.0
  - contacts: 5.0.2
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - maps: 0.2.4
  - news: 20.0.1
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - photos: 2.0.1
  - polls: 4.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - snappymail: 2.24.6
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - contactsinteraction: 1.5.0
  - encryption
  - files_external
  - password_policy: 1.9.1
  - suspicious_login
  - user_ldap
  - user_status: 1.4.0
  - weather_status: 1.1.0
 
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - {
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/var\/www\/vhosts\/my-domain.com\/sub.my-domain.com\/owncloud-tmp",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "trusted_domains": [
            "sub.my-domain.com"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "debug": "false",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": true,
        "updatechecker": true,
        "trashbin_retention_obligation": "auto",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "enable_avatars": true,
        "overwrite.cli.url": "https:\/\/sub.my-domain.com\/oc",
        "app_install_overwrite": [
            "calendar"
        ],
        "has_rebuilt_cache": true,
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "default_phone_region": "DE"
    }
}

 - Nextcloud external user backend: none

**Comment by marcelklehr** [comment]
Confirmed.

**Comment by marcelklehr** [comment]
Sorry for the delay. The URL looks like this: https://cloud.yourdomain.de/apps/bookmarks/public/rest/v2/bookmark?format=rss&token=MN7RTZUJNB

**Comment by PeterBenzin** [comment]
Thank you! 

So I can confirm that basically the RSS feed is nonetheless still working - when I build it manually.

Only the function to copy the link in Nextcloud does not work currently.
