### ISSUE TITLE
Preview and download fails (but cron is running!)

### ISSUE THREAD

**Issue by JackHewson** [nextcloud/bookmarks#1980]
I've been adding some bookmarks some days ago.
When opening their details it shows:

- no thumbnail
-  ```Content pending This content is being downloaded for offline use. Please check back later. ```

I've checked cron. It runs regularly all 5 minutes.
How to debug this error?

Thanks!

Nextcloud Bookmarks: 12.0.0
Nextcloud version : 25.0.3

**Comment by marcelklehr** [comment]
Have you enabled network access in the bookmarks admin settings?

**Comment by JackHewson** [comment]
Thanks for the hint and help, I have overlooked the bookmarks admin settings page.
