### ISSUE TITLE
In Nextcloud 26.0.0RC3 there are errors after installing "bookmarks" and some other apps don't work anymore.

### ISSUE THREAD

**Issue by parajbs** [nextcloud/bookmarks#1993]
In Nextcloud 26.0.0RC3 there are erros after installing "bookmarks" and some other apps don't work anymore.

hello support team,

right at the beginning: I tested Nextcloud 26.0.0RC1 - Nextcloud26.0.0RC3, and as soon as I installed "bookmaks" version 13.0.0, other apps don't work properly anymore.

I just reinstalled "nextcloud 26.0.0RC3" basic to check and then installed "bookmarks", and from then on some of them no longer worked.

I found an error message in the browser console that might help you further.
Here the error message:

`
Refused to prefetch content from 'https://cloud.example.com/apps/bookmarks/js/bookmarks-src_components_CustomPickerElement_vue.js?v=28a17ca8519836817963' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'prefetch-src' was not explicitly set, so 'default-src' is used as a fallback.
`

I think the error has something to do with the "smart picker provider".

**Comment by parajbs** [comment]
hello support team,

I have just tested installing version 12.1.0 of "Bookmarks" in the Nextcloud26.0.0RC3.
It worked great and there are no more error messages and all other apps work as well.

So the problem only exists in version 13.0.0 of "Bookmarks".

**Comment by parajbs** [comment]
> > and from then on some of them no longer worked.
> 
> What does this mean exactly? Which browser are you using?

Hello **@marcelklehr,**

I ran several tests.

here what I tested:
- basic installation Nextcloud 26.0.0RC1 - Nextcloud26.0.0RC3 without apps. After that I install "Bookmarks 23.0.0" and after that I click on "files" in the menu and open the browser console where I can see the error message from above.
- PHP8.0.28 and PHP8.1.16
- tested browsers:
Chrome Version 111.0.5563.65 (Official Build) (64-bit), Firefox Version 111.0 (64-bit), Edge Version 111.0.1661.44 (Official Build) (64-bit), Opera Version:96.0.4693.50 and Brave Version 1.49. 120 Chromium: 111.0.5563.64 (Official Build) (64-bit)

Then I created a "new text file" and next I clicked on "Insert Link -> Open Link Chooser -> Files", selected a file.
This inserts a link and a preview of the link into the text file.
But when I installed "Bookmarks 13.0.0", the preview doesn't work anymore, it just shows a rotating circle all the time.

When I installed "Bookmarks 12.1.0" everything works great with preview, it shows. And the error message in the browser console does not come either, everything is ok there too.
But only works with "Bookmarks" version 12.1.0.
Version 13.0.0 is broken.

**Comment by marcelklehr** [comment]
> But when I installed "Bookmarks 13.0.0", the preview doesn't work anymore, it just shows a rotating circle all the time.

Aha. That's what I needed.

**Comment by parajbs** [comment]
Hello @marcelklehr

No problem, I was very busy today and didn't have time to write earlier. sorry

I hope you get it fixed.
According to the "Release Schedule" the new final version will be released tomorrow.

**Comment by marcelklehr** [comment]
> However, the error message from above is still displayed in the browser console.

This is not a critical error. The app requests a prefetch from the browser, which is not covered by the CSP, but nothing fails.

**Comment by parajbs** [comment]
Hello @marcelklehr,

OK.
However, the debugging doesn't look pretty, and it gets in the way of troubleshooting other apps.
But I can live with that for the time being and hope that you will be able to eliminate the error message soon.

Cool I just saw that the new release version of Nextcloud 26 is here, I hope it will still work there.
