### ISSUE TITLE
Php 8.2

### ISSUE THREAD

**Issue by lugau45** [nextcloud/bookmarks#1999]
Please give support for php 8.2

**Comment by marcelklehr** [comment]
May I ask what happens when you run it on v8.2?

**Comment by lugau45** [comment]
`2023-03-28T08:08:48.238Z Syncing failed with E019: HTTP status 500. Failed GET request. Check your server configuration and log.
E019: HTTP status 500. Failed GET request. Check your server configuration and log.
E017: Network error: Check your network connection and your account details
E017: Network error: Check your network connection and your account details
E019: HTTP status 500. Failed GET request. Check your server configuration and log.
E019: HTTP status 500. Failed GET request. Check your server configuration and log.
E019: HTTP status 500. Failed GET request. Check your server configuration and log.
E019: HTTP status 500. Failed GET request. Check your server configuration and log.
E019: HTTP status 500. Failed GET request. Check your server configuration and log.
E019: HTTP status 500. Failed GET request. Check your server configuration and log.
E019: HTTP status 500. Failed GET request. Check your server configuration and log.
E017: Network error: Check your network connection and your account details
E017: Network error: Check your network connection and your account details
E017: Network error: Check your network connection and your account details
E017: Network error: Check your network connection and your account details`

**Comment by marcelklehr** [comment]
Can you check the nextcloud log for the actual error?

**Comment by lugau45** [comment]
where can i find that?

**Comment by marcelklehr** [comment]
On your nextcloud server in nextcloud/data/nextcloud.log

**Comment by lugau45** [comment]
There are no more errors in it, now I have set it up again, also recreated the bookmarks but it is not syncronized a fraction. But now no error comes. Well, I'll keep testing.
