### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by galgofa** [nextcloud/bookmarks#2004]
**Describe the bug**
After recent update and enabling Bookmakrs in the setting i do able to hit sync with 
**To Reproduce**Floccus once. Then after the main page became inaccessible while docker running fine.

Internet dose not show any way to fix the issue

**Desktop (please complete the following information):**
 - OS: W11/Android
 - Browser: Chrome, Firefox

**Server (please complete the following information):**
 - OS: Debian 11 Bullseye 
 - Server HTTP server: nginx
 - Database: Server version: 10.5.18-MariaDB-0+deb11u1 Debian 11
 - Server PHP version: PHP 7.4.33 
 - Nextcloud version: latest from official docker hub
 - Bookmarks app version: lates - unable t open setting to check
 - Activated Nextcloud Apps: cant get to work to fetch the list installed, but definately: bookmarks/noted/photos 
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 
 While i enter the command i get flw:
```
root@92732999341d:/var/www/html# php occ config:list system
An unhandled exception has been thrown:
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_appconfig' doesn't exist in /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php:72
Stack trace:
```

 - Nextcloud external user backend: Android app

**Additional context**
Running official docker from nexctloud
Portainer container log:
192.168.72.193 - dietpi [20/Apr/2023:10:21:02 +0000] "DELETE /index.php/apps/bookmarks/public/rest/v2/lock HTTP/1.1" 500 702 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"

**Web server error log**
```
192.168.72.193 - dietpi [20/Apr/2023:10:12:02 +0000] "DELETE /index.php/apps/bookmarks/public/rest/v2/lock HTTP/1.1" 500 702 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```
***"]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"array_map","args":[["Closure"],[["ReflectionParameter","appName"],["ReflectionParameter","request"],["ReflectionParameter","l10n"],["ReflectionParameter","bookmarkMapper"],["ReflectionParameter","tagMapper"],"And 12 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":124,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[["ReflectionClass","OCA\\Bookmarks\\Controller\\BookmarkController"]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":142,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Bookmarks\\Controller\\BookmarkController"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":493,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Bookmarks\\Controller\\BookmarkController"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Bookmarks\\Controller\\BookmarkController"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":162,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Bookmarks\\Controller\\BookmarkController"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Bookmarks\\Controller\\BookmarkController","releaseLock",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["bookmarks.bookmark.release_lock"]]},{"file":"/var/www/html/lib/base.php","line":1055,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/bookmarks/public/rest/v2/lock"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Utils.php","Line":116,"CustomMessage":"--"}}
**Browser log**
```

**Comment by marcelklehr** [comment]
Hello @galgofa !

> Table 'nextcloud.oc_appconfig' doesn't exist

This does not sound good. Your nextcloud instance may be broken somehow.

> Nextcloud log

The log excerpt you posted is missing key information, sadly. Can you post the whole log entry?

**Comment by galgofa** [comment]
> This does not sound good. Your nextcloud instance may be broken somehow.

While i run in the data dir i got flw:
```
DietPi:/opt/nextcloud/data# php occ config:list system
This version of Nextcloud requires at least PHP 8.0<br/>You are currently running 7.4.33. Please update your PHP version.root@DietPi:/opt/nextcloud/data# 
```
> The log excerpt you posted is missing key information, sadly. Can you post the whole log entry?

The log is huge, not sure it can be posted all here.

**Comment by marcelklehr** [comment]
> The log is huge, not sure it can be posted all here.

You don't have to post the whole log.

**Comment by marcelklehr** [comment]
> This version of Nextcloud requires at least PHP 8.0<br/>You are currently running 7.4.33.

Well that's important. You have php 7.4. Your Nextcloud version requires 8. With this setup it's expected that things will break.

Please note that I do not offer Nextcloud support here, so please come back when you have fixed your nextcloud installation and are certain that the bookmarks app is the cause of a problem.
