### ISSUE TITLE
Update API-Documentation

### ISSUE THREAD

**Issue by newhinton** [nextcloud/bookmarks#2014]
**Describe the bug**

The documentation on https://nextcloud-bookmarks.readthedocs.io/en/latest/bookmark.html#query-bookmarks
is outdated. It is missing some values, like clickcount or userid.

Would it be possible to update the documentation?
I am currently rebuilding the api for the [android app](https://gitlab.com/bisada/OCBookmarks), and i would like to do it as completely as possible to allow easy maintenance in the future. Thanks!

**Comment by marcelklehr** [comment]
@newhinton Ah, yes. I've neglected those docs a bit the last two years. Should be up to date now again. Thanks for the heads up!
