### ISSUE TITLE
file picker for archive and backup path should show hidden folders

### ISSUE THREAD

**Issue by j-lakeman** [nextcloud/bookmarks#2046]
**Is your feature request related to a problem? Please describe.**
When trying to set either archive or backup path from settings, no hidden folders as destination are shown in the file picker.

**Describe the solution you'd like**
hidden folders should be shown by default in the file picker

**Additional context**
need a hidden backup folder for several reasons

**Comment by marcelklehr** [comment]
Hey @j-lakeman 
I have checked the picker library and I believe this is currently not possible :/

**Comment by j-lakeman** [comment]
Thanks @marcelklehr!
Is this an issue I could raise in the server main repo?
I think it could be useful for other use cases, too.

**Comment by marcelklehr** [comment]
Yes, I think the appropriate repo would be https://github.com/nextcloud-libraries/nextcloud-dialogs

**Comment by j-lakeman** [comment]
Thanks a lot!
