### ISSUE TITLE
Password pop-up in admin settings popping up multiple times

### ISSUE THREAD

**Issue by Uatschitchun** [nextcloud/bookmarks#2050]
**Describe the bug**
When changeing a setting in admin settings, one needs to legetimate these with entering admin's password.
Problem: The PW pop-up pops up multiple times with possibility to enter password and answer yes or no and only one has "Bestätigen" (accept).

**To Reproduce**
1. admin -> bookmarks
2. change a setting without having entered the admin password for a longer time
3. pop-up with PW to enter pops up multiple times

**Expected behavior**
Only one pop-up

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Opera

**Server (please complete the following information):**
 - HTTP server: apache
 - PHP version: 8.2
 - Nextcloud version: 27
 - Bookmarks app version: 13.0.1

**Comment by marcelklehr** [comment]
Confirmed. Cleaned up the admin settings. Should be a much better experience now.
