### ISSUE TITLE
Tooltip is not hidden when offscreen

### ISSUE THREAD

**Issue by nicofrand** [nextcloud/bookmarks#2051]
**Describe the bug**

The tooltip shown when the cursor is over an item won't disappear when scrolling after the item is offscreen.

**To Reproduce**

1. Put cursor over an item so that a tooltip appears
2. Scroll down until the item is offscreen
3. See issue

**Expected behavior**

The tooltip is removed once the item is offscreen.

**Screenshots**

![image](https://github.com/nextcloud/bookmarks/assets/3419050/be4c7065-fc3c-4dc6-9d7d-84ef0945d9ae)

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser: Firefox
 - Version: 117a

**Comment by nicofrand** [comment]
Maybe related (I don't know how Nextcloud apps/components work): https://github.com/Akryum/floating-vue/issues/939

**Comment by marcelklehr** [comment]
Should be fixed now after an update of nextcloud-vue

**Comment by nicofrand** [comment]
Is this something that requires my intervention? Or should I wait for a new release?
