### ISSUE TITLE
New tooltips should close previous ones

### ISSUE THREAD

**Issue by nicofrand** [nextcloud/bookmarks#2052]
**Describe the bug**

Several tooltips can be shown at once, making them unreadable.

**To Reproduce**

1. Put cursor on an  items so that a tooltip appears
2. Scroll down
3. Repeat step 1 & 2

**Expected behavior**

Only one tooltip appears at a time.

**Screenshots**

![image](https://github.com/nextcloud/bookmarks/assets/3419050/5c260132-567e-402e-8900-67dcc65d7ac3)

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser: Firefox
 - Version: 117a

**Comment by marcelklehr** [comment]
Should be fixed after an update of nextcloud-vue now
