### ISSUE TITLE
Import file format

### ISSUE THREAD

**Issue by gisforgabriel** [nextcloud/bookmarks#2056]
I have bookmarks in another tool which exports to json in the format below. The Bookmarks import function gives an error when I try to import it `Unsupported file type for import`.

```json
[
    {
        "category": "best",
        "description": "The best example website I know",
        "id": "0Vvr27BrqX87AeKM",
        "link": "https://example.com",
        "readlater": "False",
        "starred": "False",
        "tags": [
            "cool websites"
        ],
        "timestamp": "2023-08-08 21:15",
        "title": "Example website"
    },
    ...
]
```

I appreciate that not all the fields will be directly useable, but I'm happy to make adjustments/compromises.

Can anyone provide an example of the accepted format for import? I looked at the documentation but couldn't see anything about imports.

**Comment by marcelklehr** [comment]
Hey @gisforgabriel  :wave: 

currently the app only accepts bookmark imports in the html format as exported by most browser vendors.
