### ISSUE TITLE
Error: Could not find resource bookmarks/js/flow.js to load (Nextcloud 27)

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#2058]
**Describe the bug**
In the log the following is reported:
```
[jsresourceloader] Fout: Could not find resource bookmarks/js/flow.js to load

GET /settings/user/workflow
```

**To Reproduce**
1. Go to https://&lt;fqdn>/settings/admin/logging

**Expected behavior**
The error should not be reported.

**Screenshots**
N.A.

**Desktop (please complete the following information):**
 - OS: openSUSE 15.5
 - Browser: N.A.

**Server (please complete the following information):**
 - OS: openSUSE 15.5
 - HTTP server: Apache
 - Database: sqlite
 - PHP version: 8.0
 - Nextcloud version: 27.0.0.2
 - Bookmarks app version: 13.0.1

**Additional context**
I see this after upgrading to NC-27

Going to the following page:
https://&lt;fqdn>//settings/admin/workflow
and
https://&lt;fqdn>//settings/user/workflow
Results in this error

**Web server error log**
```
No errors, just the the retrieval of the pages I mentioned above, at the timestamp of the error.
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Additional Information**

Someone else reported the same issue [how-can-i-fix-error-could-not-find-resource-bookmarks-js-flow-js](https://help.nextcloud.com/t/how-can-i-fix-error-could-not-find-resource-bookmarks-js-flow-js/165643).

I tried to find where js/flow.js, but did not find it.  Hopefully, this issue can be taken care of.

**Comment by radoeka** [comment]
Thanks Marcel.  

When will this be available via a released new bookmarks version?

Is it with .js files possible to make the change in the installed instance, and will the change then be immediately effective (or is there some compilation required)?

**Comment by marcelklehr** [comment]
> When will this be available via a released new bookmarks version?

Soon :)
