### ISSUE TITLE
Truncated Count

### ISSUE THREAD

**Issue by Harmon758** [nextcloud/bookmarks#2069]
**Describe the bug**
The count next to "All bookmarks" becomes truncated when over 10K bookmarks is reached.

**To Reproduce**
1. Have over 10K bookmarks
2. Notice the count is truncated in the sidebar

**Expected behavior**
The count should not be truncated.

**Screenshots**
![image](https://github.com/nextcloud/bookmarks/assets/9403740/2096b7f1-a649-4ec5-bce0-eafe4ff05f12)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows [Version 10.0.19045.3086]
 - Browser: Google Chrome Version 116.0.5845.188 (Official Build) (64-bit)

**Server (please complete the following information):**
 - OS: Synology DiskStation Manager 7.2-64570 Update 3
 - HTTP server: N/A
 - Database: PostgreSQL 15.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
 - PHP version: 8.1.23
 - Nextcloud version: Nextcloud Hub 6 (27.1.0)
 - Bookmarks app version: 13.1.1
 - Activated Nextcloud Apps: N/A
 - Nextcloud configuration: N/A
 - Nextcloud external user backend: N/A

**Additional context**
Inspecting the element in the screenshot shows that it should show "10.1K", and there's obviously enough room to do so in the sidebar.

**Web server error log**
N/A

**Nextcloud log (nextcloud/data/nextcloud.log)**
N/A

**Browser log**
N/A

**Comment by Harmon758** [comment]
Unrelated to the issue itself, but the New issue workflow for this repository seems to be failing now:
https://github.com/nextcloud/bookmarks/actions/runs/6258985289/job/16994097205

**Comment by marcelklehr** [comment]
This is fixed now.
