### ISSUE TITLE
Feature request: Ability to search for folder name

### ISSUE THREAD

**Issue by vitorhmcorreia** [nextcloud/bookmarks#2076]
**Is your feature request related to a problem? Please describe.**

My feature request for the ability to search for a folder name lies on the use case of wanting to search for my folder where I keep movie or gaming related links.

**Describe the solution you'd like**

I'd like to add a new bookmark related to new_game_just_released, but I can't recall where it is. I pull up the search bar, search for the folder new_game_just_released and it brings up the link to the folder, as opposed to just searching for bookmarks which may contain that name.

**Describe alternatives you've considered**
At the moment I try to remember a bookmark which may be in the folder I'm looking for, search for that bookmark and backtrack to the folder. 

**Additional context**
n/a

Really appreciate your time assessing if this request is feasible. I have over 100K bookmarks and Nextcloud Bookmarks has greatly improved my workflow :)

**Comment by marcelklehr** [comment]
Hey @vitorhmcorreia 

This is a great idea! Just implemented it :)

**Comment by vitorhmcorreia** [comment]
Hey @marcelklehr, brilliant stuff!! :)

So cool that you considered it to be a good idea and that you had time to implement it.
Looking forward to using it!

All the best.
