### ISSUE TITLE
Bookmark gives error when using the search box

### ISSUE THREAD

**Issue by noci2012** [nextcloud/bookmarks#2092]
**Describe the bug**
Notification os error in Bookmarks when doing a search

**To Reproduce**
1. Go to Search box, and type a search string
2. Click on 'enter'

**Expected behavior**
Not a message about a search failure

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 119

**Server (please complete the following information):**
 - OS: Linux, Gentoo current
 - HTTP server: nginx recent
 - Database: MariaDB
 - PHP version: 8.2
 - Nextcloud version: 27.1.3
 - Bookmarks app version: 13.1.1
 -  Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: none

**Additional context**

**Web server error log**
```
N/A
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Exception: OCP\Search\SearchResultEntry::__construct(): Argument #3 ($subline) must be of type string, null given, 
called in /slowdata/WWW/xxxxxxx/htdocs/apps/bookmarks/lib/Search/Provider.php on line 74 in file
'/slowdata/WWW/xxxxxxxx/htdocs/lib/public/Search/SearchResultEntry.php' line 100
```

**Browser log**
```
N/A
```

**Comment by noci2012** [comment]
Believe me i tried to fix software before (files_opds...)  then again got really realy frustrated about the maxe that is (hopefully was) the Nextcloud Documentation (API etc.). 
Examples that could maybe work in NC 10...,  i quit that when i discoverd i was starting to reverse engineer NC 20 in my spare time only to discover i could start all over again for NC 21 etc. 
Even the official documentation could not produce working stuff.
The reverse engineering consisted out of examining existing apps ("they worked...")  only to find that between 20 ish apps there were 18-ish methods of accessing / configuring NC, and none really fitted the model of the problem i tried to solve.

**Comment by marcelklehr** [comment]
@noci2012 I feel your pain. Developing code for nextcloud hasn't been easy. I believe we're doing better nowadays, but that still doesn't excuse the sins of the past. Thank you in any case for reporting this bug. :blue_heart:
