### ISSUE TITLE
Bookmarks are not editable

### ISSUE THREAD

**Issue by Alternativend** [nextcloud/bookmarks#2097]
When i try to edit a Bookmark after i´ve inserted the link the edit fails saying "Content awaiting"

Please see this screenshot:

![Bookmarkbug](https://github.com/nextcloud/bookmarks/assets/1799441/568bfa0b-a6d8-4836-a173-49f52ce7218b)

This happens every time i try to open the detail page.

Thanks!

**Comment by marcelklehr** [comment]
I can not currently reproduce this. Can you confirm whether this is still happening for you?
