### ISSUE TITLE
RSS Feed / Live bookmark

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/bookmarks#210]
Hi there,

Like others before me, I'd really like to be able to use ownCloud bookmarks more easily, natively in my browser. This seems to be the point where usually there is a big discussion that rapidly gets technical involving Mozilla Weave and Chrome sync protocol. Here's the thing though. Really I just want to be able to do two things:
1. Add a bookmark - which is easily done throught the bookmarklette already, and...
2. Access my bookmarks - which seems to be the only part really missing.

While it would be fantastic to have a native browser plugin / addon / extension, we're never going to cover all browsers, and it seems it will take a long time to even cover the major ones. If an RSS feed could be provided though, it seems that this would be pretty simple, and in Firefox at least (and likely other browsers, I suspect) it could just be dragged to bookmarks - like the bookmarklette, to create a live bookmark, thus making all my bookmarks easily accessible.

Yes, this isn't going to provide filtering, tags etc, but it seems like a 90% solution that would require only 20% of the work of implementing full sync protocols and multibrowser addons etc.

**Comment by jordila** [comment]
Suscribe.

**Comment by mhzawadi** [comment]
Hi,

Can I add my support for an RSS feed, I use opera so would work well

**Comment by mhzawadi** [comment]
Hi all,

I have had a look at an extension for opera, not what most would want or very pretty. but it works using the rest API, if you want a look the link below should work. You may be able to convert to firefox.

https://owncloud.horwood.biz/index.php/s/dU7gOdYKFqah4AI - PW: bookmarks

**Comment by planetahuevo** [comment]
I will be interested on the feeds too. Thanks!

**Comment by guitargurus** [comment]
I would also like this functionality.

**Comment by mhzawadi** [comment]
So the browser plugin has been added to github, I have a firefox and opera plugin. You might be able to edit the opera one to be used in chrome and add to the current bookmarks.

https://github.com/mhzawadi/owncloud-bookmarks-firefox
https://github.com/mhzawadi/owncloud-bookmarks-opera

**Comment by serenity-networks** [comment]
I will install one of these browsers to test and provide feedback.  It's a great start.  Thanks!

**Comment by b-harper** [comment]
> If an RSS feed could be provided though, it seems that this would be pretty simple, and in Firefox at least

I created [this][0] quick and dirty script to create Live Bookmarks.   Far from ideal, but I guess it can hold over till there is native support.

[0]: https://gist.github.com/b-harper/b8b86d56195482dd577736f148205831

**Comment by xenithorb** [comment]
I want this because I want to add it to the Nextcloud News app (Feed reader), so that I can read links on my phone easily without switching to yet another app. That way this could behave like a sort of reading list

**Comment by sunjam** [comment]
[The activity app allows for an rss feed to be enabled under user settings](https://github.com/nextcloud/activity).  Not sure if some of that code could prove useful.

![enable-rss-activity](https://user-images.githubusercontent.com/1787238/41253728-1b41c7b8-6d76-11e8-9815-2b623bcd4505.png)

**Comment by marcelklehr** [comment]
We already have a pretty comprehensive query endpoint, so all that's needed to make this happen is to add a switch to that endpoint for controlling the output format and to implement an RSS output format.

**Comment by sunjam** [comment]
Awesome.

 I'd like to request adding authentication (user name / password) to the RSS feed.  This security feature is already supported when adding feeds to Nextcloud News and other clients.  [Also requested it here in the Activity App.](https://github.com/nextcloud/activity/issues/273)
![activity-rss-suggestion](https://user-images.githubusercontent.com/1787238/41254284-f11fa7b4-6d77-11e8-8e4f-a882306f612d.png)

[It is also useful to add the user/server name to the rss feed name](https://github.com/nextcloud/activity/issues/275) by default.

**Comment by marcelklehr** [comment]
If you're up for some early testing, check out https://github.com/nextcloud/bookmarks/pull/523 -- it allows you to access `<nextcloud>/apps/bookmarks/public/rest/v2/bookmark?format=rss` to get an easily digestable rss feed, with [the full querying power of the REST API](https://github.com/nextcloud/bookmarks/blob/master/API.md#query-bookmarks) on your hands.

**Comment by marcelklehr** [comment]
RSS feeds have been released as part of [v0.12.0-rc7](https://github.com/nextcloud/bookmarks/issues/522)
