### ISSUE TITLE
How to use Screenshot function with Webshot?

### ISSUE THREAD

**Issue by ingelumer** [nextcloud/bookmarks#2101]
Hello,
I would like to use the Screenshot functionality of the Booksmarks app in combination with a selfhosted Screenshot tool.
Screenly doesn't seem to have a working docker image.
Looking at Webshot it looks like there are many possible tools available.
Does anyone know which can be used with Nextcloud bookmarks and/or has installed it?

Thanks
Ingelumer

**Comment by marcelklehr** [comment]
Sorry about the delay. I'm not sure if the webshot service still exists. In the next version you will be able to use any service the has an API that directly returns the screenshot to a GET request.
