### ISSUE TITLE
[NC28] - `Could not resolve symfonyAdapter!` - Internal Server Error and tons of error messages in the nextcloud.log

### ISSUE THREAD

**Issue by rcfa** [nextcloud/bookmarks#2102]
**Describe the bug**
The app claims to be compatible with NC28, so I installed it from the NC Store.
Trying to access the app from the web interface results in an Internal Server Error.
Even when just desktop client apps connect to the NC28 instance, Bookmarks being enabled results in many large error messages filling up the nextcloud.log file.

**To Reproduce**
1) Take a NC28 instance (in my case on ARM64)
2) download and enable the Bookmarks app from the NC Store
3) watch the sparks fly

**Expected behavior**
it just works

**Screenshots**
error log file excerpt (with sensitive bits replaced) below

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox Nightly
 - Version: [e.g. 22]

**Server (please complete the following information):**
 - OS: Kali Rolling
 - HTTP server: apache
 - Database: MariaDB
 - PHP version: 8.2
 - Nextcloud version: 28 RC2
 - Bookmarks app version: 13.1.1
 - Activated Nextcloud Apps:

Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - analytics_sourcepack: 0.0.2
  - announcementcenter: 6.7.0
  - app_api: 1.4.1
  - approval: 1.1.1
  - assistant: 1.0.2
  - auto_groups: 1.5.2
  - bookmarks: 13.1.1
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.0
  - calendar_resource_management: 0.6.0-alpha.1
  - call_summary_bot: 1.0.0
  - camerarawpreviews: 0.8.4
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - cloud_py_api: 0.1.8
  - collectives: 2.9.2
  - comments: 1.18.0
  - contacts: 5.5.0-rc.2
  - contactsinteraction: 1.9.0
  - cookbook: 0.10.4
  - cospend: 1.5.12
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.0-beta.4
  - duplicatefinder: 1.1.4
  - epubviewer: 1.5.3
  - event_update_notification: 2.3.0
  - external: 5.3.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_3dmodelviewer: 0.0.12
  - files_accesscontrol: 1.18.0
  - files_antivirus: 5.4.0
  - files_automatedtagging: 1.18.0
  - files_confidential: 2.0.1
  - files_external: 1.20.0
  - files_lock: 28.0.0
  - files_mindmap: 0.0.30
  - files_notify_redis: 0.3.2
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_snapshots: 1.0.8
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - fileslibreofficeedit: 1.1.0
  - firstrunwizard: 2.17.0
  - flow_notifications: 1.8.0
  - forms: 4.0.0-alpha.2
  - gpoddersync: 3.8.2
  - gptfreeprompt: 1.0.2
  - gpxpod: 5.0.13
  - group_default_quota: 0.1.8
  - group_everyone: 0.1.14
  - groupfolders: 16.0.0
  - groupquota: 0.1.12
  - guests: 3.0.1
  - hibp_login_check: 0.0.2
  - impersonate: 1.15.0
  - integration_alephalpha: 1.0.0
  - integration_dropbox: 2.1.0
  - integration_excalidraw: 2.0.4
  - integration_giphy: 1.0.10
  - integration_github: 2.0.6
  - integration_gitlab: 1.0.18
  - integration_google: 2.1.0
  - integration_mastodon: 2.0.3
  - integration_mattermost: 1.0.5
  - integration_onedrive: 3.1.0
  - integration_openai: 1.1.5
  - integration_openstreetmap: 1.0.10
  - integration_peertube: 1.0.2
  - integration_reddit: 2.0.2
  - integration_replicate: 1.0.8
  - integration_slack: 1.0.1
  - integration_tmdb: 1.0.3
  - integration_twitter: 1.0.7
  - integration_youtube: 0.1.5
  - keeporsweep: 0.3.0
  - limit_login_to_ip: 4.0.0
  - llm: 1.2.1
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.0-rc.3
  - mediadc: 0.3.7
  - memegen: 1.0.6
  - music: 1.9.1
  - news: 25.0.0-alpha2
  - nextcloud_announcements: 1.17.0
  - nextpod: 0.7.4
  - notes: 4.9.0
  - notifications: 2.16.0
  - notify_push: 0.6.5
  - oauth2: 1.16.3
  - ocs_api_viewer: 1.0.4
  - oidc_login: 3.0.1
  - openincryptpad: 0.2.4
  - otpmanager: 0.3.2
  - password_policy: 1.18.0
  - passwords: 2023.12.30-build5234
  - passwords_handbook: 2023.11.21
  - permissions_overwrite: 0.1.11
  - photos: 2.4.0
  - picker: 1.0.7
  - polls: 6.0.0-rc1
  - previewgenerator: 5.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - qownnotesapi: 23.12.0
  - quota_warning: 1.18.0
  - recognize: 6.0.1
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - root_cache_cleaner: 0.1.6
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - sharelisting: 1.2.0
  - side_menu: 3.11.2
  - sketch_picker: 1.0.1
  - smb_test: 0.3.8
  - snappymail: 2.30.0
  - sociallogin: 5.6.0
  - socialsharing_diaspora: 3.0.1
  - socialsharing_email: 3.0.1
  - socialsharing_facebook: 3.0.1
  - socialsharing_telegram: 3.0.1
  - socialsharing_twitter: 3.0.1
  - spreed: 18.0.0-rc.3
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - tables: 0.6.4
  - tasks: 0.15.0
  - terms_of_service: 2.3.2-beta.4
  - text: 3.9.1
  - text2image_helper: 1.0.1
  - text2image_stablediffusion: 1.0.1
  - text_templates: 1.0.4
  - theming: 2.3.0
  - theming_customcss: 1.15.0
  - thesearchpage: 1.3.0-pre
  - timemanager: 0.3.9
  - translate: 2.0.0
  - twofactor_admin: 4.4.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_email: 2.7.4
  - twofactor_nextcloud_notification: 3.8.0
  - twofactor_totp: 10.0.0-beta.2
  - twofactor_webauthn: 1.3.2
  - unroundedcorners: 1.1.2
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_migration: 5.0.0
  - user_oidc: 1.3.5
  - user_retention: 1.11.0
  - user_saml: 6.0.1
  - user_status: 1.8.1
  - user_usage_report: 1.12.0
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - webapppassword: 23.12.0
  - welcome: 1.0.10
  - whereami: 0.0.30
  - workflow_script: 1.13.0
  - workflowengine: 2.10.0
Disabled:
  - analytics: 4.11.1 (installed 4.11.1)
  - appointments: 1.15.4 (installed 1.15.4)
  - audioplayer: 3.4.0 (installed 3.4.0)
  - backup: 1.2.0 (installed 1.2.0)
  - breezedark: 27.0.0 (installed 27.0.0)
  - cadviewer: 9.20.5 (installed 9.20.5)
  - calendar_news: 1.1.8 (installed 1.1.8)
  - carnet: 0.25.2 (installed 0.25.2)
  - cas: 0.2.11 (installed 0.2.11)
  - cfg_share_links: 4.2.0 (installed 4.2.0)
  - checksum: 1.2.2 (installed 1.2.2)
  - chores: 0.0.5
  - data_request: 1.14.0 (installed 1.14.0)
  - dicomviewer: 1.2.5 (installed 1.2.5)
  - drawio: 2.1.4 (installed 2.1.4)
  - drop_account: 2.3.2 (installed 2.3.2)
  - emlviewer: 1.0.8 (installed 1.0.8)
  - encryption: 2.16.0 (installed 2.15.0)
  - externalportal: 1.2.0 (installed 1.2.0)
  - extract: 1.3.6 (installed 1.3.6)
  - facerecognition: 0.9.31 (installed 0.9.31)
  - files_archive: 1.1.3 (installed 1.1.3)
  - files_bpm: 1.2.0 (installed 1.2.0)
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_downloadlimit: 1.1.0 (installed 1.1.0)
  - files_fulltextsearch: 28.0.0 (installed 28.0.0)
  - files_fulltextsearch_tesseract: 27.0.0 (installed 27.0.0)
  - files_linkeditor: 1.1.16 (installed 1.1.16)
  - files_markdown: 2.4.1 (installed 2.4.1)
  - files_photospheres: 1.27.0 (installed 1.27.0)
  - files_retention: 1.16.0 (installed 1.16.0)
  - files_scripts: 3.0.0 (installed 3.0.0)
  - files_texteditor: 2.15.1 (installed 2.15.1)
  - files_zip: 1.4.0 (installed 1.4.0)
  - fulltextsearch: 28.0.0 (installed 28.0.0)
  - fulltextsearch_elasticsearch: 28.0.0 (installed 28.0.0)
  - geoblocker: 0.5.11 (installed 0.5.11)
  - gestion: 2.4.1 (installed 2.4.1)
  - google_synchronization: 1.0.9 (installed 1.0.9)
  - health: 1.6.2 (installed 1.6.2)
  - hedgenext: 0.0.13 (installed 0.0.13)
  - hibp: 0.1.0 (installed 0.1.0)
  - imageconverter: 1.3.5 (installed 1.3.5)
  - integration_discourse: 2.0.4 (installed 2.0.4)
  - keeweb: 0.6.13 (installed 0.6.13)
  - ldap_contacts_backend: 1.7.0 (installed 1.7.0)
  - ldap_write_support: 1.9.0 (installed 1.9.0)
  - libresign: 7.1.1 (installed 7.1.1)
  - majordomo: 1.1.5 (installed 1.1.5)
  - maps: 1.2.0 (installed 1.2.0)
  - memories: 6.1.5 (installed 6.1.5)
  - metadata: 0.19.0 (installed 0.19.0)
  - money: 0.23.1 (installed 0.23.1)
  - oidc: 0.7.1 (installed 0.7.1)
  - pandoc: 0.6.0 (installed 0.6.0)
  - phonetrack: 0.7.6 (installed 0.7.6)
  - preferred_providers: 1.13.1 (installed 1.13.1)
  - quickaccesssorting: 3.0.0 (installed 3.0.0)
  - quicknotes: 0.8.10 (installed 0.8.10)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - registration: 2.2.0 (installed 2.2.0)
  - report_uri: 0.0.1 (installed 0.0.1)
  - richdocuments: 8.3.0-beta.1 (installed 8.3.0-beta.1)
  - richdocumentscode_arm64: 23.5.602 (installed 23.5.602)
  - riotchat: 0.16.4 (installed 0.16.4)
  - scanner: 0.2.3 (installed 0.2.3)
  - secrets: 1.5.2 (installed 1.5.2)
  - sharepoint: 1.15.0 (installed 1.15.0)
  - sharerenamer: 3.2.0 (installed 3.2.0)
  - shifts: 1.9.3 (installed 1.9.3)
  - sip_trip_phone: 1.1.1 (installed 1.1.1)
  - skyprint: 0.1.4 (installed 0.1.4)
  - snowflakestheme: 1.1.0 (installed 1.1.0)
  - social: 0.6.1 (installed 0.6.1)
  - solid: 0.7.2 (installed 0.7.2)
  - talk_matterbridge: 1.27.0-0 (installed 1.27.0-0)
  - talked: 0.5.0 (installed 0.5.0)
  - timetracker: 0.0.80 (installed 0.0.80)
  - tvshownamer: 0.6.2 (installed 0.6.2)
  - uppush: 1.4.0 (installed 1.4.0)
  - user_external: 3.2.0 (installed 3.2.0)
  - users_picker: 0.2.2 (installed 0.2.2)
  - video_converter: 1.0.6 (installed 1.0.6)
  - weather: 1.7.7 (installed 1.7.7)
  - workflow_kitinerary: 1.3.0 (installed 1.3.0)
  - workflow_media_converter: 1.8.4 (installed 1.8.4)
  - workflow_ocr: 1.27.5 (installed 1.27.5)
  - workflow_pdf_converter: 1.12.0 (installed 1.12.0)
  - workspace: 3.0.3 (installed 3.0.3)

 - Nextcloud configuration: 
 
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "log_file": "nextcloud.log",
        "logdateformat": "c",
        "loglevel": 1,
        "dbtype": "mysql",
        "version": "28.0.0.8",
        "overwrite.cli.url": "http:\/\/192.168.178.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta",
        "installed": true,
        "app_install_overwrite": [
            "calendar",
            "richdocumentscode_arm64",
            "spreed",
            "deck",
            "groupfolders",
            "quota_warning",
            "announcementcenter",
            "files_accesscontrol",
            "files_automatedtagging",
            "files_retention",
            "terms_of_service",
            "notes",
            "end_to_end_encryption",
            "breezedark",
            "richdocumentscode",
            "passwords",
            "ransomware_protection",
            "files_antivirus",
            "geoblocker",
            "gpgmailer",
            "user_unix_script",
            "side_menu",
            "money",
            "appointments",
            "checksum",
            "backup",
            "cadviewer",
            "health",
            "files_zip",
            "ldap_write_support",
            "webhooks",
            "weather",
            "user_migration",
            "drop_account",
            "timemanager",
            "timetracker",
            "files_snapshots",
            "sharerenamer",
            "smb_test",
            "user_external",
            "passman",
            "permissions_overwrite",
            "polls",
            "qownnotesapi",
            "quicknotes",
            "scanner",
            "root_cache_cleaner",
            "sharelisting",
            "riotchat",
            "talked",
            "files_scripts",
            "files_staticmimecontrol",
            "workflow_pdf_converter",
            "workflow_script",
            "fulltextsearch",
            "fulltextsearch_elasticsearch",
            "files_fulltextsearch",
            "files_fulltextsearch_tesseract",
            "bookmarks_fulltextsearch",
            "workspace",
            "files_3dmodelviewer",
            "files_mindmap",
            "files_linkeditor",
            "libresign",
            "files_inotify",
            "files_downloadactivity",
            "group_default_quota",
            "electronicsignatures",
            "emlviewer",
            "files_downloadlimit",
            "groupquota",
            "cas",
            "gpoddersync",
            "keeweb",
            "majordomo",
            "oidc",
            "integration_whiteboard",
            "talk_matterbridge",
            "storj",
            "solid",
            "oidc_login",
            "dicomviewer",
            "memories",
            "imageconverter",
            "souvenirs",
            "tvshownamer",
            "nextpod",
            "uppush",
            "carnet",
            "event_update_notification",
            "pandoc",
            "sip_trip_phone",
            "whereami",
            "bookmarks",
            "calendar_news",
            "cookbook",
            "approval",
            "audioplayer",
            "auto_groups",
            "files_bpm",
            "calendar_resource_management",
            "camerarawpreviews",
            "notify_push",
            "cloud_py_api",
            "collectives",
            "cospend",
            "data_request",
            "integration_deepl",
            "integration_discourse",
            "integration_dropbox",
            "group_everyone",
            "integration_excalidraw",
            "external",
            "integration_youtube",
            "flow_notifications",
            "forms",
            "gestion",
            "integration_google",
            "google_synchronization",
            "guests",
            "hibp",
            "impersonate",
            "integration_mastodon",
            "integration_mattermost",
            "mediadc",
            "messagevault",
            "news",
            "richdocuments",
            "integration_onedrive",
            "files_texteditor",
            "preferred_providers",
            "previewgenerator",
            "registration",
            "report_uri",
            "snappymail",
            "social",
            "user_saml",
            "tasks",
            "files_lock",
            "twofactor_webauthn",
            "user_usage_report",
            "maps",
            "integration_twitter",
            "socialsharing_diaspora",
            "socialsharing_facebook",
            "socialsharing_twitter",
            "socialsharing_email",
            "workflow_kitinerary",
            "workflow_media_converter",
            "workflow_ocr",
            "tables",
            "secrets",
            "phonetrack",
            "drawio",
            "user_retention",
            "shifts",
            "ldap_contacts_backend",
            "files_markdown",
            "video_converter",
            "files_photospheres",
            "facerecognition",
            "music",
            "users_picker",
            "skyprint",
            "files_notify_redis",
            "mfazones",
            "metadata",
            "hedgenext",
            "quickaccesssorting",
            "extract",
            "cfg_share_links",
            "files_archive",
            "externalportal",
            "onlyoffice",
            "sharepoint",
            "otpmanager",
            "hibp_login_check"
        ],
        "default_phone_region": "US",
        "maintenance": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "enforce_theme": "",
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-aarch64-glibc",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-aarch64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "memories.gis_type": 1
    }
}

 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
nothing pertinent
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
due to length as attachment
[nextcloud.log.excerpt.txt](https://github.com/nextcloud/bookmarks/files/13605996/nextcloud.log.excerpt.txt)

```

**Browser log**
```
nothing pertinent
```

**Comment by jakobroehrl** [comment]
same problem with NC28

**Comment by joshtrichards** [comment]
It appears that the `bookmarks` app's NC28 compatibility may have been specified prior to NC28's final release and one of the change it needs to be updated for is nextcloud/server#39605.

**Comment by kernal64** [comment]
Same here

**Comment by Luzl1** [comment]
I can confirm the issue.

**Comment by marcelklehr** [comment]
https://github.com/nextcloud/bookmarks/releases/tag/v13.1.2 is out now

**Comment by reeno** [comment]
installed & tested > works. Thanks!

**Comment by Luzl1** [comment]
Thanks for the fix!

**Comment by rcfa** [comment]
Thanks!
