### ISSUE TITLE
Bookmarks cannot be moved from folder to root

### ISSUE THREAD

**Issue by steckerhalter** [nextcloud/bookmarks#2103]
I'd like to move bookmarks from a subfolder to the top or root, but I'm not able to.
When I select bookmarks in a folder and choose "move selection" I cannot move them to the root, only to another subfolder.

Nextcloud Server is 27.1.4
Bookmarks is 13.1.1

**Comment by marcelklehr** [comment]
Initially after clicking on Move selection, you see the contents of the root folder. When you click Choose folder now, the selection should be put into the root folder.

**Comment by steckerhalter** [comment]
Ok thanks this works. I think what confused me was that a folder is already highlighted. Maybe the root folder could be clarified in the UI?
