### ISSUE TITLE
performing search crashes server

### ISSUE THREAD

**Issue by mortee** [nextcloud/bookmarks#2110]
I admittedly run NC on a limited performance NAS (most limiting is the 2GB RAM), but still.

When I perform a search on the Bookmarks app interface, my server starts trashing, load goes up to 40+, and it eventually either reboots or docker catches up first and all the containers are restarted.

I would guess typing in the search bar sends dozens (if not thousands?) of requests simultaneously for some reason, with which the server cannot cope. 

In any case, other NC search functionality, while not blazingly fast, but at least don't crash my server.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 120

**Server (please complete the following information):**
 - OS: armbian bullseye
 - HTTP server: nginx 1.18
 - Database: MariaDB 10.11
 - PHP version: 8.2.13
 - Nextcloud version: 28.0
 - Bookmarks app version: 13.1.3

**Comment by marcelklehr** [comment]
Confirmed.
