### ISSUE TITLE
You can not leave a Share

### ISSUE THREAD

**Issue by ZID-TU-Graz-Collab** [nextcloud/bookmarks#2116]
Description:
There is no option to get rid of a bookmarks-folder shared with you.
Even when you try to delete the bookmarks or the whole folder, it persists.

1. Login as Person A
2. Go to bookmarks and create a new folder
3. add various bookmarks to that folder
4. Share that folder via the 3 dot menu to Person B
5. Login as Person B
6. Go to bookmarks and try to get rid of the folder

Expected behavior:
There should be an option to leave the share.

Available Options for Person B:
![Screenshot 2024-01-19 104850](https://github.com/nextcloud/bookmarks/assets/100593683/0f2e7f3d-a20b-4977-ac64-bb9bbe43b6a7)

**Comment by marcelklehr** [comment]
You can put it in the trash bin now where it will stay forever.
