### ISSUE TITLE
Bookmarks counter wrong

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/bookmarks#2133]
**Describe the bug**
Just deleted my bookmarks and now the bookmark counter is wrong, showing 13 bookmarks and the main screen telling me there are no bookmarks here.

**To Reproduce**
1. Previously use bookmarks.
2. Deleted bookmarks.
3. Be unable to delete them all as counter shows non-zero value with zero bookmarks.

**Expected behavior**
Counter should indicate zero or be gone.

**Screenshots**
![image](https://github.com/nextcloud/bookmarks/assets/47887158/49a3db28-f77c-4a4e-9da8-17093fdcd6f3)

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3
 - Browser: Firefox
 - Version: 122.0.1

**Server (please complete the following information):**
 - OS: Ubuntu
 - HTTP server: Apache
 - Database: Postgresql
 - PHP version: 8.1
 - Nextcloud version: 28.0.2
 - Bookmarks app version: 13.1.3
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by InfamousUser** [comment]
Turns out when I resynced the bookmarks from my device, there were 13 bookmarks that became visible...

**Comment by marcelklehr** [comment]
Yeah, it's possible this is an old remnant from an old migration when folders were first introduced. The bookmarks would not have been in any folder then, so are not visible from the "All bookmarks" view, but may have been visible from the "Recent bookmarks" view for example.

**Comment by InfamousUser** [comment]
So this should not reoccur?

**Comment by marcelklehr** [comment]
I'm not sure. It's unlikely to occur again, I think. If it does reoccur, could you send me a dump of the oc_bookmarks* tables? That would be great.

**Comment by InfamousUser** [comment]
Alright, I'll close this for now then.
