### ISSUE TITLE
Support for servers with self-signed certificates

### ISSUE THREAD

**Issue by cyb3rm00n** [nextcloud/bookmarks#2135]
**Is your feature request related to a problem? Please describe.**
I am using the app in a LineageOS 20 (Android 13) device and I have a local NextCloud server at home with self-signed SSL certificates. I would like to use Bookmarks app but I can't as it says "Failed Connection" due to the self-signed certificate. 

The CA has been installed in Android and it appears in the trusted CA settings, so I'd expect in this case that the app would consider the certificate to be "trusted".

**Describe the solution you'd like**
It'd be nice to support self-signed certificates.

**Comment by marcelklehr** [comment]
This is the wrong repository. This is the server app Bookmarks. You want to report this for the android app.
