### ISSUE TITLE
may be GDPR evidence: The user cannot delete all BMs of a user

### ISSUE THREAD

**Issue by pflegende** [nextcloud/bookmarks#2136]
**Describe the bug**

No Function for **Deleting ALL bookmarks** 
nowhere seen and described (be aware: GDPR says allways a user manual is needed)

May be here is imminent danger because of legal fail.

It is **not** enough that a Admin possibly upon request can do this!

hint:
The user has no abiltiy for using system permissions.

--

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS X]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7]
 - HTTP server: [e.g. nginx 1.1]
 - Database: [e.g. MySQL 5.3]
 - PHP version: [e.g. v7.2]
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)]
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)]
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
Hello @pflegende :wave: 

Are you not able to delete all bookmarks by selecting them all and then deleting them?

**Comment by marcelklehr** [comment]
> be aware: GDPR says allways a user manual is needed

( I currently have no capacity to write a user manual and legally I believe I am not obliged to do so because I do not host any service. If you host a Nextcloud instance with bookmarks installed, you may be obliged to provide a user manual, though. If you want to write one, I'm happy to add it here. )
