### ISSUE TITLE
Add an internal API to add bookmarks to add bookmarks from other apps

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/bookmarks#215]
This is a feature request for interacting with the News app. We want to be able to add certain articles as bookmarks.

This should be implemented using an internal controller, e.g. a controller called BookmarksController.

The API should look like this:

**POST /apps/bookmarks/bookmarks**:

``` js
{
  "url": "https://url.to/bookmark",  // required
  "name": "a title", // optional, if not given derived from the websites' title attribute
  "tags": ["tag1", "tag2"] // optional, if not existent, they should be created
}
```

The user that owns the bookmark is the currently logged in user.

It should have the following HTTP error codes:
- 404: if the url does not exist
- 409: if the bookmark exists already

It should return the newly created bookmark in JSON format.

**Comment by blizzz** [comment]
how would you deal with inter-app dependencies? good enough to just check whether bookmarks is enabled? Otherwise we'd need to get a service into core.

**Comment by marcelklehr** [comment]
As @blizzz [mentioned](https://github.com/nextcloud/bookmarks/issues/393#issuecomment-315450171), this should be possible with the new REST controller.
