### ISSUE TITLE
Add option to display url if name is empty

### ISSUE THREAD

**Issue by Emporea** [nextcloud/bookmarks#2156]
When having several bookmarks that have no name ( just identifying them by favico in the browser bookmarks menu bar ) it would be nice to have an option in the settings menu of the bookmarks nextcloud app to show the url in case the name is empty. 
Some nextcloud instances disallow the fetching of favicons, so those bookmarks then become hard to determine and its not intuitive anymore.

Being able to see the link instead would be helpful.

**Comment by marcelklehr** [comment]
Good thinking, but url is a computed property defined in the script block below, so it should work. Maybe your title is not empty but has some whitespace?

**Comment by marcelklehr** [comment]
Oh, no. I haven't had time to look into this further so far.

**Comment by marcelklehr** [comment]
You were completely right :) I didn't realize the title prop was only used for editing the title. The actual display of the title is done in the #title slot, of course. Thank you!
