### ISSUE TITLE
Bookmarks app is glitching out in the browser

### ISSUE THREAD

**Issue by morgannunan** [nextcloud/bookmarks#2159]
**Describe the bug**
When I click a folder and scroll the results panel, I just get flickering gray bars.

**To Reproduce**
1. Go to bookmarks
2. Click on a bookmark folder
3. Scroll down to see the bookmarks under the fold

**Expected behavior**
See all the bookmarks

**Screenshots**
![image](https://github.com/nextcloud/bookmarks/assets/8991137/d58ed32f-80be-4e4e-880f-7182b7c12f2f)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Vivaldi (Chromium)
 - Version: 6.7.3329.31

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - HTTP server: Apache 2
 - Database: MySql 15.1
 - PHP version: 7.4.33
 - Nextcloud version: 25.0.13
 - Bookmarks app version: 12.1.0
 - Activated Nextcloud Apps:
 - activity: 2.17.0
  - admin_audit: 1.15.0
  - bookmarks: 12.1.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.6.8
  - cloud_federation_api: 1.8.0
  - contacts: 5.5.3
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - music: 1.11.0
  - news: 22.0.0
  - notes: 4.10.0
  - notifications: 2.13.1
  - oauth2: 1.13.1
  - password_policy: 1.15.0
  - passwords: 2023.12.12
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - side_menu: 3.12.0
  - tasks: 0.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0

 - Nextcloud configuration:
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "jukebox"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.13.2",
        "overwrite.cli.url": "http:\/\/jukebox\/cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "filelocking.enabled": true,
        "app_install_overwrite": [
            "ldapcontacts",
            "ldaporg",
            "calendar",
            "ldap_write_support"
        ],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "loglevel": 0,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "mysql.utf8mb4": true
    }
}
```

**Comment by marcelklehr** [comment]
> 
> 
> Nextcloud version: 25.0.13
> 
> Bookmarks app version: 12.1.0
>

These are quite old versions, actually. They're from 2022, i think. v25 is no longer receiving updates, too. Can you try updating to a Nextcloud version that is still maintained? That would be at least v27, I think

**Comment by morgannunan** [comment]
Huh. Then why would it say this in the admin overview?

![image](https://github.com/nextcloud/bookmarks/assets/8991137/a99dc5b8-4ac6-4af7-ae88-33e5c927343b)

**Comment by marcelklehr** [comment]
Good question. You likely cannot update because your server is still in php7.4. nowadays php8 is required.

**Comment by morgannunan** [comment]
OK, I brought everything up to the latest version: NC 29.0.1, News 24.0.0. Things are looking wackier than ever. Here's my sidebar:
![image](https://github.com/nextcloud/bookmarks/assets/8991137/8838ddb1-67ed-4be3-b217-df6eff77e34f)

**Comment by marcelklehr** [comment]
I can reproduce. This is not the News app repo, though

**Comment by morgannunan** [comment]
Whoops. sorry. I moved this issue to that repo.

**Comment by morgannunan** [comment]
I can also confirm that the original bug identified in this issue is now resolved when I update to NC 29 and Bookmarks 14.1.1.

**Comment by vbresan** [comment]
I am experiencing this issue with NC 29.0.3 and Bookmarks 14.2.2. The browser is Firefox 115.13.0esr. Please see the attached video.

https://github.com/user-attachments/assets/7b3415e9-d4e5-4369-8b9b-990eb580bc0b

**Comment by marcelklehr** [comment]
Hi @vbresan 
Could you please open a new issue, ideally also with some browser console logs to see what's going on :)
