### ISSUE TITLE
Import from Firefox export cuts off URLs

### ISSUE THREAD

**Issue by MrksKwsnck** [nextcloud/bookmarks#216]
Long time ago I exported my ownCloud bookmarks and imported them into Firefox Bookmark Manager successfully. For a while I just managed the bookmarks there.

Then I exported my Firefox bookmarks as HTML file and tried to import it now back into ownCloud's bookmark app. First the import seemed to work properly, but then I realized all the URLs are gone?!

So the import mechanism imported all bookmark _titles_ and all _tags_ I used. But unfortunately no URLs got imported. Any bookmark URL is set to: `http://`

Running:
- ownCloud 8.2.1
- Bookmarks App 0.6
- Don't remember the Firefox version :-(

Well, can you fix that?

**Comment by marcelklehr** [comment]
Cannot reproduce. Likely has been fixed. Shout if this is not the case, though :)
