### ISSUE TITLE
Refresh of "folder infos" right-panel is not working

### ISSUE THREAD

**Issue by Yann-974** [nextcloud/bookmarks#2164]
Warning : My language interface is French. So I've tried to translate the texts of the interface in english, some errors would occurs !

**Describe the bug**
When you are in the page where all the folders are listed, then you choose "infos" of one of those folders. The "infos" right-panel opens and shows details and sharing for the chosen folder.
But if you select another folder, there is no refresh of informations in the right-panel "infos".

**To Reproduce**
1. Go to 'All bookmarks'
2. Click on '...' from a folder
3. Select 'infos' to launch the dedicated right-panel
4. Then select another folder
5. See error

**Expected behavior**
An automatic refresh of data in the right-panel to follow the selected element.

**Screenshots**
![image](https://github.com/nextcloud/bookmarks/assets/78294159/d356bce3-abbb-464a-bb94-3b92c5aba2c8)

**Desktop**
 - OS: Linux KDE NEON
 - Browser: FFox
 - Version: 126.0.1

**Server**
no data available

**Additional context**
-

**Web server error log**
no access to the logs

**Nextcloud log (nextcloud/data/nextcloud.log)**
no access to the logs

**Browser log**
not interesting for this purpose

**Comment by Yann-974** [comment]
Bookmarks v.14.0.2

**Comment by marcelklehr** [comment]
Hey Yann!
I think this is by design as you can also open the details of a folder that is not the currently opened folder.

**Comment by marcelklehr** [comment]
I agree that this would be a nice feature though.
