### ISSUE TITLE
Visible click counters and ability to reset them

### ISSUE THREAD

**Issue by mord0d** [nextcloud/bookmarks#2166]
### Is your feature request related to a problem? Please describe.

I have *a lot* of bookmarks and *I think* some of them are not used at all. To clean up the list I would like to see if I use the link or not.

### Additional context

With a visible click counters (which are already stored in database and used for sorting), user can see how much they use each link. If you prefer the old behavior, this can be implemented as an option (on/off in settings).

In addition, it would be great to have ability to reset counters per item (in its menu) and for all bookmarks (in settings).

**Comment by marcelklehr** [comment]
That's a good idea. I wonder how meaningful the raw numbers are, though. Maybe some more visual high/low indicator would be more appropriate?

**Comment by mord0d** [comment]
> visual high/low indicator

This is the same as **“Sort by click count”**, isn't it?

The algo must be tricky to be more precise:

- We have just one link with 1'000'000 clicks and a lot of links with 0; if we add a link with 10'000 clicks it will be “low” but in fact it's far more than 0.  
- We have a lot of links with 0 clicks; if we add a link with just 1 click, it will be “high”.

**Comment by marcelklehr** [comment]
How about: average click count +- 15% is medium; everything below is low, everything above is high?

**Comment by marcelklehr** [comment]
cc @jancborchardt / @nextcloud/designers / @nextcloud/designers-community

**Comment by marcelklehr** [comment]
I could imagine something like this
![image](https://github.com/nextcloud/bookmarks/assets/986878/e6cedd25-b888-4564-94d4-70b8b8574d3c)

**Comment by mord0d** [comment]
> How about: average click count +- 15% is medium; everything below is low, everything above is high?

Looks reasonable.

> The exact count could be shown on hover then

Great idea!

**Comment by mord0d** [comment]
> I could imagine something like this

*// Pseudocode:*

```
if clicks == 0:
  img = 0of3.svg
elseif clicks < avg:
  img = 1of3.svg
elseif clicks == avg:
  img = 2of3.svg
else:
  img = 3of3.svg
```

The idea is always show 0/3 for 0 clicks even if average click count is low (<=1).

**Comment by marcelklehr** [comment]
I've released this already, have a look at v14.2.0

**Comment by mord0d** [comment]
> I've released this already

Thanks!

> have a look

Sadly, I won't be able to do this any time soon. Disks are dead.

**Comment by mord0d** [comment]
Great! Better than I expected. ☺ @marcelklehr thank you!

---

**NOTE:** After upgrade, if you get `🔥🔥🔥` for all the links no matter of click count, just clear the cache.

**Comment by marcelklehr** [comment]
> Great! Better than I expected. ☺ @marcelklehr thank you!

Yay, I'm gald you like it :)
