### ISSUE TITLE
Loaded bookmarks (only viewed through the normal view) are added also to Trash Bin section

### ISSUE THREAD

**Issue by estux** [nextcloud/bookmarks#2167]
**Describe the bug**
I opened Bookmarks app and started navigating through folders I created (only viewing what bookmarks I have). 
Then I went to Trash Bin and seen the "viewed" items added also there. 
So I exited the app and then opened again (I have 3 bookmarks that aren't in any folder). 
Opened the Trash Bin and saw the 3 loaded bookmarks (the one seen in the previous view, that aren't in any folder, loaded in the main view) added also there. 
So every time you go out and come back the view in the Trash Bin is reset and shows only the "last viewed-navigated items" from the main view.

**To Reproduce**
1. Open Bookmarks app
2. Have some bookmarks that aren't in any folder (e.g. 3 of them)
3. Click to see what bookmarks you have inside a folder (e.g. 8)
4. Open the Trash Bin
5. You can see 3+8 items "viewed" before in the Trash Bin view.
6. It seems that they aren't really trashed because if you come back to the main view you can still see e.g. the first 3 bookmarks (the ones that aren't in any folder)
7. Now you can try exiting Bookmarks app
8. open again Bookmarks app
9. In the main view the 3 bookmarks that aren't in any folder are automatically "loaded"
10. Go again to the Trash Bin to see only this 3 bookmarks in the Trash Bin view.

**Expected behavior**
No bookmarks seen in the Trash Bin as I didn't trashed any bookmark.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 126.0.1

**Server (please complete the following information):**
 - OS: Linux 5.15.149-1-pve
 - HTTP server: nginx/1.18.0 (fpm-fcgi)
 - Database: mysql 10.5.23
 - PHP version: 8.2.14
 - Nextcloud version: 28.0.6
 - Bookmarks app version: 14.1.1
 - Activated Nextcloud Apps: 
Enabled:
 - activity: 2.20.0
 - bookmarks: 14.1.1
 - bruteforcesettings: 2.8.0
 - calendar: 4.7.6
 - camerarawpreviews: 0.8.5
 - circles: 28.0.0
 - cloud_federation_api: 1.11.0
 - collectives: 2.11.0
 - comments: 1.18.0
 - contacts: 5.5.3
 - contactsinteraction: 1.9.0
 - cospend: 1.6.1
 - dashboard: 7.8.0
 - dav: 1.29.1
 - deck: 1.12.2
 - federatedfilesharing: 1.18.0
 - federation: 1.18.0
 - files: 2.0.0
 - files_pdfviewer: 2.9.0
 - files_reminders: 1.1.0
 - files_sharing: 1.20.0
 - files_trashbin: 1.18.0
 - files_versions: 1.21.0
 - firstrunwizard: 2.17.0
 - forms: 4.2.4
 - groupfolders: 16.0.6
 - inventory: 0.1.2
 - logreader: 2.13.0
 - lookup_server_connector: 1.16.0
 - maps: 1.4.0
 - news: 25.0.0-alpha3
 - nextcloud_announcements: 1.17.0
 - notes: 4.10.0
 - notifications: 2.16.0
 - oauth2: 1.16.3
 - password_policy: 1.18.0
 - photos: 2.4.0
 - polls: 7.0.3
 - privacy: 1.12.0
 - provisioning_api: 1.18.0
 - recommendations: 2.0.0
 - related_resources: 1.3.0
 - richdocuments: 8.3.7
 - serverinfo: 1.18.0
 - settings: 1.10.1
 - sharebymail: 1.18.0
 - spreed: 18.0.8
 - support: 1.11.1
 - survey_client: 1.16.0
 - suspicious_login: 6.0.0
 - systemtags: 1.18.0
 - tables: 0.7.2
 - tasks: 0.16.0
 - text: 3.9.1
 - theming: 2.3.0
 - twofactor_backupcodes: 1.17.0
 - updatenotification: 1.18.0
 - user_status: 1.8.1
 - viewer: 2.2.0
 - weather_status: 1.8.0
 - workflowengine: 2.10.0
Disabled:
 - admin_audit
 - carnet: 0.25.4
 - encryption
 - files_external
 - files_rightclick: 1.6.0
 - mail: 3.7.0
 - twofactor_totp
 - unsplash: 2.2.1
 - user_ldap

 - Nextcloud configuration: 
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "my domain (sensitive value)"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "28.0.6.1",
    "overwrite.cli.url": "https:\/\/my domain (sensitive value)",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "logtimezone": "Europe\/Amsterdam",
    "maintenance": false,
    "loglevel": 0,
    "filesystem_check_changes": 1,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "has_rebuilt_cache": true,
    "default_phone_region": "IT",
    "versions_retention_obligation": "auto,90",
    "trashbin_retention_obligation": "auto,30",
    "updater.release.channel": "stable"
}

 - Nextcloud external user backend: none

**Additional context**

**Web server error log**
```
No errors related to Bookmarks seem to be recorded.
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
Confirmed.

**Comment by marcelklehr** [comment]
Workaround for now is to reload the page after accessing the trash bin

**Comment by estux** [comment]
> Workaround for now is to reload the page after accessing the trash bin

Thanks for looking into this and confirming!
I'm fine with the workaround ...... I only hope it doesn't automatically trash some bookmarks!

**Comment by marcelklehr** [comment]
Yeah, I understand that it's disconcerting to see stuff in the bin that shouldn't be there. I'll fix this soon.

**Comment by estux** [comment]
Thank you so much for working so fast on this! :)
