### ISSUE TITLE
Visual glitches (content messed up) in the Details screen on the right sidebar

### ISSUE THREAD

**Issue by estux** [nextcloud/bookmarks#2168]
**Describe the bug**
Details screen content is messed up (centered and icons + content spread in multiple lines)

**To Reproduce**
1. Open Bookmarks app
2. Click on the 3 dots menu of a bookmark
3. Click on "Details"
4. See content messed up in the right sidebar and misaligned text + icon in the main central view.

**Expected behavior**
Content (properties) well aligned and recognizable at first sight.

**Screenshots**
![Bookmarks-screenshot](https://github.com/nextcloud/bookmarks/assets/145768753/384fd11e-05ae-4673-a474-eeaf10a2712c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 126.0.1

**Server (please complete the following information):**
 - OS: Linux 5.15.149-1-pve
 - HTTP server: nginx/1.18.0 (fpm-fcgi)
 - Database: mysql 10.5.23
 - PHP version: 8.2.14
 - Nextcloud version: 28.0.6
 - Bookmarks app version: 14.1.2 (but also present in 14.1.1 at least)
 - Activated Nextcloud Apps:
Enabled:
 - activity: 2.20.0
 - bookmarks: 14.1.1
 - bruteforcesettings: 2.8.0
 - calendar: 4.7.6
 - camerarawpreviews: 0.8.5
 - circles: 28.0.0
 - cloud_federation_api: 1.11.0
 - collectives: 2.11.0
 - comments: 1.18.0
 - contacts: 5.5.3
 - contactsinteraction: 1.9.0
 - cospend: 1.6.1
 - dashboard: 7.8.0
 - dav: 1.29.1
 - deck: 1.12.2
 - federatedfilesharing: 1.18.0
 - federation: 1.18.0
 - files: 2.0.0
 - files_pdfviewer: 2.9.0
 - files_reminders: 1.1.0
 - files_sharing: 1.20.0
 - files_trashbin: 1.18.0
 - files_versions: 1.21.0
 - firstrunwizard: 2.17.0
 - forms: 4.2.4
 - groupfolders: 16.0.6
 - inventory: 0.1.2
 - logreader: 2.13.0
 - lookup_server_connector: 1.16.0
 - maps: 1.4.0
 - news: 25.0.0-alpha3
 - nextcloud_announcements: 1.17.0
 - notes: 4.10.0
 - notifications: 2.16.0
 - oauth2: 1.16.3
 - password_policy: 1.18.0
 - photos: 2.4.0
 - polls: 7.0.3
 - privacy: 1.12.0
 - provisioning_api: 1.18.0
 - recommendations: 2.0.0
 - related_resources: 1.3.0
 - richdocuments: 8.3.7
 - serverinfo: 1.18.0
 - settings: 1.10.1
 - sharebymail: 1.18.0
 - spreed: 18.0.8
 - support: 1.11.1
 - survey_client: 1.16.0
 - suspicious_login: 6.0.0
 - systemtags: 1.18.0
 - tables: 0.7.2
 - tasks: 0.16.0
 - text: 3.9.1
 - theming: 2.3.0
 - twofactor_backupcodes: 1.17.0
 - updatenotification: 1.18.0
 - user_status: 1.8.1
 - viewer: 2.2.0
 - weather_status: 1.8.0
 - workflowengine: 2.10.0
Disabled:
 - admin_audit
 - carnet: 0.25.4
 - encryption
 - files_external
 - files_rightclick: 1.6.0
 - mail: 3.7.0
 - twofactor_totp
 - unsplash: 2.2.1
 - user_ldap

 - Nextcloud configuration:
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "my domain"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "28.0.6.1",
    "overwrite.cli.url": "https:\/\/my domain",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "logtimezone": "Europe\/Amsterdam",
    "maintenance": false,
    "loglevel": 0,
    "filesystem_check_changes": 1,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "has_rebuilt_cache": true,
    "default_phone_region": "IT",
    "versions_retention_obligation": "auto,90",
    "trashbin_retention_obligation": "auto,30",
    "updater.release.channel": "stable"
}

 - Nextcloud external user backend: none

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
Confirmed

**Comment by estux** [comment]
Thank you again @marcelklehr ! :) Great job!
