### ISSUE TITLE
Cannot permanently delete bookmarks

### ISSUE THREAD

**Issue by kozmik-moore** [nextcloud/bookmarks#2169]
**Describe the bug**
I tried to permanently delete bookmarks from the trashbin. The bookmarks disappear but, upon a refresh of the web browser, they reappear in the trashbin.

**To Reproduce**

1. Select bookmark and click 'Put bookmark into trash bin'.
2. Click on 'Trash Bin'.
3. Right-click or click three dots on recently deleted bookmark and select 'Delete bookmark permanently' from drop down (Menu disappears and bookmark is removed from view).
4. Refresh web browser (regular refresh and hard refresh using Ctrl-Shift-R and Ctrl-F5).
5. Bookmark reappears in Trash Bin view.

**Expected behavior**
I expected the bookmark to be permanently removed from the system (not present in Trash Bin view).

**Screenshots**
![issue_1](https://github.com/nextcloud/bookmarks/assets/11305345/52723871-3299-4505-a2f8-7870064d30b5)
![issue_2](https://github.com/nextcloud/bookmarks/assets/11305345/7fbf072f-e623-4a99-ae9d-c8ca1a61149c)
![issue_3](https://github.com/nextcloud/bookmarks/assets/11305345/03e83fde-4fad-4b83-82bc-7e6ae39283d4)
![issue_4](https://github.com/nextcloud/bookmarks/assets/11305345/090040ae-1b59-4622-8cd7-3225e76ed098)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 126.0.1.8912

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - HTTP server: Nginx 1.18.0
 - Database: MariaDB 10.3.39
 - PHP version: 8.1.2
 - Nextcloud version: 28.0.6
 - Bookmarks app version: 14.1.2
 - Activated Nextcloud Apps:

    - activity: 2.20.0
    - bookmarks: 14.1.2
    - bruteforcesettings: 2.8.0
    - calendar: 4.7.6
    - circles: 28.0.0
    - cloud_federation_api: 1.11.0
    - comments: 1.18.0
    - contacts: 5.5.3
    - contactsinteraction: 1.9.0
    - cookbook: 0.11.0
    - dashboard: 7.8.0
    - dav: 1.29.1
    - deck: 1.12.2
    - federatedfilesharing: 1.18.0
    - federation: 1.18.0
    - files: 2.0.0
    - files_mindmap: 0.0.30
    - files_pdfviewer: 2.9.0
    - files_reminders: 1.1.0
    - files_sharing: 1.20.0
    - files_trashbin: 1.18.0
    - files_versions: 1.21.0
    - firstrunwizard: 2.17.0
    - logreader: 2.13.0
    - lookup_server_connector: 1.16.0
    - nextcloud_announcements: 1.17.0
    - notes: 4.10.0
    - notifications: 2.16.0
    - oauth2: 1.16.3
    - passman: 2.4.9
    - password_policy: 1.18.0
    - photos: 2.4.0
    - privacy: 1.12.0
    - provisioning_api: 1.18.0
    - recommendations: 2.0.0
    - related_resources: 1.3.0
    - serverinfo: 1.18.0
    - settings: 1.10.1
    - sharebymail: 1.18.0
    - side_menu: 3.12.0
    - spreed: 18.0.8
    - support: 1.11.1
    - survey_client: 1.16.0
    - systemtags: 1.18.0
    - tasks: 0.16.0
    - text: 3.9.1
    - theming: 2.3.0
    - twofactor_backupcodes: 1.17.0
    - updatenotification: 1.18.0
    - user_status: 1.8.1
    - viewer: 2.2.0
    - weather_status: 1.8.0
    - workflowengine: 2.10.0

 - Nextcloud configuration:
    - "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.roselandblue.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.6.1",
        "overwrite.cli.url": "https:\/\/cloud.roselandblue.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "US",
        "maintenance": false,
        "maintenance_window_start": 1,
        "defaultapp": "apporder",
        "theme": "",
        "loglevel": 2,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 28800,
        "session_keepalive": true,
        "auto_logout": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "enforce_theme": "",
        "has_rebuilt_cache": true
 - Nextcloud external user backend: None

**Additional context**
Removing the database, clearing the database of all references to the bookmarks app (using these instructions), and reinstalling the app does not seem to have any effect on the issue.
There are no errors reported relating to this issue in the Nginx logs or the Nextcloud logs.

**Comment by marcelklehr** [comment]
Confirmed. I'll look into this.
