### ISSUE TITLE
Allow emptying Trash Bin and/or selecting multiple bookmarks at a time to delete permanently

### ISSUE THREAD

**Issue by Harmon758** [nextcloud/bookmarks#2183]
Currently, the only way to delete bookmarks permanently from the Trash Bin seems to be one at a time with a confirmation for each one. Allowing emptying the Trash Bin and/or the ability to select multiple bookmarks at a time to delete permanently would eliminate the hassle of permanently deleting lots of bookmarks.

**Comment by marcelklehr** [comment]
> Currently, the only way to delete bookmarks permanently from the Trash Bin seems to be one at a time with a confirmation for each one.

The trashbin also auto-retires items that are older than 2 months, but I agree that an "Empty trashbin" button is a good idea :+1:

**Comment by marcelklehr** [comment]
Latest update has this now :)
