### ISSUE TITLE
Add the names to bookmarks

### ISSUE THREAD

**Issue by oleua** [nextcloud/bookmarks#2198]
By now the bookmarks are represented in the list with the URLs, which is not so convenient to search amongst them, process, especially, if a user bookmarks several pages on the same website with dynamic content. 

Please, add the function to name the bookmarks like the naming in the bookmark panel of an ordinary browser.

**Comment by marcelklehr** [comment]
Hi @ostasevych 
This should already be possible by clicking on the three dot menu of a bookmark and selecting "rename".
