### ISSUE TITLE
set HTML meta keywords as tags and meta description as defaults

### ISSUE THREAD

**Issue by rhinux** [nextcloud/bookmarks#22]
When setting a bookmark with bookmarklet it would be very helpful that the HTML meta values like
<meta name="description" content="Contribute to bookmarks development by creating an account on GitHub." /> as OC description and 
<meta name="keywords" content="owncloud, apps, bookmarks, development, GitHub, language:en" /> as tags
for the formular fields as defaults. 

BTW, I miss that also on firefox or chrome and didn't have found an AddOn that has this feature....

**Comment by blizzz** [comment]
Meta tags were used by spammers or wannabe-SEOs a lot, but reasonable if it implies a limit of allowed terms (5, 7, 10, other?).

**Comment by webmarka** [comment]
Agree it would be nice if the meta description was loaded!

Same for meta keywords (and eventually other kind of meta/header/semantic infos).

Even if it's true meta keywords could be filled with scrap from the page, personally I generally do not bookmark those sites!! 

I would prefer a higher maximum like 20, but also an easy way to remove tags on the fly while bookmarking.

Those params could be in the app options (auto fetch descriptions, tags) or in personal/admin settings if we want to keep app options panel clean.

**Comment by marcelklehr** [comment]
closing per #1160
