### ISSUE TITLE
Can't disable Auto-Arcihve and Auto-backup

### ISSUE THREAD

**Issue by coddec** [nextcloud/bookmarks#2200]
**Describe the bug**
Uncheck Auto-Arcihve and Auto-backup doesn't stay, it always revert back to checked state.
Thus can't disable them.

**To Reproduce**
1. Go to bookmark in nextcloud
2. Click on Settings
3. Click on Auto-Arcihve and Auto-backup to disable them
4. Refresh the browser, they are checked again

**Expected behavior**
Auto-Arcihve and Auto-backup stay unchecked

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, Windows 11, iPhone
 - Browser: Firefox, Chrome, Edge, Safari
 - Version: latest

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7]
 - HTTP server: [e.g. nginx 1.1]
 - Database: [e.g. MySQL 5.3]
 - PHP version: [e.g. v7.2]
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)]
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)]
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
Sorry, latest is not a version.

**Comment by marcelklehr** [comment]
I can reproduce this on master, though.
