### ISSUE TITLE
Nonsensical bookmark count

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/bookmarks#2202]
**Describe the bug**
A bookmark folder has more bookmarks than all the bookmarks on the server

**To Reproduce**
1. Have a number of bookmarks uploaded.
2. Open the bookmarks app.
3. Look at the bookmarks count

**Expected behavior**
All of the bookmarks contained within the bookmarks app should not be more than the total number of bookmarks.

**Screenshots**
![image](https://github.com/user-attachments/assets/12860435-2f86-4ac4-a82a-f90512579d0c)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: Firefox
 - Version: 128.0.3

**Server (please complete the following information):**
 - OS: Ubuntu Linux
 - HTTP server: Apache 2
 - Database: Postgresql
 - PHP version: 8.1
 - Nextcloud version: 29.0.4
 - Bookmarks app version: 14.2.3
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by InfamousUser** [comment]
Even worse now, the inner counter is at 7k, outer at 6.8k.

**Comment by marcelklehr** [comment]
How many duplicates do you have?

**Comment by InfamousUser** [comment]
Oh geez, there might be over 100, I have no clue, must be that. There is absolutely no way to know the counters show different things when they are in the same relative location and they're contents of folders that are one inside another. This should be clarified somehow or, rather, the counts equalized, this is highly unintuitive.

**Comment by marcelklehr** [comment]
Yeah, I think you're right. It's more intuitive to subtract duplicates from the total than to add duplicates to the total to get the real total.

**Comment by marcelklehr** [comment]
Thank you for the feedback! :blue_heart:
