### ISSUE TITLE
floccus unable to synchronize bookmarks: "Malformed UTF-8 characters, possibly incorrectly encoded"

### ISSUE THREAD

**Issue by 2GetApp** [nextcloud/bookmarks#2203]
**Describe the bug**
floccus was not able to synchronize bookmarks (got http 500 error). The server log shows: "Malformed UTF-8 characters, possibly incorrectly encoded". This happened after I upgraded bookmarks app to 14.2.3.
Folder names are redacted from the provided log bellow. I have folder names with special characters (space and ampersand &), as well as Japanese and Chinese characters, but everything worked fine before upgrading.

**To Reproduce**
1. Upgrade bookmarks app to the recent release (14.2.3)
2. Open browser extension floccus and click "Sync now"
3. See error

**Expected behavior**
Bookmarks are supposed to be synchronized successfully.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 127.0.6533.88

**Server (please complete the following information):**
 - OS: Debian 12
 - HTTP server: nginx 1.22.1
 - Database: mariadb 10.6
 - PHP version: 8.2.22
 - Nextcloud version: 29.0.4
 - Bookmarks app version: 14.2.3
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
[05/Aug/2024:05:26:59 +0000] **REDACTED** **REDACTED** **REDACTED** "GET /index.php/apps/bookmarks/public/rest/v2/folder/-1/children?layers=-1 HTTP/2.0" 500 2454 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
{
    "reqId": "QNFyCr0d1CPodMaqDIQQ",
    "level": 3,
    "time": "2024-08-05T05:26:55+00:00",
    "remoteAddr": "**REDACTED**",
    "user": "**REDACTED**",
    "app": "index",
    "method": "GET",
    "url": "/index.php/apps/bookmarks/public/rest/v2/folder/-1/children?layers=-1",
    "message": "Malformed UTF-8 characters, possibly incorrectly encoded",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "version": "29.0.4.1",
    "exception": {
        "Exception": "JsonException",
        "Message": "Malformed UTF-8 characters, possibly incorrectly encoded",
        "Code": 5,
        "Trace": [
            {
                "file": "/var/www/html/lib/public/AppFramework/Http/JSONResponse.php",
                "line": 71,
                "function": "json_encode",
                "args": [
                    [
                        "success",
                        [
                           "**REDACTED**"
                        ]
                    ],
                    4194305
                ]
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
                "line": 183,
                "function": "render",
                "class": "OCP\\AppFramework\\Http\\JSONResponse",
                "type": "->",
                "args": []
            },
            {
                "file": "/var/www/html/lib/private/AppFramework/App.php",
                "line": 184,
                "function": "dispatch",
                "class": "OC\\AppFramework\\Http\\Dispatcher",
                "type": "->",
                "args": [
                    [
                        "OCA\\Bookmarks\\Controller\\FoldersController"
                    ],
                    "getFolderChildren"
                ]
            },
            {
                "file": "/var/www/html/lib/private/Route/Router.php",
                "line": 338,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::",
                "args": [
                    "OCA\\Bookmarks\\Controller\\FoldersController",
                    "getFolderChildren",
                    [
                        "OC\\AppFramework\\DependencyInjection\\DIContainer"
                    ],
                    [
                        "-1",
                        "bookmarks.folders.get_folder_children"
                    ]
                ]
            },
            {
                "file": "/var/www/html/lib/base.php",
                "line": 1050,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->",
                "args": [
                    "/apps/bookmarks/public/rest/v2/folder/-1/children"
                ]
            },
            {
                "file": "/var/www/html/index.php",
                "line": 49,
                "function": "handleRequest",
                "class": "OC",
                "type": "::",
                "args": []
            }
        ],
        "File": "/var/www/html/lib/public/AppFramework/Http/JSONResponse.php",
        "Line": 71,
        "message": "Malformed UTF-8 characters, possibly incorrectly encoded",
        "exception": {},
        "CustomMessage": "Malformed UTF-8 characters, possibly incorrectly encoded"
    }
}
```

**Browser log**
```
2024-08-05T05:26:37.735Z Starting sync process for account redacted@redacted.domain
2024-08-05T05:26:37.739Z QUEUING POST https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/lock
2024-08-05T05:26:37.739Z FETCHING POST https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/lock
2024-08-05T05:26:43.958Z Receiving response for POST https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/lock
2024-08-05T05:26:43.958Z Using "merge default" strategy (no cache available)
2024-08-05T05:26:43.959Z Retrieving local tree
2024-08-05T05:26:43.959Z Retrieving server tree
2024-08-05T05:26:43.959Z QUEUING GET https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/bookmark?page=1&limit=1
2024-08-05T05:26:43.959Z FETCHING GET https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/bookmark?page=1&limit=1
2024-08-05T05:26:50.053Z Receiving response for GET https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/bookmark?page=1&limit=1
2024-08-05T05:26:50.053Z QUEUING GET https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash
2024-08-05T05:26:50.053Z FETCHING GET https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash
2024-08-05T05:26:51.081Z Receiving response for GET https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash
2024-08-05T05:26:51.081Z Filtering out unaccepted local bookmarks
2024-08-05T05:26:51.081Z Filtering out invalid server bookmarks
2024-08-05T05:26:51.081Z Filtering out duplicate bookmarks
2024-08-05T05:26:51.081Z Loading sparse tree as necessary
2024-08-05T05:26:51.081Z Merge strategy: Load complete tree from server
2024-08-05T05:26:51.081Z QUEUING GET https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/folder/-1/children?layers=-1
2024-08-05T05:26:51.081Z FETCHING GET https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/folder/-1/children?layers=-1
2024-08-05T05:26:59.457Z Receiving response for GET https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/folder/-1/children?layers=-1
2024-08-05T05:26:59.458Z Syncing failed with E019: HTTP status 500. Failed GET request. Check your server configuration and log.
2024-08-05T05:26:59.459Z QUEUING DELETE https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/lock
2024-08-05T05:26:59.459Z FETCHING DELETE https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/lock
2024-08-05T05:27:03.726Z Receiving response for DELETE https://redacted.domain/index.php/apps/bookmarks/public/rest/v2/lock
```

**Comment by marcelklehr** [comment]
mmmh, that's strange. Could you perhaps export your bookmarks in the web UI and send the export to me for reproduction?

**Comment by 2GetApp** [comment]
> mmmh, that's strange. Could you perhaps export your bookmarks in the web UI and send the export to me for reproduction?

Sorry to leave out the most important information. My bookmarks contain just too much sensitive information to be shared. I am still trying to find out the relevant bookmark entries that are related to this bug.

After exporting all bookmarks and importing them to a fresh account, synchronization proceeds normally for the new account. So my current guess is that the generated fields (notes, generated previews and fetched html, etc) from some web pages with faulty encoding caused the problem.

**Comment by marcelklehr** [comment]
> After exporting all bookmarks and importing them to a fresh account, synchronization proceeds normally for the new account. So my current guess is that the generated fields (notes, generated previews and fetched html, etc) from some web pages with faulty encoding caused the problem.

That's a good lead!

**Comment by marcelklehr** [comment]
@2GetApp Could you try making these changes locally in your environment to see if they fix your issue? https://github.com/nextcloud/bookmarks/pull/2204/files

**Comment by 2GetApp** [comment]
> @2GetApp Could you try making these changes locally in your environment to see if they fix your issue? https://github.com/nextcloud/bookmarks/pull/2204/files

After some experimentation (edit note with messy contents like è£½ä½, move to trash bin and restore) on suspicious folders and bookmarks, my account is able to synchronize now. But I somehow lost the content that caused the problem because I had to do the experimentation on the original account (new account synchronizes normally). Now I am not able to reproduce the bug myself :(

I have to wait for the content to be regenerated in the new account (I don't know how to generate them immediately). I will try the fix if I reproduce the bug.

**Comment by 2GetApp** [comment]
Still not able to reproduce it. I will just give up and upgrade the bookmarks app.🥲

**Comment by reary1993** [comment]
I ran into a very similar issue:
Desktop:

    OS: Debian 12
    Browser: Firefox
    Version: 115.14.0esr

Server:

    OS: Ubuntu 22.04 arm64
    HTTP server: apache2
    Database: 10.11.8-MariaDB-0ubuntu0.24.04.1
    PHP version: 8.3
    Nextcloud version: 29.0.5
    Bookmarks app version: 14.2.4
	
The error message I get when I try to sync my bookmarks from my browser to Nextcloud is: 
`DbalException An exception occurred while executing a query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xE8\xE2\x80\xA6' for column `nextcloud`.`oc_bookmarks`.`title` at row 1
`
I found out that the the following link is causing the issue: https://github.com/cirosantilli/china-dictatorship#cute-cat-theory-of-digital-activism

I also have another setup of Nextcloud where the only difference is the database being mysql not mariadb. There, the syncing goes without an error.

**Comment by marcelklehr** [comment]
@reary1993 Could you try making these changes locally in your environment to see if they fix your issue? [#2204 (files)](https://github.com/nextcloud/bookmarks/pull/2204/files)

**Comment by reary1993** [comment]
@marcelklehr I can confirm that #2204  fixed my issue. Thanks for your work.

**Comment by marcelklehr** [comment]
Yay!
