### ISSUE TITLE
Composer detects an incorrect PHP version

### ISSUE THREAD

**Issue by d4nyl0** [nextcloud/bookmarks#2221]
**Describe the bug**
In NextCloud > Administration > Logging I see a lot of error messages: "Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.30. at /var/www/vhosts/[removed]/httpdocs/nextcloud/apps/bookmarks/vendor/composer/platform_check.php#24"

**To Reproduce**
1. Go to your avatar image
2. Click on 'Administration settings'
3. On the functionality list on the left scroll down to 'Logging'
4. See error described above

**Expected behavior**
I'm running PHP 8.2.23; a phpinfo.php file shows it correctly. PHP_VERSION_ID on other test script shows 80223 as value.
Disabling "Bookmarks" app on NC the error doesn't occur anymore.
Bookmark app is working, but I get this error message any 5 minutes (cronjob every 5 minutes).

**Screenshots**
N/A

**Desktop (please complete the following information):**
It happens on every client platform: Linux, Android, Windows.

**Server (please complete the following information):**
 - OS: Linux 5.15.83-1-pve # 1 SMP PVE 5.15.83-1 (2022-12-15T00:00Z) x86_64
 - HTTP server: nginx + FPM/FastCGI 
 - Database: 10.4.34-MariaDB - MariaDB Server
 - PHP version: 8.2.23
 - Nextcloud version: Nextcloud Hub 7 (28.0.10)
 - Bookmarks app version: 14.2.5
 - Activated Nextcloud Apps: [void]
 - Nextcloud configuration: [void]
 - Nextcloud external user backend: none

**Comment by marcelklehr** [comment]
>  I get this error message any 5 minutes (cronjob every 5 minutes).

Sounds like your php cli is still using php v8.0. Could you check that?

**Comment by d4nyl0** [comment]
> Sounds like your php cli is still using php v8.0. Could you check that?

Perfect, You are right.
It was a server configuration issue, not a software bug.

Thank You.
