### ISSUE TITLE
 Composer detects an incorrect PHP version

### ISSUE THREAD

**Issue by natrius** [nextcloud/bookmarks#2226]
**Describe the bug**
Basically the same as https://github.com/nextcloud/bookmarks/issues/2221 as far as i could see. 

**To Reproduce**
1. Click on 'Administration settings'
2. On the functionality list on the left scroll down to 'Logging'
3. See error described above

**Expected behavior**
No error

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 11 and Windows 10
 - Browser: Firefox
 - Version: 

**Server (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - HTTP server: 
 - Database: mysql 10.6.18
 - PHP version: 8.2.12
 - Nextcloud version: 28.0.10
 - Bookmarks app version: 14.2.6
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [void]
 - Nextcloud external user backend: none

**Additional context**
In my nginx i have set nextcloud to 8.2 `server unix:/run/php/php8.2-fpm.sock;`
And with `sudo update-alternatives --config php` it is set to 0 - that `/usr/bin/php8.2` as well. 

Do i miss some setting here?

**Comment by marcelklehr** [comment]
Hello @natrius 
Could you post the full log entry, please?

**Comment by natrius** [comment]
Apology, forgot. 

`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.30. at /var/www/nextcloud/apps/bookmarks/vendor/composer/platform_check.php#24 `

**Comment by marcelklehr** [comment]
> You are running 8.0.30

So it seems you are running v8.0 somewhere. Perhaps your cron job is running with phph v8.0?
