### ISSUE TITLE
Request: Option to change the folder where bookmarks are saved in nextcloud

### ISSUE THREAD

**Issue by PennyWafel** [nextcloud/bookmarks#2240]
The bookmarks app saves all bookmarks in nextcloud in **/Bookmarks/**

I would like to change the location to where it saves to a folder of my choosing, so my root nextcloud folder doesn't get cluttered. For example a **hidden folder** (/.Bookmarks/) or **any subfolder** /nextcloudfiles/Bookmarks/)

This option is currently not available, so I am posting here to request this feature to be added to the app :pray:

I envision it would simply be an input field in the admin settings, where you could specify where the bookmarks need to be saved, similar to how other apps implemented it.

**Comment by marcelklehr** [comment]
> This option is currently not available

When Auto-Archiving is enabled the Bookmarks settings in the bookmarks app should allow setting a folder where to save bookmarks archive files.

**Comment by PennyWafel** [comment]
Aha, there it was hidden! Thank you!
