### ISSUE TITLE
can t create new tag correctly

### ISSUE THREAD

**Issue by pra75011** [nextcloud/bookmarks#2244]
**can t create a new tag**
when i create a new tag in 'new tag' / 'nouvelle étiquette' , it s created, if i reload / refresh you can see the tag gone
you can take a look [https://nxt.pra.rip/index.php/s/9Nc9MWWnYdsTZT3]([https://nxt.pra.rip/index.php/s/9Nc9MWWnYdsTZT3)
nxt-bookmark-1.png show the creation
nxt-bookmark-2.png show the tag displayed (just after creation)
nxt-bookmark-3.png show the tag gone (after refresh)
nxt-bookmark-4.png show  tag research doesn t find the tag

i have some bookmark with this tag : nxt-bookmark-5.png

**To Reproduce**
1. nxt-bookmark-1.png show the creation
2. nxt-bookmark-2.png show the tag displayed (just after creation)
3. nxt-bookmark-3.png show the tag gone (after refresh
4. nxt-bookmark-4.png show  tag research doesn t find the tag

**Expected behavior**

**Screenshots**
[https://nxt.pra.rip/index.php/s/9Nc9MWWnYdsTZT3]([https://nxt.pra.rip/index.php/s/9Nc9MWWnYdsTZT3)

**Desktop (please complete the following information):**
 - OS: windows 11, mac 15.1.1, linux debian
 - Browser: chrome, firefox
 - Version: latest

**Server (please complete the following information):**
 - OS: debian 12
 - HTTP server: apache 2.4.62
 - Database:postgresql 14.5
 - PHP version: 8.2
 - Nextcloud version: 30.0.1
 - Bookmarks app version: 14.2.2
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 Enabled:
  - activity: 3.0.0
  - app_api: 4.0.0
  - bookmarks: 15.0.2
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.1
  - checksum: 1.2.5
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadactivity: 1.17.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - qownnotesapi: 24.9.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - richdocuments: 8.5.2
  - richdocumentscode: 24.4.802
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.1
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - encryption: 2.18.0
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0

 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 {
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nxt.pra.rip"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "30.0.1.2",
        "overwrite.cli.url": "https:\/\/nxt.pra.rip",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "force_language": "fr",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "default_phone_region": "FR",
        "diagnostics.logging": true,
        "diagnostics.logging.threshold": 5,
        "log_type": "file",
        "log_type_audit": "file",
        "loglevel_frontend": 2,
        "loglevel": 2,
        "log.backtrace": false,
        "logfile": "\/var\/www\/nxtData\/logs\/nextcloud.log",
        "logfile_audit": "\/var\/www\/nxtData\/logs\/audit.log",
        "log_query": false,
        "log_rotate_size": 104857600,
        "logdateformat": "d F, Y H:i:s",
        "logtimezone": "UTC",
        "tempdirectory": "\/tmpnextcloud",
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable",
        "integrity.check.disabled": false,
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Epub",
            "OC\\Preview\\PDF",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\FB2"
        ],
        "preview_max_x": 1080,
        "preview_max_y": 1920,
        "app_install_overwrite": [
            "files_downloadactivity",
            "admin_notifications",
            "defaultlinkopen",
            "files_reader",
            "apporder"
        ],
        "has_rebuilt_cache": true,
        "theme": "",
        "enforce_theme": "",
        "maintenance": false,
        "maintenance_window_start": "2"
    }
}
 - Nextcloud external user backend:  none

**Additional context**
nxt=# \d oc_bookmarks_tags
                             Table « public.oc_bookmarks_tags »
   Colonne   |          Type          | Collationnement | NULL-able |      Par défaut       
-------------+------------------------+-----------------+-----------+-----------------------
 bookmark_id | bigint                 |                 | not null  | 
 tag         | character varying(255) |                 | not null  | ''::character varying
Index :
    "oc_bookmarks_tags_pkey" PRIMARY KEY, btree (bookmark_id, tag)
    "bookmark_tag" UNIQUE, btree (bookmark_id, tag)

nxt=# \d oc_bookmarks
                                         Table « public.oc_bookmarks »
    Colonne    |         Type          | Collationnement | NULL-able |                Par défaut                
---------------+-----------------------+-----------------+-----------+------------------------------------------
 id            | bigint                |                 | not null  | nextval('oc_bookmarks_id_seq'::regclass)
 url           | text                  |                 | not null  | ''::text
 title         | text                  |                 | not null  | ''::text
 user_id       | character varying(64) |                 | not null  | ''::character varying
 description   | text                  |                 | not null  | ''::text
 added         | integer               |                 |           | 0
 lastmodified  | integer               |                 |           | 0
 clickcount    | integer               |                 | not null  | 0
 last_preview  | integer               |                 |           | 0
 available     | boolean               |                 |           | true
 archived_file | bigint                |                 |           | 
 html_content  | text                  |                 |           | 
 text_content  | text                  |                 |           | 
Index :
    "oc_bookmarks_pkey" PRIMARY KEY, btree (id)
    "bookmarks_clickcount" btree (clickcount)
    "bookmarks_dead" btree (available)
    "bookmarks_deadbyuser" btree (user_id, available)
    "bookmarks_modified" btree (lastmodified)
    "bookmarks_user_clickcount" btree (user_id, clickcount)
    "idx_3ee1cd04a76ed395" btree (user_id)
    "idx_3ee1cd04df091378" btree (last_preview)

nxt=# select * from oc_bookmarks_tags where tag='tickets';
 bookmark_id |   tag   
-------------+---------
         411 | tickets
         412 | tickets
(2 lignes)

nothing pertinent in log

thank you for your help
pra

**Comment by pra75011** [comment]
hello Marcel
hope you are well
thank you for your time

**Comment by pra75011** [comment]
`I'm good, thank you :)
`
super

`
Could it be that these bookmarks are shared with you?`
sure

`Generally, when creating a tag, you need to immediately assign it to a bookmark for it to stay visible across page reloads.`
it was what i done too in db i can see :
nxt=# select * from oc_bookmarks_tags where tag='tickets';
 bookmark_id |   tag   
-------------+---------
         411 | tickets
         412 | tickets
(2 lignes)

but it s not in tag search , not in left in ui : you can see in nxt-bookmark-6.png (new screenshot)
and nothing in tag search : nxt-bookmark-7.png (new screenshot)

is the both tables description i posted are corrects (oc_bookmarks,oc_bookmarks_tags) ?


nxt=# \d oc_bookmarks_tags
Table « public.oc_bookmarks_tags »
Colonne | Type | Collationnement | NULL-able | Par défaut
-------------+------------------------+-----------------+-----------+-----------------------
bookmark_id | bigint | | not null |
tag | character varying(255) | | not null | ''::character varying
Index :
"oc_bookmarks_tags_pkey" PRIMARY KEY, btree (bookmark_id, tag)
"bookmark_tag" UNIQUE, btree (bookmark_id, tag)

nxt=# \d oc_bookmarks
Table « public.oc_bookmarks »
Colonne | Type | Collationnement | NULL-able | Par défaut
---------------+-----------------------+-----------------+-----------+------------------------------------------
id | bigint | | not null | nextval('oc_bookmarks_id_seq'::regclass)
url | text | | not null | ''::text
title | text | | not null | ''::text
user_id | character varying(64) | | not null | ''::character varying
description | text | | not null | ''::text
added | integer | | | 0
lastmodified | integer | | | 0
clickcount | integer | | not null | 0
last_preview | integer | | | 0
available | boolean | | | true
archived_file | bigint | | |
html_content | text | | |
text_content | text | | |
Index :
"oc_bookmarks_pkey" PRIMARY KEY, btree (id)
"bookmarks_clickcount" btree (clickcount)
"bookmarks_dead" btree (available)
"bookmarks_deadbyuser" btree (user_id, available)
"bookmarks_modified" btree (lastmodified)
"bookmarks_user_clickcount" btree (user_id, clickcount)
"idx_3ee1cd04a76ed395" btree (user_id)
"idx_3ee1cd04df091378" btree (last_preview)

**Comment by pra75011** [comment]
hello
yes correct  i can create ticket tag under user_id boulot 
thank you for your help
thus should be grate to share tag too when we share bookmarks ... but how to manage conflicts in the bookmark code
sorry to eaten your time
pra

**Comment by marcelklehr** [comment]
Ah, yes, I'm aware of that ticket. We can close this in favor of that one, then :) 

> sorry to eaten your time

No worries :) I'm glad I could help you! 💙
