### ISSUE TITLE
Search input field loses focus after results are displayed

### ISSUE THREAD

**Issue by miroklarin** [nextcloud/bookmarks#2248]
**Describe the bug**
Search input field loses focus after results are displayed

**To Reproduce**
1. Go to 'Bookmarks'
2. Click on 'Search'
3. Type few letters and stop for about half second
4. You shouldn't be able to continue typing as search input field lost focus

**Expected behavior**
I would expect to continue typing to refine search results

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave
 - Version: Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) unknown (64-bit)

**Server (please complete the following information):**
 - OS: AlmaLinux OS 9.3 AArch64
 - HTTP server: Apache
 - Database: 	PostgreSQL 16.4 on aarch64
 - PHP version: 8.3.13
 - Nextcloud version: Nextcloud Hub 9 - 30.0.2
 - Bookmarks app version: 15.0.3

**Comment by marcelklehr** [comment]
This appears to be fixed in the latest development version. Thank you for your feedback nonetheless 💙
