### ISSUE TITLE
Can not enable network access

### ISSUE THREAD

**Issue by nkk67** [nextcloud/bookmarks#2252]
I just installed bookmarks on my newly created nextcloud instance. Wenn I go to bookmarks i get the following information:
"Network access is disabled by default. Go to administrator settings for the bookmarks app to allow fetching previews and favicons."

Wenn I then go to administration settings of bookmarks and try to activate it, I geht the error "failed to safe settings".

I could not find any information what todo in this case.

**Comment by marcelklehr** [comment]
Hello @nkk67 👋  

Which version of Nextcloud Bookmarks is this?

**Comment by nkk67** [comment]
Version 15.0.4

**Comment by marcelklehr** [comment]
Mmh, I can't reproduce this with v15.0.4, it works for me. Can you check the network request for saving the settings? It should tell why saving failed

**Comment by nkk67** [comment]
I found the problem. It was apache modsecure.  I disabled the id "210730" in the firewall.
This was the error message:
"ModSecurity: Warning. Match of "pmFromFile userdata_wl_extensions" against "TX:extension" required. [file "[/etc/apache2/modsecurity.d/rules/comodo_free/10_HTTP_HTTP.conf] [line "27"] [id "210730"] [rev "5"] [msg "COMODO WAF: URL file extension is restricted by policy|"

Never had this previously.
Thanks for the help

**Comment by marcelklehr** [comment]
Awesome. Have a nice start into 2025!
