### ISSUE TITLE
set Wiki Categories and Language as tags, Wiki Introtext as description

### ISSUE THREAD

**Issue by rhinux** [nextcloud/bookmarks#23]
When adding a Bookmark of a wiki like Wikipedia with the help of the Bookmarklet it would be very helpful if the app could set the Wiki Categories as tags and the Intro Text between Beginning and Table of Contents as description, additionally to HTML meta keywoeds=tags and description (see Issue #22).
- Categories on On https://en.wikipedia.org/wiki/OwnCloud
  - Free software for cloud computing, 
  - Free software programmed in JavaScript,
  - Free software programmed in PHP, 
  - KDE software,
  - KDE stubs
    The hidden categories or known internal like "\* stubs" and like that could be ignored optionally.
- The language is also given by subdomain en.wikipedia.org, so another tag language:en could be set as default.
- Perhaps also all Parent-Categories of the mentioned Cats in hierachical tags (see below)? Like the Category Tree...
- If the wikipedia page has an template it could also be hierachical tags like 
  - KDE:Applications:Internet:owncloud and
  - Cloud computing:Applications:owncloud

**Comment by marcelklehr** [comment]
I think overtaking Wikipedia Categories as Tags is a very specific use case and would be over-engineering. I'm closing this for now.
