### ISSUE TITLE
Issue importing Bookmarks

### ISSUE THREAD

**Issue by DeastinY** [nextcloud/bookmarks#255]
Hi all,
when I enabled the bookmarks app and tried to import bookmarks nothing worked. I figured out a workaround, but want you to know of this issue.

When inspecting the import button you get
`<input type="file" id="bm_import" name="bm_import" size="5">`
and further down the road 
`<button type="button" name="bm_import_btn" id="bm_import_submit">Importieren</button>`

What I needed to do in order for the button to work, was changing 
`$('#bm_import').change(attachSettingEvent);`
in bookmarks.js to use the name of the button:
`$('#bm_import_btn').change(attachSettingEvent);`

Then the import dialogue opens as expected.

I'm pretty unsure about everything js and html, so sorry for not creating a fix (if there is an issue :smile: ). Hope this helps.

Cheers, DeastinY
### Steps to reproduce
1. Open Bookmarks (non jet imported)
2. Open Sidebar
3. Click Import
### Expected behaviour

Import-dialogue should open
### Actual behaviour

Nothing happens
### Server configuration

**Operating system**:  
Debian 3.16.7
**ownCloud version:** (see ownCloud admin page)
9.0.1 (stable)
**Bookmarks version:** (see ownCloud apps page)
0.7
**Updated from an older ownCloud or fresh install:**
Updated
### Client configuration

**Browser:**
Current Firefox/Chrome/Chromium
**Operating system:**
Current Ubuntu

**Comment by blizzz** [comment]
Cannot reproduce on Firefox and a Chromium-based browser, works for me.

**Comment by Tomasu** [comment]
I just installed this app and have the same issue. the button does nothing. I'm running chrome 61 dev.

The button seems to have an id of firstrun_setting, but theres no js in the html that references it, so I presume its in some js file some place. A grep of the bookmarks app folder has no other match to that id, so it seems it just does nothing.

**Comment by marcelklehr** [comment]
So, there's an invisble file input hovering above a dummy button. So, when you click the dummy button you actually click the file input. The app waits for a change event on the file input to fire the upload. (see https://github.com/nextcloud/bookmarks/blob/master/js/bookmarks.js#L11 and https://github.com/nextcloud/bookmarks/blob/master/templates/settings.php#L27). Yet, in my case it didn't fire either (could be some precaution by the chrome devs, regarding file inputs, I'm guessing). So, selecting a file works, but it doesn't trigger an upload, afaict.
