### ISSUE TITLE
Request: Import bookmarks from pinboard.in

### ISSUE THREAD

**Issue by bildlich** [nextcloud/bookmarks#256]
Popular bookmarking service [Pinboard](http://pinboard.in) offers three export options:

![screenshot 2016-05-26 22 27 59](https://cloud.githubusercontent.com/assets/501617/15589029/3c00e64a-2391-11e6-9261-a8e45c37b175.png)

I tried to import each of these into owncloud bookmarks. XML and JSON fail with the app telling me the file formats are not supported. When importing HTML the app tells me the import was successful but no bookmarks show up.

Is there a way to import the booksmarks?
If not I'd like to request the feature.

**Comment by jlepthien** [comment]
Any news on this? This still isn't working...what kind of bookmarks are we supposed to import if it is not the most common formats? Help would be highly appreciated...

**Comment by danj-ca** [comment]
Further, importing the HTML pinboard export in NextCloud 11.0.2 gives me the "unsupported format" message, unlike @bildlich. Either way, it doesn't work. Looking at the file itself, it appears very similar to the Bookmark app's export file, so I imagine it's possible for the import routine to support it...
[pinboard_export.txt](https://github.com/nextcloud/bookmarks/files/927272/pinboard_export.txt)
[bm_20.html.txt](https://github.com/nextcloud/bookmarks/files/927273/bm_20.html.txt)

**Comment by jlepthien** [comment]
Good to know! And btw, wow. Are the developers always that non responsive?

**Comment by danj-ca** [comment]
Heh, I assume that's a rhetorical question. ;) Anyway, I try not to judge too harshly the customer-service practices of people who make useful software for free. The repo is seeing regular commits, so at least this thing *is* being worked on! :)

**Comment by jlepthien** [comment]
I am completely with you, but don't you think that it has been long enogh now? Almost a year without any reaction for a simple problem? You said it yourself, the files look similar. For a guy with programming knowledge this should be easy to fix shouldn't it? And those are the features that make people use your software more. I guess there are way more people wanting to add existing bookmarks instead of starting completely at 0 :)
