### ISSUE TITLE
URL metadata extraction causes an exception and results in a 500 response

### ISSUE THREAD

**Issue by theWatchmen** [nextcloud/bookmarks#257]
### Steps to reproduce
1. Trying to book the following urls causes an error:
2. https://software.intel.com/en-us/android/articles/unity-optimization-guide-for-x86-android-part-1 (certificate issue)
3. http://www.nytimes.com/2016/05/29/opinion/sunday/why-you-will-marry-the-wrong-person.html (Will not follow more than 6 redirects)

The issue seems to be cause by this line:
https://github.com/owncloud/bookmarks/blob/master/controller/rest/bookmarkcontroller.php#L75

While I appreciate getting some data from the url, if there is an issue with the `getURLMetadata` call, the app should skip this part and still save the bookmark.

I am happy to submit a PR if this solution is acceptable.
### Server configuration

**Operating system**: Debian Jessie

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 9.0.2

**Bookmarks version:** 0.7

**Updated from an older ownCloud or fresh install:** fresh install with data migration from latest 8.2

**Where did you install ownCloud from:** apt package manager

**Signing status (ownCloud 9.0 and above):** Seems to be OK

**Comment by c0mputerking** [comment]
I think i am having the same issue with some different urls of course ... also this is showing up in my logs

`Exception: {"Exception":"GuzzleHttp\\Exception\\RequestException","Message":"cURL error 60: SSL certificate problem: unable to get local issuer certificate","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(104): GuzzleHttp\\Exception\\RequestException::wrapException(Object(GuzzleHttp\\Message\\Request), Object(GuzzleHttp\\Ring\\Exception\\RingException))\n#1 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(132): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n#2 \/var\/www\/owncloud\/3rdparty\/react\/promise\/src\/FulfilledPromise.php(25): GuzzleHttp\\RequestFsm->GuzzleHttp\\{closure}(Array)\n#3 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/ringphp\/src\/Future\/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)\n#4 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Message\/FutureResponse.php(43): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\n#5 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/RequestFsm.php(135): GuzzleHttp\\Message\\FutureResponse::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))\n#6 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php(165): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\n#7 \/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php(125): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Message\\Request))\n#8 \/var\/www\/owncloud\/lib\/private\/http\/client\/client.php(129): GuzzleHttp\\Client->get('https:\/\/gate-1....', Array)\n#9 \/var\/www\/owncloud\/apps\/bookmarks\/controller\/lib\/bookmarks.php(556): OC\\Http\\Client\\Client->get('https:\/\/gate-1....')\n#10 \/var\/www\/owncloud\/apps\/bookmarks\/controller\/rest\/bookmarkcontroller.php(75): OCA\\Bookmarks\\Controller\\Lib\\Bookmarks::getURLMetadata('https:\/\/gate-1....')\n#11 [internal function]: OCA\\Bookmarks\\Controller\\Rest\\BookmarkController->newBookmark('https:\/\/gate-1....', Array, '0', '', false, '')\n#12 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#13 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Bookmarks\\Controller\\Rest\\BookmarkController), 'newBookmark')\n#14 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Bookmarks\\Controller\\Rest\\BookmarkController), 'newBookmark')\n#15 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('BookmarkControl...', 'newBookmark', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#16 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#17 \/var\/www\/owncloud\/lib\/private\/route\/router.php(276): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#18 \/var\/www\/owncloud\/lib\/base.php(882): OC\\Route\\Router->match('\/apps\/bookmarks...')\n#19 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#20 {main}","File":"\/var\/www\/owncloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Exception\/RequestException.php","Line":51} `

**Comment by theWatchmen** [comment]
I am going to submit a PR to solve this and another couple of exceptions that prevent saving the bookmarks that display fine on the browser.

**Comment by JSoko** [comment]
Thank You, your PR helps...

https://github.com/theWatchmen/bookmarks/commit/9d3586b247bc088a200032a3409dbba261626c42

**Comment by ToniNichevNBCUNI** [comment]
Same thing here. 
I modified bookmarks/controller/lib/bookmarks.php so instead of throwing exception if http request fails it will at least set up the metadata with the url so the bookmark will work.
This way the url and the title will be set up with the url but at least bookmark app is usable again. 

	public static function getURLMetadata($url) {
		
		$metadata = array();
		$metadata['url'] = $url;
		$page = "";
		
		try {
			$request = \OC::$server->getHTTPClientService()->newClient()->get($url);			
			$page = $request->getBody();
			$contentType = $request->getHeader('Content-Type');
		} catch (\Exception $e) {
			**$metadata = array('url' => $url, 'title' => $url);
			return $metadata;**			
		}
