### ISSUE TITLE
Heads up: Move to Nextcloud in the near future

### ISSUE THREAD

**Issue by blizzz** [nextcloud/bookmarks#259]
Hey, I intend to move this repo over to https://github.com/nextcloud in the next 2 to 12 days.

**Comment by tflidd** [comment]
Will the existing bug reports and pull requests be moved as well?

At the moment, it is quite annoying to apply patches manually after each update, e.g. for bug https://github.com/owncloud/bookmarks/issues/29. If these patches were lost, this would be a pity.

**Comment by JSoko** [comment]
Any news about that?

**Comment by blizzz** [comment]
Well, other than planned, I run out of time, that's why I did not happen yet.

@tflidd thanks for the hint on the issue. I did not see a pull request with a fix for this, did I miss it?

**Comment by tflidd** [comment]
This one? https://github.com/owncloud/bookmarks/pull/159

I must confess, that my last major upgrade was some time back and I don't remember what I exactly applied. There are some overlapping PR, perhaps it was already merged.

Not sure if https://github.com/owncloud/bookmarks/pull/135 was already solved in the meantime by: https://github.com/owncloud/bookmarks/commit/c522347d2cad3bbc49900215bd9f659cb5c9bc99

**Comment by blizzz** [comment]
@tflidd the bookmarkcontroller.php changes in 29 should not be necessary, solved differently meanwhile, although master only yet: https://github.com/owncloud/bookmarks/pull/245. 

The title length adjustments could be interesting, but also if we extent the limit to 4096. Or don't limit it all. Since no limit is documented, we should change the DB accordingly and would not need the adjustments.

**Comment by tflidd** [comment]
> The title length adjustments could be interesting, but also if we extent the limit to 4096. Or don't limit it all. Since no limit is documented, we should change the DB accordingly and would not need the adjustments.

A title must be short. How long is a twitter post, 140, 160 characters? Personally, I would shorten titles to something meaningful, everything else kills the purpose of a title. When importing existing bookmarks, you can't be forced to change all titles. But 4096 should be enough. When you don't put a limit, you can inject huge amount of data into the database.

**Comment by blizzz** [comment]
> A title must be short.

Yes, I totally agree. There's also (at least was) a rough magic SEO-related maximum length that should not be exceeded for proper display in search engine result snippets. Might have been 60 or so, some years back.

> When you don't put a limit, you can inject huge amount of data into the database.

This should not really be a problem, that's its purpose after all. Might have a performance influence on searching the DB against the title.

> When importing existing bookmarks, you can't be forced to change all titles. But 4096 should be enough.

Obviously we should add a check and cut it. If there is a nice way that also works for RTL languages.

Such lengths are a corner case and probably it does not matter much. 4096k should be sufficient, agreed.

**Comment by blizzz** [comment]
did this change in https://github.com/owncloud/bookmarks/pull/266

**Comment by blizzz** [comment]
This repo was now moved to the Nextcloud organization.
