### ISSUE TITLE
Show bookmark description and/or icon in overview

### ISSUE THREAD

**Issue by gsantner** [nextcloud/bookmarks#292]
### Steps to reproduce
1. Go to bookmarks app
2. See the list of bookmarks
### Expected behaviour

I exepct some way to see the description (and/or the favicon of the link).
Currently the description is only visible when editing or creating a bookmark.
At least it should be possible to "Show descriptions" via an setting/option, if this should be not default.
### Actual behaviour

Just a List with link, tags and date. No description. 
Because of the limited space for the url it's not easy (depending on site's link title sometimes impossible) to identify whats behind this link.

![unbenannt](https://cloud.githubusercontent.com/assets/6735650/18783667/771da722-818d-11e6-89dd-6ce99a853710.png)
### Server configuration

**Operating system**: Debian 8

**Web server:** Apache

**Database:** MySql

**PHP version:** 5.6

**ownCloud version:** 9.1.0.16 / NextCloud 10.0

**Bookmarks version:**  0.9.0

**Comment by guitargurus** [comment]
I would like this as well.

**Comment by warenhaus** [comment]
Me too.
