### ISSUE TITLE
Search Bookmarks Capability

### ISSUE THREAD

**Issue by serenity-networks** [nextcloud/bookmarks#297]
This is a requested feature / enhancement  (and my first every request on git)
# **Steps to reproduce:**
1. Go to bookmarks app
2. See hundreds, if not thousands of bookmarks and an overwhelming number of tags
# **Expected Behavior:**

A basic search field in the left sidebar, between the Add Address button and the Filter by tag box.  For those of us with thousands of bookmarks and nearly a hundred tags, having a basic search capability would be an enormously valuable feature.  This should also be very straight forward to implement.
# **Actual behaviour:**

No ability to search bookmarks.  One must first find a relevant tag, then another, and another, which is not easy because they are not listed in alphabetical order (which would make that process easier).  It can take substantial time to find a bookmark because there is no search ability, and tags are not in any proper order on the sidebar.

_To the developers what work on these Apps and the Nextcloud platform, Thank you for your amazing work and dedication._

**Comment by guitargurus** [comment]
Anyone else like to see this functionality?

**Comment by hubitor** [comment]
I've just installed nextcloud and the bookmarks app. As I've seen the bookmarks interface I thought it was broken because there was no search bar. Having all bookmarks at one place and platform independent is great but without being able to search them is no go. It would be OK if one had only few bookmarks but if you have thousands it's a nightmare. So yes it would be great to have at least this functionality.

**Comment by serenity-networks** [comment]
Yea, it's definitely a pain.  Not getting even an acknowledgment from any of the developers either.  Looks like maybe the nextcloud / owncloud split was pointless after all.  The couple months of awesome bug fixes and enhancements was nice while it lasted.  Now it just seems like business as usual.

**Comment by blizzz** [comment]
The search provider needs a fix, probably a rewrite, I believe that's pretty old.

**Comment by marcelklehr** [comment]
It should be relatively easy to implement this, as the API already supports full text bookmarks search. It would be an entirely client-side adventure, if anyone has some time and experience for that :)

**Comment by warenhaus** [comment]
I would like to see this, too.

in the meantime: do you know if the [Nextant ](https://github.com/nextcloud/nextant) app, which claims to search through your Nextcloud bookmarks too, lets us _limit_ its search to bookmarks?

**Comment by marcelklehr** [comment]
@warenhaus Good question, why don't you ask them? :)

**Comment by marcelklehr** [comment]
Check out and feel free to test #347

**Comment by rhonda** [comment]
With respect to choosing multiple tags to narrow down the search: It would be immensly helpful that after adding a tag only the remaining tags are listed that would still produce results. It doesn't make sense to choose tags that would bring the list down to zero. So the remaining tags that are listed should only consist of those that are additional to the ones listed already in the remaining list of bookmarks.

**Comment by marcelklehr** [comment]
@rhonda This "drill down" feature was discussed over here: https://github.com/nextcloud/bookmarks/issues/168#issuecomment-121685377 You may also want to add your thoughts to the pull request for the new ui over here: #424 :)

**Comment by damko** [comment]
FIY meanwhile things get sorted out (thanks @marcelklehr ) you can use my [webextension](https://github.com/damko/freedommarks-browser-webextension) for [Firefox](https://addons.mozilla.org/en-US/firefox/addon/freedommarks/) which provides search in the URL and tags with logic operators.

My extension is far from being perfect but it helps me more than the current Nextcloud interface.

There is also the Chrome version but it don't think it works at the moment.
