### ISSUE TITLE
Allow Sorting

### ISSUE THREAD

**Issue by eMerzh** [nextcloud/bookmarks#3]
Expected behaviour :

The user might be able to sort his bookmarks by name, creation date, tag, ... (see Google Bookmarks or ownCloud Tasks). It would be nice if either a clickable columnheader or a series of buttons allows custum sort order.

ref owncloud/apps#811

**Comment by mase76** [comment]
Maybe an option for sorting in the addon settings would be
a (temporary) solution. I personally would leave it on alphabetical
order by title. I think, people don't change that setting very often,
so such an option would do it.

**Comment by atroxix** [comment]
I propose to add usage/click counter for every bookmark and order by that counter by default. This would basically be a "top/favourite sites" feature. I miss this in basically every bookmark manager app I've found so far.

**Comment by chiotisn** [comment]
I’m a CS student and for this semester I have to work on an open-source project. 
I think that I could work on that issue. Can I give it a try?

**Comment by marcelklehr** [comment]
Hey @chiotisn :)
Awesome! We can always use a helping hand. I'm not sure if it'll be enough work for a whole semester, but then, we never run out of issues ;)
Just FYI, we're currently working on a new UI (see #424), so it would make sense to base your work on that, once the PR is merged :)
And if you have any questions, feel free to email me or create an issue. :)

Cheers!

**Comment by Hylas01** [comment]
I know this is a 5 year old issue, but  I'd like to give a +1 to the idea of better sorting.    I get it that some (most? All but me?) folks want their bookmarks sorted by last use, but I just don't understand that behavior at all.   When I want a bookmark, I think...Oh...I need the bookmark for Google...let me look at the letter G in my long, long list of bookmarkes....  Even categories, although useful have their issues...  Is my google link in "utilities" or "email links" category?    Let's say I realize it's in utilities...well, I've got 75 links in that category..and they are not alphatized...   I need a way to find my google link quickly, not to think when I used it last... it just doesn't make any sense to me.    For the folks that want their bookmarks sorted by last use....why?  how do you find anything?   Am I just wired differently from other folks?   Do I have a paradigm that's just off?    Anyhow, plus one for a different sort ability for this app....it's got so much potential, but drives me crazy as is....

**Comment by marcelklehr** [comment]
@Hylas01 With the new UI you'll at least be able to search for "Google" (theh), but we do have attributes that would make sense to sort by, e.g. sort by most used (@atroxix we already have that built-in, but it's not used anywhere, surprisingly). It shouldn't be too hard to whip a PR for this with the new UI. @chiotisn I would happily give you directions on how to do this, so you could familiarize yourself with the codebase :)

**Comment by chiotisn** [comment]
@marcelklehr Thank you! I have seen the click-counting functionality. Currently, I’m trying to understand how all the components are connected, because I’m a beginner in php and in large applications but I will figure it out.

**Comment by marcelklehr** [comment]
@chiotisn (replying here for posterity ;)) I think a settings entry would be a good idea for this feature as it seems most people will not change this very often and it's not very suitable for an entry in the menu either.

For persisting the setting there's the [config interface](https://doc.owncloud.org/api/classes/OCP.IConfig.html) which is used as can be seen in the calendar app: [[1]](https://github.com/nextcloud/calendar/blob/master/controller/settingscontroller.php) [[2]](https://github.com/nextcloud/calendar/blob/master/appinfo/routes.php#L35-L36)

**Comment by chiotisn** [comment]
To send an Ajax request to the controller I have to create a Settings Model, right? Or I can send it from the settings view?

**Comment by marcelklehr** [comment]
It probably makes sense to have a settings model, yea. Then you can implement a private settings controller on the server that handles CRUD operations on the settings entries. This obviously raises the burden on your part, but makes it easy to add new settings in the future :)

**Comment by chiotisn** [comment]
@marcelklehr thank you for your fast response! I think that the problem was that I had to get familiar with php and Marionette. I hope I will have it ready by Monday!

**Comment by chiotisn** [comment]
I’m currently writing tests to test my code, but I have problem running PHPUnit tests.
I type: 
phpunit -c tests/phpunit.xml —bootstrap vendor/autoload.php
But php can’t find Test\TestCase class in TestCase.php

Is there anything else that I should do before running tests?

**Comment by marcelklehr** [comment]
Patch has landed. Thanks for your good work,  @chiotisn :tada:

**Comment by not2biz** [comment]
Hello,
my wishlist would include (by priority)
- Sorting by Tag (without leading floccus:... if possible)
- Export / Import with Tags
- Favorites (***, **, *)
- Sorting by Favorites
Thank you for your work!
