### ISSUE TITLE
Bug:  Unable to add certains types of bookmarks (https)

### ISSUE THREAD

**Issue by serenity-networks** [nextcloud/bookmarks#301]
1.   Go to any website with a self signed cert, or a cert signed from a private CA that the NextCloud server isn't a part of.
2.  Try to add a bookmark manually via the web interface, or with the shortcut pop-up window.
3.   Watch it do nothing and not add the bookmark.

### Expected behaviour

Bookmark should be added.

### Actual behaviour

Absolutely nothing.  No book mark is added.  The wheels spins on on the window briefly, then stops and nothing happens.

### Server configuration
**Operating system**: 
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6

**NextCloud version:**
10.0.1

**Bookmarks version:**
0.9.0

**Updated from an older ownCloud or fresh install:**
No

**Where did you install NexCloud from:**
From package on NextCloud download page.

**Signing status (ownCloud 9.0 and above):**
Signed

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - bookmarks: 0.9.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - documents: 0.13.1
  - external: true
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_automatedtagging: 1.1.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - news: 9.0.4
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - files_accesscontrol
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml
```
**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (
  'instanceid' => 'oc4gjuyhnjni',
  'passwordsalt' => 'blahblahblahblah',
  'secret' => 'blahblahblahblah',
  'trusted_domains' =>
  array (
    0 => 'mydomain.com',
  ),
  'datadirectory' => '/var/www/ncdata',
  'overwrite.cli.url' => 'http://mydomain.com',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'nextclouddbname',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'ncusername',
  'dbpassword' => 'passwordhere',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'updater.release.channel' => 'stable',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome, IE, Firefox and Opera

**Operating system:**
Windows 10 & Windows 7

#### Web server error log
```
It's empty
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"DCPOlSLgwnhTLuJgk+kv","remoteAddr":"139.162.13.205","app":"core","message":"Trusted domain error. \"139.162.13.$
{"reqId":"jxyrGmUG2LwNf4t\/BUbw","remoteAddr":"69.30.227.222","app":"core","message":"Trusted domain error. \"69.30.227.2$
{"reqId":"IkHeBdrDdmDTOr827x7s","remoteAddr":"74.82.47.5","app":"core","message":"Trusted domain error. \"74.82.47.5\" tr$
{"reqId":"1VTupHYYcO\/NX2Psm4UA","remoteAddr":"23.247.27.43","app":"core","message":"Trusted domain error. \"23.247.27.43$
{"reqId":"+KJ0HJflOW5fOLQvlrei","remoteAddr":"14.134.2.4","app":"core","message":"Trusted domain error. \"14.134.2.4\" tr$
{"reqId":"NhK5vVR\/199PH\/XrUMj0","remoteAddr":"31.192.105.51","app":"core","message":"Trusted domain error. \"31.192.105$
{"reqId":"LQrYq8ozS+KIkThzGPR5","remoteAddr":"23.247.72.74","app":"core","message":"Trusted domain error. \"23.247.72.74\$
{"reqId":"WKgJ2qHtmujmb5oHYlAc","remoteAddr":"195.154.41.132","app":"core","message":"Trusted domain error. \"195.154.41.$
{"reqId":"+7kean\/EwPxSKb9IN2Ql","remoteAddr":"212.129.62.79","app":"core","message":"Trusted domain error. \"212.129.62.$
{"reqId":"VHXgUowom6nEZl4gSjik","remoteAddr":"195.154.41.132","app":"core","message":"Trusted domain error. \"195.154.41.$
{"reqId":"Q+Fcsy0tPIeF6\/UUM3ZB","remoteAddr":"212.129.62.79","app":"core","message":"Trusted domain error. \"212.129.62.$
{"reqId":"ZqPhIikeZooXIOca8+AF","remoteAddr":"31.192.105.51","app":"core","message":"Trusted domain error. \"31.192.105.5$
{"reqId":"NtbBfxJoh5XMivag8qFq","remoteAddr":"183.129.160.229","app":"core","message":"Trusted domain error. \"183.129.16$
{"reqId":"mZmw3sYD2aOlLO0p9q4o","remoteAddr":"69.172.229.225","app":"core","message":"Trusted domain error. \"69.172.229.$
{"reqId":"V7Vye5hf9Y1cg2wLfTn2","remoteAddr":"74.82.47.3","app":"core","message":"Trusted domain error. \"74.82.47.3\" tr$
{"reqId":"JP\/SalXRQ7vxKH8YGIB7","remoteAddr":"31.192.105.51","app":"core","message":"Trusted domain error. \"31.192.105.$
{"reqId":"hkmpyY1Pt3+YKDojbeef","remoteAddr":"31.192.105.51","app":"core","message":"Trusted domain error. \"31.192.105.5$
{"reqId":"ee4WmNFQFXNOSjynvBQy","remoteAddr":"14.134.2.4","app":"core","message":"Trusted domain error. \"14.134.2.4\" tr$
{"reqId":"LU3UGb3p0EiDZ+O4neJx","remoteAddr":"46.4.90.68","app":"core","message":"Trusted domain error. \"46.4.90.68\" tr$
{"reqId":"ovLkcK5b3YbAw1rA7afk","remoteAddr":"162.243.112.22","app":"core","message":"Trusted domain error. \"162.243.112$
{"reqId":"NPyW743uTVRHryeNrOq4","remoteAddr":"31.192.105.51","app":"core","message":"Trusted domain error. \"31.192.105.5$
{"reqId":"Ssud3vL6j8GTh1Zez8\/l","remoteAddr":"46.172.91.20","app":"core","message":"Trusted domain error. \"46.172.91.20$
{"reqId":"rGXo8bHyloKQCX3sFfg1","remoteAddr":"23.247.88.10","app":"core","message":"Trusted domain error. \"23.247.88.10\$
{"reqId":"hqoBjEBNgqv1SKbfxY0W","remoteAddr":"23.247.27.12","app":"core","message":"Trusted domain error. \"23.247.27.12\$
{"reqId":"MjAS1xdXysbvLEE94NAF","remoteAddr":"69.30.226.218","app":"core","message":"Trusted domain error. \"69.30.226.21$
{"reqId":"E9C4pBFPlz21V\/7G4aUN","remoteAddr":"192.187.118.22","app":"core","message":"Trusted domain error. \"192.187.11$
{"reqId":"iS1WeJ2naDMt7sp2thhf","remoteAddr":"31.192.105.51","app":"core","message":"Trusted domain error. \"31.192.105.5$
{"reqId":"mXrbiB0OTRkCgFGe90Pt","remoteAddr":"104.148.75.26","app":"core","message":"Trusted domain error. \"104.148.75.2$
{"reqId":"dlryubPJyof2mrRynbSN","remoteAddr":"74.51.99.248","app":"index","message":"Exception: {\"Exception\":\"Error\",$
{"reqId":"37Pi\/MT32FKswY3hgYbh","remoteAddr":"74.51.99.248","app":"index","message":"Exception: {\"Exception\":\"Error\"$



```

**Comment by sirio81** [comment]
Note: as **work around** I think you can create a bookmark with and address you can reach (i.e. http://www.google.com) then edit the bookmark with the right address, name and description.

**Comment by blizzz** [comment]
For convenience, can you name a domain where that happens?

**Comment by serenity-networks** [comment]
FYI, sirio81's workaround does work, but we definitely should get this properly fixed.

The specific URL i was referring to originally is on a private gov network and it will not be accessible.  I will try to find another website with an expired or self-signed certificate to use as a reference and post it back here.  Any site with a certificate that's expired or self-signed will behave the same.  Stand by.  Thanks

**Comment by blizzz** [comment]
Found https://self-signed.badssl.com/ via https://badssl.com/ and can reproduce.

**Comment by blizzz** [comment]
I have a fix, that would disable certificate checks on a request error (curl). Not sure I overly like it though, but it would be the only way to get it done. Will propose a fix soon.

**Comment by blizzz** [comment]
Please see https://github.com/nextcloud/bookmarks/pull/313

**Comment by blizzz** [comment]
Final fix in https://github.com/nextcloud/bookmarks/pull/316. I reworked the new bookmark logic instead. Also safes couple requests now in almost all cases, so adding bookmarks should be faster now, too.
