### ISSUE TITLE
Open all bookmarks simulatenously in tabs

### ISSUE THREAD

**Issue by sirio81** [nextcloud/bookmarks#303]
Hi, this an enhancement request.

There's an option in firefox bookmarks that I use a lot and I wonder if bookmarks app can handle it:
'open all in tabs'.

### Expected behaviour
Filter bookmarks by tag.
Get a button/link to open all filtered bookmarks in separate browser tabs.
This feature would work very well in combination with this other [enhancement request](https://github.com/nextcloud/bookmarks/issues/302).

### Server configuration
**Operating system**: debian8

**Web server:** apache2

**Database:** mariadb

**PHP version:** 5.6

**nextcloud version:** 10.0.1

**Bookmarks version:** 0.90

**Comment by marcelklehr** [comment]
Closing as WONTFIX, due to browser security constraints preventing the opening of multiple windows at once.
