### ISSUE TITLE
TAG rename doesn't work

### ISSUE THREAD

**Issue by sirio81** [nextcloud/bookmarks#305]
### Steps to reproduce
1. Create a bookmark
2. Add a tag to the bookmark
3. Edit the tag changing its name

### Expected behaviour
The tag get renamed

### Actual behaviour
Nothing happens.
An error is printed in nextcloud.log

### Server configuration
**Operating system**: debian 8

**Web server:** apache2 v2.4

**Database:** mariadb 10.0.28

**PHP version:** 5.6.27

**nextcloud version:** 10.0.1

**Bookmarks version:** 0.9.0

**Updated from an older nextcloud or fresh install:** fresh

**Where did you install ownCloud from:**

I attach nextcloud.log with the specific error.
[nextcloud.log.zip](https://github.com/nextcloud/bookmarks/files/594023/nextcloud.log.zip)

**Comment by sirio81** [comment]
The query giving problem is at line 301

```
// Remove potentialy duplicated tags
$query = $db->prepareQuery("
DELETE FROM `*PREFIX*bookmarks_tags` as `tgs` WHERE `tgs`.`tag` = ?
AND exists( SELECT `id` FROM `*PREFIX*bookmarks` WHERE `user_id` = ?
AND `tgs`.`bookmark_id` = `id`)
AND exists( SELECT `t`.`tag` FROM `*PREFIX*bookmarks_tags` `t` where `t`.`tag` = ?
AND `tgs`.`bookmark_id` = `t`.`bookmark_id`)");
```

I have no idea of the reason it **deletes duplicate tags**.
I'm not able to find the syntax error.

As work around I commented out this query
`// 			$query->execute($params);`
and rename works.

Please, may you tell me why this query is required?
And possibly fix it?

**Comment by marcelklehr** [comment]
I'd say the query in its current form, contrary to the comment, tries to delete all existing instances of the new tag. To make sense, I'd change the params to `$params = [$new, $userid, $old]`.

The syntax error seems to be due to MySQL expecting the "as" clause only in "multi table syntax": https://dev.mysql.com/doc/refman/5.7/en/delete.html

So, the query should look like this:
```
 $query = $db->prepareQuery("
DELETE `tgs`.* FROM `*PREFIX*bookmarks_tags` as `tgs` WHERE `tgs`.`tag` = ?
AND exists( SELECT `id` FROM `*PREFIX*bookmarks` WHERE `user_id` = ?
AND `tgs`.`bookmark_id` = `id`)
AND exists( SELECT `t`.`tag` FROM `*PREFIX*bookmarks_tags` `t` where `t`.`tag` = ?
AND `tgs`.`bookmark_id` = `t`.`bookmark_id`)");
```

**Comment by blizzz** [comment]
Agreed, MySQL does not like the AS.

We should move to the query builder, too, so I am a bit hesitant to just change the query. Either way, a good fix to have for the next release.

**Comment by marcelklehr** [comment]
@blizzz have you begun translating the queries into query builder code, already? I could spare a few hours to help out, if you like.

**Comment by blizzz** [comment]
@marcelklehr not really, i looked a bit into it and also realized there we do some special foo that is not so easily done with the builder. On the plus side, it would work with all databases. However, I did not look far enough to come across the blocker. Then, perhaps there is a way around that (which does not degrade performance, although so far I do not think it was ever really stressed)?

**Comment by marcelklehr** [comment]
Multiple queries wouldn't be ideal of course, but I guess you're right that's possible, too. The trade-off is performance for availability, but as you said, it should be ok.
