### ISSUE TITLE
Enable sharing of bookmarks to other users

### ISSUE THREAD

**Issue by LiamHD** [nextcloud/bookmarks#306]
I would like to share some of my bookmarks to other NextCloud users similar to files.
Is this on your list?

**Comment by TheCelavi** [comment]
We use owncloud in our small organization, bookmarks are used for referencing some interesting websites -> sharing of bookmarks would be AWESOME!!! Really useful!

**Comment by Tech-Port** [comment]
That's exactly what we need!

**Comment by tflidd** [comment]
duplicate of https://github.com/nextcloud/bookmarks/issues/5
