### ISSUE TITLE
could not add bookmark

### ISSUE THREAD

**Issue by jiml8** [nextcloud/bookmarks#307]
I have attempted to add this page: https://www.av-test.org/en/  as a bookmark.  The bookmark app refuses to do so either with the bookmarklet or directly on the bookmark page, giving the error: "could not add bookmark.

Bookmarks seems to work fine on other sites.

### Steps to reproduce
1. navigate to page
2. select "add to owncloud" button
3. 

### Expected behaviour
Tell us what should happen
bookmark should be added

### Actual behaviour
Tell us what happens instead
popup window does not confirm success, and bookmark is not added.

### Server configuration
**Operating system**:
Nas4Free 11.0.0.4 (FreeBSD 11)

**Web server:**
lighttpd 1.4.43

**Database:**
sqlite

**PHP version:**
7.0.13

**ownCloud version:** (see ownCloud admin page)
Nextcloud 10.0.1

**Bookmarks version:** (see ownCloud apps page)
0.90

**Updated from an older ownCloud or fresh install:**
updated from ownCloud 8.2

**Where did you install ownCloud from:**
Nextcloud site

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
The server that hosts nextcloud has no capability to do this.  No browser, no wget, no cURL.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - bookmarks: 0.9.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - music: 0.3.12
  - notifications: 0.3.0
  - ownbackup: 0.3.8
  - ownnote: 1.08
  - password_policy: 1.0.0
  - passwords: 19
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - weather: 1.3.3
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_mv
  - files_retention
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
{
    "system": {
        "instanceid": "oc9yzksqeu34",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "trusted_domains": [
            "trusted1",
            "trusted2"
        ],
        "datadirectory": "\/mnt\/VD01\/owncloud_data",
        "filesystem_check_changes": 1,
        "overwrite.cli.url": "https://my_domain_and_port",
        "dbtype": "sqlite3",
        "version": "9.1.1.5",
        "installed": true,
        "forcessl": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "myusername",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_domain": "mydomain",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "myserver",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "theme": "",
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

yes, local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
webdav

### Client configuration
**Browser:**
Firefox 45.5.0
**Operating system:**
Linux Mageia 5 and Linux Mint 17.3 (tried from both systems)

#### Web server error log
```
Insert your webserver log here
```
Nov 28 13:02:18 jssnas lighttpd[2369]: (server.c.1832) server stopped by UID = 0 PID = 70224 
Nov 28 13:02:18 jssnas lighttpd[2369]: (server.c.1832) server stopped by UID = 0 PID = 70224 
Nov 28 13:02:18 jssnas lighttpd[70271]: (log.c.217) server started 
Nov 28 13:02:18 jssnas lighttpd[70271]: (log.c.217) server started 
Nov 28 13:02:18 jssnas root: websrv service restarted
Nov 28 13:05:10 jssnas root: websrv_htpasswd service executed
Nov 28 13:05:10 jssnas lighttpd[70271]: (server.c.1832) server stopped by UID = 0 PID = 70335 
Nov 28 13:05:10 jssnas lighttpd[70271]: (server.c.1832) server stopped by UID = 0 PID = 70335 
Nov 28 13:05:10 jssnas lighttpd[70382]: (log.c.217) server started 
Nov 28 13:05:10 jssnas lighttpd[70382]: (log.c.217) server started 
Nov 28 13:05:10 jssnas root: websrv service restarted
Nov 28 13:18:25 jssnas root: websrv_htpasswd service executed
Nov 28 13:18:25 jssnas lighttpd[70382]: (server.c.1832) server stopped by UID = 0 PID = 70476 
Nov 28 13:18:25 jssnas lighttpd[70382]: (server.c.1832) server stopped by UID = 0 PID = 70476 
Nov 28 13:18:26 jssnas lighttpd[70525]: (log.c.217) server started 
Nov 28 13:18:26 jssnas lighttpd[70525]: (log.c.217) server started 
Nov 28 13:18:27 jssnas root: websrv service restarted
Nov 28 13:22:23 jssnas root: websrv_htpasswd service executed
Nov 28 13:22:23 jssnas lighttpd[70525]: (server.c.1832) server stopped by UID = 0 PID = 70598 
Nov 28 13:22:23 jssnas lighttpd[70525]: (server.c.1832) server stopped by UID = 0 PID = 70598 
Nov 28 13:22:23 jssnas lighttpd[70645]: (log.c.217) server started 
Nov 28 13:22:23 jssnas lighttpd[70645]: (log.c.217) server started 
Nov 28 13:22:23 jssnas root: websrv service restarted

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
cat nextcloud.log | grep bookmark
{"reqId":"QKj8JIdYbhmx0gdYlMaj","remoteAddr":"192.168.0.2","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-11-28T20:28:54+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/bookmarks\/tag","user":"jiml"}
{"reqId":"7CJpVy\/TjIGovVjIe5Ki","remoteAddr":"192.168.0.2","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-11-28T20:28:54+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/bookmarks\/tag","user":"jiml"}
{"reqId":"FRv60y9bawJbbX9N96pg","remoteAddr":"192.168.0.2","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-11-28T20:55:41+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/bookmarks\/tag","user":"jiml"}
{"reqId":"11FmgOEi86lUwrXXjiNO","remoteAddr":"192.168.0.2","app":"no app in context","message":"CSRF check failed","level":0,"time":"2016-11-28T20:55:41+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/bookmarks\/tag","user":"jiml"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
not available

**Comment by blizzz** [comment]
can  confirm, does  not work for me either

**Comment by blizzz** [comment]
curl request fails, because the server sent less data than expected. A fix is in https://github.com/nextcloud/bookmarks/pull/312
