### ISSUE TITLE
can´t activated in Nextcloud 11 beta 2

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/bookmarks#308]
I updated my Cloud to Nextcloud 11 beta 2. But the Bookmarks App only support lower Version of nextcloud.

### Steps to reproduce
1. running Nextcloud 10
2. make an update to Nextcloud 11 beta 2
3. Bookmarks App can´t activated

### Expected behaviour
![apps_cant_activated](https://cloud.githubusercontent.com/assets/3295104/20744094/2e73fabc-b6da-11e6-863c-9e3769c920be.png)

### Server configuration
**Operating system**:
ubuntu 16.04 LTS

**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
PHP 7.0.13
**nextcloud Version:** 
Nextcloud 11 beta 2
**Bookmarks version:** 
0.9.0
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**
installed with the updater (beta Channel)

**Comment by macmeck** [comment]
You need to fetch the current code from the git repository I guess. appinfo has been updated there but not in the latest release yet.

**Comment by blizzz** [comment]
Yes, this should be solved with https://github.com/nextcloud/bookmarks/pull/304 and the upcoming release
