### ISSUE TITLE
the bookmarklet is still called "add to owncloud" instead of "add to nextcloud"

### ISSUE THREAD

**Issue by doomi** [nextcloud/bookmarks#309]
### Steps to reproduce
1. goto bookmarks
2. click the gear icon in the bottem left corner
3. the button to drag to bookmarks is still called "add to owncloud"

### Expected behaviour
should be called "add to nextcloud"

**Comment by blizzz** [comment]
@doomi cool, thx for your contribution! Instead of hard coding the name, could you get the instance name from the Defaults/Theming? You can retrieve the name from ``\OC::$server->getThemingDefaults()->getName();``.

**Comment by blizzz** [comment]
Fixed by #311 and #314
