### ISSUE TITLE
Import of larger bookmark files fails: "Bookmark URL is missing"

### ISSUE THREAD

**Issue by mkaehlcke** [nextcloud/bookmarks#325]
1. Import a larger bookmark file (>=256 bookmarks) 

### Expected behaviour
All bookmarks in the file are imported

### Actual behaviour
Import fails with message "Failed to import one bookmark, because: Bookmark URL is missing". Bookmarks are partially imported.

### Additional information

The problem seems to occur when the bookmark HTML files contains more than 256 elements. Attached are three files:

- bm_253.txt contains 253 bookmarks and is imported successfully
- bm_254.txt has 254 bookmarks, import fails
- bm_254.txt has 254 bookmarks, another HTML element has been removed. It is successfully imported

[bm_253.txt](https://github.com/nextcloud/bookmarks/files/681334/bm_253.txt)
[bm_254.txt](https://github.com/nextcloud/bookmarks/files/681336/bm_254.txt)
[bm_254a.txt](https://github.com/nextcloud/bookmarks/files/681337/bm_254a.txt)

### Server configuration
**Operating system:**  Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.16

**PHP version:** 7.0.8

**Nextcloud version:** 11.0

**Bookmarks version:** 0.9.1

**Updated from an older Nextcloud or fresh install:** latest Nextcloud appliance (updates itself?)

**Where did you install Nextcloud from:** Nextcloud appliance

**Comment by miniluigi008** [comment]
I also have this issue.

**Comment by marcelklehr** [comment]
Thank you for this awesomely concise bug report! Fixing this was a breeze :) (See #440)
