### ISSUE TITLE
Support app/device password in REST API

### ISSUE THREAD

**Issue by mjanser** [nextcloud/bookmarks#330]
The REST API for getting the bookmarks seems to check the password in way so it doesn't support a generated app/device password. Can this be changed easily? Or can I help implementing this?

### Steps to reproduce
1. Generate new app/device password on your account page
2. call https://example.com/apps/bookmarks/public/rest/v1/bookmark?user=[user]&password=[password] with the above generated password

### Expected behaviour
List of bookmarks is returned.

### Actual behaviour
Error "Wrong password for user [user]" is returned.

**Nextcloud version:** 11.0.0

**Bookmarks version:** 0.9.1

**Comment by blizzz** [comment]
Yes, this will change with the next release. It should work already with current master, although that is not the final state.

**Comment by brantje** [comment]
Why not use basic auth? You can send the following header:
`var encodedLogin = base64.encode('username:password');
`Authorization: Basic encodedLogin`

**Comment by mjanser** [comment]
Because version 0.9.1 of the bookmarks app still needs the `user` and `password` query parameters, otherwise you get `User could not be identified`.

**Comment by brantje** [comment]
I don't see the purpose of adding additional parameters when you can use Basic auth.
That will identify the user also, and it will also work with app passwords.

**Comment by blizzz** [comment]
@brantje Dunno how this ever went in, but as mentioned before, this will be fixed with the upcoming release.

**Comment by marcelklehr** [comment]
It went in originally, I think, to allow passing a username only, to get the public bookmarks of a user.
