### ISSUE TITLE
getUID() throws null pointer exception

### ISSUE THREAD

**Issue by theScrabi** [nextcloud/bookmarks#331]
### Steps to reproduce
1.  Try to add a bookmark in any way

### Expected behaviour
bookmark is added

### Actual behaviour
bookmark is not added

### Server configuration
**Operating system**:
ubuntu 16.04.1
**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
5.7.17-0ubuntu0.16.04.1
**PHP version:**
PHP 7.0.13-0ubuntu0.16.04.1
**Nextcloud version:** (see Nextcloud admin page)
ownCloud 9.1.3 (stable)
**Bookmarks version:** (see Nextcloud apps page)
v0.9.1

**Log:
```
{
   "Exception":"Error",
   "Message":"Call to a member function getUID() on null",
   "Code":0,
   "Trace":"#0 \/var\/www\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(113): OCA\\Bookmarks\\AppInfo\\Application->OCA\\Bookmarks\\AppInfo\\{closure}(Object(OC\\AppFramework\\DependencyInjection\\DIContainer))\n#1 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(102): Pimple\\Container->offsetGet('WebViewControll...')\n#2 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(82): OC\\AppFramework\\Utility\\SimpleContainer->query('WebViewControll...')\n#3 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('WebViewControll...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#4 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#5 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#6 \/var\/www\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/apps\/bookmarks...')\n#7 \/var\/www\/owncloud\/index.php(54): OC::handleRequest()\n#8 {main}",
   "File":"\/var\/www\/owncloud\/apps\/bookmarks\/appinfo\/application.php",
   "Line":41
}
```

**Stacktrace:
```

#0 /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OCA\Bookmarks\AppInfo\Application->OCA\Bookmarks\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer)) 
#1 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('WebViewControll...') 
#2 /var/www/owncloud/lib/private/AppFramework/App.php(82): OC\AppFramework\Utility\SimpleContainer->query('WebViewControll...') 
#3 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('WebViewControll...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array) 
#4 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array) 
#5 /var/www/owncloud/lib/private/Route/Router.php(280): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array) 
#6 /var/www/owncloud/lib/base.php(891): OC\Route\Router->match('/apps/bookmarks...') 
#7 /var/www/owncloud/index.php(54): OC::handleRequest() 
#8 {main}
```

**Comment by blizzz** [comment]
Can you elaborate on you reproduction steps? I could not find a way that does not work for me, yet.

**Comment by theScrabi** [comment]
That is everything I can tell you. I dont know when or why it happened that it failes now.

However it might be the database. Im tryingto delete everything regarding owncloud bookmarks maybe it helps.

**Comment by theScrabi** [comment]
All right I found out that it only happens with certain urls, but so far I could not determine which kind of url fail.

**Comment by theScrabi** [comment]
I'm stupid ... with the current version this does not appear to happen, but that strange versioning with 0.9.x and 9.x mad owncloud still use 0.9.0 and that version seems broken.

**Comment by blizzz** [comment]
did you try to upgrade bookmarks on OC or is there a blocker?

**Comment by theScrabi** [comment]
Upgrade only works if you install the app via git. The app from ownclouds native app store fails because of the versioning.

**Comment by blizzz** [comment]
> The app from ownclouds native app store fails because of the versioning.

Really? Max version is 9.2 (https://github.com/nextcloud/bookmarks/blob/master/appinfo/info.xml#L19) so it should work against 9.1.x?
