### ISSUE TITLE
Need more advanced rest API

### ISSUE THREAD

**Issue by theScrabi** [nextcloud/bookmarks#333]
Hello,

I'm trying to update [Nethars ownCloud bookmark app for android](https://github.com/Nethar/owncloud-bookmarks), and make it using the REST api. However there are some things I miss at the Api to make it work proper:

Nice to have:
- [ ] ask for a list of available tags
- [x] add new bookmarks via REST
- [ ] when asked for bookmarks send the tags for each bookmark
- [ ] proper API documentation

would be Nice to have :)
rgds Schabi

**Comment by marcelklehr** [comment]
In the next version there'll be a public REST API with CRUD support  for bookmarks, which also sends all tags for each bookmark. It's [in the making](322), but there'll probably be endpoints for managing tags as well.

**Comment by theScrabi** [comment]
All right I'll take everything back, and let you guys do your job :)
