### ISSUE TITLE
No results from this query

### ISSUE THREAD

**Issue by LennartRoeder** [nextcloud/bookmarks#340]
### Steps to reproduce
1. Call "https://mydomain.de/nextcloud/index.php/apps/bookmarks/public/rest/v1/bookmark?user=user&password=password"

### Expected behaviour
Response with bookmarks

### Actual behaviour
{"status":"error","message":"No results from this query"}

### Server configuration
**Operating system**:
Ubuntu Server 16.10 armhf

**Web server:**
Apache

**Database:**
Mariadb

**PHP version:**
7

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Bookmarks version:** (see Nextcloud apps page)
0.9.1

**Updated from an older Nextcloud or fresh install:**
updated

**Where did you install Nextcloud from:**
manually.

**Signing status (Nextcloud 9 and above):**
all good

```
No errors have been found.
```

**active apps**
```
- activity: 2.4.1
  - bookmarks: 0.9.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
```

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "ocakdi63wgy7",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "myurl.de"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/myurl.de\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nc",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 2
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome and FF

**Operating system:**
OSX el capitan

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Karlsoost** [comment]
Same story here. Nextcoud server log is showing:
`	Error: Call to a member function getUID() on null
/var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 113: OCA\Bookmarks\AppInfo\Application->OCA\Bookmarks\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
/var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 115: Pimple\Container->offsetGet('PublicControlle...')
/var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 544: OC\AppFramework\Utility\SimpleContainer->query('PublicControlle...')
/var/www/owncloud/lib/private/AppFramework/App.php - line 91: OC\AppFramework\DependencyInjection\DIContainer->query('PublicControlle...')
/var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('PublicControlle...', 'returnAsJson', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/owncloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/owncloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/bookmarks...')
/var/www/owncloud/index.php - line 40: OC handleRequest()
{main}` 

Any help is appreciated.

Regards,
Heiko

**Comment by Karlsoost** [comment]
Is anyone looking at this at all!?

Thank you,
Heiko

**Comment by blizzz** [comment]
@Karlsoost i get the notification, but don't have time yet to look into it

**Comment by marcelklehr** [comment]
There will be a new REST API in the next release! Stay tuned :)

**Comment by Karlsoost** [comment]
Sounds promising...

**Comment by marcelklehr** [comment]
:tada:
