### ISSUE TITLE
Bookmarks 0.9.1 throws error if used in Owncloud 9.1.4 because of missing theming support

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/bookmarks#341]
Hello,

Bookmarks 0.9.1 only shows a blank page if I try to access the app in Owncloud 9.1.4. Here is the error message in the log:

`
"Call to undefined method OC\\Server::getThemingDefaults() at \/var\/www\/owncloud\/apps\/bookmarks\/templates\/main.php#22
`

I fixed it by editing the bookmarklet() function in /templates/main.php:

```
function bookmarklet($bookmarkleturl) {
$l = \OC::$server->getL10N('bookmarks');
# $defaults = \OC::$server->getThemingDefaults();
$blet = "javascript:(function(){var a=window,b=document,c=encodeURIComponent,e=c(document.title),d=a.open('";
$blet .= $bookmarkleturl;
$blet .= "?output=popup&url='+c(b.location)+'&title='+e,'bkmk_popup','left='+((a.screenX||a.screenLeft)+10)+',top='+((a.screenY||a.screenTop)+10)+',height=400px,width=550px,resizable=1,alwaysRaised=1');a.setTimeout(function(){d.focus()},300);})();";
$help_msg = $l->t('Drag this to your browser bookmarks and click it, when you want to bookmark a webpage quickly:');
$output = '<div id="bookmarklet_hint" class="bkm_hint">' . $help_msg . '</div><a class="button bookmarklet" href="' . $blet . '"> Add to Owncloud</a>';
return $output;
}
?>
```

**Comment by blizzz** [comment]
Thanks for your report! 

As far as I know there is no bookmarks dev using ownCloud. So far we were driving the usual tests against it and see how it went.  Apparently this part was uncovered.

As such pull requests fixing this while staying compatible are welcome.
