### ISSUE TITLE
getUID error on null    / Folders

### ISSUE THREAD

**Issue by JudaB** [nextcloud/bookmarks#344]
I am getting the following error ,
when using code mirror from the repo

[Wed Apr 19 00:21:22.119925 2017] [:error] [pid 4838] [client 192.168.x.xx:xxxx] PHP Fatal error:  Call to a member function getUID() on null in /xxxxxxxxxxxxxxxxxxxxxxx/www/html/nextcloud/apps/bookmarks/appinfo/application.php on line 78

on other hand when using bookmark downloaded/enable via App menu it works,

p.s does Bookmark support Folders because i was unable to create folder

**Comment by blizzz** [comment]
You're attempting to run master? Against which nextcloud version?

> p.s does Bookmark support Folders because i was unable to create folder

Nope, we think tags are enough to sort bookmarks.

**Comment by marcelklehr** [comment]
Closing due to lack of response. I'm happy to reopen, if you can provide more details :)
