### ISSUE TITLE
NC 12 support?

### ISSUE THREAD

**Issue by rseek** [nextcloud/bookmarks#345]
### Steps to reproduce
1. upgrade to NC12
2.
3.

### Expected behaviour
Bookmarks app is enabled

### Actual behaviour
Bookmarks app is disabled and can't be enabled

**Comment by blizzz** [comment]
We ought to do the next release quickly. 

As a workaround, you could try to use the current release by increasing the max version in the info.xml of the current version to 12, but I am not entirely sure this succeeds.

**Comment by Hanzei** [comment]
Fixed  with bfb2002

**Comment by blizzz** [comment]
Yes, and the new version should be available from the app store.
