### ISSUE TITLE
Server error on activating bookmark app in Nextcloud

### ISSUE THREAD

**Issue by warenhaus** [nextcloud/bookmarks#346]
Upon a fresh install of Nextcloud 11 (with some other apps already activated), I receive the following error message:

Server error response [url] https://ovin.schiwon.me/index.php/s/iBUBG7ZbIUbiudn/download [status code] 500 [reason phrase] Internal Server Error

**Comment by warenhaus** [comment]
[works now](https://help.nextcloud.com/t/bookmark-app-download-server-error/12169/2), thanks.

**Comment by blizzz** [comment]
thx for notifying :)
