### ISSUE TITLE
Collaborate with GNOME browser for bookmark sync

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/bookmarks#35]
At GUADEC (the GNOME conference) I talked to @csaavedra about syncing the bookmarks with GNOME Web / Epiphany.

Since ownCloud is already in GNOME Online Accounts with Files, Calendar and Contacts, it would be cool to have »Bookmarks« added there too. @csaavedra can you talk to Debarshi/rishi about that? What do you need from us?

@eMerzh do we expose an API or a protocol at the moment? There’s some standard format for bookmarks, right?

**Comment by jancborchardt** [comment]
@blizzz maybe @MorrisJobke and I should also talk to some GNOME devs about this at GUADEC? :)

**Comment by blizzz** [comment]
Sure, cannot hurt :)

**Comment by jancborchardt** [comment]
@blizzz did you research anything on standard formats? What does Firefox use, what does Chrome use etc?

**Comment by blizzz** [comment]
@jancborchardt not me, @rakshazi intends to dive into sync API, that might be related to a certain degree.

**Comment by strugee** [comment]
> @blizzz did you research anything on standard formats? What does Firefox use, what does Chrome use etc?

Are you talking about bookmark synchronization? If so, both Firefox and Chrome use their own custom protocols to talk with Firefox Sync and Google, respectively.

**Comment by rakshazi** [comment]
@jancborchardt @blizzz @strugee 
I want to create custom API interface for OwnCloud Bookmarks and extension for Google Chrome (based on chrome.bookmarks API) and I don't know anything about Firefox API.

PS: What protocol/standard used in GNOME? Please, give some links to documentation.

**Comment by joeplus** [comment]
I think here is the resource descibing how bookmarks are manipulated in [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Manipulating_bookmarks_using_Places)!

**Comment by rakshazi** [comment]
Thank you very.much! I'll study this later

17 августа 2015 г. 19:33:48 EEST, joeplus <notifications@github.com> пишет:
>I think here is the resource descibing how bookmarks are manipulated in
>[Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places/Manipulating_bookmarks_using_Places)!
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/bookmarks/issues/35#issuecomment-131882480

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by nsrosenqvist** [comment]
I would love to have it sync with Firefox Sync as well. There used to be a plugin for syncing with Firefox Sync but I don't believe it's maintained anymore. If that could be integrated somehow in this project it would be awesome.

**Comment by webmarka** [comment]
+1 for Firefox Sync feature!

**Comment by tanty** [comment]
GNOME Buzgilla bug https://bugzilla.gnome.org/show_bug.cgi?id=708081 was closed WONTFIX but, at the same time, GNOME Web added recently support for Firefox Sync. See: https://bugzilla.gnome.org/show_bug.cgi?id=665633

I suppose this should be the way to go, although, probably, some more work would need to be done in order to integrate with GNOME Web through Firefox Sync. Maybe it would be sufficient so it can be configured in NextCloud Bookmarks to use the same bookmarks repository than GNOME Web inside Firefox Sync (just guessing, since I'm not really an expert in this API).

**Comment by marcelklehr** [comment]
Apparently, the collaboration wasn't successful, so I'll close this issue. Feel free to open an issue for firefox sync support (if there isn't one already).
