### ISSUE TITLE
POST new bookmarks via REST seem to ignore item[] parameter

### ISSUE THREAD

**Issue by theScrabi** [nextcloud/bookmarks#353]
Hi,

everytime I try to POST a url with a `item[]` parameter I get a responce that says `"tags":false`, just like if I don't set this parameter. So what am I doing wrong?

### Example
`http://msi-7816:8080/index.php/apps/bookmarks/public/rest/v2/bookmark?url=https://schabi.org&item[]=bla`

### Response
```
{
  "item": {
    "id": "6",
    "url": "https://schabi.org",
    "title": "schabi.org",
    "user_id": "admin",
    "description": "",
    "public": "1",
    "added": "1494792351",
    "lastmodified": "1494793035",
    "clickcount": "0",
    "tags": false
  },
  "status": "success"
}
```

**Comment by marcelklehr** [comment]
Ah, that's a documentation bug. Apparently, it's supposed to be `item[tags][]=foo&item[tags][]=bar`, would have been better to call this `tags[]` directly.
