### ISSUE TITLE
REST: Not able to edit bookmarks

### ISSUE THREAD

**Issue by theScrabi** [nextcloud/bookmarks#359]
I'm trying:

PUT `http://msi-7816:8080/index.php/apps/bookmarks/public/rest/v2/bookmark/15?titel=asdf`

I'm getting a `400`

Same with

PUT `http://msi-7816:8080/index.php/apps/bookmarks/public/rest/v2/bookmark/15?record_id=15&titel=asdf`

**Comment by marcelklehr** [comment]
Might be because `title` is misspelled, could be something else, though :/

**Comment by marcelklehr** [comment]
Ah, no. Another mistake in the docs: The params are not optional, you always need to supply all of them.
