### ISSUE TITLE
Setting up dev env

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#365]
I've finally come around to setting up a dev env and stop developing on travis :P

Problem is: I'm hitting the following error running the tests with latest master of nextcloud/server and nextcloud/bookmarks and sqlite:

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_bookmarks" ("url", "title", "user_id", "public", "added", "lastmodified", "description") VALUES(http://www.google.com, Heise, testuser, 0, strftime('%s','now'), strftime('%s','now'), PrivatTag)':

Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000]: General error: 1 unrecognized token: ":"
```

Any ideas?

**Comment by blizzz** [comment]
just looking on the reported  query the values are not encapsulated within quotation marks

**Comment by marcelklehr** [comment]
Yeah, I noticed. What causes this, though?
