### ISSUE TITLE
REST: Bookmark with no tags contains empty tag

### ISSUE THREAD

**Issue by theScrabi** [nextcloud/bookmarks#371]
Bookmarks that do not have a tag now return an empty "" tag when trying to tags:
```
"tags": [
  ""
]
```

### Call
GET `http://msi-7816:8080/index.php/apps/bookmarks/public/rest/v2/bookmark`

### Replay
```
{
  "data": [
    {
      "id": "17",
      "url": "http://asdf.com",
      "title": "asdf",
      "user_id": "admin",
      "description": "",
      "public": "0",
      "added": "1495714580",
      "lastmodified": "1495714580",
      "clickcount": "0",
      "tags": [
        ""
      ]
    }
  ]
}
```

**Comment by blizzz** [comment]
version 0.10.0 or  master?

**Comment by theScrabi** [comment]
master

**Comment by theScrabi** [comment]
Will these improvements be marked as API v3 after the next release?

**Comment by blizzz** [comment]
nope, that does not bring a new api version.

**Comment by theScrabi** [comment]
You know if you change an api, and not mark it as a new version, I'll have a bad time writing a client for this app. Because the client than has to be aware of all the differences. 

Is there a way to ask the owncloud/nextcloud installation with which version I'm dealing with?

**Comment by blizzz** [comment]
> Please stabilize v2 until the next release.

that's what's happening :)

> Is there a way to ask the owncloud/nextcloud installation with which version I'm dealing with?

The bookmarks version not, iirc, the server version you can get from /status.php.

**Comment by theScrabi** [comment]
All right thanks.
