### ISSUE TITLE
\"Could not resolve OCA\\\\Bookmarks\\\\Controller\\\\PublicController! Class OCA\\\\Bookmarks\\\\Controller\\\\PublicController does not exist\"

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#373]
After updating to Nextcloud 12 and bookmarks 0.10.0. Request:

domain/nextcloud/index.php/apps/bookmarks/public/rest/v1/bookmark?select=tags&user=user&password=password

returns error 500
log shows:
{"reqId":"iXP2tgDHAXftcVtkyvpd","level":3,"time":"2017-05-25T16:27:53+00:00","remoteAddr":"31.30.118.115","user":"--","app":"index","method":"GET","url":"\/nextcloud\/index.php\/apps\/bookmarks\/pub
lic\/rest\/v1\/bookmark?select=tags&user=user&password=password","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\Bookmark
s\\\\Controller\\\\PublicController! Class OCA\\\\Bookmarks\\\\Controller\\\\PublicController does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Ap
pFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Bookmarks\\\\\\\\C...')\\n#1 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/
private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Bookmarks\\\\\\\\C...')\\n#2 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFr
amework\\\/DependencyInjection\\\/DIContainer.php(410): OC\\\\ServerContainer->query('OCA\\\\\\\\Bookmarks\\\\\\\\C...')\\n#3 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\
\\/App.php(101): OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer->query('OCA\\\\\\\\Bookmarks\\\\\\\\C...')\\n#4 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/R
outing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('PublicControlle...', 'returnAsJson', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 [internal fu
nction]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\Ap
pFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#7 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/bookmarks...')\\n#8 \\\/srv\\\/www
\\\/htdocs\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"L
ine\":102}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.29"}

Any idea what can be wrong?

**Comment by marcelklehr** [comment]
Thank you for reporting this. This is a bug.
The commit responsible is: db8331b491c2a82550066

**Comment by blizzz** [comment]
hm, what is using the old ``domain/nextcloud/index.php/apps/bookmarks/public/rest/v1/bookmark?select=tags&user=user&password=password`` endpoint? Would be good to get it to use the new API. Transporting the password as GET parameter is not so nice after all.
