### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by kees-closed** [nextcloud/bookmarks#375]
Hi,

Sorry, this is not a bug report or something like that. Just a question, I couldn't find any other place to ask this. How can people use this app? There is no way to sync the bookmarks directly into a browser? So how should people use this app? Go to Nextcloud in your browser to find your bookmarks?

**Comment by marcelklehr** [comment]
Hey!
My personal vision is that people are able to sync their browsers with nextcloud. My current attempt is https://github.com/marcelklehr/floccus ;)

**Comment by blizzz** [comment]
That said, Bookmarks gives you a WebUI to manage your bookmarks and a bookmarklet for comfortably adding bookmarks from webpages. Browser extensions like @marcelklehr s can work on top of it :)

**Comment by e-alfred** [comment]
Well, mobile apps (with offline storage) would be a great addition. Hopefully somebody can make https://github.com/Nethar/owncloud-bookmarks run again one day.

**Comment by pixelrust** [comment]
Yes, I actually go to Nextcloud in my browser to find my bookmarks.

I privately manage my own Nextcloud installation and I value the privacy aspect when it comes to private bookmarks.

In my personal case, I don't feel the need for browser sync: I often need to _add_ new bookmarks from multiple locations, but I only rarely need to _access_ them, and only from a specific location.

**Comment by sprnza** [comment]
@pixelrust but there is no even simple search. How do you find your bookmarks?

**Comment by pixelrust** [comment]
@sprnza I always tag them, and their number is relatively small, say 20 per tag. I understand this doesn't scale and doesn't necessarily work for everybody :)

**Comment by marcelklehr** [comment]
There will be search. I promise ;)

**Comment by marcelklehr** [comment]
Closing this for now. Thanks for all your feedback, folks! :)
