### ISSUE TITLE
OwnCloud support?

### ISSUE THREAD

**Issue by ace02000** [nextcloud/bookmarks#378]
Hi,
short question regarding compatibility ... is the bookmark 0.10 app also compatible with owncloud or only with nextcloud?

**Comment by blizzz** [comment]
@ace02000 It's not compatible. We have bug reports about OC, but no developer working on it. We had failing auto-tests, that were not obvious to fix either. Thus, we dropped support for OC with bookmarks 0.10 (also see changelog https://github.com/nextcloud/bookmarks/releases/tag/v0.10.0)

**Comment by ace02000** [comment]
thanks
