### ISSUE TITLE
[Feature request] Brower extension

### ISSUE THREAD

**Issue by brantje** [nextcloud/bookmarks#379]
Hi there!
I was wondering, is there any interest in having a browser extension for this app?
In my opinion it should sync the browser bookmarks with the bookmarks in Nextcloud.
I have made some browser extensions, it's not that hard once you understand how it works.
If you like i can help and guide you along the process.

**Comment by blizzz** [comment]
Did you take a look at floccus? https://github.com/marcelklehr/floccus

**Comment by e-alfred** [comment]
Hello,

how about listing useful addons on the Github page? Floccus and the NCBookmarks Android app would be very useful tools for use with the Bookmarks app. The developer of the NCBookmarks app also now made it run with the 0.10 release and the new API:

https://github.com/lenchan139/NCBookmark

**Comment by marcelklehr** [comment]
Good idea! Pull requests welcome :)

**Comment by brantje** [comment]
@blizzz I did, but it does not support folder structure, which i really need with the amount of bookmarks i have.

**Comment by e-alfred** [comment]
@marcelklehr Okay, done here:

https://github.com/nextcloud/bookmarks/pull/385

**Comment by marcelklehr** [comment]
@brantje see #13
