### ISSUE TITLE
[Feature Request] iOS Bookmarks app

### ISSUE THREAD

**Issue by blacs30** [nextcloud/bookmarks#380]
# iOS Bookmarks app
It would be great to have an app which could kinda replace the Safari read later and favorites and sync with the nextcloud bookmarks.

Is an iOS app in planning or is it out of scope completely for the moment?

Thanks a lot for all your effort.

**Comment by blizzz** [comment]
Out of scope. Would be a different project/repo since this is purely the Nextcloud app. So, in general useful and desirable, but then "someone" needs to create a dedicated project.

**Comment by sunjam** [comment]
iOS port here: https://github.com/lenchan139/NCBookmark_iOS

**Comment by marcelklehr** [comment]
Cool, when it's ready we'll happily add it to the companion apps :)
