### ISSUE TITLE
Possible circular reference causing import failure

### ISSUE THREAD

**Issue by dominic-p** [nextcloud/bookmarks#382]
### Steps to reproduce
1. Install the app
2. Attempt to import a file using the import button at the bottom left. I used an export file from Google Bookmarks, but I observed the same behavior with an export from Google Chrome as well.

### Expected behavior
The bookmarks should be imported.

### Actual behavior
The bookmarks are not imported. A message pops up saying "Bookmarks imported successfully." but no bookmarks are added.

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 12.0.0

**Bookmarks version:** (see Nextcloud apps page) 0.10.0

**Updated from an older Nextcloud or fresh install:** No

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No

### Client configuration
**Browser:** Firefox 54.0

**Operating system:** Windows 10

#### Web server error log
```
2017/06/20 11:57:11 [error] 23813#23813: *1206 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 262144 bytes) in /var/www/nextcloud/apps/bookmarks/controller/rest/internalbookmarkcontroller.php on line 141
```

As you can see from the server logs, PHP-FPM is running out of memory. The referenced [line of code](https://github.com/nextcloud/bookmarks/blob/b9c810cfb4125ab90f7a56936938cb48e6527811/controller/rest/internalbookmarkcontroller.php#L140) looks suspiciously like a circular reference. That would definitely explain the memory issue and the error.

**Comment by marcelklehr** [comment]
Oh! Nice catch!
