### ISSUE TITLE
Feature Request: Allow display of un-tagged bookmarks only

### ISSUE THREAD

**Issue by andreas-h** [nextcloud/bookmarks#384]
It would be great if the tags list in the filter bar to the left of the screen were auto-populated with an entry *untagged* (call it what you like), which filters for all entries which don't have any tag.

My use case is that when adding a bookmark I sometimes don't want to assign any tags (think fire-and-forget) but rather do this later. For those cases, it would be great to be able to find these entries quickly.

**Comment by marcelklehr** [comment]
I think this is mostly covered by #168, so even though this is important, I'll close this as a duplicate. :)
