### ISSUE TITLE
Import fails on nextcloud 12.0.0 with out of memory

### ISSUE THREAD

**Issue by cangeeq** [nextcloud/bookmarks#388]
### Steps to reproduce
1. From a fresh install of nextcloud 12.0.0, enable bookmarks
2. Add a bookmark to https://www.google.ca
3. Export to bad.html: [bad.zip](https://github.com/nextcloud/bookmarks/files/1115773/bad.zip)
4. Delete the bookmark
5. Try to import bad.

### Expected behaviour
Successful import

### Actual behaviour
"Import error" in app UI, nothing in nextcloud logs, in apache logs:

```
[Fri Jun 30 11:40:37.203058 2017] [:error] [pid 16094] [client 192.168.2.1:54222] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /var/www/nextcloud/apps/bookmarks/controller/rest/internalbookmarkcontroller.php on line 141
[Fri Jun 30 11:40:37.203207 2017] [:error] [pid 16094] [client 192.168.2.1:54222] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
```

Doesn't look like the other import issues that I saw.  I suspect this is something off with my config and not a general issue or there would already be one. :-)

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** SQLite

**PHP version:** 7.0

**Nextcloud version:** 12.0.0

**Bookmarks version:** 0.10.0

**Updated from an older Nextcloud or fresh install:** fresh

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "ocnm6jqv1o0s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "web.weirdways.com"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/web.weirdways.com\/cloud",
        "dbtype": "sqlite3",
        "version": "12.0.0.29",
        "installed": true,
        "mail_from_address": "webmaster",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "weirdways.com"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7

#### Web server error log
```
[Fri Jun 30 11:40:37.203058 2017] [:error] [pid 16094] [client 192.168.2.1:54222] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /var/www/nextcloud/apps/bookmarks/controller/rest/internalbookmarkcontroller.php on line 141
[Fri Jun 30 11:40:37.203207 2017] [:error] [pid 16094] [client 192.168.2.1:54222] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0
```

#### Nextcloud log (data/nextcloud.log)

(empty)

**Comment by 4oo4** [comment]
I'm getting the same thing happening when I try to import my own set of bookmarks (both from Chrome and Firefox).

I know this was working fine with NC 11, but this was the first time I tried it after upgrading to 12. I'm also using Ubuntu 16.04 with Apache, but MySQL as my database.

What do your Apache settings look like for these? 

(From: https://serverfault.com/questions/112361/limit-apache-2-memory-usage)
```
<IfModule mpm_prefork_module>
    StartServers          5
    MinSpareServers       5
    MaxSpareServers      10
    MaxClients          150
    MaxRequestsPerChild   0
</IfModule>

<IfModule mpm_worker_module>
    StartServers          2
    MinSpareThreads      25
    MaxSpareThreads      75
    ThreadLimit          64
    ThreadsPerChild      25
    MaxClients          150
    MaxRequestsPerChild   0
</IfModule>

<IfModule mpm_event_module>
    StartServers          2
    MaxClients          150
    MinSpareThreads      25
    MaxSpareThreads      75
    ThreadLimit          64
    ThreadsPerChild      25
    MaxRequestsPerChild   0
</IfModule>
```
In my case, I have a pretty high memory limit for PHP (2G), but I'm guessing that my limiting factor is in those Apache settings. What does your `memory_limit` in `php.ini` and `nextcloud/.user.ini` look like?

**Comment by cangeeq** [comment]
I only have prefork enabled, with the default values from 16.04:
```
<IfModule mpm_prefork_module>
        StartServers                   5
        MinSpareServers           5
        MaxSpareServers          10
        MaxRequestWorkers     150
        MaxConnectionsPerChild   0
</IfModule>
```
As for PHP memory:
```
memory_limit = 128M
```
For sure none of this would handle a big install, but it's basically a single user nextcloud instance, so I would have hoped that was enough for a single bookmark. :-)

**Comment by 4oo4** [comment]
Yeah, I have the defaults for those too. I totally agree with you, it sounds like I have a bit beefier hardware but we are both using ours for small instances and shouldn't run into this for importing very small bookmarks files :smile: 

I was watching htop while running the import, and saw it spike up to 40% while it was trying to do the import, not sure if that points to memory leaks or not.

**Comment by 4oo4** [comment]
Looks like a fix is on the way: https://github.com/nextcloud/bookmarks/issues/382

It looks like something was causing an infinite recursion during the import, which would explain why the memory usage explodes

**Comment by cangeeq** [comment]
Bingo! I missed that when I looked since it was closed, but manually applying the patch fixed it for me, so closing this as a duplicate. Good spotting!

**Comment by marcelklehr** [comment]
Hey there!
Sorry for the wait... You seem to have figured things out quite well on your own :) Kudos for that ;)
We hope to release the next update soon, but there are a few bugs that we'd like to address first.

Cheers,
Marcel
