### ISSUE TITLE
Bulk Actions?

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/bookmarks#396]
I'm excited to see an app for Bookmarks. I suppose it is pretty new. I might be overlooking something, but I see no method for bulk operations. Here are some features I'd like:
- Bulk delete (I imported a bunch of bookmarks and have no way to delete them)
- Bulk tag (I'd like to tag a bunch of bookmarks at once)
- More advanced filtering
- Nested tags
- More ways to sort
- Import/Export include tags

**Comment by marcelklehr** [comment]
What do you mean by "nested tags"? Folders? What would be the purpose of that?

**Comment by marcelklehr** [comment]
Just found this older ticket: #157, so I'm closing this as a duplicate.

**Comment by mark-orion** [comment]
+1 from my side. The bulk tag / delete feature is the most important for me. It's just a pain to work one by one through a bunch of imported bookmarks.
