### ISSUE TITLE
[Announcement] Nextcloud Bookmark App for android

### ISSUE THREAD

**Issue by theScrabi** [nextcloud/bookmarks#398]
Hello there, I just wanted to announce my Nextcloud bookmark App for android, which is based on the new REST API. I comes with full ability to add/delete/edit, and view bookmarks.

Here is the App:
https://play.google.com/store/apps/details?id=org.schabi.nxbookmarks&hl=de

and here is there source code to it:
https://github.com/theScrabi/OCBookmarks

**Comment by marcelklehr** [comment]
Looks good! Do you intend to have it distributed via F-Droid as well?
Also, you could wrap up a pr to add this to the available companion applications ;)

**Comment by theScrabi** [comment]
@marcelklehr yes the PR for adding this app to f-droid is out, should be available in a few days.

**Comment by marcelklehr** [comment]
:tada: Awesome :)

**Comment by blizzz** [comment]
@theScrabi great stuff, thanks! :) 🚀

**Comment by theScrabi** [comment]
Thanks :)
