### ISSUE TITLE
Accesss to bookmarks from private browsing

### ISSUE THREAD

**Issue by Jurik-Phys** [nextcloud/bookmarks#404]
### Steps to reproduce
1. Turn browser to private mode
2. Follow the bookmark link [https://your.nextcloud.domen/index.php/apps/bookmarks/]
3. No bookmark access. You may see nextcloud login page.

### Expected behaviour
I expect access to bookmarks e.g. via unique link such as shared folders and used bookmarks from private mode.

### Actual behaviour
Now I have nextcloud login page after click to bookmarks url.

**Comment by 4oo4** [comment]
I use Chromium in Incognito mode all the time and have never had this issue. What browser/OS are you using?

**Comment by Jurik-Phys** [comment]
After additional tests I found out the following.
The login request appears only once after the browser starts and private window run for the first time. After the first login in private mode, bookmarks are available even after reopen private window of browser. This behavior suits for me.

P.S. Idea of unique link can be used for shared bookmarks and access for them without login to NC.
OS: Debian 8.2, browser: Icweasel 43, Chromium 49.0.2623.75

**Comment by 4oo4** [comment]
Interesting, never had that happen to me but glad to hear it's working.
