### ISSUE TITLE
Support for several profiles / collections?

### ISSUE THREAD

**Issue by Wernfried** [nextcloud/bookmarks#405]
Hi

Do you consider to provide possibility of using different sync profiles, similar to this feature: http://www.xmarks.com/about/features/sync_profiles

I am still using the service above with cost but I would prefer to use my nextcloud storage.

Of course, such feature makes sense only in conjunction with this Add-On: https://addons.mozilla.org/de/firefox/addon/floccus/

Best Regards

**Comment by blizzz** [comment]
It's a valid concern I think.I am not sure we need to change much on the server, provided that you say "I tag all my home bookmarks with 'home`and all my work bookmarks with 'work'". In some way you need to categorize them and the taggin infrastructure is already there. The clients (like addons) would then only sync bookmarks containing the specified tags.

**Comment by Wernfried** [comment]
Well, take a look at xmarks. There you define the profile just on the top-folders, not on single bookmarks. Handling the profile for each individual bookmark might be a difficult job.

**Comment by blizzz** [comment]
Well, we don't support folders. Tags are more flexible and can realize such a structure as well. In this case, it is also on the client to add the tag accordingly and automatically.

**Comment by mikeziri** [comment]
@blizzz if nextcloud/bookmarks doesn't support folders how can the browser show them as folders? not having a tree structure on the bookmarks is a mess in my opinion.

**Comment by marcelklehr** [comment]
@mikeziri Feel free to leave your opinion on the folders request over here: https://github.com/nextcloud/bookmarks/issues/13 ;)

**Comment by blizzz** [comment]
@mikeziri i'm for keeping a legacy attribute to support for browsers. Otherwise, i  think,  folders are an attempt to square the circle.

**Comment by marcelklehr** [comment]
Floccus now provides the possibility of setting a server path for syncing bookmarks, allowing you to sync different folders (possibly on different machines) with the same bookmarks account, rendering this issue superfluous.
