### ISSUE TITLE
bookmarklet doesn't work on this - github

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#409]
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”).

**Comment by blizzz** [comment]
Yes, it is a security measure of Github to not allow foreign java script. no way around for us. therefore, i am closing it. a browser extensions would work.

**Comment by kylepwarren** [comment]
Can you recommend an extension to work with this?

**Comment by blizzz** [comment]
@marcelklehr it's not?

**Comment by marcelklehr** [comment]
First time I hear of it. @kylepwarren let's head over to https://github.com/marcelklehr/floccus/issues and sort this out, shall we?
