### ISSUE TITLE
I see other user's tags

### ISSUE THREAD

**Issue by mase76** [nextcloud/bookmarks#411]
Hi!
When applying any of my tag filters, the other user's tags appear additionally.
I can even see the amount of entries near the tags, but not the bookmartks itself.

**Comment by kylepwarren** [comment]
Wow. Verified. Pretty heinous error. Really question the security of the entire nextcloud ecosystem now

**Comment by marcelklehr** [comment]
Hello there,

I've reproduced the bug and I've just opened a pull request that addresses this.
Thank you for reporting and sorry for the inconvenience it may have caused!

**Comment by kylepwarren** [comment]
Cool. It works. Not sure what's going on with that travis ci error[your pull request] about it not having php7.1 right after it tries to install it. php on my server is 7.0... and it works.

**Comment by mase76** [comment]
I confirm, commit 2c609d2f302999774ae83338b613307613ec618e fixed this issue.
