### ISSUE TITLE
Export bookmarks doesn't work

### ISSUE THREAD

**Issue by damko** [nextcloud/bookmarks#416]
### Steps to reproduce
1. click on gear
2. click export

### Expected behaviour
An htm file should be downloaded

### Actual behaviour
No file gets downloaded . This error message instead

> File not found
The specified document has not been found on the server.
You can click here to return to Nextcloud.

### Server configuration

**Operating system**:
debian stable

**Web server:**
nginx

**Database:**
mysql

**PHP version:**
7x

**Nextcloud version:** (see Nextcloud admin page)
12.0.4

**Bookmarks version:** (see Nextcloud apps page)
0.10.1  (v9.1.0RC4-314-g3be4e33a)
**Updated from an older Nextcloud or fresh install:**
fresh

### Note
I've already diagnosed the issue and made a fix. I'll submit PR right after this ticket

**Comment by tflidd** [comment]
reference: https://github.com/nextcloud/bookmarks/pull/417
