### ISSUE TITLE
Can you hide navbar while adding bookmark?

### ISSUE THREAD

**Issue by Mirokko** [nextcloud/bookmarks#418]
Hello! I have a simple question. Can you disable visibility of top navbar while i am adding bookmark? (see below for picture)
![firefox_2018-01-04_22-05-46](https://user-images.githubusercontent.com/11059471/34582175-2df580a0-f1a4-11e7-9995-6766f005d2b3.png)

**Comment by blizzz** [comment]
I guess so… although  keeping the logo could be reasonable to be have some confidence to be on the  right instance, in case you use more than one.

**Comment by ToKaTpoHb** [comment]
Yeah, keep it righter from "Add bookmark" words.

**Comment by marcelklehr** [comment]
Closing as won't fix. I don't think it's worth the hassle.
