### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#419]
I was thinking, maybe we could do a new release after #417 and #401 have landed / been fixed?

**Comment by blizzz** [comment]
Aye, makes sense 👍

**Comment by marcelklehr** [comment]
I've split up #417 by damko into two prs (excluding the css modifications): #421 and #422 

I also fixed #401 in #420

**Comment by blizzz** [comment]
just #422 left, thanks so much @marcelklehr 🚀

**Comment by blizzz** [comment]
On 13, the sidebar layout is borked:

![screenshot_20180129_111918](https://user-images.githubusercontent.com/2184312/35505383-4582d20e-04e6-11e8-8dc8-7434b0715d7e.png)

I'd try to fix it first before releasing, OK? Since 13 release is also very close

**Comment by marcelklehr** [comment]
Does this work?

```
.tag_list li {
  display: block;
}
```

**Comment by radoeka** [comment]
In nextcloud 13.0.0 the sidebar looks wrong.
It's like shown above (issuecomment-361200825 / https://github.com/nextcloud/bookmarks/issues/419#issuecomment-361200825)

Can it be fixed for nextcloud-13.0?

App version 0.10.1

The CSS did not work for me.  But than again, where must it be stored?  I guess in apps/bookmarks/css/bookmarks.css.  Any restart are similar action needed?

**Comment by marcelklehr** [comment]
@radoeka could you try #436 and see if that fixes it?

**Comment by radoeka** [comment]
YES!  That's fixes it.  Really nice :+1:

**Comment by marcelklehr** [comment]
Ah, thanks @radoeka, I'll look into that.

@blizzz when are you available for this? :)

**Comment by blizzz** [comment]
empowered @marcelklehr, and he was so nice :fireworks: :rocket:
