### ISSUE TITLE
Import of large file fails silently

### ISSUE THREAD

**Issue by tiberiuana** [nextcloud/bookmarks#423]
### Steps to reproduce
1. Export larger (Firefox) bookmarks HTML file (~5000 lines)
2. In Chrome, import into Bookmarks

### Expected behaviour
Bookmarks should be imported or an error message should appear.

### Actual behaviour
Nothing happens in the UI.

The import actually fails with this error in the browser console:
```
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)
```

Bookmarks 0.10.1
Chrome 63 on MacOS

**Comment by marcelklehr** [comment]
Thanks for reporting!

The reason for this is our (backwards-compatible) approach to uploading the file: We're using an iframe and those don't provide any response status information. A timeout may be in order, but wouldn't tell the user what went wrong.
