### ISSUE TITLE
Open files directly from "search result in another folder" instead of using scrollto=

### ISSUE THREAD

**Issue by ALT0023** [nextcloud/bookmarks#428]
When trying to open a file located in a folder with over 6 thousand files Nextcloud hangs for several minutes on all browsers. Using Nextant helps but is being decommissioned and I don't have any need for searching the contents of the files.

System has plenty of resources available and I have done many MariaDB enhancements but I believe the issue is occurring because of "scrollto" function having to page down to the file before displaying the appropriate file instead of a database problem, as the further down the filelist the file is, the longer it takes to load.

**Comment by marcelklehr** [comment]
Closing as it doesn't seem to be related to the nextcloud *bookmarks* app ;) Please open an issue over at https://github.com/nextcloud/server
