### ISSUE TITLE
Bookmarklet doesn't recognize already bookmarked urls with urlencoded chars

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#429]

**Comment by marcelklehr** [comment]
As a cause, this neat, useless-looking line of code catches the eye: https://github.com/nextcloud/bookmarks/blob/master/controller/lib/bookmarks.php#L128

**Comment by marcelklehr** [comment]
Mh @blizzz I cannot reproduce this with master?

**Comment by blizzz** [comment]
Does not work with this page for me: https://fr.wikipedia.org/wiki/Correspondance_entre_logiciels_libres_et_logiciels_propri%C3%A9taires

**Comment by marcelklehr** [comment]
Ah, ok. It's an encoding/matching problem.

The bookmarklet directs you to:
```
http://localhost:8008/index.php/apps/bookmarks/bookmarklet?output=popup&url=https%3A%2F%2Ffr.wikipedia.org%2Fwiki%2FCorrespondance_entre_logiciels_libres_et_logiciels_propri%25C3%25A9taires&title=Correspondance%20entre%20logiciels%20libres%20et%20logiciels%20propri%C3%A9taires%20%E2%80%94%20Wikip%C3%A9dia
```
where the url is read as: `https://fr.wikipedia.org/wiki/Correspondance_entre_logiciels_libres_et_logiciels_propri%C3%A9taires`

```
http://localhost:8008/index.php/apps/bookmarks/bookmarklet?output=popup&url=https%3A%2F%2Ffr.wikipedia.org%2Fwiki%2FCorrespondance_entre_logiciels_libres_et_logiciels_propri%C3%A9taires&title=Correspondance%20entre%20logiciels%20libres%20et%20logiciels%20propri%C3%A9taires%20%E2%80%94%20Wikip%C3%A9dia
```

where the URL is read as: `https://fr.wikipedia.org/wiki/Correspondance_entre_logiciels_libres_et_logiciels_propriétaires`

-- since the server code looks for exact matches, it doesn't find the existing bookmark.

**Comment by marcelklehr** [comment]
@xXSTrikeXx Any reason for moving this back to 'backlog'? :)

**Comment by xXSTrikeXx** [comment]
Holding a smartphone in the hands while walking :D Sry I thought i have undone my fault for using github on smartphone 🥇  :/ I hope its not to late to apologize :)

**Comment by marcelklehr** [comment]
No worries. I know the feeling. Github on mobile is like minimally invasive surgery with your bare hands :)

**Comment by xXSTrikeXx** [comment]
My friend next to me reading this - he´s studying medicine - is rofl due to that comparison with Github :D :D
