### ISSUE TITLE
Can you optimize page to view in sidebar?

### ISSUE THREAD

**Issue by Mirokko** [nextcloud/bookmarks#430]
I'm talking about sidebar in new firefox quantum. On my screen it takes about 370 pixels, so it all comes down to optimize to mobile view.
![image](https://user-images.githubusercontent.com/11059471/35191911-7fe93332-fe8f-11e7-950d-6e293363939d.png)

**Comment by marcelklehr** [comment]
Hey there,
thanks for taking the time to give feedback! :)
To answer your question: Yes, we're currently working on a new user interface that will be much more usable on mobile and small screens. See #424 for some early screenshots.

Cheers :)
