### ISSUE TITLE
Bookmark tags are visible in notification popup

### ISSUE THREAD

**Issue by goeck** [nextcloud/bookmarks#434]
### Steps to reproduce
1. open Nextcloud web interface
2. go to "bookmarks" app
3. click on notifications bell icon , which has active message-waiting indicator

### Expected behaviour
popup opens attached to bell icon with messages list boxes carrying formatted text

### Actual behaviour
popup opens just as expeded, plus some list boxes show tags shown in bookmarks area with same visual appearance as is in active bookmarks area

### Server configuration detail

**Operating system:** Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 5.7.16

**PHP version:** 7.0.27
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, mcrypt, standard, mysqlnd, mysqli, PDO, pdo_dblib, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, Reflection, imap, shmop, SimpleXML, snmp, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, apache2handler

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - announcementcenter: 3.1.1
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.5.7
 - caniupdate: 0.1.2
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - deck: 0.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxedit: 0.0.7
 - gpxpod: 2.2.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.9
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - encryption
 - files_trashbin
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "oc22yd6p5y5t",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "lavatechnology.de"
    ],
    "datadirectory": "\/home\/www\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/lavatechnology.de\/nextcloud",
    "dbtype": "mysql",
    "version": "12.0.4.3",
    "dbname": "xb1340_db2",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "php",
    "mail_smtpsecure": "ssl",
    "mail_domain": "lavatechnology.de",
    "mail_from_address": "nextcloud",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "production"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Operating system:** 

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
```

#### Browser log

firefox console log
```
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
Source-Map-Fehler: request failed with status 404
Ressourcen-Adresse: http://lavatechnology.de/nextcloud/core/vendor/core.js?v=daaac81f2daa438103e348aa5c2fbf9f-0
Source-Map-Adresse: purify.min.js.map
[Weitere Informationen]
SyntaxError: unexpected token: ':'
[Weitere Informationen]
merged-template-prepend.js:4:11
Passwort-Felder sind auf einer unsicheren (http://) Seite vorhanden. Dies ist ein Sicherheitsrisiko, durch das Zugangsdaten gestohlen werden können.
[Weitere Informationen]
bookmarks
Synchrone XML
```

**Comment by goeck** [comment]
![2018-01-31 09_19_18-lesezeichen - nextcloud](https://user-images.githubusercontent.com/392197/35626085-e5bb1e0c-0694-11e8-8eae-8df69f6d45c8.png)

**Comment by goeck** [comment]
![2018-01-31 09_19_18-lesezeichen - nextcloud](https://user-images.githubusercontent.com/392197/35626131-0b83f1cc-0695-11e8-9838-6584114467ef.png)

**Comment by marcelklehr** [comment]
Hah, this is unfortuante. The notification has the same id as one of your bookmarks, so it gets assigned the tags that are meant for the bookmark.

Problem is this line: https://github.com/nextcloud/bookmarks/blob/master/js/bookmarks.js#L336

**Comment by goeck** [comment]
Wow, thanks for fixing that quick. :thumbsup:
