### ISSUE TITLE
Copy page as an artikel

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/bookmarks#438]
In last time, i prefer wallabag, because it gives me the ability to read my bookmarks offline. Its a perfekt pocket/read it later solution. It would be also an Archievement to read offline in train or somewhere else bookmarked links. Another cool feature is the archive. I can archive readed articles and thats a very nice new possibility of structure. I often bookmark new cooking receipts and then I know which of them I already cooked. 
I also like the raster view with an example picture of the bookmarked site and a little description of it. Little disadvantage for me using wallabag: The apps in nextcloud are better. 

I hope I can post my little suggestions here and hope that it is not an overenhancement for a simple bookmark app. But in my opinion is overview and a little imagination behind the bookmarks the most important thing to find what you want - even if you dont know it (example cooking receipt, there you can easily choose an receipt what you want by choosing based on preview images.) :smile::heart_eyes::grinning:
The table list of bookmark is so unclear. ;)

**Comment by marcelklehr** [comment]
hey @xXSTrikeXx 
Thank you for your feedback! The UI is being overhauled at the moment, adding a grid view with preview images. A read-it-later feature would be very useful indeed and is also something we have in mind for the future. :)

**Comment by marcelklehr** [comment]
These libraries would be useful for this feature:

 * https://github.com/essence/essence
 * https://github.com/j0k3r/graby

**Comment by sunjam** [comment]
[Here is another selfhosted bookmark app written in Go called Shiori that is cloning Pocket: It saves copies of webpages as HTML for use offline. ](https://github.com/RadhiFadlillah/shiori)
    
Saving bookmarked webpages as Markdown would also be really useful, so they could be available in the Markdown Editor and QownnotesAPI.

**Comment by marcelklehr** [comment]
I'm closing this in favor of https://github.com/nextcloud/bookmarks/issues/210 which can be used together with the newsreader app, avoiding the need to duplicate that code base.

**Comment by marbetschar** [comment]
+1 for offline storage of bookmarks. On my end mainly for archive purposes. That said, I would also be fine with the possibility to upload an attachment manually (e.g. a PDF print of bookmarked page, or a simple HTML output).

**Comment by florianwgnr** [comment]
Might also be linked to @1128 with the idea of saving a screenshot via screenly when adding a bookmark.

**Comment by sunjam** [comment]
In this case, would coincide if that screenshot is one of the full web page
since this request is for archiving an offline copy of the bookmarked site.
Saving as a screenshot, or as HTML + attachments, is the way Evernote does
it.

**Comment by florianwgnr** [comment]
Just to leave the idea here: 

I stumbled across the Firefox-AddOn "SingleFile", which saves a complete web page into a single HTML file (including images, CSS, etc.). Maybe some parts of this tool are useful and can be used to generate and save a page as one file within the nextcloud instance (while bookmarking it).

**Comment by marcelklehr** [comment]
Work on this is in progress over here: https://github.com/nextcloud/bookmarks/pull/1416

**Comment by github-account1111** [comment]
> 
> 
> [Surprisingly, I've found a Nextcloud app for archiving bookmarks called **Nextcloud Paper**](https://github.com/andreasjacobsen93/nextcloud-paper). Crazy, but here it is!
> 
> Also, there is issue #524 for building out wallabag integration.

This doesn't really produce a faithful copy of the webpage though, does it? It's sorta like what Pocket does, which honestly I'm not a fan of, but to each their own of course.
