### ISSUE TITLE
Request: integrate Tagspaces web clipper with Nextcloud Bookmarks

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#442]
[Based on Electron, fully open source, works with latest firefox and chrome](https://github.com/tagspaces/browser-extensions), [should be usable as maintainer mentions here](https://github.com/tagspaces/browser-extensions/issues/1). This tool could also benefit [Nextcloud Notes issue #169](https://github.com/nextcloud/notes/issues/169) by allowing one browser extension to create related Nextcloud Notes and Nextcloud Bookmarks.

- Saving complete web pages as HTML and MHTML(chrome only) files
- Saving selected part of a web pages as HTML file
- Saving a screenshot of the visible area of the current tab as PNG file
- Saving a bookmark as URL files

**Comment by marcelklehr** [comment]
Hey @sunjam 

Thank you for your activities and ideas! Open source projects do need to work together more closely :)

There is already a feature request open regarding adding a complete page / allowing html in descriptions: https://github.com/nextcloud/bookmarks/issues/438 which is a very useful feature.

#424 adds support for preview images, but there's no possibility to manually set those, yet.

Regarding bookmarks as files in nextcloud: I see how this would be useful, as there would be an already standardized protocol (webdav) and extisting facilities for ordering/organizing, syncing and sharing bookmarks. The downsides would be (apart from breaking existing tools) that it might be confusing for users to have the bookmarks stored inside their files, and we probably cannot run special actions, when people Create/Update/Delete bookmarks from outside the bookmarks app.

In general, a tighter integration with the notes app would definitely be an improvement for the user experience, I think.

**Comment by marcelklehr** [comment]
I'm closing this in favor of separate issues (see #445, #446).
