### ISSUE TITLE
Feature Request: Markdown support in bookmark descriptions

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#443]
This feature request is for markdown support in bookmark descriptions for instances with Markdown Editor app installed.  Tested on server 12.0.5

Edit: This might also be addressed by #447

**Comment by sunjam** [comment]
[If it helps for reference, the Nextcloud Deck app has implemented markdown descriptions.](https://github.com/nextcloud/deck)

**Comment by jancborchardt** [comment]
It seems that for a _Bookmarks_ app, having markdown support in the descriptions comes with a lot of maintenance work at the benefit to just few use-cases or people. Usually descriptions are only a sentence or at most a few paragraphs. Also other systems like Firefox or Chrome bookmarks don’t really make use of Markdown.

@marcelklehr I’d suggest focusing on other thigns more core to a Bookmarks app. ;)

**Comment by marcelklehr** [comment]
@jancborchardt I agree. It's not a priority for me, either. More of a nice to have. If someone wants to implement this, feel free :)

**Comment by jancborchardt** [comment]
@marcelklehr I’d even drop it, because even if someone develops it, you will have to maintain it. ;)

**Comment by marcelklehr** [comment]
@jancborchardt good point :)
