### ISSUE TITLE
Storing bookmarks in files?

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#446]
requested in https://github.com/nextcloud/bookmarks/issues/442

Personally, I think this would be a lot of work for little benefit, but if someone wants to implement this, go ahead.

**Comment by blizzz** [comment]
Agreed about the effort-benefit-ratio.

**Comment by sunjam** [comment]
I also agree.  I was asking about this, but I see adding a Share API will resolve this request as well.  #5

**Comment by sunjam** [comment]
I found a way to save my bookmarks as a file.  Exporting my bookmarks gives me everything as a single HTML file.  This is perfect; now I'd just like that process automated via user settings so it can be saved and updated within a user location in Nextcloud.  It serves as a sort of universal backup.

This would make it easy to view and search my bookmarks within the NextNotes app via the html version.
