### ISSUE TITLE
Tighter integration with Notes app?

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#447]
Many apps these days combine bookmarking and note taking, as the two are indeed a way to collect information (either produced by someone else, or created by yourself).

I'm open to suggestions on how this could look like.

cc @nextcloud/notes

**Comment by stefan-niedermann** [comment]
The notes app already has a category system, maybe there could be a hardcoded category "bookmarks" which lists all bookmarks from the bookmarks-app as editable notes? (of course only if both apps are installed)

**Comment by marcelklehr** [comment]
@stefan-niedermann thanks for the reply! :)

Yeah, linking notes to bookmarks and vice versa could be very useful. We could parse notes for URLs and automatically add bookmarks for those, linking back or even integrating the relevant notes. Vice versa, an existing bookmark could offer adding a note to it in the notes.

btw, I saw there's a second notes app in the making. What's the status in this regard, will the current app be replaced, is that a grass-roots-alternative?

**Comment by marcelklehr** [comment]
Are there any hooks in the notes app for the CRUD operations?

**Comment by korelstar** [comment]
The notes app doesn't have any own hooks. But since it's completely based on file operations, you can use those hooks.

Development on the other new notes app has slow down. I don't know if they continue.

**Comment by sunjam** [comment]
Very interesting possibilities in integration with the QownnotesAPI and the [Qownnotes app, which is already capable of converting URL's to Nextcloud Notes; see this request for integration with bookmarks app](https://github.com/pbek/QOwnNotes/issues/1198).  Also, see their *[Web Companion](https://github.com/qownnotes/web-companion)* extension which saves bookmarks in Firefox and Chrome.

**Comment by marcelklehr** [comment]
Currently, I'm thinking the most useful integration feature for this app would be extracting bookmarks from notes.

**Comment by lexelby** [comment]
This might be useful for those of us using Nextcloud Bookmarks to curate a list of bookmarks, e.g. for a newsletter.  See https://github.com/nextcloud/bookmarks/issues/506#issuecomment-403330574 for more details on this use case.

A Notes app integration may make a lot more sense for my use case rather than trying to wedge Bookmarks into a use case you folks don't intend it for.  For now, I've hacked my version to add the description in the non-grid view, but it's kinda janky.

**Comment by jakobroehrl** [comment]
It's planned to provide an Text API for an easy integration with other App.

**Comment by marcelklehr** [comment]
Note to self: https://github.com/nextcloud/notes/blob/1518f70b224b8b2012acf4b6e99b0c5dd23c8bc1/lib/Service/SettingsService.php

**Comment by marcelklehr** [comment]
I've implemented projects support and added an additional hook that will add Links from Notes to the bookmarks app and link the bookmark with the Note file (Notes does not support projects, yet.)

**Comment by sunjam** [comment]
Here is the [attach note to project](https://github.com/nextcloud/notes/issues/598) request for anyone wanting to learn more about it.
