### ISSUE TITLE
Federate entire Bookmarks app onto other Nextcloud instances

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#449]
[I’m curious about logging into, and possibly mirroring, an existing Nextcloud Bookmarks app on Box A, by adding proper credentials in app store of Box B.](https://help.nextcloud.com/t/radical-idea-for-federated-apps-add-app-via-remote-credentials-rather-than-install-locally/28054/2)

[See server issue #8463](https://github.com/nextcloud/server/issues/8643)

**Comment by marcelklehr** [comment]
I think this is out of the scope for this app, as we can't do much about it. :)
