### ISSUE TITLE
RFI on Readme.md update with App information

### ISSUE THREAD

**Issue by novski** [nextcloud/bookmarks#450]
This App seams to be in heavy development, realy nice!
I wold like to know how this App works. 
For that im asking the developers to update the Readme file with information about how its built.
Information about how the data ist stored, where it lies, and what are the dependencies or if its built on a framework to line out what kind.

**Comment by blizzz** [comment]
Why don't you also start collect the info from the source and create a PR?

**Comment by marcelklehr** [comment]
I agree that this information can be quite useful and it's probably easier to provide for someone who's already familiar with the code base. I have updating the README on my to-do list anyhow, once #424 is merged :)

**Comment by novski** [comment]
Thanks.

**Comment by marcelklehr** [comment]
@novski The updated README is live. I thought about adding more info about dependencies, but I think it's probably best to look into the composer.json and package.json files directly to get up-to-date information. (The new UI is built with Backbone Marionette, e.g.)
