### ISSUE TITLE
possibility of sharing

### ISSUE THREAD

**Issue by hercut** [nextcloud/bookmarks#453]
It would be interesting to give the possibility to share folders with other nextcloud users.

This makes it possible to have favorites managed by several people of a team.

**Comment by marcelklehr** [comment]
Hey @hercut :)
Thanks for taking the time to give feedback. We're thinking about how best to add sharing functionality to the app at the moment. See #5 for more information ;)

Closing this as a duplicate of #5 
Cheers!
