### ISSUE TITLE
Accept more protocols?

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#454]
With the ability to sync bookmarks come protocols that are not currently accepted by the app.

E.g. `file://` and `javascript:`

One the one hand I feel it should be possible to sync these bookmarks just like any other, on the other hand (especially file URLs) tend to be of little use in a web app. Still, e.g. in a LAN  with shared network drives that map to the same drive letters on all machines, file URLs might come in handy.

What do you think?

**Comment by blizzz** [comment]
certainly not the JS one, there should not be any arbitrary code executed. Also file:// could perhaps grant access to sensitive files of the server. Would not go for either of them.

**Comment by marcelklehr** [comment]
Makes sense, then let's close this.
