### ISSUE TITLE
l10n messages in html files aren't picked up by translation bot

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#456]
Hey @MorrisJobke 
Thanks for setting up the translation infrastructure for us. There appears to be one string that isn't picked up, however. (or simply hasn't been translated perhaps?)
https://github.com/nextcloud/bookmarks/blob/bdd0d06ee62791a58824a61cef2e050dc3107736/js/templates/Settings.html#L7

Is there anything wrong on our end?

**Comment by MorrisJobke** [comment]
We only scan php, js, jsx, ts and tsx files. Could you open a ticket in the docker-ci repo to also include html files in the parsing process? Thanks

**Comment by MorrisJobke** [comment]
Should be fixed by tomorrows run of the transifex sync. ;)

**Comment by marcelklehr** [comment]
:tada: Awesome! Thanks a lot :)
