### ISSUE TITLE
missing from apps store

### ISSUE THREAD

**Issue by yeupou** [nextcloud/bookmarks#459]
Running latest 13.0.1 nextcloud, I cannot find bookmarks in the app store from within nextcloud. Is it supposed to be so?
(even though it is marked as ready for 13)

**Comment by yeupou** [comment]
Ok, forget about it. Somehow, with a very small windows, some apps are never visible with Firefox. In fullscreen, no issue.

**Comment by marcelklehr** [comment]
Might be an issue for https://github.com/nextcloud/server in that case :)
Thanks for reporting anyhow! :)

**Comment by yeupou** [comment]
No problem. Nice work, BTW, thanks :-)
