### ISSUE TITLE
Disable autocomplete in form fields

### ISSUE THREAD

**Issue by iw0nderhow** [nextcloud/bookmarks#463]
Hello, just a small feature request to make the interface look a bit "cleaner".

### Expected behaviour

Input suggestions are not made when editing the "Address" or "Site title" fields

### Actual behaviour

There are suggestions for the input in these fields.

### Server configuration

**Operating system**: Raspbian 9

**Web server:** Apache 2.4.25-3

**Database:** MariaDB 10.1.23-MariaDB-9

**PHP version:** 7.0.27-0

**Nextcloud version:** 13.0.1

**Bookmarks version:** 0.11.0

**Updated from an older Nextcloud or fresh install:** Updated from 12.0.4

### Client configuration
**Browser:** Firefox 59.0.1

**Operating system:** Windows 7

**Comment by marcelklehr** [comment]
Thanks for your feedback! This is a good idea. :)
