### ISSUE TITLE
Unable to Remove All Bookmarks with Specific Tag

### ISSUE THREAD

**Issue by SomePoorBastard** [nextcloud/bookmarks#464]
### Expected Use Case
Import of bookmarks to Nextcloud Bookmarks (here on referred to as NCB) from .json, and .html exports from Mozilla Firefox and Google Chrome, non-respectively. Server should act as authority once bookmarks have been collected from clients and imports.
### Summary of Issue
Removing bookmarks by tag from NCB web interface to prepare for re-importation of bookmarks as part of cleanup of oddly named tags from Floccus addon (See https://github.com/marcelklehr/floccus/issues/64) [Inline Edit: Just read these are by design to keep folder structure intact on browser side. Whoops...]. I have temporarily disabled client on both browsers I work from to perform the cleanup, but could not remove the following tag: `__floccus-path:\`.
#### Clients
_Note:_ Clients are on two separate computers
##### Google Chrome <system_with_chrome>
chrome://version
```
Google Chrome | 65.0.3325.181 (Official Build) (64-bit)
           -- | --
     Revision | dc3469be277cc962ba01d9c0cb5bb1a265676c36-refs/branch-heads/3325@{#725}
           OS | Linux
   JavaScript | V8 6.5.254.41
```
##### Mozilla Firefox <system_with_firefox>
about:support
```
Name: Firefox
Version: 59.0.2
BuildID: 20180327091359
User Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
OS: Linux 4.15.13-300.fc27.x86_64
```
##### Nextcloud <example.com>
**Operating system**:
_uname -a_
```
FreeBSD nextcloud.example.com 11.1-RELEASE-p8 FreeBSD 11.1-RELEASE-p8 #0: Tue Mar 13 17:07:05 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```
**Web server:**
_nginx -v_
```
nginx version: nginx/1.12.1
```
**Database:**
PostgreSQL 10.0.1
**PHP version:**
```
PHP 7.1.15 (fpm-fcgi) (built: Mar 18 2018 21:37:26)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.15, Copyright (c) 1999-2018, by Zend Technologies
```
**Nextcloud version:** (see Nextcloud admin page)
13.0.1
_Updated from an Older Nextcloud_ (Yes) | Fresh Install (No)
**Bookmarks version:** (see Nextcloud apps page)
_Note:_ Also tested with commit bdd0d06ee62791a58824a61cef2e050dc3107736 previously; updated to see if issue persisted
commit 332e775a78293d3173be8bc885c4cf10933c56b2 (HEAD -> master, origin/master, origin/HEAD)
_Update Procedure:_
```
cd <./apps/bookmarks>
git pull
npm run build
```
### Procedure to attempt reproduction of issue
1. Start with a Nextcloud Deployment with the same Nextcloud version, NCB version, and two clients; Google Chrome and Mozilla Firefox with Floccus installed.
2. Let clients synchronize with NCB.
3. Look for tag with ```__floccus-path:\```
4. Remove all bookmarks with this tag using the left panel.

### Expected behaviour
All bookmarks with this tag are deleted. (Originally expected all bookmarks with that tag to be cleared of that tag, but backups are handy)

### Actual behaviour
Tag disappears for a brief (under a second) moment before re-appearing in the same position.

**Signing status:**
```No errors have been found.```
(Interestingly on a separate issue, this is tripped up by the presence of nextcloud.log inside the install dir [Tested on NC ~12.0.4, and NC 13.0.0]

**Are you using external storage, if yes which one:** No
**Are you using encryption:** No
**Are you using an external user-backend, if yes which one:** No

#### nginx
```
system_with_chrome - - [30/Mar/2018:23:42:41 -0400] "DELETE /apps/bookmarks/tag/__floccus-path%3A%2F HTTP/1.1" 302 5 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"
system_with_chrome - - [30/Mar/2018:23:42:42 -0400] "DELETE /apps/files/ HTTP/1.1" 405 5 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Saf
ari/537.36"
```

#### Nextcloud log (data/nextcloud.log)
No entries are found indicating that NCB is writing relevant data to this log.

##### system_with_chrome
```
core.js?v=d83a95b6-5:7 JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://nextcloud.example.com/core/vendor/purify.min.js.map
DevTools failed to parse SourceMap: https://nextcloud.example.com/apps/bookmarks/js/dist/backbone.radio.js.map
main.bundle.js?v=d83a95b6-5:13175 DELETE https://nextcloud.example.com/apps/files/ 405 ()
send @ main.bundle.js?v=d83a95b6-5:13175
ajax @ main.bundle.js?v=d83a95b6-5:12781
Backbone.ajax @ main.bundle.js?v=d83a95b6-5:1530
Backbone.sync @ main.bundle.js?v=d83a95b6-5:1513
__WEBPACK_IMPORTED_MODULE_0_backbone___default.a.sync @ main.bundle.js?v=d83a95b6-5:24979
sync @ main.bundle.js?v=d83a95b6-5:507
destroy @ main.bundle.js?v=d83a95b6-5:751
actionDelete @ main.bundle.js?v=d83a95b6-5:25655
dispatch @ main.bundle.js?v=d83a95b6-5:8758
elemData.handle @ main.bundle.js?v=d83a95b6-5:8566
```

**Comment by marcelklehr** [comment]
Hey :)

This is a known bug: Tags with underscores or slashes cause problems, which is why I opted to remove the underscores and replace slashes with `>` in floccus v2. See #432 and #441

As a workaround, you could remove the bookmarks with those tags (either individually in v0.11 or by bulk selecting and delting them with the master version) and add them again.
