### ISSUE TITLE
Keep the tag selector visible in the browser window

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#465]
### Steps to reproduce
1. Have many bookmarks and many tags
2. The tags will be shows on the left side (it is a long list)
3. Select a tag somewhere at the bottom of the long list with tags
4. Now reset the tag selection.... (via the tag selection box)

### Expected behaviour
The tag selection box is very easy to reach, e.g. by keeping it visible in the browser window, or by enabling the home button.

### Actual behaviour
The tag selection reset, etc works, that's OK.

Due to the long list with tags, one has to scroll up to be able to change the tag set (that is located at the top left corner of the page).

The tag selection box is hard to reach. It is not possible to e.g. use the home button to quickly jump to the top of the page.  The scroll bar is small, and hard to see.  Making it a bit curmbersome to work with (at least it isn't a pleasure).

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** sqlite

**PHP version:** 7.x

**Nextcloud version:** 13.0.1

**Bookmarks version:** 0.11

**Updated from an older Nextcloud or fresh install:** updated

**Comment by marcelklehr** [comment]
Thanks for reporting this. The UI has been completely revamped recently (the changes have not been released yet) and we've tried to optimize tag selection. In the new UI, tags will not disappear anymore when selecting them and you can reset the selection by clicking on a different tag or clicking on a different button to show all bookmarks. We've thus opted to make combining tags a little harder in order for the former behavior to be more straightforward: If you want to combine two tags in the new UI, you need to select one and then add the other to the selection in its 3-dot menu.

If you'd like to try the new UI, you can follow [these installation steps](https://github.com/nextcloud/bookmarks#manual-install).

**Comment by radoeka** [comment]
Do you already know when a version with the new GUI will be released?
I prefer to wait for an official release.

**Comment by radoeka** [comment]
Sounds good.  Keep up the good work, looking forward to the new version.
