### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Lantizia** [nextcloud/bookmarks#466]
### Steps to reproduce
1. Notice there is no way to directly donate to this great app

### Expected behaviour
Have a way... like the...
"Donate using Liberapay"
Button that is on this page... https://github.com/marcelklehr/floccus

### Actual behaviour
There isn't one

### Server configuration, etc...
Really not needed for this bug :)

Basically I don't mind logging a bunch of issues, but I feel better knowing people can eat (ok maybe an extreme example) before I do.  I'm doing the same with floccus issues at the moment.

**Comment by blizzz** [comment]
@marcelklehr if you like, place your LiberaPay button here, too. Since you're the main driver right now and also maintainer it seems right and fair.

**Comment by marcelklehr** [comment]
Closing this as I don't feel comfortable adding my donate button to this repo.
