### ISSUE TITLE
Duplicate bookmarks

### ISSUE THREAD

**Issue by Lantizia** [nextcloud/bookmarks#467]
### Steps to reproduce
1. Have the same bookmark twice (e.g. perhaps they have different tags, so they're in there twice for different purposes... e.g. they might be different folders if you're using floccus which uses tags to emulate folders)

### Expected behaviour
It to work

### Actual behaviour
Apparently this is not supported... see... https://github.com/marcelklehr/floccus/issues/80

### Side note...
Let me donate...
https://github.com/nextcloud/bookmarks/issues/466

**Comment by blizzz** [comment]
The philosophy is to have just one bookmark per URL and user. You can assign several tags to them. Which scenario would you like to solve?

**Comment by Lantizia** [comment]
I guess the issue is really two bookmarks that have the same URL but have different names.

From a floccus perspective (granted not everyone uses this) the tags are not visible, but rather just something that is used to recreate folders.

So if you need something bookmarked twice (in two different folders for example, where the information on that page might be useful for two different projects)... you may want two different names to help you remember why the hell you needed it bookmarked :)

I get the philosophy (and it's a good one, if you're not *like me* and have more interest in native integration)... but can't we do both?  Have duplicates allowed (e.g. for two different names) and *also* use tags to have a single bookmark be under two tags?

**Comment by blizzz** [comment]
> you may want two different names to help you remember why the hell you needed it bookmarked :)

there'd be the description field 

>  Have duplicates allowed (e.g. for two different names)

Now this has a deep impact in several areas as we build on the assumption to have just one unique URL stored. Actually it will result in a mess, when people start to bookmark the same page multiple times, or in a cluttered UI, compromising UX.

**Comment by marcelklehr** [comment]
I also think this does not belong in the scope of the bookmarks app. Let's tackle this in floccus.

**Comment by dotancohen** [comment]
@marcelklehr Now that we have [folders implemented](https://github.com/nextcloud/bookmarks/issues/514), there is a very valid use case for duplicate bookmarks.

[This bookmark](https://www.instructables.com/id/ARDUINO-WIRELESS-HOME-SECURITY-SYSTEM/) I have bookmarked in two folders:
* Projects with Maayan
* Arduino

I need that bookmark to show up in both locations, as it is relevant to learning Arduino, and it is also a project that I might do with my daughter if she finds it interesting.

Additionally, all major web browsers (Firefox, Opera, Chrome) allow duplicate bookmarks so Floccus would need support in Nextcloud for dupe bookmarks anyway to cleanly sync a full browser's stored bookmarks.

Please reconsider reopening this issue. Thank you.

**Comment by marcelklehr** [comment]
@dotancohen It is already possible to have one bookmark in multiple folders, which is how floccus syncs duplicates. :)

**Comment by dotancohen** [comment]
@marcelklehr Terrific, thank you!
