### ISSUE TITLE
Imported Bookmarks missing descriptions

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#471]
Tried migrating bookmarks using default html export option from one instance of 0.11.0 to another.  I see descriptions in the html file itself, but none of them actually imported back into Nextcloud Bookmarks app.

**Comment by marcelklehr** [comment]
Thanks for reporting this! A fix has been accepted into the master branch already and is waiting to be released: https://github.com/nextcloud/bookmarks/pull/461

**Comment by prog-amateur** [comment]
Hello, maybe I misunderstood, but I have tried to export bookmarks as html file, then drag it to Nextcloud bookmark page, but I see the description of my bookmarks (local webpage). 
Is the problem above different than mine ? How to proceed ?
Thank you.

**Comment by sunjam** [comment]
There is an import button under settings.  Use it to import the html file.

**Comment by prog-amateur** [comment]
Thank you very much, I have found it.
