### ISSUE TITLE
Refine deletion experience especially for accidental deletions

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#481]
I’d like to request an option to hide all delete buttons completely.  Speaking for myself, I’m not interested in deleting bookmarks and see it is now very easy to delete any entry without confirmation.

Couple possible thoughts...
- Hide “Delete” as a a selectable option within _Settings_.
- Bookmark Trashcan, so accidental deletions can be restored
![9113fd85-0393-4825-a893-55ddb3c02f34](https://user-images.githubusercontent.com/1787238/39377822-60bb7cbe-4a0b-11e8-95a2-1c610421ddff.jpeg)

Thanks for considering!

**Comment by marcelklehr** [comment]
The deletion experience is not very smooth, I agree. I'd personally favor a seven second timeout allowing the user to undo the delete action, as described here: https://docs.nextcloud.com/server/13/developer_manual/design/navigation.html#undo-entry

**Comment by sunjam** [comment]
Does that mean the user must literally wait seven seconds for every deletion before they can continue browsing?
- _Are you sure_?  might also work.
- I would love to avoid the ... menu entirely.

**Comment by marcelklehr** [comment]
The timeout wouldn't be directly visible to the user. The user would simply be able to "undo" the delete action within a timespan of 7 seconds. (Internally, the app would wait 7 secs before actually deleting the bookmark).

I think, the three-dot menu is pretty similar to how other nextcloud apps, e.g. files, work. I can understand that two clicks in a context menu for initiating bulk selection may be annoying, though...

**Comment by skewty** [comment]
Bulk selection, even with the new [Select all visible option] is neither intuitive nor is it efficient.  Perhaps offer a selection mode toggle up top so single clicking on bookmarks works to select.  Also, a DELETE ALL needs to exist somewhere.  Maybe hide it in Settings and use a confirmation popup or something.  Just my 2 cents.

**Comment by marcelklehr** [comment]
@skewty I see you've found the release candidate :)

> Bulk selection ... is neither intuitive nor is it efficient.

I'm, sorry to hear that. Why is it not intuitive do you think? How would you improve it?

> Perhaps offer a selection mode toggle up top so single clicking on bookmarks works to select.

Once you have selected a bookmark, you're essentially in edit mode.

**Comment by jancborchardt** [comment]
The direct deletion button in the sidebar really seems a bit too prominent. Could we either remove that or put it into a 3-dot-menu?

@sunjam we are not going to introduce settings for small stuff like hiding the delete button though. ;) Settings will only come for really important things.

**Comment by marcelklehr** [comment]
@jancborchardt Thanks for your input! A three-dot-menu would only make sense if there were other menu items in my opinion, but there is only "delete" currently, so I'm fine with removing the button from the drawer entirely.

**Comment by marcelklehr** [comment]
See #525 for the removal. The timeout still needs to be implemented.

**Comment by jancborchardt** [comment]
@marcelklehr a usual other action in the menu is "Rename" for example. :)

**Comment by marcelklehr** [comment]
I'm closing this in favor of a bookmarks trashcan #681
