### ISSUE TITLE
Remove Thumbnail Color

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#484]
Question:  How is thumbnail color assigned?

As a visual medium for organization, it would be interesting if Bookmark colors could be altered...

- Color by tag
- Color by date
- Color if description included
- Select and change color
- View by color

Point of reference: Kanban boards and the [Deck app](https://apps.nextcloud.com/apps/deck) with colored cards that have tags, etc.

**Comment by marcelklehr** [comment]
The thumbnail color is currently selected based on the URL. Every URL gets a different color. It is merely a fallback for link previews, though, which are only populated when you add a bookmark. When you upgrade from an existing installation you won't see any previews, atm.

**Comment by marcelklehr** [comment]
Come to think about it, it might make more sense to assign one color per domain, rather than individual colors for all the different URLs.

Color by tag or date would tap into the same hole as sorting, I think, which is being worked on already. I think it's not advisable to have too many options for organizing bookmarks. If you want to organize, you can do that via tags. We might add configurable colors to those one day, but I don't see the use case for changing the thumbnail colors right now.

**Comment by marcelklehr** [comment]
The colors in this PR are somewhat more beautiful: https://github.com/nextcloud/bookmarks/pull/487 :)

**Comment by jancborchardt** [comment]
The color should be:
- based on the favicon, to have a relation to the site
- as soon as we really display previews, the background color could also be based on that preview image to show before it loads

Any other colorization (by every url getting different color, or date, or tag etc) is meaningless. And changing color is not needed if we base the color on the favicon for example.

**Comment by marcelklehr** [comment]
@jancborchardt Background colors based on favicons are a good idea. The current "random" colors were a fallback for the previews (which we do have, already, more or less) to show at least something recognisable. With favicons we can fall back to the main favicon color, and only if there's no favicon assign a color based on  the domain.

**Comment by marcelklehr** [comment]
Getting colors from a favicon/screenshot has too little benefit in comparison to the amount of work necessary, IMO. I think I'll simply remove those colors entirely, they apparently indeed instill a false sense of meaning.

**Comment by jancborchardt** [comment]
@marcelklehr hm, the Google image search for example uses one primary color from the image as a placeholder. It gives some sense of what an image could be, and at the very least it’s a bit less bland than just a grey box. :)

**Comment by marcelklehr** [comment]
I agree that this would be a nice feature, but it's a pretty minor one and I'm not sure if the potential amount of code necessary for it is worth it.
