### ISSUE TITLE
Feature Request: Zoom

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#485]
The new interface is really interesting, and I have tons of bookmarks, so the first thing I did was zoom way out to 20% in Opera/Vivaldi so I could more easily see bookmarks in a 17 x 12 grid, then zoomed up to 300% so just one thumbnail was visible in ultra high detail.  Could this be on the roadmap as a way to view the thumbnails while keeping the left pane same resolution?  I know it is a silly and huge request, but I thought it was really useful and fun. :)

View at 20%
![zoom-at-20-percent](https://user-images.githubusercontent.com/1787238/39382001-e47322a2-4a18-11e8-9574-db626b3614cb.png)

Adjustable view bar in bottom right of Vivaldi/Opera
![zoom-bar](https://user-images.githubusercontent.com/1787238/39382023-fa131c84-4a18-11e8-88c6-5a34e404194e.png)

View at 280%
![super-close](https://user-images.githubusercontent.com/1787238/39381831-50b93ace-4a18-11e8-80e7-f0f397e2fc6e.png)

**Comment by sunjam** [comment]
Issue #495 scrolling would be important if users did have the option to zoom out and see many bookmarks at the same time.

**Comment by jancborchardt** [comment]
Keep in mind that every different view requires maintenance and testing. So a second way of viewing (and these are more than just a second view) requires double the maintenance and testing.

There’s certainly other things to focus on first. ;)

**Comment by marcelklehr** [comment]
>  I know it is a silly and huge request

Agreed :)
