### ISSUE TITLE
Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script

### ISSUE THREAD

**Issue by damko** [nextcloud/bookmarks#489]
heads up: if you are on ubuntu 16.04 be sure to update nodejs (official package has 4.2.6) to a more recent version (like 8.11.2) by updating the apt repo (ex. `curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh` ) otherwise you get this error 

> Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'

when running `npm install` and it fails.

**Comment by marcelklehr** [comment]
The README links to nodejs.org, which recommends using nodesource when selecting [Download > installing via package manager](https://nodejs.org/en/download/package-manager/).
