### ISSUE TITLE
Feature request: add "search" endpoint

### ISSUE THREAD

**Issue by damko** [nextcloud/bookmarks#492]
for [freedommarks](https://github.com/damko/freedommarks-browser-webextension) I need a "search by URL" API endpoint to check if the URL is already present in the database so that I can retrieve the previous record and display the recorded info to the user.
I can take care of this task but I need some agreement with the developers who are actively developing the app because I see several changes happening and I don't want to be in the way.

**Comment by marcelklehr** [comment]
Sounds like a good idea. There is already a method that covers this functionality [in the bookmarks class](https://github.com/nextcloud/bookmarks/blob/master/controller/lib/bookmarks.php#L136) which can be used to expose the functionality. :)

How do you imagine the endpoint to look like in the REST API?

**Comment by damko** [comment]
yes I saw that. There is also some refactoring that can be done:
addBookmark() 
* line 553 should be ->is_duplicated() which returns ID
* line 601 should be -> create_bookmark() (most likely private method)

For the endpoint:
route "search" or "search_by_url" 
```
# roughly
function search($url){
if($id = $this->is_duplicated(){
return $this->findUniqueBookmark($id);
} else {
return false
}
```

**Comment by marcelklehr** [comment]
I think it would be beneficial, if that functionality would be merged into the existing querying endpoint, e.g. something like `GET bookmark?url=foo.com`. What do you think?

**Comment by damko** [comment]
@marcelklehr that also works for me but I would still add a private method with the logic and then I would call that method from getbookmarks(). Basically same thing as I said before but without a specific route, right?

**Comment by marcelklehr** [comment]
That would probably make sense. It should probably still return an array to be compatible with the otput of the other params. Perhaps it would be ideal to integrate the `user` param as well: https://github.com/nextcloud/bookmarks/blob/master/API.md#query-bookmarks The other params of the endpoint don't make much sense as there's very likely only one bookmark per URL (which is not always true, but that should be the assumption.)

**Comment by damko** [comment]
Generally speaking it looks like the whole get_bookmarks need a refactory, right? ... 
However, I don't get the "user" part. Shouldn't the user be identified upon authentication?

About the uniqueness of the record, yes, I don't expect duplicates because is_duplicated is triggered before saving. There is a chance thought that there are duplicates because time ago there was a bug in the bulk importer (if I remember well) which would allow duplicated URLs. Maybe someone still have duplicates hanging around. Therefore I'd select just the 1st returned records

**Comment by marcelklehr** [comment]
As a workaround, until this is implemented, it's possible to search for the URL and filter out every occurrences of bookmarks where the URL is not the (full) bookomark URL. You're then left with (hopefully only one) bookmark(s) that link to the URL you searched for.
