### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by exekutive** [nextcloud/bookmarks#494]
Fairly self explanatory. I'm surprised nobody suggested it yet.

**Comment by marcelklehr** [comment]
duplicate of #32 #64 #297 ;)

**Comment by exekutive** [comment]
Sorry, I guess I should have searched closed issues as well.

**Comment by marcelklehr** [comment]
No problem :D

**Comment by damko** [comment]
@exekutive as a temporary solution you can use my Firefox [addon](https://addons.mozilla.org/en-US/firefox/addon/freedommarks/) for searching bookmarks
