### ISSUE TITLE
Deleting inexistent bookmark via ...rest/v2/bookmark/ throws http-code 400

### ISSUE THREAD

**Issue by ionum** [nextcloud/bookmarks#498]
### Steps to reproduce
1. Delete bookmark on client1 and sync
2. Delete same bookmark on client2 and sync

### Expected behaviour
server should throw 404 "Not found"
a log entry

### Actual behaviour
server throws http-code 400 which is "bad request"
no log entries at all

apache-log-entry:

xxxx - xxxx [31/May/2018:10:19:01 +0200] "DELETE /index.php/apps/bookmarks/public/rest/v2/bookmark/403 HTTP/1.1" 400 2 "-" "Mozilla/5.0 (Windows NT 6.1; rv:59.0) Gecko/20100101 Firefox/59.0"

if i create manually a bookmark with id 403 in the db, i get

xxxx - xxxx [31/May/2018:10:22:03 +0200] "DELETE /index.php/apps/bookmarks/public/rest/v2/bookmark/403 HTTP/1.1" 200 20 "-" "Mozilla/5.0 (Windows NT 6.1; rv:59.0) Gecko/20100101 Firefox/59.0" 

nextcloud version: 13.0.2
bookmarks version: 0.11.0

**Comment by marcelklehr** [comment]
In the upcoming version this was fixed to return a 200 status, as the state of the DELETE operation is as expected, regardless of whether the item existed in the first palce or not: Afterward it definitely doesn't exist. See https://github.com/nextcloud/bookmarks/pull/462

**Comment by ionum** [comment]
It seems that you patch was not merged. Problem persists...
