### ISSUE TITLE
oc_bookmarks already exist

### ISSUE THREAD

**Issue by TheRealSagrotan** [nextcloud/bookmarks#499]
Steps to reproduce
1. Enter 'Apps' 'Disabled Apps'
2. Enable 'Bookmarks'

Expected behaviour
Install 'bookmarks' and change icon to 'enabled'

Actual behaviour
An exception occurred while executing 'CREATE TABLE `oc_bookmarks` (`id` INT AUTO_INCREMENT NOT NULL, `url` VARCHAR(4096) DEFAULT '' NOT NULL, `title` VARCHAR(4096) DEFAULT '' NOT NULL, `user_id` VARCHAR(64) DEFAULT '' NOT NULL, `description` VARCHAR(4096) DEFAULT '' NOT NULL, `public` SMALLINT DEFAULT 0, `added` INT UNSIGNED DEFAULT 0, `lastmodified` INT UNSIGNED DEFAULT 0, `clickcount` INT UNSIGNED DEFAULT 0 NOT NULL, PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_bookmarks' already exists

Operating system**:
dietpi Linux

Web server:**
Apache2

Database:**
Maria
**PHP version:**

Nextcloud version:** (see Nextcloud admin page)
Nextcloud v 13.0.2

Bookmarks version:** (see Nextcloud apps page)
try to install 0.11

**Comment by marcelklehr** [comment]
Is it possible to remove the app and reinstall?

**Comment by TheRealSagrotan** [comment]
Tried that now.  Went to the Your Apps section and removed "bookmarks".  Went to the store and clicked on "enable".  Same error message.  Seems like I need to manually remove it on the command line. Any thoughts?

**Comment by marcelklehr** [comment]
This looks like a nextcloud bug: https://github.com/nextcloud/server/issues/8431

**Comment by TheRealSagrotan** [comment]
Hey Marcel - I figured it out in the end.  Here is what I did:
1. Drop table oc_bookmarks
2. Enabled "bookmarks" but got the "Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes" error
3. Modified mysql my.cnf to add Innodb config information:
innodb_large_prefix            = ON
innodb_file_format_check       = 1
innodb_file_format             = Barracuda                           
innodb_buffer_pool_size        = 128M                              
innodb_buffer_pool_instances   = 8                                  
innodb_file_per_table          = 1                                   
innodb_flush_log_at_trx_commit = 2                               
innodb_log_buffer_size         = 8M                                  
innodb_log_file_size           = 256M  
4. Drop table oc_bookmarks
5. Enable Bookmarks

That did it

**Comment by marcelklehr** [comment]
@TheRealSagrotan uh. I'm glad it works for you now. :sweat_smile:
