### ISSUE TITLE
No thumbnails, no search button

### ISSUE THREAD

**Issue by hubitor** [nextcloud/bookmarks#501]
I'm testing nextcloud on docker. I have installed the latest version as well as the bookmarks app but the search button does not appear for this app (it does for some other apps such files or contacts). I have also added some URLs but there is no thumbnail view.

**Comment by hubitor** [comment]
Hi. Thanks! OK, but how can I install it? I see only the option to download the archive.

**Comment by marcelklehr** [comment]
Yup, that's an unfortunate obstacle. You should be able to install it by dropping the unpacked files into the `custom_apps` (or simply `apps` if the former is missing) folder of your nextcloud.
