### ISSUE TITLE
View bookmarks in Mindmaps app

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#507]
[Here is a link to the issue in Nextcloud Mindmaps app](https://github.com/splitt3r/mindmaps/issues/50).  It would be very useful to view Bookmarks as a mindmap.  Posting here for reference.

> Once there is url support ala issue #40, it would be awesome to mindmap view Nextcloud Bookmarks marcelklehr via their Rest-api. Bookmarks currently support a title, url, tags, folders, and descriptions. Unsure if this request would pertain to Bookmarks issue #134.

- View and organize Bookmarks as a mindmap
- Import to node from Bookmark
- Export from node to Bookmark

**Comment by marcelklehr** [comment]
Thanks for the reference!

AFAICT, the ball lies in their court, as we provide the necessary APIs and they have the UI that needs to be taught how to use them.
