### ISSUE TITLE
How to install from the app store in Nextcloud 13

### ISSUE THREAD

**Issue by PabloCastellano** [nextcloud/bookmarks#509]
According to the README, this app can be installed from the app store.
However, I'm using Nextcloud 13.0.4 and I don't see the Bookmarks app there.

Is it outdated or am I missing something?

**Comment by marcelklehr** [comment]
The bookmarks app should be in the category 'Organization' or similar. You will not see the new UI in the current version, though.

**Comment by PabloCastellano** [comment]
@marcelklehr Thanks! It is there. I've submitted a patch to make it clearer in the README
