### ISSUE TITLE
Tag suggestions / Make it easier to filter for tags

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#515]
The old UI had a drill-down feature that only displayed tags that actually provided results together with the current tag selection. Clearly, dynamic state changes in the sidebar were a bad idea, however, I think the ability to see additional tags that can refine the current result was not, especially when you have lots of bookmarks.

1. Simplify refining of tag selections: My idea would be to add a top bar for displaying refining tag suggestions, but I defer to @jancborchardt for the best UX on this :D (I think we even spoke about this once, but alas my memory...)

2. With 400+ tags in a simple scrollable list in the sidebar, tags lose their advantages, because you now have to visually scan lots of tags instead of lots of bookmarks. One advantage of the old drill-down field, was the ability to search for tags by keystroke. Perhaps it is worth bringing back this ability?

**Comment by marcelklehr** [comment]
So, Obama already agrees. That's great, I guess :D 

@nextcloud/designers Any input?

**Comment by skjnldsv** [comment]
A multiselect with a search input?

**Comment by marcelklehr** [comment]
> multiselect with a search input

I'm not sure about that. we had that before and it was confusing. Mostly, because the list of tags was drilled down by applicable tags based on the ones already selected. I was thinking of a search input just to search within the tag list in the side bar.

**Comment by tossican** [comment]
I generally use the already existing search function at the top of the page. It works great! "anime video stream" (each are separate tags) happily brings up the links to the anime series I am currently watching on the various services I use.. The search box is also 'live' so the list of links changes as you type.. I'm not entirely sure how the "multiselect with a search input" idea improves on this, perhaps I am missing something.

 Sadly, being new here, I didn't get to experience the prior drill down system or the "dynamic state change" issue.. However, such a function sounds amazing to me! Assuming it is what I think. i.e. you select the tag "web dev" and the list then becomes "CSS", "PHP", "HTML", "Guide", "Tutorial", "Reference" (etc) based on what tags are also on the "Web dev" tagged content.. A website I use does this, taking it a step further to add a "+" and "-" next to each tag, so you can include, or even exclude the tags from the current tag list and content filters.

One other thing I considered would be some sort of meta-tagging.. For example, the meta-tag "Web dev" could have "PHP", "CSS", "JaveScript", etc added to it.. The user then would not need to specifically add "Web dev" as a tag to content with the other tags. It would instead be implicit.. This would be one-way of course, so a search for "web dev" would bring up all content with the associated tags, while a search for "PHP" would only bring up content with the PHP tag.

Lastly, tho of less usefulness, would be tag synonyms.. For example, define "Manual", "Guide", and "Reference" to be synonyms.. This came to mind as  I was close to finishing the tag process on my collection. The whole process took me a few days, and once done, I realized I used a variety of terms to mean the same things.. I am now going through and trying to consolidate such tags. Trying to make a "standardized" tagging system.. Only time will tell if I remember which tags I chose to use come six months from now.

**Comment by jancborchardt** [comment]
As @tossican already mentioned, this is something that search is perfect for. No additional interface or elements, just something people already know. :slightly_smiling_face:  I’d really say this is the way to go and we need to prevent ourselves from offering too specific and complicated ways of navigating. :)

- Clicking on a tag shows all the elements with that tag
- Clicking on another tag shows the elements with that other tag
- If you want to combine or do anything more advanced – search, as that should simply search through everything, content and tags.

**Comment by marcelklehr** [comment]
While I see a potential for refining combined tag queries, I do get that we need to keep things simple. Thanks for your input, everyone :)

**Comment by tategriffin** [comment]
![nextcloud-tag-sort](https://user-images.githubusercontent.com/6013805/189549942-78f5e95f-46a8-4c38-8f38-935322c2bc03.png)
I would like to see the tags sorted in some order more logical than count, preferably with an option to change similar to how the bookmark sorting is done (see attached). Bookmarks are searchable and sortable, but tags are currently only searchable. The arguments for making bookmarks sortable seem to apply equally to tags.

**Comment by Jurik-Phys** [comment]
> If the tags are in alpha order
I've been asking for a long time about the ability to sort a column with tags in alphabetical order (see 
https://github.com/nextcloud/bookmarks/issues/563)
