### ISSUE TITLE
Exception occurs while creating tables during install\enabling bookmarks app

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#521]
I previously ran an older version of Nextcloud with no manually installed apps.  I migrated to a new server using the old database and files.  Migration went fine.  

After installing v13.0.4, I decided to add the bookmarks app.

When I click the enable button, I get this error:
`An exception occurred while executing 'CREATE TABLE `oc_bookmarks_tags` (`bookmark_id` BIGINT DEFAULT NULL, `tag` VARCHAR(255) DEFAULT '' NOT NULL, UNIQUE INDEX bookmark_tag (`bookmark_id`, `tag`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

From problems with other apps during migration, I've noticed that I've had to modify "VARCHAR(255)" to "VARCHAR(180) after installation.  However, I've not found how I can modify this in the bookmark tables such to get the bookmark app installed in such a way that I can alter the tables after the fact.  Any help would be appreicated.

**Comment by vxdIOT** [comment]
Resolved.  

I dropped the bookmark(s) tables.  Then where I had nextcloud installed, I edited apps/bookmarks/appinfo/database.xml.  I changed the tag field from a length of 255 to 180.  Then went back into the web app installer and clicked enable again and everything is installed now.

**Comment by marcelklehr** [comment]
Since you are using  utf8mb4_bin you may want to adjust your configuration accordingly. Have a look at this guide: http://mechanics.flite.com/blog/2014/07/29/using-innodb-large-prefix-to-avoid-error-1071/
