### ISSUE TITLE
Need Help continuing Android app

### ISSUE THREAD

**Issue by theScrabi** [nextcloud/bookmarks#526]
Hello,

I need help continuing the [OCBookmark App](https://gitlab.com/derSchabi/OCBookmarks). I currently have not much time to take care about this app since I have all heads full handling other Projects like NewPipe. This Project may need a new maintainer in order to continue.

An important Issue open in this App atm is that it's not possible on android 7+ to accept custom certificates when they are installed in the Android certificate Management. Thus someone had to add a feature so custom certificates can be accepted directly through the app.

Here is a list issues the app has:
- Accept custom certificates through the app itself
- Make app compatible with new tree representation of tags
- Save user credentials using Android AccountManager

The app is currently available against payment in Playstore. If it gets a new Maintainer, I will make it available for free. Also I will make sure to Sign and release the apk.

**Comment by marcelklehr** [comment]
Hi @theScrabi 

I didn't know you also built NewPipe! Two awesome apps, I use almost daily :)
I'm afraid I won't be able to overtake maintainership of OCBookmarks, as I have my hands quite full already. You could also try asking around on the nextcloud forums: https://help.nextcloud.com

**Comment by theScrabi** [comment]
Thank you.
All right :), if you find something however pls notify me :)

**Comment by marcelklehr** [comment]
@theScrabi As [mentioned on the nextcloud forum](https://help.nextcloud.com/t/ocbookmarks-app-android-seeking-new-maintainer/34611) @DasBiswajit offers to take on mainainership of the android app. :tada: :1st_place_medal:

**Comment by dasbiswajit** [comment]
Hello @theScrabi @marcelklehr 
Would you please add me to the [project](https://gitlab.com/derSchabi/OCBookmarks)

**Comment by theScrabi** [comment]
I'll add you.

**Comment by dasbiswajit** [comment]
Username [gitlab](https://gitlab.com/bisasda)

**Comment by dasbiswajit** [comment]
Thanks I got the access. I will do the next releases.

**Comment by marcelklehr** [comment]
@dasbiswajit Awesome! Thank you for taking this on! :)

**Comment by dasbiswajit** [comment]
@theScrabi @marcelklehr no problem. I will update a new version in the play store and fdroid shortly.
