### ISSUE TITLE
v0.12 - Upgrade fails - Missing "image" & "favicon" fields in DB

### ISSUE THREAD

**Issue by TtuxX** [nextcloud/bookmarks#527]
Hi @marcelklehr and all the Bookmarks contributors team ! :)

First of all I would like to thank you for the incredible rework of the Bookmarks app you did.
It looks amazing, the visual aspect is beautiful, you all did a wonderful job, so a big thank you for this and all the time you spent improving this useful app !! :)

Referring to issue https://github.com/nextcloud/bookmarks/issues/522, I am reporting a small bug during the migration process from previous Bookmarks app official version (version 0.11.0). I don't know if it really is a "bug" or just something that went wrong on my side.

 
You will find the issue's details hereafter.

Once again, thank you for the great job you did on this application and for your time =)

-----------

### Steps to reproduce
1. You must have a Nextcloud instance with Bookmarks previous official release (version 0.11.0)
2. Install the new Bookmarks app v0.12.0-rc2 as described in the Readme's install process
3. Upgrade using command line (occ upgrade)

### Expected behaviour
New tables 'image' and 'favicon' should be created if not already present at the begining of the migration process.

### Actual behaviour
Migration fails during upgrade from previous official release.

New fields `image` and `favicon` are missing from table `oc_bookmarks` during bookmarks recreation repair step, making the MySQL/MariaDB migration commmand abort with a message like this:

_SQLSTATE[42s22]: Column not found: 1054 Unknown column 'favicon' in 'field list'_

**Solution:** Altering table `oc_bookmarks` and adding columns `image` (TEXT) and `favicon` solves the issue and the migration process finishes without any other issue. :)

### Server configuration

**Operating system**: Linux

**Web server:** Nginx

**Database:** MariaDB

**PHP version:**PHP 7.1

**Nextcloud version:** 13.0.4

**Bookmarks version:** v0.12.0-rc2

**Updated from an older Nextcloud or fresh install:** Updated

**Comment by marcelklehr** [comment]
Hey

Thanks for the kind words! :) Did you disable the app before and enable after updating? that might have triggered the db migration.

**Comment by TtuxX** [comment]
You are right, should have followed https://github.com/nextcloud/bookmarks/issues/522 instead of Readme. Would it be relevant to include a note about migrating from previous version in the Readme install section ? Closing as non-issue, than you ! :)
