### ISSUE TITLE
v0.12 - Cannot scroll tags list

### ISSUE THREAD

**Issue by TtuxX** [nextcloud/bookmarks#528]
Referring to tests for issue #522

### Steps to reproduce
1. Install v0.12.0-rc2
2. Have many bookmark tags
3. Issue while trying to scroll the tags list

### Expected behaviour
User should be able to scroll the tags list

### Actual behaviour
It is currently not possible for user to scroll the tags list

### Client configuration
**Browser:** tested on Firefox (desktop and mobile) & Chromium

### Solution

- In section `.tags-management ` of CSS file `/css/bookmarks.css`, replace rule `overflow-y: auto;` with `overflow-y: scroll !important;`

Works fine for me on Firefox (desktop and mobile) & Chromium after changing this rule; I don't know if anyone else is experimenting the same issue?

**Comment by marcelklehr** [comment]
Confirmed and fixed. Thanks :)

**Comment by marcelklehr** [comment]
@TtuxX Can you reproduce https://github.com/nextcloud/bookmarks/issues/500 ?

**Comment by TtuxX** [comment]
@marcelklehr Replying you on issue #500.
