### ISSUE TITLE
Tumbnails: Actual Screenshots?

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#529]
Re: #522 

> The only visible "issue" I do easily see at the moment (on my own bookmarks), is the one of issue #501, regarding thumbnails/website previews. For some sites it works, for some other (the majority for me), it does not.
> I know it might be a lot of work, but.... given that previews have quite an important role in your new bookmarks application layout, what about the idea of imitating/implementing code from Marius Wieschollek, the maintener of the nextcloud Passwords app ? :))  (https://github.com/marius-wieschollek/passwords)
> His app uses websites such as as https://www.screenshotapi.io/ for screenshots, and is very reliable :)
> _Screenshot of the Password app in Nextcloud settings page:_
> ![image](https://user-images.githubusercontent.com/6570830/43004643-b241bbae-8c30-11e8-9969-de142de25fb9.png)

-- @TtuxX, rescued from https://github.com/nextcloud/bookmarks/issues/500#issuecomment-406601467

**Comment by marcelklehr** [comment]
Do the favicons work for you at least?

We thought about using a public API for retrieving screenshots, but having that as a default would seriously compromise the privacy of our users. I'm not sure it would be worth the time to further improve the current aproach, though, so being able opt-in to using a third-party service would probably be cool, and wouldn't even leave the user without any visuals if they don't opt in.

**Comment by TtuxX** [comment]
Unfortunately no, favicons are missing on 2/3 of my bookmarks (with websites that actually have favicons) :/

I agree for privacy. Opting-in by default would be a wrong idea.
Ideally, it could be fantastic to have the choice, on a case-by-case basis, to generate a screenshot using a public api thanks to a "generate screenshot" button on each properties tab :)

**Comment by marcelklehr** [comment]
https://github.com/nextcloud/bookmarks/pull/531 adds support for a screenshot API and fixes the favicon issue

I'm thinking about only using the screenshots when the default method doesn't yield any results, as I often prefer the previews for sites like youtube which in this case are a direct copies of their video preview over a screenshots of the complet page. Any thoughts on that?

**Comment by TtuxX** [comment]
Wow your reactivity is amazing, thank you for these improvements !!

I did not have time to view the thumbnails display of v0.12.0 for YouTube as I didn't have direct videos bookmarks, but I tried and it looks very nice ! I completely agree with the behavior and logic you describe. :)

**Comment by marcelklehr** [comment]
This is now available in the latest release candidate -- happy testing ;)
