### ISSUE TITLE
Open/close card properties on click

### ISSUE THREAD

**Issue by TtuxX** [nextcloud/bookmarks#530]
Hello @marcelklehr, just a small fluidity improvement suggestion. :)

What about **clicking on bookmark card to directly open/close properties** in the same way that clicking on a tag (on bookmarks which have several tags) selects the one we click on ?

For now tag description is not visible at first sight like that was the case in previous version, and requires two clicks to be visible (_>popovermenu>properties_), slowing-down the fluidity for user to get the information.

That way, if user specifically clicks on bookmark link, it opens-up link, and if he clicks more generally on card, it opens-up/closes its properties in a more intuitive and versatile way ? :)

**Comment by marcelklehr** [comment]
This is a good idea, I had that implemented once but it got lost during refactoring somehow.

**Comment by TtuxX** [comment]
Thank you @marcelklehr ! :)

Do you know if it could also be possible/a good idea to close the card properties panel the same way it has been opened-up, with a click again on the card ?

If you click once on the card, panel opens-up; but if you click again on it, it currently does not close the properties panel back, and you have to move the mouse pointer to the panel's cross to close it
