### ISSUE TITLE
Feature request: easier sidebar closing & thumbnail resizing

### ISSUE THREAD

**Issue by meepiquitous** [nextcloud/bookmarks#532]
I've followed the instructions of #522 and noticed that

* The 'close' button of the sidebar is hard to see on a black thumbnail. Would it be possible to hide it when a background element is clicked?

* On a low-resolution display, the thumbnails can be quite large. Would it be feasible to have an option to pick a thumbnail size?

**Comment by marcelklehr** [comment]
re 1) yes, that's on my list.

2) Could you provide a screenshot? I think a setting may be overkill, but it would be interesting to see the ratio on different screen resolutions and how this could be optimized.

**Comment by TtuxX** [comment]
@marcelklehr For information, appearance on a **1366x768 pixels (361x203 millimeters)** screen _(`xdpyinfo  | grep 'dimensions:'`)_:

![image](https://user-images.githubusercontent.com/6570830/43169472-7d6fa75a-8fa1-11e8-9a80-920769eb14e3.png)

**Comment by marcelklehr** [comment]
Thanks the details drawer is indeed a bit clunky. The cards/tiles feel ok to me, though -- this is probably not a capture of v0.12.0-rc3 but a later, unreleased revision where I had already transitioned from cm to the magic px unit, I take it? (px, I recently learned, is more relevant for the actual device and still resolution independent...)

**Comment by marcelklehr** [comment]
> @meepiquitous would you please mind testing the latest bookmarks master code

I'll release a new release candidate soon, to make this easier as not everyone is inclined to install all the dev requirements ;)

**Comment by TtuxX** [comment]
Haha ok, perfect ^^

**Comment by marcelklehr** [comment]
@meepiquitous [v0.12.0-rc4](https://github.com/nextcloud/bookmarks/releases/tag/v0.12.0-rc4) has just been released. Please test :)

**Comment by blacs30** [comment]
For me it works a little bit too good.

# Behavior is this:
1. Click the 3 dots of a bookmark and select details || click on the white transparent background of the bookmark label
2. the sidebar opens
3. click anywhere (including the description box, tags box, link edit box) on the sidebar and it closes

Nextcloud 13.5, bookmarks rc4
Firefox 61.0.1 
Safari 11.1.2
macOS 10.13.6

**Comment by meepiquitous** [comment]
Thanks, everyone.

Regarding the thumbnail sizing, I wanted to apologize. I didn't notice I was running dpi scaling (Windows 10, 125% @ 1280x1024), which led to only two rows of thumbnails being shown. 

Screenshot PC, [sidebar closed](https://user-images.githubusercontent.com/39339889/43370907-dffd9aaa-9387-11e8-904b-dc3f12a4a73e.png)

Screenshot PC, [sidebar open](https://user-images.githubusercontent.com/39339889/43370914-e7e1e5e6-9387-11e8-8d23-2d788df7adce.png)


However, would it be possible to have the option to switch between thumbnail- and old/text ui? This would make it easier to find something on mobile browsers, especially because text is hard to read in 'desktop mode'. 

Bromide/Chromium browser on Android showing

Screenshot of [old UI/v0.11.0](https://user-images.githubusercontent.com/39339889/43370929-25f0230c-9388-11e8-872f-af0f16349f50.png)

Screenshot of [v0.12.0-rc4](https://user-images.githubusercontent.com/39339889/43370933-30ea9850-9388-11e8-91c1-19b02582e1c3.png)

Screenshot of [v0.12.0-rc4 in 'desktop mode'](https://user-images.githubusercontent.com/39339889/43370935-3ba492be-9388-11e8-8846-81d8ad0aafa3.png)

Regarding the finished builds vs building from source code - it's not necessarily a matter of inclination or lack of will; as a novice, I ran into fringe issues 90% of the way and gave up on several occasions, after hours of troubleshooting things like timeouts in npm or key size errors in mariadb.. so the builds are much appreciated.

**Comment by marcelklehr** [comment]
@blacs30 Thanks, I've just fixed this in the master branch, so it'll be in the next release

@meepiquitous 

> Regarding the finished builds vs building from source code - it's not necessarily a matter of inclination or lack of will; as a novice, I ran into fringe issues 90% of the way and gave up on several occasions, after hours of troubleshooting things like timeouts in npm or key size errors in mariadb.. so the builds are much appreciated.

Yeah, that's what I mean. Building software without prior knowledge of the components involved potentially takes a lot of time. Plus, builds area always nice :v: 

> would it be possible to have the option to switch between thumbnail- and old/text ui

I won't be maintaining two views, I'm afraid, but it might be a good idea to shrink the bookmark tiles on mobile so they don't appear too bloated.

**Comment by meepiquitous** [comment]
Alright, thanks again. 

I'm new to this, so.. may i close this issue?

**Comment by marcelklehr** [comment]
> may i close this issue?

Nah, I usually leave things open until a commit has landed in the master branch and/or has been released.

> but it might be a good idea to shrink the bookmark tiles on mobile so they don't appear too bloated.

What do you people think about this:

![bookmarks - nextcloud](https://user-images.githubusercontent.com/986878/43415996-5cfc885e-9437-11e8-93e6-41f6bad1a5e0.png)

(I shrank the tiles, the favicon, the title font size and made the title wrap around the favicon to make more room for the text)

**Comment by TtuxX** [comment]
It looks great!

**Comment by marcelklehr** [comment]
Awesome, then we can close this :) :tada:
