### ISSUE TITLE
v0.12.0-rc3 - Overhaul Previews - API key not saved & Screeenly.com screenshots not generated

### ISSUE THREAD

**Issue by TtuxX** [nextcloud/bookmarks#533]
**(_Referring to issue https://github.com/nextcloud/bookmarks/issues/529, solved by PR https://github.com/nextcloud/bookmarks/pull/531_)** _-- continuation of conversation here._

Thank you very much @marcelklehr for your work, looks great !! :)

Unfortunately I am having some issues, new screenshot previews implementation do not work for me at the moment, either for already existing or new bookmarks (I don't know if this problem is on my side):
- 3rd-party Screeenly.com API key does not appears to be saved in the app settings,
- http://screeenly.com/api/v1/fullsize returns error 400, telling bookmarks app makes bad requests

**Details of the first issue**:
_(tested on both Firefox & Chromium, mobile & desktop)_

- 1: Download v0.12.0-rc3
- 2: Setup the release (`composer install; npm install; npm run build`)
- 3: Register on https://screeenly.com (points me to https://staging.screeenly.com) and generate API key
- 4: Insert API key in Bookmarks app new settings page, in the field `Screenly API key` and press enter
- 5: App asks for password to save the new API key and supposedly saves it; a green validation tick then displays close to `Screenly API URL` field
- 6: Refresh the page to check if API key has been saved
- 7: Field `Screenly API key` displays the same content as `Screenly API URL` field, that is to say "http://screeenly.com/api/v1/fullsize", instead of the API key. In database, `previews.screenly.token` contains value "http://screeenly.com/api/v1/fullsize".

If I then insert API key in the configvalue of `previews.screenly.token`, it displays well in the field and previews fetching now seems ready to operate.

**Details of the second issue**:
_(tested on both Firefox & Chromium, mobile & desktop)_

Now API key is set, but returning to the bookmark app, previews are not getting generated and checking the logs, I then have 2 types of errors/warnings constantly coming back in the app logs:

- 1st message:
Level: **Warning**; App: **Bookmarks**
`GuzzleHttp\Exception\ClientException: Client error response [url] http://screeenly.com/api/v1/fullsize [status code] 400 [reason phrase] Bad Request in /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89 Stack trace: #0 /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(32): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response)) #1 /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete') #2 /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent)) #3 /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) #4 /var/www/nextcloud/apps/bookmarks/vendor/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array) #5 /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) #6 /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL) #7 /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure)) #8 /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) #9 /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/Client.php(150): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request)) #10 /var/www/nextcloud/apps/bookmarks/controller/lib/previews/screenlypreviewservice.php(109): GuzzleHttp\Client->post('http://screeenl...', Array) #11 /var/www/nextcloud/apps/bookmarks/controller/lib/previews/screenlypreviewservice.php(84): OCA\Bookmarks\Controller\Lib\Previews\ScreenlyPreviewService->fetchScreenshot('http://mywiki.w...') #12 /var/www/nextcloud/apps/bookmarks/controller/rest/internalbookmarkcontroller.php(215): OCA\Bookmarks\Controller\Lib\Previews\ScreenlyPreviewService->getImage(Array) #13 [internal function]: OCA\Bookmarks\Controller\Rest\InternalBookmarkController->getBookmarkImage(108) #14 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array) #15 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(91): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Bookmarks\Controller\Rest\InternalBookmarkController), 'getBookmarkImag...') #16 /var/www/nextcloud/lib/private/AppFramework/App.php(115): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Bookmarks\Controller\Rest\InternalBookmarkController), 'getBookmarkImag...') #17 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('InternalBookmar...', 'getBookmarkImag...', Object(OC\AppFramework\DependencyInjection\DIContainer), Array) #18 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array) #19 /var/www/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array) #20 /var/www/nextcloud/lib/base.php(999): OC\Route\Router->match('/apps/bookmarks...') #21 /var/www/nextcloud/index.php(42): OC::handleRequest() #22 {main}`

- 2nd message:
Level: **Error**; App: **Index**
`GuzzleHttp\Exception\RequestException: cURL error 51: SSL: no alternative certificate subject name matches target host name 'www.XYZ.com'
    /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
    /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/nextcloud/apps/bookmarks/vendor/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)
    /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
    /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
    /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
    /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
    /var/www/nextcloud/apps/bookmarks/vendor/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
    /var/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Readers/HttpReader.php - line 95: GuzzleHttp\Client->get('https //www.fre...', Array)
    /var/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Parsers/BaseParser.php - line 65: Marcelklehr\LinkPreview\Readers\HttpReader->readLink(Object(Marcelklehr\LinkPreview\Models\Link))
    /var/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Parsers/HtmlParser.php - line 111: Marcelklehr\LinkPreview\Parsers\BaseParser->readLink(Object(Marcelklehr\LinkPreview\Models\Link))
    /var/www/nextcloud/apps/bookmarks/vendor/marcelklehr/link-preview/src/Client.php - line 62: Marcelklehr\LinkPreview\Parsers\HtmlParser->parseLink(Object(Marcelklehr\LinkPreview\Models\Link))
    /var/www/nextcloud/apps/bookmarks/controller/lib/linkexplorer.php - line 23: Marcelklehr\LinkPreview\Client->getPreview('general')
    /var/www/nextcloud/apps/bookmarks/controller/lib/previews/defaultpreviewservice.php - line 71: OCA\Bookmarks\Controller\Lib\LinkExplorer->get('https //www.fre...')
    /var/www/nextcloud/apps/bookmarks/controller/lib/previews/faviconpreviewservice.php - line 45: OCA\Bookmarks\Controller\Lib\Previews\DefaultPreviewService->scrapeUrl('https //www.fre...')
    /var/www/nextcloud/apps/bookmarks/controller/rest/internalbookmarkcontroller.php - line 233: OCA\Bookmarks\Controller\Lib\Previews\FaviconPreviewService->getImage(Array)
    [internal function] OCA\Bookmarks\Controller\Rest\InternalBookmarkController->getBookmarkFavicon(153)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Bookmarks\Controller\Rest\InternalBookmarkController), 'getBookmarkFavi...')
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Bookmarks\Controller\Rest\InternalBookmarkController), 'getBookmarkFavi...')
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('InternalBookmar...', 'getBookmarkFavi...', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/nextcloud/lib/base.php - line 999: OC\Route\Router->match('/apps/bookmarks...')
    /var/www/nextcloud/index.php - line 42: OC handleRequest()
    {main}`

I hope my testing report is not too messy...

Do not hesitate to let me know if I can provide you with any other kind of detail/information.

Thank you again for your time! :)

**Comment by marcelklehr** [comment]
Nice catch! Just pushed a fix for the admin settings :see_no_evil: 

Ah, https://staging.screeenly.com/ is not the production version. For some reason the production version doesn't seem to have SSL enabled. Try signing up with http://screeenly.com or using staging.screeenly.com/... in the API URL field

**Comment by TtuxX** [comment]
Thank you ! :)

Regarding Screeenly, connecting with Github on https://secure.screeenly.com/ throws the following error for now: _"Whoops, looks like something went wrong"_
Similarly, accessing API https://staging.screeenly.com/api/v1/fullsize throws the error: _"Whoops, looks like something went wrong"_

I guess Stefan Zweifel (founder of screeenly) might be doing some migrations for now; I'll have to test later on when service will be up & running again.

**Comment by marcelklehr** [comment]
https://secure.screeenly.com/ has the same database as http://screeenly.com, but you cannot sign up with github on that domain, because github only knows about the latter.

**Comment by TtuxX** [comment]
Ok :)

_(just for info, https://staging.screeenly.com/dashboard and https://staging.screeenly.com/dashboard do not seem to share the same database as it shows me different API keys I created with the same account)._

Now using https://staging.screeenly.com/api/v1/fullsize in API URL field, I would say I have previews/images for about half of my bookmarks :)

However, I get 2 types of error messages that are regularly coming back:

- Still the 2nd error message I posted hereabove, which occurs for one specific bookmark host. I don't know how "bad" it is and if it breaks preview generation (preview is actually not generated)

- A new error: Syntax error, malformed JSON - Happens for many bookmarks
Level: **Error**; App: **Index**
`GuzzleHttp\Exception\ParseException: Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON
/var/www/nextcloud/apps/bookmarks/controller/lib/previews/screenlypreviewservice.php - line 112: GuzzleHttp\Message\Response->json()
/var/www/nextcloud/apps/bookmarks/controller/lib/previews/screenlypreviewservice.php - line 84: OCA\Bookmarks\Controller\Lib\Previews\ScreenlyPreviewService->fetchScreenshot('https //www.cgs...')
/var/www/nextcloud/apps/bookmarks/controller/rest/internalbookmarkcontroller.php - line 215: OCA\Bookmarks\Controller\Lib\Previews\ScreenlyPreviewService->getImage(Array)
[internal function] OCA\Bookmarks\Controller\Rest\InternalBookmarkController->getBookmarkImage(33)
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Bookmarks\Controller\Rest\InternalBookmarkController), 'getBookmarkImag...')
/var/www/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Bookmarks\Controller\Rest\InternalBookmarkController), 'getBookmarkImag...')
/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('InternalBookmar...', 'getBookmarkImag...', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/nextcloud/lib/base.php - line 999: OC\Route\Router->match('/apps/bookmarks...')
/var/www/nextcloud/index.php - line 42: OC handleRequest()
{main}`

**Comment by TtuxX** [comment]
Thanks for your help, it works quite well now :)

Some website screenshots are not working due to being heavy on JS and so on, but nothing we can really do about it.

Does the proview of https://www.webpagetest.org/ gets generated for you ? Screenshot works on Screeenly, but does not get generated on my side even if I delete it, add it again and wait for a long time :{

**Comment by marcelklehr** [comment]
Awesome!

> Some website screenshots are not working due to being heavy on JS and so on, but nothing we can really do about it.

I can make screeenly wait longer before it takes the screenshot, so the heavier sites are ready for the flash, too. This is going to degrade the overall experience, though, as it will take longer for all previews to be loaded (at least the first time they are loaded).

> Does the proview of https://www.webpagetest.org/ gets generated for you ?

Yes, it works for me. The current implementation employs heavy caching to soften the load though, so even a negative response like a 404 or something like that is cached to avoid trying to generate the preview time and time again in cases where people have a lot of links that simply aren't previewable. I suppose it makes sense to distinguish long term unavailability vs. simple errors that might be fixed next time.

**Comment by TtuxX** [comment]
> I can make screeenly wait longer before it takes the screenshot, so the heavier sites are ready for the flash, too. This is going to degrade the overall experience, though, as it will take longer for all previews to be loaded (at least the first time they are loaded).

No, please do not worry, it nearly never happens; I just saw one preview or so that was not working, and when I tried directly using the screeenly online service, it throwed back a rendering error talking about issues with heavy JS, but it has nothing to do with your app.  :)

>Yes, it works for me. The current implementation employs heavy caching to soften the load though, so even a negative response like a 404 or something like that is cached to avoid trying to generate the preview time and time again in cases where people have a lot of links that simply aren't previewable. I suppose it makes sense to distinguish long term unavailability vs. simple errors that might be fixed next time.

Generation was really slow for all the bookmarks I had; I left the browser open for a long time and in the end it worked for me too, sorry for the bad report ❌:/
I understand; you're right yeah.
I now have images for all bookmarks :) It works perfectly well, once generated and cached, previews are loaded quite quickly. Thank you so much for your great work @marcelklehr!! :)

**Comment by marcelklehr** [comment]
Great! Thank you for testing! :tada:
