### ISSUE TITLE
Edit bookmark

### ISSUE THREAD

**Issue by ghovmand** [nextcloud/bookmarks#534]
### Steps to reproduce
1. Edit bookmark text
2. Click Save
3. Nothing happens

### Expected behaviour
That bookmark is saved with updated values

### Actual behaviour
Bookmark is not saved

### Server configuration

**Operating system**:
Linux

**Web server:**
Nginx

**Database:**
Mtysql

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13.0.4

**Bookmarks version:** (see Nextcloud apps page)
Latest

**Updated from an older Nextcloud or fresh install:**
Fresh install

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

Contacts
Calender
Bookmarks

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

#### Browser log
General
Request URL: https://ds.hovmand.org/nextcloud/index.php/apps/bookmarks/bookmark/1
Request Method: PUT
Status Code: 400 Bad Request
Remote Address: 212.178.177.228:443
Referrer Policy: no-referrer

Response headers:
Cache-Control: no-cache, no-store, must-revalidate
Content-Length: 2
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-VXFGTGJ6SVdaUWQzSUFKV3NHZUFPRy9QWnZueWhTc2pINnNaRm82anEvdz06QU9RTkdubHVBWFkyU1ROdndBYTVXeVAzVkxEQ3RINTdhc2xzVktIczhhWT0=' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
Content-Type: application/json; charset=utf-8
Date: Tue, 24 Jul 2018 10:41:05 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: lighttpd/1.4.45
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block

Request headers:
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
Connection: keep-alive
Content-Length: 119
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: oc_sessionPassphrase=9NcazbqaNX3X5n80lBk5U7SPsV2VZWsPutuv7CoZM5CTClfEbm%2BiRGGZhhQsXzO4onnHR2mzkXqyKyHU7dbMP531q17Fcw8eDwzhsWMUnP1gExI2a1Dv8cLuM%2F0FfhZW; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; ocsugjw03xdr=ighsa16i2iu83bisnufiiopj62
Host: ds.hovmand.org
OCS-APIREQUEST: true
Origin: https://ds.hovmand.org
requesttoken: dGq6NJ6iuoiSBjb7G4q5IOdGg+wt1tz0NHEfqoTgliA=:Ji/8QdXa3vnTbwfCa+uAQ6t+saUd54msQRNq6KuvzHo=
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.103 Safari/537.36
X-Requested-With: XMLHttpRequest

Form data:
record_id: 1
title: https://webmail.surftown.com
url: Webmail
item[tags][]: mail
description: Personal Webmail

**Comment by TtuxX** [comment]
Hello @ghovmand :)

Cannot reproduce on Bookmarks v0.12.0-rc3, descriptions are correctly saved for me :)
Do you see any interesting error message in Nextcloud log file ? :)


>Form data:
record_id: 1
title: https://webmail.surftown.com
url: Webmail
item[tags][]: mail
description: Personal Webmail

Might be a dumb question, but.... is it normal that URL field is "Webmail" (not an url), and Title is "https://webmail.surftown.com" ?

I don't know if you are talking about this but I have an issue however adding https://webmail.surftown.com/ bookmark: bookmark has no title and I cannot edit it as title field is not present in bookmark:

![image](https://user-images.githubusercontent.com/6570830/43138695-ff425a36-8f4f-11e8-8d4d-903f1c9c8afc.png)

**Comment by ghovmand** [comment]
Sorry made a massive mistake: Mixed up url and title, i will close, thanks for feedback

**Comment by ghovmand** [comment]
Just as a comment: There are no labels in input fields, maybe an idea so user knows what is what

**Comment by TtuxX** [comment]
@ghovmand No worries!! ^^

Are you on version v0.11.0 ? I guess this version will be deprecated soon as v0.12.0 might be released in the coming weeks, so development at the moment might be more focused on version v0.12.0

You can maybe reopen this issue changing its title as I actually stumbled into the error hereabove trying to debug your error on v0.12.0-rc3:
- No title is fetched when adding https://webmail.surftown.com as bookmark, and title cannot be manually added/changed afterwards as `title` field (above `link` field in bookmark side-panel) is not visible/editable

**Comment by TtuxX** [comment]
@marcelklehr thank you for https://github.com/nextcloud/bookmarks/commit/af5bf6e00c5338b789456d53d401a94fd939db6a (and https://github.com/nextcloud/bookmarks/commit/d89c18bdebc260dfbf0480e261eb0e2d5c874484 by the way !)
Everything works very well !! :)

Just one - really miiiinor - "issue": when clicking on `title` field, it disappears between click and text input (as you can see in screenshot below)
 
Thank you for being so reactive; do not hesitate to let me know if I can help you for testing ! :))

![peek 25-07-2018 00-10](https://user-images.githubusercontent.com/6570830/43169054-c0f515b6-8f9f-11e8-9787-8bfccc606343.gif)
