### ISSUE TITLE
Bookmarks 0.12 RC4 UI broken in Nextcloud 14 Beta 2

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/bookmarks#540]
### Steps to reproduce
1. Adding or editing bookmarks in Nextcloud 14 Beta 2 with Bookmarks App 0.12 RC4

### Expected behaviour
Adding a bookmarks only works by pressing "enter", the "+" just closes the URL window without doing anything. Editing bookmarks also doesn't work because the pane gets closed by clicking on it. The UI also looks weird because the top row is empty. The rectangle for a bookmark also only shows a color image and nothing more:

Screenshot:
![image](https://user-images.githubusercontent.com/10073629/43582944-4d684da0-965e-11e8-9eea-3cfaaeb24f38.png)

### Actual behaviour
All clickable items should work and the UI should be polished.

### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4.7

**Database:** Mysql 5.6

**PHP version:** PHP 7.2

**Nextcloud version:** 14.0 Beta 2

**Bookmarks version:** 0.12 RC4

**Updated from an older Nextcloud or fresh install:** Fresh install with old data and config

**Comment by marcelklehr** [comment]
Gnaa, they've broken the UI again :/

Thanks for reporting!

**Comment by blizzz** [comment]
@skjnldsv do you have pointers or can help out?

**Comment by skjnldsv** [comment]
@blizzz https://github.com/nextcloud/server/pull/9982 :)

**Comment by marcelklehr** [comment]
fixed by #541

**Comment by marcelklehr** [comment]
@e-alfred RC5 has just been released with this fix. :)
