### ISSUE TITLE
Bookmark description as card link tooltip

### ISSUE THREAD

**Issue by TtuxX** [nextcloud/bookmarks#543]
_[Just opening a discussion with few thoughts on bookmark descriptions accessibility]_

Bookmarks descriptions can sometimes be quite important when we add personal notes to a bookmark to recontextualise it. Currently, viewing the description requires clicking on the bookmark (which is now already way more fluid than before).

What about further improving this by also displaying bookmark's description when hovering the bookmark link ? :)  (yes, this idea directly conflicts with current tooltips simple indications)

It could be done with native tooltip, line 3 in `bookmarks/js/templates/BookmarkCard.html`, or with a more beautiful design that could be kind of inspired from https://jqueryui.com/tooltip/ ?

When hovering on the bookmark card link, the `'Open website in new tab'` tooltip could be transformed into something like: `'This is the bookmark description blablabla.... *LINE BREAK*
Click here to open website in a new tab'`

Any thoughts on this @marcelklehr ? :)

**Comment by marcelklehr** [comment]
A speech bubble tooltip would be cool. This won't make it to v0.12, though. We need to release at some point :D

**Comment by TtuxX** [comment]
Great! :)
Yes of course, I do completely agree.

**Comment by marcelklehr** [comment]
Fixed
