### ISSUE TITLE
Not possible to add a new tag after the last one was removed

### ISSUE THREAD

**Issue by poVoq** [nextcloud/bookmarks#549]
### Steps to reproduce
1. Remove last tag from bookmark
2. Try to add new tag
3. detail window slides away, not possible to add tag

### Expected behaviour
Adding a new first tag should be possible

### Actual behaviour
Not possible to add new first tag

### Server configuration
Nextcloud 13.0.5

**Bookmarks version:** (see Nextcloud apps page)
Latest (0.11?)

**Browser:**
Firefox latest
**Operating system:**
Windows10

**Comment by marcelklehr** [comment]
This should be resolved in v0.12.1
