### ISSUE TITLE
Impossible to edit tags

### ISSUE THREAD

**Issue by skadge** [nextcloud/bookmarks#550]
With bookmarks 0.12.0, the bookmark editing window slide away as soon as given focus, as visible in the screencast below:

![bug-editing bookmarks](https://user-images.githubusercontent.com/300158/44628038-b8dfd000-a930-11e8-83a2-7bacfde2f4c4.gif)

Nextcloud 13.0.4; firefox 61.

This seems related to #549 but happen even without first removing a tag.

**Comment by marcelklehr** [comment]
This should be resolved in v0.12.1
