### ISSUE TITLE
Option to keep using a list view [$5 awarded]

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/bookmarks#552]
Hello, 

First, thanks for your recent work in the app. It is great to see that it is coming back to life.

Even though I really like the new tiled view, it would be great to keep the option of the classic list view (or some kind of list view). For some of us it is easier to read.

Thoughts?

Thanks again

**Comment by nickian** [comment]
Yeah, I second that. I love the new view as well, but It'd be nice to be able to switch, similar to standard NextCloud directories between gallery/list.

**Comment by bernd-wechner** [comment]
Likewise, I'd like to see a list view. Especially with a tags column wide enough or sizeable that I can see the long tags floccus puts in place. And sort by tag:

https://github.com/nextcloud/bookmarks/issues/553

**Comment by mikec83** [comment]
100x this.  The thumbnail grid is pretty awful and not what someone needs in a bookmarks app.

**Comment by nachoparker** [comment]
> 100x this. The thumbnail grid is pretty awful and not what someone needs in a bookmarks app.

Hey let's not be mean, someone worked hard for this and I think it is pretty cool and well made. It is only that I would like to switch back and forth to the list view, depending on the situation.

**Comment by hexenring** [comment]
Also would like to be able to choose the list view. Please.

With many, many bookmarks into something like a research site on a very specific subject, the url or _full_ title, or my own description, becomes the primary way to distinguish between bookmarks.

Often on sites like Lexis or JStor the first twenty characters or so of the title are not always distinct within a subject matter collection.

For something like a "Favorites" page the grid is amazing, though, and I do like it better for my daily reads.

**Comment by IzzySoft** [comment]
Nice as it looks, if you have many bookmarks using the same tag, a list view (whithout the background thumbnails) would make it much easier to find the one you're after: faster loading, less scrolling.

And while on it, please don't forget a "date added" column: the date is stored in the DB, but not shown to the user anywhere. If you know when about you've added something, this would be very helpful.

Nothing wrong with tiles, but please give us the choice. And then either remember it, or let the user define one (grid or list) as default.

**Comment by mikec83** [comment]
Added bounty on bountysource.

**Comment by aslmx** [comment]
:+1: 

i usually use some browser extensions to add and view bookmarks. Just today i logged in to nextcloud web and the bookmark page was terribly slow at first. Later i saw that the thumbnail view has loaded lots of thumbnails for my ~100 bookmarks. Then i knew why.

I failed to find an option to disable the thumbnail view and go back to a list view which i thought was implemented in the past...

Please add the list view again. Thanks! :)

**Comment by mfilser** [comment]
I would also like to have a switch between thumbnail view and a list view.
Is it also possible to customize the list view? So the user can check which columns he want to view? If yes, Please add all columns to list view of data what is available in database.

Thank you for your great work, i like it very much.

**Comment by IzzySoft** [comment]
Thanks @marcelklehr! Short question though: from the spacing I assume none of the bookmarks in the screenshot have a tag assigned – and if they had, tags would be shown in the free area below the bookmark names? If this assumption is wrong, please understand it as suggestion :wink:

**Comment by marcelklehr** [comment]
@IzzySoft You're spot on! That's exactly how it works. Should've made a better screenshot...

**Comment by IzzySoft** [comment]
Wow, cool – then I eagerly await it! As I doubt you'll backport it: what will be the minimal NC version for this? 14 or 15?

Further question: Say I'd want to stick with list view and never to use the tiles view. Will it be possible to disable "thumbnail generation" as it won't be needed in this case? If so, how to deal with the situation a user might want to turn it on again at a later time (would that automatically start generating all missing thumbnails, or would there be a way to trigger that manually – as after all, they are not really "essential")?

**Comment by marcelklehr** [comment]
This will be available for v14 as well, as I currently support both versions.

The details view makes use of the previews, so with this and the fact that people should be able to seamlessly switch between both views, I will probably not disable preview generation. However, I am addressing the performance issues regarding previews by adding a daily background job that will generate the previews.

**Comment by IzzySoft** [comment]
Thanks Marcel – and you also caught the main reason for my asking that. I had really huge delays when importing even 100 bookmarks. Your solution sounds really good :bowing_man: Looking forward to it (after I found time to upgrade my NC to 14 :wink:)

**Comment by IzzySoft** [comment]
Thanks a lot, Marcel! It's a real good start – but doesn't it waste a lot of space? What I had in mind would look close to what you see with

``` css
.list-view .bookmark-card { height: 38px; }
.list-view .bookmark-card .tags { height: 30px; top: -1.5em; left: unset; }
.bookmark-card { box-shadow; none; }
.bookmarks.list-view { padding: 55px 0; }
```

And omitting the "background image". That then would just give a raw idea, would need some fine-tuning, too – and I rather meant to "attach" the tags right at the end of the tile, instead of lying in top of it if the title gets too long. With the current formatting, rather than getting *more* entries on a single screen I get less.

I don't mean to critisize, but rather try to improve upon – if possible :wink:

**Comment by bernd-wechner** [comment]
Love it too! But agree, a more compact view would be nice too, and a way to choose the sort order. But big thumbs up!

**Comment by IzzySoft** [comment]
@bernd-wechner you can change the sort order when you click on the wheel in the lower left corner (below the tags).

**Comment by marcelklehr** [comment]
> With the current formatting, rather than getting more entries on a single screen I get less.

Ah, I see. Thanks for the feedback! We'll definitely improve upon this -- PRs welcome, of course 😄 

> Be nice if that sorting included a "Tags" option

There's an issue open for that :D

**Comment by IzzySoft** [comment]
@marcelklehr thanks! As you can see by my example CSS, I didn't manage to get something "acceptable" (it's more a "sketch") – otherwise I had created a PR…

**Comment by nickian** [comment]
Huge improvement. I agree though, no need for all the padding, tags, and background images on the list view. Just keep it simple and fast to navigate a large list.

**Comment by marcelklehr** [comment]
So, with a CSS-only switch we can either have the tags below the title or one column for title (preferably wider) and one for tags. With floccus as a use case a wide tag-line would be beneficial, as @bernd-wechner suggested, however, it's possible to sync folders natively, now (without the tags-hack), so this is kind of a moot point, I think. I think, the usual use of tags involves a few, short, precise keywords per item, so a table-like layout may be useful to reduce vertical space, while still retaining some amount of padding. What do you think?

**Comment by IzzySoft** [comment]
I was afraid that with CSS only it might be difficult to "inline" tags – so this might be the only viable approach. That tag-column then would hopefully only use minimum space, or maybe could even have a "max-width" setting (not that a single entry with e.g. 10 tags would "bloat" the column for all entries)? Or maybe even a way to "hide" the tag column (e.g. via a check-box on top)?

**Comment by marcelklehr** [comment]
Say hello to v0.16.1 :)

**Comment by IzzySoft** [comment]
Uh! I need to get home very fast and take a look 😃

**Comment by IzzySoft** [comment]
Much better! But might I suggest to decrease the padding?

    .list-view .bookmark-card .panel { padding:3px; }

10px is far too much (wastes too much space). Then adjust the tags:

    .list-view .bookmark-card .tags { top:2px; }

More compact, and good lucking :wink:

**Comment by nachoparker** [comment]
you guys rock

**Comment by marcelklehr** [comment]
@IzzySoft I have a tendency to have a long leash for padding on elements :D I've decreased it some more, but it's still a bit more than your values :)

**Comment by IzzySoft** [comment]
@marcelklehr maybe make it an option for "compactness"? If not for putting in values directly (as the two must somehow match), 3 levels (wide, normal, compact) might suffice. Just a thought…

(or maybe I should wait speaking out until I see the next release)
