### ISSUE TITLE
Sort by tag(s)

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/bookmarks#553]
It would be nice if bookmarks could be sorted by tag. Currently on the Sort dropdown we only see:

![image](https://user-images.githubusercontent.com/7296506/44637090-a037ee80-a9f2-11e8-9dd5-4f8f622e8421.png)

Given a bookmark can have more than one tag, suggest a simple rule to select the tag to sort on. The first tag if they are ordered, a random tag if not, the shortest tag perhaps (if they are used to denote the browser folder location as the floccus add-in does, then the shortest is likely to be the highest folder in a folder tree). A concatenation of tags, sorted by length, or alphabetically might be the sort key. Whatever, one hard coded option is better than none and a choice is just cream on top ;-)

https://github.com/marcelklehr/floccus

**Comment by marcelklehr** [comment]
Is it ok if I close this in favor of #514 ?

**Comment by bernd-wechner** [comment]
Wow, of course it is. You have to be the nicest most patient lead dev I've seen ;-). Most I come across just close stuff sometimes with a fatigued (grumpy) comment ;-). I'll leave it with you. https://github.com/nextcloud/bookmarks/issues/514 is not a replacement for this, but better in a sense. I'd certainly much rather see https://github.com/nextcloud/bookmarks/issues/514 than this, but if categories exist, being able to sort on them is a sort of (no pun intended) fitting thing too.

**Comment by marcelklehr** [comment]
heh, thanks, I try.

The question was mostly about whether this request was out of a need for managing floccus' tags and thus would become obsolete by implementing folders, but I agree that it could be a useful thing on it's own, just not as much a priority as folders :)

**Comment by marcelklehr** [comment]
*insert grumpy comment here*
