### ISSUE TITLE
Bug on upgrade 0.12.1

### ISSUE THREAD

**Issue by Picus13** [nextcloud/bookmarks#555]
Hello, today I make upgrade to Bookmarks 0.12.1 on App Panel. And when I go to bookmarks page I found it : 
![bookmarks down](https://user-images.githubusercontent.com/26966124/44728222-37c53c00-aadc-11e8-8d80-d67e79b6ffac.png)
😭 

Guys, have you an idea ?
Thank you for everything you do ! ❤️

**Comment by marcelklehr** [comment]
Hey there,

Which version of nextcloud is running on your server? You may try to clear your browser cache and reload the page.

**Comment by Picus13** [comment]
Hello,

Nextcloud version : 13.0.5

Unfortunately, even when I cleared cache, same result. 😢 . I tried to make a manual install, same result ...

**Comment by marcelklehr** [comment]
That's actually still the old UI being displayed :/ Without any styles, though. Can you try disabling the app and re-enabling it?

**Comment by marcelklehr** [comment]
For some reason you still have some file from the old version, it seems. Did you remove the bookmarks/ directory before installing [manually](https://github.com/nextcloud/bookmarks#manual-install)?

**Comment by Picus13** [comment]
Yes, I had already tried to disable / reactivate it. And of course I remove everything before reinstalling Bookmarks.

**Comment by Picus13** [comment]
🎉 It's okay, I found out where the problem is. 

On this installation, Nextcloud was installed via Snap, I did a  `snap restart nextcloud`  and it works again without any problems. It makes so much sense, though, I mean, now it's done.

Thanks again ! 🙏 🍪

**Comment by marcelklehr** [comment]
Glad it works now :)
