### ISSUE TITLE
Caching preview images of screenly

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/bookmarks#558]
It seems, that the previews which are generated via screenly are refreshed on every reload of the bookmarks app. Isn't it possible to cache them?

**Comment by marcelklehr** [comment]
Are you talking about caching in the browser or caching on the server? They are cached for 4 months on the server.

**Comment by dartcafe** [comment]
Server cahing. It seems, that the thumbnails are rendered on every reload. Loading the Bookmarks with about 90 entries lasts more than 10 minutes. 
Where are the thumbnails stored? I cannot find them in the filesystem.

**Comment by marcelklehr** [comment]
It appears you are correct. I have been astounded before by the bad performance of the previews but have always blamed that on the poor performance of my own server. After some investigation however, it transpires that I used the wrong caching module. The one I used was for memory caching, when I wanted to use file caching :/

**Comment by jfqd** [comment]
Quick question: where are they stored on the filesystem?

**Comment by marcelklehr** [comment]
In v0.13.0 they should be somewhere stored in data/

**Comment by jfqd** [comment]
Thx! Found it. They are separated per user in the cache folder (data/<user>/cache).
