### ISSUE TITLE
Tags not imported from Chromium

### ISSUE THREAD

**Issue by ctag** [nextcloud/bookmarks#562]
### Steps to reproduce
1. Export bookmarks from Chromium (ver 69) as html file
2. Import html file to Nextcloud Bookmarks (ver 0.12.2)
3. All bookmarks are listed as untagged.

### Expected and Actual behaviour

I understand that the bookmarks app does not support -- and likely will not add -- [folders for organizing bookmarks](https://github.com/nextcloud/bookmarks/issues/13). That issue instead cites tags as the method of grouping bookmarks, which is different in the lack of hierarchy, but serves a similar enough purpose.

Chromium does not appear to have tags for bookmarks at all, and instead solely relies on folders to organize bookmarks. Though it's sub-optimal, I'd expect importing bookmarks from Chromium to Nextcloud to bring in folder names as tags. Is there an alternate method to import bookmarks and have tags generated?

### Server configuration

**Operating system**: FreeBSD

**Web server:** nginx

**Database:** mariadb

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page) 13.0.4

**Bookmarks version:** (see Nextcloud apps page) 0.12.2

**Updated from an older Nextcloud or fresh install:** Updated from older nextcloud.

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...


### Client configuration
**Browser:** Chromium

**Operating system:** Linux

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
> I understand that the bookmarks app does not support -- and likely will not add -- folders for organizing bookmarks.

Folder support is being implemented as we speak :)
