### ISSUE TITLE
Sort colum of tags by alpabeticaly

### ISSUE THREAD

**Issue by Jurik-Phys** [nextcloud/bookmarks#563]
### Steps to reproduce
1. Open bookmarks and see to column of tags. 

### Expected behaviour
I expect have possibility sort it by name. Because I remember tag name and do search by tag's name.

### Actual behaviour
Column of tags sorted by count of bookmarks of each tag. I don't understand how information about count of bookmarks for tags may help me for select tag. I have to see column of tags and check every tag because don't know how many bookmarks with needed tag.

**Nextcloud version:**
 13.0.6

**Bookmarks version:**
0.12.2

**Comment by marcelklehr** [comment]
My bad. It is indeed not a duplicate, as #553 asks for being able to sort bookmarks by tags. I do think the tags column could be made easier to navigate, but I don't think sorting alphabetically is the way to go. See #515 for that subject :)
