### ISSUE TITLE
Version 11.x to 12.2 - no longer renders correctly - no bookmarks display

### ISSUE THREAD

**Issue by bsherwoodofdaptiv** [nextcloud/bookmarks#564]
### Steps to reproduce
1. In Bookmarks app 0.11.x create as many passwords as you desire.
2. Upgrade to Bookmarks 0.12.2
3. Try and open the Bookmark apps and use it

### Expected behaviour
Render Bookmarks app

### Actual behaviour
Doesn't render beyond:
Left pane - filters box (half off screen) - 'fitlerable tags' text, no existing tags listed (as it was in 0.11.x) gear icon at the bottom, which exposes bookmarklet link and Import/Export buttons.
Right pane - blank

Firefox dev tools exposes:

Loading failed for the <script> with source “https://bkmk.mysite.com/extra-apps/bookmarks/js/bookmarks.js?v=0af3ae55-5”. bookmarks:45
Loading failed for the <script> with source “https://bkmk.mysite.com/extra-apps/bookmarks/js/settings.js?v=0af3ae55-5”. bookmarks:44
Loading failed for the <script> with source “https://bkmk.mysite.com/extra-apps/bookmarks/js/3rdparty/tag-it.js?v=0af3ae55-5”. bookmarks:46
Loading failed for the <script> with source “https://bkmk.mysite.com/extra-apps/bookmarks/js/3rdparty/js_tpl.js?v=0af3ae55-5”. bookmarks:47
JQMIGRATE: Migrate is installed, version 1.4.0

### Server configuration

**Operating system**:
Linux 
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
13.0.6
**Bookmarks version:** (see Nextcloud apps page)
0.12.2

**Updated from an older Nextcloud or fresh install:**
Fresh Install

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

**Are you using external storage, if yes which one:** local/smb/sftp/...
WebDav

**Are you using encryption:** yes/no
yes (encrypt home storage)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox 62

**Operating system:**
Windows 10

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

Loading failed for the <script> with source “https://bkmk.mysite.com/extra-apps/bookmarks/js/bookmarks.js?v=0af3ae55-5”. bookmarks:45
Loading failed for the <script> with source “https://bkmk.mysite.com/extra-apps/bookmarks/js/settings.js?v=0af3ae55-5”. bookmarks:44
Loading failed for the <script> with source “https://bkmk.mysite.com/extra-apps/bookmarks/js/3rdparty/tag-it.js?v=0af3ae55-5”. bookmarks:46
Loading failed for the <script> with source “https://bkmk.mysite.com/extra-apps/bookmarks/js/3rdparty/js_tpl.js?v=0af3ae55-5”. bookmarks:47
JQMIGRATE: Migrate is installed, version 1.4.0
```

**Comment by marcelklehr** [comment]
Thanks for the detailed bug report!

Could you try:

1. Clearing your browser cache and reloading the page
2. Disabling, re-enabling the bookmarks app and reloading the page

**Comment by bsherwoodofdaptiv** [comment]
Will attempt request actions.

**Comment by Kweck** [comment]
Also here with Bookmarks 0.13.1 - I also just get the "Schlagworte" on the left pane top and nothing else.
Bookmarks are still accessible using FreedomMarks.

**Comment by marcelklehr** [comment]
So, the errors show that old code is being loaded on the client.

@bsherwoodofdaptiv  @Kweck Thank you! That's very helpful. Is there anything going on in the nextcloud log?

**Comment by marcelklehr** [comment]
Also, do any of you have installed the search app for bookmarks? It seems to cause trouble with the newer versions...

**Comment by bsherwoodofdaptiv** [comment]
Hmm.. I don;t think so. I don't recall adding that as an app? Or is it a configuration setting?

**Comment by bsherwoodofdaptiv** [comment]
Ahh, an add on. No. I do not have "Full text search - Bookmarks" installed.

**Comment by bsherwoodofdaptiv** [comment]
Additional comment:

Since I was logged in as Admin, I tried the Bookmarks app. It does render that statement:
"No bookmarks here.

There are no bookmarks available for this query. Try changing your filter or add some using the menu entry on the left."

Adding a bookmark in there worked.

**Comment by bsherwoodofdaptiv** [comment]
And... now book marks work again for my regular user.

Very odd. I haven't reinstalled the android app

**Comment by marcelklehr** [comment]
Probably some kind of caching issue in nextcloud. I'm gllad it works again :) I'll close this for now.
