### ISSUE TITLE
Option to disable thumbnail and favico retrieving

### ISSUE THREAD

**Issue by urlyb** [nextcloud/bookmarks#565]
Is it possible to add an option to disable/enable thumbnail and favicon retrieving for each bookmark? 

The reason for this request are bookmarks of pages which are not accessible from the nexcloud server and trying to retrieve  thumbnails or favicons causes a lot of exceptions in the log files.

**Comment by marcelklehr** [comment]
This should be fixed in 0.12.2. Which version are you running?

**Comment by urlyb** [comment]
I'm running NC 13.0.6 and Bookmarks app version 0.12.2.

**Comment by marcelklehr** [comment]
Ah, my bad. It's fixed in 0.13, which is only available for nextcloud 14, however. I might get around to backporting this, but the quickest way to fix this is to upgrade to v14. Or v14.0.1 perhaps, if you're worried about stability :)
