### ISSUE TITLE
Error shown on nextcloud log: "Trying to get property of non-object"

### ISSUE THREAD

**Issue by pachulo** [nextcloud/bookmarks#567]
### Steps to reproduce
1. Install the nextcloud snap
2. Install the bookmarks app
3. Open it.

### Expected behaviour
There should be no errors in the nextcloud logs.

### Actual behaviour
I see quite a few errors in the log.

### Server configuration
**Operating system**: Ubuntu core 16

**Web server:** The one included in the snap (Apache).

**Database:** The one included in the snap (MySQL).

**PHP version:** The one included in the snap (7.1.22 right now).

**Nextcloud version:** 13.06

**Bookmarks version:** 0.12.2

**Updated from an older Nextcloud or fresh install:** Updated all the way back from nextcloud 11.

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 62

**Operating system:** Ubuntu 18.04

### Nextcloud log (data/nextcloud.log)
```
Trying to get property of non-object at /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/controller/lib/bookmarks.php#700
```

**Comment by marcelklehr** [comment]
Ah, this particular error stems from the import mechanism which is quite dusty. With my current effort to implement folders I'm rewriting this part anyway, so this should be fixed in the process. Thanks for the feedback! Any other unexpected errors?

**Comment by pachulo** [comment]
That's great @marcelklehr ! Not more errros, but I also observed this warning:

`GuzzleHttp\Exception\ClientException: Client error response [url] https://statuscode.ch/favicon.ico [status code] 404 [reason phrase] Not Found in /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89 Stack trace: #0 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(32): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response)) #1 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete') #2 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent)) #3 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) #4 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array) #5 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) #6 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL) #7 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure)) #8 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) #9 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request)) #10 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/controller/lib/previews/defaultpreviewservice.php(129): GuzzleHttp\Client->get('https://statusc...', Array) #11 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/controller/lib/previews/defaultpreviewservice.php(98): OCA\Bookmarks\Controller\Lib\Previews\DefaultPreviewService->fetchImage('https://statusc...') #12 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/controller/lib/previews/faviconpreviewservice.php(57): OCA\Bookmarks\Controller\Lib\Previews\DefaultPreviewService->getOrFetchImageUrl('https://statusc...') #13 /var/snap/nextcloud/8973/nextcloud/extra-apps/bookmarks/controller/rest/internalbookmarkcontroller.php(243): OCA\Bookmarks\Controller\Lib\Previews\FaviconPreviewService->getImage(Array) #14 [internal function]: OCA\Bookmarks\Controller\Rest\InternalBookmarkController->getBookmarkFavicon(17) #15 /snap/nextcloud/8973/htdocs/lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array) #16 /snap/nextcloud/8973/htdocs/lib/private/AppFramework/Http/Dispatcher.php(91): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Bookmarks\Controller\Rest\InternalBookmarkController), 'getBookmarkFavi...') #17 /snap/nextcloud/8973/htdocs/lib/private/AppFramework/App.php(115): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Bookmarks\Controller\Rest\InternalBookmarkController), 'getBookmarkFavi...') #18 /snap/nextcloud/8973/htdocs/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('InternalBookmar...', 'getBookmarkFavi...', Object(OC\AppFramework\DependencyInjection\DIContainer), Array) #19 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array) #20 /snap/nextcloud/8973/htdocs/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array) #21 /snap/nextcloud/8973/htdocs/lib/base.php(999): OC\Route\Router->match('/apps/bookmarks...') #22 /snap/nextcloud/8973/htdocs/index.php(42): OC::handleRequest() #23 {main}`

**Comment by marcelklehr** [comment]
Ah, yes, this has been handled in the following version, which works in nextcloud 14 only. It's nothing to worry about, though, except maybe drive usage of logs :D
