### ISSUE TITLE
Settings cannot be clicked if the list of tags fills the left hand tags-management element

### ISSUE THREAD

**Issue by TraceyC77** [nextcloud/bookmarks#569]
### Steps to reproduce
1. Create some tags & resize the browser so that the list of tags fills up the left hand navigation element
2. Attempt to click on "Settings"

### Expected behaviour
The settings are accessible and shown

### Actual behaviour
The tag is clicked and the bookmarks with that tag are shown on the right
The "Settings" element (div id='app-settings') seems to be behind the tags-management element. I can't even target the settings icon with the inspector tool in the developer console.
This can be reproduced with Firefox and Chromium, both browsers are up to date

## Server configuration detail

**Operating system:** Linux 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** sqlite3 3.7.17

**PHP version:** 

7.0.32
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, cgi-fcgi, bcmath, calendar, ctype, curl, dom, fileinfo, ftp, gd, iconv, imap, json, mbstring, mcrypt, mysqlnd, PDO, Phar, posix, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, Zend OPcache

**Nextcloud version:** 14.0.1 - 14.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** zip file from the Nextcloud website

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - bookmarks: 0.13.0
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.2
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.6
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - news: 13.0.1
 - nextcloud_announcements: 1.3.0
 - notes: 2.4.2
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - qownnotesapi: 18.8.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.7
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - bookmarks.old
 - encryption
 - files_external
 - ransomware_protection
 - twofactor_totp
 - twofactor_yubikey
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.tlcnet.info"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/www.tlcnet.info\/nextcloud",
    "dbtype": "sqlite3",
    "version": "14.0.1.1",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "theme": "",
    "loglevel": 2,
    "maintenance": false,
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** n/a

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** n/a

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/69.0.3497.81 Chrome/69.0.3497.81 Safari/537.36

**Operating system:** CentOS 7

## Logs

<details><summary>Browser log</summary>

```
Firefox Console
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

Firefox Console
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542

</details>

**Comment by TraceyC77** [comment]
Here's a screenshot showing the overlap

![bookmarks_settings_overlap_screenshot](https://user-images.githubusercontent.com/10402612/46251170-44a5ba00-c411-11e8-8c1c-d5ecc5e6ec55.png)

**Comment by marcelklehr** [comment]
Thanks for the feedback. The fix will be in the next release. :)

**Comment by z3ntu** [comment]
@marcelklehr Is there an ETA on the next release? I'm affected by this issue as well.

**Comment by marcelklehr** [comment]
I'll try to do a release soon-ish.

**Comment by marcelklehr** [comment]
Say hello to v0.13.1

**Comment by z3ntu** [comment]
Thanks!
