### ISSUE TITLE
NC14.0.1 & Bookmarks 0.13.0: "App is not compliant"

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/bookmarks#572]
`occ app:check-code bookmarks`

```
Analysing /var/www/html/apps/bookmarks/controller/lib/bookmarks.php
 18 errors
    line   99: != - is discouraged
    line  194: != - is discouraged
    line  196: == - is discouraged
    line  208: == - is discouraged
    line  229: == - is discouraged
    line  242: == - is discouraged
    line  248: != - is discouraged
    line  250: != - is discouraged
    line  281: == - is discouraged
    line  284: == - is discouraged
    line  292: == - is discouraged
    line  312: == - is discouraged
    line  479: == - is discouraged
    line  578: == - is discouraged
    line  582: == - is discouraged
    line  698: == - is discouraged
    line  700: == - is discouraged
    line  734: != - is discouraged
Analysing /var/www/html/apps/bookmarks/controller/lib/previews/defaultpreviewservice.php
 3 errors
    line   74: OCP\Util::writeLog - Method of deprecated class must not be called
    line  139: OCP\Util::writeLog - Method of deprecated class must not be called
    line  146: != - is discouraged
Analysing /var/www/html/apps/bookmarks/controller/lib/previews/screenlypreviewservice.php
 2 errors
    line  119: OCP\Util::writeLog - Method of deprecated class must not be called
    line  124: != - is discouraged
Analysing /var/www/html/apps/bookmarks/controller/lib/search.php
 3 errors
    line   37: OCP\User - Static method of deprecated class must not be called
    line   37: OCP\User::getUser - Method of deprecated class must not be called
    line   45: OC_Search_Result - private class must not be instantiated
Analysing /var/www/html/apps/bookmarks/controller/lib/linkexplorer.php
 2 errors
    line   33: OCP\Util::writeLog - Method of deprecated class must not be called
    line   39: OCP\Util::writeLog - Method of deprecated class must not be called
Analysing /var/www/html/apps/bookmarks/controller/rest/publiccontroller.php
 6 errors
    line   46: == - is discouraged
    line   46: == - is discouraged
    line   60: != - is discouraged
    line   68: Util::writeLog - Method of deprecated class must not be called
    line   75: != - is discouraged
    line   82: == - is discouraged
Analysing /var/www/html/apps/bookmarks/controller/rest/bookmarkcontroller.php
 10 errors
    line   73: == - is discouraged
    line   82: != - is discouraged
    line  150: == - is discouraged
    line  180: == - is discouraged
    line  254: == - is discouraged
    line  332: == - is discouraged
    line  385: Util::writeLog - Method of deprecated class must not be called
    line  391: == - is discouraged
    line  428: OC_Util - Static method of private class must not be called
    line  436: OC_Util - Static method of private class must not be called
Analysing /var/www/html/apps/bookmarks/controller/rest/tagscontroller.php
 3 errors
    line   34: == - is discouraged
    line   57: == - is discouraged
    line   57: == - is discouraged
App is not compliant
```

What does this mean?
Thank you!

**Comment by marcelklehr** [comment]
Hey,

this means that some details in the app's code are old or badly written. Thanks for filing an issue. We'll sort this out before the next release :)

**Comment by lvarnava** [comment]
the same in NC14.0.3
and bookmarks do not work at all

Nextcloud 14.0.3
ubuntu 16.04.5
postgresql 9.5
apache 2.4.18
Bookmarks 0.13.1

Analysing /var/www/html/nextcloud/apps/bookmarks/controller/rest/bookmarkcontroller.php
 10 errors
    line   73: == - is discouraged
    line   82: != - is discouraged
    line  150: == - is discouraged
    line  180: == - is discouraged
    line  254: == - is discouraged
    line  332: == - is discouraged
    line  385: Util::writeLog - Method of deprecated class must not be called
    line  391: == - is discouraged
    line  428: OC_Util - Static method of private class must not be called
    line  436: OC_Util - Static method of private class must not be called
Analysing /var/www/html/nextcloud/apps/bookmarks/controller/rest/tagscontroller.php
 3 errors
    line   34: == - is discouraged
    line   57: == - is discouraged
    line   57: == - is discouraged
Analysing /var/www/html/nextcloud/apps/bookmarks/controller/rest/publiccontroller.php
 6 errors
    line   46: == - is discouraged
    line   46: == - is discouraged
    line   60: != - is discouraged
    line   68: Util::writeLog - Method of deprecated class must not be called
    line   75: != - is discouraged
    line   82: == - is discouraged
Analysing /var/www/html/nextcloud/apps/bookmarks/controller/lib/bookmarks.php
 18 errors
    line   99: != - is discouraged
    line  194: != - is discouraged
    line  196: == - is discouraged
    line  208: == - is discouraged
    line  229: == - is discouraged
    line  242: == - is discouraged
    line  248: != - is discouraged
    line  250: != - is discouraged
    line  281: == - is discouraged
    line  284: == - is discouraged
    line  292: == - is discouraged
    line  312: == - is discouraged
    line  479: == - is discouraged
    line  578: == - is discouraged
    line  582: == - is discouraged
    line  698: == - is discouraged
    line  700: == - is discouraged
    line  734: != - is discouraged
Analysing /var/www/html/nextcloud/apps/bookmarks/controller/lib/previews/defaultpreviewservice.php
 3 errors
    line   74: OCP\Util::writeLog - Method of deprecated class must not be called
    line  139: OCP\Util::writeLog - Method of deprecated class must not be called
    line  146: != - is discouraged
Analysing /var/www/html/nextcloud/apps/bookmarks/controller/lib/previews/screenlypreviewservice.php
 2 errors
    line  119: OCP\Util::writeLog - Method of deprecated class must not be called
    line  124: != - is discouraged
Analysing /var/www/html/nextcloud/apps/bookmarks/controller/lib/linkexplorer.php
 2 errors
    line   33: OCP\Util::writeLog - Method of deprecated class must not be called
    line   39: OCP\Util::writeLog - Method of deprecated class must not be called
Analysing /var/www/html/nextcloud/apps/bookmarks/controller/lib/search.php
 3 errors
    line   37: OCP\User - Static method of deprecated class must not be called
    line   37: OCP\User::getUser - Method of deprecated class must not be called
    line   45: OC_Search_Result - private class must not be instantiated
App is not compliant

![bookmarks_2018-10-15_11-01-47](https://user-images.githubusercontent.com/32108411/46937463-098ac400-d06a-11e8-9c23-9c3df5420f40.png)

this is all I can see; I cannot add a bookmark

**Comment by lvarnava** [comment]
When the "fulltextsearch" is disabled then "bookmarks" is running, which was previously blocked!
https://github.com/nextcloud/jsxc.nextcloud/issues/111#issuecomment-432641535

**Comment by marcelklehr** [comment]
Ah, makes sense.

**Comment by kylepwarren** [comment]
Did you try getting rid of all of those "Util::writeLog"s? I love how no one really cares enough to fix this. Maybe it will be fixed by 2019.

**Comment by marcelklehr** [comment]
@kylepwarren Feel free to take this on. :) It's not that I don't care, I just need to prioritize.

**Comment by kylepwarren** [comment]
I waited for another nc update, and it still didn't work. I decided to try removing and re-installing. That worked. Update was not an option while it was disabled for compatibility reasons.
