### ISSUE TITLE
Settings button out of reach when sidebar is full

### ISSUE THREAD

**Issue by reimarstier** [nextcloud/bookmarks#574]
This is about a small change in CSS I think. My current version is Nextcloud 14, Bookmarks 0.13.0.

If the left sidebar is full with bookmark tags it is no longer possible to click the settings button. Instead the click goes onto the bookmark tag.

![nextcloud-bookmark-settings-button](https://user-images.githubusercontent.com/11158749/46548958-d198b980-c8d0-11e8-93ca-f125d853fc10.png)

**Comment by marcelklehr** [comment]
Yup, I can confirm. This has been reported before. See #569 In any case: Thanks for the feedback :)
