### ISSUE TITLE
adding tags fails

### ISSUE THREAD

**Issue by obama** [nextcloud/bookmarks#585]
### Steps to reproduce
try to add a tag

### Expected behaviour
success

### Actual behaviour
spinning wheel never ends, 
XHR fails with a 500, showing a HTML site that says i need to enable JS

## Server configuration detail

**Operating system:** Linux 4.4.0-138-generic #164-Ubuntu SMP Tue Oct 2 17:16:02 UTC 2018 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.21

**PHP version:** 

7.0.30-nmm1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dom, hash, filter, ftp, gettext, SPL, iconv, json, mbstring, posix, Reflection, session, standard, shmop, SimpleXML, soap, exif, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cgi-fcgi, propro, raphf, http, mysqlnd, PDO, curl, dba, fileinfo, gd, gender, gmp, htscanner, imagick, imap, interbase, intl, ldap, mailparse, mcrypt, mongodb, mysqli, OAuth, odbc, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, pspell, recode, SourceGuardian, sqlite3, tidy, xsl, ionCube Loader

**Nextcloud version:** 14.0.3 - 14.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - bookmarks: 0.13.1
 - bookmarks_fulltextsearch: 1.0.0
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.3
 - checksum: 0.4.1
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.6
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - metadata: 0.7.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.4.2
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - ownbackup: 18.8.1
 - password_policy: 1.4.0
 - phonetrack: 0.3.6
 - previewgenerator: 1.1.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.7
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - unsplash: 1.1.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - drawio
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "domain.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/domain.com\/nextcloud",
    "dbtype": "mysql",
    "version": "14.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "kNkKk_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "tempdirectory": "\/www\/htdocs\/acc1\/nextcloud\/tmp\/",
    "maintenance": false,
    "theme": "",
    "loglevel": 2
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Chrome and firefox

**Operating system:** windows 10

## Logs

<details><summary>Browser log</summary>

```
error 500, HTML response saying no JS enabled
```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

error 500, HTML response saying no JS enabled
</details>

**Comment by marcelklehr** [comment]
Which version of the bookmarks app is this? Could you provide an excerpt of the nextcloud log from the time when the error occurs?

**Comment by marcelklehr** [comment]
Hey,

Which bookmarks app version are we talking about here? Could you add an excerpt of the nextcloud log from the time when the error occurs?

**Comment by obama** [comment]
0.13.1


Error | index | Error: Class 'OCA\FullTextSearch\Api\v1\FullTextSearch' not found | 2018-11-02T19:30:07+0100
-- | -- | -- | --
Error | PHP | Undefined index: host at /www/htdocs/acc1/nextcloud/apps/bookmarks/controller/lib/previews/faviconpreviewservice.php#53 | 2018-11-02T19:29:44+0100
Error | PHP | Undefined index: host at /www/htdocs/acc1/nextcloud/apps/bookmarks/controller/lib/previews/faviconpreviewservice.php#53 | 2018-11-02T19:29:44+0100
Error | PHP | Undefined index: host at /www/htdocs/acc1/nextcloud/apps/bookmarks/controller/lib/previews/faviconpreviewservice.php#53 | 2018-11-02T19:29:44+0100

**Comment by marcelklehr** [comment]
Could you try disabling the FullTextSearch bookmarks app?

**Comment by obama** [comment]
than it works. thank you.
