### ISSUE TITLE
Display date added

### ISSUE THREAD

**Issue by IzzySoft** [nextcloud/bookmarks#591]
### Steps to reproduce
1. add or import one or more bookmarks
2. open the Bookmarks app in Nextcloud to browse existing bookmarks
3. see the bookmark tiles, or click one to see the details

### Expected behaviour
Next to title, description, tags and URL, the date when the bookmark was added is shown (at least read-only)

### Actual behaviour
The date a bookmark was added on is nowhere to be found (except by looking up the timestamp in the database manually)

### Server configuration

**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
13

**Bookmarks version:** (see Nextcloud apps page)
0.12.2

**Updated from an older Nextcloud or fresh install:**
Updated

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
n/a

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
n/a

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Waterfox

**Operating system:**
n/a

### Logs
n/a

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

I've marked several sections n/a because the date is not parsed into the page (so browser etc. are irrelevant), I've checked the page source. Unfortunately, this part takes place in the Javascript block and I'm not experienced enough with that, or I had offered a patch.

Date added should be easily accessible to the end user, as it gives context without opening the link behind – not only on the linked page itself, but also on other bookmarks added around the same time.

**Comment by marcelklehr** [comment]
Good idea. I was thinking of adding it as a relative date (i.e. 2 months ago), rather than an absolute one. (Although this might be tricky to do with i18n...) Thoughts?

**Comment by IzzySoft** [comment]
@marcelklehr Please, not that Yoda-time. Or at least only on mouse-over (`title` attribute). Taking your example: was "2 month ago" before or after October 12th? Those "relative" times are always hard to compare. I remember them from Pocket, where it was even worse: "1325 days ago"? Thanks.

Besides: If you wish, I can provide you with my diffs for bookmark import/export (I "patched" that on NC 12, and cannot test it on the latest build, hence I'd prefer not to make that a PR). IIRC I even posted that here in a different issue… ah, here it is: #592. Tested it on NC 12 & 13 multiple times (importing from Pocket initially, so it would work with that as well). The combination of NC Bookmarks with the NC Bookmarks Android app and the Freeemarks addon for Firefox/Waterfox works quite well as Pocket replacement (though I wish Freemarks would use a local database).

Just mention this here as the two issues are somehow connected :wink:

**Comment by IzzySoft** [comment]
Thanks a lot! :tada:
