### ISSUE TITLE
Empty page with bookmarks v0.14.0

### ISSUE THREAD

**Issue by jurgenhaas** [nextcloud/bookmarks#594]
### Steps to reproduce
1. Use NC 14.03
2. Update to bookmarks v0.14.0
3. Go to the bookmarks

### Expected behaviour
Would like to see my bookmarks

### Actual behaviour
The nextcloud header is visible but nothing from the bookmarks

![2018-11-12 19 14 14 screen](https://user-images.githubusercontent.com/1475675/48367067-e4609400-e6af-11e8-91ad-667124dcd83a.jpg)

When digging around I found #579 and I then disabled the fulltext search plugin for bookmarks. When going back to the bookmark page I got a bit more, i.e. the left bar with the tags is being displayed but still no bookmarks. The error messages in the console remain the same, so something must be wrong with this module's update.

The previous version just worked perfectly.

**Comment by js-d-coder** [comment]
I am also using Bookmarks 0.14.0. Try clearing your browser cache and load the page again...

**Comment by jurgenhaas** [comment]
That didn't help I'm afraid, there is the spinning wheel forever:

![2018-11-13 09 02 45 screen](https://user-images.githubusercontent.com/1475675/48399094-f92a3f80-e722-11e8-9189-584ea708e2ec.jpg)

**Comment by tcitworld** [comment]
I had to run the migrations again manually because the postMigration stuff is quite heavy (I have lots of users with lots of data), and I guessed it didn't worked through the interface.

```bash
sudo -u www-data php ./occ migrations:execute bookmarks 000014000Date20181002094721
sudo -u www-data php ./occ migrations:execute bookmarks 000014000Date20181029094721
```
You may have to delete the `index` column on the new tables `oc_bookmarks_folders` and `oc_bookmarks_folders_bookmarks` since the second migration wants to recreate it.
By the way, naming a column `index` is a really bad idea, since it's a reserved SQL keyword. :(

**Comment by jurgenhaas** [comment]
If I'm trying to run the migration manually I do get the error

```
There is no table with name 'nextcloud_privat.oc_bookmarks_folders' in the schema.
```

I can't find any error in the logs and wonder what should be done next.

**Comment by jurgenhaas** [comment]
Ah, OK - did it in the wrong order. When doing it as described by @tcitworld then it does work, but still the fulltextsearch_bookmarks app needs to be disabled.

**Comment by c0r3dump3d** [comment]
I have had the same problem, I have need to disable the fulltextsearch_bookmarks app, they appear to be incompatible?

Nextcloud: 14.0.3
Apache: Apache/2.4.6
O.S.: CentOS Linux release 7.5.1804 (Core)
PHP 7.1.23

**Comment by marcelklehr** [comment]
@c0r3dump3d Yep, the fulltextsearch bookmarks app is not compatible with bookmarks v0.12+

**Comment by warsix4** [comment]
I do not have fulltextsearch app enabled on my Nextcloud and am experiencing this same issue. 
![image](https://user-images.githubusercontent.com/43068195/49331346-e4420e80-f560-11e8-937c-9ee4562365c5.png) Firefox 63, Nextcloud 15. CSP is a pain!

**Comment by marcelklehr** [comment]
@warsix4 Thanks for the heads-up! Could you open a new issue for this?

**Comment by warsix4** [comment]
Sure!
