### ISSUE TITLE
Wrong date on bookmarks export file

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/bookmarks#603]
### Steps to reproduce
1. Open the Bookmarks App within Nextcloud from a web browser
2. Click on Settings on the bottom left
3. Click on Export within 1 hour of midnight in the Eastern time zone

### Expected behaviour
The exported file should have a date that matches the date the user exported the bookmarks

### Actual behaviour
The date is actually the day after the bookmarks were exported

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
nginx 1.10.3
**Database:**
mariadb
**PHP version:**
7.0.32
**Nextcloud version:** (see Nextcloud admin page)
13.0.7 (or 14.0.4)
**Bookmarks version:** (see Nextcloud apps page)
0.12.2 (or 0.14.3)
**Updated from an older Nextcloud or fresh install:**
Updated
**Signing status:**

### Client configuration
**Browser:**
Firefox (or Brave. IE has issues displaying anything.)
**Operating system:**
Windows 10 (or Android 9)

**Comment by marcelklehr** [comment]
I cannot reproduce this. Please check your server time.

**Comment by koreywithak** [comment]
My server time was correct. I think I was exporting near midnight, which made me question if the date was based on a certain timezone even if the time was correct. However, I have since updated to NC 14 and cannot use the app currently, so I cannot currently help investigate this issue, sadly.

**Comment by marcelklehr** [comment]
> I have since updated to NC 14 and cannot use the app currently

Is that because the app doesn't work? It should work in NC 14. Do you perhaps have the fulltext search app installed?

**Comment by koreywithak** [comment]
Well yesterday it said the app wasn't compatible but today it said it had an update. I swear I'm not dumb. Anyways I updated it. It works fine in NC 14. The export had the right date when I tried it now. Let me try it before and after midnight. If it works again then (similar to last time this happened), I'll close this comment

**Comment by koreywithak** [comment]
Okay I have reproduced this once again. It is 11:38 PM on 12/9 and when I export the Bookmarks file, the date shown says 12/10. Both the computer I'm on and the server time correctly show 12/9 for the date. This time the Bookmarks app is version 0.14.3 and NC is 14.0.4. I'll update the original post with the more specific conditions to reproduce.

**Comment by marcelklehr** [comment]
Mmh. Which timezone are you and the server in?

**Comment by koreywithak** [comment]
Eastern Standard Time

**Comment by marcelklehr** [comment]
It's probably possible to circumvent this by setting [date.timezone in php.ini](https://secure.php.net/manual/en/datetime.configuration.php#ini.date.timezone). However, it's probably more straightforward to simply use the nextcloud date utilities to avoid this problem.
