### ISSUE TITLE
serverListTempFolder.findBookmark is undefined

### ISSUE THREAD

**Issue by wrohdewald** [nextcloud/bookmarks#608]
floccus 3.1.13

### Steps to reproduce
1. define an account like https://my.page.org/nextcloud/

2. sync

3. get that error message

### Server configuration
Nextcloud 14.04.2

**Operating system**:
Ubuntu 18.04

**Web server:**
Apache2

**Database:**
Mysql

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
14.04.2

**Bookmarks version:** (see Nextcloud apps page)
0.14.2

**Updated from an older Nextcloud or fresh install:**
fresh install

**Signing status:**

```No errors have been found.
```

**Nextcloud configuration:**

### Client configuration
**Browser:**
Firefox 63.0.3

**Operating system:**
Ubuntu 18.04

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
nothing
```

**Comment by marcelklehr** [comment]
Hey!

Thanks for reporting this error. Unfortunately, this is the wrong repository, as the error occured in [floccus](https://github.com/marcelklehr/floccus). I happen to be maintainer of both projects, though, and have just found a fix, which will be in the next release of floccus.

Cheers!
