### ISSUE TITLE
High Load on Nextcloud when Using Bookmarks App with Multiple Browsers

### ISSUE THREAD

**Issue by mbrandis** [nextcloud/bookmarks#620]
![load-nextcloud](https://user-images.githubusercontent.com/4790494/50004587-e7e58480-ffa7-11e8-977c-ceebe2183d3c.png)
### Steps to reproduce
1. Link multiple browsers to Bookmarks App
2. Have the browsers run at the same time.

### Expected behaviour
The sync should happen with minimal impact on the Nextcloud instance.

### Actual behaviour
Syncing with multiple browsers at the same time (two on two different computers) increases the load on the Nextcloud instance significantly. See attached screenshot of monitoring instance. During workday (second and third browser open), the load increases. This Friday I double checked and stopped the other running browser 

instances.

### Server configuration
**Operating system**:
Debian 9.6

**Web server:**
Apache 2.4.25-3+deb9u6

**Database:**
MySQL 5.5.9999+default

**PHP version:**
7.0.33-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page)
14.0.4

**Bookmarks version:** (see Nextcloud apps page)
0.14.3

**Updated from an older Nextcloud or fresh install:**
Updated

**Signing status:**
No errors have been found.

**List of activated apps:**
  - accessibility: 1.0.1
  - bookmarks: 0.14.3
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.0.1
  - contacts: 2.1.8
  - dav: 1.6.0
  - encryption: 2.2.0
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - metadata: 0.8.0
  - notes: 2.5.1
  - notifications: 2.2.1
  - oauth2: true
  - provisioning_api: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - tasks: 0.9.8
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_sql: 4.1.0
  - workflowengine: 1.4.0

**Nextcloud configuration:**

        "dbtype": "mysql",
        "version": "14.0.4.2",
        "dbtableprefix": "oc_",
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 604800,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "token_auth_enforced": false,
        "mail_smtpdebug": false,
        "mail_smtpmode": "sendmail",
        "mail_smtpport": 25,
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "",
        "mail_smtpauth": false,
        "mail_smtpauthtype": "LOGIN",
        "htaccess.RewriteBase": "\/owncloud",
        "trashbin_retention_obligation": "7, auto",
        "versions_retention_obligation": "7, auto",
        "appcodechecker": true,
        "updatechecker": false,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "config_is_read_only": false,
        "forcessl": true,
        "log_type": "syslog",
        "logfile": "",
        "loglevel": 3,
        "syslog_tag": "Nextcloud",
        "log_authfailip": true,
        "log_rotate_size": 1048576,
        "theme": "",
        "share_folder": "\/Shared",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_previews": false,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "port": 6379
        },
        "upgrade.disable-web": false,
        "debug": false,
        "mysql.utf8mb4": true,

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
user_sql

### Client configuration
**Browser:**
Firefox and Chromium

**Operating system:**
Debian

Before I past a log of unnecessary log information, could you please let me know what you exactly need?

**Comment by marcelklehr** [comment]
The latest version should have improved performance somwhat. Can you confirm that?

**Comment by mbrandis** [comment]
Yes, thank you it looks way better. The load is still high, but round about 50% lower compared to before! Thank you!

Attached a comparison. I installed the update on the 26. and used it with multiple browser on the 27. and 28.

![load-nextcloud-bookmarks](https://user-images.githubusercontent.com/4790494/50522322-96221b80-0aca-11e9-8bef-a78c671aadb8.png)

**Comment by marcelklehr** [comment]
Thanks :)
