### ISSUE TITLE
[Enhancement] Open Details panel on adding a bookmark

### ISSUE THREAD

**Issue by mat-m** [nextcloud/bookmarks#627]
When we add a bookmark through the favelet, we have a pop-up with all fields (tags, link, title, description)
When we add a URL to the bookmark app through the "+" button, Default title  and description are filled, but not the tags. 

I think it makes sense to open the Details panel when you add a bookmark, so you can add tags or update Title & Description in the same workflow.

**Comment by marcelklehr** [comment]
Yes, that makes a lot of sense! Thanks for the feedback! :)
