### ISSUE TITLE
Undefined variable: folderId

### ISSUE THREAD

**Issue by ShapeShifter499** [nextcloud/bookmarks#636]
### Steps to reproduce
1.  Installed bookmarks app using admin account
2.  Saw error popup in log under index.php/settings/admin/logging

### Expected behaviour
No error

### Actual behaviour
Got an error in log
Undefined  variable: folderId at  /usr/share/webapps/nextcloud/apps2/bookmarks/lib/Migration/Version000014000Date20181029094721.php#74

### Server configuration

**Operating system**:  
Arch Linux
Linux kumo 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux

**Web server:** 
Server version: Apache/2.4.37 (Unix)
Server built:   Oct 23 2018 18:27:46

**Database:**
MariaDB
mysql  Ver 15.1 Distrib 10.1.37-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP
PHP 7.3.1 (cli) (built: Jan  8 2019 16:39:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.1, Copyright (c) 1999-2018, by Zend Technologies

PHP-FPM
PHP 7.3.1 (fpm-fcgi) (built: Jan  8 2019 16:39:04)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.1, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.0

**Bookmarks version:** (see Nextcloud apps page)
0.15.1

**Updated from an older Nextcloud or fresh install:**
Fresh install

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
[root@kumo nextcloud]# sudo -u http php occ app:list
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bookmarks: 0.15.1
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - groupfolders
  - user_external
  - user_ldap
[root@kumo nextcloud]#
```

**Nextcloud configuration:**

```
[root@kumo nextcloud]# sudo -u http php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "kumo.failserv.com",
            "kumo.lan",
            "192.168.1.15"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0
        },
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "knowledgebaseenabled": true,
        "allow_user_to_change_display_name": true,
        "auth.bruteforce.protection.enabled": true,
        "filesystem_check_changes": 1,
        "filelocking.enabled": true,
        "max_filesize_animated_gifs_public_sharing": -1,
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "installed": true,
        "loglevel": 2,
        "overwrite.cli.url": "https:\/\/kumo.failserv.com",
        "maintenance": false
    }
}
[root@kumo nextcloud]#
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by marcelklehr** [comment]
Thank you for the feedback! :)

**Comment by ShapeShifter499** [comment]
@marcelklehr does this affect anything in my setup?   Guessing based off the name of the file path it has to do with migration but I'm not sure much else from there.
