### ISSUE TITLE
Error on import: Doctrine\DBAL\Exception\SyntaxErrorException

### ISSUE THREAD

**Issue by dev107** [nextcloud/bookmarks#637]
Hi there! I'm not able to import bookmarks from Firefox or Chrome as HTML file. I got an error like this:

Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'INSERT INTO `oc_bookmarks` (`url`, `title`, `user_id`, `public`, `added`, `lastmodified`, `description`) VALUES(?, ?, ?, ?, , UNIX_TIMESTAMP(), ?)' with params ["http:\/\/xxx.com\/", "xxx | xxx", "myuser", 0, ""]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' UNIX_TIMESTAMP(), '')' at line 1

Reproduce:
1. Go to bookmarks
2. Left side Settings -> Import
3. Server error 500 occurs and the log is filled with messages above

Versions:
Nextcloud 15.0.0
Bookmarks 0.15.1
mysql  Ver 15.1 Distrib 10.1.37-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
apache2 2.4.25-3+deb9u6
php 7.0.33-0+deb9u1

**Comment by metalcated** [comment]
Same issue here, I was just about to post the same bug. 

Thanks

**Comment by Bananenschreck** [comment]
Go into your exported .html bookmark file and remove everything tagged <h3>.
After removing these you can upload them into nextcloud without any hassle.

at least this fixed it for me.
