### ISSUE TITLE
FR: Disable parsing remote content when adding bookmark for privacy reasons [$30]

### ISSUE THREAD

**Issue by gerroon** [nextcloud/bookmarks#647]
Hi

Can you please add an option to disable parsing the urls for thumbnails and additional information for the bookmarks? 

The reason is that the current way of adding bookmarks leaks private information as in reparsing all those bookmarks again. The user might have added those bookmarks in a differnet browser in different location with privacy in mind. Now when the user imports those bookmarks or adds them using synching with Floccus, all those urls will be reparsed therefor the data will be leaked by the Nextcloud server.

thanks

**Comment by mikec83** [comment]
+1

**Comment by marcelklehr** [comment]
Hey,
Thank you for your feedback! I understand your concern and it sounds like a reasonable thing to do.

**Comment by gerroon** [comment]
thanks for considering

**Comment by akidburn** [comment]
+1
