### ISSUE TITLE
Errors accessing bookmarks via API

### ISSUE THREAD

**Issue by apiraino** [nextcloud/bookmarks#649]
For some reason POST and PUT to the bookmark API endpoint do not work.

```
$ curl -i -X POST -u $NC_USER:$NC_PASS \
    "https://myserver.com/apps/bookmarks/public/rest/v2/bookmark?url=https%3A%2F%2Fwww.ddg.com"
```
I get a: HTTP/1.1 200 OK a list of my bookmarks.

```
$ curl -i -X PUT -u $NC_USER:$NC_PASS \
    "https://myserver.com/apps/bookmarks/public/rest/v2/bookmark/100?record_id=100&title=hey
```
I get a: HTTP/1.1 405 

### Steps to reproduce
1. Create a device auth token like [explained in the documentation](https://docs.nextcloud.com/server/stable/user_manual/session_management.html#managing-devices)
2. Run the example above

### Expected behaviour
A new bookmark should be created or modified

### Actual behaviour
The POST receives a 200 instead of a 201
The PUT receive a 405

### Server configuration

**Operating system**: Ubuntu 18.04.1 LTS

**Web server:** apache 2.24

**Database:** MySql 7.x

**PHP version:** 7.0.2

**Nextcloud version:** (see Nextcloud admin page) 15.0.2

**Bookmarks version:** (see Nextcloud apps page) Bookmark 0.16

**Updated from an older Nextcloud or fresh install:** fresh

**Signing status:**
no error

**List of activated apps:**
not relevant

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "myserver.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "overwrite.cli.url": "https:\/\/myserver.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "log_type": "file",
        "logfile": "\/var\/www\/myserver.com\/logs\/nextcloud.log",
        "loglevel": "0"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** none

**Operating system:** : Ubuntu 18.10

#### Web server error log
none

#### Web server access log
```
a.b.c.d - myuser [25/Jan/2019:23:29:46 +0100] "POST /apps/bookmarks/public/rest/v2/bookmark?url=www.ddg.com HTTP/1.1" 200 7874 "-" "curl/7.61.0"
```

#### Nextcloud log (data/nextcloud.log)
none

#### Browser log
none

**Comment by marcelklehr** [comment]
Mh. I can reproduce the 200 OK for POST, but not the 405 for the PUT.

**Comment by apiraino** [comment]
btw I have a 405 also on the DELETE http verb. I'll try to investigate a bit, too; seems like the API router is broken :thinking:

**Comment by apiraino** [comment]
A little more debug on the issue. I tried adding four more endpoints to `appinfo/router.php` (and the relevant code in the controller) to see which are mapped:
```
    ['name' => 'bookmark#testget',     'url' => '/public/rest/v2/test-get', 'verb' => 'GET'],
    ['name' => 'bookmark#testpost',    'url' => '/public/rest/v2/test-post', 'verb' => 'POST'],
    ['name' => 'bookmark#testdelete',  'url' => '/public/rest/v2/test-delete', 'verb' => 'DELETE'],
    ['name' => 'bookmark#testput',     'url' => '/public/rest/v2/test-put', 'verb' => 'PUT'],
```
Turns out that only GET returns a `200`, all the others return a `405`.

Don't know much of the Bookmark app internals, maybe I'm doing something wrong. I don't understand at what level the issue is (the Apache config should be ok)

**Comment by marcelklehr** [comment]
Is it possible that the request URL is wrong?

**Comment by apiraino** [comment]
Could be but I'm not sure. Leaving aside my experiments for a moment, do you confirm the [API documentation](https://github.com/nextcloud/bookmarks/blob/master/API.md) is up to date? I expect for example this DELETE request to be correct:
```
$ curl -i X DELETE -u $NC_USER:$NC_PASS \
    "https://my-nc-cloud.com/apps/bookmarks/public/rest/v2/bookmark/107"
```
I receive a 405 with error:
```
<p>The requested method DELETE is not allowed for the URL /apps/bookmarks/public/rest/v2/bookmark/107.</p>
```

**Comment by marcelklehr** [comment]
Good point! What does the URL look like when you open the bookmarks app ui in your browser?

**Comment by apiraino** [comment]
The same DELETE request from the browser looks like (checking the network traffic tool):
```
curl 'https://my-nc-cloud.com/index.php/apps/bookmarks/bookmark/107' \
     -X DELETE \
     -H 'User-Agent: ...' \
     -H 'Accept: application/json, text/javascript, */*; q=0.01' \
     -H 'Accept-Language: de,en-US;q=0.7,it;q=0.3' \
     -H 'requesttoken: ...' \
     -H 'X-Requested-With: XMLHttpRequest' \
     -H 'DNT: 1' \
     -H 'Connection: keep-alive' \
     -H 'Cookie: ....' \
     --compressed
```
but the Bookmarks App uses other non-REST APIs (a CSRF is required)

**Comment by marcelklehr** [comment]
The URL shows what I suspected, though, you need the `index.php` in your REST path as well.

**Comment by apiraino** [comment]
Dang! You were right there :-)
The correct URL for the REST API is:
```
/index.php/apps/bookmarks/public/rest/v2/bookmark
```
Do you think the documentation could be enhanced on this or was it just me? In case I'll happly submit a small PR.

**Comment by marcelklehr** [comment]
Some people have URL rewriting in place that removes the index.php and others don't so the docs should probably have a note about this, to avoid issues like the one you ran into. I'm happy to merge :)
