### ISSUE TITLE
How can I save URL parameters?

### ISSUE THREAD

**Issue by job963** [nextcloud/bookmarks#652]
### Steps to reproduce
1. Add a bookmark with an URL containing parameters, eg. `http://my.domain.com/test?id=1234`. Parameter is **?id=1234**
2. Only the major URL http://my.domain.com/test will be displayed and opened on clicking
3. Using the android app, you can see that the full URL (incl. parameters ist stored)

### Expected behaviour
The parameters should be displayed and used for linking

### Actual behaviour
Just the major URL http://my.domain.com/test is displayed and linked/opened

**Comment by marcelklehr** [comment]
I cannot confirm this with v0.16.1 which version of the bookmarks app do you have installed? Also, how did you add the url? Try adding the URL in the web UI.

**Comment by bimplus-admin** [comment]
Oh, sorry, the example URL works! But not that one: www.soldesportal.de/anlagendaten.htm?091160

**Comment by job963** [comment]
Did you read my last comment? 
Error still exists - try the second URL

**Comment by marcelklehr** [comment]
Does the error still exist with the latest update?

**Comment by job963** [comment]
Thank you. With the latest update the issue is fixed.
