### ISSUE TITLE
Limit tag counting requests on multiple items update

### ISSUE THREAD

**Issue by apiraino** [nextcloud/bookmarks#655]
I've imported a pretty high number of bookmarks (~2500) using the API and I've noticed quite a lot of traffic and performance degrading of the Bookmark application.

One of the thing I've noticed is that on a bulk tags update (for example adding or remove a tag with multiple bookmarks selected) results in a proportional number of `/tag?count=true` being issued by the web application.

### Steps to reproduce
1. Select multiple bookmarks (say 3)
2. update tags on them
3. from the browser network traffic monitoring I see 3 `/tag?count=true` requests

### Expected behaviour
These kind of requests should be issued once at the end of the batch update

### Actual behaviour
Each bookmark update triggers a tag counting request

### Server configuration

**Nextcloud version:** 15.0.2

**Bookmarks version:** 0.16.1

**Comment by marcelklehr** [comment]
I haven't tested this, yet, but it sounds plausible that this might happen. The whole app needs a rewrite using vue.js anyway, so I will probably not tackle this before the rewrite. :/

**Comment by apiraino** [comment]
No problem, I'm happy there's a roadmap and you already put some thoughts on that :+1:

By the way, unrelated to this issue but in line with your rewrite thoughts: I think that also the backend could benefit from some attention on bulk updates. Namely the PUT and DELETE endpoints could greatly improve from accepting multiple items (that would save a lot of traffic from the client)

**Comment by marcelklehr** [comment]
This should be fixed with v2.x

**Comment by apiraino** [comment]
Thank you so much!
