### ISSUE TITLE
List view 3-dot menu unusable

### ISSUE THREAD

**Issue by jimbolaya** [nextcloud/bookmarks#662]
### Steps to reproduce
1. Open up bookmarks in List View
2. Click on 3-dot menu on right
3. Scroll down, menu disappears behind next item below. This menu works fine in Grid View

### Expected behaviour
The menu should be raised until I can make a choice or click somewhere else.

### Actual behaviour
I noticed the menu is persistent, but unviewable since it highlights the next entry below when you move the mouse to select an item. It appears to work in Grid View because there is enough space below the menu for the mouse to get into the menu. There isn't enough space for this behavior in List View.

## Server configuration detail

**Operating system:** Linux 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 5.5.62

**PHP version:** 

7.2.15-1+0~20190209065041.16+jessie~1.gbp3ad8c0
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 14.0.7 - 14.0.7.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** occ command line

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - admin_audit: 1.4.0
 - apporder: 0.6.0
 - audioplayer: 2.6.0
 - bookmarks: 0.16.2
 - bruteforcesettings: 1.3.0
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.8
 - dav: 1.6.1
 - deck: 0.5.2
 - dotclear: 0.7.4
 - encryption: 2.2.0
 - event_update_notification: 0.3.2
 - federatedfilesharing: 1.4.0
 - files: 1.9.0
 - files_external: 1.5.0
 - files_pdfviewer: 1.3.2
 - files_reader: 1.2.3
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - flowupload: 0.0.9
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - keeweb: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - mail: 0.11.0
 - mindmaps: 0.1.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.5.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - ocsms: 2.1.1
 - password_policy: 1.4.0
 - phonetrack: 0.4.3
 - polls: 0.10.0
 - provisioning_api: 1.4.0
 - richdocuments: 3.2.1
 - scanner: 0.1.1
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - spreed: 4.0.3
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_admin: 0.1.0
 - twofactor_backupcodes: 1.3.1
 - twofactor_yubikey: 0.4.1
 - updatenotification: 1.4.1
 - weather: 1.5.5
 - workflowengine: 1.4.0
Disabled:
 - circles
 - federation
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "14.0.7.1",
    "installed": true,
    "maintenance": false,
    "forcessl": true,
    "theme": "",
    "loglevel": 0,
    "log_rotate_size": 10485760,
    "trusted_domains": [
        "klaashome.org",
        "www.klaashome.org",
        "192.168.4.12",
        "shenandoah.appalachian.home"
    ],
    "secret": "***REMOVED SENSITIVE VALUE***",
    "share_folder": "\/Shared",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "production",
    "appstore.experimental.enabled": true,
    "trashbin_retention_obligation": "auto, 180",
    "auth.bruteforce.protection.enabled": true,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "overwrite.cli.url": "https:\/\/klaashome.org",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0

**Operating system:** Mint 17

## Logs

<details><summary>Browser log</summary>

```
N/A
```
</details>

<details><summary>Nextcloud log</summary>

```
N/A
```
</details>

<details><summary>Browser log</summary>

N/A
</details>

**Comment by mikec83** [comment]
+1.  Can't delete any existing bookmarks.

**Comment by tossican** [comment]
+1 Same issue.. Makes editing bookmarks an annoyance (having to switch view modes to get access to actions menu)
