### ISSUE TITLE
FR: REST Endpoint to solely check Authentication

### ISSUE THREAD

**Issue by zachtib** [nextcloud/bookmarks#664]
I'm working on an Android client for Bookmarks, and was looking for a simple way to check the credentials the user enters in the "Add Account" screen. Since I'm trying to support multiple Nextcloud instances / accounts, I want to be able to quickly check if the credentials entered are valid before I persist them and leave the screen.

Currently I'm doing this by just a call to `/bookmarks`, which works, but seems wasteful bandwidth and I/O wise. If there was a simple checkauth route that returned either a 200 or 401 status code, that would make things simpler for client development.

**Comment by marcelklehr** [comment]
Agreed! :)

**Comment by marcelklehr** [comment]
Ah, wait. There's a canonical way to login to nextcloud from clients, apparently: https://docs.nextcloud.com/server/stable/developer_manual/client_apis/LoginFlow/index.html

**Comment by marcelklehr** [comment]
I'll close this in favor of the mentioned login flow.
