### ISSUE TITLE
Bug: Nextcloud returns HTTP 500 when uploading large bookmark

### ISSUE THREAD

**Issue by rarapost** [nextcloud/bookmarks#666]
When I try to upload bookmarks with certain (long) URL to the NC server with  bookmarks app, server returns HTTP response 500.
Except this issue, bookmarks work as expected for another users.

### Steps to reproduce
1. in Chrome, create new profile, install floccus extension there
2. load bookmarks from attachment [Bookmarks_02.03.19.zip] to the this new profile
3. create or select account on Nextcloud with bookmarks app enabled, empty bookmarks
4. set synchronization in floccus against the NC server / account,  run it 

Postman or similar REST client probably also may be used for the test, but I didnť try it.

### Actual behaviour
After I start upload, I got HTTP response 500. 
I am attaching single row from log of NGINX , which acts as a proxy (between client and NC server).
[access.000.log](https://github.com/nextcloud/bookmarks/files/2922361/access.000.log)

Fragment of nextcloud.log with the response 500
[nextcloud-json.log](https://github.com/nextcloud/bookmarks/files/2922377/nextcloud-json.log)

Also attaching bookmarks causing an issue.
[Bookmarks_02.03.19.zip] (https://github.com/nextcloud/bookmarks/files/2922363/Bookmarks_02.03.19.zip)

Server: Nextcloud 15.0.4, docker fpm-alpine, with bookmarks 0.16.2, nginx proxy in front
Database: Mariadb 
PHP version: 7.2
Client: Floccus 3.2.7, Google Chrome

**Comment by marcelklehr** [comment]
Hello, I'm sorry for the delay. I cannot replicate this with bookmarks v0.16.3 and floccus 3.2.9. I didn't create a new empty profile, though, but that shouldn't matter, I think. Can you try again with the latest versions and report back? Thank you :)

**Comment by e-alfred** [comment]
This happened to me too as I encountered this bug: https://github.com/marcelklehr/floccus/issues/258

Specifically, Floccus created duplicate bookmarks which were very long if they contained a hash (#) and then Floccus sometimes showed an error 500 as it tried to sync those bookmarks to the server.

**Comment by marcelklehr** [comment]
Mh. The log posted above doesn't contain an actual error, which I'd need to diagnose this. Is somebody able to provide a log with the error that triggered the 500?

**Comment by Yogibaer75** [comment]
I had the same error and it was possible to solve it with the procedure for this error.
https://github.com/nextcloud/server/issues/10655

**Comment by ItsOnlyBinary** [comment]
I suspect i might be having an issue related to this one. seems the title field in the database is a little too short.

the bookmark its trying to sync is 148 char where the column is set to 140, it results in error 500 when trying to sync

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_bookmarks` (`url`, `title`, `user_id`, `public`, `added`, `lastmodified`, `description`) VALUES(?, ?, ?, ?, UNIX_TIMESTAMP(), UNIX_TIMESTAMP(), ?)' with params ["https:\/\/www.amazon.co.uk\/dp\/B01LWQGIUR\/?tag=pcp0f-21", "ASUS ROG SWIFT PG278QR, 27 Inch WQHD (2560 x 1440) Gaming monitor, 1ms, up to 165Hz, DP, HDMI, USB3.0, G-SYNC: Amazon.co.uk: Computers & Accessories", "neil", 0, ""]: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1
```

**Comment by marcelklehr** [comment]
@ItsOnlyBinary Which database and version are you using? With the latest version the title field should be a varchar(4096) :thinking:

**Comment by ItsOnlyBinary** [comment]
@marcelklehr I thought I was using the latest but maybe Ive had bookmarks installed in the past and removed it, when firefox broke syncing to nextcloud

**Comment by marcelklehr** [comment]
> I thought I was using the latest but maybe Ive had bookmarks installed in the past and removed it, when firefox broke syncing to nextcloud

You don't know whether you removed it? Firefox broke syncing to nextcloud bookmarks?

**Comment by ItsOnlyBinary** [comment]
many many moons ago you could reconfigure mozilla sync to sync to a custom server, i suspect i had bookmarked installed back then.

unfortunately ive run some stuff on the database that recreated all the tables for emoji support, so none of the creation dates are accurate

from migrations db:
```
"bookmarks"	"000014000Date20181002094721"
"bookmarks"	"000014000Date20181029094721"
"bookmarks"	"000016005Date20190402094721"
````

**Comment by marcelklehr** [comment]
I see what you mean.

Your migrations [look up to date](https://github.com/nextcloud/bookmarks/tree/master/lib/Migration). Can you run `DESCRIBE oc_bookmarks;` and paste the output?

**Comment by ItsOnlyBinary** [comment]
I changed title from varchar(140) -> varchar(256)
```
"id"	"int(11)"	"NO"	"PRI"	\N	"auto_increment"
"url"	"varchar(4096)"	"NO"	""	""	""
"title"	"varchar(256)"	"NO"	""	""	""
"user_id"	"varchar(64)"	"NO"	"MUL"	""	""
"description"	"varchar(4096)"	"NO"	""	""	""
"public"	"smallint(6)"	"YES"	""	"0"	""
"added"	"int(10) unsigned"	"YES"	""	"0"	""
"lastmodified"	"int(10) unsigned"	"YES"	""	"0"	""
"clickcount"	"int(10) unsigned"	"NO"	""	"0"	""
```

**Comment by marcelklehr** [comment]
Aha. It may indeed be that you missed a few versions of the bookmarks, before we had the migrations.

**Comment by ItsOnlyBinary** [comment]
that could also explain why it didnt seem to be showing bookmarks in folders correctly (wasnt sure if it was just me as ive not had a chance to look into it yet)

recommend the best way to ensure everything is up to date?

**Comment by marcelklehr** [comment]
Yeah, probably best to export your bookmarks, remove all bookmarks related tables and reset the bookmarks migrations. Then re-install the bookmarks app.

**Comment by ItsOnlyBinary** [comment]
thanks will do that

**Comment by marcelklehr** [comment]
Closing this for now. Please let me know if this is still an issue.
