### ISSUE TITLE
Not easy hundling on a touchscreen

### ISSUE THREAD

**Issue by dachilliou** [nextcloud/bookmarks#667]
Try "bookmarks" on any cellphone with a touchscreen
1. Trying to navigate through bookmarks is not easy because usually the tile under your finger gets drugged
2. Folder List is hidden 

I would rather if 
1. there where a "only view" mode
2. the "initially screen"  would be  a folder list instead of #all

**Comment by marcelklehr** [comment]
> Trying to navigate through bookmarks is not easy because usually the tile under your finger gets drugged

Aah, I didn't consider this. There are ways to improve this, though.

> Folder List is hidden
You can access the folder list by clicking on the menu icon at the top of the screen. This could be more accessible, though, I agree. Supporting a swipe right gesture would be nice for example.
