### ISSUE TITLE
Tags editing is b0rked

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/bookmarks#668]
Hej! Thank your for this great app. I finally found a replacement for my age-old Scuttle!

It would be nice if it was easier to add tags. Every time I press enter to add a tag, I have to click into the field again to add the next. It would be cooler, if I could type them in one go. Like in WordPress.

**Comment by kaffeeringe** [comment]
Sometimes saving the first tag takes so long that no tags are being saved.

**Comment by kaffeeringe** [comment]
I just realized: tags are actually added - but not shown. When I add tags and reload the page, tags are there.

**Comment by tossican** [comment]
> Every time I press enter to add a tag, I have to click into the field again to add the next

Use comma (",") between multiple tags, instead of enter.

Like so:
css,web dev,tutorial

**Comment by leggettc18** [comment]
I don't know if this is related, but I'm having an issue where when I type tags into the editor, it takes a couple of keystrokes and then stops taking anymore, like the textbox becomes unfocused. Then when I click back in to retype it, it clears out, and the cycle repeats itself. Not sure if its a browser problem or what. If I need to open a new issue let me know.

**Comment by marcelklehr** [comment]
@leggettc18 see #693

**Comment by leggettc18** [comment]
Ah thanks, didn't see that earlier. So I guess I'll just be on the lookout for plugin updates on my server then.
