### ISSUE TITLE
Feature Request: Sort options for tags in filter menu

### ISSUE THREAD

**Issue by tossican** [nextcloud/bookmarks#671]
First off, thanks for all your hard work!

Please provide an option for default tag sorting, and perhaps a toggle to select current mode (for quick switching).

Sorting by number of links can be really useful.. At times.. However, for general daily use, I would prefer the tags list to be in alphabetical order.

**Comment by marcelklehr** [comment]
Thanks for the feedback!
I agree that tag filtering is not as slick as it could be. I tend to think adding a sorting option doesn't improve the situation too much, however, as it kind of places the burden of finding a tag on the user that now has to consciously decide which sort order will get them to the target the fastest.

Over in #515 I outlined a few ideas on how tag selection could be improved. Feel free to join the discussion over there as well :)

**Comment by tossican** [comment]
Personally, I like options, the more the better.. Not sure I would call it a 'burden' myself, but I understand how having too many options can bother some people.

To be clear, I'm not talking about filtering in my suggestion. Just the normal list of "Here's all your tags" that appears on the left side of the page.

For me, I would relate it to a folder on your computer with 500 other folders.. Could you imagine if it would only sort those folders by how many items were in the folder, not by the name of the folder. It would drive me batty!.. Yes, sometimes knowing which folder had the most (or least) stuff in them would be useful, but more often than not, seeing the list by name is most useful.

I will join the other discussion.

**Comment by marcelklehr** [comment]
> To be clear, I'm not talking about filtering in my suggestion. Just the normal list of "Here's all your tags" that appears on the left side of the page.
> For me, I would relate it to a folder on your computer with 500 other folders.. Could you imagine if it would only sort those folders by how many items were in the folder, not by the name of the folder. It would drive me batty!

Yes, I completely understand. To be clear hen looking at your request what I see as an underlying need, though, is not to actually sort the tags -- that's not what you need, what you need is to find tags. Your suggestion is to improve finding by offering different ways of sorting, which works, but I think there may be better ways to improve finding tags, e.g. an input field for filtering the list of tags.

**Comment by cwmke** [comment]
While an input field could indeed be nice, I think having the tags sorted alphabetically by default might make some sense. That's my preference anyways. :smile:

**Comment by marcelklehr** [comment]
@jancborchardt :)

**Comment by jancborchardt** [comment]
So, alphabetical sorting rarely makes sense as the first letter of a tag has no bearing on its meaning. :) Sorting by usage at least gives some context.

@tossican could you describe your actual use-case or problem a bit more? That would help us find possible solutions. It’s often better to describe the problem than to ask for solutions, as we need to weigh lots of different requirements.

**Comment by stlehmann** [comment]
I agree with @tossican. Sorting tags alphabetically makes it easy to scroll through the list of tags and look for one or more specific tags. Of course you can always search for a tag directly with the search function but I find having an alphabetic list to browse in often much more useful. It is very much like the index page of a book which is also sorted alphabetically in order to make it easier to find things.

**Comment by marcelklehr** [comment]
I think the new UI will cover this need nicely without resorting to sort order as a means to speed up finding things. It has a multiselect tag input that allows you to filter-as-you-type your tags.
