### ISSUE TITLE
Feature Request: Option to hide/show/move tags in gridview.

### ISSUE THREAD

**Issue by tossican** [nextcloud/bookmarks#672]
I have sites with a large number of tags.. The result, in gridview, is the tags covering most of the thumbnail.. So I propose and option to hide the tags in this view mode.. Additionally, this could be expanded upon to provide a third option to (re)locate the tags under the card title.

**Comment by marcelklehr** [comment]
Hey, thank you for your feedback!
I think there's too little room beneath the titles, but I can imagine truncating the list of tags and only displaying the full list on hover. What do you think?

**Comment by tossican** [comment]
Sounds like a fair compromise.. 

To be honest tho, now the "..." works in list mode, I use that view almost exclusively. The only time I switch to gridview is when I can't remember exactly which of a number of sites is the one I want. At that point it is the thumbnails I am looking at.
