### ISSUE TITLE
Screeenly/screenly typo

### ISSUE THREAD

**Issue by Derkades** [nextcloud/bookmarks#674]
![image](https://user-images.githubusercontent.com/15892014/54884716-79507680-4e74-11e9-932b-2a3205c3a3ac.png)

It says both "screenly" and "screeenly". The correct website is "screeenly.com". "screenly.com" is a completely different service (which I unfortunately found out after spending an hour setting up docker in a VM to run the image)

**Comment by marcelklehr** [comment]
Ah, sorry for the trouble. Thanks for the feedback, though! :)
