### ISSUE TITLE
Delete all bookmarks doesn't delete folders

### ISSUE THREAD

**Issue by ingorichter** [nextcloud/bookmarks#683]
### Steps to reproduce
1. Import bookmarks with folder
2. Delete them all via Settings -> Clear data -> Delete all bookmarks
3. The list with folders is still there after all bookmarks are gone

### Expected behaviour
I expected that all bookmarks and folders have been deleted

### Actual behaviour
Folders are not removed

### Server configuration

**Operating system**:
Linux DiskStationNAS 3.10.105 (Synology)
**Web server:**
apache
**Database:**
mariadb 10.3.14
**PHP version:** 
7.2.17
**Nextcloud version:**
15.0.7
**Bookmarks version:** 
0.17.0
**Updated from an older Nextcloud or fresh install:**
Fresh install in docker container
**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- news
	- EXTRA_FILE
		- vendor/arthurhoaro/favicon/resources/cache/url5dc01745869f6e92c3fa545a45f004f2
		- vendor/arthurhoaro/favicon/resources/cache/urla20a738ac56ac26e0c1ebcce45fa2faa
		- vendor/arthurhoaro/favicon/resources/cache/urlbbd93c01f90665a875e7350529f31679
		- vendor/arthurhoaro/favicon/resources/cache/urlf371b708541d5ab2a50320679da6fbcb
		- vendor/arthurhoaro/favicon/resources/cache/url9ba6bb2d778d11fee9a42ccc0b644d3c
		- vendor/arthurhoaro/favicon/resources/cache/urla4f743c187ce7a4a21eba13d1face5ef
		- vendor/arthurhoaro/favicon/resources/cache/urlf548f507454c7b8598d916c638f46ad6
		- vendor/arthurhoaro/favicon/resources/cache/url19a61c5ab470bb5cb627e3efe796207d
		- vendor/arthurhoaro/favicon/resources/cache/url33232df877f3716497327473b9369d29
		- vendor/arthurhoaro/favicon/resources/cache/url2dcba437c78d8eae6092bc1ea24cba6d
		- vendor/arthurhoaro/favicon/resources/cache/urlb5303701bf5c865b1c0cd5ee9ac8856c
		- vendor/arthurhoaro/favicon/resources/cache/url24b412bbd4547de0b2415ce37056990e
		- vendor/arthurhoaro/favicon/resources/cache/url048e7becb9c8be1db9c3daa627d04247
		- vendor/arthurhoaro/favicon/resources/cache/url044f29e082bd58bb47269639eeccb234
		- vendor/arthurhoaro/favicon/resources/cache/url211493816445cefba59ad98fe0dd820d
		- vendor/arthurhoaro/favicon/resources/cache/url8c244b429f4a6fc138b5fe77734691e5
		- vendor/arthurhoaro/favicon/resources/cache/url1cda1a92c6b06d7ea31e2885b8db7d4f
		- vendor/arthurhoaro/favicon/resources/cache/url59ad9e7a19712285f453e764597eddf9
		- vendor/arthurhoaro/favicon/resources/cache/urlc383ac0bd00864dcf4da8d43f9cf149a
		- vendor/arthurhoaro/favicon/resources/cache/urlf016daa5301aea7c6330164e06d1ff01
		- vendor/arthurhoaro/favicon/resources/cache/url0eab74d0b067566b58731c7026260b47
		- vendor/arthurhoaro/favicon/resources/cache/urlc38b6fcdebdfd5997742d78c92fe8093
		- vendor/arthurhoaro/favicon/resources/cache/url61a180e3ed1e1db0bebc2535a9f715ec
		- vendor/arthurhoaro/favicon/resources/cache/urlc53c97223e46ed433bc4404a16e956d5
		- vendor/arthurhoaro/favicon/resources/cache/urlcac03ca1a6fb003422c2e35377ccc935
		- vendor/arthurhoaro/favicon/resources/cache/urld7bc829056e421cba1a1788c1a5da3d6
		- vendor/arthurhoaro/favicon/resources/cache/urlbc2aa54cf3239576df99f95e3893d598
		- vendor/arthurhoaro/favicon/resources/cache/urlbed001bdd8e6488d6e2d8a3def18f0da
		- vendor/arthurhoaro/favicon/resources/cache/url6036b9272b66a58d0545f8d039247dd4
		- vendor/arthurhoaro/favicon/resources/cache/url53cbda364f23728a3f89f69bb415ccc6
		- vendor/arthurhoaro/favicon/resources/cache/url859d7836100ff05d02dd676b92bf6afc
		- vendor/arthurhoaro/favicon/resources/cache/urlac77d57f8d58d03aff097cbe5af6b362
		- vendor/arthurhoaro/favicon/resources/cache/url6a7d16fd8d9bf28f9e7144d19ed1588d
		- vendor/arthurhoaro/favicon/resources/cache/url57b821c98493871b871b5cc6c04b67be
		- vendor/arthurhoaro/favicon/resources/cache/urlcdd2667c113e6644a1066cd9729d4800
		- vendor/arthurhoaro/favicon/resources/cache/url6f4f8612de5a43d46c749ec608645a9b
		- vendor/arthurhoaro/favicon/resources/cache/url1af4208ed972f6e1deb16ec7b4e159d7
		- vendor/arthurhoaro/favicon/resources/cache/url64b33416cd6c26f770cf50c386eb8bf6
		- vendor/arthurhoaro/favicon/resources/cache/url0377bbd79d05462d99459546664d9f62
		- vendor/arthurhoaro/favicon/resources/cache/urlbfb1ef350171d7c7068e27d645e50535
		- vendor/arthurhoaro/favicon/resources/cache/url068ead74d0884c90edd325965056ce2b
		- vendor/arthurhoaro/favicon/resources/cache/urlac3b0f667177c9565ac8d01752f96dda
		- vendor/arthurhoaro/favicon/resources/cache/url3ceeee62108cf515bd4caa51bbe8868f
		- vendor/arthurhoaro/favicon/resources/cache/urlfa47832cfcabe2f60accdc5bb62b9d37
		- vendor/arthurhoaro/favicon/resources/cache/url5fc4562709ad0ad43969873944814378
		- vendor/arthurhoaro/favicon/resources/cache/url7982149656515036411fe2bcccdd27d3
		- vendor/arthurhoaro/favicon/resources/cache/urlf496b644712e852e2b9b8b98e9c8cd72
		- vendor/arthurhoaro/favicon/resources/cache/url6e282f0f716ef6c30074817ced23cd93
		- vendor/arthurhoaro/favicon/resources/cache/urle47f9a66b6ace9050ee2259657dc137e
		- vendor/arthurhoaro/favicon/resources/cache/url3bb346881e00117eea475d79d72eb1dc
		- vendor/arthurhoaro/favicon/resources/cache/url9c89b9fd5a1f8b403faa8c8ff5f5253c
		- vendor/arthurhoaro/favicon/resources/cache/urlf632e71340a7ad3d8633cf278e155b92
		- vendor/arthurhoaro/favicon/resources/cache/url6711cac74c9ca9f828bdb1b3a557f304
		- vendor/arthurhoaro/favicon/resources/cache/urlcf8172b5d3724449b1e54eeb40d959ac
		- vendor/arthurhoaro/favicon/resources/cache/url193bcabbf76f898d02bbd2df8b7e638f

Raw output
==========
Array
(
    [news] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [vendor/arthurhoaro/favicon/resources/cache/url5dc01745869f6e92c3fa545a45f004f2] => Array
                        (
                            [expected] => 
                            [current] => eea32f32a796fb082a641b7c16ef1b2d7557c9a0abe8568d146c95ca8d2a0a2019a554911dcc2fd9590efd33b8604861abb24c5e2d8f37295a6eb51e3463ada7
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urla20a738ac56ac26e0c1ebcce45fa2faa] => Array
                        (
                            [expected] => 
                            [current] => 7f6e4be66042e39f968096fe979916422bf02810ed6834e7f145d8839724690a1655ab2fe81c8e6be70c1920bc4bf60eeb8075c1e1616e7ebb25cf5ebca86381
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlbbd93c01f90665a875e7350529f31679] => Array
                        (
                            [expected] => 
                            [current] => b291bc3d6a40ea3640737ea7839196da9686d5932af2a18dd69783ecbdd47daa6c679c2c3bd05401e8b80933c71ed9e276352e83928bb9fb7b7e4254f053602a
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlf371b708541d5ab2a50320679da6fbcb] => Array
                        (
                            [expected] => 
                            [current] => c6641895b6d64470c978c63a604c8fa05209678c142503f419fb902d959dcb8ba3c95b69761f9c74a53e032ba7787010f92c4ecc8e799c2a67d5965109ffd710
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url9ba6bb2d778d11fee9a42ccc0b644d3c] => Array
                        (
                            [expected] => 
                            [current] => 0586f643b1b42ed69f317825d549fe4e5911dd4bdf8dc9fe620b426d53b857d8d50484924c18d76295c9d272318774db5652435ead552f6539fab82d34870d6d
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urla4f743c187ce7a4a21eba13d1face5ef] => Array
                        (
                            [expected] => 
                            [current] => 7055976483327c82717e88354d12f6799c1e06efedae8d5c542c0c9f4605b637ec481905d02f8ab9c9f104a86e3740f6f059b6c79fe3c00fa429bf30c757b36f
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlf548f507454c7b8598d916c638f46ad6] => Array
                        (
                            [expected] => 
                            [current] => eea839055b1c681362c5ec5b12a38e344e6b6dd682d799d097f574f3c966c2508b3f2b5eeba1aa1a647d371513bde0ea104b0ef88beae007a734ff8d2763d1a6
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url19a61c5ab470bb5cb627e3efe796207d] => Array
                        (
                            [expected] => 
                            [current] => 63821ee187966fd88fad3d243a0e6592ab5b4ccf67ea35f4c5761fa2444e51e05bb5092182d181d0c283fcc3b14b3fceddebc622a73d0d3943f3dd9dd39b6d07
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url33232df877f3716497327473b9369d29] => Array
                        (
                            [expected] => 
                            [current] => 0e8168cb48110c49a3653dc445329d1c69fce134dd1c4210638d68b36009bb1ac26760be2532d59f2a9aa8e8f3b908b1cb6edfcf3dcb75f1ea80c0f615d53619
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url2dcba437c78d8eae6092bc1ea24cba6d] => Array
                        (
                            [expected] => 
                            [current] => 4d15bd543b6ff529f98024e76bbc681fdfae203d967c06b986ab847427866a0f5d9017b809f5d61d0df195eaac34d8c43d97716221fd4c708c1a868db2a8cb9c
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlb5303701bf5c865b1c0cd5ee9ac8856c] => Array
                        (
                            [expected] => 
                            [current] => 50d728d2709c0e5ecaee8620ccbc29f2fb0b0db68fe03ece680d2a6145d1a6ba5faf8dd223130b8c5e5cd6f8989e0d4169f6eb7342f3f383f067f7a6783e1bf9
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url24b412bbd4547de0b2415ce37056990e] => Array
                        (
                            [expected] => 
                            [current] => b8da94316bd94d76069ce387e619d7c3db348802b03ed60053c4288e672b40b5a58a52ff966edf2080e96fb7cdb5d0ef133a9a384a44cbd85bac96398d7b6f20
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url048e7becb9c8be1db9c3daa627d04247] => Array
                        (
                            [expected] => 
                            [current] => b0553fb09eef03113280b874771955916b6160ab3b8b62ee3819e497a7c132ac3d9d83afefda3e93edd4e4bb570d4d59bc7d1b814bf544120a967c0782b80b13
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url044f29e082bd58bb47269639eeccb234] => Array
                        (
                            [expected] => 
                            [current] => 3839d6988aba3de4419a89844b5f7ec11932e432904d378bb44a6bd19b1dbedb92a01ce6a5e2b6998696e68ae356d33610fdf907fba90cafc1dc41b8817645de
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url211493816445cefba59ad98fe0dd820d] => Array
                        (
                            [expected] => 
                            [current] => a355c4d4f465bd4a286c8a619a443f47139e054fc1c739027c41778c453af396a0bc022d161c8a11e7da642aeccff174c79ed6742649ef566da572ab89ffb483
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url8c244b429f4a6fc138b5fe77734691e5] => Array
                        (
                            [expected] => 
                            [current] => 25fb8d4711bcdcd2f22d7ac646575d0e0c5d5363591246fc04e5874c5223c59627f26253e3bcaa3538c3a9d474f38d66640f57bfd508da24d44c1fa1d25d44d9
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url1cda1a92c6b06d7ea31e2885b8db7d4f] => Array
                        (
                            [expected] => 
                            [current] => 5e809092e19e95a0c75e768aa5383bfbb78feafdf806a3d8c1945d874bf7e3d912d92650d6275d4b00b605ad6fd6db38e005d56591c4db5c2646506a2bb6db67
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url59ad9e7a19712285f453e764597eddf9] => Array
                        (
                            [expected] => 
                            [current] => be7d960cdf663a5b25ea4f505f369609d59afc0d5fb2044a1fc5f577605c34a090645dab7d40e2dbcde42baeb81e851cd90eb5682bb1c50668f55cfdad772386
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlc383ac0bd00864dcf4da8d43f9cf149a] => Array
                        (
                            [expected] => 
                            [current] => b7b7dfb219d225fb9dad10dadce079bf10c85ed6bbca2a51e8b8ff86396ab2da8bd5f73c0ceda2980e84d56f6ca146cd29b25645d7f6ba414ad54b78026aa5ea
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlf016daa5301aea7c6330164e06d1ff01] => Array
                        (
                            [expected] => 
                            [current] => df2cabadc5978845ea33f0babec666ff7890f4a3096ce246b5c78ddcd66cbdfc11df19e9e91531afad94f8c1cbfecbee889bef3020198f96712b93eb9e93240d
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url0eab74d0b067566b58731c7026260b47] => Array
                        (
                            [expected] => 
                            [current] => 60c8fb39217abe54c722c051a6693341662c9fd0f19a876758e6927739e9bf2b89f9985a382ed5b830adaaf49bdb30fbc062e197d4ed48f1c9cb58cfcd078703
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlc38b6fcdebdfd5997742d78c92fe8093] => Array
                        (
                            [expected] => 
                            [current] => 3d76a0e4ed301c20392297a097de0ece9f3939a93ccf58ff1cef17f044877836d7a71ec403d6abf8362fbcff61ea10ef646f019e8a11e74a60f8b25adb9db613
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url61a180e3ed1e1db0bebc2535a9f715ec] => Array
                        (
                            [expected] => 
                            [current] => e6a60e1abbfe2446c13a735355f06d3a49e1f32fc1576184e8e82130a12cb4746ad3d15bad515adc155d33e824aef5beca8e122272710c58cb190d945ece2306
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlc53c97223e46ed433bc4404a16e956d5] => Array
                        (
                            [expected] => 
                            [current] => 585374306aab01581b5819d81ce87c59c7dba34846d9cc19a850e9b8536d2654c19a2d24a6bbfb867afe7761b3fc24dd5e5e2df320123c02ad46102071f031f8
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlcac03ca1a6fb003422c2e35377ccc935] => Array
                        (
                            [expected] => 
                            [current] => 43bb85fb86562f9a2467ada6cdfebf8782f93260cc2bbcfed7f1f4686a6d30e53d259822e93540944a1dfa66fe1891a81b44890a43f652c504959de9407ae429
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urld7bc829056e421cba1a1788c1a5da3d6] => Array
                        (
                            [expected] => 
                            [current] => 395a56d26182695d9b3a944b8e5c2b05a3272b57898cdd20ee705d83167c0e0dccb84cb729864ce866b70b371a7bac18c7b4da50c81c0ce8b1841d5f2a629b76
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlbc2aa54cf3239576df99f95e3893d598] => Array
                        (
                            [expected] => 
                            [current] => eb7fcb849f19440030da529e18e11fb134d85757c8ec0c023ff46e6bf08e973da3d111036a910f908ab5a48ba8dca2fd6d54b2a979d87279443feec2ed1bd26c
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlbed001bdd8e6488d6e2d8a3def18f0da] => Array
                        (
                            [expected] => 
                            [current] => f8b6fc202f61d809df40a46e02d33060055e9ae5cbccf743125cb0ffe401f947a23aa940e06c76aab10aa31cea1f3ca058febaa867f81c5f9e59d00605470f74
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url6036b9272b66a58d0545f8d039247dd4] => Array
                        (
                            [expected] => 
                            [current] => 380beee4f18cb5fbcc9c8b6d39a6450c0e38d9c68893799a913a4d7a8563d1e3b7177ff56d08c0cbd391ae86bd5183ac3128bcdbcf2fcbfb7238e04fe7ae4061
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url53cbda364f23728a3f89f69bb415ccc6] => Array
                        (
                            [expected] => 
                            [current] => dba2755657ebe18f09f7e0d636d67d05067daae6fef38168f3abfbd1df727ebb972d94ed3246ffa6464825896dfd86cf102254b433d84b59c043d59ad73512f3
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url859d7836100ff05d02dd676b92bf6afc] => Array
                        (
                            [expected] => 
                            [current] => 8deddea8d4b2c11f13771fb29c9a46f1e1be843522df29c5c960f5808845ca2623a9568c6277e43f77b2e75a99b199b25e9306a7c847b6e8f6ffc3b30ccbf1b3
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlac77d57f8d58d03aff097cbe5af6b362] => Array
                        (
                            [expected] => 
                            [current] => 48703c28d8ea327747d04e745fd72f23783b8315ba4d0b8f0de6f5ee8e283ecde5f1f3fc3cd2c0c6f0a6d5f579d52f5963feb962ce40062267cf667f5915d2ae
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url6a7d16fd8d9bf28f9e7144d19ed1588d] => Array
                        (
                            [expected] => 
                            [current] => 7907835354da2883826a8dbcbbecb58388441c4777530b28d4f9491687df718132111d63683907db37e6b0bd951492dc18f25d2c121500ffa46a1dfcb77c825c
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url57b821c98493871b871b5cc6c04b67be] => Array
                        (
                            [expected] => 
                            [current] => cb5f71a9bc54244a1c4fde34a3526fbfe92bc4e266e59ce51c8ffaf2a840f4db741f3c819ea3a86ef9864d5fd223bbd3d896bf92b9a71fb686f1bfb9cce5410c
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlcdd2667c113e6644a1066cd9729d4800] => Array
                        (
                            [expected] => 
                            [current] => 904bd0f4a74d46deaba6b08b12947310def9f8039d7d5f6ea83eba15c5fb7f56c7d43d7910cb33e677fc59ac7bef5cc231f1f2d0b2af24c447c546e2d8803156
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url6f4f8612de5a43d46c749ec608645a9b] => Array
                        (
                            [expected] => 
                            [current] => e58765bb3001e92f11685f5f35b797fe7710ce3fd9d71687193224b241d63f5e3aad64dafd997c977b3b2e65de534d9a815b35e5b998ee65ab0d31653cf6ee44
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url1af4208ed972f6e1deb16ec7b4e159d7] => Array
                        (
                            [expected] => 
                            [current] => 070441af60732b7093528cefa091e111fe0ce917452f6cccef9cf2fb596accf6533d4655da1a524f46852ec795e83383871784b6fa5b43b29b615cd52eecd465
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url64b33416cd6c26f770cf50c386eb8bf6] => Array
                        (
                            [expected] => 
                            [current] => 5303470ce018f55d1e4c9a6a757fd264a61b424222f3c095c6826a84e21b5d970b8143002c35e39dad9a5b62f762f0fb1af545fc8d3e215f6433359662c16c8c
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url0377bbd79d05462d99459546664d9f62] => Array
                        (
                            [expected] => 
                            [current] => 794e5008a17c0780e24e093e200b40f733a6263b790e0f1767e0a547c277c47f09618cf592aff48295251ef671f8980d1df8f1313e0db6e563647bbe71066e44
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlbfb1ef350171d7c7068e27d645e50535] => Array
                        (
                            [expected] => 
                            [current] => 34b00a8db91cd987ce151b93199a88c2e3254fc87e5ad44dbb17c9c2725c7151ea3d99e251ca9d9314618c8e795230854cd82b0715677ccc28e131b63215441b
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url068ead74d0884c90edd325965056ce2b] => Array
                        (
                            [expected] => 
                            [current] => 33b33e11ab91b7d214dc41ed73f52bd27583634ef183453c299913f419968e25c2da9e8802b7fe2b5c6c75be1026ba9b5a30c95e20c7ca4100fe9bdda1908ca5
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlac3b0f667177c9565ac8d01752f96dda] => Array
                        (
                            [expected] => 
                            [current] => 371ea245603aa5e16bf3fb984c82cd75092cabdb81fd3463d2fdc0464ec1e10f9e9c0eb68955cb9f0688f88934076c4aa7e992eb097e24f4dc4d1bd4e0085c85
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url3ceeee62108cf515bd4caa51bbe8868f] => Array
                        (
                            [expected] => 
                            [current] => 2250e9d2aacfcbd1ceea902c77c4f0fdd8f186c4d86ce42749e356185a815e8bc722504268f122dfb8ef9f3bbb1e5203cde0f96f929897cbb58828cfb83f67c4
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlfa47832cfcabe2f60accdc5bb62b9d37] => Array
                        (
                            [expected] => 
                            [current] => 04c48b30a22bd19c5682128f687141d489969db7c12ba04c7efbed5154b44cd7b4a613142124b6fa5413acb31a1990befd56da94cdcec477e5380becba8ed0fb
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url5fc4562709ad0ad43969873944814378] => Array
                        (
                            [expected] => 
                            [current] => e761e1ed7407b6226b49accc1bfc9c77ded6fd26c17c6f147b00b35f5c3f53a1031ff7057ed044114066a8ab733f283d7f3e0fa623ecdba72a8ab3f8b3a608dc
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url7982149656515036411fe2bcccdd27d3] => Array
                        (
                            [expected] => 
                            [current] => d2ad7ce2179fea0a900835ec22556a4d622f9839312d5b63d967eb634f8feafb6e570a1a5fe109520185ce8d90ef4570359871a163ad323358690f864e260bbd
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlf496b644712e852e2b9b8b98e9c8cd72] => Array
                        (
                            [expected] => 
                            [current] => 9c24b75117aba549b7f80f15557dc4785d7730e3f71ded4f1825c6808ea0004a3cc6dfbb9016f1a9d1806a003268d80d1e7e0441ab458a3c07962c80da68645c
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url6e282f0f716ef6c30074817ced23cd93] => Array
                        (
                            [expected] => 
                            [current] => 9e7c75015afa74718aae80257057ee3b1306f1c3c6f3fa9447bc4de54df626537456381b364493aec7ae2a9f79e9ac6be29613d30258a23180c7997f0c5781ac
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urle47f9a66b6ace9050ee2259657dc137e] => Array
                        (
                            [expected] => 
                            [current] => 711b296b74acc2181f94ac3a3cfc30242f5a384bb014342572ffa3f8ff7d2a3efbd2b1115956ab4f94827fd21ea2e3397591df3848b7a2fbe80306ac6f78cc44
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url3bb346881e00117eea475d79d72eb1dc] => Array
                        (
                            [expected] => 
                            [current] => d30b2431c5b8bf5f3121b906aa4b5c7eef77f8b3bd2647b510a7e4290c0247d72b107431f751d45417430bb40a5725bf878122ab444073bf6777f00b7cb98536
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url9c89b9fd5a1f8b403faa8c8ff5f5253c] => Array
                        (
                            [expected] => 
                            [current] => 57024e062cde5297b55cc8d10ef223a611d995d23fe0050f83bd633d7f84a1bcbd921d0fbb76cd7e0ff95978d77c7eab108876f9de38f612869e1b1eea5a6ff3
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlf632e71340a7ad3d8633cf278e155b92] => Array
                        (
                            [expected] => 
                            [current] => 1a9bd147a89fb4a5249ac55429f227daa6b9176b74d7ab42fdcd878994bcb1e0550b01715b989ff797f1c5e1c53796ff38bb49bced119e52a83b74db9d6aba72
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url6711cac74c9ca9f828bdb1b3a557f304] => Array
                        (
                            [expected] => 
                            [current] => 5c5b95a6c3585b66b42f9d6e002980c76c2f4b4f4d08e01258c13f0216fe9ba858ffcf9a492fea80c2e20d38c003f098753b37fc11512e4dfaa2b6768585757d
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urlcf8172b5d3724449b1e54eeb40d959ac] => Array
                        (
                            [expected] => 
                            [current] => 745a9dda97c68516ccc49fe12fc49c47568567979a70feeea8a937d75f9dfe4f9c5217ec8868ba6b84ba2ae6a7979a244b033576fecfa0338485e3cdcc5ebafb
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/url193bcabbf76f898d02bbd2df8b7e638f] => Array
                        (
                            [expected] => 
                            [current] => a3c6572e2cc8743721cbc7c7c21419f53f0b36438140974cce7bd963e6ea4357bb84010a3915de2605ee1cbab426c10404a46dd33f76fce85f48c7b6a5150421
                        )

                )

        )

)
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled: 
- accessibility: 1.1.0 
- activity: 2.8.2 
- announcementcenter: 3.4.1 
- bookmarks: 0.17.0 
- calendar: 1.6.4
- circles: 0.16.2 
- cloud_federation_api: 0.1.0
- comments: 1.5.0
- contacts: 3.1.0
- dashboard: 6.0.0
- dav: 1.8.1
- deck: 0.5.2
- federatedfilesharing: 1.5.0
- federation: 1.5.0
- files: 1.10.0
- files_accesscontrol: 1.5.
 - files_automatedtagging: 1.5.0
- files_mindmap: 0.0.13
- files_pdfviewer: 1.4.0
- files_sharing: 1.7.0
- files_texteditor: 2.7.0
- files_trashbin: 1.5.0
- files_versions: 1.8.0
- files_videoplayer: 1.4.0
- firstrunwizard: 2.4.0
- gallery: 18.2.0
- logreader: 2.0.0
- lookup_server_connector: 1.3.0
- metadata: 0.9.0
- news: 13.1.6
- nextcloud_announcements: 1.4.0
- notifications: 2.3.0
- oauth2: 1.3.0
- occweb: 0.0.4
- password_policy: 1.5.0
- provisioning_api: 1.5.0
- serverinfo: 1.5.0
- sharebymail: 1.5.0
- social: 0.1.4
- support: 1.0.0
- survey_client: 1.3.0
- systemtags: 1.5.0
- theming: 1.6.0
- twofactor_backupcodes: 1.4.1
- unsplash: 1.1.3
- updatenotification: 1.5.0
- workflowengine: 1.5.0

Disabled:
- admin_audit
- encryption
- files_external
- user_ldap
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

{    "system": {        "htaccess.RewriteBase": "\/",        "memcache.local": "\\OC\\Memcache\\APCu",        "apps_paths": [            {                "path": "\/var\/www\/html\/apps",                "url": "\/apps",                "writable": false            },            {                "path": "\/var\/www\/html\/custom_apps",                "url": "\/custom_apps",                "writable": true            }        ],        "memcache.locking": "\\OC\\Memcache\\Redis",        "redis": {            "host": "***REMOVED SENSITIVE VALUE***",            "port": 6379        },        "instanceid": "***REMOVED SENSITIVE VALUE***",        "passwordsalt": "***REMOVED SENSITIVE VALUE***",        "secret": "***REMOVED SENSITIVE VALUE***",        "trusted_domains": [            "192.168.1.22:5678",            "cloud.familie-richter.synology.me"        ],        "datadirectory": "***REMOVED SENSITIVE VALUE***",        "dbtype": "mysql",        "version": "15.0.7.0",        "overwrite.cli.url": "http:\/\/192.168.1.22:5678",        "dbname": "***REMOVED SENSITIVE VALUE***",        "dbhost": "***REMOVED SENSITIVE VALUE***",        "dbport": "",        "dbtableprefix": "",        "mysql.utf8mb4": true,        "dbuser": "***REMOVED SENSITIVE VALUE***",        "dbpassword": "***REMOVED SENSITIVE VALUE***",        "installed": true,        "maintenance": false,        "loglevel": 2    }}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
```

### Client configuration
**Browser:** Firefox 66.0.3

**Operating system:** macOS 10.13.6

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
bookmarks:1:1
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More] bookmarks
New search handler registered search.js:67:4
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]

### Request
Request URL:http://192.168.1.22:5678/apps/bookmarks/bookmark
Request method:DELETE
Remote address:192.168.1.22:5678
Status code:
200
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade

### Response
{"status":"success"}
```

**Comment by marcelklehr** [comment]
Confirmed. :)
