### ISSUE TITLE
Error: Class 'OCA\Bookmarks\Controller\Rest\RedirectResponse' not found

### ISSUE THREAD

**Issue by linux0uid** [nextcloud/bookmarks#685]
### Steps to reproduce
1. Install the Bookmarks app to nextcloud server
2. Add some bookmarks.
3. Reload page.

### Expected behaviour
Displaying bookmarks without logging errors.

### Actual behaviour
On logging page you will see a lot of "Error: Class 'OCA\Bookmarks\Controller\Rest\RedirectResponse' not found" massages:

Error: Class 'OCA\Bookmarks\Controller\Rest\RedirectResponse' not found/var/www/html/apps/bookmarks/lib/Controller/Rest/InternalBookmarkController.php - line 248: OCA\Bookmarks\Controller\Rest\BookmarkController->getBookmarkFavicon(23818)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Bookmarks\Controller\Rest\InternalBookmarkController->getBookmarkFavicon(23818)/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... }}, "getBookmarkFavicon")/var/www/html/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... }}, "getBookmarkFavicon")/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("InternalBookmarkController", "getBookmarkFavicon", OC\AppFramew ... {}, { id: "23818 ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ id: "23818 ... "})/var/www/html/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { id: "23818 ... "})/var/www/html/lib/base.php - line 987: OC\Route\Router->match("/apps/bookm ... n")/var/www/html/index.php - line 42: OC::handleRequest()

### Server configuration

**Operating system**: Linux 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64

**Web server:** nginx/1.15.11 (fpm-fcgi)

**Database:** pgsql PostgreSQL 11.1 (Debian 11.1-3.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

**PHP version:** 7.3.4
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page) 15.0.7 - 15.0.7.0

**Bookmarks version:** (see Nextcloud apps page)  0.17.0

**Updated from an older Nextcloud or fresh install:**

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - announcementcenter: 3.4.1
 - apporder: 0.6.0
 - bookmarks: 0.17.0
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.4
 - camerarawpreviews: 0.6.5
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - contacts: 3.1.0
 - dav: 1.8.1
 - event_update_notification: 0.3.4
 - external: 3.2.0
 - extract: 1.0.0
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_accesscontrol: 1.5.0
 - files_automatedtagging: 1.5.0
 - files_downloadactivity: 1.4.0
 - files_mindmap: 0.0.13
 - files_pdfviewer: 1.4.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - group_everyone: 0.1.2
 - groupfolders: 2.0.4
 - groupquota: 0.1.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - metadata: 0.9.0
 - music: 0.9.4
 - nextcloud_announcements: 1.4.0
 - notes: 2.5.1
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - provisioning_api: 1.5.0
 - quota_warning: 1.4.0
 - radio: 0.6.4
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - spreed: 5.0.3
 - support: 1.0.0
 - survey_client: 1.3.0
 - systemtags: 1.5.0
 - theming: 1.6.0
 - theming_customcss: 1.3.0
 - twofactor_backupcodes: 1.4.1
 - twofactor_nextcloud_notification: 1.1.1
 - twofactor_totp: 2.1.2
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - admin_audit
 - audioplayer
 - encryption
 - files_external
 - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by linux0uid** [comment]
To fix this add the next line to bookmarks/lib/Controller/Rest/BookmarkController.php file:
use \OCP\AppFramework\Http\RedirectResponse;

**Comment by marcelklehr** [comment]
Thanks for reporting! Will be fixed with the next release.

**Comment by Jolopu** [comment]
I just updated to 1.0.1 but the same error keeps popping up in the log:
Error: Class 'OCA\Bookmarks\Controller\Rest\NotFoundResponse' not found
I looked into BookmarkController.php and the line 
use \OCP\AppFramework\Http\RedirectResponse;
is there. Didn't fix the issue though.

**Comment by marcelklehr** [comment]
Confirmed. Fix is released :sweat_smile:

**Comment by Jolopu** [comment]
1.0.2 works nicely. :-)
