### ISSUE TITLE
Can't add new tags

### ISSUE THREAD

**Issue by radoeka** [nextcloud/bookmarks#693]
### Steps to reproduce
1. Add a new bookmark
2. Add a new tag by typing the new tag
3.

### Expected behaviour
It should be possible to finish the new (not existing) tag

### Actual behaviour
While typing the app looks for matching apps and shows these.  After the 2nd character, it starts to search again.

I was able to enter new tags, by copying the desired tag and paste this into the tag window.  This way it is possible to enter new tags.

### Server configuration

**Operating system**: linux

**Web server:** apache

**Database:** sqlite

**PHP version:** 7.0.7

**Nextcloud version:** (see Nextcloud admin page) 15.0.6

**Bookmarks version:** (see Nextcloud apps page) 1.0.2

**Updated from an older Nextcloud or fresh install:** updated

**Signing status:** ok

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by j-ed** [comment]
I can confirm the described problem on my server.

**Comment by marcelklehr** [comment]
> While typing the app looks for matching apps and shows these. After the 2nd character, it starts to search again.
> I was able to enter new tags, by copying the desired tag and paste this into the tag window. This way it is possible to enter new tags.

I'm not sure I understand what you're saying. You add a bookmark, open its details and start to enter a tag name that doesn't exist at all, yet. But then what happens? I'm afraid I cannot reproduce this, at the moment.

**Comment by marcelklehr** [comment]
Scratch that. I just updated my dev instance, and can replicate this, now :/

**Comment by cpp-made-easy** [comment]
I can confirm this issue using NextCloud 15.0.7 and Bookmarks 1.0.2.
I can work around this by copying the comma-separated list of tags into the tag field (including a trailing comma).

**Comment by marcelklehr** [comment]
This is [a problem with jquery 3.4.0](https://github.com/select2/select2/issues/5485). I've reverted the upgrade to that version and this fixes this bug. I'll release the patch soon.

**Comment by LeSpocky** [comment]
> This is [a problem with jquery 3.4.0](https://github.com/select2/select2/issues/5485). I've reverted the upgrade to that version and this fixes this bug. I'll release the patch soon.

Wait, what? The app comes with its own jQuery? Does nextcloud core provide none? Does every app come with its own jQuery? o.O

**Comment by marcelklehr** [comment]
> Does every app come with its own jQuery?

No, not usually. I don't remember the exact reason, but problems of interaction between dependencies of this app and the core-shipped jquery version necessitated this.
