### ISSUE TITLE
Upgrade Issue: No table with name user.oc_bookmarks_folders_bookmarks

### ISSUE THREAD

**Issue by fazlerabbi37** [nextcloud/bookmarks#699]
A few days ago I tried to update my Nextcloud instance to 15.0.7 but while the update process the update is stuck and instance throws error ``Doctrine\DBAL\Schema\SchemaException: There is no table with name '$user.oc_bookmarks_folders_bookmarks' in the schema``. I opened an [issue](https://github.com/nextcloud/server/issues/15076) in the server repo and ask for [help](https://help.nextcloud.com/t/failed-to-update-to-nextcloud-15-0-7/51559/4) in the Nextcloud community. 

After trying a few suggestions, I decided to disable the Bookmarks app from the command line using ``occ`` and been able to update to Nextcloud 15.0.7. Ever since I haven't been able to reinstall Bookmarks app. It still throws the same error, ``	
There is no table with name 'user.oc_bookmarks_folders_bookmarks' in the schema.`` I understand that the table for bookmarks are not found on the database and yes, I could not found them using ``psql`` either. 

What can I do to start again using the bookmarks app? Thanks in advance. 

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache2

**Database:** Postgresql 

**PHP version:** 7.0.33

**Nextcloud version:** (see Nextcloud admin page) 15.0.7

**Bookmarks version:** (see Nextcloud apps page) 1.0.2

**Updated from an older Nextcloud or fresh install:**

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
Hey, I'm sorry for the inconvenience. Could you please provide an instance of the error from the  nextcloud log (data/nextcloud.log)?

**Comment by marcelklehr** [comment]
OK, I found the logs in the other issues you linked to. To make the bookmarks app add the necessary tables again, check the migrations table and remove all migrations of the bookmarks app, e.g. using a query like this:

```
delete from oc_migrations where app = 'bookmarks';
```

**Comment by fazlerabbi37** [comment]
@marcelklehr I am extremely sorry for not noticing your first message. 

---

It worked! Thanks a lot! 🎉🎉🎉
