### ISSUE TITLE
navigation issues in web interface

### ISSUE THREAD

**Issue by tessus** [nextcloud/bookmarks#706]
### Steps to reproduce
1. Sync data with floccus (it's not a floccus problem) use server folder `/xyz`
2. open the web interface of the bookmarks app
3. click on a folder in the `xyz` folder

<img width="297" alt="Screen Shot 2019-05-14 at 22 14 28" src="https://user-images.githubusercontent.com/223439/57744384-01921180-7697-11e9-9cd7-7f1c4f473826.png">

4. all the navigation items (the xyz folder, Uncategorized, Add folder) vanish and you can't get them back unless you click on the Bookmarks app icon in the nextcloud app toolbar

<img width="206" alt="Screen Shot 2019-05-14 at 22 15 00" src="https://user-images.githubusercontent.com/223439/57744430-238b9400-7697-11e9-88e6-ba355849f08b.png">

### Expected behaviour
The folder tree should remain available so that I can navigate.

### Actual behaviour
All the navigation items (the xyz folder, Uncategorized, Add folder) vanish and you can't get them back unless you click on the Bookmarks app icon in the nextcloud app toolbar.

Also, no folders are shown in the list of bookmarks. Folders are only shown in the navigation tree (up until the first click on a folder, then everything vanishes).

## Server configuration detail

**Operating system:** Linux

**Webserver:** Apache/2.4.39

**Database:** mysql 5.6.25

**PHP version:** 

7.2.18
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gnupg, SPL, hkct, ibm_db2, iconv, session, intl, json, mbstring, standard, mysqlnd, pcntl, PDFlib, mysqli, PDO, pdo_ibm, pdo_mysql, pdo_sqlite, Phar, posix, readline, Reflection, imap, shmop, SimpleXML, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, cgi-fcgi, apcu, imagick, mongodb, igbinary, sodium, redis, mcrypt, luasandbox, Zend OPcache

**Nextcloud version:** 15.0.7 - 15.0.7.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 14.0.10

**Where did you install Nextcloud from:** updater.phar

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - admin_audit: 1.5.0
 - announcementcenter: 3.4.1
 - apporder: 0.6.0
 - bookmarks: 1.0.3
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - contacts: 3.1.1
 - dav: 1.8.1
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_external: 1.6.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notes: 2.6.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - phonetrack: 0.5.0
 - provisioning_api: 1.5.0
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - systemtags: 1.5.0
 - tasks: 0.9.8
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - twofactor_totp: 2.1.2
 - twofactor_u2f: 2.1.3
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - activitylog
 - encryption
 - files_markdown
 - support
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "15.0.7.0",
    "installed": true,
    "forcessl": true,
    "loglevel": 2,
    "maintenance": false,
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "share_folder": "\/Shared",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logdateformat": "Y-m-d H:i:s O",
    "logtimezone": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "appstore.experimental.enabled": true,
    "trashbin_retention_obligation": "auto",
    "updater.release.channel": "production",
    "htaccess.RewriteBase": "\/",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "auth.bruteforce.protection.enabled": false,
    "theme": "",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0

**Operating system:** macOS 10.14.4

## Logs

Nothing in the logs.

**Comment by marcelklehr** [comment]
I've just fixed this. I will do a release soon.

**Comment by tessus** [comment]
Awesome, I can confirm that the navigation works with 1.0.5. Thanks.

I still have two comments and questions though:

1. When I click on a folder that only contains other folders, I don't see anything but the message `No bookmarks here.` This is true, but it would still be nice, if it showed me the folders instead. (Folders seem to be never listed.)
2. I'm a bit puzzled by the sort order. I have a specific order of my bookmarks and folders, but this order seems to be gone in the bookmarks app. Is this an app or floccus issue? Can I open an issue for this? What hapens, if I sync the bookmarks to a second computer? Will the order be the same as on the original computer? If not, this is a serious problem and I might have to switch to the xbel method, which should keep the order intact.

I'm sorry that I didn't open separate issues, but I need to know whether and where I should open them.

**Comment by marcelklehr** [comment]
1. Mh. I see. I think showing the folders together with the bookmarks is not a good idea, but it might make sense to automatically pop open the sub folders in the menu.
2. The sort order is indeed not reflected in the web UI, yet. The server is able to store it and provide access via the API to it, though, so syncing will definitely retain your sort order. You may open an issue for this, of course :)

**Comment by tessus** [comment]
> showing the folders together with the bookmarks is not a good idea

This is very subjective. When you are used to that behavior from the browser, it's kind of strange not seeing folders in the list.

>  it might make sense to automatically pop open the sub folders in the menu.

This would certainly help to make sure one doesn't miss the fact that there are actually additional folders.

> The sort order is indeed not reflected in the web UI, yet. The server is able to store it and provide API access to it, though, so syncing will definitely retain your sort order. You may open an issue for this, of course :)

Wow, awesome that the manual order is retained across devices. 
I will open an issue for the web UI, but it is not critical. It would help a lot with finding links though.
