### ISSUE TITLE
Save mime type into Nextcloud file system via Bookmarklet

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#707]
### Steps to reproduce
1.  Bookmark url of a file https://example.com/picture.jpeg using Floccus or Bookmarklet.
2.   Try it using this url: https://i.redd.it/caxufm5mq4y21.jpg

### Expected behaviour
I'm curious on having a bookmarked file (mime type) be saved into the Nextcloud file system, rather than simply being bookmarked.

### Actual behaviour
A bookmark is created,  but the file is not saved within Nextcloud.  Not high priority, but would be useful, even as an alternative to bookmarking. Thanks for considering!

**Comment by marcelklehr** [comment]
Hey :) 
I understand you'd like to be able to access the contents of a bookmarked URL in the nextcloud file system?
With the example of a picture this would work quite well, however, I'm having trouble imagining this with full HTML pages...

**Comment by sunjam** [comment]
Html webpages would be well served by wallabag support, so bounty added ;)
not sure on integration suggestions for that here...

I'm thinking images, pdf documents, audio and video files.  Useful files
where the url ends in .(supported format)

**Comment by marcelklehr** [comment]
> I'm thinking images, pdf documents, audio and video files.  Useful files
where the url ends in .(supported format)

I like it! :)
