### ISSUE TITLE
Adding Bookmarks

### ISSUE THREAD

**Issue by rvanscherpe** [nextcloud/bookmarks#709]
### Steps to reproduce
1. click on 'Add to Nextcloud' bookmark snippet to add website to bookmarks
2.
3.

### Expected behaviour
Tell us what should happen
Dialog box with bookmark details with an OK to add 
### Actual behaviour
Tell us what happens instead
Internal Server Error. The server is unable to complete your request.
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
16
**Bookmarks version:** (see Nextcloud apps page)
1.0.4
**Updated from an older Nextcloud or fresh install:**

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
That is unfortunate. Could you provide details from the nextcloud log?

**Comment by rvanscherpe** [comment]
heres a snippet of the log file after I attempt to add a bookmark.  I believe this has been happening since 1.0.4:

{"reqId":"JFvRhbMUrNhtZuKGRTgw","level":3,"time":"2019-05-18T13:59:10+00:00","remoteAddr":"x.x.x.x","user":"username","app":"index","method":"GET","url":"\/index.php\/apps\/bookmarks\/bookmarklet?output=popup&url=https%3A%2F%2Facromove.com%2Fproducts%2Fserverpack-35%2F&title=ServerPack%E2%84%A2%2035%20%7C%20Acromove%20Inc.","message":{"Exception":"Error","Message":"Call to undefined function OCA\\Bookmarks\\idn_to_ascii()","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/bookmarks\/lib\/UrlNormalizer.php","line":62,"function":"normalize_host","class":"OCA\\Bookmarks\\UrlNormalizer","type":"::","args":["acromove.com"]},{"file":"\/var\/www\/nextcloud\/apps\/bookmarks\/lib\/Bookmarks.php","line":440,"function":"normalize","class":"OCA\\Bookmarks\\UrlNormalizer","type":"->","args":["https:\/\/acromove.com\/products\/serverpack-35\/"]},{"file":"\/var\/www\/nextcloud\/apps\/bookmarks\/lib\/Controller\/WebViewController.php","line":85,"function":"bookmarkExists","class":"OCA\\Bookmarks\\Bookmarks","type":"->","args":["https:\/\/acromove.com\/products\/serverpack-35\/","username"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"bookmarklet","class":"OCA\\Bookmarks\\Controller\\WebViewController","type":"->","args":["https:\/\/acromove.com\/products\/serverpack-35\/","ServerPack\u2122 35 | Acromove Inc."]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\WebViewController"},"bookmarklet"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\WebViewController"},"bookmarklet"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["WebViewController","bookmarklet",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bookmarks.web_view.bookmarklet"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"bookmarks.web_view.bookmarklet"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"bookmarks.web_view.bookmarklet"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/bookmarks\/bookmarklet"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/bookmarks\/lib\/UrlNormalizer.php","Line":105,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"16.0.0.9"}
{"reqId":"5cr56welncVpS38GWXpi","level":0,"time":"2019-05-18T13:59:11+00:00","remoteAddr":"x.x.x.x","user":"username","app":"files_markdown","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource file \"\/apps\/files_markdown\/css\/..\/build\/styles.css\"","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"16.0.0.9"}
{"reqId":"Z2a6NPq2SbXi6dlFAR7B","level":0,"time":"2019-05-18T13:59:12+00:00","remoteAddr":"x.x.x.x","user":"username","app":"files_markdown","method":"GET","url":"\/index.php\/apps\/files\/","message":"Could not find resource file \"\/apps\/files_markdown\/css\/..\/build\/styles.css\"","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"16.0.0.9"}

I remove my username and IP address from the log snippet

**Comment by marcelklehr** [comment]
Do you have php-intl installed?

**Comment by rvanscherpe** [comment]
Hunh.  No i didn't.  Didn't need it before.  Just installed it and restarted apache and it seems to be working now.
