### ISSUE TITLE
bookmarks 1.9.4

### ISSUE THREAD

**Issue by peteman52** [nextcloud/bookmarks#710]
Use of undefined constant n - assumed 'n' at /var/www/owncloud/apps/bookmarks/lib/UrlNormalizer.php#207
Use of undefined constant x80 - assumed 'x80' at /var/www/owncloud/apps/bookmarks/lib/UrlNormalizer.php#201

**Comment by marcelklehr** [comment]
Thanks for the feedback! I've just pushed another patch.
