### ISSUE TITLE
Please add a CHANGELOG.md file

### ISSUE THREAD

**Issue by YoSiJo** [nextcloud/bookmarks#711]
Could you please include a CHANGELOG.md file? So you can easily see what was changed.
Where can I do the current actual best?

**Comment by marcelklehr** [comment]
You can find the changes on [the releases page](https://github.com/nextcloud/bookmarks/releases)

> Where can I do the current actual best?

I'm not sure I understand you. Would you like to contribute?

**Comment by YoSiJo** [comment]
Sorry, bad translation.
The question was, where can I best view the current changes. You already answered the question with the link.
But I would still be happy about the CHANGELOG.md file.
Especially if you have the files of the repo somewhere, a CHANGELOG.md is always good to see that it has changed.
