### ISSUE TITLE
Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by dehnhardt** [nextcloud/bookmarks#713]
### Steps to reproduce
Try to sync the root folder from Firefox

### Expected behaviour
syncinc works

### Actual behaviour
Error in floccus:
Error 500. Failed POST request. Check your server configuration. 

Error on Nextcloud
[PHP] Error: Object of class DateTime could not be converted to string at /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php#197
at 2019-05-19T16:45:01+00:00

[index] Error: Error: Class 'OCA\Bookmarks\Exception' not found at <<closure>>
 0. /var/www/nextcloud/apps/bookmarks/lib/UrlNormalizer.php line 149
    unquote("KID=991012&ZBit ... =", " &=+#")
 1. /var/www/nextcloud/apps/bookmarks/lib/UrlNormalizer.php line 64
    normalize_query("KID=991012&ZBit ... =")
 2. /var/www/nextcloud/apps/bookmarks/lib/Bookmarks.php line 903
    normalize("http://booking. ... =")
 3. /var/www/nextcloud/apps/bookmarks/lib/Controller/Rest/BookmarkController.php line 308
    addBookmark("holger", "http://booking. ... =", "Willkommen bei  ... e", [], "", false, [90])
 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    newBookmark("http://booking. ... =", [], "Willkommen bei  ... e", false, "", [], [90])
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OCA\Bookmarks\Co ... }}, "newBookmark")
 6. /var/www/nextcloud/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Bookmarks\Co ... }}, "newBookmark")
 7. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("BookmarkController", "newBookmark", OC\AppFramework\ ... {}, {_route: "bookma ... "})
 8. <<closure>>
    __invoke({_route: "bookma ... "})
 9. /var/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "bookma ... "})
10. /var/www/nextcloud/lib/base.php line 987
    match("/apps/bookmarks/public/rest/v2/bookmark")
11. /var/www/nextcloud/index.php line 42
    handleRequest()

POST /index.php/apps/bookmarks/public/rest/v2/bookmark
from 92.195.79.109 by holger at 2019-05-19T16:33:59+00:00

## Server configuration detail

**Operating system:** Linux 4.16.7-xen #1 SMP Sun May 6 09:55:18 CEST 2018 x86_64

**Webserver:**   (apache2handler)

**Database:** pgsql PostgreSQL 9.4.19 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10+deb8u1) 4.9.2, 64-bit

**PHP version:** 

7.0.33-1~dotdeb+8.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, igbinary, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 15.0.8 - 15.0.8.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - admin_audit: 1.5.0
 - apporder: 0.6.0
 - audioplayer: 2.7.0
 - bookmarks: 1.0.5
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - contacts: 3.1.1
 - dashboard: 6.0.0
 - dav: 1.8.2
 - event_update_notification: 0.3.4
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_external: 1.6.0
 - files_markdown: 2.0.6
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - issuetemplate: 0.5.0
 - keeweb: 0.5.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notes: 2.6.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - ocsms: 2.1.1
 - password_policy: 1.5.0
 - provisioning_api: 1.5.0
 - qownnotesapi: 19.4.0
 - quota_warning: 1.4.0
 - rainloop: 6.0.2
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - social: 0.1.4
 - spreed: 5.0.3
 - support: 1.0.0
 - survey_client: 1.3.0
 - systemtags: 1.5.0
 - tasks: 0.10.1
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - twofactor_totp: 2.1.2
 - updatenotification: 1.5.0
 - user_ldap: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - encryption
 - ojsxc
 - ownnote

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "defaultapp": "apporder",
    "dbtype": "pgsql",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
   "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "version": "15.0.8.1",
    "logtimezone": "UTC",
    "log_query": true,
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 1,
    "ldapIgnoreNamingRules": false,
    "trashbin_retention_obligation": "auto, auto",
    "updatechecker": true,
    "updater.server.url": "***REMOVED SENSITIVE VALUE***",
    "appcodechecker": false,
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "appstore.experimental.enabled": true,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "overwrite.cli.url": "https:\/\/cloud.dehnhardt.org",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25"
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP

<details><summary>LDAP configuration (delete this par if not used)</summary>

```

```
</details>

## Client configuration

**Browser:** Firefox 60.6.3esr (64-bit)

**Operating system:** Debian Linux 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
[PHP] Error: Object of class DateTime could not be converted to string at /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php#197
at 2019-05-19T16:45:01+00:00
[index] Error: Error: Class 'OCA\Bookmarks\Exception' not found at <<closure>>

 0. /var/www/nextcloud/apps/bookmarks/lib/UrlNormalizer.php line 149
    unquote("KID=991012&ZBit ... =", " &=+#")
 1. /var/www/nextcloud/apps/bookmarks/lib/UrlNormalizer.php line 64
    normalize_query("KID=991012&ZBit ... =")
 2. /var/www/nextcloud/apps/bookmarks/lib/Bookmarks.php line 903
    normalize("http://booking. ... =")
 3. /var/www/nextcloud/apps/bookmarks/lib/Controller/Rest/BookmarkController.php line 308
    addBookmark("holger", "http://booking. ... =", "Willkommen bei  ... e", [], "", false, [90])
 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    newBookmark("http://booking. ... =", [], "Willkommen bei  ... e", false, "", [], [90])
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OCA\Bookmarks\Co ... }}, "newBookmark")
 6. /var/www/nextcloud/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Bookmarks\Co ... }}, "newBookmark")
 7. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("BookmarkController", "newBookmark", OC\AppFramework\ ... {}, {_route: "bookma ... "})
 8. <<closure>>
    __invoke({_route: "bookma ... "})
 9. /var/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "bookma ... "})
10. /var/www/nextcloud/lib/base.php line 987
    match("/apps/bookmarks/public/rest/v2/bookmark")
11. /var/www/nextcloud/index.php line 42
    handleRequest()

POST /index.php/apps/bookmarks/public/rest/v2/bookmark
from 92.195.79.109 by holger at 2019-05-19T16:33:59+00:00
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by marcelklehr** [comment]
It appears, there is a problematic URL in your bookmarks. Can you provide the client-side floccus log? (You may want to email it privately as it contains sensitive data: see https://github.com/marcelklehr for my mail address)

**Comment by marcelklehr** [comment]
Judging by the floccus log, your server data appears to be corrupt, as it consistently reports an inconsistency in a Folder. Deleting that folder on the server should mitigate that issue for now and hopefully gives way for the actual error we're here for.

**Comment by dehnhardt** [comment]
Thanks for your help. In the end I had to remove two bookmarks. What has confused me here is that the initial synchronize worked fine (delete all bookmarks in Nextcloud and select "Trigger sync from scratch")
The errors did not occur until the subsequent synchronization.
