### ISSUE TITLE
Feature request: generate screenshot button

### ISSUE THREAD

**Issue by drBenway** [nextcloud/bookmarks#715]
Hi all,

I was wondering if it would be possible to have more control over the image that is used for a bookmark. I just imported my Firefox bookmarks and had a lot of missing images.
What I'd like to have is:
- the option to pick your own image for a bookmark, like you can pick an icon in your OS. My ideal solution would allow me to drag and drop an image in the detailed view. I guess the back-end would have to crop the image to a manageable size.

- I'd like to have a button that allows me to generate a screenshot for a given url. 
From a technical point I think this could be done with a headless chrome (phantomjs is discontinued). I managed to do something similar with NodeJS.

**Comment by marcelklehr** [comment]
Hey @drBenway,
in the nextcloud admin settings for the bookmarks app you will find the possibility of integrating a [screeenly](https://screeenly.com) service (an automatic screenshot service) with your instance to generate screenshots in a more reliable way, similar to what you described.
Picking your own images for bookmarks is unlikely to be implemented, however.
