### ISSUE TITLE
Hard to navigate subfolders in webview

### ISSUE THREAD

**Issue by e-magon** [nextcloud/bookmarks#720]
I'm sorry if this has already been reported, I've tried to search this issue but I couldn't find one.

### Steps to reproduce
1. Click on the triangle of a bookmarks folder to expand it.
2. Click again on a subfolder to expand it as well.

### Expected behaviour
I should be able to keep expanding subfolder and explore the tree

### Actual behaviour
It collapses the root folder. As soon as I reopen it, the subfolder I clicked in the second step opens too.

### Server configuration
**Nextcloud version:** 16.0.1

**Bookmarks version:** 1.0.5

### Client configuration
**Browser:** Brave Browser

**Operating system:** macOS Mojave 10.14.5

**Comment by marcelklehr** [comment]
Confirmed

**Comment by AhabHyde** [comment]
Thank you @marcelklehr
