### ISSUE TITLE
Bookmarks save doesn't work

### ISSUE THREAD

**Issue by manwy** [nextcloud/bookmarks#724]
### Steps to reproduce
1. Go to NextcloudDomain.xx/index.php/apps/bookmarks
2. Clic on "Add a bookmark"
3. Write or paste an URL I want to save
4. Press Enter or "Add this to my bookmarks" icon.

### Expected behaviour
Bookmark added to my list

### Actual behaviour
Nothing happens. Bookmark is not saved and not added to my list

### Server configuration

**Operating system**:
Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64

**Web server:**
Apache/2.4.25 (Debian) (apache2handler)

**Database:**
mysql 10.1.38

**PHP version:**
7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page)
16.0.1

**Bookmarks version:** (see Nextcloud apps page)
1.0.5

**Updated from an older Nextcloud or fresh install:**
Fresh install

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

```

**List of activated apps:**
Carnet, Notes, Bookmarks, News
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bookmarks: 1.0.5
  - bruteforcesettings: 1.3.0
  - carnet: 0.16.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - encryption: 2.4.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - issuetemplate: 0.5.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - news: 13.1.6
  - nextcloud_announcements: 1.5.0
  - notes: 2.6.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - files_external
  - user_ldap
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED.duckdns.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "overwrite.cli.url": "https:\/\/REMOVED.duckdns.org\/REMOVED",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "has_rebuilt_cache": true
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
ChromeOS

**Comment by marcelklehr** [comment]
Can you press F12 and check if there are any errors in your browser console? Also can you check the nextcloud logs for errors?

**Comment by manwy** [comment]
**In the browser console I can see this:**

```
POST https://REMOVED SENSITIVE VALUE/index.php/apps/bookmarks/bookmark 500 (Internal Server Error)

  | send | @ | main.bundle.js?v=464ec80a-0:13335
-- | -- | -- | --
  | ajax | @ | main.bundle.js?v=464ec80a-0:12941
  | Backbone.ajax | @ | main.bundle.js?v=464ec80a-0:1530
  | Backbone.sync | @ | main.bundle.js?v=464ec80a-0:1513
  | __WEBPACK_IMPORTED_MODULE_1_backbone___default.a.sync | @ | main.bundle.js?v=464ec80a-0:32497
  | sync | @ | main.bundle.js?v=464ec80a-0:507
  | save | @ | main.bundle.js?v=464ec80a-0:718
  | submit | @ | main.bundle.js?v=464ec80a-0:33948
  | executeBound | @ | main.bundle.js?v=464ec80a-0:2759
  | (anonymous) | @ | main.bundle.js?v=464ec80a-0:2772
  | (anonymous) | @ | main.bundle.js?v=464ec80a-0:2119
  | dispatch | @ | main.bundle.js?v=464ec80a-0:8918
  | elemData.handle | @ | main.bundle.js?v=464ec80a-0:8726

```


**And in the nextcloud log (/var/www/htm/REMOVED SENSITIVE VALUE/data/nextcloud.og) I can't see any error**

**Comment by marcelklehr** [comment]
> in the nextcloud log (/var/www/htm/REMOVED SENSITIVE VALUE/data/nextcloud.og) I can't see any error

This is quite unlikely as the response received by the client says 'Internal Server Error'. You can also check the logs in the web admin panel under Settings -> Logging ;)

**Comment by manwy** [comment]
The logs in the web admin panel shows this:

`Error	PHP	You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at /var/www/html/alextic.duckdns.org/11071975/3rdparty/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php#18		2019-06-08T21:09:42+0200`

**Comment by manwy** [comment]
The logs in the web admin panel shows this:

Error	PHP	You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at /var/www/html/REMOVED SENSITIVE VALUE/3rdparty/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php#18	2019-06-08T21:09:42+0200

**Comment by marcelklehr** [comment]
Aha. then you will need to install the intl php extension

**Comment by manwy** [comment]
Ok. It was that. Now it works perfect. Thank you very much for your time and dedication.

**Comment by Leorivasc** [comment]
Just to say THANK YOU GUYS, I had the exact same problem, installed the php7-intl package and voilá.

Thanks a lot!
Leo
