### ISSUE TITLE
Feature Request: Use star logo as favicon

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/bookmarks#729]
Hello,

It would be great to use the icon in the tab bar as well, to tell it apart from other tabs that might contain Files, Tasks, News...

![favicon](https://user-images.githubusercontent.com/21343324/59156299-3e7bd900-8a88-11e9-8394-c344cb626332.png)

Thanks a lot for the app, it's been improving a lot recently!

**Comment by marcelklehr** [comment]
Thanks for the heads up, this has been in the back of my mind for a long time :D

**Comment by nachoparker** [comment]
no problem! is it not going to be implemented? (because the request is closed now)
