### ISSUE TITLE
PreviewJobs is too heavy

### ISSUE THREAD

**Issue by shtrom** [nextcloud/bookmarks#737]
With a large number of bookmarks, `BackgroundJobs::PreviewsJob` is way too heavy, particularly to run on a short cron interval.

Suggestions for improvements:
1. Choose whate to update
1.a. Pick a random offset to update
1.b. Update only the newly added bookmarks
2. Update a limited max number of previews each time

Number 1.b.. Is obviously preferable, but we probably need a new DB column that stores the last time the preview was updated, and only select entries which have been updated more recently than the preview (or if the preview never was updated).

In either case, it's probably a good idea to have a maximum batch size to update in one go (as in 2.), even if there are more entries than that (they'll get updated on the next run).

https://github.com/nextcloud/bookmarks/blob/f0eeae6811d274ba92667e71c9dfe1a90954309d/lib/BackgroundJobs/PreviewsJob.php#L40

**Comment by marcelklehr** [comment]
> Number 1.b.. Is obviously preferable, but we probably need a new DB column that stores the last time the preview was updated, and only select entries which have been updated more recently than the preview (or if the preview never was updated).

> In either case, it's probably a good idea to have a maximum batch size to update in one go (as in 2.), even if there are more entries than that (they'll get updated on the next run).

That sounds like a good solution!

As always: Thank you for your valuable feedback :)

**Comment by marcelklehr** [comment]
Fixed

**Comment by shtrom** [comment]
Great, I updated the app yesterday, and I can actually see a drop in the load and logging in Nextcloud :+1: 
![cpu-day](https://user-images.githubusercontent.com/160280/62282803-8bca6480-b493-11e9-9e84-4df11ebcf4d2.png)
![file_length_errorlogs-day](https://user-images.githubusercontent.com/160280/62282804-8bca6480-b493-11e9-9fd2-b165524ed475.png)
