### ISSUE TITLE
Add more preview options besides screenly

### ISSUE THREAD

**Issue by small1** [nextcloud/bookmarks#741]
New feature. Add more preview options besides screenly

Pageres would be one that would be neat to implement to get the screenshot generation done locally 

Check on the nextcloud passwords app how they did it:

[https://github.com/marius-wieschollek/passwords/tree/master/src/lib/Helper/Preview](https://github.com/marius-wieschollek/passwords/tree/master/src/lib/Helper/Preview
)

**Comment by sunjam** [comment]
If you would like to self host Screeenly, [here is a docker image built specifically for use with Nextcloud](https://github.com/ionphractal/docker-screeenly).

**Comment by small1** [comment]
That sure helps a bit on the way .. but it would still be neat with more options :)

**Comment by small1** [comment]
> If you would like to self host Screeenly, [here is a docker image built specifically for use with Nextcloud](https://github.com/ionphractal/docker-screeenly).

And that docker image does not work ... fyi

**Comment by sunjam** [comment]
You'll need to re-write the docker compose file for your specific setup.  It can be used as a reference though, along with [the documentation](https://github.com/stefanzweifel/screeenly/wiki/Requirements-and-Install) from the project [github](https://github.com/stefanzweifel/screeenly).  Hope this helps!

**Comment by small1** [comment]
@sunjam  well i did chaneg specifics .. but ionphractal/screeenly:0.1.0  is missing and cant be pulled ... and some other stuff i found that was not optimal like i get several docker images running instead of just one.  ... so then im better off following the docs you now mentioned and build my own.

**Comment by marcelklehr** [comment]
More options should be pretty simple to create when modeled after [the screeenly provider](https://github.com/nextcloud/bookmarks/blob/master/lib/Previews/ScreenlyPreviewService.php)

**Comment by marcelklehr** [comment]
@chiotisn Would you be interested in tackling this? Your work on the sort functionality was great! :)

**Comment by marcelklehr** [comment]
I've added support for webshot and screenshotmachine.com just now. @small1 would you be interested in testing this on the current master branch? I can provide a beta version :)

**Comment by SuperSandro2000** [comment]
I know how to get screenshot machine and screeenly up and running but which of the webshot servers did you use? Can you link those in the settings? This would make setting this up a lot easier.

**Comment by sunjam** [comment]
I believe the idea is for you to self-host your own instance if possible.
Suggestions?

**Comment by marcelklehr** [comment]
Mmh, I've modeled these after the passwords app. Not sure which software that is exactly. I wasn't aware there's a dozen apps called webshot :sweat_smile:

**Comment by marcelklehr** [comment]
pageres is now supported in the master branch as well :)
