### ISSUE TITLE
Screeenly typo and broken url

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#744]
Hi, I think you have a typo in Scre**e**enly.  Broken url in settings is to `https://secure.screeenly.com/api/v1/fullsize`

Are you referring to `https://www.screenly.io/` under Nextcloud settings for a Bookmarks Screenly api?

**Comment by marcelklehr** [comment]
Nope, [this](https://github.com/stefanzweifel/screeenly) is what I'm referring to... :/
