### ISSUE TITLE
Menu items on iOS browsers are not working

### ISSUE THREAD

**Issue by christianapel** [nextcloud/bookmarks#747]
### Steps to reproduce
1. Sync Chrome bookmarks with Nextcloud using Floccus
2. Open Nexcloud Bookmarks with Safari or Chrome on iOS (iPad Air and iPhone X)
3. Try to use folders
3.1 Click on a folder to show bookmarks
3.2 Click the arrow on the left to show subfolders
3.3 Click the three dots on the right to show options

### Expected behaviour
1. Bookmarks in a selected folder should be listed
2. Subfolders should be listed under the selected folder
3. Folder options should show up

### Actual behaviour
1. No bookmarks shown, but message "No bookmarks here."
2. Subfolders are not showing up when clicking on the arrow. It looks like it's just enabling drag&drop instead.
3. On the iPhone the dots are hidden and are just visible when moving the page, but then you cannot click on them. On the iPad the dots are shown but cannot be clicked.

On desktop browsers it's working as expected.

### Server configuration

**Operating system**: Linux, Docker

**Web server:** Apache

**Database:** MySQL

**Nextcloud version:** 16.0.3

**Bookmarks version:** 1.0.6

### Client configuration
**Browser:** Safari and Chrome 75.0.3770.103

**Operating system:** iOS 12.3.1

**Comment by marcelklehr** [comment]
Should be fixed with the new UI
