### ISSUE TITLE
[Enhancement] Deduplication

### ISSUE THREAD

**Issue by coolkau** [nextcloud/bookmarks#749]
I am not only using the nextcloud bookmarks but also chrome, firefox, etc. Once in a while I would like to sync them up.  
An import currently will create a lot of duplicates. The only way to deal with a sync right now is to collect all the bookmarks in firefox, clean them up there e.g. with help of a dedup tool, wipe the nextcloud bookmarks, and then import from firefox.

So it would be good to be able to either have an import filter which only imports non-existing bookmarks, or a way of de-duplicating bookmarks separately.

I am hoping for the nextcloud app to be a central place to keep the craziness of my bookmarks in check. So I need some basic clean-up tools. Otherwise it is just another place to store the bookmarks.

**Comment by marcelklehr** [comment]
Have you checked out floccus for syncing? It syncs folders directly and deduplicates inside folders (but not across folders, so the same bookmark may be present in two folders).

**Comment by coolkau** [comment]
Thanks for floccus, had not heard about it, looked at it, but did not have a chance to try it out yet... life happened in between.

**Comment by gerroon** [comment]
Hi

Is this done or implemented?

**Comment by HammyHavoc** [comment]
Wondering about deduplication myself, does anybody know what the current state of play is? I've got tens of thousands of bookmarks, looking to condense it.

**Comment by marcelklehr** [comment]
@HammyHavoc So, for each bookmark the app should display all folders a given URL is filed into in the bookmark details. Technically it only stores one bookmark for each URL and user. But deduplication itself as in removing duplicate references is not implemented.
