### ISSUE TITLE
Error when adding Bookmarks RSS url to News app

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#755]
I've been able to add the Bookmarks RSS url from side panel into the News app.  Unsure if this error is due to either the Bookmarks or News app.  Error I receive is:

![1563999658](https://user-images.githubusercontent.com/1787238/61825999-54fea980-ae16-11e9-890f-000e10525d93.png)
![1563999638](https://user-images.githubusercontent.com/1787238/61826003-57610380-ae16-11e9-901e-d9ee07117cc3.png)

**Comment by marcelklehr** [comment]
RSS feeds are not public at the moment. You will need to use the basic auth feature of the news app to authenticate.

**Comment by marcelklehr** [comment]
I can confirm that this doesn't work in the news app. However, it works using curl, so I'm inclined to say this is not a bug in the bookmarks app.

```
curl: curl -u 'username:password' https://foobar.com/index.php/apps/bookmarks/public/rest/v2/bookmark?format=rss&page=0
```
