### ISSUE TITLE
Cannot tell from webui if folder is empty or contains sub-folders unless moused over

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#756]
Hi!  I cannot tell if a folder contains subfolders,
![1563999060](https://user-images.githubusercontent.com/1787238/61826766-f5090280-ae17-11e9-914e-4d8fec28eced.png)
unless I directly mouse over it.
![1563999036](https://user-images.githubusercontent.com/1787238/61826770-f6d2c600-ae17-11e9-8b31-a400de0115fb.png)

This becomes confusing if the selected folder contains no bookmarks, but the sub-folder(s) contain bookmarks.  This message will be displayed:
![1563998412](https://user-images.githubusercontent.com/1787238/61826858-2a155500-ae18-11e9-9415-f443ad0f8423.png)

This is especially confusing to users attempting to delete folders they assume are empty.

**Comment by marcelklehr** [comment]
Fixed with the new UI
