### ISSUE TITLE
Syntax error throws 500 on HTTP-request

### ISSUE THREAD

**Issue by ionum** [nextcloud/bookmarks#758]
Bookmarks APP: 1.0.8
Nextcloud: 15.0.10
PHP: 7.0.33-0+deb9u3

[index] Error: ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) at <<closure>>

 0. /var/vhosts/owncloud/lib/composer/composer/ClassLoader.php line 322
    Composer\Autoload\includeFile("/var/vhosts/own ... p")
 1. <<closure>>
    loadClass("Rowbot\\URL\\BasicURLParser")
 2. /var/vhosts/owncloud/apps/bookmarks/vendor/rowbot/url/src/URL.php line 72
    spl_autoload_call("Rowbot\\URL\\BasicURLParser")
 3. /var/vhosts/owncloud/apps/bookmarks/lib/UrlNormalizer.php line 12
    __construct("http://www.info ... 5")
 4. /var/vhosts/owncloud/apps/bookmarks/lib/Bookmarks.php line 440
    normalize("http://www.info ... 5")
 5. /var/vhosts/owncloud/apps/bookmarks/lib/Controller/Rest/BookmarkController.php line 226
    bookmarkExists("http://www.info ... 5", "xxxx")
 6. /var/vhosts/owncloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    getBookmarks("bookmark", "", 0, "bookmarks_sorting_recent", "xxxx", null, "or", "", [], 10, false, null, "http://www.info ... 5")
 7. /var/vhosts/owncloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OCA\Bookmarks\Co ... }}, "getBookmarks")
 8. /var/vhosts/owncloud/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Bookmarks\Co ... }}, "getBookmarks")
 9. /var/vhosts/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("BookmarkController", "getBookmarks", OC\AppFramework\ ... {}, {_route: "bookma ... "})
10. <<closure>>
    __invoke({_route: "bookma ... "})
11. /var/vhosts/owncloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "bookma ... "})
12. /var/vhosts/owncloud/lib/base.php line 987
    match("/apps/bookmarks/public/rest/v2/bookmark")
13. /var/vhosts/owncloud/index.php line 42
    handleRequest()

GET /index.php/apps/bookmarks/public/rest/v2/bookmark?url=http%3A%2F%2Fwww.infoxxxxxxxxxx.com%2Farticles%2Farticle.aspx%3Fp%3D27666%26rll%3D1%26seqNum%3D15
from 10.13.0.8 by XXXX at 2019-07-27T11:13:08+00:00

**Comment by marcelklehr** [comment]
You'll need at least php v7.1, I'm afraid. I'll document this.

**Comment by radoeka** [comment]
I have the same issue!  :(

How do I get back to the previous version?  

Is the tarbal available of the previous version?

Can I just restore from backup??

**Comment by radoeka** [comment]
Remove version 1.0.8 from nextcloud-15.0.x download.

**Comment by radoeka** [comment]
I installed from backup.  The server saw this, and started maintenance/update mode.
During this, it checks for new versions, and the latest (broken) version is automatically installed.
Now to get out of this?
I'm not able to upgrade php to 7.1 at the moment.

**Comment by radoeka** [comment]
Made the bookmarks folder readonly, that made it work again (back to version 1.0.6, as that was the one in my backup (from yesterday)).
