### ISSUE TITLE
Syncing Localhost Bookmark fails. 

### ISSUE THREAD

**Issue by plutocrat** [nextcloud/bookmarks#767]
Syncing Opera using Floccus plugin (also reported in their github account)

### Steps to reproduce
 - Add a bookmark containing http://127.0.0.1/ -- In my case I was using Syncthing on http://127.0.0.1:8384/
 - Hit Sync.
 - Fail. "Syncing failed with E019: HTTP status 500. Failed GET request. Check your server configuration and log."

 - Delete bookmark, and sync succeeds. 
 
### Server configuration
Latest 16.x version of nextcloud. Latest version of Bookmarks, Floccus.

**Comment by marcelklehr** [comment]
> Check your server configuration and log.

What does the nextcloud log say? :)

**Comment by plutocrat** [comment]
Nothing at all in nextcloud.log. Nothing in apache error log. Only a http status 500 in apache webserver log. 

1.2.3.4 - user [08/Aug/2019:12:54:11 +0800] "GET /index.php/apps/bookmarks/public/rest/v2/bookmark?url=http%3A%2F%2F127.0.0.1%3A8384 HTTP/1.0" 500 6043 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.170"
I've been looking at the server config, and can't see anything in apache conf which wouldn't like this, or in the nextcloud .htaccess file. Hence my confusion. Not a big deal in any case, I've just removed the bookmark, but I thought I'd put it on your radar.

**Comment by plutocrat** [comment]
It was the php-gmp extension. I hadn't installed it. All working now. I think it might have affected all numeric IP bookmarks?
Might it be a good idea to check for extensions and pop up an error message if not installed?
