### ISSUE TITLE
New install of Newcloud and Bookmark brings up a spinning circle and nothing else. 

### ISSUE THREAD

**Issue by deathcat** [nextcloud/bookmarks#768]
Hello,

I am trying to install Bookmarks v1.1.1 and it installs properly. However when I try to go into Bookmarks within my NewCloud installation it just gives the spinning circle as if it is loading. I looked in the log and I get the following:

Error | index | Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT `url`, `title`, `user_id`, `description`, `public`, `added`, `lastmodified`, `clickcount`, `id`, GROUP_CONCAT(`t`.`tag`) AS `tags` FROM `oc_bookmarks` `b` LEFT JOIN `oc_bookmarks_tags` `t` ON `t`.`bookmark_id` = `b`.`id` LEFT JOIN `oc_bookmarks_folders_bookmarks` `f` ON `f`.`bookmark_id` = `b`.`id` WHERE `user_id` = ? GROUP BY `id`, `lastmodified` ORDER BY `lastmodified` DESC LIMIT 34 OFFSET 0' with params ["deathcat"]: SQLSTATE[42000]: Syntax error or access violation: 1055 'cloud.b.url' isn't in GROUP BY |   | 2019-08-09T16:45:06-0700
-- | -- | -- | -- | --

Error | index | Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT `url`, `title`, `user_id`, `description`, `public`, `added`, `lastmodified`, `clickcount`, `id`, GROUP_CONCAT(`t`.`tag`) AS `tags` FROM `oc_bookmarks` `b` LEFT JOIN `oc_bookmarks_tags` `t` ON `t`.`bookmark_id` = `b`.`id` LEFT JOIN `oc_bookmarks_folders_bookmarks` `f` ON `f`.`bookmark_id` = `b`.`id` WHERE `user_id` = ? GROUP BY `id`, `lastmodified` ORDER BY `lastmodified` DESC LIMIT 34 OFFSET 0' with params ["deathcat"]: SQLSTATE[42000]: Syntax error or access violation: 1055 'cloud.b.url' isn't in GROUP BY |   | 2019-08-09T16:45:06-0700

### Steps to reproduce
1. Install Bookmarks 1.1.1 through the Apps section of NextCloud.
2. Once installed, click on the Bookmarks app on the top of the NewCloud instance.
3. The Bookmark interface comes up, but a spinning circle cursor is in the middle of the screen. Adding bookmarks does not show anything. 

### Expected behaviour
I believe a list of bookmarks should show up, but never got this to work

### Actual behaviour
A SQL error occurs when trying to display the list of bookmarks. A spinning circle (loading) is stuck in the middle of the screen.

### Server configuration

**Operating system**: Raspbian GNU/Linux 10 (buster)"

**Web server:** Apache/2.4.38 (Raspbian)

**Database:** MariaDB 10.3.15

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page) Nextcloud 16.0.3

**Bookmarks version:** (see Nextcloud apps page) Bookmarks 1.1.1

**Updated from an older Nextcloud or fresh install:** Fresh install

**Signing status:** 

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

_PHP module zip not installed.
Please ask your server administrator to install the module.

An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /datavol/var/www/html/cloud.deathcat.net/lib/private/Console/Application.php:166
Stack trace:
#0 /datavol/var/www/html/cloud.deathcat.net/console.php(96): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /datavol/var/www/html/cloud.deathcat.net/occ(11): require_once('/datavol/var/ww...')_

I do have php7.1-zip installed but it does not show up when running php -m.  However I do see it in phpinfo();

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

_This returns an empty set._

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Tried on Brave, Firefox and Chrome.

**Operating system:** Windows 10 

### Logs
#### Web server error log
``` I'll add if needed, but nothing pertinent
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

Thanks for your help.

d

**Comment by marcelklehr** [comment]
This might be a quick fix: https://stackoverflow.com/questions/36950857/sqlstate42000-syntax-error-or-access-violation-1055-expression-3-of-select#answer-41145619

But in the long run, I will have to change the query.

**Comment by deathcat** [comment]
Hello @marcelklehr 

This worked perfectly. Thanks for the help!

d
