### ISSUE TITLE
Possible PHP version trouble with floccus and bookmarks

### ISSUE THREAD

**Issue by JDrewes** [nextcloud/bookmarks#770]
### Steps to reproduce
1. upgrade/update nextcloud, bookmarks app and floccus to latest version
2. add sync profile (legacy or folders)
3. try to sync

### Expected behaviour
Bookmarks should sync, which they did before

### Actual behaviour
does not sync. On the client:
E019: HTTP status 500. Failed POST request. Check your server configuration and log.

On the server many entries like:

Error | index | ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)/var/www/owncloud/lib/composer/composer/ClassLoader.php - line 322: Composer\Autoload\includeFile("/var/www/ow ... p")<<closure>>Composer\Autoload\ClassLoader->loadClass("Rowbot\\URL\\BasicURLParser")/var/www/owncloud/apps/bookmarks/vendor/rowbot/url/src/URL.php - line 72: spl_autoload_call("Rowbot\\URL\\BasicURLParser")/var/www/owncloud/apps/bookmarks/lib/UrlNormalizer.php - line 12: Rowbot\URL\URL->__construct("https://www ... /")/var/www/owncloud/apps/bookmarks/lib/Bookmarks.php - line 928: OCA\Bookmarks\UrlNormalizer->normalize("https://www ... /")/var/www/owncloud/apps/bookmarks/lib/Controller/Rest/BookmarkController.php - line 308: OCA\Bookmarks\Bookmarks->addBookmark("jan", "https://www ... /", "Calendar", [ "floccus:"], "", false, [ -1])/var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Bookmarks\Controller\Rest\BookmarkController->newBookmark("https://www ... /", { tags: [ "floccus:"]}, "Calendar", false, "", [ "floccus:"], null)/var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... }}, "newBookmark")/var/www/owncloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... }}, "newBookmark")/var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("BookmarkController", "newBookmark", OC\AppFramew ... {}, { _route: "b ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "b ... "})/var/www/owncloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "b ... "})/var/www/owncloud/lib/base.php - line 987: OC\Route\Router->match("/apps/bookm ... k")/var/www/owncloud/index.php - line 42: OC::handleRequest()
-- | -- | --

I think this might be related to:
https://stackoverflow.com/questions/51567998/parse-error-syntax-error-unexpected-const-t-const-expecting-variable-t-v

### Server configuration

**Operating system**:
Debian Stretch with latest updates

**Web server:**
apache2

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.10

**Bookmarks version:** (see Nextcloud apps page)
1.1.1

**Updated from an older Nextcloud or fresh install:**
updated

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```

How may I work around this? Thanks in advance!

Jan

**Comment by marcelklehr** [comment]
Yes, you need at least php 7.1 in the newer versions. You can either downgrade bookmarks or upgrade php.

**Comment by CodingNomad** [comment]
Same issue, here.

Although I tried to downgrade to 1.0.6, the problem persists.

Can you briefly outline a correct way for downgrading the bookmarks app? Thank you.

**Comment by marcelklehr** [comment]
You will have to [download v1.0.6](https://github.com/nextcloud/bookmarks/releases/tag/v1.0.6), extract it into your apps folder and set the folder permissions to read-only.
