### ISSUE TITLE
current tags not shown when "adding" existing bookmark

### ISSUE THREAD

**Issue by mkaehlcke** [nextcloud/bookmarks#773]
### Steps to reproduce
1. Open a URL for which a bookmark entry with tags exists
2. Click the "Add to Nextcloud" button of the browser
3. The "Add a bookmark" window opens

### Expected behaviour
The existing tags are displayed in the corresponding field

### Actual behaviour
The existing tags are not displayed. Nextcloud is clearly aware though that it's an existing bookmark, the window shows the test "This URL is already bookmarked! Overwrite?" 

### Server configuration

**Operating system**: Linux (most likely)

**Web server:** unknown (hosted by third party)

**Database:** unknown (hosted by third party)

**PHP version:** unknown (hosted by third party)

**Nextcloud version:** 16.0.3
**Bookmarks version:** 1.0.6

**Updated from an older Nextcloud or fresh install:** updated from an older version

**Signing status:**

```
Integrity checker has been disabled. Integrity cannot be verified.
```

**List of activated apps:** many

### Client configuration
**Browser:** Chromium 72.0.3626.109

**Operating system:** Debian Buster

#### Nextcloud log (data/nextcloud.log)
```
403 Forbidden
```

**Comment by marcelklehr** [comment]
Confirmed.

**Comment by marcelklehr** [comment]
Fixed.
