### ISSUE TITLE
Feature request: All bookmarks

### ISSUE THREAD

**Issue by InfamousUser** [nextcloud/bookmarks#787]
**Is your feature request related to a problem? Please describe.**
1. When you want to view all your bookmarks, first of all, it takes ages to get through the list because of the infinite scroll, takes too long to load "pages" and  "pages", please add a button or some other way to load it all at once.
2. Folders do not show under "All bookmarks", the interface is really confusing, it looks like a flat view w/o folders.

**Comment by marcelklehr** [comment]
Yes, i completely agree. In the [new version of the UI](https://github.com/nextcloud/bookmarks/pull/774) there will be no flat, unsorted "all bookmarks" view anymore. The default view will be the root folder with all folders and bookmarks that are in there. That's it. :)

**Comment by InfamousUser** [comment]
Beautiful!
