### ISSUE TITLE
Unspecified exception while trying to enter a bookmark

### ISSUE THREAD

**Issue by frlan** [nextcloud/bookmarks#791]
I wanted to add a new bookmark into a fresh installation of plugin:

 {index} {"Exception":"Rowbot\\URL\\Exception\\TypeError","Message":"http:\/\/ https:\/\/www.bodenaturkost.de\/Produkte\/Huelsenfruechte\/11\/ is not a valid URL.","Code":0,"Trace":[{"file":"\/srv\/nc\/apps\/bookmarks\/lib\/UrlNormalizer.php","line":12,"function":"__construct","class":"Rowbot\\URL\\URL","type":"->","args":["http:\/\/ https:\/\/www.bodenaturkost.de\/Produkte\/Huelsenfruechte\/11\/"]},{"file":"\/srv\/nc\/apps\/bookmarks\/lib\/Bookmarks.php","line":928,"function":"normalize","class":"OCA\\Bookmarks\\UrlNormalizer","type":"->","args":["http:\/\/ https:\/\/www.bodenaturkost.de\/Produkte\/Huelsenfruechte\/11\/"]},{"file":"\/srv\/nc\/apps\/bookmarks\/lib\/Controller\/Rest\/BookmarkController.php","line":308,"function":"addBookmark","class":"OCA\\Bookmarks\\Bookmarks","type":"->","args":["frlan","http:\/\/ https:\/\/www.bodenaturkost.de\/Produkte\/Huelsenfruechte\/11\/","http:\/\/ https:\/\/www.bodenaturkost.de\/Produkte\/Huelsenfruechte\/11\/",[],"",false,[-1]]},{"file":"\/srv\/nc\/apps\/bookmarks\/lib\/Controller\/Rest\/InternalBookmarkController.php","line":134,"function":"newBookmark","class":"OCA\\Bookmarks\\Controller\\Rest\\BookmarkController","type":"->","args":[" https:\/\/www.bodenaturkost.de\/Produkte\/Huelsenfruechte\/11\/",[],null,false,"",[]]},{"file":"\/srv\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"newBookmark","class":"OCA\\Bookmarks\\Controller\\Rest\\InternalBookmarkController","type":"->","args":[" https:\/\/www.bodenaturkost.de\/Produkte\/Huelsenfruechte\/11\/",[],null,false,"",[]]},{"file":"\/srv\/nc\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\Rest\\InternalBookmarkController"},"newBookmark"]},{"file":"\/srv\/nc\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Bookmarks\\Controller\\Rest\\InternalBookmarkController"},"newBookmark"]},{"file":"\/srv\/nc\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["InternalBookmarkController","newBookmark",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"bookmarks.internal_bookmark.new_bookmark"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"bookmarks.internal_bookmark.new_bookmark"}]},{"file":"\/srv\/nc\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"bookmarks.internal_bookmark.new_bookmark"}]},{"file":"\/srv\/nc\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/bookmarks\/bookmark"]},{"file":"\/srv\/nc\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/srv\/nc\/apps\/bookmarks\/vendor\/rowbot\/url\/src\/URL.php","Line":78,"CustomMessage":"--"}

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - OS: Debian Buster
 - HTTP server: Nginx
 - Database PostgreSQL 11
 - PHP version: 7.3
 - Nextcloud version:16.0.4
 - Bookmarks app version: 2.0.3

**Comment by marcelklehr** [comment]
Is this the URL you entered? `http:// https://www.bodenaturkost.de/Produkte/Huelsenfruechte/11/`

**Comment by marcelklehr** [comment]
Ah, no. This is what you inserted: ` https://www.bodenaturkost.de/Produkte/Huelsenfruechte/11/`, so the problem is with the space.

**Comment by frlan** [comment]
The app should report that there is some kind of an issue with URL instead of failing silently (and spamming log with not obvious error message -- btw: the error message itself might be information disclosure)

**Comment by marcelklehr** [comment]
The app no longer fails silently.
