### ISSUE TITLE
Enable Bookmarks fails due to missing php module gmp in Raspbian Buster

### ISSUE THREAD

**Issue by ovpc** [nextcloud/bookmarks#792]
**Describe the bug**
Enable Bookmarks fails due to missing php module gmp in Raspbian Buster.
Regular Debian Buster seem unaffected, so not sure this belongs here? Just close if it doesnt, thank you.
**To Reproduce**
1. Go to Apps
2. Click on download/enable Bookmarks
3. See error missing php module gmp 

**Expected behavior**
enable bookmarks

**Desktop (please complete the following information):**
 - Linux Mint
 - Firefox Version 68.0.2 (64-bit)
 

**Server (please complete the following information):**
 - RPI3B NextCloudPi latest image, up to date Raspbian 10
 - Apache
 - Mysql
 - PHP version: v7.3
 - Nextcloud version: 16.0.4
 - Bookmarks app version: 2.0.3
 - Activated Nextcloud Apps:
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - news: 13.1.6
  - nextcloud_announcements: 1.5.0
  - nextcloudpi: 0.0.1
  - notes: 3.0.2
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.1
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - calendar
  - encryption
  - user_ldap

 - Nextcloud configuration: 
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "11": "***REMOVED SENSITIVE VALUE***"",
            "1": "192.168.n.nn",
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/media\/xxxxxx\/tmp",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "jpeg_quality": "60",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "updater.release.channel": "production",
        "maintenance": false,
        "loglevel": "2",
        "app_install_overwrite": [
            "calendar"
        ],
        "log_type": "file",
        "logfile": "\/media\/nnnn\/nnnn\/nextcloud.log",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl"
    }
}

```

**Nextcloud log (nextcloud/data/nextcloud.log)**

sudo cat /media/xxxxx/xxxxxx/nextcloud.log | grep gmp
{"reqId":"XW9@OvzEWvNbVZsBUMFfzAAAUBA","level":3,"time":"2019-09-04T09:05:04+00:00","remoteAddr":"removedIP","user":"removedusername","app":"settings","method":"POST","url":"\/index.php\/settings\/apps\/enable","message":{"Exception":"Exception","Message":"App \"Bookmarks\" cannot be installed because the following dependencies are not fulfilled: The library gmp is not available.","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Installer.php","line":129,"function":"checkAppDependencies","class":"OC_App","type":"::","args":[{"__class__":"OC\\AllConfig"},{"__class__":"OC\\L10N\\L10N"},{"id":"bookmarks","name":"Bookmarks","summary":"A Bookmark manager for Nextcloud","description":"This app allows you to store and organize your favorite places on the web in one spot, while allowing you to sync them with your various devices and browsers.\n\nCheck out the third-party clients listed here: https:\/\/github.com\/nextcloud\/bookmarks#third-party-clients","version":"2.0.3","licence":"agpl","author":[{"@attributes":{"mail":"blizzz@arthur-schiwon.de","homepage":"https:\/\/www.arthur-schiwon.de"},"@value":"Arthur Schiwon"},{"@attributes":{"mail":"mklehr@gmx.net"},"@value":"Marcel Klehr"},"Marvin Thomas Rabe","Stefan Klemm"],"category":"organization","website":"https:\/\/github.com\/nextcloud\/bookmarks","bugs":"https:\/\/github.com\/nextcloud\/bookmarks\/issues","repository":{"@attributes":{"type":"git"},"@value":"https:\/\/github.com\/nextcloud\/bookmarks.git"},"screenshot":{"@attributes":{"small-thumbnail":"https:\/\/raw.githubusercontent.com\/nextcloud\/bookmarks\/master\/screenshots\/Bookmarks-small.png"},"@value":"https:\/\/raw.githubusercontent.com\/nextcloud\/bookmarks\/master\/screenshots\/Bookmarks.png"},"dependencies":{"php":{"@attributes":{"min-version":"5.6"}},"lib":["gmp","intl","mbstring"]
```

Fixed issue with:

sudo apt install php-gmp   (which also install php7.3-gmp).  

sudo systemctl reload php7.3-fpm.service

After which Bookmarks 2.0.3 is enabled and works, great app, thank you, love to have my own bookmarks manager, use it all the time ;-)

**Comment by marcelklehr** [comment]
This is not a bug. You did exactly the right thing. :)

**Comment by brettinternet** [comment]
Would it be possible to have the app install its own dependencies? This is affecting the NextCloud docker container. Because the container is slim, I'm having trouble finding the right mirror to make `php-gmp` available within `docker exec -it nextcloud bash`.

**Comment by marcelklehr** [comment]
> manually installing a dependency doesn't seem optimal for an ephemeral container.

mh, that's true.

> Apps managing their own dependencies seems more appropriate.

In this case you wouldn't want the app to be able to install the dependency as it would have root access to your server. You could open a PR with nextcloud/docker though and ask them to add the extension.

**Comment by brettinternet** [comment]
Ah, I see. Good point. Thank you for your help.
