### ISSUE TITLE
Display number of Bookmarks in any category

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#793]
**Is your feature request related to a problem? Please describe.**
Thanks for the excellent application!  This minor request is to display total number of _All Bookmarks_ and _Uncategorized_ in webui.
![Screen Shot 2019-09-10 at 1 52 37 PM](https://user-images.githubusercontent.com/1787238/64649784-7d486480-d3d2-11e9-8bc2-571b58051de0.png)

Untagged number of bookmarks is also not dislpayed, but those tagged are displayed, such as those in Floccus
![Screen Shot 2019-09-10 at 1 52 46 PM](https://user-images.githubusercontent.com/1787238/64649820-90f3cb00-d3d2-11e9-86a1-a8b127832f41.png)

**Describe the solution you'd like**
Here is an example of total number of all combined Tasks, as displayed in that app.
![Screen Shot 2019-09-10 at 1 48 02 PM](https://user-images.githubusercontent.com/1787238/64649584-06ab6700-d3d2-11e9-9663-13cca3d7d223.png)

**Comment by marcelklehr** [comment]
There's now an indicator of how many bookmarks one has in relation to the total allowed #855
