### ISSUE TITLE
Very long title text breaks layout

### ISSUE THREAD

**Issue by apiraino** [nextcloud/bookmarks#808]
**Describe the bug**
When the bookmark title is extremely long, I cannot reach the bookmark tools to edit metadata or delete the bookmark. Problem emerged updating from Bookmarks 2.0.3 to 2.1.0

**To Reproduce**
1. Import [this feed](https://blog.fefe.de/rss.xml) into the [News mobile App](https://github.com/nextcloud/news)
3. Load the articles
4. Save one article with a long title
5. Load the article from the Bookmark web interface
5. Impossible to reach the menu on the right to manage the bookmark

**Expected behavior**
I guess the text should be trimmed with `...`?

**Screenshots**
![Screenshot from 2019-09-15 21-06-27](https://user-images.githubusercontent.com/6098822/64926409-58eaee80-d7fd-11e9-837c-97ea80d46782.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: FF 70.0b6 (64-Bit)

**Server (please complete the following information):**
 - OS:ubuntu
 - Nextcloud version: 16.0.4
 - Bookmarks app version: 2.1.0

Thanks for looking into it

**Comment by marcelklehr** [comment]
Confirmed. Thanks for reporting! :)

**Comment by apiraino** [comment]
thanks to you for quickly taking care of that :+1:
