### ISSUE TITLE
Can't drag bookmarks around

### ISSUE THREAD

**Issue by tony4212** [nextcloud/bookmarks#809]
**Describe the bug**

**To Reproduce**
1. install 2.1.1
2. Go to bookmarks

**Expected behavior**
Able to click and drag bookmarks around.

**Desktop (please complete the following information):**
firefox , chrome

**Comment by marcelklehr** [comment]
Indeed the ability of drag-and-dropping bookmarks was removed, because it wasn't working as well as expected. The functionality of moving bookmarks and folders is still available, however by using the "move" dialog.

**Comment by tony4212** [comment]
Is there any plan in the future to add that back in ?

**Comment by marcelklehr** [comment]
I'm not sure. It takes a lot of effort to implement this properly, IMO. But since this would be redundant functionality I'm not sure it's worth the effort. What is your opinion on the usefulness of that feature?

**Comment by tony4212** [comment]
Honestly I found it more convenient to move things around. While it is redundant it makes a huge difference. It is just like how you can add the right click function in nextcloud. Sure technically it is redundant since you can click on the three dots, but it just makes things more user friendly.  If I am being honest because of not having that I revered back to 2.0.3 . Can you tell me what part of it didn't work as expected ?

**Comment by haqk** [comment]
I have recently started using Bookmarks in Nextcloud. It is a great app, however I have been trying to drag and drop things and it (obviously) does not work. It is such a ubiquitous feature in similar apps these days that I felt a bit lost without it. Are there any plans to bring drag n drop back?

**Comment by marcelklehr** [comment]
I see. Thank you for your feedback! I'll reopen this, then. It's not a priority at the moment, though. Help is welcome, though, as always :)

**Comment by marcelklehr** [comment]
I've finally gotten around to implementing (#1474) this :tada: Stay tuned for the next release :)
