### ISSUE TITLE
nothing displayed using Falkon since last update

### ISSUE THREAD

**Issue by syntron** [nextcloud/bookmarks#813]
Using the bookmarks app (2.1.1) nothing is displayed using Falkon since last update. Firefox is working fine.

NC 16.0.4.1
Falkon 3.1.0
Bookmarks 2.1.1

**Comment by marcelklehr** [comment]
Any errors in the browser console? (Usually you can open that with the context menu)

**Comment by syntron** [comment]
As far as I know Falkon does not provide a browser console. There is something in development but I did not got it working (https://store.kde.org/p/1305868/)

**Comment by marcelklehr** [comment]
Until I see an error message there's not much I can do.

**Comment by syntron** [comment]
OK :-( I will check if I get the plugin running and report back

**Comment by narey83** [comment]
I'm having issues with Edge. The bookmarks app will not load. Here is the apache logs showing a 302.

[IP REMOVED] - - [29/Sep/2019:03:29:22 +0100] "GET /nextcloud/index.php/apps/files/undefined HTTP/1.1" 302 1062 "https://[HOSTNAME REMOEVED]/nextcloud/index.php/apps/files/?dir=/&fileid=6" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134"

**Comment by syntron** [comment]
This seems to be something different - at least I do not get such an error if using Falkon and it is working in Firefox for me.

**Comment by syntron** [comment]
I did not got falkon webinspector working - pyfalkon is marked as beta and no updates since quite some time. However, I observed the same effect for the mail app - version not working: 0.18.0 but working again in 0.18.1! Perhaps this helps?

**Comment by syntron** [comment]
From the changelog:

## 0.18.1 - 2019-11-04
### Fixed
- JavaScript transpilation for older browsers

I'm not sure which commit is responsible but it helped!

**Comment by marcelklehr** [comment]
I see, so the javascript version is the problem.

**Comment by marcelklehr** [comment]
Will be fixed with the next release

**Comment by syntron** [comment]
Thanks!

**Comment by syntron** [comment]
I can confirm that it works again (sorry for the late message ...)
