### ISSUE TITLE
Blank page for Edge browser

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#824]
**Describe the bug**
Opening bookmarks app results in a blank page

**To Reproduce**
bookmars startpage or bookmarks Admin page
Open
Blank page shown

**Expected behavior**
Firefox, Chrome etc. are working fine.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS X]
Edge 44

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7]
 - HTTP server: [e.g. nginx 1.1]
 - Database [e.g. MySQL 5.3]
 - PHP version: [e.g. v7.2]
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)]
17.0.0 RC 2
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)]
2.1.1
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
An excerpt of the browser log would be helpful to see what kind of error occurs.

**Comment by mw80** [comment]
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
bookmarks.main.js (1,11529)

**Comment by marcelklehr** [comment]
This should be resolved in the latest release. Let me know if it isn't.
