### ISSUE TITLE
Bookmark sidebar is gone.  Bookmarks are not alphabetized

### ISSUE THREAD

**Issue by rvanscherpe** [nextcloud/bookmarks#825]
**Describe the bug**
I upgraded to the latest bookmarks version and now the sidebar with all my folders is missing.  In the main window the items are out of order, not alphabetized. 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS X]

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7]
 - HTTP server: [e.g. nginx 1.1]
 - Database [e.g. MySQL 5.3]
 - PHP version: [e.g. v7.2]
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)]
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)]
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
Yes, the folders have been moved into the main view. You can choose a sort order for bookmarks in the settings.

**Comment by rvanscherpe** [comment]
Was there a reason that was removed?  It was extremely helpful.  I sorted by alphabetical but its reverse.  Entries starting with 'Z' are at the top.

**Comment by marcelklehr** [comment]
The reason was that it would get difficult to use / unusable with deeper folder hierarchies. I initially found it more appealing to have the folders in there, as well, but I think the new way has its advantages as well.

> I sorted by alphabetical but its reverse. Entries starting with 'Z' are at the top.

Indeed, the folders are ordered in reverse. That'd be a bug.
