### ISSUE TITLE
Can't sort alphabetically

### ISSUE THREAD

**Issue by dave-kennedy** [nextcloud/bookmarks#828]
**To Reproduce**
1. Go to bookmarks
2. Click on settings
3. Change sorting to alphabetically

**Expected Behavior**
Bookmarks are sorted alphabetically.

**Actual Behavior**
They aren't.

**Screenshots**
![Screenshot from 2019-10-06 10-18-02](https://user-images.githubusercontent.com/13735532/66272094-9fdb6b00-e822-11e9-8331-d88bf8365ef8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - Browser: Firefox 69.0.1

**Server (please complete the following information):**
 - OS: Raspbian Buster Lite 4.19.66
 - HTTP server: Apache 2.4.38
 - Database: MariaDB 10.3.17
 - PHP version: 7.3.9
 - Nextcloud version: 17.0.0
 - Bookmarks app version: 2.2.0
 - Activated Nextcloud Apps:
```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bookmarks: 2.2.0
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
 - Nextcloud configuration:
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud\/",
        "htaccess.RewriteBase": "\/",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.0.9",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false
    }
}
```
 - Nextcloud external user backend: none

**Web server error log**
No errors are present in the server log.

**Nextcloud log (nextcloud/data/nextcloud.log)**
Nada.

**Browser log**
See screenshot.

**Comment by dave-kennedy** [comment]
Weird, it's working now. The UI took a long time to update after importing about 100 bookmarks.

**Comment by marcelklehr** [comment]
I can confirm, that it takes a page reload and some fiddling to get it to work. I've fixed the behavior now, and will push an update soon.
