### ISSUE TITLE
Blank page on Firefox 52.6

### ISSUE THREAD

**Issue by bitsandnumbers** [nextcloud/bookmarks#829]
**Describe the bug**
I don't get anything when loading the bookmarks page.

**To Reproduce**
Just open the bookmarks app on Nextcloud

**Expected behavior**
Bookmarks should show up.

**Desktop (please complete the following information):**
 - OS: OSX 10.7.5
 - Browser : Icecat 52.6 compiled from sources

**Server (please complete the following information):**
 - OS: Docker image nextcloud-fpm
 - Nextcloud version: 16.5
 - Bookmarks app version: 2.2.0

**Browser Console log**
```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
Content Security Policy: Couldn’t process unknown directive ‘worker-src’  (unknown)
JQMIGRATE: Migrate is installed, version 1.4.1  main.js:354:521
oc_config is deprecated: use OC.config instead  main.js:866:44
unreachable code after return statement[Learn More]  dxf-parser.js:1352:20
SyntaxError: invalid property id  bookmarks.main.js:1:11528
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
none

**Comment by marcelklehr** [comment]
This should be resolved in the latest release. Let me know if it isn't.

**Comment by bitsandnumbers** [comment]
That's good for me. Thanks very much !
