### ISSUE TITLE
Batch deletion

### ISSUE THREAD

**Issue by Friptick** [nextcloud/bookmarks#830]
**Is your feature request related to a problem? Please describe.**
Want to delete 100 bookmarks. Don't want to spend 10 minutes clicking.

**Describe the solution you'd like**
A checkbox next to each bookmark. A button to *Delete* selected bookmarks. (Next step: other batch operations, such as *Add tag*, *Remove tag*.)

**Describe alternatives you've considered**
Clicking a lot.

Thanks for considering! And congrats for the great work.

**Comment by paulcalabro** [comment]
This would be a great feature for managing large collections of bookmarks!

**Comment by marcelklehr** [comment]
Yep, this went away rather quietly with the rewrite, as I saw no need to hold off the release for this feature, but I see the general need for bulk editing features.
