### ISSUE TITLE
Can't see details when using English (British English)

### ISSUE THREAD

**Issue by ghost** [nextcloud/bookmarks#831]
**Describe the bug**
Can't open 'details' page for any bookmark while my language is set to English (British English). Doesn't matter how the bookmark was added, either within the NC web interface, using the NC Bookmarks app on Android or using the FreedomMarks Firefox add-on. Clicking on 'details' does nothing. When changing to English (US), the problem no longer exists and the details area does appear.

**To Reproduce**
1. Add a bookmark
3. Click 'Details'
4. Nothing happens

**Expected behavior**
The details section should appear.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser: Firefox
 - Version 69.0.1

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - HTTP server: Apache
 - Database PostgreSQL 10.10
 - PHP version: 7.2
 - Nextcloud version: 17.0.0
 - Bookmarks app version: 2.2.0
 - Activated Nextcloud Apps:
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - bookmarks: 2.2.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - music: 0.10.1
  - news: 14.0.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - encryption
  - files_external
  - recommendations
  - user_ldap

**Browser log**
```
Error: "No language found."
    u humanize-duration.js:545
    e humanize-duration.js:556
    e humanize-duration.js:496
    addedDate SidebarBookmark.vue:75
    VueJS 3
    Ve SidebarBookmark.vue:33
    VueJS 7
vue.runtime.esm.js:1888:12
    VueJS 10

**Comment by barbrastreisand** [comment]
Does this mean it will be fixed in the next version?

8 Oct 2019, 14:13 by sender@mailer1.33mail.com:

**Comment by marcelklehr** [comment]
Yep :)

**Comment by barbrastreisand** [comment]
Perfect. Thanks for that!
