### ISSUE TITLE
Already defined tags are not displayed until one has manually been entered.

### ISSUE THREAD

**Issue by j-ed** [nextcloud/bookmarks#840]
Bookmark app: v2.3.0
Firefox browser: v69.0.3

## Describe the bug

After upgrading the app to v2.3.0 the sidebar doesn't contain any previously defined keywords/tags.
If I select an older bookmark keywords/tags are displayed until I select the input field. From that moment on they're not shown anymore and "List is empty" is displayed. If I now enter a keyword/tag manually, all previously defined keywords/tags are shown again, in the selection dialog and also in the sidebar. The keywords/tags are now shown as long as I'm not leaving the bookmark app.

**Comment by alastair-dm** [comment]
Same behaviour in Chromium 77.0.3865.90

**Comment by marcelklehr** [comment]
:white_check_mark: fixed in v2.3.1 ;)
