### ISSUE TITLE
Can't add bookmarks anymore

### ISSUE THREAD

**Issue by bestouff** [nextcloud/bookmarks#841]
**Describe the bug**
I can't add bookmarks anymore through the WebUI or android app

**To Reproduce**
1. Go to the "Favorites" page
2. Click on the "+" to add a bookmark
3. Nothing happens

**Expected behavior**
A new bookmark is created

**Desktop (please complete the following information):**
 - OS:Debian 10
 - Browser Firefox
 - Version 69

**Server (please complete the following information):**
 - Debian 10

 - Nextcloud version: 15.0.12
 - Bookmarks app version: 2.3.1 (but maybe also before)
- Enabled Nextcloud Apps:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bookmarks: 2.3.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.6.6
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.6
  - dav: 1.8.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_markdown: 2.1.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.1
  - news: 13.1.6
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - passman: 2.3.4
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.11.3
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
- Disabled Nextcloud Apps:
  - admin_audit
  - encryption
  - user_ldap

 [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration:
```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/nextcloud",
        "version": "15.0.12.1",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_rotate_size": 3145728,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "skeletondirectory": "",
        "maintenance": false,
        "loglevel": 2,
        "data-fingerprint": "5e84814c8f256a1faf78fc912478c665",
        "theme": "",
        "upgrade.disable-web": "true",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log"
    }
}
```
 - Nextcloud external user backend: none

**Nextcloud error log**
```
[index] Error: ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) at <<closure>>

 0. /var/www/nextcloud/lib/composer/composer/ClassLoader.php line 322
    Composer\Autoload\includeFile("/var/www/nextcl ... p")
 1. <<closure>>
    loadClass("Rowbot\\URL\\BasicURLParser")
 2. /var/www/nextcloud/apps/bookmarks/vendor/rowbot/url/src/URL.php line 72
    spl_autoload_call("Rowbot\\URL\\BasicURLParser")
 3. /var/www/nextcloud/apps/bookmarks/lib/UrlNormalizer.php line 12
    __construct("http://www.jafl ... d")
 4. /var/www/nextcloud/apps/bookmarks/lib/Bookmarks.php line 931
    normalize("http://www.jafl ... d")
 5. /var/www/nextcloud/apps/bookmarks/lib/Controller/Rest/BookmarkController.php line 308
    addBookmark("xav", "http://www.jafl ... d", "Séparation, div ... s", [], "Vous pouvez tél ... t", false, [-1])
 6. /var/www/nextcloud/apps/bookmarks/lib/Controller/Rest/InternalBookmarkController.php line 134
    newBookmark("http://www.jafl ... d", [], null, false, "", [])
 7. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    newBookmark("http://www.jafl ... d", [], null, false, "", [])
 8. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OCA\Bookmarks\Co ... {}, "newBookmark")
 9. /var/www/nextcloud/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Bookmarks\Co ... {}, "newBookmark")
10. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("InternalBookmarkController", "newBookmark", OC\AppFramework\ ... {}, {_route: "bookma ... "})
11. <<closure>>
    __invoke({_route: "bookma ... "})
12. /var/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "bookma ... "})
13. /var/www/nextcloud/lib/base.php line 987
    match("/apps/bookmarks/bookmark")
14. /var/www/nextcloud/index.php line 42
    handleRequest()

POST /nextcloud/index.php/apps/bookmarks/bookmark
from 81.250.162.208 by xav at 2019-10-25T12:45:44+00:00
```

**Comment by marcelklehr** [comment]
Make sure you have the latest version of PHP installed and running. v7.1 is the minimum requirement.

**Comment by bestouff** [comment]
Oh too bad, Debian has v7.0.33 - and no way to upgrade safely ...

**Comment by wWolfovich** [comment]
> Oh too bad, Debian has v7.0.33 - and no way to upgrade safely ...

It's true for Debian stretch which is old-stable now. So it's time to upgrade to new stable "buster".
Or to use release mix, to upgrade individual packages, but it's more difficult.

**Comment by bestouff** [comment]
Yes I saw that. Unfortunately [upgrading will have to wait a bit](https://help.nextcloud.com/t/stable-debian-repository/1662/75).
