### ISSUE TITLE
Bug: Installation Failure reporting the absence of the "library gmp" 

### ISSUE THREAD

**Issue by sproggit** [nextcloud/bookmarks#847]
An attempt to install the library, using the NextCloud application installer, to an installation reported as "Nextcloud 17.0.0" in the Administration Overview. 

**To Reproduce**
1. Go to The integrated application browser and find the Bookmarks App in the library
2. Click on the Application to initiate download and installation
3. See error

**Expected behavior**
Expectation was for the application to install cleanly. 

**Screenshots** [Actually the log file error report] 
[settings] Error: Exception: App "Bookmarks" cannot be installed because the following dependencies are not fulfilled: The library gmp is not available. at <<closure>>

0. /home/sauriano/public_html/saurian/nc/lib/private/Installer.php line 129
   OC_App::checkAppDependencies(OC\AllConfig {}, OC\L10N\LazyL10N {}, {id: "bookmarks" ... }}, false)
1. /home/sauriano/public_html/saurian/nc/settings/Controller/AppSettingsController.php line 447
   OC\Installer->installApp("bookmarks")
2. /home/sauriano/public_html/saurian/nc/lib/private/AppFramework/Http/Dispatcher.php line 170
   OC\Settings\Controller\AppSettingsController->enableApps(["bookmarks"], [])
3. /home/sauriano/public_html/saurian/nc/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\Cont ... {}, "enableApps")
4. /home/sauriano/public_html/saurian/nc/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\Cont ... {}, "enableApps")
5. /home/sauriano/public_html/saurian/nc/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OC\\Settings\\C ... r", "enableApps", OC\AppFramework\ ... {}, {_route: "settin ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "settin ... "})
7. /home/sauriano/public_html/saurian/nc/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "settin ... "})
8. /home/sauriano/public_html/saurian/nc/lib/base.php line 1000
   OC\Route\Router->match("/settings/apps/enable")
9. /home/sauriano/public_html/saurian/nc/index.php line 42
   OC::handleRequest()

**Desktop (please complete the following information):**
 - OS: [Linux Mint 19.2/64-Bit]
 - Browser [Firefox]
 - Version [70.0.0/64-bit]

**Server (please complete the following information):**
 - OS:[Cloud6 - ISP Platform - Kernel Version 2.6.32-954.3.5.lve1.4.66.el6.x86_64
 - HTTP server: Apache 2.4.41
 - Database: MySQL 10.2.27-MariaDB
 - PHP version: 7.2.22
 - Nextcloud version: 17.0.0
 - Bookmarks app version: It does not say - there is no mention of a version on the Apps Page
 - Activated Nextcloud Apps: No access to Command Line - hosted @ ISP
 - Nextcloud configuration: No access to Command Line - hosted @ ISP
 - Nextcloud external user backend: None

**Additional context**
The reason for raising the ticket is that the error does not help me understand if I may have the scope to resolve the dependency issue, because I'm not sure where the "gmp library" neads to be installed or run from... 

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
I agree that the user experience in this case is not as good as it could be. I will add the [relevant parts of the README](https://github.com/nextcloud/bookmarks#requirements) to the app description in the app store.

**Comment by sproggit** [comment]
Thank you Marcel, I very much appreciate the prompt response. I am not a developer, so it may be impolite of me to ask this question [I do not mean to offend], but when I explored to better understand what the GMP library offers, I realised that it is a GNU library for precision arithmetic. 

This came as a real surprise, because it is not apparent to me why you would need to have a "precision arithmetic" library in a bookmark management utility. Obviously, I am sure there is a reason... 

However, I wonder if it might be possible to expand the usability of the Bookmark code if a way could be found to provide the functionality you derive from the library via a different means? And I *am* sorry, as a user who is grateful for the opportunity to enjoy this code that you offer for free, I am very aware that this comment could easily be taken to be rude. I REALLY do not mean it that way. I am genuinely curious to understand why such a library is used... 

[Unfortunately, the reason this is relevant for me is that I have installed my NextCloud instance with a web hosting company. I am renting "space" and not a virtual server, so I have no ability to add libraries to the server, which means I am basically unable to try your application code.] 

Thank you again for the prompt response.

**Comment by sproggit** [comment]
Issue resolved; documentation to be clarified.

**Comment by marcelklehr** [comment]
(Reopened, as it's not done yet ;) )

**Comment by marcelklehr** [comment]
Thank you for your considerate message. It is indeed a valid question to ask why the bookmarks app requires an additional library that might not be available in some scenarios, especially when it seems unrelated to the scope of the app.

The gmp extension is required for parsing and normalizing the URLs you input into the app. As the URL standard is not trivial to implement and involves parsing IP addresses as well as handling Unicode encodings, for this reason I decided to use a third-party library that takes over this part, which sadly depends on gmp to do its job.

**Comment by leeand00** [comment]
I believe this and this will fix it:

- https://help.nextcloud.com/t/gmp-library-error/59355
- https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=php%20gmp

I installed the php-gmp library and restarted Apache2 and it worked just fine.

**Comment by sproggit** [comment]
> I believe this and this will fix it:
> 
>     * https://help.nextcloud.com/t/gmp-library-error/59355
>     * https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=php%20gmp
>  
> I installed the php-gmp library and restarted Apache2 and it worked just fine.

That does indeed solve the problem... Unfortunately for me, I was hoping to host my NextCloud Bookmark module in an instance hosted by an ISP, which would have meant that I could have added bookmarks from anywhere on the internet (home, work, etc). My ISP does not include the GMP module in the build of their virtual servers. I raised a ticket to ask if they would be willing to do so, but they have refused. So for now I'm limited to using this NC App from a private instance at home.
