### ISSUE TITLE
share

### ISSUE THREAD

**Issue by NoverNobida** [nextcloud/bookmarks#858]
**Is your feature request related to a problem? Please describe.**
Share my bookmarks

**Describe the solution you'd like**
I hope I can share my bookmarks (single or folders) to others, and when I renew bookmarks, other people can get the lastest bookmarks via the share links.

**Describe alternatives you've considered**

**Additional context**

**Comment by marcelklehr** [comment]
Hey @Nover2 :)
Thanks for your feedback! This need has been documented already (#5) and I'm (slowly) working on implementing it :)
