### ISSUE TITLE
Failed to create bookmark

### ISSUE THREAD

**Issue by souldessin** [nextcloud/bookmarks#859]
Hello,

  I'm running Nextcloud 16.0.4 right now and I was trying to add a bookmark. I keep getting `failed to create bookmark` at the top and the JS console of both Firefox and Chrome on Windows says below.

```
Error: "Request failed with status code 500"
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:59
```

I did try and make a folder and it worked. The link in question is `https://www.crochetbeja.com/lovely-mesh-stitch-knitting-pattern/`. I also tried `http://www.dailyrotation.com/`.

Thanks for the help

**Comment by marcelklehr** [comment]
Could you check the nextcloud log for errors?

**Comment by souldessin** [comment]
I'm sorry to delay in responding and it turned out to be an issue on my end. I had an out of date php7.2-intl package installed and it was causing the problem. After updating, it was working fine.

Thank you for the help and the Nextcloud app!
