### ISSUE TITLE
Creating a bookmark while in a folder should retain the ownership of that folder

### ISSUE THREAD

**Issue by rtyler** [nextcloud/bookmarks#865]
**Describe the bug**

When the current browse context in the web app is in a bookmarks folder, and try to create a bookmark in that folder, it _always_ gets created in the root folder.

![bookmarks](https://user-images.githubusercontent.com/26594/69591353-5d731680-0fa7-11ea-8c61-0cbe03c7e39d.png)

**To Reproduce**
1. Go to the bookmarks app
1. Create a new folder
1. Navigate into that folder
1. Click "New Bookmark"
1. Enter a URL
1. Navigate back to the root folder
1. HEY! That's not supposed to be there!

**Expected behavior**

When creating a bookmark in a folder, I expect it to remain in that folder

**Screenshots**

![bookmarks](https://user-images.githubusercontent.com/26594/69591353-5d731680-0fa7-11ea-8c61-0cbe03c7e39d.png)

**Comment by marcelklehr** [comment]
Nice catch! Thanks for the feedback :)

**Comment by rtyler** [comment]
@marcelklehr Out of curiosity, what's the release cadence for the bookmarks app to the store? I'm debating whether I want to package and install this off `master` or if I should just wait :smile_cat:

**Comment by marcelklehr** [comment]
Thanks for reaching out! I was planning to make 3.0.0 the next release, but as it transpires that this will still take some more time, I'll just do a release now :)

**Comment by rtyler** [comment]
Hah, no worries. I understand the challenges of being a FOSS maintainer, so please don't count this as any pressure from me to push a release.

**Comment by marcelklehr** [comment]
Not at all :D It's been in the back of my mind to release these small fixes anyway :)

**Comment by marcelklehr** [comment]
Ooph, you are completely right. I just pushed a new bugfix release.

**Comment by rtyler** [comment]
2.3.3 includes the fix looks like, thanks :smile_cat:
