### ISSUE TITLE
Add dashboard widget

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#869]
Dashboard v6 is apparently quite nice from what I've gathered. A bookmarks widget might be in order: https://github.com/nextcloud/dashboard

**Comment by Spartachetto** [comment]
Have you seen this: https://github.com/nextcloud/server/issues/20930 ?

I'd have a look before starting to implement something ...

Thank you for your work!

**Comment by marcelklehr** [comment]
Ah, nice. Thanks for the link!

**Comment by marcelklehr** [comment]
v4.x is released
