### ISSUE TITLE
Cleanup backup files in tree

### ISSUE THREAD

**Issue by darix** [nextcloud/bookmarks#876]
```find -name \*~ -print -delete```

**Comment by marcelklehr** [comment]
Mmh. There actually are no backup files in the repo :thinking:

**Comment by darix** [comment]
But they are in the released tarball.

**Comment by marcelklehr** [comment]
Ah, I understand. Only one of those I actually control, though. The rest is courtesy of various npm packages. :man_shrugging:

**Comment by darix** [comment]
well you seem to have scripts to package things and could clean things up e.g.
