### ISSUE TITLE
Can't import bookmarks from Chrome: No file provided for import error

### ISSUE THREAD

**Issue by fazlerabbi37** [nextcloud/bookmarks#881]
### Steps to reproduce
- go to Chrome bookmark manager
- export all bookmarks (around 30K)
- go to bookmarks app
- go to setting
- click import
- choose bookmark_$DATE.html file
- click open 

### Expected behaviour
it should start importing the bookmarks

### Actual behaviour
it gives No file provided for import error.

## Server configuration detail
**Running on Official Nextcloud Docker.**

**Operating system:** Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** sqlite3 3.27.2

**PHP version:** 

7.3.13
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 17.0.2 - 17.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - bookmarks: 2.3.4
 - bruteforcesettings: 1.4.0
 - calendar: 2.0.0-alpha2
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.6
 - dav: 1.13.0
 - deck: 0.7.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - issuetemplate: 0.5.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - mail: 0.21.0
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - passman: 2.3.5
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - tasks: 0.11.3
 - text: 1.1.1
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost:8080",
        "192.168.0.157:8080"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "version": "17.0.2.1",
    "overwrite.cli.url": "http:\/\/localhost:8080",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "app_install_overwrite": [
        "keeweb",
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Google Chrome. user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36

**Operating system:** Ubuntu 18.04 LTS

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
172.17.0.1 - - [21/Dec/2019:12:44:39 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 873 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36"
172.17.0.1 - - [21/Dec/2019:12:44:39 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 872 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36"
172.17.0.1 - - [21/Dec/2019:12:44:45 +0000] "POST /apps/bookmarks/bookmark/import HTTP/1.1" 200 816 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36"

```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
           actions.js:223 Error: No file provided for import
        at actions.js:214
    (anonymous) @ actions.js:223
    Promise.catch (async)
    (anonymous) @ actions.js:222
    (anonymous) @ vuex.esm.js:732
    u.dispatch @ vuex.esm.js:437
    dispatch @ vuex.esm.js:331
    onImportSubmit @ Settings.vue:125
    $t @ vue.runtime.esm.js:1854
    n @ vue.runtime.esm.js:2179
    r._wrapper @ vue.runtime.esm.js:6911
    actions.js:214 Uncaught (in promise) Error: No file provided for import
        at actions.js:214

	b) The network log
	c) ...
</details>

**Comment by marcelklehr** [comment]
Hey, @fazlerabbi37 ! I just saw your post in the forums. I'm sorry for the delay!
I will try to reproduce this soon.

**Comment by fazlerabbi37** [comment]
@marcelklehr thanks for the response! I am really looking forward to the transition from Chrome Sync to NC Bookmarks.

**Comment by fazlerabbi37** [comment]
@marcelklehr did get any chance to look into this?

**Comment by marcelklehr** [comment]
With the latest master branch I cannot reproduce this anymore, chances are the next release will fix this.
