### ISSUE TITLE
Bulk deletion

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/bookmarks#886]
I understand this is supposed to be addressed by #424 but I am currently unable to delete more than one bookmark at a time. If I tick the boxes for multiple bookmarks, then select the ellipsis (...) marker and click on delete, only the active bookmark is deleted. Any other bookmarks that I've selected are left undeleted.

Is there something else I need to do to bulk delete, or has something changed since #424?

Thanks,

Tyler
nextcloud 17.0.1
bookmarks 2.3.4

---
*Originally submitted by @plantarum*

**Comment by marcelklehr** [comment]
@plantarum I cannot reproduce this. However, I suspect that you used the context menu of a single bookmark, instead of the bulk menu at the top.
![image](https://user-images.githubusercontent.com/986878/71581008-943ad000-2b03-11ea-95d5-10b912783a75.png)

**Comment by plantarum** [comment]
Oh, I did. I didn't see the separate bulk edit menu ...

Thanks,

Tyler

--
plantarum.ca
