### ISSUE TITLE
Need help: How to create the database tables für postgre 12.1 manually?

### ISSUE THREAD

**Issue by abysso2** [nextcloud/bookmarks#889]
Hi there,
i tried "bookmarks" some weeks ago and deinstalled it afterwards - also the database tables. 

If i reinstall the app now, the installation does not create any database tables and i can not use bookmarks.

Can anyone provide the postgre-statements, so that i can create them manually? (Postgre 12.1)

Thx,
Andreas

**Comment by marcelklehr** [comment]
You can simply run the following in your sql client:

```sql
delete from oc_migrations where app = 'bookmarks';
```

After that the migrations should be executed correctly upon installation.

**Comment by abysso2** [comment]
Great!!!! Thank you so much!
