### ISSUE TITLE
Hooks feature / Nextcloud flow

### ISSUE THREAD

**Issue by goodevilgenius** [nextcloud/bookmarks#900]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to integrate Nextcloud Bookmarks with services that provide webhooks, such as IFTTT.

**Describe the solution you'd like**

Add webhooks for when new bookmarks are added.

E.g., I can define a hook for any time any bookmark is added, which might POST to https://maker.ifttt.com/trigger/bookmarks/with/key/reallylongkey with a body that contains:

```
value1=Bookmark%20title&value2=Bookmark%20body&value3=comma,separated,tags
```

Of course, the URL and body would be able to be customized.

A JSON body, rather than x-www-form-urlencoded would also be useful.

It would also be nice to be able to set webhooks for a specific tag.

**Describe alternatives you've considered**

- RSS feed doesn't seem viable, because authentication is required.
- I could create my own middleman service, but it would be nice for it to be built-in

**Comment by marcelklehr** [comment]
Hey Dan!

Thanks for your feedback, this seems like a really cool idea! I'm not
sure if it fits the scope of this app, though. I think this might be a
prime candidate for using nextcloud flow (which I'm not too knowledgable
about). E.g. as the bookmarks app exposes nextcloud-internal hooks it
should be possible to create a small flow that is able to trigger a web
hook.

I would be happy to help you in this endeavor (e.g. via
https://gitter.im/nextcloud-bookmarks/community). For starters, it would
be awesome if you could look into nextcloud flow and see if there's more
work needed in the bookmarks app to realize this.

**Comment by marcelklehr** [comment]
see #900
