### ISSUE TITLE
Some Critical functionality features that we need

### ISSUE THREAD

**Issue by hosadokha** [nextcloud/bookmarks#903]
**Is your feature request related to a problem? Please describe.**
No, kinda

**Describe the solution you'd like**
I am aware what this extension is capable of.. but it is too minimal for what I need
I like that this is totally independent on Google but the world needs online backup not just for bookmarks, **but for History** (such as U History extension, but it depends on G. sync) and **extensions backup and (browser & extension) Settings backup**, all into one cross platform powerfull extension, where i am able to view what exactly is held in the cloud.
I hate G.sync btw bec. I synced once and I got BOMBARDED (without my consent or approval) by all those ancient extensions that just were there in the servers from a long time ago. and the fact that i am not able to pick what gets synced, espesially when i cant see whats up in the cloud, AND THATS WHY I USE THE WORD "BACKUP" AND NOT "SYNC" because "syncing" is too simplistic of an idea.. MY EXISTING bookmarks also got automatically removed by G.sync..
I hope the developers take this Advice profoundly to their heart because this is truly what I need, and what I would pay for..

**Additional context**

**Comment by bernd-wechner** [comment]
With all due respect what you want is something else indeed. Go find it. And good luck. What you will find in the free and open source (FOSS) world that independent of the big players (which you so like) is that it is understaffed in the extreme and almost no project without a huge injection of funding ad excited new employees is looking to grow well beyond where it's at.

As to the specifics, where can you see this on-line, in your NextCloud instance clearly. You can host one at home or [find one on-line ](https://nextcloud.com/providers/) I guess.

And you back your NextCloud instance up in any number of ways onto the cloud or elsewhere.

**Comment by marcelklehr** [comment]
Thanks @bernd-wechner for summing up the FOSS situation pretty well. :smile: 

> but for History (such as U History extension, but it depends on G. sync) and extensions backup and (browser & extension) Settings backup

It might be possible to do a history sync/backup with an browser extension one day. I doubt that cross-platform browser/extension/settings backup will ever work as that's why there are different platforms in the first place: they are different. You'll be hard put to find let alone sync matching browser settings, extensions from the two major extension markets, etc.

**Comment by hosadokha** [comment]
> Thanks @bernd-wechner for summing up the FOSS situation pretty well. 
> 
> > but for History (such as U History extension, but it depends on G. sync) and extensions backup and (browser & extension) Settings backup
> 
> It might be possible to do a history sync/backup with an browser extension one day. I doubt that cross-platform browser/extension/settings backup will ever work as that's why there are different platforms in the first place: they are different. You'll be hard put to find let alone sync matching browser settings, extensions from the two major extension markets, etc.

I did not mean "cross-platform browser" I just meant I want A third party to backup my extensions online.

**Comment by marcelklehr** [comment]
> I did not mean "cross-platform browser" I just meant I want A third party to backup my extensions online.

Ah, ok. Good luck then.
