### ISSUE TITLE
Nextcloud Bookmark Manger App will not install I get a error and it will not go any further.

### ISSUE THREAD

**Issue by eredwood007** [nextcloud/bookmarks#904]
**Describe the bug**
A clear and concise description of what the bug is. I am running Nextcloud on Ubuntu Server 18.04 LTS  x89_64 

**To Reproduce**
Steps to reproduce the behavior: Bookmark Manager
1. Go to ' I am using the Apps/ Organization/ Bookmarks / Downloads and enable...'
4. See error An exception occurred while executing 'CREATE TABLE oc_bookmarks_tags (bookmark_id BIGINT DEFAULT NULL, tag VARCHAR(255) DEFAULT '' NOT NULL, UNIQUE INDEX bookmark_tag (bookmark_id, tag)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS X]

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7]
 - HTTP server: [e.g. nginx 1.1]
 - Database [e.g. MySQL 5.3]
 - PHP version: [e.g. v7.2]
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)]
 - Bookmarks app version: [e.g. 1.1.0 (see Nextcloud apps page)]
 - Activated Nextcloud Apps: [the output of running `$ sudo -u www-data php occ app:list` in your command line]
 - Nextcloud configuration: [the output of running `sudo -u www-data php occ config:list system`]
 - Nextcloud external user backend: [e.g. ldap, or none]

**Additional context**

**Web server error log**
```
Insert your webserver log here
```

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
Insert your Nextcloud log here
```

**Browser log**
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by marcelklehr** [comment]
The problem is that you are using `utf8mb4` (which is usually a good idea) together with an older version of mysql (v5.3), where the max key limit is 767 bytes.

Your choices are

* update MySQL to v5.7+
* switch back to a non-multibyte charset in your db
