### ISSUE TITLE
privacy.enableScraping setting is being ignored, causing information to be leaked

### ISSUE THREAD

**Issue by DamnedElric** [nextcloud/bookmarks#909]
**NOTE:** Updated with corrections

**Description**

FR #647 added an option intended to enable/disable fetching previews when adding bookmarks. It seems this setting is being misinterpreted, and each new bookmark added causes the "Nextcloud Server Crawler" to fetch the URL. Thus exposing my bookmark server to the bookmarked website. Seems like a security and privacy issue to me.

The setting "privacy.enableScraping" is disabled by default in Bookmarks >  Settings > Privacy, but it appears the *default* is being misinterpreted when no value is present in the database. When Bookmarks is installed, no value is present, and the code assumes the default to be "true". Once the setting has been enabled, and then disabled in the UI, the behaviour becomes correct.

**Expected behavior**
NC/Bookmarks should not be leaking information about which sites I decide to bookmark unless I *enable* the scraping.

**Versions**
 - NC version 17.0.3
 - Bookmarks version 2.3.4.

**Comment by marcelklehr** [comment]
Fix in the repo, the next release will have the fix. Thanks for your feedback :heart:
