### ISSUE TITLE
library gmp is not available

### ISSUE THREAD

**Issue by devplan44** [nextcloud/bookmarks#919]
**An error occured during the request. Unable to proceed.
App "Bookmarks" cannot be installed because the following dependencies are not fulfilled: The library gmp is not available.**

**To Reproduce**
Attempting to install newest bookmarks version on hosted nextcloud instance 16.0.1

**Expected behavior**
supposed to work within common hosted platforms without requiring extra libraries

**Desktop (please complete the following information):**
 - OS: CentOs 7 
 - Browser Chrome
 - Version 80.0.3987.106 (Official Build) (64-bit)

**Server (please complete the following information):**
 - OS: e.g. Ubuntu0.18.04.3
 - HTTP server: nginx/1.14.0
 - Database [e.g. MySQL 5.3]
 - PHP version: v7.2
 - Nextcloud version:  16.0.1 
 - Bookmarks app version: 2.3.4

**Comment by SuperSandro2000** [comment]
You are missing the ``php-gmp`` library on your system. You can install it with ``sudo apt install php-gmp``

**Comment by devplan44** [comment]
My web host doesn't permit installs. Nextcloud also works without additional libs. Why can't bookmarks do?

**Comment by SuperSandro2000** [comment]
You could ask them to add this php module or you just switch to a VPS.

Well technically nextcloud needs [those libs](https://docs.nextcloud.com/server/18/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation) but for you they where already installed.

I mean there is probably the possibility to polyfill this module but this is probably slower and would add bloat for everyone.

**Comment by devplan44** [comment]
Good point. I will move to a VPS. Normal web hosting is just too limited.
