### ISSUE TITLE
Basic Auth Prompt Appearing

### ISSUE THREAD

**Issue by veeshi** [nextcloud/bookmarks#921]
**Describe the bug**
The nextcloud instance is hosted on a subdomain. The main domain is protected with Basic Auth. When loading the bookmarks app the basic auth prompt appears. Looking at the network requests the below url is requested subdomain.example.com/svg/core/places/link?color=666666. Disabling basic auth on the base domain causes the prompt to go away.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable basic auth on base domain and put nextcloud instance on subdomain 
2. Go to bookmarks app
3. Prompt appears

**Expected behaviour**
No basic auth popup

**Comment by marcelklehr** [comment]
Are there any network requests for the base domain? (The one you pasted still is for the subdomain)

**Comment by veeshi** [comment]
No network requests to the base domain in the network log in the browser which is what makes it unusual

**Comment by marcelklehr** [comment]
Can you run

```
$ curl -v subdomain.example.com/svg/core/places/link?color=666666
```

and paste the output here?

**Comment by marcelklehr** [comment]
@veeshi ?

**Comment by veeshi** [comment]
Apologies, appears to have been an unrelated issue causing this due to a routing error when using multiple domains on a single host.
