### ISSUE TITLE
Notes are not imported

### ISSUE THREAD

**Issue by eldelacajita** [nextcloud/bookmarks#923]
**Describe the bug**
When importing a bookmark export files, notes are not imported. It happens with:
- An HTML file exported from Diigo in "Chrome format".
- An HTML file exported from the very same instance of Nextcloud Bookmarks.

**To Reproduce**
1. Start from a blank Bookmarks instance.
2. Create some bookmarks in Nextcloud Bookmarks.
3. Export the bookmarks.
4. Delete all the existing bookmarks. 
5. Import the bookmarks (in the very same NC Bookmarks instance).
6. Everything is imported, except the notes field, which is now empty.

It can also be reproduced by using an HTML file exported from Diigo in "Chrome format". I compared both files and the only thing that the Diigo export seems to lack is closing </DD> tags. Manually closing some of them doesn't seem to solve this. And it also fails with a file exported from the Bookmarks app itself, anyway.

**Expected behavior**
All bookmarks should appear and have their titles, tags and **notes**. 

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: 72.0.2
 

**Server (please complete the following information):**
 - OS:  Not sure (shared OwnCube hosting)
 - HTTP server: Not sure (shared OwnCube hosting)
 - Database: MySQL 10.3.22
 - PHP version: 7.2.28
 - Nextcloud version: 16.0.4.1
 - Bookmarks app version: 2.3.4
 - Activated Nextcloud Apps: A lot, just let me know if you need the detailed list.
 - Nextcloud configuration: Can't access the server to check that.
 - Nextcloud external user backend: Not sure.

**Additional context**
This is the whole content of the sample file I exported and tried to re-import.

```
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE><H1>Bookmarks</h1>
<DL><p><DT><A HREF="https://gitlab.gnome.org/explore/groups" TAGS="test" ADD_DATE="1581093414">Groups · Explore</A>
<DD>Welcome to GNOME’s integrated development platform, powered by GitLab</DD>
<DT><A HREF="https://github.com/" TAGS="test" ADD_DATE="1581093391">GitHub</A>
<DD>GitHub is where people build software. More than 40 million people use GitHub to discover, fork, and contribute to over 100 million projects.</DD>
</p></DL>
```

If you need any other logs or info, please let me know and I'll see what I can do :)

**Comment by marcelklehr** [comment]
I've fixed this in the repo, the next release will have the fix.

**Comment by eldelacajita** [comment]
That's awesome! Looking forward to trying it.
