### ISSUE TITLE
No bookmarks are shown, none can be added

### ISSUE THREAD

**Issue by IzzySoft** [nextcloud/bookmarks#924]
**Describe the bug**

I've just updated to Bookmarks 2.3.4 (due to heaving my Nexcloud instance to NC15 finally; will upgrade to NC16+ soon). Now, the Bookmarks app is no longer working for me. Tags are shown with the number of bookmarks they cover, but no bookmarks are shown and neither can any be added.

**To Reproduce**

1. Go to 'Bookmarks'
2. See empty list stating no bookmarks exist
3. try to add a bookmark
4. see error that it cannot be created

**Expected behavior**

Existing bookmarks are shown, new ones can be added.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.3
 - Browser Waterfox Classic
 - Version Version of what? Desktop (Cinnamon)? Waterfox (2020.02)?

**Server (please complete the following information):**

- OS: Linux Mint 18.3
- HTTP server: Apache 2.4
- Database MariaDB
- PHP version: 7.0
- Nextcloud version: 15.0.12
- Bookmarks app version: 2.3.4
- Activated Nextcloud Apps: 
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.5.0
  - calendar: 1.6.6
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.6
  - cookbook: 0.5.7
  - dav: 1.8.2
  - drawio: 0.9.5
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_markdown: 2.1.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.11.3
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
- Nextcloud configuration:

<details><summary>JSON</summary>
<pre>{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nebo.qumran.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.12.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "check_for_working_webdav": false,
        "check_for_working_htaccess": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "30, 180",
        "versions_retention_obligation": "90, 365",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "overwrite.cli.url": "https:\/\/nebo.qumran.org:4443\/owncloud",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "589",
        "theme": ""
    }
}</pre>
</details>

- Nextcloud external user backend: none

**Additional context**

I've seen #841 – but PHP 7.1+ is not available on my current setup. As the Bookmarks app is essential to me (my backlog is in there), I'm in a mess now. If there's a Bookmarks version I can downgrade to (which still supports PHP 7.0 AND Nextcloud 15+), that would be much appreciated (including a hint on how to downgrade). A system upgrade is out of the question currently (I'm already drowning in tasks).

I've also seen #709 – and yes, `php-intl` is installed.

**Web server error log**

A bit much :wink:

**Nextcloud log (nextcloud/data/nextcloud.log)**
```
ParseError: syntax error, unexpected '='
    /var/www/nextcloud/lib/composer/composer/ClassLoader.php - line 322:
    Composer\Autoload\includeFile("/var/www/ne ... p")
    <<closure>>
    Composer\Autoload\ClassLoader->loadClass("OCA\\Bookma ... r")
    /var/www/nextcloud/apps/bookmarks/lib/AppInfo/Application.php - line 65:
    spl_autoload_call("OCA\\Bookma ... r")
    /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php - line 118:
    OCA\Bookmarks\AppInfo\Application->OCA\Bookmarks\AppInfo\{closure}("*** sensiti ... *")
    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117:
    Pimple\Container->offsetGet("BookmarkController")
    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 419:
    OC\AppFramework\Utility\SimpleContainer->query("BookmarkController")
    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 397:
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("BookmarkController")
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 95:
    OC\AppFramework\DependencyInjection\DIContainer->query("BookmarkController")
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:
    OC\AppFramework\App::main("BookmarkController", "getBookmarks", "*** sensiti ... *", { _route: "b ... "})
    <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "b ... "})
    /var/www/nextcloud/lib/private/Route/Router.php - line 297:
    call_user_func(OC\AppFramew ... {}, { _route: "b ... "})
    /var/www/nextcloud/lib/base.php - line 987:
    OC\Route\Router->match("/apps/bookm ... k")
    /var/www/nextcloud/index.php - line 42:
    OC::handleRequest()
```

**Browser log**
```
Error: Request failed with status code 500
Stack trace:
t.exports@https://<server>/nextcloud/apps/bookmarks/js/bookmarks.main.js?v=5ac9ca25-0:323:16635
t.exports@https://<server>/nextcloud/apps/bookmarks/js/bookmarks.main.js?v=5ac9ca25-0:399:2595
t.exports/</f.onreadystatechange@https://<server>/nextcloud/apps/bookmarks/js/bookmarks.main.js?v=5ac9ca25-0:323:15567
  actions.js:545:4
Unhandled promise rejection TypeError: d.a.t is not a function
Stack trace:
C</<@https://<server>/nextcloud/apps/bookmarks/js/bookmarks.main.js?v=5ac9ca25-0:1:18564
N/</<@https://<server>/nextcloud/apps/bookmarks/js/bookmarks.main.js?v=5ac9ca25-0:301:28975
N/<@https://<server>/nextcloud/apps/bookmarks/js/bookmarks.main.js?v=5ac9ca25-0:301:28843
u@https://<server>/nextcloud/apps/bookmarks/js/bookmarks.main.js?v=5ac9ca25-0:301:36737```

**Comment by IzzySoft** [comment]
Notes:

* [hints on downgrade](https://github.com/nextcloud/bookmarks/issues/783#issuecomment-526711609)
* major distributions (e.g. Debian Buster) still ship PHP 7.0, so requiring a version not available on those is at least a bit problematic
* latest Bookmarks version that seems to meet my requirements: [v2.0.3](https://github.com/nextcloud/bookmarks/tree/v2.0.3) requires PHP 5.4+ and NC 15+, according to its `appinfo/info.xml` (confirmation welcome); `gmp`, `intl` and `mbstring` PHP modules will certainly be required by other versions as well.

**Comment by marcelklehr** [comment]
Support for php v7.0 was dropped with v2.0.0. Try v1.1.2. It also doesn't require gmp.

**Comment by IzzySoft** [comment]
Thanks @marcelklehr – strange thing is only that even Buster still ships only 7.0. I know Debian isn't exactly known for shipping the latest versions, but EOL...?

Just as safeguard: between 1.1.2 and 2.0.0, have there been any database changes? If so, any pointer on how to rollback those? I do have a backup of the NC database from before the upgrade (and AFAIR I have been running on 1.1.2 or older then) in case I should need to replace the bookmarks table or something like that.

**Comment by marcelklehr** [comment]
There have been no [database migrations](https://github.com/nextcloud/bookmarks/tree/master/lib/Migration) since v1.0.7. The next migrations will happen with the release of v3 (sharing, woop, woop).

**Comment by IzzySoft** [comment]
OK, thanks! Both v2.0.3 and v1.1.2 show the bookmarks. But in the left panel, the tag list is gone (only shows "Ohne Kategorie" ("without category"), and "Add Category". I'd consider that a "working state" (as I at least can access my bookmarks again). Haven't tested adding bookmarks yet, though (especially via the API, from my Android device).

**Comment by IzzySoft** [comment]
PS: I've checked all logs. Nothing in the JS console, nothing in the NC log. But Apache shows some 500s in its `access.log` immediately after the call to bookmarks:

    "GET /nextcloud/svg/core/places/link?color=666666 HTTP/1.1" 500

7 times, followed by a

    "GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200

Not sure if that's related. That link seems to belong to the [Svg color api](https://docs.nextcloud.com/server/15/developer_manual/design/icons.html#svg-color-api). No enty in the Apache `error.log`, though.

Calling that "500" link directly, I get an entry in the nc log:

```json
{"reqId":"XlhgF38AAQEAAFJRn8IAAAAI","level":3,"time":"2020-02-28T00:34:31+00:00","remoteAddr":"xxx.xxx.xxx.xx","user":"me","app":"index","method":"GET","url"
:"\/nextcloud\/svg\/core\/places\/link?color=666666","message":{"Exception":"Exception","Message":"The requested uri(\/nextcloud\/svg\/core\/places\/link) can
not be processed by the script '\/owncloud\/index.php')","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":930,"function":"getRawPathInf
o","class":"OC\\AppFramework\\Http\\Request","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"O
C","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Request.php","Line":784,"CustomMessage":"--"},"userAgent":"Mozilla
\/5.0 (X11; Linux x86_64; rv:56.0) Gecko\/20100101 Firefox\/56.0 Waterfox\/56.3","version":"15.0.12.1"}
```

**Comment by IzzySoft** [comment]
Short update: browse, add, delete via API seems to work fine. It seems all I'm missing is the "browse by tag" in the WebIf. As I rarely use that and thus 95% of functionality I use are covered, I find that fair enough – considering I'm still running a Nextcloud version no longer supported which I could upgrade with reasonable effort (putting aside the PHP 7.0 issue I have no control over).

So for NC 15 users: v1.1.2 seems fine. Will test v2.0.3 with NC 16 as soon as time permits and report back then.

Thanks for your help, @marcelklehr!

**Comment by IzzySoft** [comment]
Ah, last note: cannot test with NC16 as that itself requires PHP 7.1+ – hence you're correct to close this, sorry for not updating earlier…
