### ISSUE TITLE
Update Error / kein Update möglich

### ISSUE THREAD

**Issue by basti2015** [nextcloud/bookmarks#925]
I have install v. 0.17.0 now I get the update Massage to update to v. 2.3.4. When I click on "update" The update is not install. It still the last one v. 017.0.

Ich habe aktuell die v. 0.17.0 installiert, jetzt bekomme ich die Meldung das ich auf die Version 2.3.4 update kann. Wenn ich das Update ausführe bleibt es aber bei der alten Version v. 017.0

**Comment by marcelklehr** [comment]
Hello @basti2015 :wave: 
It is likely your setup is missing some of the requirements of this app. Please check: https://github.com/nextcloud/bookmarks#requirements

Ich vermute, dass dein setup nicht alle Anforderungen für die app erfüllt. Schau mal hier: https://github.com/nextcloud/bookmarks#requirements

**Comment by basti2015** [comment]
Danke. Aber alle php pakete sind bereits installiert. Habe php 7.2.24 installiert.
System ist auch up-to-date

**Comment by marcelklehr** [comment]
Which nextcloud version?

Welche nextcloud version?

**Comment by marcelklehr** [comment]
Also, try checking the nextcloud log for errors.
