### ISSUE TITLE
Hamburger Button in UI doesn't display menu in Firefox

### ISSUE THREAD

**Issue by leeand00** [nextcloud/bookmarks#933]
**Describe the bug**
Resize your window vertically until the menu disappears and the Hamburger button appears; then click the hamburger button and all I get is a white space where the menu should be.

**To Reproduce**
1. Resize your window vertically until the menu disappears and the Hamburger button appears.
2. Click on the hamburger button.
4. There's a white space where the menu should be.

**Expected behavior**
I expected to see the menu.  But I have to maximize the window to see it.

**Screenshots**
![e](https://user-images.githubusercontent.com/83778/75631786-c5975100-5bc3-11ea-897d-8c0d1b61f56e.png)
![e](https://user-images.githubusercontent.com/83778/75631787-c8924180-5bc3-11ea-90d1-d2258d84a08f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 build 1903
 - Browser Firefox
 - Version 73

**Server (please complete the following information):**
N/A 

**Additional context**
N/A

**Web server error log**
N/A

**Nextcloud log (nextcloud/data/nextcloud.log)**
N/A

**Browser log**
N/A

**Comment by marcelklehr** [comment]
Which nextcloud version is that?

**Comment by marcelklehr** [comment]
@leeand00 Is this still happening for you?
