### ISSUE TITLE
Daten Wiederherstellung aus Verzeichnisbackup

### ISSUE THREAD

**Issue by basti19850429** [nextcloud/bookmarks#934]
Moin, ich habe meine komplette Nextcloud gekillt. Habe aber regelmäßig das Programmverzeichnis von Nextcloud gesichert. Gibt es eine Möglichkeit die Daten so wieder herzustellen ?

**Comment by marcelklehr** [comment]
Moin,

die Daten der Bookmarks app liegen in der datenbank, von der du hoffentlich auch ein backup hast.

**Comment by basti19850429** [comment]
Ich habe eine "nextcloud-db.sql"  ca 82 MB groß das wird sie wohl sein
