### ISSUE TITLE
Application crash on Android 7.1

### ISSUE THREAD

**Issue by apiraino** [nextcloud/bookmarks#939]
Hi,

since a couple of days the mobile App crashes on startup. Can't say what's exactly causing this. I have upgraded to NextCloud 18 but also added more bookmarks. Used to work flawlessy until now.

No useful error found in logs (either nextcloud.log, php logs, apache log). All I can see is that the client dies after receiving this response:

```
[13/Mar/2020:16:49:58 +0100] "GET /index.php/apps/bookmarks/public/rest/v2/bookmark?page=-1 HTTP/1.1" 200 1166508...."
```
I've also tried to clear the local cache and login again.

Any suggestion on how to debug this and provide more useful help? Unfortunately I don't have time to triage by bisecting the bookmarks DB table ...

Anyway, thanks.

**Comment by marcelklehr** [comment]
This is the repository of the app for nextcloud server. Please file an issue with the android app repo https://gitlab.com/bisada/OCBookmarks

**Comment by apiraino** [comment]
I'm sorry :man_facepalming:
