### ISSUE TITLE
Fehler bei Installation | Error during installation

### ISSUE THREAD

**Issue by HassanMullah** [nextcloud/bookmarks#940]
![Bild-2020-03-13-034](https://user-images.githubusercontent.com/4198497/76648788-a56e7700-655f-11ea-8b45-87792bb74e7d.jpg)
Hallo, ich habe gerade das Nextcloud Update auf 18.0.2 durchgeführt und habe da erst die App Bookmarks gesehen. Leider bekomme ich folgende Fehlermeldung.

Hi, I just did the Nextcloud update to 18.0.2 and just saw the App Bookmarks. Unfortunately I get the following error message.

`An exception occurred while executing 'CREATE TABLE oc_bookmarks_tags (bookmark_id BIGINT DEFAULT NULL, tag VARCHAR(255) DEFAULT '' NOT NULL, UNIQUE INDEX bookmark_tag (bookmark_id, tag)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

Vermutlich was mit der Datenbank, aber was muss ich da genau machen?

Probably something with the database, but what exactly do I need to do there?

**Comment by marcelklehr** [comment]
You're using utf8mb4 which quadruples the column size for text columns, so now your max key length is too short. Google helps: https://help.nextcloud.com/t/solved-syntax-error-or-access-violation-1071-specified-key-was-too-long-max-key-length-is-767-bytes/34740 :)
