### ISSUE TITLE
NC Settings fails after update

### ISSUE THREAD

**Issue by githubgoucho** [nextcloud/bookmarks#959]
NC V13 php 5.x

NC-Log:

{"reqId":"vJsbIvvqoGN6mbAacHXH","level":3,"time":"2020-04-02T14:04:42+00:00","remoteAddr":"-------------","user":"xxxxxxxxxx","app":"index","method":"GET","url":"\/index.php\/settings\/user","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/usr\\\/www\\\/users\\\/xxxxxxx\\\/cloud\\\/apps\\\/bookmarks\\\/settings\\\/adminsection.php\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/www\\\/users\\\/xxxxxx\\\/cloud\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/usr\\\/www\\\/users\\\/...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Bookmarks\\\\\\\\S...')\\n#2 [internal function]
.....
\\\/autoloader.php\",\"Line\":134}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"13.0.11.1"}

**Comment by marcelklehr** [comment]
Which version is this? (The issue template is there for a reason ;) )

> php 5.x

PHP 5 is not supported. Also, the earliest nc version that I test with regularly is nc 14, which still doesn't work with the latest code.
