### ISSUE TITLE
Suggestion: make it easier to close Details Menu

### ISSUE THREAD

**Issue by sunjam** [nextcloud/bookmarks#974]
Rather than clicking the  small `X` to close, how about just closing the Details Menu by clicking most anywhere above the bookmark title.
![Screenshot_20200416_120909](https://user-images.githubusercontent.com/1787238/79496890-ac176080-7fdb-11ea-9b2c-3b33e44f04c9.png)

**Comment by marcelklehr** [comment]
Note to self: Use a blur event emulation here. (i.e. clicking anywhere except the sidebar will close it).
