### ISSUE TITLE
Enhance bookmarks export

### ISSUE THREAD

**Issue by gibelium** [nextcloud/bookmarks#975]
It would be nice to be able to:
- adjust the file name for the exported bookmarks
- choose the folder on the file system where the export file should be stored

**Comment by sunjam** [comment]
It'd appreciate keeping the option to simply export and just directly download in the browser.  Seems this no longer possible in 3.0.5

**Comment by sunjam** [comment]
If there is a way, it would be awesome to automate `export bookmarks to html` with Cron or similar.  Totally okay without doing this with occ or even rsync on my bare metal server if it is possible.  Any simple method for ensuring there is a copy of my bookmarks is appreciated in case of catastrophic failure.

If everything gibelium requested happens, I'd be totally okay with automating the process of exporting bookmarks-copy37.html to the directory I've defined.  Having an additional copy every week or month in that folder would be awesome.

Just pie-in-the-sky thinking. :+1:

**Comment by marcelklehr** [comment]
I'll look into the issues with export soon.

@sunjam Once the export works again, you should be able to export your data at will using `GET /index.php/apps/bookmarks/public/rest/v2/bookmark/export` with Basic Auth, e.g. via curl.

**Comment by marcelklehr** [comment]
>
>    adjust the file name for the exported bookmarks
>    choose the folder on the file system where the export file should be stored

I'll be unlikely to implement both of these, as a) is possible in the file system already, and I think the current default is reasonable, and b) is a browser scope feature (which firefox for example has ;)).
