### ISSUE TITLE
Support right-click

### ISSUE THREAD

**Issue by gibelium** [nextcloud/bookmarks#977]
If the [Right-Click App](https://github.com/nextcloud/files_rightclick) is installed and enabled the context menu of bookmark folders and entries should be accessible via right-click too.

**Comment by marcelklehr** [comment]
Mmh, that'd be due to the right-click app not knowing about the bookmarks app. This is indeed confusing for uses. I doubt that the right-click app works with any other non-core apps, though.

We can leave this open for bookmarks to support right click by itself, though.
