### ISSUE TITLE
Nextcloud 18.0.3 + Bookmarks 3.0.0-beta.2 in this bunch php-fpm7.2 loads the CPU 100%

### ISSUE THREAD

**Issue by jefomin** [nextcloud/bookmarks#990]
Nextcloud 18.0.3 + Bookmarks 3.0.0-beta.2 in this bunch php-fpm7.2 loads the CPU 100%

![image](https://user-images.githubusercontent.com/39481287/80578353-ff90a200-8a10-11ea-9265-cd4ab0270eea.png)

Red load CPU
Green normal work

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - HTTP server: Server version: Apache/2.4.29 (Ubuntu) - Server built:   2020-03-13T12:26:16
 - Database: Server version: 10.1.44-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04
 - PHP version: PHP 7.4.5 (cli) (built: Apr 19 2020 07:36:30) ( NTS )
 - Nextcloud version: 18.0.3
 - Bookmarks app version:  3.0.0-beta.2

 - Activated Nextcloud Apps:  
$ Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - apporder: 0.9.0
  - breezedark: 18.0.13
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - drawio: 0.9.5
  - end_to_end_encryption: 1.4.0
  - extract: 1.2.4
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_automatedtagging: 1.8.2
  - files_clipboard: 0.7.1
  - files_external: 1.9.0
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - news: 14.1.5
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - passwords: 2020.4.1
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - qownnotesapi: 20.1.0
  - rainloop: 6.1.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.2
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - user_external: 0.9.1
  - viewer: 1.2.0
  - workflow_script: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - audioplayer
  - bookmarks
  - encryption
  - external
  - keeweb
  - richdocuments
  - spreed
  - user_ldap

 - Nextcloud configuration: 
 {
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.200.255.245",
            "nextcloud.almatey.kiev.ua"
        ],
        "default_language": "ru",
        "force_language": "ru",
        "force_locale": "ru_RU",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "app_install_overwrite": [
            "bookmarks_fulltextsearch",
            "files_clipboard"
        ],
        "overwritewebroot": "\/nextcloud",
        "htaccess.RewriteBase": {
            "\/nextcloud": ""
        },
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/10.200.0.254\/nextcloud",
        "overwritecondaddr": "^10\\.255\\.255\\.254$",
        "maintenance": false,
        "mysql.utf8mb4": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [
            "admin"
        ],
        "onlyoffice": {
            "verify_peer_off": true
        },
        "loglevel": "4",
        "app.mail.imaplog.enabled": true,
        "app.mail.smtplog.enabled": true,
        "app.mail.transport": "php-mail",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "openssl": {
            "config": "\/etc\/ssl\/openssl.cnf"
        },
        "cipher": "AES-256-CFB",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ]
    }
}

**Comment by jefomin** [comment]
in the process of php-fpm tracing, I see that it loops through directories with applications in a loop

**Comment by marcelklehr** [comment]
Mmh, I'm not sure why that would be, but there's a newer beta out already.

**Comment by jefomin** [comment]
Good! I will try to install

**Comment by jefomin** [comment]
I found a reason! This is a Floocus sync is reason load CPU

**Comment by marcelklehr** [comment]
Mmmh, do you have some kind of caching enabled? It shouldn't cause that much load with the new version of bookmarks anymore.

**Comment by jefomin** [comment]
Yes, I use cache for Nextcloud.  I updated to new beta version. And I see when start sync bookmarks with help Floocus increases the load on the CPU during synchronization. Anyway, thanks for the answer.

**Comment by mobamoba** [comment]
Same problem here (latest stable Nextcloud, Bookmarks, and Floccus). Renders system completely unusable - CPU at 100% and RAM eaten to the point where there's none left for anything else.
![image](https://user-images.githubusercontent.com/11135869/81007554-6eaa3400-8e1f-11ea-8a5b-9eda5747ce8e.png)
