### ISSUE TITLE
Sharing a folder in 3.0.0 not possible

### ISSUE THREAD

**Issue by gibelium** [nextcloud/bookmarks#992]
**Describe the bug**
It is not possible to share a folder as the list of people with whom I can share a folder stays empty, even when I type in some letters, a full username, email address or first name/last name combination. The spinner spins forever.

**To Reproduce**
1. Open Bookmarks App (clean install, never used in that instance)
2. Create a new folder
3. Go to Details and Share tab
4. Try to select a user (The list stays empty even when typing in a full username, email address or first name/last name combination)

**Expected behavior**
Share list should initially list all accounts with whom I can share a folder

**Desktop (please complete the following information):**
 - OS: Mac OSX Mojave
 - Chrome 81.0.4044.122
 - NC: 18.0.4
 - Bookmarks 3.0.0 final

**Web server error log**
No log entries

**Comment by marcelklehr** [comment]
Mmh, does nc run in a subdirectory for you?

**Comment by gibelium** [comment]
> Mmh, does nc run in a subdirectory for you?

This I need to check with the hoster of my production instance. I have no idea how they do run the nextcloud instances. What specific question could I ask them?

**Comment by marcelklehr** [comment]
You should be able to tell this from the URL. If your nextcloud URL is `domain.tld/nextcloud/` then it's a subdirectory as I was asking about. ;)

**Comment by gibelium** [comment]
Then it's not running in a subdirectory, just a subdomain...

**Comment by marcelklehr** [comment]
Ah, I've found the bug.
