### ISSUE TITLE
Auth error with API: Sync with Floccus stopped working with bookmarks 3

### ISSUE THREAD

**Issue by Jolopu** [nextcloud/bookmarks#994]
**Describe the bug**
Today I updated bookmarks in my NC installation to 3.0.2 and now on all of my computers I get an sync error in floccus on firefox. Error Code: E018 Authentification failed. I deleted my floccus account set up a new one but same error. I had no issues until updating to bookmarks 3 so I don't think it's on my side.

By the way, thanks for the work on that great app!!

**To Reproduce**
1. Update to Bookmarks 3.0.2
2. Sync with Floccus extension on Firefox

**Expected behavior**
Sync should be ok.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS X Catalina
 - Browser Firefox
 - Version 75

**Server (please complete the following information):**
 - OS: linux shared hosting
 - HTTP server: nginx
 - Database MySQL 5.3
 - PHP version: 7.3.11
 - Nextcloud version: 18.0.4
 - Bookmarks app version: 3.0.2

**Comment by autrui** [comment]
Since the update from Bookmarks v3.0.0 to v3.0.2 the error messages in the Nextcloud log have changed to this:

>**Exception: Call to undefined method OCA\Bookmarks\Service\Authorizer::userId()**
	domain.tld/lib/private/AppFramework/App.php - line 125:
	OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... {}, "hashFolder")
	domain.tld/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:
	OC\AppFramework\App::main("OCA\\Bookma ... r", "hashFolder", OC\AppFramew ... {}, { folderId: ... "})
	<<closure>>
	OC\AppFramework\Routing\RouteActionHandler->__invoke({ folderId: ... "})
	domain.tld/lib/private/Route/Router.php - line 299:
	call_user_func(OC\AppFramew ... {}, { folderId: ... "})
	domain.tld/lib/base.php - line 1008:
	OC\Route\Router->match("/apps/bookm ... h")
	domain.tld/index.php - line 38:
	OC::handleRequest()
>
>	**Caused By Error: Call to undefined method OCA\Bookmarks\Service\Authorizer::userId()**
	domain.tld/lib/private/AppFramework/Http/Dispatcher.php - line 170:
	OCA\Bookmarks\Controller\FoldersController->hashFolder(1, [ "title","url"])
	domain.tld/lib/private/AppFramework/Http/Dispatcher.php - line 99:
	OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... {}, "hashFolder")
	domain.tld/lib/private/AppFramework/App.php - line 125:
	OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... {}, "hashFolder")
	domain.tld/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:
	OC\AppFramework\App::main("OCA\\Bookma ... r", "hashFolder", OC\AppFramew ... {}, { folderId: ... "})
	<<closure>>
	OC\AppFramework\Routing\RouteActionHandler->__invoke({ folderId: ... "})
	domain.tld/lib/private/Route/Router.php - line 299:
	call_user_func(OC\AppFramew ... {}, { folderId: ... "})
	domain.tld/lib/base.php - line 1008:
	OC\Route\Router->match("/apps/bookm ... h")
	domain.tld/index.php - line 38:
	OC::handleRequest()`

**Comment by marcelklehr** [comment]
Next patch is out now. :see_no_evil:

**Comment by Jolopu** [comment]
With 3.0.3 I get this in the NC log:
Error: TypeError: Argument 3 passed to OC\AppFramework\Middleware\MiddlewareDispatcher::beforeOutput() must be of the type string, null given, called in /home/www/cloud.tv/lib/private/AppFramework/Http/Dispatcher.php on line 123

0. /home/www/cloud.tv/lib/private/AppFramework/Http/Dispatcher.php line 123
   OC\AppFramework\Middleware\MiddlewareDispatcher->beforeOutput(OCA\Bookmarks\Co ... {}, "getBookmarkFavicon", null)
1. /home/www/cloud.tv/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmarks\Co ... {}, "getBookmarkFavicon")
2. /home/www/cloud.tv/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Bookmarks\ ... r", "getBookmarkFavicon", OC\AppFramework\ ... {}, {id: "2",_route: ... "})
3. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({id: "2",_route: ... "})
4. /home/www/cloud.tv/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {id: "2",_route: ... "})
5. /home/www/cloud.tv/lib/base.php line 1008
   OC\Route\Router->match("/apps/bookmarks/bookmark/2/favicon")
6. /home/www/cloud.tv/index.php line 38
   OC::handleRequest()

**Comment by gibelium** [comment]
**I have a different sync error here:**
```
2020-05-01T06:51:01.095Z Starting sync process for account [EMAIL-ADDRESS]@grojekt.webo.family
2020-05-01T06:51:01.118Z Using normal strategy
2020-05-01T06:51:01.808Z Fetching bookmarks
2020-05-01T06:51:02.195Z Received bookmarks from server [   - #2199[Grojekt](https://grojekt.webo.family/) parentId: 410,
    - #2198[Google](https://google.de/) parentId: -1 ]
2020-05-01T06:51:02.583Z Received initial folders from server (may be incomplete) [ { id: 409,
    title: 'Grojekt',
    userId: '[EMAIL-ADDRESS]',
    children: [ [Object] ] } ]
2020-05-01T06:51:03.162Z Received initial children order from server (may be incomplete) [ { type: 'bookmark', id: 1088 },
  { type: 'bookmark', id: 2191 },
  { type: 'bookmark', id: 2193 },
  { type: 'bookmark', id: 2198 },
  { type: 'folder', id: 409, children: [ [Object] ] } ]
2020-05-01T06:51:03.163Z [Error: E022: Folder #-1[undefined] supposedly contains non-existent bookmark 1088]
2020-05-01T06:51:03.163Z Syncing failed with E022: Folder #-1[undefined] supposedly contains non-existent bookmark 1088
```

I guess this came up because I shared a folder as non-editable with a specific user and deleted the folder without un-sharing before. This led to the fact that the user I shared the folder with still sees that folder but it does not exist anymore. Removing shares when deleting a folder seems to be another issue and perhaps is the root cause of the floccus sync failure.

I need to do some more tests to find the steps to reproduce but I guess I need to clean up the database beforehand as it seems to be in an inconsistent state now.

@marcelklehr what SQL statement do I need to run to clean all bookmark and related share entries from the database? Or are there any other options?

**Comment by autrui** [comment]
@marcelklehr thanks. Log features no new errors now (3.0.3). Haven't tested sharing yet though.
Really like the app, great job.

**Comment by AndreasPantle** [comment]
For me the problem was not solved. I'm using Bookmarks 3.0.5 and floccus 4.1.0. Still get the authentication error: Syncing failed with E018: Authentifizierung fehlgeschlagen.

**Comment by Jolopu** [comment]
@AndreasPantle 
I can confirm this. I did a fresh install of 3.0.5 after deleting all bookmark database tables and still "E018: Authentifizierung fehlgeschlagen" comes up in floccus. I downgraded to bookmarks 2.3.4 and everything works fine again.

**Comment by Klaus15** [comment]
@Jolopu 
Same for me, auth not working anymore; disabled and removed bookmarks app in nextcloud, truncated mysql-tables and also getting E018:Authentifizierung fehlgeschlagen". Version is 3.0.5

**Comment by AndreasPantle** [comment]
Could it be a problem of the Two Factor Auth?

**Comment by Klaus15** [comment]
@AndreasPantle It's activated on my instance...might be the reason

**Comment by berfito** [comment]
In my Nextcloud instance I have the same problem. I already tried removing and reinstalling the app, removing the TOTP and trying the downgrade (which failed because apparently Bookmarks version 3 removes columns from the oc_bookmarks_folder table) and nothing worked. When reviewing the logs, I noticed that Floccus tries to access the following url:

https: //<nextcloud instance>/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300

I tried to enter from the browser, where I was asked for access credentials. However, these do not work. When you cancel, this message is displayed:

{"status": "error", "data": "Unauthorized"}

**Comment by marcelklehr** [comment]
Any common server setups, like nginx, docker, php-fpm?

**Comment by berfito** [comment]
Hello @marcelklehr 

My instance is running Apache 2.4 (behind the Nginx 1.17 reverse proxy), based on an image from the Nextcloud docker created by me and the official Nginx image. The PHP version is 7.3 and the database is PostgreSQL 11.7.

I hope this information is helpful to you.

**Comment by Klaus15** [comment]
@marcelklehr 
I'm also behind a nginx proxy. I've done a quick search through the nginx logs.
I'm getting a [04/May/2020:10:46:24 +0200] "GET /ocl/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash HTTP/2.0" **400** 975 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 when I click on "synchronize"
When bookmarks-app was still working this looked like
"GET /ocl/index.php/apps/bookmarks/public/rest/v2/folder/40/childorder HTTP/2.0" **200** 1649 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36"

Difference is http 400 vs http 200. 
Please let me know if you need additional logs

**Comment by marcelklehr** [comment]
v3.0.8 tries to fix the Auth error.

**Comment by Klaus15** [comment]
@marcelklehr 
I don't see version 3.0.8 updatable yet in my instance. Is there a way to manually trigger this?

**Comment by Klaus15** [comment]
@marcelklehr 
ok, it's there now. I've updated but unfortunately still no luck (E018).
Tried it with a new TOTP user as well as with my normal user.
[04/May/2020:18:09:25 +0200] "GET /ocl/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash HTTP/2.0" **400 980** "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"

[04/May/2020:18:09:26 +0200] "GET /ocl/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300 HTTP/2.0" **401 1017** "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"

**Comment by berfito** [comment]
@marcelklehr I confirm that the problem persists with version 3.0.8 (E018: Couldn't authenticate with the server). I have TOTP activated.

The log entries that appear when trying to sync with Floccus are these:

"GET /index.php/apps/bookmarks/public/rest/v2/folder/-1/hash HTTP/1.0" 400 1284 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
"GET /index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300 HTTP/1.0" 401 1326 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"

**Comment by marcelklehr** [comment]
Are you using a normal username or an email address to authenticate?

**Comment by berfito** [comment]
@marcelklehr I'm using a normal username

**Comment by gibelium** [comment]
> Are you folks using a normal username or an email address to authenticate?

Email addresses...

**Comment by selfisch** [comment]
same here
- normale username
- behing nginx
- valid https
- no 2fa

Login via webui works fine and nextcloud passwords app also works fine.

**Comment by Jolopu** [comment]
Still "E018: Authentifizierung fehlgeschlagen" with 3.0.10

Normal username (no email address)
shared hosting with apache
login to NC works normally
mysql 5.7.30
php 7.3.11
let's encrypt https
no 2fa

Hope that helps!

**Comment by marcelklehr** [comment]
So, it's not the username, it's not the reverse proxy. Can you folks provide the nextcloud version, the floccus version, the PHP version?

**Comment by Klaus15** [comment]
@marcelklehr 
- php 7.2.24
- floccus 4.1.0 (chrome)
- nextcloud 18.0.4

**Comment by berfito** [comment]
@marcelklehr 

- PHP 7.3.14 (Debian buster)
- Nextcloud 18.0.4
- Floccus 4.1.0 (Chrome)

**Comment by Jolopu** [comment]
@marcelklehr 

- PHP 7.3.11
- Nextcloud 18.0.4
- Floccus 4.1.0 (Firefox on Mac OS Catalina)

**Comment by marcelklehr** [comment]
Would somebody be willing to debug this with me live e.g. via chat? Ideally you'd have ssh access to the server.

**Comment by Klaus15** [comment]
@marcelklehr 
ok, how? :)

**Comment by marcelklehr** [comment]
Thanks to a quick debugging session with @berfito (:pray:) I have identified the problem. v3.0.11 (ooph, already?) is now available with the fix.

**Comment by afaik4711** [comment]
Finaly! :)
Thank you @marcelklehr and @berfito !
As stated in gitter, you have to delete the floccus accout and recreate it. Otherwise the E018 error will persist!
I'm so happy now

**Comment by Klaus15** [comment]
@marcelklehr 
you're the best :) After creating a new user/pw via TOTP everything is up an running again
Thanks!

**Comment by AndreasPantle** [comment]
From my side it is working too. Thank you very much!

**Comment by uriel198** [comment]
I'm doing something wrong here :( 

Error: E019: HTTP status 500. Failed POST request. Check your server configuration and log.]

Can someone help me with this one?

Regards

**Comment by uriel198** [comment]
OK, nevermind It's working on firefox ;) so i need to deal with chrome ;)
