### ISSUE TITLE
Column index already exists.

### ISSUE THREAD

**Issue by muppeth** [nextcloud/bookmarks#995]
Updating Bookmarks from 3.0.0 to 3.0.X results in:
`The column 'index' on table 'oc_bookmarks_folders_bookmarks' already exists.`

Any idea how to force update or generally why is it complaining about the table?

**Comment by marcelklehr** [comment]
Mmmh, it seems that it's trying to run a migration that has already been run: [Version000014000Date20181029094721](https://github.com/nextcloud/bookmarks/blob/master/lib/Migration/Version000014000Date20181029094721.php)

You may be able to fiddle around with the oc_migrations table to add that migration to the list of completed migrations.

**Comment by ghmrj** [comment]
Just working on a similar issue, maybe my findings are helpful: above error message came up on my setup after the first update attempt failed with
`Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_bookmarks_tree` (`id`, `type`, `parent_folder`, `index`) VALUES(?, ?, ?, ?)' with params ["401", "bookmark", "69", "110"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '401-bookmark-69' for key 'PRIMARY'`

Have tried to manually update from 2.3.4 then and deleted/reinstalled bookmarks. From then on I was stuck at that message until installing 2.3.4 again, restoring the oc_migrations content and re-enabling 2.3.4... Now not sure if I want to try this again...

**Comment by marcelklehr** [comment]
@ghmrj ooph, that's another db inconsistency: Apprently, someone managed to put the same bookmark id into a folder twice. You should be able to check for those entries with the following query:

```sql
SELECT folder_id, bookmark_id, COUNT(*) FROM oc_bookmarks_folders_bookmarks;
```

**Comment by marcelklehr** [comment]
@muppeth Is it possible that you uninstalled the app and then added in some backed up bookmarks tables without accounting for the oc_migrations table?

**Comment by muppeth** [comment]
@marcelklehr I get version: `000014000Date20181002094721` in my db. I havent uninstalled, but I did have some general issues after updating nextcloud to 18.04. Shall I just replace the version in the table or add another entry instead?

**Comment by marcelklehr** [comment]
The migrations are named after the release version, so 000014000 would indicate that your last installed version is v0.14, which is probably wrong.

After successfully installing v3.x it should look like this:

```
MariaDB [nextcloud]> select * from oc_migrations where app = 'bookmarks';
+-----------+-----------------------------+
| app       | version                     |
+-----------+-----------------------------+
| bookmarks | 000014000Date20181002094721 |
| bookmarks | 000014000Date20181029094721 |
| bookmarks | 000016005Date20190402094721 |
| bookmarks | 001000007Date20190721094721 |
| bookmarks | 003000000Date20191123094721 |
| bookmarks | 003000000Date20191129094721 |
+-----------+-----------------------------+
6 rows in set (0.00 sec)
```

If you have been using v2.3.4 successfully, you could try adding all rows except the v3 migrations and see if the update works.

**Comment by muppeth** [comment]
@marcelklehr thanks for the info. It's so weird that I only have this one single item:
```
+-----------+-----------------------------+
| app       | version                     |
+-----------+-----------------------------+
| bookmarks | 000014000Date20181002094721 |
+-----------+-----------------------------+
```
I will start adding them one by one and see what happens.

**Comment by muppeth** [comment]
@marcelklehr Looks like adding missing `000016005Date20190402094721` did the trick. Afterwards bookmarks has been enabled and all migrations added in the table. 
Thanks a lot for pointing me in right direction (learned something new about nextcloud). Still puzzled why this happened, but nonetheless, happy its solved (had quite few upset people about this). 

Thanks a lot!

**Comment by muppeth** [comment]
Weidly enough I have lost all bookmakrs in the db. Good I have backup

**Comment by muppeth** [comment]
@marcelklehr is it normal that disabling bookmarks also wipes the tables from the database? I did not experienced that with other apps.

**Comment by marcelklehr** [comment]
That should only happen on uninstall :/

**Comment by muppeth** [comment]
Nope. Tested with a friend and it does it on disable too.

**Comment by marcelklehr** [comment]
Ooph. Then I'll remove that repair step again :( The docs fooled me there.

**Comment by muppeth** [comment]
@marcelklehr after restoring tables, things seem to work except that "All bookmarks" shows nothing and one needs to select a folder to see bookmarks. I see my db backup had only those tables: 
`oc_bookmarks, oc_bookmarks_folders, oc_bookmarks_folders_bookmarks, oc_bookmarks_tags` while the new db now has: `oc_bookmarks, oc_bookmarks_folders, oc_bookmarks_folders_bookmarks, oc_bookmarks_folders_public, oc_bookmarks_root_folders, oc_bookmarks_shared_folders,| oc_bookmarks_shares, oc_bookmarks_tags,| oc_bookmarks_tree`
Sorry to bother all the time, but any idea whats going on? Is there a way/query to restore **"All bookmarks"** view?

**Comment by marcelklehr** [comment]
I can reproduce that on my own instance. I'll try to find out what's wrong.

**Comment by marcelklehr** [comment]
So, `oc_bookmarks_tree` is a new table in v3 and the relevant migration *should* have created entries for bookmarks that are in the root folder.

The following query should show those that have not made it.

```sql
SELECT * from oc_bookmarks b LEFT JOIN oc_bookmarks_tree t ON b.id = t.id WHERE t.id IS NULL and t.type = 'bookmark';
```

**Comment by muppeth** [comment]
That would be all of them, apart from few which most probably were added after I re-enabled the app.
Also noticed that export/import gives 500 error (`parentFolder is not a valid attribute`). Looks like the whole app got totally messed up.

**Comment by marcelklehr** [comment]
@muppeth Feel free to join me in the chat to sort this out more quickly :) https://gitter.im/nextcloud-bookmarks/community

**Comment by marcelklehr** [comment]
> That would be all of them

'All of them' as in all bookmarks even the ones in subfolders, or all bookmarks that were missing in the root folder(s)?
