### ISSUE TITLE
Exporting bookmarks exports folder without title

### ISSUE THREAD

**Issue by gibelium** [nextcloud/bookmarks#996]
**Describe the bug**
When importing bookmarks a folder named "Imported bookmarks" is created. The first child of that folder is an unnamed folder which contains the imported bookmarks structure.

**To Reproduce**
1. Import bookmarks
2. Check the content of the created "Imported bookmarks" folder
3. See that the structure is: 'Imported bookmarks/[unnamed-folder]/[imported-content]'

**Expected behavior**
An import should create the 'Imported bookmarks' folder which should contain the content of the import. The unnamed folder should not be created. 

**Desktop (please complete the following information):**
 - OS: MacOS X Mojave
 - Browser: Chrome 81.0.4044.122
 - NC: 18.0.4
 - Bookmarks: 3.0.3

**Comment by marcelklehr** [comment]
That may actually depend on the structure of the file you imported.

**Comment by gibelium** [comment]
I imported a file that I exported via Bookmarks App a minute before.

**Comment by marcelklehr** [comment]
Then that's the problem. The root folder of the bookmarks app has an empty title.

**Comment by gibelium** [comment]
Could we probably ignore empty root while importing?

**Comment by marcelklehr** [comment]
We should find a good default here, that is consistent across import and export, so that import and export is usable together, as well as consistent with how browsers handle this. Could you try to find out how browsers behave on import and export regarding the root folder of the imported file / the selected folder to export?

**Comment by marcelklehr** [comment]
Exporting a folder now doesn't include the selected folder.
