### ISSUE TITLE
Deleting a shared folder does not remove shares

### ISSUE THREAD

**Issue by gibelium** [nextcloud/bookmarks#997]
**Describe the bug**
When A shares a folder with B and A deletes the folder without removing the share entry B will see the shared folder that no longer exists.

**To Reproduce**
1. Create a folder as user A
2. Share the folder with user B
3. Delete the shared folder as user A
4. See that user B still sees the shared folder that no longer exists

**Expected behavior**
Deleting a shared folder should remove all share entries as well.

**Desktop (please complete the following information):**
- OS: MacOS X Mojave
- Browser: Chrome 81.0.4044.122
- NC: 18.0.4
- Bookmarks: 3.0.3

**Comment by marcelklehr** [comment]
https://github.com/nextcloud/bookmarks/releases/tag/v3.0.4
